- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
If expression.sql() throws a recursion error and we're given a string to begin with, we should return that string as-is instead of throwing an error.
> feat(ingest): make query formatting more robust

- metadata-ingestion/src/datahub/api/entities/forms/forms.py
Accept an optional `actors` input into the forms yaml API so that you can explicitly assign forms to users or groups.
> feat(cli) Add actors to forms yaml API

- docs/glossary/business-glossary.md
> doc(glossary): add note for github action for glossary

- metadata-ingestion/examples/data_product/dataproduct.yaml
- metadata-ingestion/src/datahub/api/entities/dataproduct/dataproduct.py
> feat(cli/data product): add support for institutional memory

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_plugin_v22.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/lineage/_lineage_core.py
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_basic_iolets.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_simple_dag.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_basic_iolets.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_basic_iolets_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_simple_dag.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_simple_dag_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_snowflake_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
- metadata-ingestion-modules/airflow-plugin/tests/unit/test_airflow.py
- metadata-ingestion/src/datahub/api/entities/datajob/datajob.py
- metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py
This would cause it to not be respected for data process instances. Also fixes a bug from https://github.com/datahub-project/datahub/pull/10421.
> feat(ingest/airflow): fix materialize_iolets bug

- metadata-ingestion/scripts/docgen.py
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_summary.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
- metadata-ingestion/src/datahub/ingestion/source_config/usage/snowflake_usage.py
> feat(ingest): add snowflake-summary source

- docs/api/tutorials/structured-properties.md
Fix broken examples after documentation refactor for structured properties openapi example.
> fix(docs): structured properties openapi guide

- datahub-graphql-core/src/main/resources/assertions.graphql
- datahub-graphql-core/src/main/resources/entity.graphql
- metadata-models/src/main/pegasus/com/linkedin/assertion/FreshnessAssertionSchedule.pdl
- metadata-models/src/main/pegasus/com/linkedin/common/CronSchedule.pdl
> fix(metadata-models) bridge gaps between graphql and pegasus models

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
Fix for openapi v3 spec:
- Make aspect ref inside entity schemas as nullable fields
> Aspect refs inside entity schema are nullable

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/unit/test_redshift_lineage.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/10619. In reality, it's not a full regression but rather an existing bug that the above PR exposed.
Also improves memory usage, which should help with https://github.com/datahub-project/datahub/issues/10435.
Also bumps avro-gen3, which should improve the performance of the codegen'd classes a bit.
> fix(ingest): fix redshift query urns + reduce memory usage

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/OperationsController.java
The subtle error there is that the system operation’s authorizer is only good for the system user. It doesn’t handle non-system user stuff (basically a you are system or not)
> fix(operations): fix authorizer on operations controller

- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/tests/integration/kafka-connect/docker-compose.override.yml
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_bigquery_sink_mces_golden.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_bigquery_sink_to_file.yml
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_to_file.yml
- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
> fix(ingest/kafka-connect): Add lineage extraction for BigQuery Sink Connector in Kafka Connect source

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
Related to this issue: https://github.com/datahub-project/datahub/issues/10505
We found that enabling the flag `ELASTICSEARCH_QUERY_EXACT_MATCH_EXCLUSIVE` resolved the problem where quoted search with `_` or `-` had no effect. However, enabling this flag broke structured queries tat had quotes (which are needed if the search string contains a space) due to the check that has been removed by this PR.
It seems that this logic isn't intended and was just an artifact of modeling the function `getStructuredQuery` after the `getSimpleQuery` function: https://github.com/datahub-project/datahub/blob/3a72d924936c60116740901c7b14406ab0050c9a/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java#L321
> fix(search): fixes issue where exact match exclusive flag broke quoted structured search

- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-service/openapi-servlet/models/build.gradle
- metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/exception/InvalidUrnException.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/GlobalControllerExceptionHandler.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
- metadata-service/openapi-servlet/src/test/java/mock/MockEntityService.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/EntityService.java
* Added flag to HEAD endpoint to consider (or not) soft deleted entities
* GET operations will no longer return default key aspects (instead 404)
* reflects whether the entity actually exists in the database
* better error messages on invalid urns
* refactor generic controller from models to servlet
> feat(openapi): openapi v3 updates

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-service/restli-api/src/main/idl/com.linkedin.entity.aspects.restspec.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
In my local test of emitting 1000 MCPs, it was approximately 7x faster to emit MCPs in batches of 100 instead of emitting one at a time.
This will need to be an opt-in mechanism in the rest sink until the backend GMS API has been released and stabilized. I have not built that yet.
> feat(gms): add ingestProposalBatch endpoint

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_summary.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/utilities/serialized_lru_cache.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/unit/test_serialized_lru_cache.py
~Stacked on https://github.com/datahub-project/datahub/pull/10642~
> feat(ingest/snowflake): refactor + parallel schema extraction

- metadata-ingestion/src/datahub/ingestion/graph/client.py
> Expose get_entities_v2 endpoint in python client

- metadata-ingestion/docs/transformer/dataset_transformer.md
Reading the documentation for [transformers](https://datahubproject.io/docs/metadata-ingestion/docs/transformer/dataset_transformer) there was a fair few formatting mistakes in the code blocks.
Some examples
- Bad Python formatting:
- Bad YAML formatting:
Might be worth adding some sort of tool for formatting markdown in the CI/CD pipeline (e.g. `pre-commit ci`)?
> fix(docs): formatting of transformers code blocks

- metadata-ingestion/src/datahub/ingestion/source/redash.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
> feat(ingest): log http request retries

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_helper.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/queries.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> feat(ingest/bigquery): Support for View Labels

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/AssertionRunEventMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionRunEventResolverTest.java
- datahub-web-react/src/graphql/assertion.graphql
> feat(observe) expose assertion runId and lastObservedMillis to graphql

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
Adds a `use_tables_list_query_v2` flag to the bigquery config.
> feat(ingest/bigquery): support using table read permission without profiling

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/10547
The tag key urns would previously interrupt the looker entity batches, which would cause the browse path v2 helper to generate bad browse paths. By relying on the tag materialization helper instead, we can avoid this problem.
> fix(ingest/looker): fix looker browse paths v2

- metadata-ingestion/src/datahub/cli/ingest_cli.py
> feat(cli): Make ingest deploy create recipe with urn if not exists

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
Previously we would require model/snapshot emission to be enabled for model performance to work. This removes that restriction.
> fix(ingest/dbt): support emitting only model performance

- datahub-frontend/conf/application.conf
- docker/datahub-gms/jetty.xml
> config(header): increase header size to 32k

- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_config.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
This PR adds a new configuration to the airflow plugin which allows captured ownership info to instead be applied as a corpgroup instead of a corpuser. 
We need this because we generally have groups own pipelines and datasets, not users, but it is still nice to have a user be part of the owning group.
I had difficulty testing this locally, getting unit test failures before making any changes. My hope is that CI can confirm that i have made no breaking changes.
> feat: allow task ownership as group

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
There seems to be a bug in logging_manager module.
Log levels look mixed up and debug off produces more verbose output than debug on.
In combination with known sqlalchemy logger issue that leads to huge(megabytes or dozens of megabytes)
logs in ingestion reports by default.
> fix(ingest/logging): fix excessive ingestion logging

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_basic_iolets.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_basic_iolets_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_simple_dag.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_simple_dag_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_snowflake_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator_no_dag_listener.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
> fix(ingestion/airflow-plugin): emit browsePathV2

- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MaeConsumerApplication.java
> fix(mae-consumer-job): add PE processor to component scan

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
> chore(alpine): update alpine base image

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
> fix(bigquery): use get() instead of hassattr for view labels

- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_common.py
- metadata-ingestion/tests/unit/test_iceberg.py
In a previous PR (#10614), I added support for future pyiceberg releases.  Part of this PR was to delegate the configuration of the catalog to pyiceberg, but the contributed code only supported dictionaries of string values.  It turns out that some pyiceberg configuration requires more than just strings, so this PR is opening up the configuration options to any value types.
Here is an example of a config that requires something else than a string (as found in [pyiceberg's configuration](https://py.iceberg.apache.org/configuration/)):
> fix(ingest/iceberg): add support for nested dictionaries when configuring pyiceberg

- docs/how/updating-datahub.md
- metadata-service/openapi-entity-servlet/src/test/java/io/datahubproject/openapi/config/OpenAPIEntityTestConfiguration.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/entities/EntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/relationships/RelationshipsController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/timeline/TimelineControllerV1.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/TimelineControllerV2.java
> feat(openapi): restore Timeline OpenAPIv1 and deprecations

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngineArgs.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/ReportAssertionResultResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/UpsertCustomAssertionResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/assertion/AssertionMapper.java
- datahub-graphql-core/src/main/resources/assertions.graphql
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/assertion/ReportAssertionResultResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/assertion/UpsertCustomAssertionResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/assertion/AssertionMapperTest.java
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-io/src/test/java/com/linkedin/metadata/service/AssertionServiceTest.java
- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MaeConsumerApplication.java
- metadata-models/src/main/pegasus/com/linkedin/assertion/AssertionInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/assertion/CustomAssertionInfo.pdl
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/assertions/AssertionServiceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/AssertionService.java
- smoke-test/tests/assertions/custom_assertions_test.py
> feat(data quality): custom assertions models, graphql, sdk

- docs/how/updating-datahub.md
- metadata-integration/java/datahub-protobuf/README.md
- metadata-integration/java/datahub-protobuf/build.gradle
- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/Proto2DataHub.java
- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/ProtobufDataset.java
- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/visitors/dataset/DatasetVisitor.java
- metadata-integration/java/datahub-protobuf/src/test/java/datahub/protobuf/visitors/dataset/DatasetVisitorTest.java
> feat(protobuf): disable binary protoc custom properties

- metadata-service/schema-registry-servlet/src/main/java/io/datahubproject/openapi/schema/registry/SchemaRegistryController.java
Enables compatibility with monitoring tools like https://github.com/provectus/kafka-ui
> feat(schema-registry): enable config endpoint internal schema registry

- metadata-ingestion/setup.py
This also fixes an infinite loop in sqlglot's scope builder. See https://github.com/hsheth2/sqlglot/commit/252fac18c53574f7f08ad9d106b53d4b7255580a.
> feat(ingest): bump sqlglot

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/Assertions.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionsList.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/contract/builder/DataContractBuilder.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/utils.tsx
- datahub-web-react/src/graphql/assertion.graphql
[Screencast from 27-06-24 09_13_35 PM IST.webm](https://github.com/datahub-project/datahub/assets/159848059/2510a1b5-0e82-4fab-a2bb-659ffe1f00be)
> fix(ui/data-contract): fix freshness & schema assertion is not working

- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
- metadata-ingestion/tests/integration/dbt/dbt_test_test_model_performance_golden.json
- metadata-ingestion/tests/integration/fivetran/fivetran_snowflake_empty_connection_user_golden.json
- metadata-ingestion/tests/integration/fivetran/fivetran_snowflake_golden.json
- metadata-ingestion/tests/integration/hive-metastore/docker-compose.yml
- metadata-ingestion/tests/integration/kafka-connect/docker-compose.override.yml
- metadata-ingestion/tests/integration/kafka/docker-compose.yml
- metadata-ingestion/tests/integration/trino/docker-compose.yml
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion_after_deleted.json
- metadata-models/src/main/resources/entity-registry.yml
Supersedes https://github.com/datahub-project/datahub/pull/10728
> fix(ingest): add status aspect to dataProcessInstance

- build.gradle
- metadata-integration/java/examples/build.gradle
> chore(gradle): remove httpclient 4 references

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/form/FormAssignmentHook.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/util/SearchBasedFormAssignmentManager.java
This PR adds the missing entities, which are currently not affected by the FormAssignmentHook. Technically all entities added here should support form assigments, because this was added in this [PR](https://github.com/datahub-project/datahub/pull/9801). Also the comment in the FormAssignmentHook itself was wrong, because technically only datasets are currently supported - as all entities with forms are supported by the hook now, I have also removed the corresponding comment.
Although (and I hope someone knows this) it seems there is missing a bit more "logic" around forms: It seems there is currently no hook (or other logic) which would assign forms to newly created entities (e.g., data products created via UI, but also in general e.g. during ingestion), once a form was assigned to an …
> fix(metadata-service): consider missing entities in form assignment hook

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/ermodelrelationship/CreateERModelRelationshipResolver.java
> fix(ERModelRelationship) UUID should mimic datahub_guid.py

- datahub-web-react/src/app/ingest/source/utils.ts
-  const URLPattern = new RegExp(/^(?:http(s)?:\/\/)?[\w.-]+(?:\.```[\w.-]+```)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+$/);
-  This part of the regular expression may cause exponential backtracking on strings starting with '-.' and containing many repetitions of '-.'.
- References of the Vulnerability and Weaknesses
- OWASP: [Regular expression Denial of Service - ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS).
- Common Weakness Enumeration: [CWE-1333](https://cwe.mitre.org/data/definitions/1333.html).
- Common Weakness Enumeration: [CWE-730](https://cwe.mitre.org/data/definitions/730.html).
- Common Weakness Enumeration: [CWE-400](https://cwe.mitre.org/data/definitions/400.html).
- The current expression `[\w.-]+` matches any combination of word characters …
> chore(vulnerability): Inefficient Regular Expression - Potential high time complexity leading to ReDoS 

- metadata-ingestion/examples/bootstrap_data/banking_business_glossary.yaml
- metadata-ingestion/examples/bootstrap_data/ecommerce_business_glossary.yaml
- metadata-ingestion/examples/bootstrap_data/healthcare_business_glossary.yaml
> docs(ingest): add business glossary examples

- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/FormInfoPatchBuilder.java
- metadata-integration/java/datahub-client/src/test/java/datahub/client/patch/PatchTest.java
- metadata-integration/java/examples/src/main/java/io/datahubproject/examples/FormCreate.java
- metadata-integration/java/examples/src/main/java/io/datahubproject/examples/FormUpdate.java
This PR adds a new Java patch builder for the Form entity on the FormInfo aspect. This also adds some examples for how to create or update forms using the Java SDK.
> feat(forms) Add java SDK for form entity PATCH + CRUD examples

- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/filter/RestliLoggingFilter.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-utils/src/main/java/com/linkedin/metadata/restli/NonExceptionHttpErrorResponse.java
- metadata-utils/src/main/java/com/linkedin/metadata/restli/RestliUtil.java
> fix(restli): log aspect-not-found as a warning rather than as an error

- smoke-test/tests/privileges/test_privileges.py
> fix(smoke-test): test access to create/revoke personal access tokens

- datahub-web-react/src/app/settings/SettingsPage.tsx
- datahub-web-react/src/app/settings/features/Feature.tsx
- datahub-web-react/src/app/settings/features/Features.tsx
- datahub-web-react/src/app/settings/features/useDocPropagationSettings.ts
- datahub-web-react/src/graphql/app.graphql
This PR adds a settings page to the UI for managing Documentation Propagation.
> feat(propagation): Add Documentation Propagation Settings

- docs-website/sidebars.js
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_profiling.py
> fix(ingest/databricks): Updating code to work with Databricks sdk 0.30

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_test_prefer_sql_parser_lineage_golden.json
- metadata-ingestion/tests/integration/dbt/test_dbt.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> feat(dbt): support prefer_sql_parser_lineage with sources enabled

- .github/actions/ci-optimization/action.yml
- .github/actions/docker-custom-build-and-push/action.yml
- .github/scripts/docker_helpers.sh
- .github/workflows/build-and-test.yml
- .github/workflows/docker-unified.yml
- .github/workflows/lint-actions.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-io.yml
- .github/workflows/metadata-model.yml
- .github/workflows/publish-datahub-jars.yml
- .github/workflows/spark-smoke-test.yml
- .github/workflows/test-results.yml
> feat(actions): updates to gha workflows

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-ingestion/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/kafka-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
> build: fix docker warnings

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/RestoreIndicesConfig.java
> lint(restore-indices): clean-up restore indices class

- .github/actions/docker-custom-build-and-push/action.yml
- .github/scripts/docker_helpers.sh
- .github/scripts/docker_logs.sh
- .github/workflows/docker-unified.yml
> fix(ci): additional ci and smoke-test updates

- smoke-test/tests/openapi/test_openapi.py
> test(smoke-test): minor update to openapi test

- docker/datahub-ingestion-base/Dockerfile
> feat(ingest): use pre-built dockerize binary

- docs/authorization/policies.md
- docs/authorization/roles.md
> doc: mark deprecated feature

- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImpl.java
- metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImplTest.java
> fix(ingest): invalid urn should not fail full batch of changes

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_dataproduct.py
> fix(ingestion/transformer): extend dataset_to_data_product_urns_pattern to support containers

- datahub-web-react/src/app/entity/shared/containers/profile/__tests__/EntityHeader.test.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
We don't want a feature flag for editing dataset names to be affecting the ability to edit other entity names (like glossary terms, domains, etc.). This should only affect editing dataset names.
> fix(ui) Fix bug with editing entity names

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
Fixes an NPE that was recently discovered if users/groups in form actor assignment are null.
> fix(graphql) Fix NPE on form actor assignemnt

- metadata-ingestion/setup.py
`StatementResponse` class imported by one of the tests was introduced to `databricks.sdk.service.sql` in `0.30.0`.
> fix(tests): Bump databricks-sdk dependency to `>=0.30.0`

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/FormUtils.java
Fixes a bug in the create form endpoint where we were setting the groups for actors assignments as the users.
> fix(forms) Fix small bug in createForm graphql endpoint

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/tests/integration/mongodb/mongodb_mces_golden.json
- metadata-ingestion/tests/integration/mongodb/mongodb_mces_small_schema_size_golden.json
> feat(ingest/mongodb): Ingest databases as containers

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift_schema.py
The `assert rows` lines would previously fail if rows=0.
> fix(ingest/redshift): avoid asserts in redshift schemas

- metadata-ingestion/docs/sources/dbt/dbt.md
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/tests/unit/test_mapping.py
> feat(ingest/dbt): add support for urns in add_owner directive

- metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
Also tweaks the logic to improve the way we detect temp tables based on the patterns when we have a table list present.
> fix(ingest/snowflake): propagate table list from main to query extractor

- metadata-ingestion/src/datahub/ingestion/graph/filters.py
After this https://github.com/datahub-project/datahub/pull/10814 for data flows and data jobs we have `env` stored which needed to be filtered for otherwise dataflows and datajobs won't come up when doing deletes. This fixes that problem.
The below gave zero results without this while UI was working due to lack of this filter
```
datahub delete by-filter --platform airflow --env PROD --dry-run
```
> fix(cli/delete): change filter to include env

- metadata-ingestion/src/datahub/ingestion/source/superset.py
Similar to https://github.com/datahub-project/datahub/pull/10005
> feat(ingest/superset): clickhousedb -> clickhouse mapping in superset ingestion

- metadata-ingestion/src/datahub/ingestion/source/confluent_schema_registry.py
> fix(ingest/kafka): update warning reporting for kafka

- .github/workflows/dagster-plugin.yml
- .github/workflows/docker-unified.yml
- .github/workflows/gx-plugin.yml
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/dagster-plugin/setup.py
- metadata-ingestion-modules/gx-plugin/setup.py
- metadata-ingestion/docs/sources/looker/lookml_pre.md
- metadata-ingestion/setup.py
- smoke-test/requirements.txt
> ci(build): update outdated action & pin deepdiff lib

- .github/workflows/airflow-plugin.yml
- .github/workflows/build-and-test.yml
- .github/workflows/check-datahub-jars.yml
- .github/workflows/code-checks.yml
- .github/workflows/dagster-plugin.yml
- .github/workflows/docker-unified.yml
- .github/workflows/documentation.yml
- .github/workflows/gx-plugin.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-io.yml
- .github/workflows/metadata-model.yml
- .github/workflows/publish-datahub-jars.yml
- .github/workflows/spark-smoke-test.yml
- metadata-ingestion/docs/sources/looker/lookml_pre.md
> ci: update outdated actions for java and python setup

- .github/actions/docker-custom-build-and-push/action.yml
- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
> ci(flavor):  reintroduce flavor suffix

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema_gen.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
Add clustering key (formula) as a property of a dataset in Snowflake. Some people
> feat(ingest/snowflake): Add cluster formula to dataset properties

- metadata-integration/java/openlineage-converter/build.gradle
Since the shadow jar doesn't have a classifier, specify one for the non-shadowJar. This prevents compilation errors in the project.
> fix(openlineage): fix jar conflict

- metadata-ingestion/src/datahub/ingestion/source/fivetran/config.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
Add ability for users to filter to only include specific destination IDs. This would let us exclude non-prod environments in our PROD DataHub deployment and speed up the ingestion (as its pretty slow given the 100s of connectors we have).
> feat(ingest/fivetran): support filtering on destination ids

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/LazyDataLoaderRegistry.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/SpringWebConfig.java
When using test/quickstart data locally a reduction in latency is significant however it will not impact all queries and may not be significant in other environments.
Before:
After:
> feat(graphql): Lazy dataLoaders

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
- avoid calling list projects multiple times using cachine at schema api perf level
- fix arg to set schema api perf report
- fix usage of `include_schema_metadata`
- add tests for use_queries_v2 schema ingestion
Pending:
- add tests for use_queries_v2 lineage and usage ingestion
> fix(bigquery): followups on bigquery queries v2 integration

- metadata-ingestion/src/datahub/api/entities/assertion/compiler_interface.py
- metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py
- metadata-ingestion/src/datahub/configuration/time_window_config.py
- metadata-ingestion/src/datahub/ingestion/glossary/datahub_classifier.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_query_model.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/constants.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py
- metadata-ingestion/src/datahub/testing/check_str_enum.py
- metadata-ingestion/src/datahub/utilities/str_enum.py
- metadata-ingestion/tests/performance/data_model.py
- metadata-ingestion/tests/unit/test_packages.py
This will help move us towards Python 3.11 compatibility.
> fix(ingest): add custom StrEnum type

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
> fix(api/timeline): fix corner cases missed, add tests

- smoke-test/build.gradle
- smoke-test/smoke.sh
- smoke-test/tests/cli/delete_cmd/test_timeseries_delete.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/11313
> fix(smoke): fix timeseries delete test's usage of `datahub get`

- metadata-ingestion/setup.py
This fixes an error in our error handling. Seeing such an error still indicates a formatting / data structure error, but now the errors should be more understandable.
See https://github.com/acryldata/avro_gen/pull/22
Closes https://github.com/datahub-project/datahub/issues/11273
> fix(py): fix issues with AvroException

- metadata-ingestion/src/datahub/cli/check_cli.py
- metadata-ingestion/src/datahub/cli/docker_cli.py
- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Also simplifies the `--no-default-report` handling.
> fix(ingest): disable reporting for dry-run pipelines

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
See https://datahubspace.slack.com/archives/CUMUWQU66/p1725608543705539
> fix(ingest): avoid sqlite "too many SQL variables" error

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/SearchFlagsInputMapper.java
- datahub-graphql-core/src/main/resources/search.graphql
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchRequestHandlerTest.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/query/SearchFlags.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
This PR aims to introduce a new feature to enable custom highlighting while searching via Datahub native graphql queries .
By default , Datahub graphql engine adds all searchable fields inside elastic search highlighter which adds  huge overhead if the search universe is large and have enriched description on column level . Because for each field mentioned in the highlighter , Elastic search reruns another in memory indexing per entity .
We have introduced a new field called **customHighlightingFields** where user can pass the fields which they want to highlight , we then only take these fields in to account for search highlighting . This features enables faster retrieval of data and offers customization . 
Please refer below on the usage -
**Highlight with Valid Field **
**Custom …
> Feature/custom highlight on search 

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/queries_extractor.py
This reverts change in queries extractor done by https://github.com/datahub-project/datahub/pull/11333.
This is due to inherent ordering support in FileBackedDict https://github.com/datahub-project/datahub/pull/11346.
Also adds few info logs to track ingestion progress, while no workunits are yet being generated.
> fix(ingest): followup on bigquery queries v2 ordering

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
Configurable with the `DATAHUB_REST_SINK_DEFAULT_MODE` env variable.
> feat(ingest): make default rest sink mode env-configurable

- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/Dockerfile
- metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/restli/RestliServletConfig.java
- metadata-service/auth-filter/src/main/java/com/datahub/auth/authentication/filter/AuthenticationFilter.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/OnBootApplicationListener.java
- metadata-service/factories/src/main/java/com/linkedin/restli/server/RAPServletFactory.java
- metadata-service/factories/src/main/java/com/linkedin/restli/server/RestliHandlerServlet.java
- metadata-service/war/src/main/java/com/linkedin/gms/WebApplicationInitializer.java
- metadata-service/war/src/main/java/com/linkedin/gms/servlet/RestliServletConfig.java
While updating to the latest executor code in actions, a GMS startup race condition is triggered by incomplete
initialization of the ebean framework during integration/smoke-tests.
This PR fixes the race condition by loading the class prior to starting the wait/bootstrap process during GMS startup. This allows AuthenticationFilter to handle requests which require interaction with SQL via the ebean library as the application is loading.
Notes:
In production environments running kubernetes the pod would not be expected to receive traffic before the health check is healthy and would avoid this condition.
> fix(XServiceProvider): fix ebean framework race condition

- docs/how/restore-indices.md
See https://github.com/acryldata/datahub-helm/pull/475.
> fix(docs): clarify clean-up of indices when restoring search and graph indices

- build.gradle
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocode/CreateAspectTableStep.java
- metadata-integration/java/acryl-spark-lineage/scripts/check_jar.sh
- metadata-integration/java/datahub-protobuf/scripts/check_jar.sh
- metadata-integration/java/spark-lineage-legacy/scripts/check_jar.sh
- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectV1.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectV2.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/ebean/EbeanAspectDaoTest.java
Upgrade ebean library from 12.x to 15.x
Fixes read lock NPE for postgres
Update gradle configuration for ebean
> fix(ebean): upgrade ebean library

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
Lineage for Iceberg tables isn't fully configured since this filter omits them
> fix(ingest/snowflake): Update snowflake_utils.py to account for iceberg tables

- docs/how/updating-datahub.md
- metadata-ingestion/sink_docs/datahub.md
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/utilities/partition_executor.py
- metadata-ingestion/tests/unit/test_pipeline.py
- metadata-ingestion/tests/unit/utilities/test_partition_executor.py
~Stacked on https://github.com/datahub-project/datahub/pull/11335~
- Adds a protection mechanism to prevent large batches from hitting GMS errors.
- Ensures that the BatchPartitionExecutor does not cause interpreter shutdown to stall.
> feat(ingest): default to ASYNC_BATCH mode in datahub-rest sink

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
> fix(ingest): override setdefault in file-backed dict

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AutocompleteRequestHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/CustomizedQueryHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/CustomizedQueryHandlerTest.java
> fix(customSearch): apply query string interpolation to function score

- metadata-ingestion/docs/sources/gc/gc_recipe.dhub.yml
- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
> feat(ingest/gc): Add dry run mode to gc recipe

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/structuredproperties/CreateStructuredPropertyResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/structuredproperties/UpdateStructuredPropertyResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/MapperUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/structuredproperty/StructuredPropertyMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/main/resources/properties.graphql
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/StructuredPropertyDefinitionPatchBuilder.java
- metadata-models/src/main/pegasus/com/linkedin/structured/StructuredPropertyDefinition.pdl
This adds the `created` and `lastModified` timestamps to the structured props definition aspect to track when this entity was created and last modified. Also, it adds a new graphql endpoint to explicitly get a structured property by urn.
> feat(structuredProps) Add created and lastModified timestamps to structured prop entity

- metadata-ingestion/src/datahub/ingestion/graph/client.py
> feat(ingest): add `get_entity_as_mcps` method to client

- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
We combine siblings in our main search results when the combine siblings flag is on, we should do the same to be consistent in our embedded list search results as well.
> fix(siblings) Combine siblings in embedded search results

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/structuredproperties/UpdateStructuredPropertyResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/structuredproperties/UpdateStructuredPropertyResolverTest.java
Fixes a bug where we were overwriting the allowed types value on a structured props type qualifier when providing `newAllowedTypes`. This breaks backwards compatibility as we should only be adding new types, never removing them.
This PR fixes that by fetching the existing allowed types if they exist and appending to them with what's provided in the update API.
> fix(structuredProps) Fix adding new allowed types in updateStructuredProp endpoint

- datahub-web-react/src/graphql/fragments.graphql
Way too hard for me to check every single place in the product that this query is used. Passes type check so hopefully our use of `any` typing doesn't bite us here.
> fix(graphql/getDataset): Do not fetch parent for schema fields

- gradle.properties
On my machine, this speeds up short-lived gradle commands significantly. E.g. ~ a minute -> a couple seconds. This makes gradle feel usable as a simple command runner.
> build: allow gradle daemon

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/tests/unit/test_dbt_source.py
Also fixes the algo for inferring metadata endpoints from access urls.
> fix(ingest/dbt): handle null index values

- docker/profiles/docker-compose.gms.yml
- docs/how/search.md
- metadata-io/src/test/java/com/linkedin/metadata/search/fixtures/SampleDataFixtureSetupTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/fixtures/SampleDataFixtureTestBase.java
- metadata-io/src/test/resources/search_config_fixture_test.yml
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/CustomSearchConfiguration.java
- metadata-service/configuration/src/main/resources/search_config.yaml
* Enable prefix phrase match on quoted search
* Fix documentation links
* Update docker configs with application.yaml default
* Add test to detect the expected behavior of prefix phrase match
* Add test to detect drift between application default and test fixture configs
> fix(search): restore prefix phrase match on quoted search

- datahub-web-react/src/app/lineage/LineageEntityEdge.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- datahub-web-react/src/app/lineage/LineageTree.tsx
- datahub-web-react/src/app/lineage/LineageTreeNodeAndEdgeRenderer.tsx
- datahub-web-react/src/app/lineage/LineageVizInsideZoom.tsx
- datahub-web-react/src/app/lineage/LineageVizRootSvg.tsx
- datahub-web-react/src/app/lineage/__tests__/LineageTree.test.tsx
- datahub-web-react/src/app/lineage/__tests__/adjustVXTreeLayout.test.tsx
- datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
- datahub-web-react/src/app/lineage/types.ts
- datahub-web-react/src/app/lineage/utils/__tests__/columnLineageUtils.test.tsx
- datahub-web-react/src/app/lineage/utils/__tests__/extendAsyncEntities.test.ts
- datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
- datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
- datahub-web-react/src/app/lineage/utils/constructTree.ts
- datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
- datahub-web-react/src/app/lineage/utils/useSortColumnsBySelectedField.ts
> refactor(ui/lineage): Replace FetchedEntities Object with Map

- .github/workflows/docker-unified.yml
We'd previously only see the docker logs from the last one to finish.
> chore: use unique docker log artifact names

- docs/how/restore-indices.md
I have just checked the documentation after my previous PR #11380 was merged...unfortunately I broke the layout (see: https://docs-website-1dvlu3ird-acryldata.vercel.app/docs/how/restore-indices/) , because I have forgot the closing colons in the Markdown...this PR is fixing this.
(I have not expected the previous PR to be merged that fast...I wanted to check the layout this morning to make sure everything is right...sorry! 😁)
> fix(docs): fix layout in documentation after #11380

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
1. Increases max scope limit for queries with many union statements
2. Makes detach_ctes a no-op if there is no cte_mapping, for clearer error handling
> fix(ingest/sqlglot): Make detach_ctes more robust

- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/integration/mode/test_mode.py
> fix(ingest/mode): add connection timeouts to avoid RemoteDisconnected errors

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/structuredproperties/UpsertStructuredPropertiesResolver.java
Most schema fields don't have their own urns yet in the database and structured properties are the first main aspect we're storing on them. This PR edits the `upsertStructuredProperties` endpoint to allow users to add a property to a schema field urn that doesn't exist yet. This way users will be able to add/remove properties on schema fields even if they weren't minted by some other way yet (other than forms or API, there is no other way as far as I know).
> fix(structuredProps) Allow upserting structured props on schema fields that don't exist

- docs-website/docusaurus.config.js
A number of our pages already look quite bad in dark mode. Better to avoid the bad experience by not letting people see that. Longer term, we can revert this back once dark mode looks reasonable.
> fix(docs-website): disable dark mode

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_prefer_sql_parser_lineage_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_test_model_performance_golden.json
- metadata-ingestion/tests/integration/dbt/test_dbt.py
Stacked on https://github.com/datahub-project/datahub/pull/11450
For dbt tests that depend on multiple underlying models (e.g. relationship tests), we previously would only produce one datahub assertion. The dataset that this assertion was associated with was not consistently defined (it used to be whatever model was last when alphabetically ordered - not sure why). This changes it so we produce multiple dataset assertions for the dbt test, one per dataset. While it's not strictly correct, the end user experience will make more sense. The assertions produced will have custom properties in case they need to be linked in the future.
> feat(ingest/dbt): produce multiple assertions for multi-table dbt tests

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_usage.py
Follow up on https://github.com/datahub-project/datahub/issues/10771
That PR updated most looker urns to use the platform instance when configured, but missed updating the usage code. This finishes the job by passing the urn builder function in as a parameter, so the urn construction logic only lives in one place.
It also refactors the Looker usage code to remove `cast` calls and overall be more readable.
> fix(ingest): include platform instance in looker usage urns

- docs-website/docusaurus.config.js
- docs-website/src/components/SecondNavbar/SecondNavbar.js
- docs-website/src/components/SecondNavbar/styles.module.scss
- docs-website/src/styles/global.scss
- docs-website/src/theme/Layout/index.js
- docs-website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Main changes : 
* added second navbar under /docs
* removed the version dropdown & searchbar & dark mode switch on the main navbar and move them into the second navbar
* added slack CTA on the main navbar
* modified the content under learn / community dropdown
> feat: add second navbar

- docs/dev-guides/timeline.md
- Adding documentation for modificationCategory
Based on : https://github.com/datahub-project/datahub/pull/11345
> fix(doc): Update the documentation for Timeline API

- metadata-ingestion-modules/dagster-plugin/examples/advanced_ops_jobs.py
- metadata-ingestion-modules/dagster-plugin/examples/assets_job.py
- metadata-ingestion-modules/dagster-plugin/examples/ops_job.py
Dagster function input/output values needs to be json serializable and therefore a string. The URN is a not serializable object. Function call returns the string representation.
> fix(dagster-plugin): Fix in/outs format and source config

- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
…mapping
fix issue where sub-properties in 'nested' type mappings are not detected during Elasticsearch ingestion, resulting in incomplete ingestion of data. Prior to this fix, only top-level properties were recognized, missing critical sub-fields.
Fixes: https://github.com/datahub-project/datahub/issues/10911
> fix(ingest/elasticsearch): detect sub-properties in 'nested' type mapping

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
> fix(ingest/looker) : Handle DeserializeError to improve error reporting.

- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/CustomDispatcherServlet.java
- metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/CustomDispatcherServlet.java
This PR adds two classes under mae-consumer and mce-consumer. These classes will take care of blocking HTTP TRACE method on both components. This is required because mae and mce makes use of embedded jetty which provided 200 response to http trace calls by default. This change will return proper method not allowed response with http code 405.
> Block http trace method on mce and mce consumers 

- metadata-ingestion/src/datahub/ingestion/source/sigma/sigma_api.py
- metadata-ingestion/tests/integration/sigma/test_sigma.py
Sigma introduced a breaking change in list members api about a month ago. - https://help.sigmacomputing.com/changelog#pagination-required-for-list-endpoints-breaking-change
This has started affecting instances recently.
> fix(ingest/sigma): handle members api paginated response

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
Fixes some issues around determination of description changes and pushes down ChangeCategory set behavior to reduce repeated execution.
> fix(changeGenerator): fix logic around descriptions and make execution more efficient

- metadata-models/src/main/pegasus/com/linkedin/common/SerializedValue.pdl
- metadata-models/src/main/pegasus/com/linkedin/platformresource/PlatformResourceInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/platformresource/PlatformResourceKey.pdl
- metadata-models/src/main/pegasus/com/linkedin/platformresource/PlatformResourceType.pdl
- metadata-models/src/main/resources/entity-registry.yml
> feat(models): add support for generic platform resources

- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
Without this doing a sync was removing any custom ownership type set in glossary
> fix(ingest): add typeUrn in glossary sync source

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/getFieldDescriptionDetails.ts
Current description UI deterministically chooses the first entry in the propagated array.
This PR changes that to always pick the latest propagated entry (by time).
> fix(propagation): show last modified propagated documentation

- docs/authorization/policies.md
- docs/how/updating-datahub.md
- metadata-auth/auth-api/src/main/java/com/datahub/authorization/AuthUtil.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/OperationsController.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/operations/OperationsResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/platform/PlatformResource.java
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
`MANAGE_SYSTEM_OPERATIONS` allows the following systems related privileges not otherwise directly use-able in the UI
RESTORE_INDICES_PRIVILEGE
ES_EXPLAIN_QUERY_PRIVILEGE
GET_ES_TASK_STATUS_PRIVILEGE
GET_TIMESERIES_INDEX_SIZES_PRIVILEGE
SET_WRITEABLE_PRIVILEGE
APPLY_RETENTION_PRIVILEGE
PRODUCE_PLATFORM_EVENT_PRIVILEGE
> privileges(refactor): consolidate individual sys op privileges

- docker/profiles/docker-compose.actions.yml
> feat(docker-profiles): add elasticsearch envs to docker profiles

- metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraAspectMigrationsDaoTest.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraEntityServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/cassandra/CassandraTimelineServiceTest.java
- metadata-io/src/test/resources/testng-cassandra.xml
- metadata-io/src/test/resources/testng-other.xml
- metadata-io/src/test/resources/testng.xml
Cassandra tests truncates data before each method which can cause issues when the test classes using Cassandra execute on different threads. This ensures the cassandra tests execute on a single thread.
```
metadata-io > nonsearch > com.linkedin.metadata.entity.CassandraEntityServiceTest > setupTest FAILED
java.lang.AssertionError: expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at com.linkedin.metadata.CassandraTestUtils.purgeData(CassandraTestUtils.java:128) …
```
> fix(ci): fix cassandra test flake

- .github/workflows/docker-unified.yml
> feat(scan): add scanning to setup images

- metadata-ingestion/docs/sources/datahub/datahub_pre.md
> docs(datahub source): Add urn exclusions to docs

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_queries_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_project_label_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
Add a way to reference existing DataHub Tag from a BigQuery label.
When we sync from DataHub to BigQuery, we encode the tags as modified base32 strings.
BiqQuery labels only support lowercase letters, international characters, numbers, or underscores.
So, we need to modify the base32 encoding to replace the padding character `=` with `_` and convert it to lowercase.
> feat(ingest/bigquery): Add way to reference existing DataHub Tag from a bigquery label

- metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardInfo.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
Open questions right now
- Do we want the field name to be `dashboards` or something more generic?
- Do we want to continue using the "Contains" relationship type, or use something new e.g. "Includes" to make these easy to distinguish in the future.
Will help unblock https://github.com/datahub-project/datahub/pull/11523
> feat(models): support dashboards containing dashboards

- metadata-ingestion/src/datahub/cli/config_utils.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
Stacked on https://github.com/datahub-project/datahub/pull/11562
> feat(ingest): support `__from_env__` special server value

- metadata-io/src/test/java/com/linkedin/metadata/entity/ebean/EbeanAspectDaoTest.java
> fix(test): Update EbeanAspectDaoTest.java

- metadata-io/src/main/java/com/linkedin/metadata/search/SearchService.java
- metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/v3/models/GenericEntityAspectsBodyV3.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
* added generic cross-entity scroll endpoint
> feat(openapi-v3): generic entities scroll

- metadata-ingestion/src/datahub/ingestion/source/sac/sac.py
- metadata-ingestion/src/datahub/ingestion/source/sac/sac_common.py
It is technically possible that the descriptions for Stories, Models and columns of Import Data models are None...this PR fixes the handling of such cases.
Additionally some more HTTP statuses will be retried (400 and 503) - unfortunately the Import Data API is a bit unstable and returns these HTTP status codes from time to time, although everything else is working.
FYI @hsheth2
> fix(ingest/sac): handle descriptions which are None correctly

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
- metadata-ingestion/tests/unit/test_mlflow_source.py
File count returned 0 earlier for this case. This is raising exception for `deltalake>=0.20.0` (Ref: https://github.com/delta-io/delta-rs/commit/ad35eda7983385c3011f8ae87afc24456791cd9e#diff-f81b8b91e9721dc0a3235b6674a57c0700153b92b59f3988d357950a9c8c4760)
- Also fixes mlflow lint error from CI
> fix(ingest/delta-lake): skip file count if require_files is false

- metadata-ingestion/src/datahub/ingestion/source/superset.py
parse postgres platform as postgres rather than postgresql when ingesting superset charts
> fix(ingest/superset): parse postgres platform correctly

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/IngestResult.java
Expose pre-existing features on aspect endpoints.
1. async ingestion (new param)
2. Create the aspect only if the entity doesn't exist (new param)
3. Create the aspect only if the aspect doesn't exist (exposed hidden param)
For now, maintaining backwards compatibility with `async=false` and `createIfNotExists=true` defaults.
> feat(openapi-v3): support async and createIfNotExists params on aspect

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_platform_resource_helper.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/common.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> feat(ingest/bigquery): Generate platform resource entities for BigQuery labels

- docker/build.gradle
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/docker-compose.prerequisites.yml
Similar to the normal `./gradlew quickstart`, support version override environment variable using `DATAHUB_VERSION` for `./gradlew quickstartDebug`.
For docker-compose compatible releases, the following is now possible to more easily run a previous release with the `debug` profile locally.
`DATAHUB_VERSION=v0.14.0.2 ./gradlew quickstartDebug`
This ability was already supported for `DATAHUB_VERSION=v0.14.0.2 ./gradlew quickstart` (non-debug) profile.
> feat(docker-profiles): allow version override for quickstartDebug

- docs/how/updating-datahub.md
- metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/client/dagster_generator.py
- metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/sensors/datahub_sensors.py
- metadata-ingestion/src/datahub/api/entities/dataproduct/dataproduct.py
- metadata-ingestion/src/datahub/ingestion/graph/config.py
- metadata-ingestion/src/datahub/ingestion/source/state_provider/datahub_ingestion_checkpointing_provider.py
- metadata-ingestion/tests/conftest.py
- metadata-ingestion/tests/integration/business-glossary/test_business_glossary.py
- metadata-ingestion/tests/test_helpers/state_helpers.py
- metadata-ingestion/tests/unit/graph/test_client.py
- metadata-ingestion/tests/unit/stateful_ingestion/state/test_redundant_run_skip_handler.py
- metadata-ingestion/tests/unit/stateful_ingestion/test_configs.py
- metadata-ingestion/tests/unit/test_glue_source.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
- smoke-test/pytest.ini
- smoke-test/tests/test_stateful_ingestion.py
~Stacked on https://github.com/datahub-project/datahub/pull/11569~
> fix(ingest): remove default value from DatahubClientConfig.server

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> fix(ingest/dbt): Prevent lineage cycles when parsing sql of dbt models

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
`_BASE_PROJECT_NAME` was moved to `lookml_config` in this PR https://github.com/datahub-project/datahub/pull/10542
Importing it from `lookml_source` is causing errors in environments where git is not present
> fix(ingest/looker): Remove bad imports from looker_common

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/tests/integration/looker/golden_looker_mces.json
- metadata-ingestion/tests/integration/looker/golden_test_allow_ingest.json
- metadata-ingestion/tests/integration/looker/golden_test_external_project_view_mces.json
- metadata-ingestion/tests/integration/looker/golden_test_file_path_ingest.json
- metadata-ingestion/tests/integration/looker/golden_test_folder_path_pattern_ingest.json
- metadata-ingestion/tests/integration/looker/golden_test_independent_look_ingest.json
- metadata-ingestion/tests/integration/looker/golden_test_ingest.json
- metadata-ingestion/tests/integration/looker/golden_test_ingest_joins.json
- metadata-ingestion/tests/integration/looker/golden_test_ingest_unaliased_joins.json
- metadata-ingestion/tests/integration/looker/golden_test_non_personal_independent_look.json
- metadata-ingestion/tests/integration/looker/looker_mces_golden_deleted_stateful.json
- metadata-ingestion/tests/integration/looker/looker_mces_usage_history.json
> feat(ingest/looker): include project name in model/explore properties

- metadata-ingestion/src/datahub/api/entities/platformresource/platform_resource.py
- metadata-ingestion/src/datahub/utilities/openapi_utils.py
- metadata-ingestion/src/datahub/utilities/search_utils.py
- metadata-ingestion/tests/unit/api/entities/platformresource/test_platform_resource.py
- metadata-ingestion/tests/unit/utilities/test_search_utils.py
- smoke-test/tests/platform_resources/test_platform_resource.py
- Improves the sdk support for platform resources
- Creates opportunities for other entities to support richer find-ability
- [Note] Breaks previous API for platform resource.search_by_filters (this shouldn't need an entry in the updating datahub list because we haven't cut a new release with the previous api)
> feat(sdk):platform-resource - complex queries

- metadata-ingestion/src/datahub/ingestion/source/fivetran/config.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
> feat(ingest/fivetran): add safeguards on table/column lineage

- datahub-web-react/src/app/ingest/source/builder/constants.ts
I saw in this PR (#11518) that for the datahub-gc source no platform logo is shown...we could show a DataHub Logo for all DataHub sources...;-)
SOURCE_TO_PLATFORM_URN and PLATFORM_URN_TO_LOGO are used by useGetSourceLogoUrl to return the logo URL: https://github.com/datahub-project/datahub/blob/6b09346ca554783906afd8901ba9f89e1ef7310d/datahub-web-react/src/app/ingest/source/builder/useGetSourceLogoUrl.ts#L9
The entry for vertica in SOURCE_TO_PLATFORM_URN is redundant and not needed, because the platform urn is already correct for vertica and has not be "translated"...
> fix(ui): show DataHub logo for DataHub sources in ingestion souces list

- metadata-ingestion-modules/prefect-plugin/src/prefect_datahub/datahub_emitter.py
asyncio.iscoroutine was unneded as it called an async function:
https://github.com/PrefectHQ/prefect/blob/afbed19d752b7057ccb2dc63ab806f56cc563fe1/src/prefect/client/orchestration.py#L1832
https://github.com/PrefectHQ/prefect/blob/afbed19d752b7057ccb2dc63ab806f56cc563fe1/src/prefect/client/orchestration.py#L1613
https://github.com/PrefectHQ/prefect/blob/afbed19d752b7057ccb2dc63ab806f56cc563fe1/src/prefect/client/orchestration.py#L1832
> fix(ingest/prefect): Fix prefect mypy errors

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/utilities/cachetools_keys.py
Fixes a bug with operation_config where the profiling enabled value could change partway through ingestion.
Was added in a broken state here https://github.com/datahub-project/datahub/pull/8489
> fix(ingest): cache sql is_profiling_enabled method

- metadata-ingestion-modules/dagster-plugin/setup.py
- metadata-ingestion/pyproject.toml
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/sql_parsing/_sqlglot_patch.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/src/datahub/utilities/is_pytest.py
- metadata-ingestion/src/datahub/utilities/unified_diff.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_patch.py
- metadata-ingestion/tests/unit/utilities/test_unified_diff.py
- metadata-ingestion/tests/unit/utilities/test_utilities.py
This moves us onto using sqlglot instead of our acryl-sqlglot fork. 
Closes https://github.com/datahub-project/datahub/issues/10184.
> feat(ingest): use mainline sqlglot

- metadata-ingestion/docs/sources/fivetran/fivetran_recipe.yml
- metadata-ingestion/src/datahub/ingestion/source/fivetran/config.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
Follow up on https://github.com/datahub-project/datahub/pull/11683
> feat(ingest/fivetran): show connector filter reason

- datahub-web-react/src/app/ingest/source/executions/reporting/StructuredReportItemContext.tsx
This way it's monospaced and newlines come through properly.
> fix(ui): show structured report context in pre

- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateGraphIndicesService.java
- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateIndicesService.java
- metadata-jobs/mae-consumer-job/src/main/resources/logback.xml
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MCLKafkaListener.java
- metadata-jobs/mce-consumer-job/src/main/resources/logback.xml
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
Improves logging contextualization for MCL & MCP consumers by adding urns, aspect names, entity type, and change type to logging context. This allows for improved log filtering. Also gives more details in metrics & logs during search & graph index updates.
> feat(logs): add change event details to log context and improve some logs in MCL/MCP

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/queries.py
- metadata-ingestion/tests/unit/bigquery/test_bigquery_source.py
> fet(ingest/bigquery): Add support ingesting foreign keys and primary keys for BigQuery tables

- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateGraphIndicesService.java
> fix(logging): minor modifications for logging

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MCLKafkaListener.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- Suppress `Ingestion of aspects batch to database took X ms` unless it takes longer than 50ms
- Change `Invoking MCL hook XXX` level to debug
- Change `Appending run id for entity name` level to debug
- Remove logging of ingestion proposals - already logged in `ingestProposals` method
> fix(log): reduce log volume for ingestion and consumers

- datahub-web-react/src/app/entity/schemaField/SchemaFieldPropertiesEntity.tsx
- datahub-web-react/src/app/entity/schemaField/preview/Preview.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/DatasetLink.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
- datahub-web-react/src/graphql/search.graphql
> feat(frontend): show browse paths for business attributes related entities - schema fields

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
This allows fetching JOBS from BQ locations other than Multi-region US and EU, by setting config locations.
> feat(bigquery): support config for region qualifiers to fetch jobs

- docs/managed-datahub/slack/saas-slack-setup.md
> feat(docs) steps on handling workspace admin approvals for slack installation

- docs/managed-datahub/slack/saas-slack-setup.md
> feat(docs-site) slack bot scopes

- docs-website/docusaurus.config.js
- docs-website/src/pages/_components/Trial/index.js
- docs-website/src/pages/cloud/DemoForm/index.jsx
- docs-website/src/pages/cloud/Enterprise/styles.module.scss
- docs-website/src/pages/cloud/Hero/styles.module.scss
- docs-website/src/pages/cloud/UnifiedTabs/styles.module.scss
- docs-website/src/pages/cloud/index.js
- docs-website/src/pages/cloud/styles.module.scss
> fix(docs-site) remove free trial notes

- metadata-ingestion/examples/recipes/bigquery_to_datahub.dhub.yaml
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/tests/unit/bigquery/test_bigquery_lineage.py
> fix(ingestion/bigquery-gcs-lineage): Add lineage extraction for BigQuery with GCS source

- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
- metadata-ingestion/src/datahub/ingestion/transformer/dataset_transformer.py
- metadata-ingestion/src/datahub/ingestion/transformer/pattern_cleanup_ownership.py
- metadata-ingestion/src/datahub/ingestion/transformer/remove_dataset_ownership.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
- extend pattern cleanup transformer to other entities
- future suggestion - might be good to auto generate list of entities that have ownership aspects. Will allow us to extend all ownership transformers very easily. Added some common entities for now
> feat(ingest/transform): extend ownership transformer to other entities

- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/test_helpers/mce_helpers.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_column_lineage_deduplication.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename_with_temp.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_swap.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_temp_table.json
- metadata-ingestion/tests/unit/sql_parsing/test_sql_aggregator.py
Any place we accidentally use a set instead of an OrderedSet or list is a location where we introduce inconsistency and randomness. In the worst case, this causes new aspect versions to get registered in the database when nothing semantically changed.
> feat(ingest): check ordering in SqlParsingAggregator tests

- docs-website/src/pages/_components/QuickstartContent/index.js
- docs-website/src/pages/_components/QuickstartContent/quickstartContent.js
- docs-website/src/pages/_components/QuickstartContent/quickstartcontent.module.scss
> fix: add learn more in the homepage

- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi-lexical-grammar.rule
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
1. M-Query which contains SQL: 
```
select 
order_number AS ""OrderNumber""
from DM_OPERATIONS.VI
``` 
was not working because of two double quotes after `AS`. This PR will fix this issue.
> fix(ingestion/powerbi): handle double quotes in M-query

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/upgrade/upgrade.py
Our previous usage of asyncio was broadly incorrect (it blocked the main event loop). Now it is more correct, and is confined to the check_upgrade method instead of leaking async concerns outside of that file.
It would previously not guarantee that ingestion code runs on the main thread. We want that guarantee, since it enables us to implement timeouts using signals and overall helps ensure that we get the guarantees we want.
A side benefit is that this might help us simplify the Okta source in the future, which currently uses nest_asyncio to make things work.
> fix(ingest): reduce asyncio in check_upgrade

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/parser.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
- metadata-ingestion/src/datahub/utilities/threading_timeout.py
- metadata-ingestion/tests/integration/powerbi/golden_test_container.json
- metadata-ingestion/tests/integration/powerbi/golden_test_most_config_and_modified_since_admin_only.json
- metadata-ingestion/tests/integration/powerbi/golden_test_personal_ingest.json
- metadata-ingestion/tests/unit/utilities/test_threading_timeout.py
Stacked on top of https://github.com/datahub-project/datahub/pull/11711
> feat(ingest/powerbi): add timeouts for m-query parsing

- metadata-integration/java/acryl-spark-lineage/src/main/java/datahub/spark/DatahubEventEmitter.java
- metadata-integration/java/acryl-spark-lineage/src/main/java/datahub/spark/DatahubSparkListener.java
- metadata-integration/java/acryl-spark-lineage/src/main/java/datahub/spark/conf/KafkaDatahubEmitterConfig.java
- metadata-integration/java/acryl-spark-lineage/src/main/java/datahub/spark/conf/SparkConfigParser.java
- metadata-integration/java/datahub-client/src/main/java/datahub/client/kafka/AvroSerializer.java
- metadata-integration/java/datahub-client/src/main/java/datahub/client/kafka/KafkaEmitter.java
> user should be able to pass custom mcp kafka topic

- datahub-frontend/app/auth/AuthModule.java
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLMAESpringTest.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLSpringCommonTestConfiguration.java
- metadata-jobs/mce-consumer-job/src/test/java/com/linkedin/metadata/kafka/MceConsumerApplicationTestConfiguration.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityclient/EntityClientConfigFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityclient/JavaEntityClientFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityclient/RestliEntityClientFactory.java
- metadata-service/restli-client-api/src/main/java/com/linkedin/common/client/BaseClient.java
- metadata-service/restli-client-api/src/main/java/com/linkedin/entity/client/EntityClientConfig.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/SystemRestliEntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/usage/RestliUsageClient.java
- metadata-service/restli-client/src/test/java/com/linkedin/common/client/BaseClientTest.java
- metadata-service/restli-client/src/test/java/com/linkedin/entity/client/SystemRestliEntityClientTest.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
> feat(entity-client): batch entity-client ingestProposals

- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- there was no actual loop iterating over batches, added that
- references were not being deleted, added that
- added a limit of number of entities to be deleted so a single run doesn't go endlessly for ever risking multiple runs starting concurrently
> fix(ingest/gc): add limit, add actual loop for iterating over batches

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
- metadata-ingestion/tests/integration/fivetran/fivetran_snowflake_empty_connection_user_golden.json
- metadata-ingestion/tests/integration/fivetran/fivetran_snowflake_golden.json
- Follow up this https://github.com/datahub-project/datahub/pull/9490 to remove materialisation completely. This led to badly materialised datasets that did not have all the aspects and led to a odd state in the UI without platform instances.
- This follows the consistent practice that we have adopted of 1 ingestion source not materialising other sources entities
> fix(ingest/fivetran): do not materialise upstream

- metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_sql_queries.py
> fix(ingest/dremio): update dremio sql query to retrieve queried datasets in sql jobs 

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/utils/ESUtilsTest.java
Fixes the environment filter for views by expanding origin to include env fields on entities that use env instead. Also adds the reverse expansion.
> fix(views): fix environment filter for views

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/bootstrapmcps/BootstrapMCPUtil.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/bootstrapmcps/model/BootstrapMCPConfigFile.java
- datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/system/bootstrapmcps/BootstrapMCPUtilTest.java
- datahub-upgrade/src/test/resources/bootstrapmcp/test.yaml
- docs/advanced/bootstrap-mcps.md
- metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
> feat(template-mcps): allow further control for helm

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
> fix(timeline): fixes primary key change events

- metadata-models/src/main/resources/entity-registry.yml
For consistency with other entities
> feat(model): add deprecation aspect to container

- metadata-service/war/build.gradle
- metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java
- metadata-service/war/src/test/java/com/linkedin/gms/SpringTest.java
> fix(config): add missing package

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
> fix(timeline): fixes a renaming corner case

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/utilities/partition_executor.py
- metadata-ingestion/tests/unit/utilities/test_partition_executor.py
> fix(ingest/partition-executor): Fix deadlock by recomputing ready items

- metadata-ingestion/examples/structured_properties/structured_properties.yaml
- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
- smoke-test/tests/structured_properties/bad_entity_type.yaml
- smoke-test/tests/structured_properties/test_structured_properties.py
- smoke-test/tests/structured_properties/test_structured_properties.yaml
Adds validation for entity types referenced in structured property definition yaml files.
> chore(structured-properties): add cli validation for entity types

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
This PR aims to add the CLI version to the http headers when ingesting.
We run a distributed setup for ingesting various data sources. To keep an eye on our ecosystem, we would like to correlate ingestion-users and their current cli versions, to inform them to update when we roll out a new version of datahub.
Let me know if this makes sense to you, or if we should find an alternative solution :-) Thanks!
> feat(py-sdk): add cli version to ingestion headers

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
This pull request addresses an issue caused by the use of class variables in the LookML pipelines. When multiple pipelines are executed in the same runtime environment, class variables can lead to conflicts, as they are shared across all instances and are not instance-specific.
To resolve this, class variables have been replaced with instance variables, ensuring that each pipeline instance maintains its own independent state.
**Changes**
Replaced class variables with instance variables to prevent state conflicts.
**Impact**
This change ensures proper isolation of variables between pipeline instances, eliminating errors when multiple pipelines run simultaneously.
~~[ ] Links to related issues (if applicable)~~
~~[ ] Tests for the changes have been added/updated (if applicable)~~
~~[ ] Docs …
> fix(ingest/lookml): replace class variable with instance variable for improved encapsulation

- metadata-ingestion/src/datahub/utilities/partition_executor.py
- metadata-ingestion/tests/unit/utilities/test_partition_executor.py
Previously, the batch partition executor could stall for `min_process_interval` (default 30s) if the batch was not empty, but `_pending` was cleared out into `pending_key_completion`. This changes the logic to re-calculate the batch if we can't ready from `_pending`, i.e. if it's been cleared out and the main ingestion process is blocked.
Reverts the old test so it's only testing batching behavior; adds new deadlock test that tests both the old deadlock failure + this new 30s wait failure. Before the change is made, the test times out after 10 seconds, now it passes in ~1s.
> fix(ingest/partitionExecutor): Fetch ready items for non-empty batch when _pending is empty

- datahub-web-react/src/app/entity/shared/siblingUtils.ts
We had a bug when merging schemas between entities where there was a mix of v1 and v2 schema field names - they wouldn't match as keys so the field would show up twice. Now, normalize these keys so we can merge properly by downgrading everything.
> fix(ui) Fix merging siblings schema with mix of v1 & v2 fields

- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_queries.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/queries_extractor.py
- metadata-ingestion/src/datahub/utilities/progress_timer.py
- metadata-ingestion/tests/unit/utilities/test_progress_timer.py
> fix(ingest/bigquery): increase logging in bigquery-queries extractor

- datahub-web-react/src/app/ingest/source/builder/sources.json
- datahub-web-react/src/app/ingest/source/conf/csv/csv.ts
Use the correct link for the [csv enricher](https://datahubproject.io/docs/generated/ingestion/sources/csv-enricher) source, i.e. the one used in the Managed Ingest UI dialogue box.
> fix(ui): use correct docs link for csv enricher

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/type/ResolvedActorResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/InstitutionalMemoryMetadataMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/ResolvedActorMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/LinkButton.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/LinkList.tsx
- datahub-web-react/src/graphql-mock/mutationHelper.ts
- datahub-web-react/src/graphql/domain.graphql
- datahub-web-react/src/graphql/fragments.graphql
Saw an issue where a group was added to the actor field for a link in the intitutionalMemory aspect but our graphql API was only expecting users and had that hard defined. I resolved this by deprecating the old field that only allows users, and created a new actor field that is a union of CorpUser and CorpGroup and then swapped out all the references in the UI.
> fix(ui/graphql) Handle groups in institutionalMemory aspect

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/BrowseDAOTest.java
In PR: https://github.com/datahub-project/datahub/pull/11514/files, empty strings were considered as null for ES indexing.
This is causing null pointer exception for entities, where browse path is empty string.
Which is emulated in the below test:
---
Have added test for the changes as well.
> fix(browseDAO): Handle null browse path from ES in BrowseDAO

- metadata-io/src/main/java/com/linkedin/metadata/dataproducts/sideeffects/DataProductUnsetSideEffect.java
- metadata-io/src/test/java/com/linkedin/metadata/dataproducts/sideeffects/DataProductUnsetSideEffectTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/plugins/SpringStandardPluginConfiguration.java
> fix(dataproduct): optimize data product sideeffect

- datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
> fix(ingest): always send correct data for advanced section

- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/telemetry/telemetry.py
> fix(ingest): ensure sentry is initialized with graph tags

- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
As this is doing multiple processes want to ensure one process failure doesn't step other processes
> fix(ingest): more error handling

- metadata-integration/java/datahub-schematron/lib/src/main/java/io/datahubproject/schematron/converters/avro/AvroSchemaConverter.java
- metadata-integration/java/datahub-schematron/lib/src/main/java/io/datahubproject/schematron/models/FieldPath.java
For components used in the Spark plugin (i.e. datahub client) we still need to support jdk8 for old versions of spark.
> fix(schematron): fix for jdk8

- docs/automations/snowflake-tag-propagation.md
> fix(automations docs): Update snowflake-tag-propagation.md to include permissions required for the Automation

- docs/what/urn.md
- metadata-io/metadata-io-api/build.gradle
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationApiUtils.java
- metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/validation/ValidationApiUtilsTest.java
> fix(validation): additional URN validation adjustments

- metadata-ingestion/src/datahub/ingestion/source/kafka/kafka.py
- metadata-ingestion/tests/integration/kafka/test_kafka.py
Followup on https://github.com/datahub-project/datahub/pull/11900
> fix(ingest/kafka):add poll for admin client for oauth_cb

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/qlik_sense/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/tests/integration/dbt/test_dbt.py
- metadata-ingestion/tests/unit/test_sql_types.py
> feat(ingest): standardize sql type mappings

- metadata-ingestion/src/datahub/utilities/urn_encoder.py
- metadata-ingestion/tests/unit/urns/test_urn.py
> feat(ingest): add tests for colon characters in urns

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/tests/unit/test_athena_source.py
> feat(ingest/athena): handle partition fetching errors

- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/CustomPropertiesPatchBuilder.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/DataFlowInfoPatchBuilder.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/DataJobInfoPatchBuilder.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/DatasetPropertiesPatchBuilder.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/subtypesupport/IntermediatePatchBuilder.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/builder/DataFlowInfoPatchBuilderTest.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/builder/DataJobInputOutputPatchBuilderTest.java
- Fixes an issue with the custom properties patch client in Java where if custom properties are the only things being changed, the parent patcher assumes there are no patches and throws an exception on build(). 
- Changes the interaction model between the parent patch builder and the inner builder. The inner builder now directly adds to the parent's "operations list".
> fix(java-sdk): custom properties patch client

- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
> fix(ingest/gc): delete invalid dpis

- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/feature_groups.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/models.py
- metadata-ingestion/tests/unit/sagemaker/test_sagemaker_source.py
> fix(ingest/sagemaker): Gracefully handle missing model group

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_liquid_tag.py
- metadata-ingestion/tests/integration/lookml/test_lookml.py
- Don't fail on unknown liquid filters
- Implement sql_quote liquid filter
> fix(ingest/looker): Don't fail on unknown liquid filters

- metadata-ingestion/src/datahub/cli/delete_cli.py
> feat(cli): add platform filter for undo soft delete

- .github/workflows/pr-labeler.yml
This ensures `community-contribution` is not present when it should not be there
> chore: update label for team

- entity-registry/src/main/java/com/linkedin/metadata/models/StructuredPropertyUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/AggregationQueryBuilderTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/utils/ESUtilsTest.java
Fix a few issues we were seeing with structured properties that have dots in their IDs:
- we were passing in the converted field name for structured props into `toElasticsearchFieldType` which would not match with a structured property entity definition since the field name strips dots and replaces them with underscores. Therefore we were always defaulting to `STRING` - now use the `criterion` field which doesn't have dots removed.
- When there were no matches, we were just returning the converted elastic field name back to the UI which we could not resolve to a structured property entity if there were dots in it. In this case, return the criterion field instead.
> fix(filters) Fix issues with structured properties filters

- metadata-ingestion/src/datahub/configuration/kafka_consumer_config.py
- metadata-ingestion/tests/integration/kafka/oauth.py
- metadata-ingestion/tests/integration/kafka/test_kafka.py
kafka consumer silently ignores invocation of oauth callback if it does not follow expected signature. this validation ensures to raise configuration error in advance.
> feat(ingest/kafka): additional validation for oauth_db signature

- .github/workflows/build-and-test.yml
- entity-registry/src/main/java/com/linkedin/metadata/models/extractor/FieldExtractor.java
- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateGraphIndicesService.java
- metadata-io/src/test/java/com/linkedin/metadata/service/UpdateGraphIndicesServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/service/UpdateIndicesServiceTest.java
Fixing an exception that occurs when deleting graph edges when the MCL is missing the record template. Code updated to check the previous aspect and the current aspect during a delete.
Additionally, if both aspects are missing avoid an exception and log a warning.
> fix(graph-edge): fix graph edge delete exception

- metadata-ingestion/tests/unit/urns/invalid_urns.txt
- metadata-ingestion/tests/unit/urns/test_corp_group_urn.py
- metadata-ingestion/tests/unit/urns/test_corpuser_urn.py
- metadata-ingestion/tests/unit/urns/test_data_flow_urn.py
- metadata-ingestion/tests/unit/urns/test_data_job_urn.py
- metadata-ingestion/tests/unit/urns/test_data_process_instance_urn.py
- metadata-ingestion/tests/unit/urns/test_dataset_urn.py
- metadata-ingestion/tests/unit/urns/test_domain_urn.py
- metadata-ingestion/tests/unit/urns/test_notebook_urn.py
- metadata-ingestion/tests/unit/urns/test_tag_urn.py
- metadata-ingestion/tests/unit/urns/test_urn.py
- metadata-ingestion/tests/unit/urns/valid_urns.txt
> feat(ingest): add urn validation test files

- entity-registry/build.gradle
- metadata-integration/java/datahub-event/build.gradle
- metadata-models/build.gradle
- metadata-service/openapi-servlet/models/build.gradle
* remove javax.servlet from datahub-client jar
* remove swagger classes from datahub-client jar
> fix(datahub-client): prevent unneeded classes in datahub-client jar

- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java
Refactor entityService function to filter no-op upserts. Upserts which would result in no change to the row. Still allows for updating last observed.
Another situation might occur on a transaction collision. If two identical transactions collide, one of them is re-executed and may result in a no-op as well.
Add metrics around various batch related conditions
> fix(entity-service): no-op batches

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py
- metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
This enables a user to create a token outside of the ingestion flow and supply it. This has some risks, including not being able to refresh the token once expired, so a warning is added here.
Snowflake docs that were referenced: https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-connect#connecting-with-oauth
> feat(snowflake): adding oauth token bypass to snowflake

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_report.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/tests/integration/oracle/golden_test_ingest_with_database.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json
> fix(ingest): avoid shell entities during view lineage generation

- metadata-service/auth-filter/src/main/java/com/datahub/auth/authentication/filter/AuthenticationFilter.java
- metadata-service/auth-servlet-impl/src/main/java/com/datahub/auth/authentication/AuthServiceController.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/usage/UsageStats.java
> fix(logs): add actor urn on unauthorised

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
> refactor(ingest/sql): add _get_view_definition helper method

- metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/common.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/jobs.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/lineage.py
- Adding logs to make it transparent what is going on in SageMaker
- Adding option to control retry for any aws source
> fix(ingest/sagemaker): Adding option to control retry for any aws source

- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- metadata-ingestion/tests/unit/test_gc.py
> fix(ingest/gc): Additional dataprocess cleanup fixes

- .github/workflows/airflow-plugin.yml
- docs/how/updating-datahub.md
- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_airflow_shims.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_basic_iolets.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_simple_dag.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
- metadata-ingestion-modules/airflow-plugin/tox.ini
**Why is it ok to drop Airflow < 2.3?**
- Airflow itself doesn't have much in its docs https://airflow.apache.org/docs/apache-airflow/stable/installation/supported-versions.html, but seems to assume you're on the latest e.g. Airflow 2.10
- GCP composer says support for airflow 2.2.5 ended on March 13, 2024 https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images-composer-1
- AWS MWAA ended support for airflow 2.2.2 on June 27, 2024 https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html#airflow-versions-official
- Our own telemetry indicates that the Airflow plugin is used with Airflow 2.2 extremely rarely, and almost never with Airflow 2.1.
**Why do we want to do this?**
This will let us make the DataHub plugin v2 the default version. …
> feat(airflow): drop Airflow < 2.3 support + make plugin v2 the default

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/specific/datajob.py
- metadata-ingestion/tests/integration/nifi/nifi_mces_golden_standalone.json
- metadata-ingestion/tests/unit/patch/test_patch_builder.py
- smoke-test/tests/patch/test_datajob_patches.py
Fixes a subtle bug and changes a default behavior
- The `DataJobPatchBuilder.add_output_dataset` method accepted an `Edge` but wasn't generating the patch PATH correctly
- Default behavior when no timestamps were provided was to mint a client side auditstamp - this unnecessarily creates updates in the aspect when that is not what the user wants.
> fix(py-sdk): DataJobPatchBuilder handling timestamps, output edges

- metadata-events/mxe-schemas/build.gradle
Script was expected to run with bash, but build script launched with sh (overriding the shebang) . While this mismatch didn't cause problems on osx and the ci envs, this did fail on ubuntu24.04 dev envs.
> build(metadata-events): fix shell interpreter mismatch in build script

- gradle/coverage/python-coverage.gradle
codecov requires the word coverage to be present in the coverage report file name
> build(coverage): rename python coverage reports

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
> fix(entity-service): prevent mutation of systemMetdata on prev

- docs/how/updating-datahub.md
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
Adds missing keep alive value to OpenAPI. Requires ElasticSearch 7.10+ and feature flag to be enabled to be used.
> fix(openapi): adds in previously ignored keep alive value

- docs/how/updating-datahub.md
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
* Changes the field in the OpenAPIV3Generator to target the correct string list field
* Deprecates the old sort field
* Adds default behavior for both sortCriteria and sortOrder
> fix(openapi): fix sort criteria parameter

- metadata-ingestion/src/datahub/ingestion/api/incremental_properties_helper.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/config.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
> feat(ingest/snowflake): allow option for incremental properties

- metadata-ingestion/src/datahub/cli/cli_utils.py
- metadata-ingestion/tests/unit/cli/test_cli_utils.py
The correct URL is without `/api` and many folks add `/api` in the URL causing problems. This would eliminate those problems
> fix(cli): don't use /api in gms url

- datahub-web-react/src/app/ingest/source/builder/sources.json
- metadata-ingestion/docs/sources/athena/athena_recipe.yml
> docs(ingest/athena): update recipe with aws key pair example

- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- `dataprocess_cleanup` can take some time. Making it the last step so other steps get done
- increasing hard delete entities by default from 10k to 25k
> fix(ingest/gc): minor tweak gc source

- datahub-web-react/src/app/permissions/policy/PolicyDetailsModal.tsx
- datahub-web-react/src/app/permissions/policy/PolicyPrivilegeForm.tsx
- datahub-web-react/src/app/permissions/policy/_tests_/policyUtils.test.tsx
- datahub-web-react/src/app/permissions/policy/constants.ts
- datahub-web-react/src/app/permissions/policy/policyUtils.ts
We discovered a bug where old policies with the `RESOURCE_TYPE` or `RESOURCE_URN` filters applied to them were not being rendered in the UI. These are still supported on the backend, but the UI was saying "All" since it didn't think there was a filter for the types or assets fields.
This PR adds that backwards compatibility to the UI by fetching those fields if they exist to display, and when editing these fields we remove the deprecated fields and only use the newer ones going forward.
> fix(ui) Add backwards compatibility to the UI for old policy filters

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema_gen.py
additional reporting around secure views without definitions
> feat(ingest/snowflake): ingest secure, dynamic, hybrid table metadata

- metadata-ingestion/src/datahub/cli/delete_cli.py
Hard deletion is not recommended live but when soft deleting a lot of items without parallelism it can get quite slow. This will help with that.
> feat(cli): add --workers arg in delete command

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
- metadata-ingestion/src/datahub/testing/doctest.py
- metadata-ingestion/tests/integration/git/test_git_clone.py
- metadata-ingestion/tests/unit/sagemaker/test_sagemaker_source.py
- metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
- metadata-ingestion/tests/unit/test_dbt_source.py
- metadata-ingestion/tests/unit/utilities/test_utilities.py
> fix(ingest/snowflake): handle dots in snowflake table names

- datahub-web-react/src/app/entity/dataset/profile/schema/components/StructuredPropValues.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/StructuredPropertyBadge.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/StructuredProperties/SidebarStructuredPropsSection.tsx
- datahub-web-react/src/app/entity/shared/entityForm/Form.tsx
- datahub-web-react/src/app/entity/shared/tabs/Properties/Edit/EditStructuredPropertyModal.tsx
- datahub-web-react/src/app/govern/structuredProperties/StructuredProperties.tsx
- datahub-web-react/src/app/govern/structuredProperties/ViewAdvancedOptions.tsx
- datahub-web-react/src/app/govern/structuredProperties/ViewStructuredPropsDrawer.tsx
- datahub-web-react/src/app/ingest/source/executions/ExecutionRequestDetailsModal.tsx
> fix(ui): dereference issues

- metadata-ingestion/src/datahub/ingestion/source/kafka/kafka_connect.py
When using confluent cloud, 
- GET does work on `<connect-uri>/` but works on `<connect-uri>/connectors` endpoint when testing auth. We achieve the intent of testing connection even if we use any of these urls.
- GET on /connectors/{connector-name}/topic is not supported, so lineage can not be extracted. The PR adds exception handling for failure in accessing endpoint and attempts to extract rest of information.
- Refactors around reporting warnings for structured reporting
> fix(ingest/kafka-connect): update connection test url, handle api failures

- .github/workflows/dagster-plugin.yml
- metadata-ingestion-modules/dagster-plugin/setup.py
- metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/sensors/datahub_sensors.py
- Deprecate Python 3.8 for Dagster plugin
- Fix changed Sensor return type
> fix(ingest/dagster): Fix Dagster build

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dataproduct/CreateDataProductResolver.java
Why?
- If an org has owner editor policies
- Someone goes in and creates data product in the UI, they won't be able to edit the data product that they created which is very problematic. They will have to ask overall admins to make them owner which should not be required.
Testing video https://www.loom.com/share/cb1b300112454f6cb4b61ed6b131bd1f
> fix(dataproduct): creator is assigned as owner

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
> feat(ingest): additional limits on ingestProposalBatch

- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
Reuses an existing utility + makes it thread safe.
> refactor(ingest): cleanup structured properties validation

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/graph_usage_sample_dag.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/hooks/datahub.py
Also add an example DAG showing the method's usage in Airflow.
> feat(airflow): add `DatahubRestHook.make_graph` method

- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_database_reader.py
It uses server-side cursor which is the recommended in this case -> https://docs.sqlalchemy.org/en/20/core/connections.html#using-server-side-cursors-a-k-a-stream-results
> fix(ingest/datahub): Use server side cursor instead of local one

- metadata-ingestion/sink_docs/metadata-file.md
It's filename instead of path, it may confuse the innocent if they follow the recipe to debug or demo
> docs(ingest): fix sink recipe to correct config parameter

- docs/cli.md
- docs/how/delete-metadata.md
- metadata-ingestion/src/datahub/cli/ingest_cli.py
I'm adding a new CLI command called "datahub ingest list-source-runs" (name pending) that will give this result 
Can also filter by URN and/or source name:
Do we like the resulting columns? Are there any we should add or get rid of?
I attempted to filter by platform but it seems like platform is always null in the graphql response.
> feat(cli): added cli option for ingestion source

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- While ingesting S3 datasets with a [pipeline](https://github.com/datahub-project/datahub/blob/2291c71c293dcf5b83d29723ce129450b6b64b0a/metadata-ingestion/src/datahub/ingestion/run/pipeline.py#L209), I encountered a warning: `Unable to find any files in the folder s3://your-bucket/your-path/year=2024/. Skipping...`, but the file was definitely present.
- You can reproduce this bug with the following code.
```python
from datahub.ingestion.run.pipeline import Pipeline
DATAHUB_SERVER = "http://localhost:8080"
DEFAULT_SINK = {"type": "datahub-rest", "config": {"server": DATAHUB_SERVER}}
S3_PATH = "s3://your-bucket/your-path/path/{table}/{partition_key[0]}={partition[0]}/*.parquet"
s3_config = {
"source": {
"type": "s3",
"config": {
"path_spec": {
"include": S3_PATH,
},
"aws_config": { …
```
> fix(ingest/s3): incorrectly parsing path in s3_uri

- datahub-web-react/src/app/entity/shared/tabs/Properties/__tests__/useStructuredProperties.test.ts
- datahub-web-react/src/app/entity/shared/tabs/Properties/useStructuredProperties.tsx
Most schema fields don't have their own urns yet in the database and structured properties are the first main aspect we're storing on them. This PR edits the `upsertStructuredProperties` endpoint to allow users to add a property to a schema field urn that doesn't exist yet. This way users will be able to add/remove properties on schema fields even if they weren't minted by some other way yet (other than forms or API, there is no other way as far as I know).
> fix(ui) Fix nesting logic in properties tab

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- Change so that source does not end with warnings
- add proper `enabled` flags for each sub-task
- add more error handling
> fix(ingest/gc): more logging, error handling, explicit flag

- metadata-service/configuration/src/main/resources/application.yaml
Fixes malformed application.yml
> fix(env) Fix forms hook env var default config

- metadata-ingestion/src/datahub/ingestion/source/mlflow.py
- metadata-ingestion/tests/unit/test_mlflow_source.py
> feat(ingest/mlflow): Support configurable base_external_url

- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
Fixes a bug that was exposed in https://github.com/datahub-project/datahub/pull/12144 and broke our smoke-tests.
> fix(cli/properties): fix data type validation

- metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/client/dagster_generator.py
dagster just released 1.9.6 and our builds are failling because of missing `_asdict()` method
`InputSnapDef` is not a `NamedTuple` anymore and so the missed method
https://github.com/dagster-io/dagster/compare/1.9.5...1.9.6#diff-50a436e3f602ebee518a937a2415e1157663339bb01bfe925aa26790016a75e2
> fix(dagster): support dagster v1.9.6

- datahub-graphql-core/src/main/resources/entity.graphql
Suspending a user works well for the suspended user. However, admins can't load the "Users & Groups" or "Permissions" page unless this change to the graphql model is added.
Linked to https://github.com/datahub-project/datahub/pull/12158
> fix(graphql): add suspended to corpuserstatus

- docs/api/tutorials/structured-properties.md
Also use `urn:li:entityType:datahub.*` in graphql
> docs(structured properties) fix entityTypes in creating structured property

- docker/build.gradle
* refactor gradle config for easier maint.
> feat(gradle): add quickstartPgDebug option

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/job_models.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
`BrowsePathsV2` generation depends on the `Container` hierarchy, so this is adding missed `Container` aspect for the `Data(Flow|DataJob)` entities.
> fix(mssql): adds missing containers for dataflow and datajob entities, required for browse paths v2 generation

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/job_models.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
Reverts datahub-project/datahub#12194
> Revert "fix(mssql): adds missing containers for dataflow and datajob entities, required for browse paths v2 generation"

- metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
These aspects migrated to new instance will cause problems
- Ingestion runs don't add value
- Ingestion secrets cannot be decoded due to different encryption keys
- Global settings have encrypted values and SSO url from previous instance which will cause SSO of new instance to not work
> fix(ingest): exclude aspect from migration

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
> feat(ingest): add sql parser trace mode

- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/integration/mode/mode_mces_golden.json
> fix(ingest/mode): move sql logic to view properties aspect

- metadata-ingestion/src/datahub/sql_parsing/tool_meta_extractor.py
> fix(ingest/looker): Add flag for Looker metadata extraction

- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/execution_request_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source_report/ingestion_stage.py
- in some cases while no tokens were actually being returned the token was > 0 which caused an infinite loop
- In some cases execution request calls were giving server errors
Both these caused a very long loop and in some cases an infinite loop. This fixes that and adds ingestion stage reporting so we can see what is happening in all such cases
> fix(ingest/gc): misc fixes in gc source

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_dataclasses.py
In most cases, these indicate minor syntax errors. Now that we have a warning state, it's more appropriate than failure.
> fix(ingest/lookml): emit warnings for resolution failures

- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
- metadata-ingestion/tests/integration/powerbi/test_admin_only_api.py
- metadata-ingestion/tests/integration/powerbi/test_powerbi.py
- metadata-ingestion/tests/integration/powerbi/test_profiling.py
- metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
Pytest does this by default. No need to redo it explicitly.
Also
- Fixes some logic errors in the tests around token expiry and renewal.
- Uses single underscores to prevent name mangling.
> chore(ingest): remove `enable_logging` helper

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
See https://datahubspace.slack.com/archives/C02FWNS2F08/p1732277810168469
> feat(ingest/dbt): support "Explore" page in dbt cloud

- metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
Yet another retriable error code we have received recently
```
Internal error 502 at https://prod-useast-a.online.tableau.com/api/metadata/graphql
b'<html><body><h1>502 Bad Gateway</h1>\nThe server returned an invalid or incomplete response.\n</body></html>\n\n'
File "/tmp/datahub/ingest/venv-tableau-1f7583b4403d3273/lib/python3.10/site-packages/datahub/ingestion/source/tableau/tableau.py", line 1186, in get_connection_object_page
query_data = query_metadata_cursor_based_pagination(
File "/tmp/datahub/ingest/venv-tableau-1f7583b4403d3273/lib/python3.10/site-packages/datahub/ingestion/source/tableau/tableau_common.py", line 959, in query_metadata_cursor_based_pagination
result = server.metadata.query(
File …
```
> fix(tableau): retry if 502 error code

- metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
> chore(tableau): adjust visibility of info message

- metadata-ingestion/src/datahub/api/circuit_breaker/assertion_circuit_breaker.py
- metadata-ingestion/src/datahub/configuration/datetimes.py
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/emitter/mcp_builder.py
- metadata-ingestion/src/datahub/emitter/mcp_patch_builder.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_kafka_reader.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/utilities/time.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_prefer_sql_parser_lineage_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_test_model_performance_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
- metadata-ingestion/tests/unit/sdk/test_mce_builder.py
- metadata-ingestion/tests/unit/serde/test_codegen.py
- smoke-test/smoke.sh
> feat(ingest): add parse_ts_millis helper

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/ingestion/api/closeable.py
- metadata-ingestion/src/datahub/ingestion/api/ingestion_job_checkpointing_provider_base.py
- metadata-ingestion/src/datahub/ingestion/api/report.py
- metadata-ingestion/src/datahub/ingestion/api/sink.py
- metadata-ingestion/src/datahub/utilities/urns/_urn_base.py
This was initially added in https://github.com/datahub-project/datahub/pull/7313 and then reverted in https://github.com/datahub-project/datahub/pull/7490. Now that we've dropped support for old Airflow versions in https://github.com/datahub-project/datahub/pull/12056, we can actually do the upgrade.
> fix(ingest): use `typing_extensions.Self`

- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- Reducing logs was required otherwise logs were full of useless `Deleted 0 ....` 
- Now the final report will have structured details on number of data jobs and data flows
- We don't want to wait in case there were 0 deletions. Otherwise it will take too long. This fixes that. In testing this changed things from ~1 hour to 15 minutes
- No need to query data flows in case the deletion of empty data flows is disabled
> fix(ingest/gc): reduce logging, remove unnecessary sleeps

- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/common/mappers/QueryPropertiesMapperTest.java
getCreatedOn should not be tested
> fix(tests): fixing QueryPropertiesMapperTest.java

- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
The delete function in the EnityService assumed a strictly monotonically increasing version. In a batch this can be non-strict, meaning versions can be skipped within a batch leading to only persisting the latest version, accounting for incremented versions within the batch.
> feat(delete): delete logic non-strict monotonically increasing version

- docs-website/sidebars.js
- docs/api/graphql/graphql-best-practices.md
- docs/api/graphql/how-to-set-up-graphql.md
Add best practices for graphql queries with examples.
> docs(graphql): create graphql best practices

- metadata-ingestion/tests/unit/test_aws_common.py
> fix(ingestion/aws_common): update iam role and aws access key tests to complete successfully when executed on EC2 instance

- metadata-ingestion/src/datahub/ingestion/reporting/datahub_ingestion_run_summary_provider.py
- metadata-ingestion/tests/unit/reporting/test_datahub_ingestion_reporter.py
> fix(ingest): json serializable fix

- metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- If there were 25k entities that were retained due to age then nothing will get deleted even if there were items after that to be deleted. Because only 25k were being submitted while the limit was actually on 25k deletions.
- reporting improvement to understand how much was retained due to age
- `self.ctx.graph.get_urns_by_filter` does not return `query` entity so getting it separately so we can hard delete soft deleted query entities too
> fix(ingest/gc): soft deletion loop fix

- metadata-ingestion/build.gradle
`PYTHONDEVMODE` will flag additional warnings for us, which should help with debugging.
> chore(ingest): refactor common pytest args

- metadata-ingestion/examples/mce_files/bootstrap_mce.json
Yearly update so that graphs on the stats page in the "past year" view shows multiple data points. This will allow us to test the graphs showing trends over time rather than just a single point when validating releases.
> fix(sample data): Update timestamps in bootstrap_mce.json to more recent

- datahub-frontend/app/auth/AuthModule.java
- datahub-frontend/app/config/ConfigurationProvider.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/SystemUpdateConfig.java
- docs/authentication/guides/add-users.md
- docs/how/updating-datahub.md
- metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SampleDataFixtureConfiguration.java
- metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SearchLineageFixtureConfiguration.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLSpringCommonTestConfiguration.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/ActorContext.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/OperationContext.java
- metadata-operation-context/src/main/java/io/datahubproject/test/metadata/context/TestOperationContexts.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/ActorContextTest.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/OperationContextTest.java
- metadata-service/auth-config/src/main/java/com/datahub/authentication/AuthenticationConfiguration.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/context/SystemOperationContextFactory.java
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/IngestDataPlatformInstancesStepTest.java
* document breaking change to user.props
* add flag for legacy behavior
> feat(auth): user.props authentication

- metadata-ingestion/src/datahub/ingestion/source/gc/execution_request_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- metadata-ingestion/tests/unit/cli/test_cli_utils.py
- metadata-ingestion/tests/unit/test_gc.py
- Use structured reporting for failures
- Use time limit and deletion limit in underlying method so we stop in all threads from deletion
> fix(ingest/gc): logging and stopping fix

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
- metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename_with_temp.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_swap.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_swap_with_temp.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_utils.py
- metadata-ingestion/tests/unit/test_usage_common.py
> fix(ingest): consistent fingerprint for sql parsing aggregator

- metadata-ingestion/docs/sources/snowflake/snowflake_recipe.yml
We always recommend this, especially for someone's first run. the only reason it isn't default already is backward compatibility concerns.
> docs(queries_v2): set use_queries_v2 to true in snowflake_recipe.yml

- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
> fix(ingest/gc): infinite loop query entities

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
While [this](https://github.com/datahub-project/datahub/pull/12239) fixed query fingerprinting consistency for redshift, etc, we would not wish to change query fingerprinting for old snowflake lineage method, as it would impact its performance.
> fix(ingest/snowflake): use fast query fingerprint for lineage

- metadata-ingestion/docs/sources/tableau/tableau_pre.md
> docs(tableau): clarify docs around tableau permissions

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
Having to keep these configs in sync between the snowflake queries extractor and the main snowflake source is a recipe for bugs. Having these split out would be a better long-term solve.
> feat(ingest): configurable query generation in combined sources

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java
For long indexing tasks it is quite helpful to have an estimated time in minutes to understand how long to wait. It can be calculated outside. This makes it easier to find out.
> log(elastic/index builder): add est time remaining

- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
There's a bug in the data process mapper that causes failures under specific conditions:
- When querying data process instance with or without any other entity
- AND when a data process instance actually exists
The solution is to sequence the operations, because:
- By handling the query entities first we can ensure that they will be cleaned up
- Once cleaned, even if the data process query fails it won't affect the query clean up
> fix(ingest/gc): also query data process instance

- .github/scripts/generate_pre_commit.py
- .github/scripts/pre-commit-override.yaml
- .pre-commit-config.yaml
- build.gradle
- settings.gradle
> dev: add pre-commit hooks installed by default

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_config.py
Trying to make the folder_path_pattern option more clear. Linked to [this issue](https://linear.app/acryl-data/issue/CUS-3553/team-what-is-the-best-way-to-whitelist-a-few-looker-folders-on-acryl-i)
> fix(doc): make folder_path_pattern usage more clear

- docs/api/tutorials/structured-properties.md
- metadata-ingestion/examples/structured_properties/list_structured_properties.py
- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
- metadata-ingestion/src/datahub/cli/specific/structuredproperties_cli.py
- metadata-ingestion/tests/unit/structured_properties/test_structured_properties.py
- smoke-test/tests/structured_properties/test_structured_properties.py
Improvement inspired by [this question](https://datahubspace.slack.com/archives/C029A3M079U/p1735253047214489)
- Adds support for listing all structured properties in the API
- Adds a sub-command `list` to the `properties` command in the `datahub` cli
> feat(sdk): structured properties - add support for listing

- .github/.codecov.yml
- .github/workflows/airflow-plugin.yml
- .github/workflows/build-and-test.yml
- .github/workflows/dagster-plugin.yml
- .github/workflows/gx-plugin.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-io.yml
- .github/workflows/prefect-plugin.yml
- gradle/coverage/java-coverage.gradle
- gradle/coverage/python-coverage.gradle
Code coverage carry-forward is tied to flags (used to represent modules/subprojects) and code coverage for a flag can be carried forward if ci optimizations skips a module build. So created a module `flag` for each group of projects that the ci builds together. This roughly corresponds to the groups defined in ci-optimization action.
> build(coverage): fix carry-forward coverage

- build.gradle
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- metadata-utils/build.gradle
> chore(deps): Migrate EOL vulnerability of javax.mail to jakarta.mail

- .github/workflows/build-and-test.yml
The recent upgrade to upload-artifact@v4 broke this workflow due to a backward incompatible change introduced in the action of requiring unique names.
> fix(ci): make upload-artifact name unique

- metadata-ingestion/src/datahub/ingestion/source/aws/s3_util.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/unit/s3/test_s3_source.py
- metadata-ingestion/tests/unit/s3/test_s3_util.py
Fix the group-splitting issue caused by `itertools.groupby` when the **input data is not ordered by the group key**.
- Use `itertools.groupby` for grouping. (group_key: `s3_object.key`)
- Sort s3_objects before grouping. (sort_key: `s3_object.last_modified`)
- Use `defaultdict` for grouping without pre-sorting.
- `itertools.groupby()` generates a new group every time the value of the key function changes, which requires the input data to be sorted.
- This means the input data should be sorted and the **group key must be equal to the sort key** for correct grouping.
```python
from itertools import groupby
data = [1, 1, 2, 1]
for key, val in groupby(data, key=lambda x: x):
print(key, list(val))
sorted_data = sorted(data, key=lambda x: x)
for key, val in groupby(sorted_data, key=lambda x: …
```
> fix(ingestion/s3): groupby group-splitting issue

- metadata-ingestion/src/datahub/ingestion/source/gc/execution_request_cleanup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
- metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
- Add deletion limit execution request
- Add missing fields from template
> fix(ingest/gc): add delete limit execution request

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/tests/unit/urns/test_urn.py
It used be the case that things like SchemaFieldUrn(dataset, field) required dataset to be a string. Now it supports `DatasetUrn` as well.
> feat(sdk): support urns in other urn constructors

- metadata-ingestion/src/datahub/ingestion/graph/client.py
> fix(ingest): improve error reporting in `emit_all`

- metadata-ingestion/src/datahub/cli/delete_cli.py
- metadata-ingestion/src/datahub/cli/migrate.py
`random.choice` picks with replacement, but we want a sample that does not have
duplicates.
> fix(cli/delete): prevent duplicates in delete message

- docs-website/docusaurus.config.js
> fix(header): prevent clickjack/iframing

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
- metadata-ingestion/src/datahub/ingestion/source/demo_data.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect/kafka_connect.py
- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/src/datahub/ingestion/source/mlflow.py
- metadata-ingestion/src/datahub/ingestion/source/nifi.py
- metadata-ingestion/src/datahub/ingestion/source/redash.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source/superset.py
- metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
- metadata-ingestion/tests/unit/api/test_pipeline.py
Supersedes https://github.com/datahub-project/datahub/pull/8620
> fix(ingest): tighten Source.create type annotations

- .github/workflows/metadata-model.yml
> fix(ci): only upload metadata model on root repo

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
> fix(ingest): support async_flag properly in ingestProposalBatch

- build.gradle
- docker/datahub-ingestion/pyspark_jars.sh
> fix(ingestion) fix snappy inconsistent version in ingestion

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
- metadata-ingestion/tests/unit/test_dbt_source.py
Pretty straightforward. Rather than have the redshift "super" type show up as unknown and give a warning, let's add it to the known types. Linked to issue https://linear.app/acryl-data/issue/CUS-3600/2-is-there-a-way-for-acryl-to-handle-super-type-field
> Super type dbt redshift

- settings.gradle
Uses depot under the hook. Requires a `DEPOT_TOKEN`, otherwise is a no-op.
> feat(build): use remote gradle cache

- metadata-ingestion/build.gradle
- metadata-ingestion/developing.md
Now that we have pre-commit hooks, running lintFix is extremely slow because of the mypy checks. Since we only want it to do some auto-formatting, this is a reasonable change.
> chore(ingest): speed up lintFix command

- metadata-ingestion/src/datahub/utilities/urns/_urn_base.py
- metadata-ingestion/tests/unit/urns/test_urn.py
This makes the `from_string` method a lot more flexible - it can now be used for type narrowing on `Union[str, Urn]` usages. This should ideally allow us to remove many of the `guess_entity_type(urn) == "something"` usages littered throughout our codebase.
The docs on the method have also been improved to include some examples, and those examples are tested using doctest.
> feat(sdk): support urn types in Urn.from_string

- .github/workflows/documentation.yml
This should significantly reduce the size of our git repo. My informal checks indicated that the gh-pages branch was responsible for over 50% of our repo size.
Change suggested by https://www.reddit.com/r/rust/comments/wy3j50/psa_if_youre_using_ghpages_to_host_your/
> chore(ci): truncate gh-pages branch history

- metadata-ingestion/build.gradle
- metadata-ingestion/developing.md
- metadata-ingestion/pyproject.toml
- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
- metadata-ingestion/src/datahub/utilities/memory_footprint.py
- metadata-ingestion/tests/unit/utilities/test_cli_logging.py
- metadata-ingestion/tests/unit/utilities/test_lossy_collections.py
Once this is in then can replace black and isort one by one in followup PRs
> dev(ingest): use ruff instead of flake8

- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
- metadata-ingestion/src/datahub/ingestion/source/gc/soft_deleted_entity_cleanup.py
Due to a server bug server was returning with
```
{'count': 1, 'nextScrollId': None, 'searchResults': []}
```
This led to an infinite loop in some cases. Checking for `search_results` to ensure we don't get stuck with infinite loop.
> fix(ingest/gc): infinite loop in getting soft deleted counts

- metadata-ingestion/src/datahub/entrypoints.py
The number of times I have had to tell people to use python 3.11 instead of python 3.12 and that solved the problem is too large. So putting this warning. Not throwing an exception because in many cases it can work.
> feat(cli): for python > 3.11 log a warning

- metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py
- metadata-ingestion/tests/unit/test_tableau_source.py
> fix(ingest/tableau): Fix TableauUpstream create check

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
> feat(datahub) Remove serialVersionUID from constructor

- metadata-ingestion/src/datahub/configuration/config_loader.py
- metadata-ingestion/src/datahub/secret/secret_common.py
- metadata-ingestion/tests/unit/config/test_config_loader.py
Also refactors things into a `EnvResolver` class.
> feat(ingest): add strict_env_syntax mode to config loader

- metadata-ingestion/src/datahub/ingestion/source/gcs/gcs_source.py
- metadata-ingestion/tests/unit/test_gcs_source.py
Remove pipeline name before passing context to equivalent s3 source to avoid error "Checkpointing provider DatahubIngestionCheckpointingProvider already registered." Fixes [this issue](https://github.com/datahub-project/datahub/issues/11790)
> fix(ingestion): fix stateful ingestion for GCS source

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/entitytype/EntityTypeUrnMapper.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/entitytype/EntityTypeMapperTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/entitytype/EntityTypeUrnMapperTest.java
When I tried to create a structured property using the new UI in v0.15.0, I noticed, that it does not work because there is a duplicated entry in the EntityTypeUrnMapper:
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Multiple entries with same key: dataProcessInstance=urn:li:entityType:datahub.dataProcessInstance and dataProcessInstance=urn:li:entityType:datahub.dataProcessInstance [in thread "ForkJoinPool.commonPool-worker-325"]
The duplicated entry was added with #12263.
I have also added some simple tests of EntityTypeUrnMapperTest (and EntityTypeMapperTest) to make sure that duplicated entries will be noticed in the future there. I have not tested the tests locally, we will see whether they work in the CI pipeline.
> fix(graphql): removed duplicated entity in EntityTypeUrnMapper

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py
- metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/src/datahub/utilities/groupby.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_overlapping_inserts.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_overlapping_inserts_from_temp_tables.json
- metadata-ingestion/tests/unit/utilities/test_utilities.py
`itertools.groupby` requires input data to be sorted. While we are sorting in some cases, in many others we aren't, which may lead to incorrect grouping.
This PR introduces again (previously removed in PR #4011) `groupby_unsorted` which removes such a requirement and replaces usage of `itertools.groupby`.
> fix(ingestion): groupby_unsorted

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataprocessinst/mappers/DataProcessInstanceMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/dataprocessinst/mappers/DataProcessInstanceMapperTest.java
- datahub-web-react/src/app/entity/dataProcessInstance/DataProcessInstanceEntity.tsx
- datahub-web-react/src/graphql/dataProcessInstance.graphql
- docs/how/updating-datahub.md
- smoke-test/tests/cypress/data.json
- smoke-test/tests/data_process_instance/test_data_process_instance.py
DataProcessInstance has a similar issue with DataJob - no direct mandatory relationship to a DataPlatform. The relationship is optional through the `dataPlatformInstance` aspect. 
It can also be inferred through the parentTemplate (essentially a relationship to a DataJob or a DataFlow etc.) 
- This PR removes the requirement that the DataProcessInstance graphql type should always return a dataPlatform that is filled out. It also technically makes a backwards incompatible change to the GraphQL type - but since this was a recent commit, and it only affects readers - I think the change is okay to make. 
- We will need a second PR to add the wiring for the parentTemplate to get sent back via the GraphQL type system - for clients (e.g. UI) to render a platform via the dataPlatformInstance or …
> fix(ci): remove platform from dataprocessinstance gql

- metadata-io/src/test/java/io/datahubproject/test/search/SearchTestContainer.java
> misc(test): increase test memory slightly

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/job_models.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
Possible now that https://github.com/datahub-project/datahub/pull/12198 is merged.
> feat(ingest/mssql): populate dataTransformLogic aspect for stored procs

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/tests/unit/urns/test_urn.py
This change mainly applies to urns with a single field. 
All existing functionality is preserved. Technically this is a breaking change if you had tags like `urn:li:tag:urn:li:tag:legacy`, but I don' think that's an important callout.
> feat(sdk): support qualified urn names in simple urn constructors

- .github/workflows/docker-unified.yml
> fix(ci): reduce parallelism

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> fix(slack source): Add retries to pulling information from DataHub

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> fix(ingest/glue): add try catch

- smoke-test/tests/restli/restli_test.py
- smoke-test/tests/restli/test_restli_batch_ingestion.py
> Adding smoke test for batch ingestion throwing exception 

- metadata-ingestion/src/datahub/upgrade/upgrade.py
By fetching the "latest" release, we can ignore prereleases and fetch less data.
> fix(cli): ignore prereleases when suggesting upgrades

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_config.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/tests/integration/lookml/lkml_unreachable_views/data.model.lkml
- metadata-ingestion/tests/integration/lookml/lkml_unreachable_views/employee_income_source.view.lkml
- metadata-ingestion/tests/integration/lookml/lkml_unreachable_views/employee_total_income.view.lkml
- metadata-ingestion/tests/integration/lookml/lkml_unreachable_views/unreachable_view.view.lkml
- metadata-ingestion/tests/integration/lookml/test_lookml.py
> fix(lookml/ingestion): Skip unreferenced or improperly loaded Lookml view files

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> fix(ingest/glue): add info in report

- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
> fix(ci): fix datahub-ingestion release/tag publishing

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/cli/container_cli.py
- metadata-ingestion/src/datahub/ingestion/source/apply/datahub_apply.py
Wrapper on top of `container` CLI underlying implementation to let people use it via managed ingestion
> feat(ingest): add datahub apply source

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source_config/operation_config.py
due to the is_profiling_enabled method getting called for every data set, it spams log output with these info lines.
> refactor(operation_config): change logging on is_profiling_enabled

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema_gen.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_tag.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake_tag.py
> fix(ingest/snowflake): Create all structured propery templates before assignation

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
> chore(bump): bump jmx version

- metadata-ingestion/src/datahub/upgrade/upgrade.py
Skips yanked releases when determining the latest CLI release. This is necessary because we previously released and yanked a 15.0.4 release.
> fix(cli): avoid false positive cli upgrade suggestions

- metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
Replaces list with a LossyList. Also removes the `filtered_tracking` flag - it remains the default. This is in-line with how the rest of our sources track filtered/ignored objects.
> fix(ingest/azure-ad): limit the size of the ingestion report

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
The legacy `SnowflakeQueriesSource` inherits from `SnowflakeQueriesExtractorConfig` and so exposes the config param
https://github.com/datahub-project/datahub/blob/e2b1ed7530f1c4019d331aa98bf9782225a49b5c/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py#L113-L115
and then, uses it
https://github.com/datahub-project/datahub/blob/e2b1ed7530f1c4019d331aa98bf9782225a49b5c/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py#L330-L338
However, the `SnowflakeV2Source` doesn't 
https://github.com/datahub-project/datahub/blob/e2b1ed7530f1c4019d331aa98bf9782225a49b5c/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py#L182-L190
and so the proposal in this PR is to define the config param so it can be passed …
> feat(snowflake): add missing pushdown_deny_usernames config to be used when use_queries_v2

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/RestoreIndices.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
- docs/how/restore-indices.md
> feat(restoreIndices): update restore indices args and docs

- smoke-test/tests/consistency_utils.py
In case we try to run this in a kubernetes environment this causes failures
> fix(test): move reading env variable inside method

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/unit/data_lake/test_path_spec.py
- metadata-ingestion/tests/unit/s3/test_s3_source.py
**Feature Addition:** 
Ignores the paths whose depth dose not match to `path_spec.include` while ingesting S3.
- Retrieves all paths under the prefix.
- Retrieves only paths whose depth matches path_spec.include.
- Warning messages were triggered during S3 ingestion.
- This issue was caused by attempting to ingest paths whose depth does not match `path_spec.include`.
- Since this behavior seems unintended, I propose adding this feature.
```
path_spec: s3://bucket/{table}/{partition0}/*.csv
s3_files:
1. s3://bucket/shop_log/year=2025/month=01/day=01/0000.csv
2. s3://bucket/shop_log/year=2025/month=01/day=02/0000.csv
3. s3://bucket/user_log/2025/0000.csv
============
**Before**
$ python s3_ingestion.py
INFO - Processing folder: datahub-test/shop_log
WARNING - Unable to find any files in the …
```
> feat(ingestion/s3): ignore depth mismatched path

- docs/cli.md
This is adding the pip requirement for the salesforce ingestion source described here https://datahubproject.io/docs/generated/ingestion/sources/salesforce#integration-details (simple-salesforce) to the cli doc.
I tested locally that `pip install acryl-datahub` does not install simple-salesforce, but `pip install acryl-datahub[salesforce]` does.
> docs(salesforce): add missing salesforce source to cli doc

- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/validation/AspectValidationException.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/validation/ValidationExceptionCollection.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/validation/ValidationSubType.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/plugins/validation/ValidationExceptionCollectionTest.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationException.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/GlobalControllerExceptionHandler.java
- smoke-test/tests/openapi/v3/exceptions.json
> feat(openapi): precondition exceptions return 412

- docs/cli.md
Similar to https://github.com/datahub-project/datahub/pull/12550, the exta pip requirement [dbt] is needed to ingest dbt data; without it the cli fails with:
```
datahub.ingestion.run.pipeline.PipelineInitError: Failed to find a registered source for type dbt: dbt is disabled; try running: pip install 'acryl-datahub[dbt]'
```
> doc(dbt): Add missing dbt extra requirement to cli doc

- docs/managed-datahub/operator-guide/setting-up-remote-ingestion-executor.md
> feat(docs): Add live secret reload docs to k8s remote executor page

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/entitytype/EntityTypeUrnMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/structuredproperty/StructuredPropertyMapper.java
- metadata-io/src/main/java/com/linkedin/metadata/structuredproperties/validation/PropertyDefinitionValidator.java
- metadata-io/src/test/java/com/linkedin/metadata/structuredproperties/validators/PropertyDefinitionValidatorTest.java
Previously, if someone used our API they could put invalid `allowedTypes` inside of our `typeQualifier` map. This would result in a busted graphql API because we try to hydrate an entity type entity that doesn't exist. So I took two steps to fix this problem:
1. Harden our graphql API to filter out invalid types. This isn't a perfect solution, but in the case someone had already gotten an invalid type in there, we now won't crash the whole UI. However going forward they should never be in this position because of number 2:
2. Add validation on the property definition validator to ensure that these allowedTypes are valid entity types urns.
> fix(structuredProps) Add validation for allowedTypes and harden API for invalid types

- datahub-web-react/src/app/analyticsDashboard/components/TimeSeriesChart.tsx
Combined with this PR, should fix the analytics charts https://github.com/datahub-project/datahub/pull/12461
Charts for these three currently look like this. They have the full date which isn't necessary. 
After these changes, the charts look like this, without the full month/day/year:
> fix(ui): better experience for analytics charts

- metadata-ingestion/src/datahub/cli/iceberg_cli.py
> fix(iceberg): delete associated platform resources when deleting warehouse

- datahub-web-react/src/app/entityV2/dataset/profile/schema/utils/utils.ts
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/AboutFieldTab.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useDescriptionRenderer.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useExtractFieldDescriptionInfo.ts
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useExtractFieldGlossaryTermsInfo.ts
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useExtractFieldTagsInfo.ts
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useTagsAndTermsRendererFeatureTable.tsx
We had a bug where if ingestion originally had a v1 fieldPath for a column, then a user adds a tag or a term, this adds a v1 fieldPath in editableSchemaMetadata with this tag/term.
Then if ingestion switches to v2 fieldPath, so whenever we add a tag or term, it adds it under editableSchemaMetadata with the v2 fieldPath.
However, the bug here is that we render the editable info for a field for whichever version of the fieldPath we find first in editableSchemaMetadata - so if we find v2 fieldPath first, we render that always. so we never show the new edits to the v2 field path.
My fix here is that for where we display editable info for a field, it should always match exactly what is coming from schemaMetadata either v1 or v2. That way when you edit a field, it always shows your current …
> fix(ui) Show editable field info for fields based on exact fieldPath version

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
> fix(openapi-schema): fix openapi schema generator

- docs/how/updating-datahub.md
- metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java
- smoke-test/tests/openapi/v3/entities.json
This bug is encountered when using url encoding on the url path `/` => `%2F`
workaround: https://github.com/jetty/jetty.project/issues/11890
> fix(url-encoding): fix regression in url encoding

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
> fix(ingest/snowflake): order queries for queries_v2

- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
To prevent this stacktrace from stopping ingestion in the middle
```
File "/tmp/datahub/ingest/venv-unity-catalog-bac61a203a4fea43/lib/python3.10/site-packages/datahub/ingestion/source/unity/source.py", line 467, in process_schemas
yield from self.process_tables(schema)
File "/tmp/datahub/ingest/venv-unity-catalog-bac61a203a4fea43/lib/python3.10/site-packages/datahub/ingestion/source/unity/source.py", line 472, in process_tables
for table in self.unity_catalog_api_proxy.tables(schema=schema):
File "/tmp/datahub/ingest/venv-unity-catalog-bac61a203a4fea43/lib/python3.10/site-packages/datahub/ingestion/source/unity/proxy.py", line 181, in tables
for table in response:
File "/tmp/datahub/ingest/venv-unity-catalog-bac61a203a4fea43/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", …
```
> fix(ingest/unity): add exception handling

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/utilities/ingest_utils.py
- metadata-ingestion/tests/unit/utilities/sample_demo.dhub.yaml
- metadata-ingestion/tests/unit/utilities/test_ingest_utils.py
Allows these options
```
datahub ingest deploy --urn "$URN"  -c ../tmp/demo.dhub.yaml --name demo --extra-pip '["memray"]' --debug true
```
New options allowed are
```
--extra-pip '["memray"]' --debug true
```
Changed the graphql call to be similar to what we do in the UI which makes it easier to change. Add tests by moving code out of `ingest_cli.py` file. Otherwise there were no tests
> feat(cli): add extra pip and debug flag

- metadata-ingestion/setup.cfg
- metadata-ingestion/src/datahub/emitter/mcp_builder.py
- metadata-ingestion/src/datahub/sdk/_attribution.py
- metadata-ingestion/src/datahub/sdk/_entity.py
- metadata-ingestion/src/datahub/sdk/_shared.py
- metadata-ingestion/src/datahub/sdk/_utils.py
- metadata-ingestion/src/datahub/sdk/container.py
- metadata-ingestion/src/datahub/sdk/dataset.py
- metadata-ingestion/src/datahub/sdk/main_client.py
- metadata-ingestion/src/datahub/specific/dataset.py
- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/src/datahub/utilities/sentinels.py
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_browse_path_golden.json
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_dataset_complex_golden.json
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_dataset_ingestion_golden.json
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_owners_add_remove_golden.json
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_tags_add_remove_golden.json
- metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_terms_add_remove_golden.json
- metadata-ingestion/tests/unit/sdk_v2/entity_client_goldens/test_container_update_golden.json
- metadata-ingestion/tests/unit/sdk_v2/entity_client_goldens/test_dataset_update_golden.json
- metadata-ingestion/tests/unit/sdk_v2/test_container.py
- metadata-ingestion/tests/unit/sdk_v2/test_dataset.py
- metadata-ingestion/tests/unit/sdk_v2/test_entity_client.py
- Add special sentinel values for unset and auto, in a way that works with type checking
- Refactor container / browse path init code
- Rename `container` -> `parent_container` in constructors
- Add getter for platform
- Add getter for parent container and browse path
- Add add/remove tag/term methods on both entities and schema fields
- Add add/remove owners methods for all entity types
> feat(sdk): add/remove methods + other small improvements

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_structured_properties_golden.json
Earlier snowflake apis returned 'HYBRID TABLE' as table_type in INFORMATION_SCHEMA.TABLES view. Behavior has been updated recently to use table_type as 'BASE TABLE' and IS_HYBRID column as marker.
https://docs.snowflake.com/en/sql-reference/info-schema/tables
> fix(ingest/snowflake): update logic to identify hybrid tables

- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion/build.gradle
> dev: reduce log in gradle commands

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/incident/EntityIncidentsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/incident/IncidentUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/incident/RaiseIncidentResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/incident/UpdateIncidentResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/incident/UpdateIncidentStatusResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/incident/IncidentMapper.java
- datahub-graphql-core/src/main/resources/incident.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/incident/EntityIncidentsResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/incident/IncidentInfoMatcher.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/incident/IncidentUtilsTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/incident/RaiseIncidentResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/incident/UpdateIncidentResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/incident/IncidentMapperTest.java
- datahub-web-react/src/graphql/incident.graphql
- datahub-web-react/src/graphql/mutations.graphql
- docs/how/updating-datahub.md
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/incident/IncidentsSummaryHook.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/incident/IncidentsSummaryHookTest.java
- metadata-models/src/main/pegasus/com/linkedin/incident/IncidentAssignee.pdl
- metadata-models/src/main/pegasus/com/linkedin/incident/IncidentInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/incident/IncidentStatus.pdl
- metadata-service/services/src/main/java/com/linkedin/metadata/search/utils/QueryUtils.java
- metadata-service/services/src/test/java/com/linkedin/metadata/search/utils/QueryUtilsTest.java
- smoke-test/tests/incidents/incidents_test.py
In this PR, we bring our new changes for the Incidents V2 model to the Open Source repository. 
1. Add support for stage, priority, assignee, resources to incident model PDL
2. Introduce new update incident resolver
3. Evolve existing endpoints to support new fields
4. Unit tests
> chore(): Bring latest incidents data model + GraphQL to OSS

- entity-registry/src/main/java/com/linkedin/metadata/utils/SystemMetadataUtils.java
- entity-registry/src/test/java/com/linkedin/metadata/utils/SystemMetadataUtilsTest.java
- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/trace/TraceServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/AspectDaoTest.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/trace/TraceServiceImplTest.java
Handle expected tracing output when no change to record template AND the trace id matches. The difference is that in this case the downstream storage change in ES is also an expected NO_OP.
Also prevent duplicate equality checks when determining the no op state.
> fix(tracing): handle noop mcl

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
- datahub-web-react/src/app/searchV2/filters/value/EntityValueMenu.tsx
- datahub-web-react/src/app/searchV2/filters/value/utils.tsx
Our advanced search builder which is used when clicking "+add filter" in the search experience and when building view filters was broken in one way and not optimal in another.
1. Platforms were not able to be searched for using auto-complete. So platform filters in views were completely broken. I added autocomplete functionality for it on the backend so things are good now.
2. We didn't do an initial search for dropdowns that should show some initial data, so it required that you type something in the search bar before you see any results. Now i add that initial search to pre-populate data.
**screenshots of it working now:**
> fix(filters) Fix autocomplete for platforms and improve advanced search builder

- .github/workflows/python-build-pages.yml
This PR won't have any datahub-wheels. But PRs after this one will have it.
> feat(build): use `pull_request_target` for datahub-wheels

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/lineage/UpdateLineageResolver.java
- datahub-web-react/src/app/lineage/manage/ManageLineageModal.tsx
- datahub-web-react/src/app/lineageV2/manualLineage/ManageLineageModal.tsx
- docker/datahub-gms/Dockerfile
- docs/features/feature-guides/ui-lineage.md
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyFetcher.java
- show proper error message in case user does not have privilege on upstream
- change some `log.debug(String.format` to `log.debug(` on java side
- move copying `war` to later as rest of items are less frequently changed. Will very slightly help with dev workflow for gms
- add note that you need privilege on both upstream and downstream entity when editing lineage.
> fix(lineage): error message for edit lineage

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/sql/druid.py
- metadata-ingestion/tests/integration/druid/golden/druid_mces.json
- metadata-ingestion/tests/unit/test_druid_source.py
If the platform instance was specified in a Druid ingestion, it was always set twice, because it was overrided in the get_identifier, and then added again down the line (see https://github.com/datahub-project/datahub/issues/11639).
This may break existing users that already rely on the broken platform instance implementation, but they could still manually set it to the old pattern in their dhub file.
- [ x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ x] Links to related issues (if applicable)
https://github.com/datahub-project/datahub/issues/11639 …
> Fix platform instance support on Druid ingestion

- .github/.codecov.yml
> ci(coverage): update patch coverage threshold

- datahub-web-react/src/app/entityV2/group/GroupInfoHeaderSection.tsx
- datahub-web-react/src/app/entityV2/group/GroupMembersSidebarSectionContent.tsx
- datahub-web-react/src/app/entityV2/group/GroupProfile.tsx
- datahub-web-react/src/app/entityV2/group/GroupSidebarMembersSection.tsx
- datahub-web-react/src/app/entityV2/group/types.ts
- datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/SidebarSection.tsx
There were several inconsistencies on the group page regarding the number of members in a group.
1. On the top left of the page we showed a max count of 15 since we were dislaying the number of members we retrieved from our call, not the total number of members
2. Same thing on the left sidebar, it was wonky and made you think you only had 15. now, if there's more, i display a new link to "View all members" that takes you to the members tab to do a look at all the members of the group.
> fix(ui) Fix group membership inconsistencies on group page

- datahub-web-react/src/app/entity/shared/components/styled/search/downloadAsCsvUtil.ts
- datahub-web-react/src/app/entityV2/shared/components/styled/search/downloadAsCsvUtil.ts
There was a report where downloading results with groups in them were not getting the display name of the asset properly. This fixes that in v1 and v2 UIs for all entity types.
> fix(ui) Properly get display name when downloading search results

- metadata-ingestion/src/datahub/cli/lite_cli.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/tests/integration/powerbi/test_admin_only_api.py
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
- metadata-ingestion/tests/integration/powerbi/test_powerbi.py
- metadata-ingestion/tests/integration/powerbi/test_profiling.py
- metadata-ingestion/tests/integration/powerbi_report_server/test_powerbi_report_server.py
- metadata-ingestion/tests/integration/qlik_sense/test_qlik_sense.py
- metadata-ingestion/tests/integration/sigma/test_sigma.py
- metadata-ingestion/tests/integration/superset/test_superset.py
- metadata-ingestion/tests/test_helpers/mce_helpers.py
- metadata-ingestion/tests/test_helpers/test_connection_helpers.py
- metadata-ingestion/tests/unit/api/source_helpers/test_auto_browse_path_v2.py
> dev: immutable args remove

- docker/kafka-setup/Dockerfile
> chore(bump): Bump kafka-setup base

- .github/workflows/python-build-pages.yml
In #12722 and https://github.com/datahub-project/datahub/pull/12730 I attempted to make the cloudflare pages builds work on PRs from forks. It turns out cloudflare's pages-action had issues with PRs from forks, and we started seeing errors (e.g.
https://github.com/datahub-project/datahub/actions/runs/13552436222/job/37879053347?pr=12732) when we tried an alternative action that used direct uploads.
Maybe in the future we'll revisit this, but for now it's not worth the effort.
> revert(ci): revert datahub-wheel build changes

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/unit/s3/test_s3_source.py
- Refactor `S3Source().get_folder_info()` to enhance readability
- Add a test to ensure `get_folder_info()` returns the expected result.
> refactor(ingest/s3): enhance readability

- metadata-ingestion/setup.py
See https://github.com/confluentinc/confluent-kafka-python/issues/1927
> chore(ci): avoid dep on confluent-kafka 2.8.1

- metadata-ingestion/src/datahub/ingestion/source/file.py
- metadata-ingestion/tests/unit/serde/test_domain_properties.json
- metadata-ingestion/tests/unit/serde/test_invalid_object.json
- metadata-ingestion/tests/unit/serde/test_serde.py
> feat(ingest): improve error messages for unknown metadata objects

- datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearch.tsx
> fix(web) accurate error message for embeddedlistsearch

- metadata-ingestion/src/datahub/ingestion/source/metadata/lineage.py
> fix(ingest): support pydantic v2 in file-based lineage

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/trace/KafkaTraceReader.java
- metadata-io/src/test/java/com/linkedin/metadata/search/ElasticSearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/ESSearchDAORawEntityTest.java
- metadata-io/src/test/java/com/linkedin/metadata/trace/BaseKafkaTraceReaderTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/ElasticsearchController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/kafka/KafkaController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/kafka/KafkaOffsetResponse.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/operations/elastic/ElasticsearchControllerTest.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/operations/kafka/KafkaControllerTest.java
- metadata-service/services/src/main/java/com/linkedin/metadata/search/EntitySearchService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/search/EntitySearchServiceTest.java
> feat(operations): ES and Kafka Operations Endpoints

- metadata-service/iceberg-catalog/pyproject.toml
- metadata-service/iceberg-catalog/src/integrationTest/integration_test.py
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/Utils.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubRestCatalogTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/UtilsTest.java
listNamespaces now returns the namespace names without the platform instance prefix (which is required in the container hierarchy. 
Added tests
Integrations tests now revert to creating nested namespaces (which was disabled as a workaround due to a springboot config issue that was blocking namespace separators, but has now fixed)
> fix(iceberg): listnamespaces includes warehouse name as root

- datahub-web-react/src/app/searchV2/autoComplete/AutoCompleteEntity.tsx
Fixes the order of parent containers on autocomplete entity items in the V2 UI - we were reversing these containers in `AutoCompleteEntity` since we wanted to display the top level containers first. Well in the V2 UI we updated the `ParentContainers` component to also reverse these passed in entities, which resulted in reverting back to the wrong order. Now we are showing containers in the correct order.
> fix(ui) Fix order of parent containers on v2 autocomplete item

- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceOptimizationTest.java
> fix(test): handle empty log

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchAcrossLineageResolver.java
- datahub-graphql-core/src/main/resources/search.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/search/ScrollAcrossLineageResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/search/SearchAcrossLineageResolverTest.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/elasticsearch/FilterUtils.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/FilterUtilsTest.java
This was a bug from bringing over the V2 UI where the backend wasn't built to support views and sorting while the UI was. This PR adds support for those functionalities in impact analysis. In order to do that I created a new utils class with associated tests.
> fix(lineage) Support views and sorting in impact analysis

- docs-website/sidebars.js
- docs/cli-commands/dataset.md
- docs/cli.md
- metadata-ingestion/examples/structured_properties/click_event.avsc
- metadata-ingestion/examples/structured_properties/dataset.yaml
- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
- metadata-ingestion/src/datahub/cli/specific/dataset_cli.py
- metadata-ingestion/src/datahub/pydantic/compat.py
- metadata-ingestion/tests/unit/api/entities/structuredproperties/example_structured_properties_golden.json
- metadata-ingestion/tests/unit/cli/dataset/test_dataset_cmd.py
- metadata-ingestion/tests/unit/cli/dataset/test_resources/dataset.yaml
- smoke-test/tests/cli/dataset_cmd/test_dataset_command.py
- smoke-test/tests/structured_properties/test_dataset.yaml
- smoke-test/tests/structured_properties/test_structured_properties.py
- smoke-test/tests/structured_properties/test_structured_properties.yaml
> dataset cli - add support for schema, round-tripping to yaml

- metadata-models/src/main/resources/entity-registry.yml
Subtypes are useful. Most entities should have them. 
This PR adds subtypes to most of the entities in the metadata model. 
This PR does NOT add support for GQL mapping or rendering these subtypes in the UI. 
That will be covered by a subsequent PR.
> feat(models): adds subtypes to most entities in the model

- metadata-ingestion/pyproject.toml
- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/test_packaging.py
From today we are pulling `types-setuptools==75.8.2.20250305`, and we are having this exception
```
tests/unit/test_packaging.py:11: error: Library stubs not installed for "pkg_resources"  [import-untyped]
tests/unit/test_packaging.py:11: note: Hint: "python3 -m pip install types-setuptools"
tests/unit/test_packaging.py:11: note: (or run "mypy --install-types" to install all missing stub packages)
tests/unit/test_packaging.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
which matches with this PR from yesterday https://github.com/python/typeshed/pull/13369
Stubs are not required since `setuptools>=71.1.0`
> [!NOTE]  
> Unfortunately only solved with the `ignore` mypy hint
> fix: fixes mypy complaints about pkgresources

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/unit/sdk/test_mce_builder.py
> fix(ingestion): fixes producing some URNs with reserved characters

- metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
- metadata-ingestion/tests/integration/okta/okta_mces_golden_custom_user_name_regex.json
- metadata-ingestion/tests/integration/okta/okta_mces_golden_default_config.json
- metadata-ingestion/tests/integration/okta/okta_mces_golden_include_deprovisioned_suspended_users.json
- metadata-ingestion/tests/integration/okta/okta_mces_golden_ingest_groups_users.json
> feat(okta): custom properties for okta user

- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_common.py
- metadata-ingestion/tests/integration/oracle/golden_test_ingest_with_database.json
- metadata-ingestion/tests/integration/oracle/golden_test_ingest_with_out_database.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_create_view_as_select.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_oracle_case_insensitive_cols.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_complex_ctes.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_ctes.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> fix(ingest): enable fuzzy case resolution for oracle sql

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/domain/DomainType.java
- datahub-web-react/src/app/domain/DomainsList.tsx
- datahub-web-react/src/app/domain/utils.ts
- datahub-web-react/src/app/entityV2/shared/containers/profile/header/IconPicker/IconColorPicker.tsx
- datahub-web-react/src/graphql/domain.graphql
- datahub-web-react/src/graphql/fragments.graphql
- datahub-web-react/src/graphql/glossaryNode.graphql
- datahub-web-react/src/graphql/preview.graphql
- datahub-web-react/src/graphql/search.graphql
- metadata-models/src/main/resources/entity-registry.yml
There were a few bugs related to changing the color and icon for a domain that are fixed in this PR:
- add the aspect to the entity registry (added it for glossary nodes too as they were missing)
- fetch this aspect when loading a domain
- query for this aspect from the UI
- fix weird debounce behavior in UI where we save changing the icon and color before we click "save" in the modal.
> fix(ui) Fix changing color and icon for domains in UI

- docs/iceberg-catalog.md
> doc(iceberg): iceberg doc updates

- docs/how/updating-datahub.md
- entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/MCPItem.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ChangeItemImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/DeleteItemImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/MCLItemImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/PatchItemImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ProposedItem.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationApiUtils.java
- metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImplTest.java
- metadata-io/src/test/java/com/linkedin/metadata/aspect/hooks/IgnoreUnknownMutatorTest.java
- metadata-io/src/test/java/com/linkedin/metadata/client/JavaEntityClientTest.java
- metadata-jobs/mce-consumer/build.gradle
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessor.java
- metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessorTest.java
- metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/GlobalControllerExceptionHandler.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
- metadata-service/restli-servlet-impl/src/test/java/com/linkedin/metadata/resources/entity/AspectResourceTest.java
- smoke-test/tests/openapi/v3/exceptions.json
* Returns 400 even when using async modes
* Rest.li and OpenAPI
> feat(api): URN, Entity, and Aspect name Async Validation

- datahub-web-react/src/app/previewV2/BrowsePaths.tsx
- datahub-web-react/src/app/previewV2/ContextPath.tsx
- datahub-web-react/src/app/previewV2/ContextPathEntityLink.tsx
Same changes as: https://github.com/acryldata/datahub-fork/pull/5251/files
> fix(UI): Showing platform instances only once

- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/search/client/CacheEvictionService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/client/CacheKeyMatcher.java
- metadata-io/src/main/java/com/linkedin/metadata/search/client/CachingEntitySearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/client/UrnCacheKeyMatcher.java
- metadata-io/src/test/java/com/linkedin/metadata/search/client/CacheEvictionServiceTest.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/CachingEvictionServiceFactory.java
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouse.java
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubRestCatalog.java
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/rest/secure/AbstractIcebergController.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouseTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubRestCatalogTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/AbstractControllerTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergConfigApiControllerTest.java
> fix: search cache invalidation for iceberg entities

- metadata-ingestion/tests/integration/oracle/golden_test_error_handling.json
https://github.com/datahub-project/datahub/pull/12778 and https://github.com/datahub-project/datahub/pull/11867 were merged around the same time but conflicted with each other. CI was green for both PRs but was not after the second one was merged.
> fix(ingest/oracle): refresh golden files

- build.gradle
- datahub-web-react/build.gradle
- gradle/versioning/versioning-global.gradle
- gradle/versioning/versioning.gradle
- metadata-events/mxe-schemas/build.gradle
- metadata-events/mxe-utils-avro/build.gradle
- metadata-integration/java/versioning.gradle
- metadata-io/build.gradle
- metadata-jobs/mae-consumer/build.gradle
- metadata-jobs/mce-consumer/build.gradle
- metadata-jobs/pe-consumer/build.gradle
- metadata-models/build.gradle
Multiple fixes: 
Fixes in some misconfigured clean tasks
Some clean tasks incorrectly ran clean during configure phase -- which meant clean was *always* run even if not invoked.
Combine copy and rename into single task for metadata-events/mxe-schemas/build.gradle
Having these as two separate tasks caused copy to always be out-of-date when rename is run, and rename to be out-of-date when copy is done. Gradle does not like inplace updates of any files. By combining it, the copy+rename now will appear to produce a new artifact that will be up-to-date if no sources have changed. This caused lot of downstream jars to get rebuilt since this jar is always out-of-dat and rebuilt everytime.
Reuse versioning and git properties by running once at root project and copy the git.properties for all …
> fix(build): build improvements to help with incremental builds

- docs-website/docusaurus.config.js
- docs-website/src/theme/Layout/index.js
This reverts commit b9f3d07455873c67b48b23123bccbcc5a5daf9ed / PR #12831 with a rotated API key.
> fix(doc): re-enable Algolia search

- datahub-web-react/src/graphql/browseV2.graphql
- datahub-web-react/src/graphql/fragments.graphql
As it is now supported that dashboards can contain other dashboards (#11529) it would also make sense to represent this in the browse path v2 in case a dashboard is only included in a single dashboard (same as for the charts).
Question: Shouldn't we just support all entities as part of the browse path v2 to avoid having to update the query and fragment in the future? I think technically urns of all entity types could be used as part of the browse path v2?
> feat(ui): support all entities with display names in browse paths v2

- datahub-web-react/src/app/search/SimpleSearchFilters.tsx
- datahub-web-react/src/app/search/utils/constants.ts
- datahub-web-react/src/app/searchV2/SimpleSearchFilters.tsx
There's a few filters we get back by default in impact analysis that we don't actually want to show in the UI. We already have a way to hide default filters, so this PR just extends that to hide these two we noticed.
> fix(ui) Hide default filters we want to hide from impact analysis

- datahub-web-react/src/app/entityV2/shared/EntityDropdown/UpdateDeprecationModal.tsx
Fixes auto-submitting deprecation when selecting a replacement by setting the button type to `button` instead of the default `submit`
> fix(ui) Fix submitting when selecting replacement in deprecation modal

- metadata-ingestion/src/datahub/ingestion/source/dynamodb/dynamodb.py
Without this all datasets will have `PROD` irrespective of what is passed in the config.
> fix(ingest/dynamodb): pass env to dataset urn function

- datahub-web-react/src/app/entity/shared/ExternalUrlButton.tsx
- datahub-web-react/src/app/entityV2/shared/utils.ts
Update ExternalUrlButton to include self-hosted gitlab URLs. `gitlab.com` is not part of the URL for self hosted Gitlab instances. `gitlab.` will help us cover it
> feat(ui): Update ExternalUrlButton to include self-hosted gitlab URLs

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/GlossaryNodeType.java
Fixes an issue where we were not seeing glossary nodes in the autocomplete dropdown when searching for entities to add as a value on a structured property. The problem was that glossary nodes weren't supported in autocomplete, now they are.
> fix(ui) Support glossary nodes in autocomplete

- metadata-ingestion/src/datahub/ingestion/source/unity/ge_profiler.py
This fixes the following exception where a `TimeoutError` during profiling is not properly catch and so failing abruptly the pipeline.
```
[2025-02-27 04:16:58,824] ERROR    {datahub.ingestion.run.pipeline:741} - Ingestion pipeline threw an uncaught exception: 158 (of 220) futures unfinished
File "/tmp/datahub/ingest/venv-databricks-e1b1ec025dd01f46/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 466, in run
for wu in itertools.islice(
File "/tmp/datahub/ingest/venv-databricks-e1b1ec025dd01f46/lib/python3.10/site-packages/datahub/ingestion/source/state/stale_entity_removal_handler.py", line 72, in auto_stale_entity_removal
for wu in stream:
File "/tmp/datahub/ingest/venv-databricks-e1b1ec025dd01f46/lib/python3.10/site-packages/datahu …
```
> fix(ge-profiler): catch TimeoutError

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
Fixes a couple of exceptions:
offset as bigint instead of int
```
"depop_production.datalake_silver.tracking_product_view_by_product_id_v2.event_timestamp <class 'sqlalchemy.exc.DatabaseError'>: (databricks.sql.exc.ServerOperationError) [INVALID_LIMIT_LIKE_EXPRESSION.DATA_TYPE] The limit like expression \"10005558678\" is invalid. The offset expression must be integer type, but got \"BIGINT\". SQLSTATE: 42K0E; line 4 pos 16\n[SQL: SELECT event_timestamp \nFROM depop_production.datalake_silver.tracking_product_view_by_product_id_v2 \nWHERE event_timestamp IS NOT NULL ORDER BY event_timestamp\n LIMIT %(param_1)s OFFSET %(param_2)s]\n[parameters: {'param_1': 2, 'param_2': 10005558678}]\n(Background on this error at: https://sqlalche.me/e/14/4xp6)",
```
`order by` may consume too much …
> fix(databricks): fixes profile median

- metadata-ingestion/src/datahub/cli/ingest_cli.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/12621
> fix(ingest): fix error in deploy command

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/examples/transforms/example.Dockerfile
- metadata-ingestion/examples/transforms/owners.json
- metadata-ingestion/examples/transforms/recipe.dhub.yaml
- metadata-ingestion/examples/transforms/setup.py
> docs(ingest): custom transformer remote executor

- metadata-ingestion/src/datahub/ingestion/source/sql/hive.py
- metadata-ingestion/tests/integration/hive/hive_mces_all_db_golden.json
- metadata-ingestion/tests/integration/hive/hive_mces_golden.json
> feat(ingest/hive): identify partition columns in hive tables

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
- metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
For table renames `operationType` in `object_modified_by_ddl` dictionary is `ALTER`. We need to check `query_type` to see whether it was table-rename-kind-of-alter. Taking this into consideration I added this value to `parse_ddl_query`. Considering pre-existing logic there I had to swap order of `if` conditions to achieve intended behavior (the logic didn't change beyond that).
> fix(ingest/snowflake): Fixing table rename query handling

- metadata-ingestion/src/datahub/ingestion/source/vertexai.py
Fixes an issue due to a concurrent merge: https://github.com/datahub-project/datahub/pull/12815
> fix(ingest): fix formatting to resolve lint error

- docs-website/docusaurus.config.js
- docs-website/src/pages/_components/SocialMedia/index.js
- docs-website/src/theme/Navbar/learnCardDropdownContent.js
Medium seems to be having a hard time routing to our custom domain. 
Fixing the top-level blog links so people can at least navigate to it from the main menu bar.
> docs: making top level blog links point to medium directly

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/testing/mcp_diff.py
> fix(ingest): pin lookml liquid dep

- metadata-ingestion/src/datahub/ingestion/source/superset.py
[dp.parse()](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse) takes timestr – A string containing a date/time stamp as argument. When passing "now" as an argument to it, it fails with 
```
Python 3.9.6 (default, Nov 11 2024, 03:15:38)
[Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil.parser as dp
>>> dp.parse("now")
File "<stdin>", line 1, in <module>
File "/Users/shuixi.li/Library/Python/3.9/lib/python/site-packages/dateutil/parser/_parser.py", line 1368, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/Users/shuixi.li/Library/Python/3.9/lib/python/site-packages/dateutil/parser/_parser.py", line 643, in parse
raise …
```
> fix(ingestion/superset): fixed changed_on_utc value being a string

- metadata-ingestion/src/datahub/ingestion/source/data_lake_common/path_spec.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_allow_table.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_deny_table.json
- metadata-ingestion/tests/integration/s3/sources/s3/allow_table.json
- metadata-ingestion/tests/integration/s3/sources/s3/deny_table.json
- metadata-ingestion/tests/unit/data_lake/test_path_spec.py
1. `s3_source` trying ingest all folders in `path_spec.include` and this noisily triggers the warning messages.
```
path_spec.include: s3://bucket/path/{table}/{partition0}
s3 files
1. s3://bucket/shop_log/year=2025/month=01/day=01/0000.csv  # error
2. s3://bucket/visit_log/year=2025/month=01/day=02/0000.csv  # error
3. s3://bucket/user_log/2025/0000.csv
==== start s3 ingestion
--- noisy logs---
INFO - Processing folder: datahub-test/shop_log
INFO - Getting files from folder: s3://bucket/datahub-test/shop_log/year=2025/
WARNING - Unable to find any files in the folder s3://bucket/datahub-test/shop_log/year=2025/. Skipping...
INFO - Processing folder: datahub-test/visit_log
INFO - Getting files from folder: s3://bucket/datahub-test/visit_log/year=2025/
WARNING - Unable to find any files in …
```
> feat(ingest/s3): add table filtering

- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
The schemaField entity does not support globalTags or glossaryTerms aspects, so this code would always throw an error. We already fill out tags/terms when building schema metadata. This has been a bug ever since https://github.com/datahub-project/datahub/pull/10089 and was not caught as part of https://github.com/datahub-project/datahub/pull/12764.
> fix(cli): fix unknown aspect bug in dataset upsert cli

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_tests.py
- metadata-ingestion/src/datahub/sdk/entity.py
- metadata-ingestion/src/datahub/sdk/entity_client.py
- metadata-ingestion/tests/test_helpers/sdk_v2_helpers.py
Also expands the `auto_workunit` helper to be a bit more flexible on types, allowing it to be used in more places.
> feat(ingest): allow MCPWs instead of workunits

- .github/workflows/build-and-test.yml
Branch protection rules require build and test workflow to run for all PRs, but the ignore path spec causes this workflow to not run on doc only PRs, and those PRs cannot be merged without selecting bypass branch protection rules. . The CI optimization will anyway cause the doc-only PRs to not run through the full set of tests, after just a few steps without the full tests.
> ci(docs): adjust build and test workflow for doc only PRs

- metadata-ingestion/src/datahub/emitter/request_helper.py
- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/integration/mode/test_mode.py
The main bug here was a missing `response.raise_for_status()` error. That would cause requests that returned a 401 / other error to silently pass validation. The second issue was that our response parsing logic was very lenient on missing fields, causing us to think there were just no spaces returned when auth might've failed beforehand.
To debug this, I also improved the error request logging to show curl-equivalents for every request made, with secrets redacted of course.
> feat(ingest/mode): fix issue in mode request validation

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
This way, type checkers will be able to flag deprecated calls. In VSCode, those calls with show the method name with a line through it.
> chore(ingest): use typing-aware deprecation type

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceImplTest.java
>  c.l.m.entity.ebean.EbeanAspectDao:761 - Retryable PersistenceException: Lazy loading failed on
> Caused by: jakarta.persistence.EntityNotFoundException: Lazy loading failed on
> fix(entity-service): fix delete non-existent row

- datahub-web-react/src/app/entityV2/shared/embed/UpstreamHealth/UpstreamEntitiesList.tsx
- datahub-web-react/src/app/entityV2/shared/embed/UpstreamHealth/UpstreamHealth.tsx
- datahub-web-react/src/app/homeV2/reference/sections/EntityLink.tsx
- datahub-web-react/src/app/homeV2/reference/sections/EntityLinkList.tsx
- datahub-web-react/src/app/search/utils/constants.ts
- datahub-web-react/src/app/searchV2/filters/render/acrylRenderers.ts
- datahub-web-react/src/app/searchV2/filters/render/deprecation/DeprecationFilter.tsx
- datahub-web-react/src/app/searchV2/filters/render/deprecation/DeprecationRenderer.tsx
- datahub-web-react/src/app/searchV2/filters/render/shared/BooleanSearchFilter.tsx
- datahub-web-react/src/app/shared/health/healthUtils.tsx
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchFieldConfig.java
- metadata-models/src/main/pegasus/com/linkedin/common/Deprecation.pdl
2 important changes here:
1. Adding the ability to filter by "is deprecated" for an asset. Screenshots below.
2. Adding the ability to view deprecated assets in the upstream health indicator in the lineage component of the sidebar.
> feat(ui): Support for Filtering by Deprecated, Showing Deprecation in Upstream Health Indicator

- metadata-ingestion/setup.cfg
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/emitter/response_helper.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/errors.py
- metadata-ingestion/tests/unit/datahub/emitter/test_response_helper.py
- metadata-ingestion/tests/unit/sdk/test_rest_emitter.py
> fix(ingest): warn when API tracing is unexpectedly inactive

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/tests/unit/test_rest_sink.py
While https://github.com/datahub-project/datahub/pull/13008 is blocked, it still makes sense to get this out.
Also throws an error to make it clearer when OpenAPI is not supported.
> fix(ingest): make emitter endpoint fully env-controlled

- .github/workflows/airflow-plugin.yml
- docs/how/updating-datahub.md
- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/tox.ini
As part of https://github.com/datahub-project/datahub/pull/12982, we need to depend on `typing-extensions` 4.5.0. The constraint files Airflow 2.3 and 2.4 require 4.4.0 or older.
I was considering reverting that change, but decided that we should be dropping support for Airflow <2.5 anyways. We haven't been compatible with the constraints for those for a while, and our telemetry shows that they don't have much usage anymore (just a handful of stragglers representing ~0.5% of our Airflow plugin users).
> fix(airflow): drop airflow 2.3 and 2.4 support

- entity-registry/src/main/java/com/linkedin/metadata/models/registry/LineageRegistry.java
- entity-registry/src/test/java/com/linkedin/metadata/models/registry/LineageRegistryTest.java
- smoke-test/tests/cypress/cypress/e2e/lineage/download_lineage_results.js
- smoke-test/tests/cypress/cypress/e2e/lineageV2/v2_download_lineage_results.js
The getEntitiesWithLineageToEntityType function is used to get a list of related entities to use as a filter when computing the lineage. This list was considering only only those entities that are directly related to the entity whose lineage is being computed. This needs to expand to entities that are indirectly related via more than one hop.
> fix(lineage): lineage incorrect for some entities

- entity-registry/src/main/java/com/linkedin/metadata/aspect/hooks/OwnershipOwnerTypes.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/hooks/OwnershipOwnerTypeTest.java
- metadata-models/src/main/resources/entity-registry.yml
Currently when ownership aspect is sent the internal `ownerTypes` was not being populated. This can cause the search filtering to not work. This adds a mutator for ownership so the ownerTypes is filled correctly.
> fix(ingest): add mutator for ownership types

- metadata-ingestion/src/datahub/errors.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/graph/filters.py
- metadata-ingestion/src/datahub/sdk/search_client.py
- metadata-ingestion/src/datahub/sdk/search_filters.py
- metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
- Fixes a bug in the handling of extra_of_filters in generate_filter.
- Enables searches across entities on entity types that are not in the default searchable list.
> fix(sdk): fix bugs in v2 sdk search client

- docs-website/generateDocsDir.ts
> docs: hide rc releases from autogenerated docs

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/utilities/ingest_utils.py
`executor_id` and `time_zone` values set in the `deployment` block of a recipe are not being used by `datahub ingest deploy` cli command when deploying recipes. This is because the [cli values take precedence over deployment config](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/utilities/ingest_utils.py#L63), so where the cli has default values these as always used.
Default values should be set in [`DeployOptions`](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/utilities/ingest_utils.py#L23), not in the cli options.
> fix(cli): stop deployment config being overwritten by cli defaults

- metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
`fail_safe_threshold` in `StatefulStaleMetadataRemovalConfig` is currently hidden from the docs. This this be included in the docs as it's a useful configuration and has a default value set that could catch users out. It's also being omitted from the [ingestion JSON Schema](https://datahubproject.io/schemas/datahub_ingestion_schema.json), so IDE syntax validation and other json schema validations fail for valid recipe. 
It looks like this [stateful ingestion failsafe was disabled](https://github.com/datahub-project/datahub/commit/4db51b4c4f2b78173892e204bc0ca980c599f834) and config hidden. When [failsafe was re-enabled](https://github.com/datahub-project/datahub/commit/37bc423b50d5157a0dc9b6617cec288b498fe437) the config was not unhidden.
> docs(ingest): make fail_safe_threshold config visable in docs

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/AbstractMCLStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/schemafield/GenerateSchemaFieldsFromSchemaMetadataStep.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityUtils.java
- smoke-test/tests/openapi/v3/aspects.json
- smoke-test/tests/utilities/concurrent_openapi.py
The error that is fixed is when using the endpoint for fetching versions > 0 (0 represents the latest version).
There is logic which handles the case when the requested version, say 10, is requested however the row in the database is actually 0. Instead of performing 2 round trips to the database (fetch version 10 and finding out it doesn't exist and then fetching version 0 to see if it is version 10), we perform a single query to fetch both versions 0 and 10 in 1 query.
The regression here is when version 10 exists and version 0 (in the database) represents say version 11. In this case we need to return the correct version of the two retrieved aspects. This wasn't possible since a utility method which converts a raw row from the database into another class failed to set a field which …
> fix(openapi): restore openapi v3 aspect version endpoint

- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceOptimizationTest.java
The *test* code analyzes SQL log statements, however the upstream code will log statements from concurrent tests. This tries to address the log parsing by splitting the txn statements better to be filtered by an expected string in each statement.
> fix(test): improve test stability

- datahub-web-react/src/app/domainV2/nestedDomains/DomainsSidebarHeader.tsx
- datahub-web-react/src/app/domainV2/nestedDomains/ManageDomainsSidebar.tsx
- datahub-web-react/src/app/glossaryV2/GlossarySidebar.tsx
- datahub-web-react/src/app/searchV2/sidebar/BrowseSidebar.tsx
- Updated all four files to use the correct IconProps format:
- DomainsSidebarHeader.tsx
- ManageDomainsSidebar.tsx
- GlossarySidebar.tsx
- BrowseSidebar.tsx
> fix(lint): update icon props in sidebar components to match IconProps type

- .github/workflows/docker-unified.yml
- datahub-frontend/build.gradle
- datahub-upgrade/build.gradle
- docker/build.gradle
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
- docker/elasticsearch-setup/build.gradle
- docker/kafka-setup/build.gradle
- docker/mysql-setup/build.gradle
- docker/postgres-setup/build.gradle
- gradle/versioning/versioning-global.gradle
- gradle/versioning/versioning.gradle
- metadata-jobs/mae-consumer-job/build.gradle
- metadata-jobs/mce-consumer-job/build.gradle
- metadata-service/war/build.gradle
- smoke-test/conftest.py
- smoke-test/smoke.sh
- smoke-test/tests/cypress/integration_test.py
- smoke-test/tests/cypress/test_weights.json
- smoke-test/tests/utils.py
CI Speed up using the build optimizations, depot runners and caching
Make docker image Tags built via gradle to match what CI uses
stream outputs of cypress tests so that in case of any hangs/problems, it is apparent from the log where the hang occured
Retries for initial login -- with faster runners, it appears the first attempt to login fails for some time, so added retries via tenacity
docker-unified.yaml continues build images for security scans and publishing as separate steps as before but uses the cached build context to build the image. 
Bin packing of cypress tests across workers
Some runner rightsizing still pending
> CI speedup

- metadata-service/configuration/src/main/resources/application.yaml
> config(): cache telemetry id

- datahub-web-react/src/alchemy-components/components/AutoComplete/AutoComplete.stories.tsx
- datahub-web-react/src/alchemy-components/components/AutoComplete/AutoComplete.tsx
- datahub-web-react/src/alchemy-components/components/AutoComplete/components.tsx
- datahub-web-react/src/alchemy-components/components/AutoComplete/constants.ts
- datahub-web-react/src/alchemy-components/components/AutoComplete/index.ts
- datahub-web-react/src/alchemy-components/components/AutoComplete/types.ts
- datahub-web-react/src/alchemy-components/components/Utils/ClickOutside/ClickOutside.stories.tsx
- datahub-web-react/src/alchemy-components/components/Utils/ClickOutside/ClickOutside.tsx
- datahub-web-react/src/alchemy-components/components/Utils/ClickOutside/types.ts
- datahub-web-react/src/alchemy-components/components/Utils/OverlayClassContext/OverlayClassContext.tsx
- datahub-web-react/src/alchemy-components/components/Utils/OverlayClassContext/constants.ts
- datahub-web-react/src/alchemy-components/components/Utils/index.ts
- datahub-web-react/src/alchemy-components/index.ts
Added the autocomplete component in the components library
Additionally added required utils to handle nested popups inside autocomplete:
- `ClickOutside` - wrapper to trigger callback when we click outside of our component
- `OverlayClassStackContext` - context to pass classes to children's popups that will be used in `ClickOutside` to ignore clicks with this classes
> feat(searchBarAutocomplete): add autocomplete component to components library

- .github/workflows/docker-unified.yml
- smoke-test/smoke.sh
PRs from forks do not have the project ID and token visible and by skipping the `depot configure docker` step, the regular local docker builds continue to work for PRs from forks.
> fix(ci): make depot remote container builder optional

- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/QueriesListSection.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/QueryFilters/QueryFilters.tsx
- datahub-web-react/src/app/searchV2/filters/SearchFilter.tsx
- datahub-web-react/src/app/searchV2/filters/useSearchFilterDropdown.tsx
Fix two related bugs in the queries tab on deploy-test:
1. Resolve issue where filter dropdown shows empty options when has selected options.
2. Prevent pagination overflow in the queries table by expanding the container instead of allowing scrolling.
> fix UI bugs on queries tab

- datahub-web-react/src/alchemy-components/components/Select/AutoCompleteSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/BasicSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/Nested/NestedSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/SimpleSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/components.ts
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/MultiSelectCustom.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/MultiSelectDefault.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/MultiSelectLabeled.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/SingleSelectCustom.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/SingleSelectDefault.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectLabelRenderer/variants/SingleSelectLabeled.tsx
- Updating icons
- gaps
- pills
**Before:**
**After** 
**Before:**
**After:**
> Updating icons, gaps, and pills in selects

- datahub-web-react/src/alchemy-components/components/Button/types.ts
- datahub-web-react/src/alchemy-components/components/Button/utils.ts
- datahub-web-react/src/app/glossaryV2/GlossaryContentProvider.tsx
- Added gradient for cool design tech feel 
- Added Secondary Button 
- Updated Button text weight 
(also updated create glossary button changed it to md because it was way too big) 
Button: 
Before:
After:
> Updated Button Component

- datahub-web-react/src/app/searchV2/SearchBar.tsx
> refactor(ui): Fix appearance of skeleton loading indicator for search bar 

- datahub-web-react/src/app/entity/user/UserAssets.tsx
- datahub-web-react/src/app/entityV2/group/GroupMembersSidebarSectionContent.tsx
- datahub-web-react/src/app/entityV2/shared/SidebarStyledComponents.tsx
- datahub-web-react/src/app/entityV2/shared/sidebarSection/UserOwnershipSideBarSection.tsx
- datahub-web-react/src/app/entityV2/user/UserAssets.tsx
- datahub-web-react/src/app/entityV2/user/UserProfile.tsx
- datahub-web-react/src/app/entityV2/user/UserProfileInfoCard.tsx
- datahub-web-react/src/app/entityV2/user/UserSidebar.tsx
- datahub-web-react/src/app/entityV2/user/useGetUserGroupUrns.ts
- datahub-web-react/src/app/homeV2/reference/sections/assets/AssetsYouOwn.tsx
- datahub-web-react/src/app/homeV2/reference/sections/assets/useGetAssetsYouOwn.tsx
- datahub-web-react/src/graphql/user.graphql
Everywhere we show you "assets you own" we should also be showing you the assets that the groups you are a member of own as well - this is how our permissioning system works anyways.
This PR takes care of that in both the V1 and V2 UI. I do this by creating a reusable hook that gets the groups you are a member of and passes those group urns into the queries to get assets that the user owns.
In the V1 UI this is only on the user profile page under the tab for these assets.
In the V2 UI it is on the user profile page tab just like v1 UI, as well as the user profile page sidebar. It also shows up on the home page on the left sidebar section under your profile image.
> fix(ui) Render assets owned by groups you are member of as your own assets

- metadata-io/src/main/java/com/linkedin/metadata/forms/validation/FormPromptValidator.java
- metadata-io/src/test/java/com/linkedin/metadata/forms/validators/FormPromptValidatorTest.java
- metadata-models/src/main/pegasus/com/linkedin/form/FormPrompt.pdl
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/plugins/SpringStandardPluginConfiguration.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/RestoreFormInfoIndicesStep.java
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/RestoreFormInfoIndicesStepTest.java
We want prompt IDs to be globally unique within a form or across forms. This PR adds the validator that will ensure this is the case. In order for this to work, prompt IDs need to be searchable on forms, though. So I add a searchable annotation and update the version to an existing backfill job to restore the indices of formInfo aspects. There should be very few of these on any given instance.
> feat(froms) Add validator preventing duplicate form prompt IDs globally

- datahub-web-react/src/app/entityV2/shared/tabs/Lineage/LineageTab.tsx
- Updated color
**Before**
**After**
**Before**
**After**
> Updated impact / explore switch to colors.violet[600]

- metadata-ingestion/src/datahub/ingestion/api/auto_work_units/auto_ensure_aspect_size.py
Our hard-limit for a payload is `16 000 000`. Currently we have a value used by the processor taken from global:
```python
INGEST_MAX_PAYLOAD_BYTES = 15 * 1024 * 1024
```
which equals to `15 728 640`, which gives us a little bit more than `281 000` characters as a buffer.
When we try to estimate size of a schema, field by field, we calculate their size separately, while in fact when they are serialized as part of an aspect, there are various things happening to them, such as additional escaping and additional nesting in the structure. Due to this the final size of the payload might have been `15 728 639 + X` where X was bigger than `281 000`. This would cause GMS to throw 400 response due to the payload exceeding allowed size (`16 000 000`). To avoid this situation I have limited …
> fix(ingestion): Make workunit processor ensuring schema size more aggresive

- datahub-web-react/src/app/searchV2/filters/__tests__/utils.test.tsx
- datahub-web-react/src/app/searchV2/filters/utils.tsx
- datahub-web-react/src/app/searchV2/filters/value/EnumValueMenu.tsx
Fixes the query tab filters in the UI that were showing urns for values instead of their display names. There was a bug with the way we were getting `displayName` before from a filter, so i broke it out into its own function and added tests.
**Before:**
**After:**
> fix(ui) Fix query tab filter dropdowns showing raw urns (#5230)

- docs/api/openapi/openapi-usage-guide.md
- docs/how/updating-datahub.md
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/GenericJsonPatch.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/ArrayMergingTemplate.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/PatchItemImpl.java
- metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/ebean/batch/PatchItemImplTest.java
- metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/v3/models/GenericEntityV3.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/GlobalControllerExceptionHandler.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/controller/EntityControllerTest.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/GenericRecordUtils.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/GenericRecordUtilsTest.java
- smoke-test/tests/openapi/v3/advanced_patching.json
- smoke-test/tests/openapi/v3/aspects.json
- smoke-test/tests/openapi/v3/entities.json
Docs for Generic Patching
https://github.com/datahub-project/datahub/blob/a31d5a028bbc5bd87b2b9fd5466e934bfa9cb32e/docs/api/openapi/openapi-usage-guide.md#generic-patching
Adds support for patching to the OpenAPI endpoints in a non-experimental way. Provides backwards compatible patching as well as a new generic patching interface.
> feat(openapi): add entity patch support

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericRelationshipController.java
This PR is intended to solve the following error:
***************************
APPLICATION FAILED TO START
***************************
Description:
Field graphService in io.datahubproject.openapi.controller.GenericRelationshipController required a bean of type 'com.linkedin.metadata.graph.elastic.ElasticSearchGraphService' that could not be found.
The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)
> fix(gms): bean not found

- smoke-test/tests/cypress/cypress/e2e/search/searchFilters.js
Something changed in our cypress data where the tags filter is no longer showing up in the More filter dropdown but as a top level filter now. I updated the test to check for the filter in both places so it's resilient either way.
> fix(cypress) Fix broken searchFilters.js cypress test

- datahub-web-react/src/alchemy-components/components/Select/components.ts
- Update minor icon issue 
Before:
After:
> Clear icons were purple after adding button gradient

- datahub-web-react/src/app/permissions/policy/ManagePolicies.tsx
- smoke-test/tests/cypress/cypress/e2e/settings/manage_policies.js
Fixes some flakiness in the manage_policies cypress test by making sure we adjust the filter to see all policies and adding a 1 second wait before we search filter to make sure the apollo cache gets updated before we do so. Otherwise we sometimes miss a policy we want to see in the list because we either filter it out or move too quickly before we update.
> fix(cypress) Fix flaky manage_policies cypress test

- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/AboutSection/DescriptionSection.tsx
We're properly sanitizing input in the documentation tab in V1 UI and both the tab and the sidebar in the V2 UI, but the description sidebar section was not properly sanitizing user input before rendering making it susceptible to XSS attacks.
This was only possible if the user issues an API call directly as we are sanitizing user input on the way in when saving descriptions from the UI.
> fix(ui) Sanitize V1 UI sidebar description section

- datahub-web-react/src/alchemy-components/components/Pills/utils.ts
- datahub-web-react/src/alchemy-components/components/Tooltip2/Tooltip2.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/DeprecationIcon.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/MarkAsDeprecatedButton.tsx
- datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/SidebarLogicSection.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx
- datahub-web-react/src/app/previewV2/DefaultPreviewCard.tsx
- datahub-web-react/src/app/recommendations/renderer/component/HoverEntityTooltip.tsx
in this pr we add hotfixes for deprecated popover to use our component lib, and sidebar logic section to make it less compact so users can see more of their query.
updated uis:
https://www.loom.com/share/d708dd69a191475baba276417d73ff56?sid=5707334f-7930-4c42-b4ea-cc78fdd81d31
> refactor(ui): UI hotfixes for the deprecated popover + sidebar logic section

- .github/workflows/docker-unified.yml
- build.gradle
- docker/build.gradle
- gradle/docker/docker.gradle
- settings.gradle
Building via bake makes better use of remote container builder resources with ~20 seconds to build all images
CI updates to use bake based builds and batch download of images from depot ephemeral registry
Disable pre-commit hooks in CI
Enabled PRs from forks that are not configured with depot to continue to use gha runners - which take about 20 min longer
> build: use docker bake to build all images in a single step

- metadata-ingestion/setup.py
* avoids the breaking change with the [MLflow 2.21.0 release](https://www.mlflow.org/releases/2.21.0) when calling `search_registered_models` in our connector 
* related bug report : https://github.com/mlflow/mlflow/pull/14795
* confirmed that the ingestion using `2.20.4` client is compatible with `2.21.3` (latest) server
> fix(ingest/mlflow): pin mlflow-skinny version

- metadata-service/events-service/build.gradle
- metadata-service/events-service/src/main/java/io/datahubproject/event/ExternalEventsService.java
- metadata-service/events-service/src/main/java/io/datahubproject/event/kafka/KafkaConsumerPool.java
- metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEvent.java
- metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEvents.java
- metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEventsResponse.java
- metadata-service/events-service/src/test/java/io/datahubproject/event/ExternalEventsServiceTest.java
- metadata-service/events-service/src/test/java/io/datahubproject/event/kafka/KafkaConsumerPoolTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/event/ExternalEventsController.java
In this PR we add back validated fixes for the events API. This includes correctly parsing the offset from topic name and other small fixes.
> fix(events API): Add back the original fixes for events API

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/ChangeEventGeneratorUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/EditableSchemaMetadataChangeEventGenerator.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/event/EntityChangeEventGeneratorHookTest.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/SchemaFieldUtils.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/SchemaFieldUtilsTest.java
Use one method for downgrading field paths and encoding schema field urns to be consistent and make sure we are encoding properly.
> fix(gms) Generate schema field urns consistently (#5583)

- datahub-web-react/src/app/entityV2/group/GroupMembersSidebarSectionContent.tsx
This PR fixes a type error when CorpGroup entities appear in the search result with the theme V2.
> fix(ui): fix a type error when a CorpGroup entity appears in the search result with theme V2

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
We were previously using the dataset (aka schema) info as the project name (aka database).
> fix(ingest/fivetran): use project id by default for bigquery

- datahub-web-react/src/alchemy-components/components/Select/AutoCompleteSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/BasicSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/SimpleSelect.tsx
- datahub-web-react/src/alchemy-components/components/Select/private/SelectActionButtons.tsx
- datahub-web-react/src/alchemy-components/components/Select/types.ts
- Fixed opening of select's dropdown on clicking on the clear button
- Extracted common `SelectActionButtons` component for selects
> fix(select): fix select opening on clear

- metadata-ingestion-modules/dagster-plugin/tests/unit/golden/golden_test_emit_metadata_mcps.json
- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/specific/dataset.py
- metadata-ingestion/tests/integration/dynamodb/dynamodb_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
- metadata-ingestion/tests/unit/cli/dataset/test_dataset_cmd.py
- metadata-ingestion/tests/unit/cli/dataset/test_resources/dataset.yaml
- metadata-ingestion/tests/unit/cli/dataset/test_resources/golden_test_dataset_sync_mpcs.json
Since the datahub dataset sync CLI supports a subset of the full dataset model, an update using the subset supported by the CLI was causing any additional properties previously set to be wiped out. 
Using patch instead upsert for all aspects were a subset of fields (and not all fields) are handled by the cli sync option of the datahub dataset command.
> fix(cli): use patch to update dataset properties

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake_failures.py
- metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
This should help with debugging situations where behavior seems to differ between our ingestion and snowsight.
> feat(ingest/snowflake): show returned query row counts

- smoke-test/tests/openapi/v1/timeline.json
- smoke-test/tests/openapi/v2/timeline.json
We recently merged a change where we don't downgrade field paths for change events anymore so we are always consistent with how we generate schema field urns. This broke one of our pytests as the fixtures weren't updated. this updates them.
> fix(pytest) Fix broken pytest after recent schema field urn change

- smoke-test/tests/cypress/cypress/e2e/mutations/dataset_ownership.js
This one was very tough to reproduce locally because it kept crashing cypress from running out of memory every single time no matter what i did or closed on my machine.
Ultimately I decided to break this test up into smaller chunks as that is a much more sustainable and easy way of writing cypress tests. I think this may have played into the flakiness we were seeing as we were just doing too much in one test. Now this consistently passes locally for me so hoping that does the trick.
I have a few other things I'll try to get to the bottom of the errors i was seeing remotely, but will put this up first as this is an obvious improvement.
> fix(cypress) Fix flakiness in dataset_ownership cypress test

- smoke-test/tests/cypress/cypress/e2e/auto_completeV2/v2_auto_complete.js
- smoke-test/tests/cypress/cypress/e2e/domains/nested_domains.js
- smoke-test/tests/cypress/cypress/e2e/manage_tags/manage_tags.js
- smoke-test/tests/cypress/cypress/e2e/mutations/managing_secrets.js
- smoke-test/tests/cypress/cypress/support/commands.js
Makes 2 small improvements to our cypress suite:
1. Globally catch the reseizeObserverLoop error that shouldn't cause cypress to fail. We were manually setting this on a few tests we could see locally but occasionally tests would fail in CI because of this. This is a safe error to skip and is heavily documented with this recommendation from the cypress team.
2. When developing locally, if your user has toggled v2 ui on or off, the `setIsThemeV2Enabled` override in cypress doesn't do anything. This makes developing on cypress a little easier locally. My team has run into this, I've run into this, I know others who has as well. No more!
> fix(cypress) Catch resizeObserverLoop globally and fix setThemeV2

- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/search/SearchBar.tsx
- datahub-web-react/src/app/searchV2/SearchBar.tsx
- datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSelectOption.ts
- Add options to `SelectAutoCompleteOption` related to the redesigned search bar
> feat(searchBarAutocomplete): add options to mixpanel events 

- .github/workflows/docker-unified.yml
Some cypress tests seem to cause the GMS to crash and needed a larger runner.
> ci: increase runner size for smoke tests

- datahub-web-react/src/alchemy-components/theme/foundations/colors.ts
- datahub-web-react/src/app/entity/shared/components/styled/DeprecationPill.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/DeprecationIcon.tsx
- datahub-web-react/src/app/previewV2/HealthIcon.tsx
- datahub-web-react/src/app/shared/health/healthUtils.tsx
Simply using phosphor icons for asset health indicator. 
Switching from Siren icon to WarningOutlined icon.
> refactor(ui): Use phosphor icons for asset health

- datahub-web-react/src/app/entity/shared/components/styled/search/EntitySearchResults.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/EditOwnersModal.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/search/EntitySearchResults.tsx
- smoke-test/tests/cypress/cypress/e2e/domains/nested_domains.js
- smoke-test/tests/cypress/cypress/e2e/domainsV2/v2_nested_domains.js
These tests were breaking, especially the V1 test, pretty often. This was due to assumptions on the ordering of data which is inaccurate and due to not waiting for elastic to be updated before going to a profile page to check if a tag is on there. The way it was written would work a good amount of the time but definitely failed often. These changes should harden these tests.
> fix(cypress) Fix flakiness in nested_domains and v2_nested_domains cypress tests

- smoke-test/tests/cypress/cypress/e2e/browse/browseV2.js
- smoke-test/tests/cypress/cypress/e2e/businessAttribute/attribute_mutations.js
- smoke-test/tests/cypress/cypress/e2e/businessAttribute/businessAttribute.js
- smoke-test/tests/cypress/cypress/e2e/home/home.js
- smoke-test/tests/cypress/cypress/e2e/mutations/domains.js
- smoke-test/tests/cypress/cypress/e2e/mutations/mutations.js
- smoke-test/tests/cypress/cypress/e2e/search/searchFilters.js
- smoke-test/tests/cypress/cypress/e2e/settings/manage_access_tokens.js
- smoke-test/tests/cypress/cypress/e2e/settingsV2/v2_manage_access_tokens.js
We would occasionally see a cypress test fail when we try to intercept a graphql query and the socket closes before we can mock it. This is because we were using an old way to intercept and replace a graphql query - using the `req.reply` method which completely takes over the request/response cycle, requiring handling to properly complete the response. Using `req.on("response")` allows us to modify the response data without interrupting the request/response flow, preventing the premature socket closure.
Also added request aliasing for improved test clarity and debugging capabilities.
> fix(cypress) Fix occasional socket closed exception in cypress

- datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelect.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/search/SearchSelect.tsx
- datahub-web-react/src/app/shared/constants.ts
- smoke-test/tests/cypress/cypress/e2e/mutations/domains.js
I've only seen this one flake a few times and it's hard to get to the bottom of exactly what's happening, but I think it's that the domain isn't applied to the expected asset in the second test and then fails in the third test because it wants to remove a domain from an asset that the domain isn't on. So i made the search to apply this domain to the assets we're looking for more specific, which I think was the intention of the `invoke` method here but wasn't actually working.
Since we type a longer message now it made it clear when running the test that we did not debounce this search select input, so I added debouncing here for v1 and v2 UIs.
> fix(cypress) Fix flaky mutations/domains cypress test

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/src/datahub/testing/check_imports.py
- smoke-test/tests/restli/test_restli_batch_ingestion.py
If you use `import datahub.metadata._schema_classes` instead of `import datahub.metadata.schema_classes`, you'll run into errors with the codegen having duplicate types and so isinstance checks won't work properly when `acryl-datahub-cloud` (or any alternative models package) is installed.
We already have a lint rule to avoid this in the metadata-ingestion directory, but people have been tripped up by this despite that. As such, I'm renaming `_schema_classes.py` -> `_internal_schema_classes.py` to make more clearly reflect its internal-only nature.
Any existing usages of `datahub.metadata._schema_classes ` should be replaced with `datahub.metadata.schema_classes`. Making that edit should not break anything.
> chore(sdk): rename `_schema_classes` to mark it as internal-only

- smoke-test/tests/cypress/cypress/e2e/incidentsV2/v2_incidents.js
- smoke-test/tests/cypress/incidents_test.json
The cypress tests for incidents are currently using conflicting data. Separating the data by moving the v2 test to use different urns.
> fix(cypress): fix cypress test data incidents

- datahub-web-react/src/app/searchV2/autoCompleteV2/components/matches/Matches.tsx
- datahub-web-react/src/app/searchV2/autoCompleteV2/components/matches/components/Match.tsx
- datahub-web-react/src/app/searchV2/matches/constants.ts
- datahub-web-react/src/app/searchV2/matches/utils.test.ts
- datahub-web-react/src/app/searchV2/matches/utils.ts
This PR adds the description field to matched fields section in the redesigned search bar
> feat(searchBarAutocomplete): add description to matched fields to results of the search bar

- smoke-test/tests/cypress/cypress/e2e/mutations/managing_secrets.js
- smoke-test/tests/cypress/cypress/e2e/mutationsV2/v2_managing_secrets.js
This test was occasionally flaky i believe because we were clicking the wrong "save" button that would run an ingestion source instead of just saving it which would cause issues later in the test. Now I use the data test id we already had on this button.
Additionally, an improvement we should strive for in all cypress tests is to make tests so that if they do flake, the retry is a fresh start and isn't in a bad state right away. Here, when we did flake (by clicking the wrong button) we would retry by creating the same secret name again which would result in an error because the secret already exists. Now I define variable names inside of the test itself so a retry will try to create a new secret.
> fix(cypress) Improve flakiness of managing_secrets v1 and v2

- .github/workflows/docker-unified.yml
- build.gradle
- datahub-actions/build.gradle
- docker/build.gradle
- docker/datahub-gms/Dockerfile
- docker/datahub-ingestion/build.gradle
- gradle/docker/docker.gradle
- gradle/versioning/versioning-global.gradle
- metadata-service/war/build.gradle
Enable use of gradle for all image builds for publishing, eliminating the per-image build action in `docker-unified.yml` that duplicated what was in gradle but used slightly different  mechanisms to determine what is the tag. Enabled gradle build to consume tags provided by the workflow and produce tags same as earlier.
Use bake matrix builds to build slim/full versions of datahub-ingestion, datahub-actions. 
Publish images and scan relies on gradle to get the list of images, via depot. 
Image publish and scans run once a day on schedule or on manual triggers only. 
Pending work: Separate the publish and scans into a separate workflow that runs on a schedule and could also run other tests.
> build: use versioning in gradle consistent with ci

- .github/workflows/docker-unified.yml
Better choice of runner type for some small tasks
Some fixes on the publish trigger - intent was to run publish only on manual triggers or once a day via schedule. 
Security settings on the scan job to enable results to be published.
> ci: fix publish and scan tasks and schedule

- metadata-ingestion/src/datahub/utilities/logging_manager.py
This means that when the CLI reports ingestion logs to our backend to be shown in the UI, the truncation behavior will be more consistent with managed ingestion's behavior. Without this, we'd see deep stack traces get truncated and be largely unusable.
> fix(ingest): handle newlines in CLI-internal log tracker

- datahub-web-react/src/graphql/dataset.graphql
[datahub-project/datahub#10319 (files)](https://github.com/datahub-project/datahub/pull/10319/files#diff-9de2cda98116de6142352060b80dd7511474a05dbba8d46416bff68ea873f7aaR712) means we label our partitions `SAMPLE (sample rows n)`, this will pick those up
> fix(graphql/stats): Support SAMPLE dataset profiles with sample size

- metadata-io/src/test/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationCandidateSourceTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/DomainsCandidateSourceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTagsCandidateSourceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTermsCandidateSourceFactory.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/DomainsCandidateSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopPlatformsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTagsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTermsSource.java
Home page recommendations currently show some assets that were soft deleted in the top tags, platforms, terms, domains, sources. This PR fixes that by requiring an existance check that excludes soft deleted assets for all home page recco modules.
Loom overview: https://www.loom.com/share/ba21d5ac54bd43ce88543bea7a2d57cb?sid=4a519b75-ab18-4650-8438-7dab4e6c439e
> fix(ui): Hide deleted assets on home page recommendations

- metadata-service/configuration/src/main/resources/application.yaml
Prevents an unnecessary 302 redirect to `/openapi/swagger-ui/swagger-ui/index.html` and preserves the expected path at `/openapi/swagger-ui/index.html`
> config(): swagger ui path

- .github/scripts/check_policies.py
- metadata-service/war/src/main/resources/boot/policies.json
- Fix missing privileges for Admin role
- Add checks so that privileges cannot get missed in the future for Admin role
> fix(auth): admin role missing privileges

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
When defining a policy for resources managed by the Iceberg REST Catalog, some of the new privileges are applicable to platform instances (that represent warehouses). However, platform instances were not listed in the search results when defining policies and searching for specific resources if a platform instance is selected in the resource type.
> fix(policy): show platormInstances in search when applicable

- datahub-actions/pyproject.toml
- datahub-actions/setup.py
`dependencies` in `pyproject.toml` must be in `[project]` section
and `[project]` section requires `version` field which I don't know what to set there
instead, I'm moving dependencies to `setup.py`
related to PR #13364
> fix(actions): h11 dependency

- datahub-graphql-core/src/main/resources/entity.graphql
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/PolicyEngineTest.java
Some fields in [DataHubResourceFilter.pdl](https://github.com/datahub-project/datahub/blob/f09bd8ac316c91b9dbc8d00337bfb41a5a26afb3/metadata-models/src/main/pegasus/com/linkedin/policy/DataHubResourceFilter.pdl#L4) were deprecated but these fields were not marked deprecated in the graphql. 
Policies created from the UI no longer use these deprecated fields, but policies created via API could still use these fields. 
While the [type field is marked optional](https://docs.datahub.com/docs/graphql/inputObjects#resourcefilterinput), omitting it but specifying a resourceURN had a bug in that code path that resulted in policy engine evaluate to effectively grant acces to all resources  ignoring the resourceUrn
> fix(policyEngine): policy evaluation incorrect without type 

- datahub-web-react/src/app/entity/shared/tabs/Properties/Edit/EditStructuredPropertyModal.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/search/SearchSelect.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/search/SearchSelectUrnInput.tsx
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlySearchedSource.java
There was a bug with the entity select modal where if you passed in an empty list for entity types (as can happen for structured property with entity values that have no restrictions) then the modal shows no results and you can't search for anything.
To fix this I update the logic so that if there are no entity types, then we should treat that as no filter on entity types and search all types as it works elsewhere in the app.
> fix(ui) Fix bug with entity select modal with no entity types passed in

- metadata-ingestion/src/datahub/ingestion/graph/client.py
In tests, when creating a recipe with `datahub_api` specified, mocking fetch_config() was insufficient because of this extra pathway. So I'm closing that off so things are more uniform.
> fix(ingest): use server config method from graph

- build.gradle
- datahub-actions/setup.py
- datahub-frontend/play.gradle
- datahub-upgrade/build.gradle
- metadata-ingestion/setup.py
- metadata-jobs/mae-consumer/build.gradle
- metadata-jobs/mce-consumer/build.gradle
- metadata-service/war/build.gradle
Include Java and Python modules required to support Microsoft Entra Workload Identities connections.
> feat(azure): include azure-identity-extensions for Microsoft Entra Workload Identity connections

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_connection.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_queries.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py
- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sqlalchemy_uri.py
- metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/tests/performance/databricks/generator.py
- metadata-ingestion/tests/unit/bigquery/test_bigquery_source.py
Fivetran depends on snowflake/bigquery, but only needs their ConnectionConfig types and a few other bits. It should not require things like great_expectations or datahub_classify. This PR shuffles around / refactors our helpers so that Fivetran can only depend on the bits it needs.
- Moves BigQueryConnectionConfig to a dedicated file
- Moves `make_sqlalchemy_uri` to a dedicated file
Tested by running `datahub check plugins --source fivetran --verbose` in an isolated venv.
> fix(ingest): fix deps for fivetran

- docker/build.gradle
- gradle/docker/docker.gradle
When adding bake builds, there was a bug in the quickstart path (non-debug) that when explicit tags are not supplied, the debug tag got added and resulting dev APP_ENV setting passed to image builds. This caused failures to local quickstart builds. CI always passed explicit tags and as a result, debug was excluded.
> fix(build): fix regression in local quickstart builds

- .github/workflows/docker-unified.yml
We have automated scripts that add labels, so we definitely don't want to be triggering CI whenever a label is changed.
~This is likely why our CI build minutes were ~2x higher this month than they usually are.~ Actually this has been around for about a year https://github.com/datahub-project/datahub/pull/10363 - not sure why it was added though.
Example of a useless run caused by this: https://github.com/datahub-project/datahub/actions/runs/14801741932?pr=13385 - the PR was approved, got `merge-pending-ci`, and then retriggered CI.
There's a lot of wasted CI runs due to this: https://github.com/datahub-project/datahub/actions/workflows/docker-unified.yml?query=event:pull_request+actor:datahub-cyborg
Most of the other changes are from prettier. Note sure why our auto-formatter wasn't …
> ci: don't rerun docker workflows on labels

- smoke-test/tests/audit_events/audit_events_test.py
- smoke-test/tests/consistency_utils.py
* wait_for_sync support for alternative consumer groups
* add both default users
> test(audit-events): updates for audit event tests

- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_lineage_usage_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_queries_mcps_golden.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_aggregate_operations.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_create_table_query_mcps.json
- metadata-models/src/main/pegasus/com/linkedin/common/Operation.pdl
1. Adds a queries field to the operation model
2. Starts populating that field for queries v2 (e.g. snowflake, bigquery)
> feat(ingest): associate queries with operations

- .github/workflows/docker-unified.yml
- .github/workflows/yaml-format.yml
> ci: Add yaml format check

- metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
- metadata-ingestion/tests/integration/athena/athena_mce_golden.json
- metadata-ingestion/tests/integration/delta_lake/delta_lake_minio_mces_golden.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_allow_table.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_inner_table.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_relative_path.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_single_table.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_tables_with_nested_datatypes.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_1.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_2.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_3.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_4.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_5.json
- metadata-ingestion/tests/integration/hive/hive_mces_all_db_golden.json
- metadata-ingestion/tests/integration/hive/hive_mces_golden.json
- metadata-ingestion/tests/integration/iceberg/iceberg_deleted_table_mcps_golden.json
- metadata-ingestion/tests/integration/iceberg/iceberg_ingest_mcps_golden.json
- metadata-ingestion/tests/integration/iceberg/iceberg_profile_mcps_golden.json
- metadata-ingestion/tests/integration/trino/trino_hive_instance_mces_golden.json
- metadata-ingestion/tests/integration/trino/trino_hive_mces_golden.json
- metadata-ingestion/tests/integration/trino/trino_mces_golden.json
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_deleted_actor_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_delta_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_mces_golden_profiling.json
- metadata-ingestion/tests/unit/glue/glue_mces_golden_table_column_lineage.json
- metadata-ingestion/tests/unit/glue/glue_mces_golden_table_lineage.json
- metadata-ingestion/tests/unit/glue/glue_mces_platform_instance_golden.json
`native_data_type` and `nullable` information are already stored in the dedicated fields of `schemaMetadata` aspect - by skipping adding them, redundantly, to `jsonProps` field, we avoid exceeding maximum allowed payload size (16 million bytes) too early - it is still possible of course, but more fields will be included in the trimmed aspect.
> feat(ingestion): Make jsonProps of schemaMetadata less verbose

- gradle/versioning/versioning-global.gradle
There were multiple versioning.gradle build scripts, one in metadata-integration/java -- used for within the subprojects in that folder and one at the gradle/versioning used everywhere else. 
Both these have some logic to compute a version from git examining the labels and git status. 
The `javaVersion` stores the result from the implementation that used to exist in metadata-integration/java  and `version`  is the result of the implementation used everywhere else. 
Over time, CI computed versions directly via .github/scripts/docker_helpers.sh and the schemes used by CI to tag images based on this version and that computed by versioning.gradle diverged. 
Part of making build script consistent with CI versioning is to just use releaseVersion and tag if passed by CI as is, and go through all …
> fix(build): fix version in jars

- metadata-ingestion/src/datahub/ingestion/source/sql/stored_procedures/lineage.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
We'd previously see issues like this:
```
Failed to extract table/view -> table lineage from SnowflakeFailed to extract table/view -> table lineage from Snowflake: Object of type FakeDatetime is not JSON serializable
Full stack trace:
File "/home/runner/work/datahub/datahub/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py", line 344, in _fetch_upstream_lineages_for_tables
for db_row in self.connection.query(query):
File "/home/runner/work/datahub/datahub/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py", line 412, in query
resp = self._connection.cursor(DictCursor).execute(query)
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/mock.py", line 1081, in __call__
return …
```
> fix(ingest/snowflake): fix previously broken tests

- docker/datahub-ingestion/Dockerfile
- metadata-ingestion/setup.py
In the metadata-ingestion docker image, we install Clickhouse, which depends on the zstd package.
With the latest zstd package we got:
```
[stderr]
/home/datahub/.cache/uv/builds-v0/.tmpFGjFmE/lib/python3.10/site-packages/setuptools/_distutils/dist.py:289:
UserWarning: Unknown distribution option: 'test_suite'
warnings.warn(msg)
error: command 'aarch64-linux-gnu-gcc' failed: No such file or directory
hint: This usually indicates a problem with the package or the build environment.
help: `zstd` (v1.5.7.0) was included because `clickhouse-sqlalchemy` (v0.2.4) depends on `asynch` (v0.3.0)
which depends on `zstd`
```
This pr pins zstd to the latest working version.
> fix(docker): Fix for metadata ingestion docker build

- datahub-web-react/src/app/sharedV2/search/SearchMenuItems.tsx
- minor update after search results page 
- added 8px gap 
Before: 
After
> updated search menu items after search update

- metadata-ingestion/src/datahub/ingestion/graph/config.py
Without this if someone upgrades to a new CLI and then downgrades to older CLI and tries to read `~/.datahubenv` it will fail with 
```
Error loading your ~/.datahubenv
3 validation errors for DatahubConfig
gms -> client_mode
extra fields not permitted (type=value_error.extra)
gms -> datahub_component
extra fields not permitted (type=value_error.extra)
gms -> openapi_ingestion
extra fields not permitted (type=value_error.extra)
```
This can easily happen in case of multiple `venv` containing different versions of the CLI
> fix(cli): ignore extra configs

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataflow/DataFlowType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataflow/mappers/DataFlowMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/entityV2/dataFlow/DataFlowEntity.tsx
- datahub-web-react/src/app/entityV2/dataFlow/preview/Preview.tsx
- datahub-web-react/src/graphql/dataFlow.graphql
- datahub-web-react/src/graphql/fragments.graphql
- datahub-web-react/src/graphql/preview.graphql
- datahub-web-react/src/graphql/search.graphql
Subtypes is supported in the metadata model for dataflows and datajobs. However, there were a few issues,
1. Java code was missing to bring that forward for DataFlows
2. Javascript code was missing to bring that forward for DataFlows and DataJobs.
> feat(UI): funnel subtype for dataflows and datajobs all the way to the UI

- datahub-frontend/app/controllers/AuthenticationController.java
- datahub-frontend/test/controllers/AuthenticationControllerTest.java
- datahub-web-react/src/app/auth/LogIn.tsx
This is especially useful for the chrome extension
> fix(authentication) redirection for native login and sso to function within iframes

- metadata-io/src/main/java/com/linkedin/metadata/entity/versioning/EntityVersioningServiceImpl.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/plugins/SpringStandardPluginConfiguration.java
Missed bringing these changes back.
1. Allows unlink on string versioning scheme
2. Makes entity versioning flag only alter what's shown / hidden in search, not what side effects get run
> fix(versioning): Properly set versioning scheme on unlink; always run side effects

- metadata-ingestion/src/datahub/sdk/main_client.py
- metadata-ingestion/tests/unit/sdk_v2/test_assertions_client.py
Match the pluralization of other uses.
> fix(sdk): use pluralized assertions

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_3_11.md
> docs(): v0.3.11 DataHub Cloud Docs

- smoke-test/tests/cli/dataset_cmd/test_dataset_command.py
- smoke-test/tests/cli/delete_cmd/test_timeseries_delete.py
- smoke-test/tests/cli/ingest_cmd/test_timeseries_rollback.py
- smoke-test/tests/cli/user_groups_cmd/test_group_cmd.py
- smoke-test/tests/cli/user_groups_cmd/test_user_cmd.py
`click` 8.2.0 was just released (May 10th, 2025) https://github.com/pallets/click/blob/main/CHANGES.rst#version-820 and removes `mix_stderr` param
> Keep stdout and stderr streams independent in CliRunner. Always collect stderr output and never raise an exception. Add a new output stream to simulate what the user sees in its terminal. Removes the mix_stderr parameter in CliRunner. [:issue:`2522`](https://github.com/pallets/click/blob/main/CHANGES.rst#id29) [:pr:`2523`](https://github.com/pallets/click/blob/main/CHANGES.rst#id31)
> tests(smoke): removes non existing `mix_stderr` param in `CliRunner`

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/DescriptionUtils.java
Tested locally and the UI works
> fix(ui): enable to edit tag when properties aspect was not present

- metadata-ingestion/src/datahub/ingestion/source/sql/presto.py
- metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
1. Workaround for Presto to not fail on missing system column
Unfortunately, the Presto dialect provides catalog_name as a column; therefore, we need a workaround to avoid failure.
This is a workaround not to fail, which causes only the table comment to be returned as a property, which is still better than failing.
2. Fix Trino property extraction from Iceberg tables
> fix(ingest/presto): Presto/Trino property extraction fix

- .github/workflows/docker-unified.yml
> fix(ci): enable publish on release

- .github/workflows/metadata-io.yml
Failures in the `metadata-io` test seem to indicate that there is no longer a python requirement for this build & test. Removing python from the workflow.
```
Post job cleanup.
Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip. This likely indicates that there are no dependencies to cache. Consider removing the cache step if it is not needed.
```
> fix(ci): metadata-io test

- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
- metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessorTest.java
This code path used to consider a `null` string as an exception case, however it can also represent a no-op case as well. While this interface (returns a string) is limited, the requirement to emit a failed mcp was moved to the other side of the interface for tracing at a stage where more detailed information is available. This is now handled [here](https://github.com/datahub-project/datahub/blob/master/metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java#L897) in the `EntityServiceImpl`
> fix(mcp-processor): prevent exception in mcp processor

- metadata-integration/java/acryl-spark-lineage/README.md
> fix(docs): broken link in spark docs

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/upgrade/upgrade.py
- smoke-test/pytest.ini
- smoke-test/tests/cli/dataset_cmd/test_dataset_command.py
- smoke-test/tests/cli/delete_cmd/test_timeseries_delete.py
- smoke-test/tests/cli/ingest_cmd/test_timeseries_rollback.py
- smoke-test/tests/cli/user_groups_cmd/test_group_cmd.py
- smoke-test/tests/cli/user_groups_cmd/test_user_cmd.py
- smoke-test/tests/utils.py
See https://github.com/pallets/click/issues/2894
Also creates a `run_datahub_cmd` helper.
> fix(cli): avoid click 8.2.0 due to bugs

- metadata-ingestion/src/datahub/api/graphql/base.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/graph/filters.py
In our monitoring was seeing this error
```
Deprecated use of a filter using Criterion's `value` has been detected and corrected. Please migrate to `values` instead.
```
Changing a few places where I saw `value` in filter. I have not tested this locally. I am assuming that we have automated tests for these places. Will let CI tell me if I am wrong here.
> fix(sdk): change deprecated value use

- docker/build.gradle
For debug variants of quickstart, any container startup failure retains containers to help debug any failures.
> build(quickstart): skip composeForceDownOnFailure for debug variants

- metadata-service/plugin/build.gradle
Gradle was reporting an implicit dependency that can cause errors depending on the order of execution. This gradle error appears to be inconsistent -- but when it failed, it fails with 
```
A problem was found with the configuration of task ':metadata-service:plugin:processTestResources' (type 'ProcessResources').
- Gradle detected a problem with the following location: '/home/runner/work/datahub/datahub/metadata-service/plugin/src/test/resources'.
Reason: Task ':metadata-service:plugin:processTestResources' uses this output of task ':metadata-service:plugin:src:test:sample-test-plugins:copyJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task …
```
> build(ci): fix a gradle implicit dependency error

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/graphql/fragments.graphql
- datahub-web-react/src/graphql/glossaryNode.graphql
- datahub-web-react/src/graphql/glossaryTerm.graphql
Supported in model and in code, but weren't passing values via graphql
> fix(ui/glossary): Display custom properties on glossary nodes

- datahub-web-react/src/app/entityV2/dataset/profile/schema/components/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/AboutSection/DescriptionSection.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/SchemaTable.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/AboutFieldTab.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldDescription.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/SchemaFieldDrawer.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/useDescriptionRenderer.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx
Simplifies code by no longer managing state higher up to coordinate show more state between schema field drawer and table.
> fix(ui/table): Fix column / ml feature description show more button

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/auth/ListAccessTokensResolver.java
- datahub-graphql-core/src/main/resources/auth.graphql
This is to bring the code in line with the graphQL schema definition.
> fix(graphql): Add default parameters to access token resolver

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake_queries.py
~Stacked on top of https://github.com/datahub-project/datahub/pull/13383~
Still pending
> feat(ingest/snowflake): generate lineage through temp views

- metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
So when deployed through helm it uses the system defaultCliversion
> fix(ingest(gc): remove default cli version

- metadata-ingestion/src/datahub/ingestion/source/sql/hive.py
- metadata-ingestion/tests/integration/hive/test_storage_parser.py
Earlier s3 datasets had an extra slash:
```
urn:li:dataset:(urn:li:dataPlatform:s3,/bucket/foldera/folderb,PROD)
```
vs how it should look like:
```
urn:li:dataset:(urn:li:dataPlatform:s3,bucket/foldera/folderb,PROD)
```
> fix(ingest/hive): Fix hive storage path formats

- metadata-integration/java/spark-lineage-legacy/build.gradle
`:metadata-integration:java:spark-lineage:integrationTest` is currently failing due an attempt to use an unavailable docker image:
https://github.com/datahub-project/datahub/actions/runs/15010274145
```
Task :docker:quickstartSlimComposeUp FAILED
opensearch Pulling 
mysql Pulling 
kafka-broker Pulling 
datahub-actions-quickstart Error manifest for acryldata/datahub-ingestion:v1.1.0rc3-slim not found: manifest unknown: manifest unknown
mysql Error manifest for acryldata/datahub-ingestion:v1.1.0rc3-slim not found: manifest unknown: manifest unknown
opensearch Error manifest for acryldata/datahub-ingestion:v1.1.0rc3-slim not found: manifest unknown: manifest unknown
kafka-broker Error manifest for acryldata/datahub-ingestion:v1.1.0rc3-slim not found: manifest unknown: manifest unknown
Error …
```
> fix(smoke-test): use full quickstart image instead of slim for spark tests

- .github/workflows/docker-unified.yml
Restoring image publish on push to master branch
> ci(publish): restore image publish on push to master

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
~Stacked on top of https://github.com/datahub-project/datahub/pull/13436~
> feat(ingest/dbt): fallback to schema from graph

- datahub-web-react/src/app/SearchRoutes.tsx
Don't want to show 404 while we're deciding whether the user has permissions to access a page
> fix(ui): Hide 404 page while loading permissions

- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/profile/shared/result/AssertionResultPopoverContent.tsx
> feat(web): display external assertion result links in run event view

- docs-website/generateDocsDir.ts
fixing the rendering error for indented inline code blocks
this code block with indentation
https://github.com/datahub-project/datahub/blob/a02d31c60402a915fdd81ed26dfe05716ae03de5/docs/lineage/dagster.md?plain=1#L37
breaks in docs site 
https://docs.datahub.com/docs/lineage/dagster#setup
this looks like this now : https://docs-website-git-docs-fix-inline-render-acryldata.vercel.app/docs/lineage/dagster/#setup
existing inline code blocks (w/o indentation) works as well : https://docs-website-git-docs-fix-inline-render-acryldata.vercel.app/docs/dataproducts#creating-a-data-product-yaml--git
> docs: update markdown_process_inline_directive to work with indentations

- metadata-service/services/src/main/java/com/linkedin/metadata/service/util/SearchBasedFormAssignmentManager.java
Right now we don't want to directly assign forms to schema fields since that's not supported on the UI in any way, we can only answer forms questions for schema fields when a form is assigned to the parent level dataset and we have schema field questions.
Therefore if someone has schema field entities defined, we will try to assign forms to those schema fields if they match the form assignment filter defined. This is just unnecessary work we're doing even though it doesn't actually break anything.
> fix(forms) Remove schema field entities from form assignment entity types

- metadata-ingestion/setup.py
See https://github.com/duckdb/duckdb/issues/17600
> fix(ingest): restrict duckdb dep on old python versions

- docs/authorization/access-policies-guide.md
The camel casing breaks linkage in the docs website
> fix(docs): Correct Access Policy references to GraphQL endpoints

- .github/workflows/build-and-test.yml
1. If a commit to master missed tests due to some failure, its coverage is not uploaded. A base branch having no coverage for a commit  (when there are changes) prevents  computation of patch coverage of all PRs using that base commit. Running on schedule helps restore base branch coverage at regular intervals.
2. On releases, branch is not auto-computed, so override_branch is required to upload codecoverage, however, use of override-branch causes codecov to think this is not a public repo and requires tokens. This breaks coverage for all PRs from forks.  So, use override-branch only when the trigger is release.
> ci(coverage): run coverage without ci-optimization on release and schedule

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourcesResolver.java
- metadata-ingestion/src/datahub/cli/ingest_cli.py
The big change in `datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourcesResolver.java` is just changing the brackets so the indentation is less. This just makes it easier to read what is happening there.
The PR is just changing/adding log messages in case there are issues with privileges
> fix(log): improve log for list-source-runs without privileges

- docker/datahub-gms/env/docker-without-neo4j.env
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
Change OSS quickstart default docker-compose files for m1 machines & otherwise to use the new UI. This requires that the docker-compose file stored `~/.docker/quickstart` be removed to be in effect I think.
> fix(quickstart): Enable V2 UI by default

- datahub-web-react/src/app/ingest/ManageIngestionPage.tsx
- datahub-web-react/src/app/ingest/secret/SecretsList.tsx
- datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
- datahub-web-react/src/app/ingestV2/secret/SecretsList.tsx
- datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx
https://linear.app/acryl-data/issue/CH-365/move-saas-secrets-tab-code-to-oss
> feat(ingestion): update the layout of secrets tab

- datahub-web-react/src/alchemy-components/components/AvatarStack/AvatarStack.stories.tsx
- datahub-web-react/src/alchemy-components/components/AvatarStack/AvatarStack.tsx
- datahub-web-react/src/alchemy-components/components/AvatarStack/types.ts
- datahub-web-react/src/app/entityV2/shared/tabs/Incident/IncidentAssigneeAvatarStack.tsx
https://linear.app/acryl-data/issue/CH-357/create-components-for-owner-pills-if-they-dont-already-exist
> feat(components): show the remaining number in stacked avatar component

- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/profile/AssertionProfile.tsx
- datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/profile/AssertionTabs.tsx
When there is only one button the UI of the assertion drawer is somewhat confusing so we remove the buttons from the display
> fix(web): Only display assertion tab buttons if there is more than one button

- docs-website/generateDocsDir.ts
skipping release note details for 1.1.0 
release note preview : https://docs-website-ebo2qt0to-acryldata.vercel.app/docs/releases#v1-1-0
> docs: skip release note details for 1.1.0 on docs site to fix build

- datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
https://linear.app/acryl-data/issue/CH-394/owner-gets-added-twice-when-adding-current-user-as-the-owner
> fix(ui/ingestion): filter current user to prevent the owner from getting added twice

- datahub-web-react/src/app/ingestV2/ManageIngestionPage.tsx
- datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
https://linear.app/acryl-data/issue/CH-410/competing-modals-welcome-tutorial-modals-for-first-time-user
> fix(ui/ ingestion): fix double onboarding modals on ingestion page

- datahub-web-react/src/alchemy-components/components/Avatar/Avatar.tsx
- datahub-web-react/src/alchemy-components/components/Avatar/types.ts
- datahub-web-react/src/alchemy-components/components/AvatarStack/AvatarStackWithHover.tsx
- datahub-web-react/src/alchemy-components/components/AvatarStack/HoverSectionContent.tsx
- datahub-web-react/src/alchemy-components/components/AvatarStack/types.ts
- datahub-web-react/src/alchemy-components/components/StructuredPopover/types.ts
- datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx
https://linear.app/acryl-data/issue/CH-402/implement-hover-state-for-stacked-avatars-in-owners-column
> feat(ui/ingestion): implement hover state for stacked avatars in owners column

- datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
- datahub-web-react/src/app/ingestV2/source/IngestionSourceRefetcher.tsx
- datahub-web-react/src/app/ingestV2/source/cacheUtils.ts
- datahub-web-react/src/app/ingestV2/source/usePollSources.ts
- datahub-web-react/src/app/ingestV2/source/utils.ts
https://linear.app/acryl-data/issue/CH-409/creating-a-new-ingestion-source-should-be-added-to-the-top-of-the-list
- Adds the newly added source to cache and shows at the top of the list
- Fetches only the single source after create/update/execute instead of the entire list
- Keeps polling the individual sources after create/update/execute till execution is complete
**Video:**
Create:
https://github.com/user-attachments/assets/ff4ddd92-e509-4cd0-8cff-95c03bc37e7e
Run source:
https://github.com/user-attachments/assets/8d8dcc17-0595-4098-b07a-6645b06f8bd5
> feat(ui/ingestion): show the newly added ingestion source at the top of the list

- datahub-web-react/src/alchemy-components/components/AutoComplete/AutoComplete.tsx
Fixes an issue where if you type in the middle of a word in the new search bar experience, it pushes your cursor to the end. This was happening due to unnecessary state changing in our component causing a re-render every time you change the value unnecessarily.
Testing and looks like all functionality works as expected.
> fix(ui) Fix cursor jumping around in search bar

- datahub-web-react/src/app/searchV2/SearchResults.tsx
We've seen an issue where users will change the page size on one of the last pages and then get stuck on a page that doesn't exist - showing no results and sometimes causing bigger issues.
After analyzing similar experiences in other apps (ie. Stack Overflow) we saw that people were taking users back to page 1 whenever they changed the size of the page. To keep it simple we're doing that here too.
> fix(ui) Take users to page 1 after page size change

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_lineage_golden_1.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_lineage_golden_2.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_queries_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_project_label_mcp_golden.json
- metadata-ingestion/tests/unit/test_confluent_schema_registry.py
- metadata-ingestion/tests/unit/test_kafka_source.py
* Added `qualifiedName` to project-level containers in the `gen_project_id_containers` function, using the database name as the identifier. (`metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py`)
* Added `qualifiedName` to dataset-level containers in the `gen_dataset_containers` function, using a combination of project ID and dataset name. (`metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py`)
> fix(ingest/bigquery): Set qualified name for bigquery containers

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/debug/datahub_debug.py
Sometimes we have various common issues like network in the environment where ingestion is running. At that point without having access to a shell debugging the issue is hard. This source adds the first capability so we can do the basic network resolution and print out the debugging information without having shell access.
Kept the name as debug source so that in future if we wanted to add more like checking disk space or anything else like that we have scope for incremental additions to this.
Some folks will do a DNS probe from within their enterprise network and see things working and assume the exact same restrictions are present in their deployed infra which is mostly not the case.
Most of the code is generated by AI. Ran it locally with internet and without internet. 
With internet …
> feat(ingest): add debug source

- datahub-web-react/src/app/ingestV2/executions/utils.ts
Replaced ExclamationMark icon with WarningCircle
ExclamationMark doesn't exist in the current version of phosphor
> fix(ingestion): replace nonexistent icon

- datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py
Fixes the handling of unicode characters that get sent across in MetadataChangeLogs. With the standard MCP, the Avro to_obj method converts unicode characters to their actual unicode form, while the MCPW to_obj() is our internal implementation that does a standard decode, preserving the format.
> fix(metadata_change_sync): fix unicode handling

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
Improves the `pyo3_runtime.PanicException` handling from PR #13758 by using precise runtime type checking instead of catching all `BaseException` types.
PR #13758 fixed the original `JSONDecodeError: Expecting value: line 1 column 1 (char 0)` crash by catching `pyo3_runtime.PanicException` from SQLGlot's Rust tokenizer. However, the implementation caught all `BaseException` types, which could interfere with important system signals.
Narrows down the exception handling to:
- ✅ **Still catch** `pyo3_runtime.PanicException` from Rust tokenizer panics
- ✅ **Re-raise** other `BaseException` types like `KeyboardInterrupt`, `SystemExit` 
- ✅ **Preserve** normal signal handling (Ctrl+C, etc.)
The key complexity is that `pyo3_runtime.PanicException` requires runtime type checking because:
- …
> fix(sql-parsing): catch pyo3_runtime.PanicException instead of BaseException

- metadata-ingestion/scripts/docgen.py
- metadata-ingestion/scripts/docs_config_table.py
- metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
This allows setting
```
schema_extra={"supported_sources": ["snowflake", "bigquery"]},
```
to only show the field in the source docs where it is actually supported. This will help reduce confusion about what is supported by not showing fields not supported.
> feat(docs): add showing specific fields to docs of specific connectors

- metadata-ingestion/src/datahub/cli/delete_cli.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
Why?
While trying to soft delete a container recursively which had 650k+ entities hit upon an issue where the initial call to get list of all urns was taking too long. And then in case there was an intermittent network issue or I had to go take a break there was a chance that I will have to restart the whole thing from beginning.
What?
- Added new flag `--streaming-batch` that allows you to delete in batches of `--streaming-batch-size` number of child entities
- Fixed a `skip_cache` issue where it being passed as a string was causing it to not work and still return cached results.
Taking these 2 together can do streaming batch cleanup which works like this
```
-> % datahub delete --urn "urn:li:container:e5688443d570ff612c481a4527831235" --recursive --streaming-batch --workers 16 …
```
> feat(cli): --streaming-batch option delete large hierarchy

- metadata-ingestion/scripts/docs_config_table.py
Rather than having this
we will just have this
which should make searching and scrolling a bit easier on the config table.
> feat(doc): hide repeating allow/deny things in config tables

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/common.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_lineage_usage_golden.json
- metadata-ingestion/tests/unit/bigquery/test_bigquery_usage.py
All user urns should be based off emails not just names. Changing this to be consistent with everything else.
> fix(ingest/bigquery): use email as user urn

- docs/automations/ai-docs.md
Render: https://docs-website-git-ai-docs-updates-acryldata.vercel.app/docs/automations/ai-docs
- Mentions that this is in public beta now
- Also improves the copy a bit.
Question: let me know if you think we should remove the youtube video now that we have the gif.
> docs: add screenshots for AI documentation

- docs-website/sidebars.js
- docs/managed-datahub/slack/saas-slack-app.md
- docs/managed-datahub/slack/saas-slack-setup.md
Also improves the structure of the Slack notification docs, particularly to add links between the various pages.
> docs: add docs on DataHub slack bot

- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/UrnExtractionUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/utils/UrnExtractionUtilsTest.java
When elastic index for some reason has missing urn then improving application logging to be able to debug it easier.
Have confirmed the new unit tests work locally + lint is fine.  
Most of the change has been done using Claude. So if something is wrong with the test do let me know.
> log(nullpointer): when elastic doc has missing urn

- datahub-web-react/src/app/ingestV2/source/IngestedAssets.tsx
- datahub-web-react/src/app/ingestV2/source/__tests__/tests_utils.test.tsx
- datahub-web-react/src/app/ingestV2/source/utils.ts
Fix explain here [loom.com/share/5b6dc75310c841c89f6e7e7502971aa2](https://www.loom.com/share/5b6dc75310c841c89f6e7e7502971aa2)
Problems
In some cases our ingestion can emit more aspects than status aspect. But status aspect remains the most reliable way to tell what has been ingested
The total assets was using sink's total records which is not the same as total assets. So using some of numbers from each entity count's status to get total assets ingested.
> fix(ui/ingest): ingestion run report

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/sac/sac.py
- metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
- metadata-ingestion/src/datahub/ingestion/source/sql/cockroachdb.py
- metadata-ingestion/src/datahub/ingestion/source/sql/hana.py
- metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mariadb.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
- metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/usage/clickhouse_usage.py
- Moved some of these capabilities to source common so they start appearing on all sources that inherit from sql-common
- Change the wording of stale deletion detection as it used to be disabled by default but we have changed it to be enabled by default a while ago
> docs(ingest): docs for lineage

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
Similar to https://github.com/datahub-project/datahub/pull/13852 but only deprecating for now so folks have time to change this. Not adding warning in pydantic validators as those get lost and are not surfaced properly to folks in source report.
> deprecate(ingest): match_fully_qualified_names for redshift,bigquery

- entity-registry/src/main/java/com/linkedin/metadata/models/registry/LineageRegistry.java
- entity-registry/src/test/java/com/linkedin/metadata/models/registry/LineageRegistryTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/registry/LineageRegistryController.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v1/registry/LineageRegistryControllerTest.java
Create some quick APIs around the LineageRegistry
> feat(): lineage registry via openapi

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.yml
- docker/profiles/docker-compose.prerequisites.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
A recent PR that bumped kafka to 8.0.0 also bumped zookeeper to 8.0.0, but that version was never published. Changed this to 7.9.2 (was 7.9.1 before the kafka bump)
> fix(quickstart): use latest zookeeper version

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
After merging https://github.com/datahub-project/datahub/pull/13871, quickstart still failed.  zookeeper support in kafka was removed in 8.0.0. So, quickstart requires kafka and schema registry also to be 7.9.2 along with zookeeper. 
There is a separate PR that removes zookeeper and will move kafka to 8.0.0
> fix(quickstart): use kafka version that supports zookeeper

- docs/cli.md
- docs/how/restore-indices.md
Follow up of https://github.com/datahub-project/datahub/pull/13820 
Move doc for sub-command to the CLI page for easier discoverability.
> doc(cli): update for restore-indices

- docs-website/sidebars.js
Before
After
Without this I find myself missing this section completely.
> doc(cloud): make datahub cloud docs prominent in side bar

- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
In pydantic 2.x we need to provide `default` argument to `Field` if the field is intended to be `Optional`.
> fix(cli): explicit default field value for optional field (pydantic v2)

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
* prevent js error
```
swagger-ui-bundle.js:2 Error: Could not parse parameter value string as JSON Object or JSON Array
at parseJsonObjectOrArray (swagger-ui-bundle.js:2:1065126)
at swagger-ui-bundle.js:2:1069814
at Array.forEach (<anonymous>)
at Object.execute_buildRequest [as buildRequest] (swagger-ui-bundle.js:2:1069110)
at swagger-ui-bundle.js:2:686865
at swagger-ui-bundle.js:2:543214
at swagger-ui-bundle.js:2:539296
at swagger-ui-bundle.js:2:691141
at Object.newAction (swagger-ui-bundle.js:2:551626)
at Object.executeRequest (swagger-ui-bundle.js:2:555363)
```
> fix(openapi): fix example

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Adding a print in telemetry confirmed the properties being passed after pipeline success is this
```
{'source_type': 'datahub-mock-data', 'source_aspects': {'dataset': {'status': 2, 'subTypes': 2, 'upstreamLineage': 2}}, 'sink_type': 'datahub-rest', 'transformer_types': [], 'records_written': 8, 'source_failures': 0, 'source_warnings': 0, 'sink_failures': 0, 'sink_warnings': 0, 'global_warnings': 0, 'failures': 0, 'warnings': 0, 'has_pipeline_name': False}
```
or
```
{'source_type': 'datahub-mock-data', 'source_aspects': {'dataset': {'status': 2, 'subTypes': 2, 'upstreamLineage': 1}}, 'sink_type': 'datahub-rest', 'transformer_types': [], 'records_written': 4, 'source_failures': 0, 'source_warnings': 0, 'sink_failures': 0, 'sink_warnings': 0, 'global_warnings': 0, 'failures': 0, …
```
> feat(ingest): add source aspect number in telemetry

- metadata-ingestion/examples/ai/dh_ai_client.py
- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/mock_data/datahub_mock_data.py
- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
Remove magic strings and use the established subtype classes so we know what subtypes we have available.
> refactor(ingest): centralise subtype strings

- datahub-web-react/src/app/tags/ManageTags.tsx
Fixing the page size selector in Tags page by adding a state, and redirecting to page 1 when we are changing the page size. This redirecting behaviour is to keep it consistent with search page behaviour
> fix(ui): Fix non-functional page size in tags page

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/Constants.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UrnToEntityMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleParamsMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleTypeMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleVisibilityMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateSurfaceMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateVisibilityMapper.java
- datahub-graphql-core/src/main/resources/app.graphql
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/main/resources/module.graphql
- datahub-graphql-core/src/main/resources/template.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/module/PageModuleMapperTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/module/PageModuleTypeTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/template/PageTemplateMapperTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/template/PageTemplateTypeTest.java
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-models/src/main/pegasus/com/linkedin/template/DataHubPageTemplateProperties.pdl
This PR has a very large diff but it is almost entirely boilerplate code and tests. This builds off of #13911 and does the following:
1. Adds the corresponding GraphQL object definitions for the new PDL object definitions
2. Adds the new "Type" Java classes for Modules and Templates in order to hydrate these entity types in the graphql layer
3. Adds mappers to get data from the PDL definition to the GraphQL definition for both Templates and Modules
4. Adds tests for all of these things
> feat(graphql) Add GraphQL Objects, Type classes, and Mappers for Templates and Modules

- metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatefulTokenService.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatelessTokenService.java
- metadata-service/auth-impl/src/test/java/com/datahub/authentication/token/StatelessTokenServiceTest.java
- smoke-test/tests/tokens/session_access_token_test.py
This PR enhances token security by adding actor validation during token verification when the endpoints don't already call this method for authorization checks. This does incur redundant validation however it should be mitigated by aspect caching.
The changes include:
* Added actor validation: StatelessTokenService now validates that actors are active when validating access tokens
* Added OperationContext dependency: Required for accessing AspectRetriever to check actor status
* Updated constructor signatures: All constructors now require an OperationContext parameter
* Comprehensive test coverage: Added 6 new tests covering all actor validation scenarios:
* System actors (always active)
* Hard deleted users (missing CorpUserKey)
* Removed users
* Suspended users
* Active users
* Users …
> fix(token-service): extend validation for actor

- metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/page-modules.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/page-templates.yaml
- metadata-service/war/src/main/resources/boot/global_settings.json
This PR ingests a default home page template and adds it to the global settings aspect. It also ingests a default page module that is referenced on the default page template.
When we add more default modules we can just extend this bootstrap step and update the version.
When we add these default page modules to our default home page template we can update the bootstrap step and increase the version.
> feat(templates/modules) Ingest default page templates and modules

- metadata-ingestion/src/datahub/ingestion/source/kafka_connect/sink_connectors.py
- metadata-ingestion/tests/unit/test_kafka_connect.py
This pull request introduces a new `RegexRouterTransform` helper class to handle Kafka Connect RegexRouter transformations, and integrates it across multiple sink connector parsers (`S3SinkParser`, `SnowflakeParser`, and `BQParser`). The changes improve the handling of topic transformations by centralizing the logic and ensuring compatibility with Kafka Connect's RegexRouter. Additionally, type annotations and minor refactoring have been added for better code clarity and maintainability.
> feat(ingest/kafka-connect): Add more connectors the regexp transformation support

- metadata-ingestion/src/datahub/ingestion/graph/client.py
Previously, when given a url without `/gms` on the end, some methods would succeed and some would fail.
> fix(graph/client): use fixed GMS URL consistently

- datahub-actions/setup.py
- datahub-actions/src/datahub_actions/pipeline/pipeline.py
- datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py
- datahub-actions/src/datahub_actions/plugin/action/hello_world/hello_world.py
- datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py
- datahub-actions/src/datahub_actions/plugin/action/propagation/docs/propagation_action.py
- datahub-actions/src/datahub_actions/plugin/action/propagation/propagation_utils.py
- datahub-actions/src/datahub_actions/plugin/action/slack/slack.py
- datahub-actions/src/datahub_actions/plugin/action/snowflake/tag_propagator.py
- datahub-actions/src/datahub_actions/plugin/action/stats_util.py
- datahub-actions/src/datahub_actions/plugin/action/tag/tag_propagation_action.py
- datahub-actions/src/datahub_actions/plugin/action/teams/teams.py
- datahub-actions/src/datahub_actions/plugin/action/term/term_propagation_action.py
- datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_event_source.py
- datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_events_consumer.py
- datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py
- datahub-actions/src/datahub_actions/plugin/transform/filter/filter_transformer.py
- docs/how/updating-datahub.md
This PR upgrades the `datahub-actions` Python package to exclusively use Pydantic V2.
**Why this change**
To leverage performance improvements and enhanced type validation offered by Pydantic V2, and to align with modern Python ecosystem practices.
**Key Changes:**
- **Dependency Update:** The `pydantic` dependency in `datahub-actions/setup.py` is now set to `pydantic>=2.0.0,<3.0.0`. Pydantic V1 compatibility has been removed.
- **Code Migration:**
- Replaced `Model.parse_obj()` with `Model.model_validate()`.
- Replaced `model.dict()` with `model.model_dump()`.
- Updated `@validator` decorators to `@field_validator` with `@classmethod` and `mode="before"` where `pre=True` was used.
- Adjusted Pydantic imports for V2 compatibility.
- **Documentation:** Added a changelog entry in …
> feat(actions): require pydantic v2

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/athena_properties_extractor.py
- metadata-ingestion/tests/integration/athena/athena_mce_golden.json
- metadata-ingestion/tests/unit/test_athena_properties_extractor.py
- metadata-ingestion/tests/unit/test_athena_source.py
- Change simple column names from v2 to v1
- Athena's get metadata call doesn't return Iceberg partitions.
This pr adds a more advanced table property and partitions extraction, which extracts it from the Table Create statement using SQL parsing. This is only used for partition extraction, but in the future, it can be used for other use-cases as well (like table ingestion from audit logs)
This feature is disabled by default and it is experimental.
> feat(ingest/athena): Iceberg partition columns extraction

- .dockerignore
- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- gradle/docker/docker.gradle
This eliminates the copy step that copies selected files from source root to a build context that is in the project build dir. A few files like jars were copied from build dir in Dockerfiles, they need to use a path relative to repo root for the source path. This was a pattern carried over from the older docker plugin that was being used.
This also addresses an occasional build error reported due to implicit dependencies between some components and test outputs. This happened because the earlier copy step would copy all files from a referenced source file (does not consider .dockerignore) which can contain outputs of a test task that is not a dependency, however gradle reports this as implicit dependency. An alternate way of addressing this is to make the copy step follow .dockerignore …
> build(docker): use root as build context

- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectV2.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java
MySQL treats trailing padding as if it were the same key, this aligns the EbeanAspect behavior with this. Prevents DuplicateKeyExceptions in the Collectors toMap processing when someone typos a trailing space on an entity aspect.
> fix(mysql): modifies hashing and equals behavior for primary keys to match mysql behavior

- datahub-web-react/src/alchemy-components/components/Button/Button.tsx
- datahub-web-react/src/alchemy-components/components/Button/types.ts
- datahub-web-react/src/alchemy-components/components/Button/utils.ts
- datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
- datahub-web-react/src/app/homeV3/module/components/__tests__/LargeModule.test.tsx
- datahub-web-react/src/app/homeV3/modules/YourAssetsModule.tsx
- datahub-web-react/src/app/homeV3/modules/__tests__/useSearchYourAssets.test.ts
- datahub-web-react/src/app/homeV3/modules/useSearchYourAssets.ts
This PR finishes up the Your Assets module by building off of #13978 and adding a "View all" button which takes you to search with a filter for your own assets. Most of the diff here is tests.
> feat(ui) Finalize Your Assets module on the frontend

- .github/scripts/pre-commit-override.yaml
- .pre-commit-config.yaml
This was too slow for pre-commit hooks. This is still checked in the CI so should be ok.
> chore(capability): remove capability summary task from pre-commit

- smoke-test/tests/cypress/cypress/e2e/search/query_and_filter_search.js
- smoke-test/tests/cypress/package.json
- smoke-test/tests/cypress/yarn.lock
- **Cypress Core**: Updated from `12.5.1` → `14.5.1`
- Drive-by: fixes for flaky tests
**Test Replay & Interactive Debugging**
- **Test Replay**: Interactive debugging of CI test failures with full session recording
- Enhanced ability to debug flaky tests and CI failures without local reproduction
- Complete DOM snapshots, network requests, and console logs for failed tests
**Advanced Flaky Test Management**
- **Enhanced Detection**: Improved algorithms for identifying flaky tests
- **Analytics Dashboard**: Better insights into test reliability and failure patterns
- **Smart Retry Logic**: More intelligent retry mechanisms for intermittent failures
**AI-Powered Test Intelligence**
- **Test Intent Summaries**: Automated explanations of test purposes and coverage
- **Failure Analysis**: …
> feat(ci): upgrade to Cypress 14.5.1 (#6204)

- metadata-service/configuration/src/main/resources/application.yaml
- metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTimerCacheTest.java
* cannot maintain multiple percentiles for legacy metrics
* defaulting to previous percentiles by default
> fix(metrics): fix metrics warning

- datahub-graphql-core/src/main/resources/module.graphql
- metadata-models/src/main/pegasus/com/linkedin/module/DataHubPageModuleType.pdl
- metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/page-modules.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/page-templates.yaml
https://linear.app/acryl-data/issue/CH-559/remove-subscription-type-module-from-oss
> fix(homepage): remove default subscription module and its type references

- datahub-web-react/src/app/homeV3/module/components/ModuleContainer.tsx
- datahub-web-react/src/app/homeV3/template/Template.tsx
- datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
- datahub-web-react/src/app/homeV3/template/types.ts
- datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
- datahub-web-react/src/app/homeV3/templateRow/__tests__/utils.test.ts
- datahub-web-react/src/app/homeV3/templateRow/types.ts
- datahub-web-react/src/app/homeV3/templateRow/utils.ts
- datahub-web-react/src/app/previewV2/EntityHeader.tsx
- datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
- datahub-web-react/src/app/searchV2/autoCompleteV2/components/DisplayName.tsx
**DEPENDS ON: https://github.com/datahub-project/datahub/pull/13994**
> feat(customHomePage): adjust rows component and add wrapping

- metadata-service/configuration/src/main/resources/application.yaml
This PR updates application.yml to enable the V2 UI by default unless otherwise specified with an env variable.
> Enable UI theme V2 by default

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
All nullable schema ref properties in openAPI 3.1.0 must use a `oneOf($ref, null)` like so:
```
result.addProperty(
NAME_SYSTEM_METADATA,
newSchema()
.types(TYPE_OBJECT_NULLABLE)
.oneOf(
List.of(
newSchema().$ref(PATH_DEFINITIONS + "SystemMetadata"),
newSchema().type(TYPE_NULL)))
.description("System metadata for the aspect."));
```
> fix(openapi): openapi 3.1.0 nullable refs to use oneOf(ref, null)

- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
- metadata-ingestion/tests/unit/cli/docker/test_quickstart_version_mapping.py
This commit hash is used to download the resolved quickstart profile if using the latest CLI to install an older version - - like 1.1 that does not contain the profile based resolved quick start compose file.
> fix(quickstart): update commit hash with resolved quickstart profile

- datahub-web-react/src/app/searchV2/filters/value/EnumValueMenu.tsx
- datahub-web-react/src/app/searchV2/filters/value/__tests__/utils.test.tsx
- datahub-web-react/src/app/searchV2/filters/value/utils.tsx
- metadata-service/configuration/src/main/resources/application.yaml
This PR handles a situation that arose where people were not able to search for structured property values in the search results dropdown if they weren't in the initial 20 aggregations we get back from search results. This does that with 2 changes:
1. Update the max number of aggregations we allow to be a higher number than 20 (went with 60 for now, somewhat arbitrary but given the OK by our search expert) so that we show more values in the enum menu right away. We were already passing in a search flag to get a higher number in the aggregations query.
2. Allow "searching for values" in the filter search bar by doing an aggregations query with a filter for the property value with the input value of the search bar. That way if the user knows the value they want to filter on, they can search …
> fix(ui) Allow aggregation searches for enum filter types

- metadata-ingestion/setup.py
Bug in Delta Lake source ingestion — fails when Delta Table contains Deletion Vectors (DV).
Resolves https://github.com/datahub-project/datahub/issues/14051
1. Create a Delta Table with DV enabled (Delta 2.4.0+, Spark 3.4.4)
```
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, LongType, StringType
table_path = "tmp/dv_test_table"
spark = SparkSession.builder \
.appName("DeltaTableWithDV") \
.config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
.config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
.config("spark.databricks.delta.properties.defaults.enableDeletionVectors", "true") \
.master("local[*]") \
.getOrCreate()
schema = StructType([
StructField("id", LongType(), True), …
```
> fix(ingest/deltalake): pin upperbound for delta lake

- docker/kafka-setup/Dockerfile
The wget in the cp-base-new appears to be a little old and fails to download the snakeyaml jar due to an ssl handshake failure. The wget in the later stage does work.
> chore(deps): bump kafka in kafka-setup

- metadata-ingestion/src/datahub/ingestion/source/abs/source.py
- metadata-ingestion/src/datahub/ingestion/source/azure/azure_common.py
- metadata-ingestion/src/datahub/ingestion/source/data_lake_common/object_store.py
- metadata-ingestion/tests/unit/abs/test_abs_source.py
- metadata-ingestion/tests/unit/data_lake/test_object_store.py
- Update abs_browser to use name_starts_with instead of deprecated prefix parameter in Azure Storage SDK
- fix for broken ABS prefix matching to support https as well as already supported abfss
> fix(ingestion/abs): updated deprecated azure sdk parameter to supported parameter and uri prefix support of https 

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
- datahub-graphql-core/src/main/resources/app.graphql
- datahub-web-react/src/appConfigContext.tsx
- datahub-web-react/src/graphql/app.graphql
- metadata-models/src/main/pegasus/com/linkedin/logical/LogicalParent.pdl
- metadata-models/src/main/resources/entity-registry.yml
- metadata-service/configuration/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java
- metadata-service/configuration/src/main/resources/application.yaml
Initial work to support logical models, i.e. representing the relationship between logical dataset and their physical representations
> feat(logical): Add feature flag and models

- docker/kafka-setup/Dockerfile
The latest cp-base-new (version 8.0.0) also did not include an updated commons-beanutils. So downloading it separately
> chore(deps): bump commons-beanutils

- docker/kafka-setup/Dockerfile
The same jar is also needed in /opt/kafka/libs
> chore(deps): bump commons-beanutils - one more location

- metadata-ingestion/docs/sources/dbt/dbt.md
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/sample_dbt_manifest_1.json
- metadata-ingestion/tests/integration/dbt/test_dbt.py
add support for nested dbt meta field mapping (meta_mapping, column_meta_mapping)
dbt define [meta](https://docs.getdbt.com/reference/resource-configs/meta) field as dictionary
if meta section looks like this
```yaml
meta:
data_governance:
team_owner: "Finance"
```
this meta mapping start to work:
```yaml
meta_mapping:
data_governance.team_owner:
match: "Finance"
operation: "add_term"
config:
term: "Finance_test"
```
---
> feat(dbt/ingestion): add support for nested meta properties mapping

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/tests/integration/athena/athena_mce_golden.json
- metadata-ingestion/tests/unit/test_athena_source.py
Make Athena simple column v1 conversion optional and disabled by default, to not introduce a breaking change
> fix(ingest/athena): Make Athena simple column v1 conversion optional

- .github/workflows/build-and-test.yml
- datahub-web-react/src/alchemy-components/components/ActionsBar/ActionsBar.stories.tsx
- datahub-web-react/src/alchemy-components/components/ActionsBar/ActionsBar.tsx
- datahub-web-react/src/alchemy-components/components/ActionsBar/index.ts
- datahub-web-react/src/alchemy-components/index.ts
- datahub-web-react/src/app/homeV3/EditDefaultTemplateBar.tsx
- datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
- datahub-web-react/src/app/homeV3/HomePageContent.tsx
This PR adds the edit and "Done" buttons for allowing users to edit the global template on the homepage in the new home page experience.
Originally we thought we wanted to make this editing experience "staged" but after discussion it's much easier and probably more expected to always have edits happen in place for these sort of interactions. So now you just click the edit button to get into editing the global template and have a warning actions bar where you can stop editing global.
> feat(ui) Add ability to edit global template on homepage

- datahub-web-react/src/app/homeV3/module/Module.tsx
- datahub-web-react/src/app/homeV3/moduleModals/ModuleModalMapper.tsx
- datahub-web-react/src/app/homeV3/moduleModals/common/BaseModuleModal.tsx
- datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModal.tsx
- datahub-web-react/src/app/homeV3/modules/documentation/DocumentationModal.tsx
- datahub-web-react/src/app/homeV3/modules/documentation/DocumentationModule.tsx
- datahub-web-react/src/app/homeV3/modules/documentation/RichTextContent.tsx
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
https://linear.app/acryl-data/issue/CH-515/add-ability-to-create-documentation-module
https://linear.app/acryl-data/issue/CH-516/ability-to-view-documentation-module-on-homepage
https://linear.app/acryl-data/issue/CH-520/ability-to-edit-documentation-module
This PR adds support to create, edit and render Documentation (Rich-text) type modules.
It also disables the Create/Update button in the modal when the required values are not present.
And makes the content inside the modal scrollable, keeping the header and footer fixed.
> feat(homepage): support documentation modules in the new home page

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/module/UpsertPageModuleResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/module/UpsertPageModuleResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolverTest.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/PageModuleService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/PageModuleServiceTest.java
- metadata-service/war/src/main/resources/boot/policies.json
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
This PR adds the platform privilege for whether or not you can manage the global home page. Specifically, this controls whether you can create/editdelete global templates or global modules. This will also be used in the UI later for controlling who can see the edit button for editing a global global templates for the rest of folk.
> feat(permissions) Add platform privilege for editing global home page

- datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
- datahub-web-react/src/app/homeV3/announcements/Announcements.tsx
- datahub-web-react/src/app/homeV3/header/Header.tsx
- datahub-web-react/src/app/homeV3/styledComponents.ts
- datahub-web-react/src/app/homeV3/template/Template.tsx
- datahub-web-react/src/app/homeV3/template/components/NewRowDropZone.tsx
- datahub-web-react/src/app/homeV3/template/components/TemplateGrid.tsx
- datahub-web-react/src/app/homeV3/templateRow/components/RowLayout.tsx
- datahub-web-react/src/app/sharedV2/__tests__/useGetEntities.test.ts
- datahub-web-react/src/app/sharedV2/useGetEntities.ts
Ensures that all rows align properly left and right with the rest of the content on the page. Also implements percentage width of the page content to grow and shrink appropriately with the size of the page. Then if the page is smaller, give it a bigger percentage to fill in space for usability.
> feat(ui) Fix alignment of rows and columns on new home page

- docker/build.gradle
- metadata-integration/java/spark-lineage-legacy/spark-smoke-test/smoke-gms.env
quickstart CLI which by default uses METADATA_SERVICE_AUTH_ENABLED=false
The docker compose file did not define this env and hence defaulted to the value in application.yaml (which is true). 
When generating a resolved compose file, all env sections are stripped off and the expanded in the resulting environment variables section in the compose file. So, the profile-based quickstart implementation added this env var to the `environment` section so that it can be overriden to false during generating the resolved compose file for quickstart CLI
The consequence of adding this to environment section is that it takes precedence over env files, it can no longer be overriden by env files to disable METADATA_SERVICE_AUTH_ENABLED (but the environment variable defined with this name still works). …
> fix(tests): disable auth for spark test via env var instead of env file

- datahub-web-react/src/app/homeV3/context/hooks/useDragAndDrop.ts
- datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
- datahub-web-react/src/app/homeV3/module/components/SmallModule.tsx
- datahub-web-react/src/app/homeV3/modules/constants.ts
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
- datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
- datahub-web-react/src/app/homeV3/templateRow/components/ModuleDropZone.tsx
- datahub-web-react/src/app/homeV3/templateRow/components/RowLayout.tsx
- datahub-web-react/src/app/homeV3/templateRow/hooks/useTemplateRowLogic.ts
**Linear tickets:**
https://linear.app/acryl-data/issue/CH-584/handle-height-of-drop-zones-for-small-modules
https://linear.app/acryl-data/issue/CH-585/handle-drag-and-drop-with-small-and-large-modules
- Adds the ability to the small modules (currently Link type) to be dragged and dropped. 
- Handles the extra space after small modules (due to the large height of drop zones). 
- Restricts the drag and drop of small modules into the rows with large modules and vice-versa.
> feat(ui/homepage): handle drag and drop with small modules

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- Make the REST emitter's maximum payload size configurable via environment variable
- Add `DATAHUB_REST_EMITTER_BATCH_MAX_PAYLOAD_BYTES` environment variable to control batch size limits
- Maintains backward compatibility with default value of 15MB
- Modified `INGEST_MAX_PAYLOAD_BYTES` in rest_emitter.py to read from environment variable
- Allows users to customize payload size limits based on their infrastructure constraints
-----------------------
> feat(ingestion): make REST emitter batch max payload size configurable

- smoke-test/tests/cypress/cypress/e2e/lineageV2/v2_lineage_graph.js
- smoke-test/tests/cypress/cypress/e2e/siblings/siblings.js
- smoke-test/tests/cypress/cypress/e2e/siblingsV2/v2_siblings.js
- smoke-test/tests/cypress/cypress/e2e/viewV2/v2_view_select.js
- smoke-test/tests/cypress/cypress/e2e/views/view_select.js
- smoke-test/tests/cypress/cypress/support/commands.js
Fix for Cypress 14.5.1 upgrade compatibility issues
- Global handler in `commands.js` now handles all `ResizeObserver` errors
- Supports both Cypress 12.x and 14.x error message formats:
- 	"ResizeObserver loop limit exceeded" in older Electron/Chromium VS "ResizeObserver loop completed with undelivered notifications."
- Remove individual `cy.on('uncaught:exception')` handlers from 9 test files (158 lines of redundant code)
- ResizeObserver is a browser API that monitors changes to element dimensions. 
-  In complex web applications you can get into situations where:
```Observer watches element → Element resizes → Observer triggers callback → Callback causes layout change → Element resizes again → Infinite loop!```
- Browser detects the loop and throws an error to prevent hanging/crashing …
> ci(cypress): resize observer fix (#6263)

- docs/advanced/monitoring.md
- metadata-io/src/main/java/com/linkedin/metadata/system_telemetry/GraphQLTimingInstrumentation.java
- metadata-io/src/main/java/com/linkedin/metadata/trace/TraceServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/trace/TraceServiceImplTest.java
- metadata-jobs/common/src/main/java/com/linkedin/metadata/kafka/listener/AbstractKafkaListener.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessor.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/listener/mcl/MCLKafkaListener.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessorTest.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/listener/mcl/MCLKafkaListenerTest.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessor.java
- metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessorTest.java
- metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java
- metadata-jobs/pe-consumer/src/main/java/com/datahub/event/PlatformEventProcessor.java
- metadata-jobs/pe-consumer/src/test/java/com/datahub/event/PlatformEventProcessorTest.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/DataHubConfiguration.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/MetricsOptions.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/kafka/ConsumerConfiguration.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/system_telemetry/KafkaMetricsConfiguration.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/system_telemetry/RequestMetricsConfiguration.java
- metadata-service/factories/src/test/java/com/linkedin/gms/factory/system_telemetry/KafkaMetricsConfigurationTest.java
- metadata-service/factories/src/test/java/com/linkedin/gms/factory/system_telemetry/RequestMetricsConfigurationTest.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTest.java
This PR introduces comprehensive Micrometer-based metrics for monitoring Kafka message queue time (latency) across all Kafka consumers in the system, while maintaining backward compatibility with existing Dropwizard metrics.
Documentation: 
- [Kafka Consumer Instrumentation (Micrometer)](https://github.com/datahub-project/datahub/blob/5a7e700421b2319de9821c255bc20fe1b34b398e/docs/advanced/monitoring.md#kafka-consumer-instrumentation-micrometer)
- [DataHub Request Hook Latency Instrumentation (Micrometer)](https://github.com/datahub-project/datahub/blob/5a7e700421b2319de9821c255bc20fe1b34b398e/docs/advanced/monitoring.md#datahub-request-hook-latency-instrumentation-micrometer)
- Adds configurable percentiles, SLOs, and time windows for Kafka queue time metrics
- Implements …
> feat(kafka-consumer): micrometer kafka consumer metrics

- datahub-web-react/src/app/homeV3/context/hooks/__tests__/moduleOperationsUtils.test.ts
- datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
- datahub-web-react/src/app/homeV3/context/hooks/useDragAndDrop.ts
- datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
- datahub-web-react/src/app/homeV3/context/hooks/utils/moduleOperationsUtils.ts
- datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
https://linear.app/acryl-data/issue/CH-566/handle-situation-where-you-add-module-to-a-row-with-3-modules-in-it
**Video:**
https://github.com/user-attachments/assets/312adc52-17c1-4677-9abc-91eac69f164b
> feat(ui/homepage): handle adding module to a row with 3 modules already

- datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
- datahub-web-react/src/app/homeV3/context/__tests__/PageTemplateContext.test.tsx
- datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleModalState.test.ts
- datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
- datahub-web-react/src/app/homeV3/context/hooks/useModuleModalState.ts
- datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
- datahub-web-react/src/app/homeV3/context/types.ts
- datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
This PR updates the edit logic when a user tries to edit a global module while not explicitly editing the global template, we let them feel like they'r editing, but in reality they're creating a new module with the edits and replacing the global module under the hood. That way users don't change global modules that exist on the default home page for all users.
Majority of diff here are tests.
> feat(ui) Create and replace when editing global modules on personal template

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/factories/BootstrapManagerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/MigrateHomePageLinksStep.java
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/MigrateHomePageLinksStepTest.java
- metadata-service/factories/src/test/resources/test-entity-registry.yaml
This PR adds a new upgrade step that will look for existing home page links and then converts them to module entities. We then add these module entities to the first row(s) of the default home page template. These rows will have max 3 modules and we can create multiple rows if there's more than 3 modules.
> feat(homePage) Migrate existing home page links to modules on default template

- datahub-web-react/src/app/homeV3/moduleModals/common/BaseModuleModal.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/HierarchyViewModal.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/DepthMargin.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/TreeNodeRenderer.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts
- Disabled intermediate state of checkboxes
- Changed text and color of the load more button
- Indentation increased (8px -> 16px)
- Width of the modal reduced to 900px
> fix(customHomePage): fixes after design review of hierarchy view

- datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
- datahub-web-react/src/app/homeV3/module/components/__tests__/ModuleMenu.test.tsx
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/ModuleMenuItem.tsx
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
https://linear.app/acryl-data/issue/CH-578/design-review-updates-misc
- Edit button should be present on all widgets; default and custom and edit button on DEFAULT should be disabled with a hover state
- Update home page defaults to handle disabling the modules based on row size and type of module
> improvement(ui/homepage): miscellaneous design review updates for custom home page

- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateGraphIndicesService.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/update/indices/UpdateIndicesServiceFactory.java
This PR attempts to restrict the finegrained lineage creation on the basis of platforms, which is configurable.
Th idea is to restrict for platforms like hdfs,s3, for which explosive creation of finegrained lineage is observed results in consuming large space in graph store like Neo4j and slow write throughput which results in constant lag in MCL topic.
> feat(lineage): restrict the creation of finegrained lineage in graphstore

- metadata-ingestion/src/datahub/sdk/search_filters.py
- metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
With sdk v2, we can now support raw strings in addition to proper objects.
> fix(sdk): make Filter type parsing more permissive

- docker/build.gradle
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/docker-compose.prerequisites.yml
- docker/quickstart/docker-compose.quickstart-profile.yml
* allow overriding base compose file
* wire debug-aws with localstack
> feat(docker-gradle): localstack debug

- docs/api/tutorials/lineage.md
This table is missing datajob->dataset lineage
> docs(lineage): clarifying datajob->dataset lineage is supported

- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
Use `system.access.column_lineage` to grab column lineage for an entire schema in one go. If a warehouse isn't configured, fall back to the older and slower HTTP API, which has to make a request for each individual column at a time.
Performance testing: on a schema with 316 tables, ingestion using the HTTP API for column lineage took 20 minutes 51 seconds. Using the system tables lineage took 3 minutes 49 seconds (~5x improvement).
> feat(ingest/unity): use system tables to get column lineage

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datajob/mappers/DataJobMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/entityV2/dataJob/DataJobEntity.tsx
- datahub-web-react/src/app/lineage/utils/__tests__/extendAsyncEntities.test.ts
- datahub-web-react/src/graphql/dataJob.graphql
- datahub-web-react/src/graphql/fragments.graphql
In the case that a datajob has a data platform instance, we should use that for platform name and logo rather than the data flow's. This allows for visualizing when an orchestrator executes a task within a different tool.
> feat(datajobs): support dataplatform instance in datajobs

- datahub-web-react/src/app/lineageV2/controls/DownloadLineageScreenshotButton.tsx
- datahub-web-react/src/app/lineageV2/controls/__tests__/DownloadLineageScreenshotButton.test.tsx
- datahub-web-react/src/app/lineageV3/controls/DownloadLineageScreenshotButton.tsx
- datahub-web-react/src/app/lineageV3/controls/__tests__/DownloadLineageScreenshotButton.test.tsx
- datahub-web-react/src/app/lineageV3/utils/lineageUtils.ts
Lineage screenshot filenames now contain the dataset name:  `{dataset name}_{timestamp}` 
| Before      | After |
| ----------- | ----------- |
| <img width="314" height="100" alt="Screenshot 2025-07-18 at 3 31 43 PM" src="https://github.com/user-attachments/assets/857ddbe0-1d71-4ce5-8666-1d2c185c810a" /> |  <img width="311" height="115" alt="Screenshot 2025-07-18 at 5 45 34 PM" src="https://github.com/user-attachments/assets/2a621081-e544-41e5-9b01-9fa93b2dd51b" /> |
> feat(lineage): downloaded filename contains entity name

- metadata-ingestion/docs/sources/dbt/dbt.md
- metadata-ingestion/src/datahub/utilities/mapping.py
- metadata-ingestion/tests/unit/test_mapping.py
YAML lists are fully supported in dbt meta properties. Each item in the list is evaluated against the match pattern, and only matching items are processed.
```yaml
meta:
owners:
- alice@company.com
- bob@company.com
- contractor@external.com
```
```yaml
meta_mapping:
owners:
match: ".*@company.com"
operation: "add_owner"
config:
owner_type: user
```
> feat(meta-mapping): support meta mappings of lists

- docker/snippets/oracle_instantclient.sh
The Oracle Instant Client cannot find `libaio.so.1` due to the [transition of Debian and its derivatives to 64-bit time](https://wiki.debian.org/ReleaseGoals/64bit-time). This causes an error when using thick mode.
```sh
$ docker run --rm --entrypoint /bin/ldd docker.io/acryldata/datahub-actions:v1.2.0 /opt/oracle/instantclient_21_15/libociei.so
linux-vdso.so.1 (0x00007ff054a82000)
libclntsh.so.21.1 => /opt/oracle/instantclient_21_15/libclntsh.so.21.1 (0x00007ff047800000)
libclntshcore.so.21.1 => /opt/oracle/instantclient_21_15/libclntshcore.so.21.1 (0x00007ff047200000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff054a70000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff04bf17000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff054a6b000)
librt.so.1 …
```
> fix(oracle): create libaio.so.1 symbolic link

- metadata-ingestion/src/datahub/sdk/entity_client.py
- metadata-ingestion/tests/unit/sdk_v2/test_entity_client.py
> feat(ingest/sdkv2): Add way to pass in emit_mode to entity client update and upsert

- docs/iceberg-catalog.md
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouse.java
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/IcebergBatch.java
- metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/TableOrViewOpsDelegate.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouseTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/TableOpsDelegateTest.java
- metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/ViewOpsDelegateTest.java
Add some of the standard metadata fields are populated in the Dataset Properties. Additionally, any Iceberg `TBLPROPERTIES` set via DDL on tables or views are also shown in DatasetProperties with a prefix `iceberg:`
The iceberg 'TBLPROPERTIES' can only be set via DDL and is a one way sync. Changes to iceberg `TBLPROPERTIES` properties via datahub APIs do not get written to the Iceberg table or view properties.
> feat(irc): report tblproperties via dataset properties

- datahub-web-react/src/app/analytics/__tests__/columnFilterAnalytics.test.ts
- datahub-web-react/src/app/analytics/__tests__/useTrackPageView.test.ts
- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/analytics/useTrackPageView.ts
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- datahub-web-react/src/app/lineageV2/LineageExplorer.hooks.tsx
- datahub-web-react/src/app/lineageV2/LineageExplorer.tsx
- datahub-web-react/src/app/lineageV3/LineageDisplay.hooks.tsx
- datahub-web-react/src/app/lineageV3/LineageDisplay.tsx
Fixes for the following issues:
1. The lineage section view event doesn't include metadata like, # of upstreams, # of downstreams, whether CLL is present, or if those upstreams or downstreams are expandable. All of this is important context of the quality of the lineage graph - P0
* Added new fields to the event:
2. Opening the lineage tab triggers a new section view event and page view event. It should just trigger a section view event - P1
* Emitting only two events (`EntitySectionViewEvent` and `VisualLineageViewEvent`):
3. Impact Analysis- since column level lineage analysis is important- we should track in the SearchAcrossLineageResultsViewEvent if a column filter is applied, just like we do with maxDegree 
4. Impact Analysis - when opening the impact analysis tab, I see 3-4 …
> fix(lineage): Improve lineage logging (#6242)

- .aikido
Exclude docs-website from security scans with Aikido.
> fix(security): exclude docs-website from scans

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/tests/unit/dbt/test_dbt_source.py
Currently, dbt Cloud sources incorrectly prioritize schema-level `sourceDescription` over table-level `description` for source resources. This fix ensures table-level descriptions take precedence, with fallback to schema-level when table description is empty.
Added unit tests to validate the correct behavior and prevent regression.
> fix(dbt-cloud): use correct node description for sources

- datahub-frontend/app/auth/sso/SsoManager.java
- datahub-frontend/test/security/SsoManagerTest.java
Prevents clearing the SSOProvider on refresh if there is an existing provider with OIDC configuration enabled. This avoids removing the SSOProvider in cases where there is no database configuration for the OIDC settings which are typically configured through the UI.
> fix(sso): fix null overrides in case of non-ui sso configuration

- metadata-service/services/src/main/java/com/linkedin/metadata/service/PageTemplateService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/PageTemplateServiceTest.java
This PR prevents default template deleting through API
> fix(customHomePage): prevent default template deleting through API

- docker/build.gradle
- docker/profiles/README.md
- Modified `docker/build.gradle` to allow the `quickstartCypress` task to use a custom project name (`dh-cypress`) instead of the default `datahub` project name
- Updated `docker/profiles/README.md` to document the new `quickstartCypress` task and its purpose for Cypress testing scenarios
- Added documentation for the `:smoke-test:cypressData` gradle task for loading test data
This enables isolated Cypress testing environments by using a different docker compose project name, preventing conflicts with other running DataHub instances during testing.
> dev(cypress): gradle command `quickstartCypress`

- datahub-web-react/src/app/entityV2/glossaryTerm/profile/RelatedTerm.tsx
- datahub-web-react/src/app/entityV2/shared/SearchCardContext.tsx
- datahub-web-react/src/app/previewV2/DefaultPreviewCard.tsx
Before:
After:
Reused the existing SearchCard context instead of handling it separately
> fix(ui): Remove text overlaps with custom links

- datahub-actions/src/datahub_actions/cli/actions.py
- datahub-actions/tests/unit/cli/test_actions.py
We had an issue where actions enabled or disabled via env vars were throwing exceptions instead of being skipped appropriately if they were disabled via an env var. This PR updates our check after we expand variables to double check the `enabled` field once we know their final values with env vars. Also update to add tests for this scenario.
This issue explains the situation very well: https://github.com/datahub-project/datahub/issues/14224
Fixes #14224
> fix(actions) Fix checking actions enabled via env vars

- datahub-web-react/package.json
- datahub-web-react/src/app/ingestV2/executions/components/BaseTab.tsx
- also change yarnLintFix to only print file names that `prettier` changed not all files which makes the log very large
> fix(ui/ingest): always show scroll bar on summary tab

- datahub-web-react/src/app/previewV2/HealthIcon.tsx
https://linear.app/acryl-data/issue/CH-651/bug-entity-hover-card-covers-the-cards-deprecation-tooltip
> fix(ui): fix entity hover cards covering health popover

- datahub-web-react/src/app/entity/glossaryNode/GlossaryNodeEntity.tsx
- datahub-web-react/src/app/entityV2/dataProduct/DataProductEntity.tsx
- datahub-web-react/src/app/entityV2/domain/DomainEntity.tsx
- datahub-web-react/src/app/entityV2/glossaryTerm/GlossaryTermEntity.tsx
- datahub-web-react/src/app/entityV2/summary/SummaryTab.tsx
- datahub-web-react/src/app/entityV2/summary/__tests__/useShowAssetSummaryPage.test.ts
- datahub-web-react/src/app/entityV2/summary/documentation/AboutSection.tsx
- datahub-web-react/src/app/entityV2/summary/properties/PropertiesHeader.tsx
- datahub-web-react/src/app/entityV2/summary/useShowAssetSummaryPage.ts
https://linear.app/acryl-data/issue/CH-667/skeleton-for-the-new-summary-tab-on-required-entities
> feat(ui/summary): add new summary tab on the required entities

- datahub-web-react/src/app/entity/shared/__tests__/siblingsUtils.test.ts
- datahub-web-react/src/app/entity/shared/siblingUtils.ts
Currently if someone wants to clear a description on a schema field (or dataset or what have you) but the sibling has a description, we just always show the sibling's description. This is a frustrating experience for our users.
So now I modify the function that removes fields with empty strings to be overwritten when merging siblings. This should solve the immediate issue but may cause other issues. Will review meticulous to see what else gets impacted.
> fix(ui) Allow empty strings for sibling values

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
fix(ingestion): updated schema name handling to support Snowflake quoted identifiers and added tests for schema transpilation
- **Issue:** #14210 
- **Issue Summary:** Fivetran ingestion pipeline implements queries for Snowflake, and banks on sqlglot to transpile to BigQuery at runtime. Certain scheme names required quoted identifiers [(Snowflake Doc).](https://docs.snowflake.com/en/sql-reference/identifiers-syntax) 
- **Tests:** Added unit tests to check if there are any exceptions in transpilation for a supported list of strings
> fix(ingestion): updated schema name handling to support Snowflake quoted identifiers #14210

- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/childrenLoader/context/ChildrenLoaderContext.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/childrenLoader/context/ChildrenLoaderProvider.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/DomainsSelectableTreeView.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/hooks/__tests__/useSelectableDomainTree.test.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/hooks/useDomains.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/hooks/useLoadMoreRootDomains.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/hooks/useRootDomains.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/hooks/useSelectableDomainTree.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/TreeNodeRenderer.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/TreeNodesRenderer.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/__tests__/utils.test.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/Row.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/TreeNodesViewLoader.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/itemsLoaderWrapper/NodesLoaderByButtonWrapper.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/itemsLoaderWrapper/NodesLoaderInfiniteScrollWrapper.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/itemsLoaderWrapper/NodesLoaderWrapper.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/components/itemsLoaderWrapper/types.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/constants.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContext.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts
- datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/utils.ts
This PR brings changes from Saas repo
> feat(customHomePage/hierarchy): add support of pagination for root level nodes

- .github/pull_request_template.md
- docs/CONTRIBUTING.md
> docs(contributing): added PR title format

- metadata-ingestion/src/datahub/ingestion/autogenerated/lineage.json
- metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl
- metadata-service/services/src/main/java/com/linkedin/metadata/service/LineageService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/graph/LineageGraphFiltersTest.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/LineageServiceTest.java
This allows Chart entities to have both Dataset and Chart upstreams. Useful for BI tools which have allow more complex relationships between charts.
Examples for Metabase and Sigma:
> feat(models): support charts in edges fields of other charts

- metadata-ingestion/setup.py
Fixes Excel connector failures in nightly builds due to missing dependencies (boto3, cachetools, pandas, pyspark).
Added required dependency sets: aws_common, abs_base, cachetools_lib, data_lake_profiling.
> fix(excel): Add missing dependencies

- docker/docker-compose.yml
Elastic Elasticsearch Multiple Log4j Vulnerabilities (ESA-2021-31, Log4Shell) Changed the version to 7.16.1
> fix(elasticsearch): version for security reason

- metadata-ingestion/tests/integration/nifi/docker-compose.yml
Change Zookeeper image to bitnamilegacy version in test
> fix(ingestion/nifi): Change Zookeeper image to bitnamilegacy version in test

- docs-website/docusaurus.config.js
this is to promote our 1 day virtual summit per Jen Atherly's request: https://app.asana.com/1/1203979157792006/project/1210127569658102/task/1211185547599558?focus=true
-  [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [PR Title Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#pr-title-format))
-  [X] Links to related issues (if applicable)
[NA] Tests for the changes have been added/updated (if applicable)
[NA] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
[NA] For any breaking changes
> docs: Update docs banner to promote Context event

- metadata-ingestion/setup.py
Reverts datahub-project/datahub#14630
Reverting this because PR accidentally got merged with some failing tests
> Revert "chore(kafka): fixes lower bound version for confluent_kafka dep in ingestion"

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_connection.py
⏺ Summary
Added automatic user-agent identification for BigQuery client connections to improve observability and client tracking.
Changes:
- BigQuery: Added ClientInfo with user-agent format datahub/{version} to all BigQuery client connections
- Imported ClientInfo from google.api_core.client_info and nice_version_name from datahub._version
- Created _get_bigquery_client_info() helper function that returns ClientInfo(user_agent=f"datahub/{__version__()}")
- Updated get_bigquery_client() method to include client_info=_get_bigquery_client_info() parameter
Benefits:
- Enables Google Cloud to identify DataHub client requests in BigQuery logs and monitoring
- Follows Google's recommended best practices for client identification using ClientInfo
- Consistent with existing patterns in Unity …
> feat(ingest/bigquery): Set user-agent for bigquery connections

- datahub-actions/src/datahub_actions/plugin/source/acryl/constants.py
- datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_event_source.py
- datahub-actions/tests/unit/plugin/source/acryl/test_datahub_cloud_event_source.py
- metadata-service/events-service/src/main/java/io/datahubproject/event/ExternalEventsService.java
- metadata-service/events-service/src/test/java/io/datahubproject/event/ExternalEventsServiceTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/event/ExternalEventsServiceFactory.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/event/ExternalEventsController.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v1/event/ExternalEventsControllerTest.java
- metadata-service/war/src/main/resources/boot/policies.json
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
Adding support for MCLs in DataHub server external events API. This will unblock DataHub Actions support for MCLs from DataHub Cloud and DataHub OSS
> feat(datahub-actions): Adding support for Metadata Change Log in DataHub Cloud Events Source

- datahub-graphql-core/src/main/resources/module.graphql
- datahub-web-react/src/app/entityV2/summary/modules/assets/AssetsModule.tsx
- datahub-web-react/src/app/entityV2/summary/modules/assets/__tests__/useGetAssets.test.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/__tests__/useGetDataProductAssets.test.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/__tests__/useGetDomainAssets.test.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/__tests__/useGetTermAssets.test.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/useGetAssets.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/useGetDataProductAssets.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/useGetDomainAssets.ts
- datahub-web-react/src/app/entityV2/summary/modules/assets/useGetTermAssets.ts
- datahub-web-react/src/app/homeV3/context/hooks/utils/utils.test.ts
- datahub-web-react/src/app/homeV3/context/hooks/utils/utils.ts
- datahub-web-react/src/app/homeV3/module/Module.tsx
- datahub-web-react/src/app/homeV3/modules/constants.ts
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/useAddModuleMenu.test.tsx
- datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
- metadata-models/src/main/pegasus/com/linkedin/module/DataHubPageModuleType.pdl
- metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
- metadata-service/configuration/src/main/resources/bootstrap_mcps/page-modules.yaml
- metadata-service/services/src/main/java/com/linkedin/metadata/service/PageModuleService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/PageModuleServiceTest.java
https://linear.app/acryl-data/issue/CH-722/support-assets-module-on-summary-pages
Description:
Supports Asset module on summary pages for domain and data products.
TODO: 
- Add support on glossary term pages
- Do not show this module item in add menu on home page
> feat(summary-tab): support assets module on the summary pages

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/athena_properties_extractor.py
- metadata-ingestion/tests/unit/test_athena_source.py
⏺ Fix Athena partition extraction and CONCAT function type issues
Summary
This PR fixes two critical issues in the Athena source:
Partition extraction not respecting extract_partitions=false - The configuration was being ignored and partition extraction was still happening
CONCAT function type mismatch errors - Type conflicts when concatenating partition keys with different data types (e.g., integer year with varchar separator)
Problem
Users experienced errors like:
FUNCTION_NOT_FOUND: line 1:108: Unexpected parameters (integer, varchar(1)) for function concat.
Expected: concat(E, array(E)) E, concat(array(E)) E, concat(array(E), E) E, concat(char(x), char(y)), concat(varbinary), concat(varchar)
Even when extract_partitions: false was set, partition extraction still occurred and failed on …
> fix(ingest/athena): Fix Athena partition extraction and CONCAT function type issues

- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
- metadata-ingestion/tests/unit/test_iceberg.py
1. Function processing dataset handles superclass exception `RESTError` instead of `ServerError`
2. Exceptions while retrieving namespace properties are handled so that they don't affect entire execution
3. Additional exception type is handled as a warning when listing tables in a namespace
> fix(ingestion/iceberg): Improve iceberg source resiliency to server errors

- metadata-ingestion/setup.py
This prevents errors like:
```
<class 'pyiceberg.exceptions.NotInstalledError'>: AWS glue support not installed: pip install 'pyiceberg[glue]'
```
> chore(ingestion/iceberg): Include explicit extras in dependencies

- metadata-ingestion/setup.py
This reverts commit 3af386b626da363df1efc7a21fe383b5485cf0cd.
Reverts PR: https://github.com/datahub-project/datahub/pull/14736
Rationale:
Currently Managed UI ingestion installs only `acryl-datahub[iceberg]` which actually pulls the newest (0.10.0) version. This safeguard would help for users who use `acryl-datahub[all]` (i.e. use datahub ingestion image directly), but potentially would break compatibility for users who are ingesting via the UI.
I propose we lift this safeguard and add a release note informing about difference in config, after we merge changes allowing to install pydantic version 2, when installing `all`.
> Revert "chore(ingestion/iceberg): Safe-guard pyiceberg version before pydantic 1->2 transition (#14736)"

- datahub-web-react/src/app/searchV2/sidebar/BrowseNode.tsx
- datahub-web-react/src/app/searchV2/sidebar/PlatformNode.tsx
- datahub-web-react/src/app/searchV2/sidebar/useBrowsePagination.tsx
When leaving the nested folder, we'd have 2 pages of results but the internal component state would think we only had one and fetch the second page, getting no new results. I couldn't reason about the existing code so I cleaned it up. A consequence of the refactor is that after selecting a folder, we're no longer hiding other loaded folders in the same platform. I think this is a better experience anyway so seems like an improvement. I also added a loading state to improve UX.
> fix(ui/browse): Fix bug where browse would not paginate when leaving a nested container

- datahub-web-react/src/app/permissions/policy/PolicyActorForm.tsx
- datahub-web-react/src/app/permissions/policy/PolicyPrivilegeForm.tsx
- datahub-web-react/src/graphql/policy.graphql
- smoke-test/tests/cypress/cypress/e2e/mutations/manage_ingestion_secret_privilege.js
When we edit a policy, we currently render the urns for Tags, Users and Groups.. instead of the readable display name. Fixing that in this PR
> fix(ui): Render the values instead of urns in Policies Modal

- datahub-web-react/src/app/homeV3/HomePageContent.tsx
- datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
- datahub-web-react/src/app/homeV3/module/components/SmallModule.tsx
- datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
- docs/features/feature-guides/custom-home-page.md
- smoke-test/tests/cypress/cypress/e2e/homeV3/modules.js
- smoke-test/tests/cypress/cypress/e2e/homeV3/templates.js
Adds some changes to template edit-ability making sure that if you shouldn't be allowed to edit the home page that you can't.
> feat(ui) Update home page template editability

- metadata-ingestion/src/datahub/ingestion/source/redash.py
- metadata-ingestion/tests/unit/test_redash_source.py
Need to throw a warning not error on sql parsing exceptions
> fix(ingest): change redash sql parse error to warnining

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandler.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandlerTest.java
By default we throw `RuntimeException` in our code but in this exception handler we were not handling that leading to `An unknown error occurred` being the default response which caused API responses to not be useful in case an error happened.
On a local endpoint that I was working on
Before
```
❌ Test FAILED with error: GraphQL errors: [{'message': 'An unknown error occurred.', 'locations': [{'line': 3, 'column': 9}], 'path': ['startS3StreamingUpload'], 'extensions': {'code': 500, 'type': 'SERVER_ERROR', 'classification': 'DataFetchingException'}}]
File "/Users/aseembansal/code/recipes/./scripts/test_s3_streaming_upload.py", line 267, in main
upload_result = start_streaming_upload(
^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> fix(exception): surface exceptions to API response

- datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx
https://linear.app/acryl-data/issue/CH-769/documentation-on-the-sidebar-has-different-formatting-styles
Changes the `Editor` used in `CompactMarkdownViewer` to use the one from our component library. This allows the styles lije font size, underline etc. to consistently take effect.
> improvement(ui/summary-tab): use editor from component library in CompactMarkdownViewer for consistent styles

- metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
- metadata-ingestion/src/datahub/ingestion/source/superset.py
- metadata-ingestion/tests/integration/superset/golden_test_aggregate_ingest.json
- metadata-ingestion/tests/integration/superset/golden_test_ingest.json
- metadata-ingestion/tests/integration/superset/golden_test_stateful_ingest.json
- metadata-ingestion/tests/integration/superset/test_superset.py
- Get chart & dashboard tags from the metadata, extract user-defined tags (`type == 1` ([source](https://github.com/apache/superset/blob/master/superset/tags/models.py#L61-L77))) and append them to chart and dashboard aspects
---
**Checklist**
> feat(superset/preset): propagate chart & dashboard tags to DataHub

- build.gradle
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandler.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandlerTest.java
- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/GraphQueryBaseDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAORelationshipGroupQueryTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/GraphQueryElasticsearch7DAOTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/GraphQueryOpenSearchDAOTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/LineageSearchServiceTest.java
- smoke-test/tests/utils.py
* add graphql error forwarding for illegalstate exceptions
> fix(impact-lineage): separate viz and impact query path

- smoke-test/tests/cypress/cypress/e2e/structured_properties/structured_properties.js
https://linear.app/acryl-data/issue/CH-795/oss-bring-tests-for-structured-properties
This PR brings the cypress tests for structured properties to OSS
> test: bring cypress tests for structured properties to OSS

- datahub-web-react/src/app/entityV2/shared/containers/profile/header/DefaultEntityHeader.tsx
- datahub-web-react/src/app/sharedV2/OverflowList.tsx
https://linear.app/acryl-data/issue/CH-784/adding-link-to-header-infinite-flashing
This fixes the links of certain widths flashing infinitely in the entity header.
This also handles the entity name getting truncated even when there's space available.
Before:
After:
> fix(ui): fix link in entity header flashing infinitely

- metadata-ingestion/docs/sources/redshift/redshift_pre.md
- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
Because of a lack of permission, we could not extract tables from a schema that was not visible in our schema query.
I added a join to make sure the two queries are consistent.
> fix(ingest/redshift): Fix for missing schema containers during ingestion

- metadata-ingestion/src/datahub/ingestion/source/metabase.py
Upstream lineage URNs are being created in uppercase while they should be lowercase.
> feat(ingest): add lowercase urn config option to metabase source

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
This fixes the issue on MWAA, where it seems like the import level variable setting didn't work.
My idea is this is what happened:
1. Module import happens first (when Python starts up, before your DAG runs)
2. At import time, OVERRIDE_SQLITE_VERSION_REQ is not yet set
3. So the module-level variables get cached as:
OVERRIDE_SQLITE_VERSION_REQUIREMENT_STR = ""
OVERRIDE_SQLITE_VERSION_REQUIREMENT = False
4. Later, your DAG code sets OVERRIDE_SQLITE_VERSION_REQ=true
5. The log shows the environment variable is now set correctly
6. But the module-level cached variables are still False from the original import
7. When FileBackedDict.__post_init__ runs, it uses the cached OVERRIDE_SQLITE_VERSION_REQUIREMENT = False
8. So it raises the SQLite version error
> fix(ingestion): Fix for module level variable caching in sqllite check

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_insert_with_cte.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
Thanks @ligfx - for the code suggestion.
> feat(sqlglot): preserve CTEs when extracting SELECT from INSERT statements and add corresponding unit test

- metadata-ingestion/src/datahub/ingestion/source/aws/s3_boto_utils.py
- metadata-ingestion/src/datahub/ingestion/source/data_lake_common/path_spec.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/integration/s3/golden-files/gcs/golden_mces_allow_table.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_allow_table.json
- metadata-ingestion/tests/integration/s3/test_s3.py
- metadata-ingestion/tests/unit/data_lake/test_path_spec.py
- metadata-ingestion/tests/unit/s3/test_s3_source.py
- fix: make `dir_allowed` work with `tables_filter_pattern`
- don't list all partitions when `traversal method != ALL`
- don't list all partitions when `traversal method == ALL`
- `get_dir_to_process`: don't recurse if already at correct depth
- `get_dir_to_process`: apply s3 prefix filter when listing folders
- `get_folder_info`: apply s3 prefix filter when listing objects
- `get_dir_process`: skip S3 listing for fully-specified components
> feat(s3/ingest): performance improvements for get_dir_to_process and get_folder_info

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
Fixed the Snowflake external URL generation issue for privatelink connections.
The Problem:
The code was generating incorrect Snowsight URLs for privatelink accounts using the format:
https://app.my_org.us-east-1.privatelink.snowflakecomputing.com/#/data/databases/...
This was wrong because Snowsight is always accessed via the public internet (app.snowflake.com), even when the account uses privatelink for database connections. Privatelink only applies to the data plane (SQL queries), not the Snowsight web UI.
> fix(ingest/snowflake): Fixed the Snowflake external URL generation issue for privatelink connections.

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
- metadata-ingestion/tests/unit/snowflake/test_snowflake_queries.py
When running Snowflake ingestion with all query-based features disabled, the ingestion process was still:
- Fetching queries from Snowflake's `query_history` and `access_history` tables
- Parsing and fingerprinting each query
- Taking several minutes to process queries that would never be used
This happened because the feature flags (`include_lineage`, `include_queries`, `include_usage_statistics`, `include_query_usage_statistics`, `include_operations`) only controlled **what output was 
generated**, not **whether to fetch queries in the first place**.
```yaml
source:
type: snowflake
config:
include_table_lineage: false
include_queries: false
include_usage_stats: false
include_query_usage_statistics: false
include_operational_stats: false
include_views: true
Users would see …
```
> fix(ingest/snowflake): Skip sql parsing if all the features disable in config where it is needed

- metadata-ingestion/src/datahub/ingestion/source/grafana/models.py
In case title of panel is missing we started getting
```packages/datahub/ingestion/source/grafana/models.py", line 82, in extract_panels
Fri Oct  3 18:16:12 IST 2025	 panels.append(Panel.parse_obj(panel_data))
Fri Oct  3 18:16:12 IST 2025	 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fri Oct  3 18:16:12 IST 2025	 File "pydantic/main.py", line 532, in pydantic.main.BaseModel.parse_obj
Fri Oct  3 18:16:12 IST 2025	 File "pydantic/main.py", line 347, in pydantic.main.BaseModel.__init__
Fri Oct  3 18:16:12 IST 2025	 pydantic.error_wrappers.ValidationError: 1 validation error for Panel
Fri Oct  3 18:16:12 IST 2025	 title
Fri Oct  3 18:16:12 IST 2025	 field required (type=value_error.missing)
```
which caused the whole ingestion to start failing.
> fix(ingest/grafana): add exception handling

- datahub-web-react/src/alchemy-components/components/Checkbox/Checkbox.stories.tsx
- datahub-web-react/src/alchemy-components/components/Checkbox/Checkbox.tsx
- datahub-web-react/src/alchemy-components/components/Checkbox/components.ts
- datahub-web-react/src/alchemy-components/components/Checkbox/types.ts
- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/entityV2/shared/sidebarSection/SidebarStructuredProperties.tsx
- datahub-web-react/src/app/govern/structuredProperties/DisplayPreferences.tsx
- datahub-web-react/src/app/govern/structuredProperties/StructuredPropsDrawer.tsx
- datahub-web-react/src/app/govern/structuredProperties/StructuredPropsTable.tsx
- datahub-web-react/src/app/govern/structuredProperties/ViewDisplayPreferences.tsx
- datahub-web-react/src/app/govern/structuredProperties/__tests__/cacheUtils.test.ts
- datahub-web-react/src/app/govern/structuredProperties/__tests__/useStructuredProp.test.ts
- datahub-web-react/src/app/govern/structuredProperties/cacheUtils.ts
- datahub-web-react/src/app/govern/structuredProperties/styledComponents.ts
- datahub-web-react/src/app/govern/structuredProperties/useStructuredProp.ts
- datahub-web-react/src/graphql/fragments.graphql
This PR adds to UI option in settings of structured properties to hide them in assets sidebar
Additionally adjusted color of check mark in Checkbox component when it's disabled
> feat(structuredProperties): add option to hide properties with empty values

- datahub-web-react/src/app/govern/structuredProperties/DisplayPreferences.tsx
- smoke-test/tests/cypress/cypress/e2e/structured_properties/structured_properties.js
This PR adds cypress tests to cover flow with the new setting property `Hide when Empty` in structured properties
> tests(structuredProperties): add cypress tests

- docs-website/genJsonSchema/gen_json_schema.py
- metadata-ingestion/scripts/docgen.py
Pydantic v2 generates schemas for configs using the newer spec (using `$defs` instead of `definitions`), this PR makes adjustment for that.
> chore(doc): Fix json schema generation after pydantic v2 move

- datahub-web-react/src/app/entityV2/summary/properties/property/properties/BaseProperty.tsx
- datahub-web-react/src/app/entityV2/summary/properties/property/properties/__tests__/utils.test.ts
- datahub-web-react/src/app/entityV2/summary/properties/property/properties/utils.ts
https://linear.app/acryl-data/issue/CH-758/hide-current-property-in-dropdown-for-replace-in-summary-elements
This hides the current property that is clicked from the replace menu items in properties header on the asset summary tab.
It gives a better experience to the user as giving an option to replace a property with the same one doesn't make much sense.
> improvement(summary-tab): hide current property in replace dropdown of property header
