datahub-project/datahub

docs/how/updating-datahub.md
=> chore(docs): update release notes v0.14.1

docs-website/src/pages/_components/CaseStudy/case-study.module.scss, docs-website/src/pages/_components/Community/index.js, docs-website/src/pages/_components/Hero/hero.module.scss, docs-website/src/pages/_components/Hero/index.js, docs-website/src/pages/_components/Trial/index.js, docs-website/src/pages/_components/Trial/trial.module.scss, docs-website/src/pages/cloud/UnifiedTabs/index.js, docs-website/src/pages/index.js, docs-website/src/styles/global.scss
=> feat(docs-site) tours to open in a modal

build.gradle
=> chore(bump): bump spring versions

build.gradle
=> chore(bump): pac4j version

metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java
=> fix(SearchDocumentTransformer): Use correct variable to update ES

datahub-frontend/app/auth/sso/oidc/OidcConfigs.java, datahub-frontend/app/auth/sso/oidc/custom/CustomOidcClient.java, datahub-frontend/app/auth/sso/oidc/custom/CustomOidcRedirectionActionBuilder.java
=> fix(oidc): apply acr values to redirect url

metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
=> feat(ingest/sink): report datahub-rest sink mode

docs/cli.md, metadata-ingestion/developing.md
=> docs(ingest): add docs on pydantic compatibility

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/ScrollAcrossLineageResolver.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/search/ScrollAcrossLineageResolverTest.java
=> test(graphql): fix searchFlags in searchAcrossLineage

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java, metadata-service/configuration/src/main/resources/application.yaml, metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchIndexBuilderFactory.java
* disable reindex timeout by default
=> config(reindex): create reindex timeout configuration

datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/contract/utils.tsx
=> feat(data-contracts): support custom assertions in the data contracts builder

.github/workflows/docker-unified.yml, gradle.properties
=> build(gradle): Update gradle.properties

build.gradle, datahub-web-react/build.gradle, docs-website/build.gradle, smoke-test/build.gradle
=> build(yarn): increase yarn timeout and version bump

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
=> fix(ingest/dbt): allow custom owner types for dbt meta

docs/automations/docs-propagation.md
=> doc: fix typo

docs-website/src/pages/champions/_components/ChampionQualityCardsSection/championqualitycardssection.module.scss, docs-website/src/pages/champions/_components/ChampionQualityCardsSection/index.js, docs-website/src/pages/champions/index.js, docs-website/src/styles/global.scss
=> fix: fix broken global style

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
=> feat(ingest/dbt): speed up dbt CLL with node_name_patterns

docker/datahub-ingestion-base/Dockerfile
Partially addresses #11474.
We'll also need to cut a new release of datahub-actions once this is merged.
=> feat(ingest): add `git` to ingestion-base image

metadata-ingestion/src/datahub/configuration/source_common.py, metadata-ingestion/src/datahub/emitter/enum_helpers.py, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/emitter/mcp_builder.py, metadata-ingestion/tests/unit/test_codegen.py
Follow up on https://github.com/datahub-project/datahub/pull/11214 to improve compatibility.
Also refactors `get_enum_options` and adds a test.
=> feat(ingest): support `DATAHUB_INCLUDE_ENV_IN_CONTAINER_PROPERTIES`

docs/lineage/openlineage.md, metadata-service/war/src/main/resources/boot/data_platforms.json
Fixing path to the dagster logo
Updating openlinage doc
=> fix(ingest/dagster): Fixing path to the dagster logo

docker/profiles/docker-compose.gms.yml
Allow overriding with the above `DATAHUB_LOCAL_COMMON_ENV` and `DATAHUB_LOCAL_GMS_ENV`
WIll default to application of `true` in other cases.
=> docker(config): Update docker profiles

metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
=> feat(ingest/elasticsearch): add api_key auth

build.gradle, buildSrc/build.gradle, metadata-service/factories/build.gradle
=> chore(bump): bump commons, misc versions

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_dataproduct.py
=> fix(ingest): fix UnboundLocalError in dataproduct transformer

docs-website/src/pages/cloud/DemoForm/index.jsx
=> fix(docs-site) cloud form copy spelling error

docs-website/docusaurus.config.js, docs-website/src/pages/_components/Hero/hero.module.scss, docs-website/src/pages/_components/Hero/index.js, docs/quickstart.md
=> feat(website): added built by acryl and linkedin to home hero

metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> fix(datahub-gc): set system flag on ingestion source

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/getFieldDescriptionDetails.ts
=> fix(lint): fix yarn lint breakage from #11498

.github/workflows/docker-unified.yml
=> chore(ci): bump trivy action version

docs-website/sidebars.js, docs/managed-datahub/release-notes/v_0_3_6.md
=> docs(release): 0.3.6 - docs update

metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> fix(datahub-gc):  Update ingestion-datahub-gc.yaml

docs/how/search.md
=> docs(search): add structured search examples for structured properties

metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py, metadata-ingestion/src/datahub/ingestion/source_config/csv_enricher.py
=> docs(csv-enricher): Add warning for write_semantics

metadata-io/src/test/java/com/linkedin/metadata/entity/ebean/EbeanAspectDaoTest.java
=> fix(test): fix test specific for single query

docker/airflow/docker-compose.yaml, docker/cassandra/docker-compose.cassandra.yml, docker/docker-compose-with-cassandra.yml, docker/docker-compose-without-neo4j.override.yml, docker/docker-compose-without-neo4j.postgres.override.yml, docker/docker-compose-without-neo4j.yml, docker/docker-compose.consumers-without-neo4j.yml, docker/docker-compose.consumers.dev.yml, docker/docker-compose.consumers.yml, docker/docker-compose.dev.yml, docker/docker-compose.kafka-setup.yml, docker/docker-compose.override.yml, docker/docker-compose.tools.yml, docker/docker-compose.yml, docker/ingestion/docker-compose.yml, docker/mariadb/docker-compose.mariadb.yml, docker/monitoring/docker-compose.consumers.monitoring.yml, docker/monitoring/docker-compose.monitoring.yml, docker/mysql/docker-compose.mysql.yml, docker/quickstart/docker-compose-m1.quickstart.yml, docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml, docker/quickstart/docker-compose-without-neo4j.quickstart.yml, docker/quickstart/docker-compose.consumers-without-neo4j.quickstart.yml, docker/quickstart/docker-compose.consumers.quickstart.yml, docker/quickstart/docker-compose.kafka-setup.quickstart.yml, docker/quickstart/docker-compose.monitoring.quickstart.yml, docker/quickstart/docker-compose.quickstart.yml, docker/quickstart/generate_docker_quickstart.py, metadata-integration/java/spark-lineage-legacy/spark-smoke-test/docker/spark-docker-compose.yml
This gives warnings when running quickstart
=> chore: remove obsolete attribute from docker

metadata-ingestion/src/datahub/cli/delete_cli.py, smoke-test/cypress-dev.sh, smoke-test/run-quickstart.sh
=> fix(cli): update hard delete confirmation message in delete cli

metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py, metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state.json, metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state_after_deleted.json, metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion.json, metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion_after_deleted.json, metadata-ingestion/tests/unit/stateful_ingestion/state/test_stateful_ingestion.py
=> feat(ingest/stateful): omit irrelevant urns for deletion

metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
=> feat(ingest): add extra reporting for rest sink ASYNC_BATCH mode

docs/lineage/airflow.md, metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_config.py, metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
=> feat(airflow): add a `render_templates` config parameter

datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
=> fix(ui): update soft-deletion banner message

metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
=> fix(ingest/looker): handle sdk error for folder_ancestors

.github/workflows/airflow-plugin.yml, metadata-ingestion-modules/airflow-plugin/setup.py, metadata-ingestion-modules/airflow-plugin/tox.ini
=> feat(airflow): add airflow 2.10 to test matrix

smoke-test/tests/cypress/README.txt
=> docs(cypress): Update README.txt

.github/workflows/docker-unified.yml, docker/build.gradle
=> fix(trivy): multi-repo, bump trivy version

.github/workflows/docker-unified.yml, docker/build.gradle
=> fix(trivy): also add alternative java db

docs-website/src/pages/cloud/DemoForm/styles.module.scss, docs-website/src/pages/cloud/DemoFormModal/index.jsx, docs-website/src/pages/cloud/DemoFormModal/styles.module.scss, docs-website/src/pages/cloud/Hero/index.js, docs-website/src/pages/cloud/Hero/styles.module.scss, docs-website/src/pages/cloud/index.js, docs-website/src/pages/cloud/styles.module.scss
=> fix: display demo form modal on mobile

metadata-ingestion/src/datahub/ingestion/graph/client.py
=> fix(ingest): gracefully handle missing system metadata in client

docs/api/tutorials/custom-assertions.md
=> docs(assertions): add example of fetching associated dataset to assertion docs

build.gradle
=> chore(frontend): force frontend protobuf version

metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
=> fix(bootstrap): fix early bootstrap mcps

metadata-integration/java/spark-lineage-legacy/scripts/check_jar.sh
=> fix(spark-lineage-legacy): fix check jar script

metadata-ingestion/src/datahub/api/entities/platformresource/platform_resource.py, smoke-test/tests/platform_resources/test_platform_resource.py
=> fix(sdk): platform resource api for non existent resources

metadata-ingestion/src/datahub/ingestion/source/preset.py
=> fix(ingest/preset): Add skip_on_failure to root_validator decorator

docs-website/sidebars.js, docs/automations/ai-docs.md, docs/automations/ai-term-suggestion.md, docs/automations/snowflake-tag-propagation.md
Related: https://github.com/datahub-project/static-assets/pull/101
=> docs: add docs on term suggestion

metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
=> fix(airflow): fix lint related to dag_run field

docs-website/docusaurus.config.js, docs-website/src/pages/index.js, docs-website/src/styles/global.scss
=> feat(docs-site) brought back announcement banner

docs/advanced/mcp-mcl.md
=> docs(ingestion): add architecture diagrams

.github/workflows/contributor-open-pr-comment.yml
=> fix(ci): Update contributor-open-pr-comment.yml

.github/workflows/metadata-ingestion.yml
=> fix(ci): add runtime limit

.github/workflows/metadata-io.yml
=> fix(ci): metadata-io req python

.github/workflows/build-and-test.yml
=> fix(ci): fix build and test workflow

metadata-ingestion/src/datahub/cli/check_cli.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
=> feat(ingest): add offline flag to SQL parser CLI

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py, metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_platform_resource_helper.py, metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
=> fix(ingest/bigquery): Not setting platform instance for bigquery platform resources

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
=> fix(ingest/dbt): fix bug in CLL pruning

docs/lineage/airflow.md
=> docs(airflow): add known limitations for automatic lineage

metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/client/dagster_generator.py
=> fix(ingest/dagster): FIx JobSnapshot import is broken

metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py, metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py, metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py, metadata-ingestion/tests/integration/fivetran/test_fivetran.py
=> feat(ingest/fivetran): protect against high sync volume

docs-website/docusaurus.config.js, docs-website/src/styles/global.scss
=> fix(docs-site): announcement bar responsive behavior

metadata-ingestion/scripts/avro_codegen.py, metadata-ingestion/src/datahub/api/entities/platformresource/platform_resource.py
=> feat(ingest): generate urn types for all entities

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py, metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json, metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
=> fix(ingest/bigquery): Fix tags urn/name ingestion for BigQuery 

metadata-ingestion/src/datahub/ingestion/api/source_helpers.py, metadata-ingestion/src/datahub/ingestion/source/fivetran/config.py, metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py, metadata-ingestion/src/datahub/ingestion/transformer/system_metadata_transformer.py, metadata-ingestion/src/datahub/testing/compare_metadata_json.py
Also updates Fivetran config docs.
=> fix(ingest): add logging for mcp diff

metadata-ingestion/src/datahub/ingestion/source/mongodb.py, metadata-ingestion/tests/integration/mongodb/mongodb_mces_golden.json, metadata-ingestion/tests/integration/mongodb/mongodb_mces_small_schema_size_golden.json
=> fix(ingest/mongodb): Add Collection Name as Dataset Name in MongoDB

metadata-ingestion/src/datahub/ingestion/source/superset.py
=> fix(ingest/superset): Don't set schema/db for druid

.github/workflows/build-and-test.yml, .github/workflows/documentation.yml, .github/workflows/metadata-ingestion.yml
=> fix(ci): remove pip cache

docs/managed-datahub/release-notes/v_0_3_6.md
=> docs(managed/v0.3.6): Add additional release notes for 0.3.6.8

docker/build.gradle
=> gradle(profiles): create compose base variable

docker/build.gradle
=> misc(gradle): project name parameter

datahub-web-react/src/app/shared/businessAttribute/AddBusinessAttributeModal.tsx
Bug Link - https://github.com/datahub-project/datahub/issues/11719
=> fix: business attribute empty bubble selection issue

docs/managed-datahub/slack/saas-slack-troubleshoot.md
=> feat(docs) steps on how to troubleshoot the slack command not working

docs/how/updating-datahub.md
=> doc: add missed breaking change note

metadata-ingestion/setup.py
Closes https://github.com/datahub-project/datahub/issues/11718
=> feat(ingest): unpin traitlets

metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
Closes https://github.com/datahub-project/datahub/issues/11640
=> fix(ingest/unity): remove redundant check

metadata-ingestion/docs/sources/dbt/dbt-cloud_pre.md, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
=> docs(dbt-cloud): reference service accounts in docs

metadata-ingestion/setup.py
=> fix(ingest/bigquery): add missing path spec deps

metadata-ingestion/setup.py
=> fix(ingest): pin teradata dep

datahub-web-react/src/app/entity/shared/tabs/Incident/components/AddIncidentModal.tsx, datahub-web-react/src/app/entity/shared/tabs/Incident/components/IncidentListItem.tsx
- Support authoring incidents with markdown descriptions
- Support viewing incident markdown description
=> feat(ui): Support markdown for incident descriptions

datahub-upgrade/src/test/resources/bootstrapmcp/datahub-test-mcp.yaml, metadata-ingestion/docs/sources/gc/gc_recipe.dhub.yml, metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py, metadata-ingestion/src/datahub/ingestion/source/gc/execution_request_cleanup.py, metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml, metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> feat(ingestion): Add execution request cleanup job

metadata-ingestion/setup.py
=> feat(ingest): unpin looker-sdk dependency

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/parser.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py, metadata-ingestion/src/datahub/sql_parsing/schema_resolver.py, metadata-ingestion/src/datahub/utilities/partition_executor.py, metadata-ingestion/src/datahub/utilities/perf_timer.py, metadata-ingestion/tests/unit/sql_parsing/test_schemaresolver.py, metadata-ingestion/tests/unit/utilities/test_perf_timer.py
- Adds additional stats + error reporting
- Fix dependency declaration
- ~Incorporates changes from https://github.com/datahub-project/datahub/pull/11756~
- Support mixed-case platform instances with lowercased urns
- Fix a deadlock bug in the rest sink's ASYNC_BATCH mode
=> feat(ingest/powerbi): improve reporting around m-query parser

docs/quick-ingestion-guides/bigquery/setup.md
=> doc(bigquery): Update setup.md

datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/system/bootstrapmcps/BootstrapMCPUtilTest.java, metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml, metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> Make DatahubGC bootstrap MCP non-optional

metadata-ingestion/tests/integration/openapi/openapi_mces_golden.json, metadata-ingestion/tests/integration/openapi/openapi_to_file.yml
Openapi tests got broken due to test refactoring on the Openapi side.
=> fix(ingest/openapi): Fix openapi tests

metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
=> fix(entity-client): switch to caller runs for entity-client

metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml, metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> bump(cli): Update ingestion-datahub-gc.yaml

docs/how/updating-datahub.md, metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py, metadata-ingestion/tests/integration/powerbi/golden_test_admin_access_not_allowed.json, metadata-ingestion/tests/integration/powerbi/golden_test_admin_only.json, metadata-ingestion/tests/integration/powerbi/golden_test_cll.json, metadata-ingestion/tests/integration/powerbi/golden_test_container.json, metadata-ingestion/tests/integration/powerbi/golden_test_endorsement.json, metadata-ingestion/tests/integration/powerbi/golden_test_ingest.json, metadata-ingestion/tests/integration/powerbi/golden_test_ingest_patch_disabled.json, metadata-ingestion/tests/integration/powerbi/golden_test_lineage.json, metadata-ingestion/tests/integration/powerbi/golden_test_lower_case_urn_ingest.json, metadata-ingestion/tests/integration/powerbi/golden_test_personal_ingest.json, metadata-ingestion/tests/integration/powerbi/golden_test_platform_instance_ingest.json, metadata-ingestion/tests/integration/powerbi/golden_test_report.json, metadata-ingestion/tests/integration/powerbi/golden_test_server_to_platform_instance.json
=> fix(ingest/powerbi): change default for `use_powerbi_email`

docs/how/updating-datahub.md
=> docs(breaking-changes): datahub-gc

metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_classes.py
=> fix(ingestion/powerbi): object has no attribute startswith

datahub-web-react/src/app/search/SearchablePage.tsx
=> feat(web-react) improved webpage title generation logic

.github/workflows/docker-unified.yml
=> fix(ci): additional disk clean

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
In case someone sets owner to be multiple
=> fix(ingest/dbt): handle multiple owners

metadata-ingestion-modules/gx-plugin/src/datahub_gx_plugin/action.py
=> fix(ingest): update GX version having name arg

docs/managed-datahub/release-notes/v_0_3_7.md
=> docs(release): helm chart version req 0.3.7

metadata-ingestion/src/datahub/ingestion/source/sql/oracle.py, metadata-ingestion/tests/unit/test_oracle_source.py
=> fix(ingest/oracle): fix scheme for sqlalchemy < 2

docs/managed-datahub/release-notes/v_0_3_7.md
=> fix(docs): Update v_0_3_7.md

docs/managed-datahub/release-notes/v_0_3_7.md
=> fix(doc): fix link to doc, update cli recommendation

build.gradle
=> chore(version): bump netty version

docs/how/search.md
=> docs(search): example tag AND condition

metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
=> fix(ingest/airflow): Add log to dag emit

docs/what/urn.md
=> docs(urn): urn encoding

metadata-ingestion/setup.py
Closes https://github.com/datahub-project/datahub/issues/11103
=> fix(ingest): upgrade msal

metadata-ingestion/src/datahub/cli/check_cli.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py, metadata-ingestion/tests/unit/sql_parsing/goldens/test_sqlite_attach_database.json, metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
=> fix(ingest): consider sql parsing fallback as failure

li-utils/src/main/javaPegasus/com/linkedin/common/urn/UrnUtils.java
=> chore(cleanup): remove unused UrnUtils function

metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
=> fix(ingest): add error handling

docs/api/restli/restli-overview.md
=> chore(docs): Update restli-overview.md

metadata-ingestion/src/datahub/utilities/is_pytest.py, metadata-ingestion/tests/conftest.py
When the pytest module is loaded, we would run sanity checks to validate that our patcher behaved properly. This was intended for testing and debugging only.
However, there are environments where pytest will be loaded for normal execution. Airflow and Dagster environments are particular examples, but there's likely others as well. In those environments, we'd see an error like this:
```
FileNotFoundError: [Errno 2] No such file or directory: 'patch'
File "/venvs/1407f5f85ba1/lib/python3.8/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
yield
File "/venvs/1407f5f85ba1/lib/python3.8/site-packages/dagster/_grpc/server.py", line 255, in __init__
loadable_targets = get_loadable_targets(
File "/venvs/1407f5f85ba1/lib/python3.8/site-packages/dagster/_grpc/utils.py", …
```
=> fix(ingest/sql): disable patch checker

metadata-ingestion/docs/sources/sac/sac_pre.md
With the quarterly update this weekend SAP changed something on the API permissions, which is why we need one additional permission to be able to use the API for ingestion: Story Listing
=> docs(ingest/sac): add additional permission for SAP Analytics Cloud source to docs

metadata-ingestion/src/datahub/utilities/file_backed_collections.py
=> docs(ingest): Raise error on unsupported sqlite version

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/service/AnalyticsUtil.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/utils/AnalyticsUtilTest.java
=> fix(analytics): look at userEditableInfo to populate cells

entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/AspectsBatch.java, metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImpl.java, metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImplTest.java, metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java, metadata-service/services/src/main/java/com/linkedin/metadata/entity/EntityService.java
=> fix(batch-patch): fix patches in batches

docs/how/updating-datahub.md, docs/managed-datahub/release-notes/v_0_3_7.md, li-utils/src/main/java/com/linkedin/metadata/Constants.java, metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/analytics/Analytics.java, metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java, metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java, metadata-utils/src/main/java/com/linkedin/metadata/utils/CriterionUtils.java, metadata-utils/src/test/java/com/linkedin/metadata/utils/CriterionUtilsTest.java
=> fix(rest.li): fix use of Criterion in rest.li filters

docker/profiles/docker-compose.gms.yml, docs/deploy/environment-vars.md, docs/what/urn.md, metadata-io/build.gradle, metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationApiUtils.java, metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/validation/ValidationApiUtilsTest.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
=> fix(validation): improved urn validation logic

metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl
Lower the impact of a schema field/column match on a dataset.
=> feat(search): adjust schema field boost

metadata-ingestion/src/datahub/configuration/kafka_consumer_config.py, metadata-ingestion/tests/unit/test_kafka_source.py
=> feat(ingest/kafka): improve error handling of oauth_cb config

metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> fix: remove ai summit post

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
=> docs(ingest/bigquery): add partition support capability

metadata-io/src/main/java/com/linkedin/metadata/dataproducts/sideeffects/DataProductUnsetSideEffect.java, metadata-io/src/test/java/com/linkedin/metadata/dataproducts/sideeffects/DataProductUnsetSideEffectTest.java
Condenses patches per Data Product urn, so can significantly reduce fan out in certain scenarios like all assets flipping from one data product to another. Also reduces potential repeated work for bulk edits of assets.
=> fix(dataProduct): reduce write fan-out for unset side effect

metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py
=> fix(ingest/tableau): handle none database field

metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationApiUtils.java, metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/validation/ValidationApiUtilsTest.java
=> fix(urn-validator): update urn validation logic

metadata-ingestion/src/datahub/ingestion/source/kafka/kafka.py
=> feat(ingest): add more logs for kafka polling

docs/how/updating-datahub.md, docs/managed-datahub/release-notes/v_0_3_7.md
=> docs(cloud): add documentation for Data Product side effect

metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py, metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json, metadata-ingestion/tests/integration/sql_server/source_files/mssql_no_db_with_filter.yml
=> feat(ingest/mssql): allow filtering by procedure_pattern

.github/workflows/check-datahub-jars.yml, metadata-integration/java/datahub-protobuf/scripts/check_jar.sh, metadata-integration/java/datahub-schematron/lib/build.gradle
=> fix(shadowJar): fix shadowJar

metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml, metadata-service/configuration/src/main/resources/bootstrap_mcps/ingestion-datahub-gc.yaml
=> feat(datahub-gc): add truncation days param

docs/managed-datahub/release-notes/v_0_3_7.md
=> docs(release): Update v_0_3_7.md

.github/workflows/build-and-test.yml
=> fix(ci): fix build-and-test

build.gradle, datahub-frontend/play.gradle
=> chore(bump): bump version of akka for datahub-frontend

docs/managed-datahub/release-notes/v_0_3_7.md
=> docs(release): update recommended CLI

metadata-ingestion/setup.py
=> feat(ingest): bump typing_extensions dep

metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py, metadata-ingestion-modules/airflow-plugin/tox.ini
=> feat(airflow): show dag/task logs in CI

docs/managed-datahub/release-notes/v_0_3_7.md
=> chore(docs): Update v_0_3_7.md - v0.3.7.5

metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- Not deleting empty entities as that can cause lineage to break for orgs
=> fix(ingest/gc): typo fix, do not delete empty entities

metadata-ingestion/src/datahub/ingestion/source/gc/dataprocess_cleanup.py
- Not deleting empty entities as that can cause lineage to break for orgs
=> fix(ingest/gc): do not cleanup empty job/flow

metadata-io/src/test/java/com/linkedin/metadata/search/fixtures/SampleDataFixtureTestBase.java, metadata-io/src/test/resources/search_config_fixture_test.yml
=> fix(test): fix metadata-io tests

metadata-integration/java/datahub-client/build.gradle
=> fix(ci): fix datahub-client validatePythonEnv

datahub-web-react/src/app/ingest/source/executions/reporting/StructuredReportItem.tsx
Support long messages in the title and description of error logs.
=> fix(ui): Adding overflow handling (also goes to oss)

metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/data_classes.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/pattern_handler.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py, metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/tree_function.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
=> fix(ingest/powerbi): reduce type cast usage

datahub-web-react/src/app/search/SimpleSearchFilters.tsx
=> fix(web) disallow deselecting all degrees on impact analysis view

datahub-frontend/build.gradle
=> build(datahub-frontend): enable code-coverage

metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/src/datahub/utilities/partition_executor.py, metadata-ingestion/tests/unit/utilities/test_partition_executor.py
=> feat(ingest): allow max_workers=1 with ASYNC_BATCH rest sink

metadata-integration/java/datahub-client/build.gradle
tested locally with `publishMavenLocal`
```
$ ./gradlew :metadata-integration:java:datahub-client:publishToMavenLocal 
...
$ ls $HOME/.m2/repository/io/acryl/datahub-client/*      
/Users/sergio/.m2/repository/io/acryl/datahub-client/maven-metadata-local.xml
/Users/sergio/.m2/repository/io/acryl/datahub-client/0.15.0rc3-SNAPSHOT:
datahub-client-0.15.0rc3-SNAPSHOT-javadoc.jar datahub-client-0.15.0rc3-SNAPSHOT-sources.jar datahub-client-0.15.0rc3-SNAPSHOT.jar         datahub-client-0.15.0rc3-SNAPSHOT.pom         maven-metadata-local.xml
$
```
and
```
$ ./gradlew clean :metadata-integration:java:datahub-client:publishToMavenLocal -PjavaClassVersionDefault=8 -ParchiveAppen         
$ ls $HOME/.m2/repository/io/acryl/datahub-client-java8/* …
```
=> fix(datahub-client): adds missing archiveAppendix to artifactid when publishing

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
Follow up on https://github.com/datahub-project/datahub/pull/12105
=> fix(ingest/snowflake): further improve dot handling

metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py, metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename.json, metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_swap.json, metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_swap_with_temp.json, metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_utils.py
- Handle `--` comments properly
- Better handling for whitespace around parens and commas
=> feat(ingest): improve query fingerprinting

docs-website/generateDocsDir.ts, docs-website/sidebars.js, docs/lineage/airflow.md, docs/lineage/sql_parsing.md, metadata-ingestion/scripts/docgen.py
=> docs(ingest): add docs on the SQL parser

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
=> fix(ingest/snowflake): improve warn message

entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/DataJobInputOutputPatchBuilder.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/UpstreamLineagePatchBuilder.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/FineGrainedLineageTemplateHelper.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/TemplateUtil.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/datajob/DataJobInputOutputTemplate.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/dataset/UpstreamLineageTemplate.java, entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/template/DataJobInputOutputTemplateTest.java
- Add Finegrained Lineage patch support for DatajobInputOutput
- Encoded patch path caused patch failure in UpstreamLineage aspect patching
=> fix(patch): Add Finegrained Lineage patch support for DatajobInputOutput (#4749)

metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
=> feat(ingest/datahub): report progress on db ingestion

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
Follow up on https://github.com/datahub-project/datahub/pull/12125
=> fix(ingest/snowflake): improve lineage parse failure logging

docs/managed-datahub/release-notes/v_0_3_7.md
=> docs(release): v0.3.7.7

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/EmbeddedModelMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeatureMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeaturePropertiesMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeatureTableMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeatureTablePropertiesMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLModelGroupMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLModelGroupPropertiesMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLModelPropertiesMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLPrimaryKeyMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLPrimaryKeyPropertiesMapper.java, datahub-graphql-core/src/main/resources/entity.graphql
Tried to standardize the code here.
=> feat(graphql/ml): Add custom properties to ml entities

docker/datahub-ingestion-base/build.gradle, docker/datahub-ingestion/build.gradle, docker/profiles/docker-compose.actions.yml
=> chore(bump): ingestion-base & actions

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
=> fix(gms): Change names of charts in Analytics

docs/managed-datahub/release-notes/v_0_3_7.md
=> docs update: Update v_0_3_7.md

metadata-ingestion/src/datahub/specific/dataproduct.py
=> fix(ingest): quote asset urns in patch path

metadata-ingestion/src/datahub/ingestion/graph/client.py
=> fix(ingest): preserve certs when converting emitter to graph

.github/workflows/docker-unified.yml, smoke-test/.gitignore, smoke-test/build.gradle, smoke-test/conftest.py, smoke-test/smoke.sh, smoke-test/tests/cypress/integration_test.py
=> Parallelize smoke test

build.gradle
=> chore(bump): spring minor version bump 6.1.14

smoke-test/tests/cypress/integration_test.py
=> chore: cleanup extra lines

metadata-ingestion/tests/integration/athena/athena_mce_golden.json, metadata-ingestion/tests/integration/athena/test_athena_source.py
=> test(ingest/athena): add connector integration tests

docs/how/delete-metadata.md
See title. I hear questions about this often.
=> docs(undo_by_filter): Document un-soft-delete commands in delete-metadata.md

metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
=> feat(ingest/gc): truncate query usage statistics aspect

metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py, metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
also adds additional reported around tableau api calls and errors.
=> fix(ingest/tableau): retry on auth error for special case

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/datahub/config.py, metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_database_reader.py, metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
Follow up on https://github.com/datahub-project/datahub/pull/12129
=> feat(ingest/datahub): use stream_results with mysql

.github/workflows/airflow-plugin.yml, .github/workflows/build-and-test.yml, .github/workflows/dagster-plugin.yml, .github/workflows/gx-plugin.yml, .github/workflows/metadata-ingestion.yml, .github/workflows/metadata-io.yml, .github/workflows/prefect-plugin.yml
=> ci: upload test coverage to codecov

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- Add a try catch over table iteration
- Add a try catch over profiling specifically
=> fix(ingest/glue): don't fail on profile

metadata-ingestion/src/datahub/cli/cli_utils.py, metadata-ingestion/tests/unit/cli/test_cli_utils.py
=> fix(cli): correct url ending with acryl.io:8080

metadata-ingestion/src/datahub/utilities/file_backed_collections.py, metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
=> fix(ingest/file-backed-collections): Properly set _use_sqlite_on_conflict

metadata-ingestion/src/datahub/ingestion/source/datahub/config.py, metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
=> feat(ingest/datahub): support dropping duplicate schema fields

.github/actions/ci-optimization/action.yml, .github/workflows/airflow-plugin.yml, .github/workflows/build-and-test.yml, .github/workflows/dagster-plugin.yml, .github/workflows/gx-plugin.yml, .github/workflows/metadata-ingestion.yml, .github/workflows/metadata-io.yml, .github/workflows/prefect-plugin.yml
=> feat(ci): add manual trigger for full build

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
=> docs(ingest/glue): add permissions for glue

.github/workflows/build-and-test.yml
=> fix(ci): fix artifact upload name

docker/build.gradle
=>  fix(docker) add new gradle profile for consumer debug purpose

docs/how/updating-datahub.md
=> docs(async-api): addition to known issues

.gitignore, metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
=> feat(ingest): add `num_queries_used_in_lineage` counter

metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
=> fix(ingest/datahub): dataHubExecutionRequest default exclude

metadata-ingestion/src/datahub/secret/datahub_secrets_client.py
Wrong parsing of the recipe can cause empty secret names to be passed to the client. That can cause the other secrets to remain unbound.
=> fix(sdk): cleanup empty secret names

build.gradle
=> chore(bump): bump/align avro-serializer

datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx, docs/api/datahub-apis.md, docs/how/updating-datahub.md, gradle/versioning/versioning.gradle
=> feat(docs): Add release docs for 0.15.0

.github/dependabot.yml
=> build: create dependabot.yml to update github actions

metadata-ingestion/build.gradle, metadata-ingestion/pyproject.toml, metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py, metadata-ingestion/src/datahub/ingestion/source/aws/s3_boto_utils.py, metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py, metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py, metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_patch.py
Fixes issues introduced by https://github.com/datahub-project/datahub/pull/12364
=> fix(ingest): simplify + fix ruff config

.github/pr-labeler-config.yml, .github/workflows/pr-labeler.yml
=> ci: fix labeler config after upgrade

metadata-ingestion/docs/sources/redshift/redshift_recipe.yml
=> fix(ingest/redshift): example recipe fix

smoke-test/tests/structured_properties/test_structured_properties.py
Follow up on https://github.com/datahub-project/datahub/pull/12333. Happened because the #12359 / #12375 changes were merged while the PR was in review.
=> fix(smoke): fix lint failure

datahub-web-react/src/app/entity/dataProcessInstance/DataProcessInstanceEntity.tsx
=> fix(frontend): fix frontend build

docker/README.md
=> docs(docker): fix typo in docker hub url

docs/actions/README.md, docs/actions/sources/datahub-cloud-event-source.md
=> docs(): Add docs for DataHub Cloud x DataHub Actions

smoke-test/tests/restli/test_restli_batch_ingestion.py
=> fix(smoke-test) add smoke test for restli ingestProposalBatch 

docs/cli.md, metadata-ingestion/src/datahub/cli/container_cli.py
=> feat(ingest(cli): add domain helper, add progressbar

docs-website/sidebars.js, docs/managed-datahub/release-notes/v_0_3_8.md
This PR includes the WIP release notes for DataHub Cloud's v0.3.8 release.
=> DataHub Cloud release notes v0.3.8

metadata-ingestion/docs/sources/tableau/tableau_pre.md
=> docs(ingest/tableau): clarify impact of lower permissions

docs/actions/sources/datahub-cloud-event-source.md, docs/managed-datahub/datahub-api/entity-events-api.md
=> fix(docs): Add links to new datahub cloud event source

metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
=> fix(ingest/clickhouse): remove unused lineage_properties code path

metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/OperationsController.java
=> misc(search-explain): set default value

docs/automations/bigquery-metadata-sync.md, docs/automations/docs-propagation.md, docs/automations/glossary-term-propagation.md, docs/automations/snowflake-tag-propagation.md
=> docs: add beta labels for Automation

datahub-web-react/src/graphql/search.graphql
=> gql: add data platform instance to search fragment

metadata-ingestion/src/datahub/ingestion/source/looker/looker_config.py, metadata-ingestion/src/datahub/ingestion/source/looker/looker_file_loader.py
=> feature(ingestion/lookml): Report view file missing/parsing errors as warnings

datahub-upgrade/build.gradle, datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/OpenTelemetryConfig.java, datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/UpgradeCliApplicationTest.java
=> fix(nocode): fix no-code upgrade

docs/managed-datahub/observe/assertions.md
=> feat(docs) assertion execution behavior

docs/ui-ingestion.md
With this searching for this page is extremely hard
=> docs: change heading of ingestion page

metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchRequestHandlerTest.java
=> fix(test): fix metadata-io test

.github/workflows/metadata-model.yml
=> fix(ci): disable ci telemetry modelDocUpload

metadata-ingestion/docs/sources/mode/mode.md, metadata-ingestion/docs/sources/mode/mode_pre.md
=> docs(ingest/mode): add details on authentication/permissions for mode

metadata-ingestion/examples/ai/dh_ai_client.py, metadata-ingestion/examples/ai/dh_ai_client_sample.py
allows ingestion without tokens when token-based authentication is disabled. 
locally tested and it worked fine
=> docs: fix token to be not required in sample script 

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
=> fix(ingest/glue): change to warning on access denied

metadata-ingestion/src/datahub/ingestion/source/mode.py
=> fix(ingest/mode): remove unused field

docs/managed-datahub/operator-guide/setting-up-remote-ingestion-executor.md
=> docs: fix link to executor helm chart

metadata-ingestion/setup.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/12416
=> fix(ingest): add missing dep for gcs

docs/actions/events/entity-change-event.md
=> docs(entity-change-events): add docs for action request events

.github/workflows/docker-unified.yml
=> fix(ci): run smoke tests on release

metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java, metadata-io/src/test/java/com/linkedin/metadata/search/utils/ESUtilsTest.java
=> fix(businessAttribute): fix business Attribute related entities

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/utils/DateUtilTest.java
This PR reverts backend changes that were messing up the MAU chart. This separate PR is the actual fix https://github.com/datahub-project/datahub/pull/12462
=> fix(ui): revert backend breaking changes to mau

.github/workflows/docker-unified.yml
This should help us identify long-running and flaky smoke tests.
=> ci(smoke): report smoke test results to codecov

metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java, smoke-test/tests/openapi/v3/entities.json
=> feat(openapi): point in time parameter (elasticsearch only)

docs/managed-datahub/release-notes/v_0_3_8.md
=> doc: update doc of first release

docs/modeling/extending-the-metadata-model.md
=> fix(docs) explain need to restore indices when adding @Searchable

metadata-ingestion/src/datahub/sdk/_shared.py, metadata-ingestion/src/datahub/sdk/container.py, metadata-ingestion/tests/test_helpers/sdk_v2_helpers.py, metadata-ingestion/tests/unit/sdk_v2/container_golden/test_container_basic_golden.json, metadata-ingestion/tests/unit/sdk_v2/container_golden/test_container_complex_golden.json, metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_dataset_complex_golden.json, metadata-ingestion/tests/unit/sdk_v2/dataset_golden/test_dataset_ingestion_golden.json, metadata-ingestion/tests/unit/sdk_v2/test_container.py, metadata-ingestion/tests/unit/sdk_v2/test_dataset.py
Also adds tests for the container entity.
=> fix(sdk): fix platform instance generation in the sdk

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
=> fix(looker): sort user mapping for consistency

metadata-ingestion/src/datahub/sql_parsing/split_statements.py, metadata-ingestion/tests/unit/sql_parsing/test_split_statements.py
=> feat(ingest/mssql): improve stored procedure splitting

.github/workflows/pr-labeler.yml
=> feat(gh-workflows) adding jayacryl to pr-labeler

datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
=> fix(web) ingestion page resets when filter updated

docs/managed-datahub/release-notes/v_0_3_8.md
=> doc: add note for subscription

metadata-ingestion/src/datahub/ingestion/source/mode.py
=> fix(ingest/mode): tweak lineage warning message

README.md
add Wealthsimple in adoption list
=> docs: add Wealthsimple in adoption list

build.gradle, datahub-frontend/play.gradle
=> chore(bump): bump netty version

build.gradle
=> chore(bump): bump jsonsmart

metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl
=> fix(search): Add boost to chart title for consistency 

datahub-web-react/build.gradle, datahub-web-react/package.json
Adding the same changes as : https://github.com/acryldata/datahub-fork/pull/5134/files
=> feat(UI): Adding sourcemaps for cloudfare builds

metadata-ingestion-modules/dagster-plugin/setup.py, metadata-ingestion-modules/dagster-plugin/tests/unit/test_dagster.py
Changes required due to a breaking change https://github.com/dagster-io/dagster/pull/16025
=> fix(dagster): support dagster 1.10.0

metadata-service/iceberg-catalog/requirements.txt, metadata-service/iceberg-catalog/src/integrationTest/integration_test.py
=> tests(iceberg): integration test fixes

metadata-models/src/main/pegasus/com/linkedin/ingestion/DataHubIngestionSourceInfo.pdl
=> feat(ingestion) source info data model to use keyword searchables

datahub-web-react/src/app/shared/time/timeUtils.tsx, datahub-web-react/src/graphql/dataProcessInstance.graphql
=> fix: fix data process instance preview & add state on data process instance graphql

datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/builder/details/PrimaryButton.tsx, datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavBarMenuItem.tsx, datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavSidebar.tsx, datahub-web-react/src/app/homeV2/layout/navBarRedesign/types.ts, datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx, datahub-web-react/src/app/permissions/policy/usePolicy.ts, smoke-test/tests/cypress/cypress/e2e/domains/nested_domains.js, smoke-test/tests/cypress/cypress/e2e/ml/model.js, smoke-test/tests/cypress/cypress/e2e/settings/manage_policies.js, smoke-test/tests/cypress/cypress/e2e/settingsV2/v2_managing_groups.js, smoke-test/tests/cypress/cypress/e2e/siblings/siblings.js, smoke-test/tests/cypress/cypress/support/commands.js, smoke-test/tests/entity_versioning/test_versioning.py
=> fix(cypress): Improve smoke test flakiness

datahub-graphql-core/build.gradle, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/businessattribute/AddBusinessAttributeResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/businessattribute/BusinessAttributeAuthorizationUtils.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/businessattribute/RemoveBusinessAttributeResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/BusinessAttributeUtils.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/businessattribute/AddBusinessAttributeResolverTest.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/businessattribute/RemoveBusinessAttributeResolverTest.java, metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
This PR is intended to fix [issue](https://github.com/datahub-project/datahub/issues/12548)
=> fix(businessAttribute): add businessAttribute-dataset missing permission

docs/how/updating-datahub.md, metadata-service/factories/src/main/java/com/linkedin/gms/factory/plugins/SpringStandardPluginConfiguration.java
=> fix(spring): Correct SpringStandardPluginConfiguration for UserDeleteValidator

metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Uses an ExitStack and stack.pop_all() to ensure that initialized resources are always cleaned up, even when errors happen.
=> fix(ingest): ensure proper cleanup on pipeline init failure

metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceImplApplyUpsertTest.java
=> fix(npe): fix and test for npe

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
=> fix(ui): new users chart title fix

li-utils/src/main/java/com/linkedin/metadata/Constants.java, metadata-io/src/main/java/com/linkedin/metadata/aspect/validation/ExecutionRequestResultValidator.java, metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java, metadata-io/src/test/java/com/linkedin/metadata/aspect/validation/ExecutionRequestResultValidatorTest.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceOptimizationTest.java
Only consider a change in status an exception. If the status is the same, then only filter it without causing an exception.
=> fix(smoke-test): fix test_timeseries_rollback

metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLGMSSpringTest.java, metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLMAESpringTest.java, metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLSpringCommonTestConfiguration.java, metadata-service/configuration/src/main/resources/application.yaml
=> config(): disable edge filter

docs/lineage/sql_parsing.md, metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_indirect_references.json, metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
=> docs(ingest): add more details on SQL parser limitations

metadata-ingestion-modules/airflow-plugin/setup.py, metadata-ingestion-modules/dagster-plugin/setup.py, metadata-ingestion-modules/gx-plugin/setup.py, metadata-ingestion-modules/prefect-plugin/setup.py, metadata-ingestion/pyproject.toml, metadata-ingestion/setup.py, metadata-ingestion/tests/unit/api/source_helpers/test_incremental_lineage_helper.py, metadata-ingestion/tests/unit/api/source_helpers/test_source_helpers.py, metadata-ingestion/tests/unit/test_iceberg.py, metadata-service/iceberg-catalog/requirements.txt, smoke-test/requirements.txt
=> dev: upgrade ruff, remove 2 ruff ignore rules

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/GetGrantedPrivilegesResolver.java
=> feat(api): let admins use granted privileges for actors

docs/automations/ai-docs.md
=> docs: clarify limits on AI docs

metadata-ingestion/setup.py
Also add the avro extra on confluent schema registry
=> fix(ingest): bump avro dep

README.md, docs-website/docusaurus.config.js, docs-website/src/components/SlackUtm/index.js, docs-website/src/pages/slack/index.js, docs-website/src/theme/Navbar/communityCardDropdownContent.js, docs/slack.md, metadata-ingestion/examples/mce_files/bootstrap_mce.json
Also updates the badges in the README.
=> docs: update slack link

.github/workflows/python-build-pages.yml
=> fix(build): support datahub-wheels from forked PRs

docs-website/src/theme/Layout/index.js
=> docs: add scarf integration

metadata-ingestion/src/datahub/cli/iceberg_cli.py
=> fix(iceberg-cli): add missing filter for iceberg dataplatform

docs/how/restore-indices.md
=> docs(restore-indices): added best practices

metadata-ingestion/pyproject.toml, metadata-ingestion/src/datahub/cli/docker_cli.py, metadata-ingestion/src/datahub/cli/lite_cli.py, metadata-ingestion/src/datahub/cli/specific/dataproduct_cli.py, metadata-ingestion/src/datahub/configuration/kafka.py, metadata-ingestion/src/datahub/ingestion/fs/s3_fs.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/graph/entity_versioning.py, metadata-ingestion/src/datahub/ingestion/source/cassandra/cassandra_api.py, metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_api.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_aspects.py, metadata-ingestion/src/datahub/ingestion/source/gc/execution_request_cleanup.py, metadata-ingestion/src/datahub/ingestion/source/kafka/kafka.py, metadata-ingestion/src/datahub/ingestion/source/looker/looker_file_loader.py, metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py, metadata-ingestion/src/datahub/ingestion/source/mode.py, metadata-ingestion/src/datahub/ingestion/source/pulsar.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py, metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py, metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py, metadata-ingestion/src/datahub/lite/duckdb_lite.py, metadata-ingestion/src/datahub/lite/lite_local.py, metadata-ingestion/src/datahub/lite/lite_util.py, metadata-ingestion/src/datahub/utilities/memory_footprint.py, metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
=> dev: enable ruff rule

metadata-ingestion/docs/sources/metabase/metabase.yml, metadata-ingestion/src/datahub/ingestion/source/metabase.py, metadata-ingestion/tests/unit/test_metabase_source.py
- [Feature request details](https://feature-requests.datahubproject.io/p/support-metabase-api-key-authentication-for-metadata-ingestion)
- No such change
=> feat: API key support in Metabase source

metadata-service/iceberg-catalog/build.gradle, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouse.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubRestCatalog.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/IcebergBatch.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/TableOrViewOpsDelegate.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/Utils.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouseTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/DataHubRestCatalogTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/IcbergBatchTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/TableOpsDelegateTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/UtilsTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/ViewOpsDelegateTest.java
=> feat(iceberg): improve concurrency control and resilience

docs/api/tutorials/owners.md
=> docs(users+groups): show that you can set title via users YAML

datahub-web-react/src/app/searchV2/SearchBar.tsx, datahub-web-react/src/app/searchV2/SearchHeader.tsx
=> feat(UI): make searchbar centered and wider

metadata-ingestion/src/datahub/ingestion/source/preset.py, metadata-ingestion/src/datahub/ingestion/source/superset.py, metadata-ingestion/tests/unit/test_preset_source.py, metadata-ingestion/tests/unit/test_superset_source.py
Remaking this pull request from [here](https://github.com/datahub-project/datahub/pull/12737). The rebase was getting unmanageable and I found it easier/less confusing to make a new PR.
=> feat(ingest): allowdenypattern for dashboard, chart, dataset in superset

metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py, metadata-ingestion/src/datahub/ingestion/source/sql/mssql/job_models.py, metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py, metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json, metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json, metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json, metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
=> feat(mssql): adds subtypes aspect for dataflow and datajobs

metadata-models/src/main/resources/entity-registry.yml
=> Support container in ML Model Group, Model and Deployment 

metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_common.py
Experimental setup for the `RestCatalog` type, once it is battle-proven it is to be proposed to `pyiceberg` repo instead.
=> feat(ingest/iceberg): Introduce network problems resiliency for Iceberg source

build.gradle
=> chore(postgres): bump version

docs/managed-datahub/release-notes/v_0_3_8.md
=> feat(docs): Release for DataHub Cloud 0.3.8.2

metadata-ingestion/developing.md
=> docs(ingest): update metadata-ingestion dev guide

metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceImplTest.java
* ensure key aspects are created when a timeseries aspect is encountered when using async mode
=> fix(openapi): fix openapi timeseries async ingestion

metadata-ingestion/src/datahub/ingestion/source/mode.py
=> docs(ingest/mode): update mode workspace docs

docs/automations/ai-docs.md
=> feat(docs) add perms req to ai docs

.github/workflows/pr-labeler.yml
=> fix(workflows): Update pr-labeler

metadata-ingestion/pyproject.toml, metadata-ingestion/src/datahub/configuration/common.py, metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/reporting/datahub_ingestion_run_summary_provider.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/src/datahub/ingestion/source/data_lake_common/path_spec.py, metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py, metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_tests.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_api.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_aspects.py, metadata-ingestion/src/datahub/ingestion/source/kafka_connect/common.py, metadata-ingestion/src/datahub/ingestion/source/sql/athena.py, metadata-ingestion/src/datahub/ingestion/source/sql/hive.py, metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py, metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py, metadata-ingestion/src/datahub/ingestion/source/superset.py, metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py, metadata-ingestion/src/datahub/lite/duckdb_lite.py, metadata-ingestion/src/datahub/sdk/dataset.py, metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py, metadata-ingestion/tests/performance/bigquery/bigquery_events.py
=> chore(ruff): enable some ignored rules

metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py, metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py, metadata-ingestion/src/datahub/ingestion/source/redshift/profile.py, metadata-ingestion/src/datahub/ingestion/source/redshift/query.py, metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py, metadata-ingestion/src/datahub/ingestion/source/redshift/redshift_schema.py, metadata-ingestion/tests/unit/redshift/test_redshift_datashares.py, metadata-ingestion/tests/unit/redshift/test_redshift_lineage.py
=> feat(ingest/redshift): lineage for external schema created from redshift

metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/tests/unit/sdk/test_rest_emitter.py, smoke-test/tests/timeline/timeline_test.py, smoke-test/tests/utils.py
=> feat(openapi-ingestion): implement openapi ingestion

datahub-web-react/src/app/entityV2/domain/DataProductsTab/DataProductResult.tsx
Same changes as:
https://github.com/acryldata/datahub-fork/pull/5261
=> fix(UI): Multiple data product delete modals

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchUtils.java
=> fix(graphql/search): Remove schema field and data process instance from default search types

docs/managed-datahub/operator-guide/setting-up-remote-ingestion-executor.md
=> docs: clear remote executor docs

datahub-frontend/app/security/AuthenticationManager.java, datahub-frontend/app/security/DataHubUserPrincipal.java, datahub-frontend/app/security/PropertyFileLoginModule.java, datahub-frontend/conf/jaas.conf, datahub-frontend/run/jaas.conf, datahub-frontend/test/security/AuthenticationManagerTest.java, datahub-frontend/test/security/DataHubUserPrincipalTest.java, datahub-frontend/test/security/PropertyFileLoginModuleTest.java
=> fix(jaas): fix jaas login

metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceInput.pdl, metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceOutput.pdl
=> feat(models): Add edges fields to data process instance relationship aspects

metadata-ingestion/src/datahub/ingestion/source/mlflow.py, metadata-ingestion/tests/integration/mlflow/mlflow_mcps_golden.json
=> feat(ingest/mlflow): update dpi to use edge for lineage

docs-website/docusaurus.config.js
=> docs(website) update docusaurus config

metadata-io/build.gradle, metadata-io/src/main/java/com/linkedin/metadata/dao/throttle/APIThrottle.java, metadata-io/src/test/java/com/linkedin/metadata/dao/throttle/APIThrottleTest.java, metadata-operation-context/build.gradle, metadata-operation-context/src/main/java/io/datahubproject/metadata/context/RequestContext.java, metadata-operation-context/src/test/java/io/datahubproject/metadata/context/RequestContextTest.java
=> feat(system-metrics): track api usage by user, client, api

.github/scripts/docker_helpers.sh
=> fix(python-version): Fix with dash docker_helpers.sh

docs-website/sidebars.js, docs/managed-datahub/release-notes/v_0_3_9.md
=> docs(cloud): DataHub Cloud v0.3.9 release notes

build.gradle, datahub-frontend/play.gradle, datahub-upgrade/build.gradle, docker/datahub-frontend/Dockerfile, docker/datahub-gms/Dockerfile, docker/datahub-mae-consumer/Dockerfile, docker/datahub-mce-consumer/Dockerfile, docker/datahub-upgrade/Dockerfile, docker/datahub-upgrade/start.sh, docs/advanced/monitoring.md, metadata-jobs/mae-consumer-job/build.gradle, metadata-jobs/mce-consumer-job/build.gradle, metadata-service/war/build.gradle
* update datahub-upgrade docker container to support open-telemetry as well
=> fix(open-telemetry): include missing dependency

metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceInput.pdl, metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceOutput.pdl
=> feat(models): Support DPI in edges fields of DPI relationship aspects

metadata-ingestion/setup.py
Also removes a couple deps that aren't actually required.
=> fix(ingest): fix superset declared deps

datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavBarHeader.tsx
Fixes some broken CSS for the new nav bar header.
=> fix(ui) Fix styling of new nav bar header in safai

.github/workflows/react-cloudflare-pages.yml, datahub-web-react/functions/api/v2/graphql.js, datahub-web-react/functions/authenticate.js, datahub-web-react/functions/cloudflare_proxy.js, datahub-web-react/functions/logIn.js, datahub-web-react/functions/track.js
Changes:
- Publishing OSS frontend builds on Cloudflare pages, under a new project datahub-project-web-react
- Proxying the API calls to Backend API set in Cloudflare Variable
Todo:
- Change Build Settings in cloudflare project
=> ci(ui): enable frontend previews

datahub-web-react/src/app/analytics/plugin/mixpanel.ts
Motivation is in a comment in the PR itself.
=> fix(ui): improve mixpanel analytics support

metadata-events/mxe-schemas/build.gradle
=> fix(build): use sync instead of copy so excess files are deleted

datahub-web-react/src/app/entity/dataset/profile/schema/components/StructuredPropValues.tsx, datahub-web-react/src/app/entityV2/dataset/profile/schema/components/StructuredPropValues.tsx
Fixing null pointer references in versions
=> fix(ui): versions null reference issues

metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_datahub_source_mapping.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_entities.py, metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_source.py, metadata-ingestion/tests/integration/dremio/dremio_mces_golden.json, metadata-ingestion/tests/integration/dremio/dremio_platform_instance_mces_golden.json, metadata-ingestion/tests/integration/dremio/dremio_platform_instance_to_file.yml, metadata-ingestion/tests/integration/dremio/dremio_schema_filter_to_file.yml, metadata-ingestion/tests/integration/dremio/dremio_to_file.yml, metadata-ingestion/tests/unit/dremio/test_dremio_source_map.py
=> fix(ingest/dremio): simplify and fix build source map

.github/scripts/docker_helpers.sh
Specifically, fixes some bugs in tag -> version conversion.
=> fix(ci): update docker helpers script

metadata-ingestion/src/datahub/sdk/dataset.py, metadata-ingestion/src/datahub/sdk/entity.py, metadata-ingestion/src/datahub/sdk/entity_client.py, metadata-ingestion/src/datahub/sdk/main_client.py, metadata-ingestion/src/datahub/sdk/search_filters.py
=> docs(sdk): add docstrings for some sdk classes

metadata-service/configuration/src/main/resources/application.yaml
This has caused confusion a few times.
=> docs(view authorization): document view authorization in application.yaml

metadata-ingestion/examples/library/dataset_add_column_documentation.py, metadata-ingestion/examples/library/dataset_add_column_tag.py, metadata-ingestion/examples/library/dataset_add_column_term.py, metadata-ingestion/examples/library/dataset_add_documentation.py, metadata-ingestion/examples/library/dataset_add_owner.py, metadata-ingestion/examples/library/dataset_add_tag.py, metadata-ingestion/examples/library/dataset_add_tag_patch.py, metadata-ingestion/examples/library/dataset_add_term.py, metadata-ingestion/examples/library/dataset_query_deprecation.py, metadata-ingestion/examples/library/dataset_query_description.py, metadata-ingestion/examples/library/dataset_query_description_on_columns.py, metadata-ingestion/examples/library/dataset_query_domain.py, metadata-ingestion/examples/library/dataset_query_owners.py, metadata-ingestion/examples/library/dataset_query_tags.py, metadata-ingestion/examples/library/dataset_query_terms.py, metadata-ingestion/examples/library/dataset_schema.py, metadata-ingestion/examples/library/dataset_set_tag.py, metadata-ingestion/examples/library/dataset_set_term.py
First round of example script improvements using the SDK v2. There will be more updates as we build out additional capabilities in the new SDK.
=> docs(sdk): update some examples with the new SDK

metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py, metadata-ingestion/tests/unit/test_schema_util.py
proposed solution for https://github.com/datahub-project/datahub/issues/12926
=> Fix(ingestion): fix jsonProps not being ingested for optional fields

metadata-ingestion/src/datahub/ingestion/source/vertexai/vertexai.py
=> fix(metadata-ingestion) fix connector test error for Vertex AI 

datahub-web-react/vite.config.ts
Adding meticulous script to record sessions
=> feat(ui): enabling meticulous recording

datahub-web-react/.eslintrc.js, datahub-web-react/package.json, datahub-web-react/yarn.lock
=> feat(web) require trailing commas

datahub-web-react/src/app/entity/ownership/OwnershipList.tsx, datahub-web-react/src/app/entity/ownership/table/ActionsColumn.tsx, datahub-web-react/src/app/entityV2/ownership/OwnershipList.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/builder/details/PrimaryButton.tsx, datahub-web-react/src/app/identity/ManageIdentities.tsx, datahub-web-react/src/app/settings/SettingsPage.tsx, datahub-web-react/src/app/settings/posts/PostItemMenu.tsx, datahub-web-react/src/app/settingsV2/settingsPaths.tsx, smoke-test/tests/cypress/cypress/e2e/glossaryV2/v2_glossaryTerm.js, smoke-test/tests/cypress/cypress/e2e/mutations/managing_secrets.js, smoke-test/tests/cypress/cypress/e2e/ownership/manage_ownership.js, smoke-test/tests/cypress/cypress/e2e/ownershipV2/v2_manage_ownership.js, smoke-test/tests/cypress/cypress/e2e/settings/homePagePost.js, smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js, smoke-test/tests/cypress/cypress/e2e/settingsV2/v2_managing_groups.js, smoke-test/tests/cypress/cypress/support/commands.js
We have some flaky cypress tests and this hopefully takes care of one of them.
=> fix(cypress) Fix flaky managing_secrets cypress test

metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceInput.pdl, metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceOutput.pdl, smoke-test/tests/cypress/cypress/e2e/ownershipV2/v2_manage_ownership.js
Aligning files across repositories!
=> fix(): Aligning tests and data process instance models

metadata-ingestion/src/datahub/ingestion/source/vertexai/vertexai.py, metadata-ingestion/tests/integration/vertexai/vertexai_mcps_golden.json, metadata-ingestion/tests/unit/test_vertexai_source.py
=> fix(ingestion) Added externalURL of model group for Vertex AI 

metadata-ingestion/src/datahub/ingestion/source/mlflow.py
adding basic auth config setting based on this MLflow guide : https://mlflow.org/docs/latest/auth/index.html#using-environment-variables
=> feat(ingest/mlflow): add mlflow auth config

docs/lineage/airflow.md, metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py, metadata-ingestion-modules/airflow-plugin/tests/integration/dags/custom_operator_sql_parsing.py, metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_custom_operator_sql_parsing.json, metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_custom_operator_sql_parsing_no_dag_listener.json, metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
=> chore(ingestion/airflow): Example custom operator with sql parsing

metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py, metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
=> fix(ingest/redshift): resolve ingestion errors

metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
=> fix(ingest): fix logging typo

metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
This PR fixes a KeyError which occurs on line 491 in powerbi_api.py.
The other changes are only for readability or to make it consistent (although the .get()s are a little bit "hard to read" when used in an if statement, that's the shortest solution to handle the None case and the KeyError case at the same time...:/)
=> fix(powerbi): fix KeyError when ingesting apps from Power BI

datahub-web-react/package.json, datahub-web-react/yarn.lock
=> fix(web) styltistic lint downgraded to support legacy lint definition path

metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
=> fix(ingest/redshift): respect skip external table config

metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py, metadata-ingestion/tests/test_helpers/mce_helpers.py, metadata-ingestion/tests/unit/test_generic_aspect_transformer.py, metadata-ingestion/tests/unit/test_transform_dataset.py, metadata-ingestion/tests/unit/test_usage_common.py
Removes some now unused utilities for usage generation + cleans up some transformer test code.
=> chore(ingest): remove calls to deprecated methods

datahub-web-react/src/app/lineageV2/useSearchAcrossLineage.ts
=> fix(ui/lineageV2): Fix bug with not getting all lineage nodes when hiding transformations

metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java
=> refactor(): use static yaml mapper es search service

metadata-ingestion/src/datahub/ingestion/source/sigma/config.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
=> feat(ingest/sigma): add reporting on filtered workspaces

metadata-ingestion/src/datahub/ingestion/api/source.py, metadata-ingestion/src/datahub/ingestion/api/source_helpers.py, metadata-ingestion/src/datahub/ingestion/source/cassandra/cassandra.py
=> feat(ingest): allow sources to produce sdk entities

metadata-ingestion/src/datahub/utilities/threaded_iterator_executor.py
=> feat(ingest): propagate backpressure in ThreadedIteratorExecutor

metadata-ingestion/docs/sources/snowflake/snowflake_pre.md
We've gotten a few tickets in the past week where customers were not formatting their keys correctly. Hopefully this clarifies things.
=> docs(ingest): clarify snowflake key language

metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
Probably fixes a regression from https://github.com/datahub-project/datahub/pull/9853
=> fix(ingest/trino): always use table properties fallback

.github/workflows/docker-unified.yml, build.gradle, datahub-frontend/build.gradle, datahub-graphql-core/build.gradle, datahub-upgrade/build.gradle, datahub-web-react/.gitignore, datahub-web-react/build.gradle, docker/build.gradle, docker/datahub-frontend/Dockerfile, docker/datahub-ingestion-base/build.gradle, docker/datahub-ingestion/build.gradle, docker/elasticsearch-setup/build.gradle, docker/kafka-setup/build.gradle, docker/mysql-setup/build.gradle, docker/postgres-setup/build.gradle, docker/profiles/docker-compose.frontend.yml, docker/profiles/docker-compose.gms.yml, gradle/docker/docker-utils.gradle, gradle/docker/docker.gradle, metadata-integration/java/spark-lineage-legacy/build.gradle, metadata-io/src/test/java/com/linkedin/metadata/graph/dgraph/DgraphGraphServiceTest.java, metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java, metadata-jobs/mae-consumer-job/build.gradle, metadata-jobs/mce-consumer-job/build.gradle, metadata-service/war/build.gradle
=> build: optimizations for incremental builds and faster CI 

metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
=> feat(ingestion/iceberg): source lastModified from table metadata field

metadata-service/auth-filter/src/main/java/com/datahub/auth/authentication/filter/AuthenticationFilter.java, metadata-service/auth-filter/src/test/java/com/datahub/auth/authentication/AuthenticationFilterTest.java, metadata-service/auth-impl/src/test/java/com/datahub/authentication/authenticator/DataHubTokenAuthenticatorTest.java
=> refactor(auth-filter): refactor exception and logging

docs/lineage/sql_parsing.md
=> docs(ingest): more specific CLL limitation language

metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
=> fix(ingest/sigma): include workspace names in report

docs/deploy/environment-vars.md
=> feat(docs): Add environment variables for OSS 1.0.0

docs/act-on-metadata/impact-analysis.md
There's a known issue around impact analysis regarding our lightning cache (see the PR for more details) - this updates our user guide to make that known for folks out there.
=> fix(docs) Update impact analysis docs to call out lightning cache bugs

build.gradle
=> chore(): bump parquet-avro

docs/managed-datahub/managed-datahub-overview.md
=> docs(oss-vs-cloud): update to re-align with current offering

datahub-web-react/src/app/entityV2/shared/components/styled/search/SearchSelect.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Incident/AcrylComponents/IncidentLinkedAssetsList.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Incident/IncidentList.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Incident/hooks.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Incident/utils.tsx, datahub-web-react/src/graphql/incident.graphql
- Hide search bar recs in search select
- Fix bug with linking assets without properties aspect to incidents
- correctly use entity registry to get display name for linked incident entities 
- remove space after column name in incidents
=> fix(ui): Adding incident changes from DataHub Cloud QA

docker/datahub-ingestion-base/Dockerfile, docker/datahub-ingestion-base/build.gradle, docker/datahub-ingestion/build.gradle
=> chore(): bump base ubuntu image 22.04 -> 24.04

docs/managed-datahub/release-notes/v_0_3_9.md
=> docs(cloud): DataHub Cloud v0.3.9.2 release notes

docker/datahub-ingestion-base/Dockerfile, docker/datahub-ingestion-base/build.gradle, docker/datahub-ingestion/build.gradle
=> fix(docker): also rename group to datahub

docs/managed-datahub/release-notes/v_0_3_10.md
=> Update docs discussing 0.3.10.1

datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/profile/actions/Actions.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/assertion/profile/actions/AssertionListItemActions.tsx
=> fix(ui): Styling fix for css regression

metadata-ingestion/docs/sources/hex/README.md
=> docs(hex): additional limitations

metadata-models/src/main/pegasus/com/linkedin/ml/metadata/MLModelDeploymentProperties.pdl
=> feat(models): Making ML deployment status searchable!

metadata-ingestion/src/datahub/ingestion/source/sql/stored_procedures/base.py, metadata-models/src/main/pegasus/com/linkedin/query/QueryStatement.pdl
=> fix(ingest/snowflake): fix error on stored procs in non-SQL languages

docs-website/docusaurus.config.js, docs-website/src/css/custom.css, docs-website/src/styles/global.scss
=> docs-website: add announcement for MCP. Some improvements in rendering

README.md
=> docs: link to mcp-server-datahub repo

docs-website/src/styles/global.scss
=> docs-website: fix search modal positioning and support smaller screens

datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Properties/ValuesColumn.tsx
https://github.com/user-attachments/assets/7816ed6a-f70a-4dec-ab4f-f4219a058515
=> fix(web) structured props to display right

metadata-ingestion/src/datahub/ingestion/source/sigma/config.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
=> refactor(ingest/sigma): add warning on empty workspaces

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
=> fix(ingest): quote db name in streams query

metadata-ingestion/docs/sources/sigma/sigma_pre.md, metadata-ingestion/src/datahub/ingestion/source/sigma/config.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma_api.py
=> refactor(ingest/sigma): make some error cases more clear

docs/advanced/api-tracing.md
=> docs(tracing): Add known limitations about openapi tracing

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java, metadata-io/src/test/java/com/linkedin/metadata/search/ElasticSearchServiceTest.java
=> fix(runId): make sure runid includes urn

docs-website/src/theme/Layout/index.js
=> docs: remove scarf

docs-website/src/pages/champions/index.js
=> docs(champions) Update DataHub Champions

metadata-ingestion/src/datahub/ingestion/source/sigma/config.py
=> fix(ingest/sigma): Fix missing key in workspace_counts

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/UpgradeCliApplication.java, metadata-service/configuration/src/main/resources/application.yaml, metadata-service/events-service/build.gradle, metadata-service/events-service/src/main/java/io/datahubproject/event/ExternalEventsService.java, metadata-service/events-service/src/main/java/io/datahubproject/event/exception/UnsupportedTopicException.java, metadata-service/events-service/src/main/java/io/datahubproject/event/kafka/KafkaConsumerPool.java, metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEvent.java, metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEvents.java, metadata-service/events-service/src/main/java/io/datahubproject/event/models/v1/ExternalEventsResponse.java, metadata-service/factories/build.gradle, metadata-service/factories/src/main/java/com/linkedin/gms/factory/event/ExternalEventsServiceFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/event/KafkaConsumerPoolFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/KafkaEventConsumerFactory.java, metadata-service/openapi-servlet/build.gradle, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/SpringWebConfig.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v1/event/ExternalEventsController.java, metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v1/event/ExternalEventsControllerTest.java, metadata-service/war/src/main/java/com/linkedin/gms/servlet/OpenAPIServletConfig.java, metadata-service/war/src/main/resources/boot/policies.json, metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java, settings.gradle, smoke-test/tests/openapi/v1/events.json
* returns platform events from kafka
=> feat(openapi): platform events endpoint

metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
=> fix(platform-events): add platform events privilege to platform list

datahub-web-react/src/alchemy-components/components/Button/utils.ts
- removed hardcoded gradient as it was overriding gray, green, etc 
- Just want gradient on violet
=> updated hard coded button gradient and added it only for violet

metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceOptimizationTest.java, metadata-io/src/test/resources/testng-cassandra.xml, metadata-io/src/test/resources/testng-neo4j.xml, metadata-io/src/test/resources/testng-other.xml, metadata-io/src/test/resources/testng-sql-opt.xml, metadata-io/src/test/resources/testng.xml
* isolate EbeanEntityServiceOptimizationTest (reduce flake)
* isolate neo4j (reduce peak memory consumption)
=> test(config): update metadata-io tests

.github/workflows/docker-unified.yml, docker/datahub-ingestion/build.gradle, gradle/versioning/versioning-global.gradle
=> fix(ci): fix image publish task, python-docker version

docs/api/openapi/openapi-usage-guide.md
=> docs(): Update generic patch openapi-usage-guide

metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/validation/ValidationApiUtils.java, metadata-io/metadata-io-api/src/test/java/com/linkedin/metadata/entity/validation/ValidationApiUtilsTest.java
=> fix(api-validation): correct mcp/urn entity mismatch

datahub-web-react/src/alchemy-components/components/SelectItemsPopover/SelectItemCheckboxGroup.tsx, datahub-web-react/src/alchemy-components/components/SelectItemsPopover/hooks.tsx
https://www.loom.com/share/ddecdc51eae24192b2af86b7915e927b
=> fix(): Hotfix assertions tag add / remove

.github/workflows/react-cloudflare-pages.yml, datahub-web-react/src/conf/utils.ts
Syntax fix to the react-clouflare-pages github action
Tested this with a sample deployment as well.
=> fix(ci): cloudflare github actions syntax

datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavBarHeader.tsx
Removed line height to match Johns change in Nav bar header
=> removed line height from oss nav header

datahub-web-react/src/app/entityV2/mlModel/MLModelEntity.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/EntitySidebarTabs.tsx
=> updated sidebar tabs removed margins updated icon in ML

metadata-ingestion/src/datahub/sdk/lineage_client.py, metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py, metadata-ingestion/tests/unit/sdk_v2/lineage_client_golden/test_lineage_copy_column_mapping_golden.json, metadata-ingestion/tests/unit/sdk_v2/lineage_client_golden/test_lineage_copy_fuzzy_golden.json, metadata-ingestion/tests/unit/sdk_v2/lineage_client_golden/test_lineage_copy_none_golden.json, metadata-ingestion/tests/unit/sdk_v2/lineage_client_golden/test_lineage_copy_strict_golden.json, metadata-ingestion/tests/unit/sdk_v2/test_lineage_client.py
=> [wip] feat(sdk): add auto lineage mapping to lineage client

metadata-ingestion/docs/sources/mlflow/mlflow_pre.md
=> docs(mlflow): add docs on version requirement for mlflow

docs/quick-ingestion-guides/snowflake/overview.md
=> docs(snowflake): remove procedures from list of assets not ingested

docs/how/updating-datahub.md
=> v1.0.0 release notes update

entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/GlobalTagsPatchBuilder.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/GlossaryTermsPatchBuilder.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/OwnershipPatchBuilder.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/StructuredPropertiesPatchBuilder.java, entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/builder/GlobalTagsPatchBuilderTest.java, entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/builder/GlossaryTermsPatchBuilderTest.java, entity-registry/src/test/java/com/linkedin/metadata/aspect/patch/builder/OwnershipPatchBuilderTest.java
=> fix(patch): add encoding to patch builders

datahub-web-react/src/app/entityV2/businessAttribute/BusinessAttributeEntity.tsx, datahub-web-react/src/app/entityV2/businessAttribute/preview/Preview.tsx, datahub-web-react/src/app/entityV2/businessAttribute/preview/_tests_/Preview.test.tsx, datahub-web-react/src/app/entityV2/shared/components/styled/MarkAsDeprecatedButton.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldDetails.tsx, datahub-web-react/src/app/preview/DataProcessInstanceInfo.tsx, datahub-web-react/src/app/settings/SettingsPage.tsx
Swaps business attribute to use v2 default preview card. Also fixes minor bug in v1 settings render.
Before:
After:
Before:
After:
=> fix(ui): Various minor fixes

metadata-ingestion/docs/sources/fivetran/fivetran_pre.md
Requires https://github.com/datahub-project/static-assets/pull/122 to be merged
=> docs(fivetran): Update docs on connection mapping to source systems

metadata-ingestion/src/datahub/emitter/mcp.py, metadata-ingestion/src/datahub/errors.py, metadata-ingestion/tests/unit/sdk/test_mcp_wrapper.py
=> feat(sdk): auto-fix bad entity type casing

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py, metadata-ingestion/tests/integration/snowflake/common.py
=> chore(ingest/snowflake): remove unused query code

metadata-ingestion/src/datahub/ingestion/source/sql/hive.py, metadata-ingestion/tests/integration/hive/hive_mces_all_db_golden.json, metadata-ingestion/tests/integration/hive/hive_mces_golden.json, metadata-ingestion/tests/integration/hive/hive_setup.sql
=> fix(ingest/hive): support multiline view definitions

metadata-ingestion/docs/sources/fivetran/fivetran_pre.md
=> docs: fix fivetran docs formatting

datahub-web-react/src/alchemy-components/components/AutoComplete/AutoComplete.stories.tsx, datahub-web-react/src/alchemy-components/components/AutoComplete/types.ts, datahub-web-react/src/alchemy-components/components/SearchBar/SearchBar.stories.tsx, datahub-web-react/src/alchemy-components/components/SearchBar/SearchBar.tsx, datahub-web-react/src/alchemy-components/components/SearchBar/components.ts, datahub-web-react/src/alchemy-components/components/SearchBar/types.ts, datahub-web-react/src/alchemy-components/components/Utils/ClickOutside/ClickOutside.tsx, datahub-web-react/src/alchemy-components/components/Utils/ClickOutside/components.tsx, datahub-web-react/src/app/searchV2/CommandK.tsx, datahub-web-react/src/app/searchV2/SearchBar.tsx, datahub-web-react/src/app/searchV2/SearchHeader.tsx, datahub-web-react/src/app/searchV2/SearchablePage.tsx, datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/__tests__/useUniqueEntitiesByPlatformUrn.test.tsx, datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/useUniqueEntitiesByPlatformUrn.ts, datahub-web-react/src/app/searchV2/filtersV2/defaults/DefaultFacetsUpdater/FacetsUpdater.tsx, datahub-web-react/src/app/searchV2/searchBarV2/SearchBarV2.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/AutocompleteDropdown.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/SearchBarInput.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/Skeleton.tsx, datahub-web-react/src/app/searchV2/searchBarV2/constants.ts, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useAutocompleteSuggestionsOptions.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useOptions.ts, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useRecentlySearchedQueriesOptions.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useRecentlyViewedEntitiesOptions.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSearchBarData.ts, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSelectOption.ts, datahub-web-react/src/app/searchV2/searchBarV2/types.ts, datahub-web-react/src/app/searchV2/useSearchBarData.ts
This PR includes:
- refactoring of `SearchBarV2` component
- moving state for `SearchBarV2` from `SearchablePage` to `SearchBarV2`
- reusing of `SearchBar` component from the components library
- adjusting styled for pre-navbar design
=> refactor(searchBarAutocomplete): refactoring of the new search bar

build.gradle
=> chore(pegasus): bump pegasus 29.65.7

.github/pull_request_template.md
=> chore: only show pull request checklist on PR creation

metadata-ingestion-modules/airflow-plugin/build.gradle, metadata-ingestion-modules/airflow-plugin/setup.py
~Previously the installDev command didn't include the extra pip requirements.~
Ensure installDev doesn't mess things up too much. Pins Airflow to <3
=> fix(ci): ensure extra airflow requirements are respected

datahub-web-react/.eslintrc.js, datahub-web-react/src/alchemy-components/theme/foundations/index.ts, datahub-web-react/src/alchemy-components/theme/index.ts, datahub-web-react/src/alchemy-components/theme/semantic-tokens.ts, datahub-web-react/src/alchemy-components/theme/utils.ts
=> fix(ui/storybook): Allow relative imports to fix storybook build

.github/workflows/airflow-plugin.yml, metadata-ingestion-modules/airflow-plugin/build.gradle
This should make airflow CI more reliable. It's a follow up on https://github.com/datahub-project/datahub/pull/13289
=> ci(airflow): separate airflow constraints from deps

datahub-web-react/src/app/context/UserContextProvider.tsx, datahub-web-react/src/app/searchV2/filtersV2/filters/EntityTypeFilter/hooks/useOptions.ts, datahub-web-react/src/app/searchV2/searchBarV2/SearchBarV2.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/AutocompletePlaceholder.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/KeyIcon.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/NoResultsFoundPlaceholder.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSearchBarData.ts, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSelectedView.ts
- add handling of selected view when no results
- fix case of subtype in the EntityTypeFilter
- fix vertical alignment of icons in KeyIcon component
=> fix(searchBarAutocomplete): UI fixes for the search bar

datahub-web-react/src/alchemy-components/components/Checkbox/Checkbox.tsx, datahub-web-react/src/alchemy-components/components/Checkbox/components.ts, datahub-web-react/src/alchemy-components/components/Checkbox/utils.ts
https://linear.app/acryl-data/issue/PRD-2169/improve-the-checkbox-component-in-the-library
=> improvement(component-library): make improvements in the checkbox component

datahub-web-react/src/graphql/fragments.graphql
For consistency with glossary term fetch above
=> fix(ui/graphql): Fetch glossary node details when fetching glossary node children

.github/workflows/pr-labeler.yml
=> ci: add anthonyburdi to team in pr-labeler.yml

datahub-web-react/.prettierrc.js, datahub-web-react/src/App.tsx, datahub-web-react/src/AppConfigProvider.tsx, datahub-web-react/src/alchemy-components/components/SelectItemsPopover/SelectItemPopover.tsx, datahub-web-react/src/app/entity/ermodelrelationships/ERModelRelationshipEntity.tsx, datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/CreateERModelRelationModal.tsx, datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/ERModelRelationPreview.tsx, datahub-web-react/src/app/entity/shared/tabs/Dataset/Relationship/RelationshipsTab.tsx, datahub-web-react/src/app/entity/shared/tabs/ERModelRelationship/ERModelRelationshipTab.tsx
=> fix(ui): Sort less files first

docker/build.gradle, docker/profiles/docker-compose.frontend.yml, docker/profiles/docker-compose.gms.yml, docker/profiles/docker-compose.prerequisites.yml, docs/developers.md, docs/docker/development.md
Adds new quickStartDebugMin target
Adds new debugReloadEnv task
Documentation updates on using debugReload and debugReloadEnv and updates on the general local dev workflow
=> build: support reload of some modules with env changes

datahub-web-react/src/app/lineageV2/useComputeGraph/filterNodes.ts
=> fix(ui/lineage): Fix bug when hiding transformations: edges via queries would disappear

metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/boot/MCLApplicationStartupListener.java, metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/boot/MCPApplicationStartupListener.java
This prevents GMS from starting up cleanly if using embedded MAE consumers.
=> fix(gms): class collision in mcp/mcl consumers

datahub-actions/pyproject.toml
=> fix(datahub-actions) bump h11 version to 0.16

docs-website/docusaurus.config.js
Updating GTM & GA ID to track docs-site metrics under datahub.com
=> docs: update GTM & GA ID

datahub-web-react/src/alchemy-components/components/Select/private/SelectActionButtons.tsx
=> fix(ui/select): replace clear icon and decrease size of it

metadata-service/auth-impl/src/main/resources/graphiql/index.html
=> feat(graphiql): upgrade graphiql interface

metadata-ingestion/tests/integration/dremio/dremio_mces_golden.json, metadata-ingestion/tests/integration/dremio/dremio_platform_instance_mces_golden.json
Seems like the newest Dremio version changed the default description of some stuff, causing tests to break.
=> fix(ingest): update dremio golden files

.github/workflows/python-build-pages.yml, datahub-actions/build.gradle, datahub-actions/setup.py, datahub-actions/src/datahub_actions/pipeline/pipeline_config.py, datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py, datahub-actions/src/datahub_actions/plugin/action/hello_world/hello_world.py, datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py, datahub-actions/src/datahub_actions/plugin/action/propagation/docs/propagation_action.py, datahub-actions/src/datahub_actions/plugin/action/stats_util.py, datahub-actions/src/datahub_actions/plugin/action/tag/tag_propagation_action.py, datahub-actions/src/datahub_actions/plugin/action/term/term_propagation_action.py, datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_event_source.py, datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_events_consumer_offsets_store.py, datahub-actions/tests/unit/action/test_action_registry.py, metadata-ingestion/setup.py
Upgrades datahub-actions to support pydantic v2 and use it in tests. Adds snowflake-slim and bigquery-slim extras to acryl-datahub in order to make this work.
=> feat(actions): support pydantic v2

datahub-web-react/src/alchemy-components/components/DatePicker/variants/dateSwitcher/components.tsx, datahub-web-react/src/alchemy-components/components/Loader/Loader.tsx, datahub-web-react/src/alchemy-components/components/Loader/components.tsx, datahub-web-react/src/alchemy-components/components/Loader/types.ts, datahub-web-react/src/alchemy-components/components/Select/Nested/NestedSelect.tsx, datahub-web-react/src/alchemy-components/components/Select/components.ts, datahub-web-react/src/alchemy-components/components/Select/utils.ts, datahub-web-react/src/app/analytics/event.ts, datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx, datahub-web-react/src/app/entityV2/schemaField/SchemaFieldEntity.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/__tests__/utils.test.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/utils.tsx, datahub-web-react/src/app/entityV2/view/select/ViewSelectContent.tsx, datahub-web-react/src/app/searchV2/filters/value/ValueMenu.tsx, datahub-web-react/src/app/searchV2/filtersV2/context/useAppliedFilters.ts, datahub-web-react/src/app/searchV2/searchBarV2/components/Filters.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/NoResultsFoundPlaceholder.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/SearchBarInput.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useAutocompleteSuggestionsOptions.tsx, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useOptions.ts, datahub-web-react/src/app/searchV2/searchBarV2/hooks/useSearchBarData.ts, datahub-web-react/src/graphql/search.graphql, metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
This PR fixes a few bugs discovered while QA'ing the new search bar experience.
1. Fixes issues with creating a view where selected values were not being saved after selecting, creating incorrect views.
2. Removes unnecessary tooltip in views that was reducing the clickable area to create a view to a small button
3. Support schema fields properly in this search bar experience by rendering the correct field path name and link to dataset profile
4. Fixes showing the "no data" message when we're in the 300ms between the debounce and `loading` is true by doing equality checks properly
5. Add some padding to the loading
6. Fix the sizing of the actions menu in the entity type menu
=> fix(ui) Fix a few bugs around new search bar experience

docs/managed-datahub/operator-guide/setting-up-remote-ingestion-executor.md
Resolving typo in RE K8s snippet
=> docs(remote executor) Fix typo in k8s snippets

metadata-ingestion/src/datahub/utilities/server_config_util.py, metadata-ingestion/tests/unit/utilities/test_server_config_util.py, metadata-service/configuration/src/main/resources/application.yaml
* change oss to core
* remove version suffix as descriminator
=> fix(ingestion): fix cloud vs core logic

metadata-ingestion/docs/sources/dynamodb/dynamodb_pre.md
=> docs(dynamodb): add privileges for dynamodb

metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessor.java, metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/config/MetadataChangeProposalProcessorCondition.java, metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/config/batch/BatchMetadataChangeProposalProcessorCondition.java, metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java, metadata-service/configuration/src/main/java/com/linkedin/metadata/config/MetadataChangeProposalConfig.java, metadata-service/configuration/src/main/resources/application.yaml
* Prevent SQL statements from exceeding database limits
=> fix(mce-consumer): prevent too large SQL statements

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
This should set us up to support pydantic v2 more broadly. Will be doing that in a future PR though.
=> fix(ingest): move to acryl-great-expectations

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_connection.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
=> chore(ingest/snowflake): clean up unused params in Snowflake connections

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/graph/links.py, metadata-ingestion/tests/unit/sdk/test_links.py
Also fixes a dep issue with the Fivetran source.
=> feat(ingest): add urn -> url helpers

datahub-actions/build.gradle, datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_events_consumer_offsets_store.py, docker/build.gradle, docs/advanced/api-tracing.md, docs/how/updating-datahub.md, metadata-ingestion/src/datahub/emitter/request_helper.py, metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/src/datahub/utilities/server_config_util.py, metadata-ingestion/tests/test_helpers/graph_helpers.py, metadata-ingestion/tests/unit/api/test_pipeline.py, metadata-ingestion/tests/unit/datahub/emitter/test_request_helper.py, metadata-ingestion/tests/unit/sdk/test_rest_emitter.py, metadata-ingestion/tests/unit/test_rest_sink.py, metadata-ingestion/tests/unit/utilities/test_server_config_util.py, smoke-test/conftest.py, smoke-test/tests/actions/doc_propagation/test_propagation.py, smoke-test/tests/cli/user_groups_cmd/test_user_cmd.py, smoke-test/tests/restli/restli_test.py, smoke-test/tests/restli/test_restli_batch_ingestion.py
Created EmitMode to control write guarantees:
* SYNC_WAIT: Fully synchronous processing that updates both primary storage (SQL) and search storage (Elasticsearch) before returning. Provides the strongest consistency guarantee but with the highest cost. Best for critical operations where immediate searchability and consistent reads are required.
* SYNC_PRIMARY: Synchronously updates the primary storage (SQL) but asynchronously updates search storage (Elasticsearch). Provides a balance between consistency and performance. Suitable for updates that need to be immediately reflected in direct entity retrievals but where search index consistency can be slightly delayed.
* ASYNC: Queues the metadata change for asynchronous processing and returns immediately. The client continues execution …
=> feat(ingestion): refactor api-tracing EmitMode

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/sql_parsing/_sqlglot_patch.py, metadata-ingestion/tests/unit/sql_parsing/goldens/test_postgres_update_subselect.json, metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_default_normalization.json
=> chore(ingest): bump sqlglot dep

datahub-graphql-core/src/main/resources/tests.graphql
=> fix(graphql): remove false deprecation note

smoke-test/tests/audit_events/audit_events_test.py
=> fix(smoke-test): fix flakiness of audit smoke test

datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
=> fix(searchBarAutocomplete): ui tweaks

docs/managed-datahub/release-notes/v_0_3_10.md
=> docs(release): Adding notes for v0.3.10.3 release

docker/build.gradle, gradle/docker/docker.gradle
=> fix(build): fix local quickstart builds

docs/managed-datahub/release-notes/v_0_3_10.md
=> docs: Adding color to 3.10 release notes

build.gradle
Update to parquet-avro 1.15.2 due RCE CVE-2025-46762
=> chore(avro): bump parquet-avro version

.github/workflows/docker-unified.yml
=> ci(): run smoke tests on release

datahub-web-react/src/app/sharedV2/StopPropagationWrapper.tsx
https://linear.app/acryl-data/issue/PRD-2200/bring-back-stop-propagation-wrapper-to-oss
=> improvement(ui): add wrapper component for stop propagation

metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_patch.py
=> chore(ingest): bump bounds on cooperative timeout test

docs/managed-datahub/release-notes/v_0_3_10.md
=> feat(docs): Add 0.3.10.4 hotfix release notes

docs-website/sphinx/requirements.txt, docs/actions/events/audit-events-search-guide.md
This is to make clear where this particular feature is available.
=> fix(docs): Add feature availability to audit API

metadata-ingestion/examples/library/lineage_datajob_to_datajob.py, metadata-ingestion/examples/library/lineage_datajob_to_dataset.py, metadata-ingestion/examples/library/lineage_dataset_copy.py, metadata-ingestion/examples/library/lineage_dataset_from_sql.py, metadata-ingestion/examples/library/lineage_dataset_transform.py, metadata-ingestion/examples/library/lineage_dataset_transform_with_query_text.py
=> feat(sdk): update lineage sample script to use client.lineage

docs-website/docusaurus.config.js
=> docs: remove 0.15.0 from archived list

docs/developers.md
=> fix(docs): Add requirement on yarn for documentation for local development

smoke-test/tests/audit_events/audit_events_test.py
=> fix(test): prevent audit test flakiness

metadata-ingestion/src/datahub/ingestion/graph/links.py
This ensures the links are valid even if the urn has a space or `/`.
=> fix(sdk): always url-encode entity links

metadata-ingestion/src/datahub/cli/delete_cli.py
=> fix(cli): warn more strongly about hard deletion

docs/managed-datahub/release-notes/v_0_3_11.md
=> docs(cloud): fix indent, remove note not relevant for cloud users

metadata-service/auth-impl/src/main/resources/graphiql/index.html, metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphiQLController.java
graphiql 4.0.3
react 18.3.1
fixes utf8 encoding
=> chore(): graphiql latest versions

metadata-ingestion/src/datahub/ingestion/source/mode.py
=> fix(ingest/mode): Additional 404 handling and caching update

li-utils/src/main/pegasus/com/linkedin/common/CorpGroupUrn.pdl, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
=> feat(platform): up limit of corpuser char length from 64 to 128

metadata-ingestion/setup.py, smoke-test/requirements.txt, smoke-test/tests/actions/doc_propagation/test_propagation.py, smoke-test/tests/lineage/test_lineage.py
Also upgrades smoke-tests to pydantic v2.
=> feat(ingest): support pydantic v2 in mysql source

.github/workflows/actions.yml, .github/workflows/airflow-plugin.yml, .github/workflows/build-and-test.yml, .github/workflows/dagster-plugin.yml, .github/workflows/docker-unified.yml, .github/workflows/gx-plugin.yml, .github/workflows/metadata-ingestion.yml, .github/workflows/metadata-io.yml, .github/workflows/prefect-plugin.yml
* fixes the case where we cannot always determine the branch from git checkout
=> update(ci): specify branch

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/query/QueryType.java, datahub-web-react/src/graphql/lineage.graphql
This was merged improperly when we brought V2 UI to OSS
=> fix(graphql,lineage): Fix CLL through queries

.github/workflows/build-and-test.yml
=> fix(ci): fix typo

metadata-ingestion/src/datahub/entrypoints.py
=> fix(cli): move to stderr instead of stdout

metadata-ingestion/docs/sources/looker/lookml_post.md
Making the language of what we support for liquid syntax clearer.
=> fix(docs): update support limits for liquid-python

docker/kafka-setup/Dockerfile
=> chore(): bump kafka-setup base image

metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecommendationSource.java
=> fix(): remove unused recursive code

docker/datahub-upgrade/README.md, docs/advanced/monitoring.md, docs/how/backup-datahub.md, docs/how/restore-indices.md
1. Discuss how to actually backup MySQL or AWS Rds
2. Discuss how to actually backup elastic / open search 
3. Discuss how to restore MySQL or AWS rds 
4. Discuss how to restore elastic / open search
=> fix(docs): Improve backup and restore doc

docs/how/updating-datahub.md
=> fix(docs): add known issue for server_config

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java, datahub-graphql-core/src/main/resources/app.graphql, datahub-web-react/src/appConfigContext.tsx, datahub-web-react/src/graphql/app.graphql, metadata-service/configuration/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java, metadata-service/configuration/src/main/resources/application.yaml
=> feat(ingestion): create feature flag for ingestion page redesign

metadata-ingestion/src/datahub/ingestion/source/apply/datahub_apply.py
=> fix(ingestion/datahubapply): fix typos in config descriptions

docs/dataproducts.md, docs/managed-datahub/observe/data-contract.md
fixing rendering error caused by this : https://github.com/datahub-project/datahub/pull/13220
=> docs: fix inline code format

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java, datahub-graphql-core/src/main/resources/app.graphql, datahub-web-react/src/app/lineageV2/LineageEntityNode/ExpandLineageButton.tsx, datahub-web-react/src/appConfigContext.tsx, datahub-web-react/src/graphql/app.graphql, metadata-service/configuration/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java, metadata-service/configuration/src/main/resources/application.yaml
=> feat(lineage): Add feature flag to hide expand more action

docs/dataproducts.md, docs/managed-datahub/observe/data-contract.md
=> ci(docs): Fix md prettier lint by ignoring inline blocks

datahub-web-react/src/alchemy-components/components/Pills/Pill.tsx, datahub-web-react/src/app/searchV2/filters/FilterOption.tsx, datahub-web-react/src/app/searchV2/filters/utils.tsx, datahub-web-react/src/graphql/search.graphql
=> fix(ui/filters): Improve platform instance filter

entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/AspectsBatch.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/hooks/OwnershipOwnerTypes.java
=> fix(hook): collect write mutation hook to ensure side effects

docs/managed-datahub/release-notes/v_0_3_11.md
=> docs(): Update v_0_3_11 Release notes

datahub-web-react/src/app/entityV2/glossaryNode/ChildrenTab.tsx, datahub-web-react/src/app/entityV2/glossaryNode/GlossaryNodeEntity.tsx, datahub-web-react/src/app/entityV2/glossaryNode/useGlossaryChildren.ts, datahub-web-react/src/app/glossaryV2/BusinessGlossaryPage.tsx, datahub-web-react/src/app/glossaryV2/EmptyGlossarySection.tsx, datahub-web-react/src/app/glossaryV2/GlossaryContentProvider.tsx
=> fix(web): glossary term create buttons inlined in content area

metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py, metadata-ingestion/tests/unit/test_mapping.py, metadata-ingestion/tests/unit/test_sql_types.py
Fix the urn validation in the ownership type check.
Add missing SQL types to Snowflake types.
=> fix(ingest/dbt): Fix urn validation in ownership type check.

metadata-models/src/main/resources/entity-registry.yml
This PR adds the ownership aspect to the ingestion source
=> feat(ingestionSource/ownership): add ownership aspect to ingestionSource

metadata-ingestion/src/datahub/api/entities/dataset/dataset.py, metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py, metadata-ingestion/tests/unit/cli/dataset/test_resources/golden_test_dataset_sync_mpcs.json, metadata-ingestion/tests/unit/structured_properties/test_structured_properties.py
=> fix(cli): strictly validate structured property values

datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearchResults.tsx
=> fix(ui): Fix pagination overflow on embedded list search results

docs-website/docusaurus.config.js
=> feat(docs-website): announcement banner features series b

datahub-web-react/src/alchemy-components/components/Select/components.ts, datahub-web-react/src/alchemy-components/components/Select/private/hooks/useSelectDropdown.ts, datahub-web-react/src/alchemy-components/components/Table/Table.tsx, datahub-web-react/src/app/entityV2/shared/EntitySearchInput/EntitySearchInputResultV2.tsx, datahub-web-react/src/app/searchV2/filters/SearchFiltersLoadingSection.tsx, datahub-web-react/src/app/searchV2/filters/useSearchFilterDropdown.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/NoResultsFoundPlaceholder.tsx, datahub-web-react/src/app/sharedV2/filters/Filter.tsx, datahub-web-react/src/app/sharedV2/filters/FilterSection.tsx
=> fix(ui): Changes to components

metadata-io/src/test/resources/testng-other.xml, metadata-io/src/test/resources/testng.xml, metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessor.java, metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java, metadata-service/configuration/build.gradle, metadata-service/configuration/src/main/java/com/linkedin/metadata/config/DataHubAppConfiguration.java, metadata-service/configuration/src/main/java/com/linkedin/metadata/config/MetadataChangeProposalConfig.java, metadata-service/configuration/src/test/java/com/linkedin/metadata/config/DataHubAppConfigurationTest.java, metadata-service/configuration/src/test/java/com/linkedin/metadata/config/DataHubTestApplication.java
=> fix(config): fix mcp batch configuration

docs/api/tutorials/custom-assertions.md
=> doc(assertion): change to millis in example

docs/managed-datahub/release-notes/v_0_3_11.md
=> feat(docs): Add docs for 0.3.11.1 Cloud Release

build.gradle, datahub-upgrade/build.gradle, docker/build.gradle, entity-registry/build.gradle, metadata-integration/java/acryl-spark-lineage/scripts/check_jar.sh, metadata-integration/java/datahub-client/build.gradle, metadata-integration/java/datahub-protobuf/build.gradle, metadata-integration/java/spark-lineage-legacy/build.gradle, metadata-models/build.gradle, metadata-service/configuration/build.gradle, metadata-service/openapi-servlet/models/build.gradle, metadata-service/plugin/build.gradle, metadata-service/schema-registry-api/build.gradle, metadata-service/servlet/build.gradle
* more consistent pinning of jackson version
=> config(gradle): pin jackson via bom

datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx, gradle/versioning/versioning.gradle
=> misc(): Bump CLI version to v1.1.0

.github/workflows/docker-unified.yml
=> ci(smoke-tests): run tests on push to release branches (#13629) (addendum)

.github/scripts/docker_helpers.sh
=> build: support tag computation from branch with slash in name

metadata-service/configuration/src/main/resources/application.yaml, metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java
=> config(): disable service name in header

docker/build.gradle, docker/profiles/README.md, docker/profiles/docker-compose.actions.yml, docker/profiles/docker-compose.gms.yml, docker/profiles/docker-compose.prerequisites.yml
=> feat(docker-compose): add localstack to compose profiles

.github/scripts/check_policies.py, metadata-service/war/src/main/resources/boot/policies.json
=> fix(policies): more assertions, add missing policy for editor role

datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/CompactMarkdownViewer.tsx
Bringing back changes to OSS from [here](https://github.com/acryldata/datahub-fork/commit/ed81cc051b0025149ee493065f12ce84ea1a3d57)
=> improvement(ui): bring compact markdown viewer changes to OSS

metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py, metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_virtual_connections.py
refactored to display the virtual connection as individual tables rather than a single table
=> refactored to display the virtual connection as individual tables

datahub-frontend/play.gradle, datahub-upgrade/build.gradle, metadata-integration/java/spark-lineage-legacy/spark-smoke-test/test-spark-lineage/build.gradle
=> chore(): bump beanutils version

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourcesResolver.java, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourceResolverTest.java, datahub-web-react/src/alchemy-components/components/Table/types.ts, datahub-web-react/src/alchemy-components/components/Table/utils.ts, datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx, datahub-web-react/src/app/ingestV2/source/IngestionSourceTable.tsx, datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx, datahub-web-react/src/app/ingestV2/source/__tests__/tests_utils.test.tsx, datahub-web-react/src/app/ingestV2/source/utils.ts
https://linear.app/acryl-data/issue/CH-336/ingestion-table-support-and-modify-sort-on-name-column
**Video:**
https://github.com/user-attachments/assets/031ae479-1c89-47f6-96dd-888818f96299
=> feat(ingestions): support backend sort and combine type and name sorts in ingestion table

datahub-web-react/src/app/permissions/policy/PolicyDetailsModal.tsx, datahub-web-react/src/app/permissions/policy/PolicyPrivilegeForm.tsx, datahub-web-react/src/app/permissions/policy/_tests_/PolicyDetailsModal.test.tsx, datahub-web-react/src/app/permissions/policy/_tests_/PolicyPrivilegeForm.test.tsx, docs/iceberg-catalog.md, metadata-auth/auth-api/src/main/java/com/datahub/authorization/EntityFieldType.java, metadata-service/auth-impl/src/main/java/com/datahub/authorization/DefaultEntitySpecResolver.java, metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/ContainerFieldResolverProvider.java, metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java, metadata-service/auth-impl/src/test/java/com/datahub/authorization/PolicyEngineTest.java, metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/ContainerFieldResolverProviderTest.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/DataHubIcebergWarehouse.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/rest/secure/AbstractIcebergController.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergNamespaceApiController.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergTableApiController.java, metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergViewApiController.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/open/PublicIcebergApiControllerTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/AbstractControllerTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergNamespaceApiControllerTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergTableApiControllerTest.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/rest/secure/IcebergViewApiControllerTest.java, metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
=> feat(iceberg): add namespace permissions

docs/managed-datahub/release-notes/v_0_3_11.md
=> docs(cloud): update remote executor version

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/GetLatestSuccessfulExecutionRequestResolver.java, datahub-graphql-core/src/main/resources/ingestion.graphql, datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/GetLatestSuccessfulExecutionRequestResolverTest.java, datahub-web-react/src/app/ingestV2/executions/ExecutionsTab.tsx, datahub-web-react/src/app/ingestV2/executions/components/ExecutionsTable.tsx, datahub-web-react/src/app/ingestV2/executions/components/columns/ActionsColumn.tsx, datahub-web-react/src/graphql/fragments.graphql, datahub-web-react/src/graphql/ingestion.graphql
This PR adds:
- the latest executed request to ingestion source
- the rollback button to the executions table
=> feat(ingestion): add rollback button

datahub-web-react/src/app/ingestV2/shared/components/filters/SourceFilter.tsx
=> fix(ingestion): fix size of the sources filter

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java, metadata-io/src/test/java/com/linkedin/metadata/search/indexbuilder/IndexBuilderTestBase.java
=> fix(build): restore deleted code that broke build

metadata-ingestion/src/datahub/api/entities/external/external_entities.py, metadata-ingestion/src/datahub/api/entities/external/external_tag.py, metadata-ingestion/src/datahub/api/entities/external/restricted_text.py, metadata-ingestion/src/datahub/api/entities/external/unity_catalog_external_entites.py, metadata-ingestion/src/datahub/ingestion/source/unity/config.py, metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py, metadata-ingestion/src/datahub/ingestion/source/unity/source.py, metadata-ingestion/src/datahub/ingestion/source/unity/tag_entities.py, metadata-ingestion/tests/unit/api/entities/external/test_external_entitites.py, metadata-ingestion/tests/unit/api/entities/external/test_restrictions.py
This pull request adds Unity Catalog tag extraction.
To support Tag extraction, it introduces new abstractions that handle external entities, tags, and text processing within the DataHub ingestion framework. The changes include the addition of a repository for managing platform resources, utilities for external tags, and a new `RestrictedText` type for handling sanitized and truncated strings.
* **`PlatformResourceRepository`**: Added a repository class for managing platform resources, with methods for searching, creating, retrieving, and deleting resources. It includes caching to optimize performance. (`metadata-ingestion/src/datahub/api/entities/external/external_entities.py`, [metadata-ingestion/src/datahub/api/entities/external/external_entities.pyR1-R239](diffhunk://#diff-8031a685a0dd …
=> feat(ingest/unity-catalog): Tag extraction

datahub-web-react/.storybook/preview.js, datahub-web-react/src/alchemy-components/components/Button/utils.ts
Storybook locally gives no compilation errors without this import statement
=> fix(build/storybook): Surface errors

metadata-ingestion/src/datahub/sdk/main_client.py
=> fix(sdk): Ignore mypy error for conditional ResolverClient import

.github/scripts/docker_helpers.sh, .github/workflows/docker-ingestion-smoke.yml, .github/workflows/docker-unified.yml, .github/workflows/publish-datahub-jars.yml
=> fix(ci): handle missing github ref

datahub-web-react/src/app/ingestV2/executions/components/ExecutionsTable.tsx, datahub-web-react/src/app/ingestV2/shared/components/filters/SourceFilter.tsx
=> fix(ingestion): rename name column and filter to sources on the executions tab

datahub-web-react/src/app/ingestV2/executions/components/columns/ExecutedByColumn.tsx, datahub-web-react/src/app/ingestV2/source/IngestionSourceTable.tsx, datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx, datahub-web-react/src/app/ingestV2/source/types.ts
=> fix(ingestion): show dash for null values in sources and execution tables

metadata-ingestion/src/datahub/sdk/main_client.py
=> feat(sdk): Add subscriptions client to main client OSS

metadata-ingestion/src/datahub/sdk/main_client.py
=> refactor(sdk): Use sdk instead of _sdk_extras

metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/graph/config.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/tests/unit/cli/test_config_utils.py, metadata-ingestion/tests/unit/sdk/test_rest_emitter.py
* preserve default cache behavior
* change parameter name to server_config_refresh_interval
=> feat(config): update configuration caching

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/ingestion/ExecutionRequestMapper.java, entity-registry/src/main/java/com/linkedin/metadata/aspect/EntityAspect.java, metadata-ingestion/src/datahub/ingestion/reporting/datahub_ingestion_run_summary_provider.py
=> feat(ingest,graphql): Support displaying actor of CLI ingestion

datahub-web-react/src/alchemy-components/components/Select/utils.ts, datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
Fix of Select's padding
Fix the alignment of refresh button on the ingestion tab
=> fix(ingestion): UI fixes

datahub-web-react/src/app/govern/structuredProperties/StructuredPropsTable.tsx, datahub-web-react/src/app/tags/TagsTableColumns.tsx
Manually tested locally it copied to clipboard
=> feat(ui): add copy urn tag and structured properties

docs/authorization/policies.md
Adding proposal privileges documentation
=> fix(doc): Update proposals documentation

entity-registry/src/main/java/com/linkedin/metadata/models/DataSchemaFactory.java
Root cause: https://github.com/datahub-project/datahub/pull/13298
=> fix(dataschema): fix for reflections upgrade

docs-website/sidebars.js, docs/automations/databricks-metadata-sync.md
This pull request introduces a new automation feature, Databricks Metadata Sync, to the documentation and updates the sidebar navigation to include it. The feature enables seamless metadata synchronization between DataHub and Databricks Unity Catalog, providing enhanced governance capabilities. Key changes include the addition of a new documentation page and an update to the sidebar configuration.
* Added a new documentation page `docs/automations/databricks-metadata-sync.md` detailing the Databricks Metadata Sync automation. This includes an overview, key capabilities, prerequisites, configuration guide, and troubleshooting steps.
* Updated `docs-website/sidebars.js` to include a new entry for "Databricks Metadata Sync" under the automations section.
* Added a new entry for "Databricks …
=> doc(unity-catalog): Add doc for Databricks metadata sync

docs-website/sidebars.js, docs/features/feature-guides/mcp.md
=> docs: add MCP server guide

metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
=> refactor(neo4j): parameterized neo4j Queries execution to escape special characters in urn

docs-website/sidebars.js, docs/api/datahub-apis.md, docs/managed-datahub/observe/assertions.md, docs/managed-datahub/observe/column-assertions.md, docs/managed-datahub/observe/custom-sql-assertions.md, docs/managed-datahub/observe/data-contract.md, docs/managed-datahub/observe/data-health-dashboard.md, docs/managed-datahub/observe/freshness-assertions.md, docs/managed-datahub/observe/schema-assertions.md, docs/managed-datahub/observe/smart-assertions.md, docs/managed-datahub/observe/volume-assertions.md
=> feat(docs): smart assertions and dataset health dashboard docs

metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_summary.py, metadata-ingestion/tests/unit/snowflake/test_snowflake_summary.py, metadata-ingestion/tests/unit/test_classification_mixin.py
Summary source was missing a few things. This PR fixes those and also adds tests to prevent the summary accidentally breaking in the future.
=> fix(snowflake summary): fixing snowflake summary source

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java, metadata-io/src/test/java/com/linkedin/metadata/search/indexbuilder/ESIndexBuilderTest.java, metadata-service/configuration/src/main/java/com/linkedin/metadata/timeseries/BatchWriteOperationsOptions.java
=> fix(reindex): fix cast exception during reindex

docs/managed-datahub/approval-workflows.md
Updated images : https://github.com/datahub-project/static-assets/pull/134
=> fix(docs): Update proposals docs

docs/features/feature-guides/compliance-forms/create-a-form.md
=> docs(Forms) Update Form Creation guide with notification details

metadata-ingestion/src/datahub/ingestion/source/kafka/kafka.py, metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
=> doc(mysql,kafka): fix support status

docs/ui-ingestion.md
Updates the managed ingestion docs to include screenshots of the updated page and highlight the new Run History tab.
=> feat(docs) Update managed ingestion docs with new UI

docs/iceberg-catalog.md
=> docs(iceberg): added notes on session expiry config, some minor updates

li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdl, metadata-service/restli-api/src/main/idl/com.linkedin.entity.aspects.restspec.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
Support PRD, TST, and SIT fabric types
=> feat(fabricType): add new supported fabric types

docs/managed-datahub/release-notes/v_0_3_12.md
=> docs(release): add MCP server note to release notes

metadata-ingestion/src/datahub/ingestion/source/usage/clickhouse_usage.py, metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
=> doc(ingest): mark for usage

datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py, metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/tests/unit/sdk/test_rest_emitter.py
Revert previous mcpw changes as it has unintended consequences, fix lower down at the emitter level.
=> fix(emitter): fix emitter handling of unicode characters

metadata-ingestion/src/datahub/ingestion/source/preset.py
=> docs(ingestion): preset - update source certification status

docs/managed-datahub/release-notes/v_0_3_12.md
=> fix(docs): add recommended versions for v0.3.12

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py, metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py, metadata-ingestion/tests/unit/snowflake/test_snowflake_source.py
=> feat(ingest/snowflake): add extra_info for snowflake

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java, metadata-io/src/test/java/com/linkedin/metadata/search/query/BrowseDAOTest.java, metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchRequestHandlerTest.java
=> fix(search): additional search size defaults

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java, datahub-graphql-core/src/main/resources/app.graphql, datahub-web-react/src/app/ProtectedRoutes.tsx, datahub-web-react/src/app/homepageV2/HomePage.tsx, datahub-web-react/src/appConfigContext.tsx, datahub-web-react/src/graphql/app.graphql, metadata-service/configuration/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java, metadata-service/configuration/src/main/resources/application.yaml
https://linear.app/acryl-data/issue/CH-493/create-new-feature-flag-and-render-empty-div
=> feat(homepage): create new feature flag for homepage redesign

datahub-web-react/src/alchemy-components/components/Avatar/Avatar.tsx, datahub-web-react/src/alchemy-components/components/Avatar/components.ts, datahub-web-react/src/alchemy-components/components/Avatar/types.ts, datahub-web-react/src/alchemy-components/components/Avatar/utils.ts, datahub-web-react/src/alchemy-components/components/AvatarStack/AvatarStack.tsx, datahub-web-react/src/alchemy-components/components/AvatarStack/AvatarStackWithHover.tsx, datahub-web-react/src/alchemy-components/components/AvatarStack/HoverSectionContent.tsx, datahub-web-react/src/alchemy-components/components/AvatarStack/types.ts, datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx
=> fix(ingestion): fix group avatar (changes from SaaS)

datahub-web-react/src/alchemy-components/components/SearchBar/SearchBar.stories.tsx, datahub-web-react/src/alchemy-components/components/SearchBar/SearchBar.tsx, datahub-web-react/src/alchemy-components/components/SearchBar/types.ts, datahub-web-react/src/app/searchV2/SearchablePage.tsx, datahub-web-react/src/app/searchV2/searchBarV2/SearchBarV2.tsx, datahub-web-react/src/app/searchV2/searchBarV2/components/SearchBarInput.tsx
=> fix(searchBarV2): do not clean filters on the search hit with empty filters

datahub-web-react/src/app/homepageV2/HomePage.tsx, datahub-web-react/src/app/homepageV2/HomePageContent.tsx, datahub-web-react/src/app/homepageV2/HomePageHeader.tsx, datahub-web-react/src/app/homepageV2/styledComponents.ts, datahub-web-react/src/app/searchV2/SearchablePage.tsx, datahub-web-react/src/images/homepage-vector.svg
https://linear.app/acryl-data/issue/CH-495/render-skeleton-of-home-page
=> feat(ui/homepage): render skeleton of the new homepage

docs/lineage/airflow.md
=> docs(airflow): document background operation

docs/managed-datahub/release-notes/v_0_3_12.md
=> docs: fix api-gateway version in release notes

docs/actions/concepts.md
=> chore: Fix typo

docs/managed-datahub/slack/saas-slack-app.md
=> docs(slack): add docs on slackbot permissions

docs/actions/events/audit-events-search-guide.md, metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceImplTest.java, metadata-service/configuration/src/main/resources/application.yaml, metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java, metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/event/DeletePolicyEvent.java, metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/event/UsageEventResult.java, smoke-test/tests/audit_events/audit_events_test.py
Adds in a default audit event for policy deletes
=> feat(auditEvents): add in top level delete policy event by default

datahub-web-react/src/alchemy-components/components/Select/utils.ts
Very minor update to lighten up color in selects on hover & active
=> update hover color in selects

metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
=> fix(ingest): mypy lint python 3.8

docs/api/tutorials/assertions.md
=> fix(docs): hide unsupported assertion API feature docs

docs/managed-datahub/release-notes/v_0_3_12.md
=> feat(docs): v0.3.12.2 release notes

docs/cli.md, metadata-ingestion/src/datahub/cli/check_cli.py, metadata-ingestion/src/datahub/ingestion/graph/client.py
=> feat(cli): add kafka helper, improve restore indices helper

datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearchEmbed.tsx
=> fix(ui): reset page in embedded components

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
=> docs(dbt): incremental-lineage

metadata-io/src/test/java/com/linkedin/metadata/CassandraTestUtils.java, metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraAspectMigrationsDaoTest.java, metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraEntityServiceTest.java, metadata-io/src/test/java/com/linkedin/metadata/timeline/cassandra/CassandraTimelineServiceTest.java
=> fix(ci): cassandra test stabilization

metadata-utils/build.gradle
=> fix(gradle): prevent metadata-utils from downgrading zookeeper

metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityregistry/ConfigEntityRegistryFactory.java, metadata-service/factories/src/test/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactoryTest.java, metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java, metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTimerCacheTest.java
=> misc(metrics): fix legacy metrics cache & tests

metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json, metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py, metadata-ingestion/src/datahub/ingestion/source/gcs/gcs_source.py, metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py, metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py, metadata-ingestion/src/datahub/ingestion/source/unity/source.py
=> feat(ingest): add subtype capability modifier

metadata-ingestion/src/datahub/cli/check_cli.py, metadata-ingestion/src/datahub/cli/cli_utils.py, metadata-ingestion/src/datahub/cli/delete_cli.py, metadata-ingestion/src/datahub/cli/docker_cli.py, metadata-ingestion/src/datahub/cli/exists_cli.py, metadata-ingestion/src/datahub/cli/get_cli.py, metadata-ingestion/src/datahub/cli/ingest_cli.py, metadata-ingestion/src/datahub/cli/put_cli.py, metadata-ingestion/src/datahub/cli/specific/assertions_cli.py, metadata-ingestion/src/datahub/cli/specific/datacontract_cli.py, metadata-ingestion/src/datahub/cli/specific/dataproduct_cli.py, metadata-ingestion/src/datahub/cli/specific/dataset_cli.py, metadata-ingestion/src/datahub/cli/specific/forms_cli.py, metadata-ingestion/src/datahub/cli/specific/group_cli.py, metadata-ingestion/src/datahub/cli/specific/structuredproperties_cli.py, metadata-ingestion/src/datahub/cli/specific/user_cli.py, metadata-ingestion/src/datahub/cli/state_cli.py, metadata-ingestion/src/datahub/cli/timeline_cli.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/src/datahub/upgrade/upgrade.py, metadata-ingestion/src/datahub/utilities/server_config_util.py
What has been changed
---
- The decorator of `check_upgrade` and `telemetry` were not consistently being applied. Added a method that applies it to every CLI command automatically. This fixes our CLI telemetry coverage as well notifying folks to upgrade CLI. Check `enable_auto_decorators` in `cli_utils` and `entrypoints.py` to see how wiring is done.
- There were versions hard-coded for server and CLI, removed them
In managed ingestion we get a warning if using a old CLI older to what is configured as default on server.
Shows up like this in beginning of ingestion
Shows up in report like this
Some folks use older CLI versions and face issues. The easiest solve in many cases is to ask them to upgrade their CLI version. It can get a manual process so adding this warning in the code.
This …
=> feat(ingest): warn of older cli versions automatically

datahub-web-react/src/alchemy-components/README.mdx
=> fix(alchemy): fix typo

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py, metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py, metadata-ingestion/tests/unit/test_teradata_integration.py, metadata-ingestion/tests/unit/test_teradata_performance.py, metadata-ingestion/tests/unit/test_teradata_source.py
🚀 Key Changes
1. Fix for capturing column descriptions
2. SqlParsingAggregator Integration
Replaced custom lineage processing with modern aggregator
self.aggregator = SqlParsingAggregator(
platform="teradata",
generate_lineage=True,
generate_queries=True,
generate_usage_statistics=True,
)
3. Enhanced View Processing
- Multi-threaded view processing with view_processing_workers
- SqlParsingAggregator integration for view DDL analysis
- Parallel processing with proper threading validation
4. Historical lineage extraction from PDCRDATA.DBQLSqlTbl_Hst  if exists
- include_historical_lineage needs to be enabled  
5. Memory-Efficient Streaming
Stream processing without memory accumulation
for entry in self._fetch_lineage_entries_chunked():
observed_query = …
=> fix(ingest/teradata): Teradata perf improvements

metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_api.py
=> fix(ingest/dremio): add debug info on failed requests

.github/workflows/docker-unified.yml
=> fix(ci): avoid concurrent action cache  updates

smoke-test/tests/openapi/v3/entities.json, smoke-test/tests/utilities/concurrent_openapi.py
=> fix(test): fix test conflicts in openapi

docs/developers.md, docs/troubleshooting/build.md
Fixed a few typos in developer-related documentation files.
=> docs: typos fixed

metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json, metadata-ingestion/src/datahub/ingestion/source/mlflow.py
=> fix(ingest/mlflow): add missing container modifier

build.gradle
=> chore(deps): fix (org.pac4j:pac4j-oidc)

docker/kafka-setup/Dockerfile
=> chore(kafka-setup): bump aws-msk-iam-auth

.github/workflows/docker-unified.yml
=> fix(ci): image publish only for master branch push or release

metadata-ingestion/src/datahub/ingestion/api/source.py, metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
=> fix(ingest/dbt): improve dbt-cloud error message

datahub-actions/pyproject.toml, metadata-ingestion-modules/airflow-plugin/pyproject.toml, metadata-ingestion-modules/dagster-plugin/pyproject.toml, metadata-ingestion-modules/gx-plugin/pyproject.toml, metadata-ingestion-modules/prefect-plugin/pyproject.toml, metadata-ingestion/pyproject.toml, metadata-service/iceberg-catalog/pyproject.toml, smoke-test/pyproject.toml
=> chore(setuptools): bump setuptools

metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLSpringCommonTestConfiguration.java, metadata-service/configuration/src/test/java/com/linkedin/metadata/config/DataHubAppConfigurationTest.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java, metadata-service/factories/src/test/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactoryTest.java, metadata-service/factories/src/test/java/com/linkedin/gms/factory/search/DisabledCustomSearchTest.java
=> fix(spring): fix null custom search config

.github/workflows/airflow-plugin.yml, .github/workflows/build-and-test.yml, .github/workflows/dagster-plugin.yml, .github/workflows/gx-plugin.yml, .github/workflows/metadata-ingestion.yml, .github/workflows/metadata-io.yml, .github/workflows/prefect-plugin.yml
=> fix(ci): use depot runners when possible

metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java, metadata-service/war/src/test/java/com/linkedin/gms/SpringTest.java
=> Enabling SSL for gms if the keystore and password is passed

.github/workflows/quickstart-test.yml
=> fix(ci): quickstart ci - additional tests

docs-website/sidebars.js, docs/managed-datahub/upgrade_core_to_cloud.md
In this doc, we provide instructions on upgrading from DataHub Core to DataHub Cloud.
=> docs(upgrade): Add instructions / user guide for upgrading from Core to Cloud

.github/workflows/quickstart-test.yml, docker/quickstart/quickstart_version_mapping.yaml
=> feat(quickstart): bump default version to v1.2.0

metadata-ingestion/src/datahub/sdk/search_filters.py, metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
~Stacked on top of https://github.com/datahub-project/datahub/pull/14127~
=> feat(sdk): add container filter to search sdk

datahub-web-react/src/app/ingestV2/executions/components/ExecutionDetailsModal.tsx
=> fix(ui/ingest): change title

datahub-web-react/src/app/ingestV2/executions/components/SummaryTab.tsx, datahub-web-react/src/app/ingestV2/source/IngestedAssets.tsx, datahub-web-react/src/app/ingestV2/source/utils.ts
=> fix(ui/ingest): cleanup, exception handling

metadata-ingestion/src/datahub/sdk/search_filters.py, metadata-ingestion/tests/unit/sdk/test_client.py
The new docs should help anyone looking at the JSON schema for the filter types.
=> feat(sdk): add data products to suggested entity type filters

.github/workflows/pr-labeler.yml
=> ci: update pr-labeler

datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/EntityProfileSidebar.tsx
=> fix(ui): remove box-shadow, margin, and collapse button on embedded sidebar

docs/tests/metadata-tests.md
=> docs(metadata test): clarify current state

docs/townhalls.md
Updates to town hall with new link
=> docs(townhall): Update Town Hall details

metadata-ingestion/src/datahub/upgrade/upgrade.py
=> fix(cli): do not check for compatibility if cloud

datahub-web-react/src/app/analytics/event.ts, datahub-web-react/src/app/homeV3/EditDefaultTemplateBar.tsx, datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx, datahub-web-react/src/app/homeV3/announcements/Announcements.tsx, datahub-web-react/src/app/homeV3/context/hooks/useModuleModalState.ts, datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts, datahub-web-react/src/app/homeV3/context/types.ts, datahub-web-react/src/app/homeV3/module/components/EntityItem.tsx, datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx, datahub-web-react/src/app/homeV3/modules/YourAssetsModule.tsx, datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModule.tsx, datahub-web-react/src/app/homeV3/modules/assetCollection/SelectAssetsSection.tsx, datahub-web-react/src/app/homeV3/modules/assetCollection/SelectedAssetsSection.tsx, datahub-web-react/src/app/homeV3/modules/assetCollection/dragAndDrop/DraggableEntityItem.tsx, datahub-web-react/src/app/homeV3/modules/domains/TopDomainsModule.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/DomainsTreeView.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/glossary/GlossaryTreeView.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts, datahub-web-react/src/app/homeV3/modules/link/LinkModule.tsx, datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx, metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
This PR adds audit events related to the new home page
One event `HomePageTemplateResetToGlobalTemplate` isn't handled as it's not implemented yet
=> feat(customHomePage): add telemetry

build.gradle
=> chore(deps): fix (com.typesafe.play:shaded-oauth)

datahub-web-react/src/alchemy-components/components/Tabs/Tabs.tsx, datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/GovernanceTab.tsx, datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/TestResults.tsx, datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/TestResultsSummary.tsx, datahub-web-react/src/app/entityV2/dataset/DatasetEntity.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/AcrylValidationsTab.tsx, datahub-web-react/src/app/homeV2/content/tabs/announcements/AnnouncementsTab.tsx, datahub-web-react/src/app/homeV2/content/tabs/discovery/DiscoveryTab.tsx
- Update margin (removed)
- Cleaned up subtags to align on the left
- Added count to governance tab 
- Changed text in governance tab
- Cleaned up icons in gov tab
Before: 
After:
=> updated tabs to remove margin minor updates to quality tab

datahub-web-react/src/app/sharedV2/queryBuilder/builder/__tests__/utils.test.tsx, datahub-web-react/src/app/sharedV2/queryBuilder/builder/utils.ts
=> fix(customHomePage): fix hierarchy view with empty condition in filter

metadata-operation-context/src/main/java/io/datahubproject/metadata/context/RequestContext.java, metadata-operation-context/src/test/java/io/datahubproject/metadata/context/RequestContextTraceTest.java
Expose the trace id with the request log and logging context.
=> feat(logging): add trace id to logging

datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts, datahub-web-react/src/app/homeV3/context/hooks/__tests__/useTemplateOperations.test.ts, datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts, datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
=> fix(customHomePage): fix splitting a row below when editing global module

datahub-upgrade/build.gradle, datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillDatasetLineageIndexFieldsConfig.java, datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFields.java, datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFieldsStep.java, datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFieldsTest.java, metadata-models/src/main/pegasus/com/linkedin/dataset/FineGrainedLineage.pdl, metadata-models/src/main/pegasus/com/linkedin/dataset/Upstream.pdl, smoke-test/tests/search/test_lineage_search_index_fields.py
Need the hasUpstreams and hasFineGrainedUpstreams for ingestion completion coverage
Loom showing it working [loom.com/share/3dc21761d902415fa1fe539d42d6e87d](https://www.loom.com/share/3dc21761d902415fa1fe539d42d6e87d)
=> feat(lineage): add pdl annotations for upstreams

metadata-ingestion/build.gradle, metadata-ingestion/tests/integration/okta/test_okta.py
=> chore(ingest): reduce Okta test warnings

metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java, metadata-io/src/test/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformerTest.java
* handle removing fields in elasticsearch
* fixes moving term groups to root level
=> fix(es-field-removal): extend field removal logic for elasticsearch

docs/deploy/environment-vars.md
=> docs(envs): update environment variables

metadata-ingestion/src/datahub/ingestion/source/hex/query_fetcher.py
=> fix(ingest/hex): improve warning message

docs/automations/ai-docs.md, docs/managed-datahub/slack/saas-slack-app.md
Also moves the Slack bot related content up on the page.
=> docs(slack): update screenshots

metadata-ingestion/src/datahub/ingestion/graph/client.py
Not comprehensive yet, but should cover more cases.
=> fix(ingest): improve entity type -> graphql enum conversion

metadata-ingestion/src/datahub/ingestion/source/sql/athena_properties_extractor.py
=> fix(ingestion/athena): Fix DeprecationWarning: invalid escape sequence '\s' for testing

metadata-models-custom/README.md
Sample repo introduced in https://github.com/datahub-project/datahub/pull/14250
=> docs(customer-metadata-models): refer to the custom data validator repo

docs-website/sidebars.js, docs/features/feature-guides/custom-home-page.md
This PR adds a new feature guide for the custom home page feature that is private launching soon!
=> feat(docs) Add feature guide doc for the new custom home page

metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
=> feat(ingest): include endpoint in rest sink report

docs-website/sidebars.js, docs/managed-datahub/observe/assertion-notes.md, docs/managed-datahub/observe/assertions.md, docs/managed-datahub/observe/column-assertions.md, docs/managed-datahub/observe/data-health-dashboard.md, docs/managed-datahub/observe/freshness-assertions.md, docs/managed-datahub/observe/smart-assertions.md, docs/managed-datahub/observe/volume-assertions.md
=> feat(docs): 3.13 Observe docs

docker/datahub-gms/Dockerfile, docker/datahub-mae-consumer/Dockerfile, docker/datahub-mce-consumer/Dockerfile, docker/datahub-upgrade/Dockerfile, docker/elasticsearch-setup/Dockerfile, docker/mysql-setup/Dockerfile, docker/postgres-setup/Dockerfile
=> chore(): bump base alpine image

smoke-test/tests/cypress/cypress/e2e/mutations/edit_documentation.js, smoke-test/tests/cypress/cypress/e2e/ownership/manage_ownership.js
* fixes for latest Cypress flakes
=> ci(cypress): fix Cypress flakes

metadata-ingestion/src/datahub/ingestion/source/looker/looker_liquid_tag.py, metadata-ingestion/tests/integration/lookml/test_lookml.py
Adding support for incrementalcondition condition in liquid template -> https://cloud.google.com/looker/docs/reference/param-view-increment-key#creating_an_incremental_sql-based_pdt
This way the source generates proper sql from liquid template with incrementalcondition expression
=> feat(ingest/lookml): Lookml incremental expression support

build.gradle
=> Upgrading the spring version

docker/kafka-setup/Dockerfile, docker/kafka-setup/build.gradle
* mirrors other alpine based images
* fixes several CVEs: CVE-2025-50059, CVE-2025-30749, CVE-2025-50106, CVE-2025-6965
=> chore(kafka-setup): migrate from confluent image to alpine

metadata-ingestion/CLAUDE.md, metadata-ingestion/tests/unit/cli/test_check_upgrade.py
=> test(cli/upgrade): add unit test for check upgrade

metadata-service/iceberg-catalog/src/main/java/io/datahubproject/iceberg/catalog/TableOrViewOpsDelegate.java, metadata-service/iceberg-catalog/src/test/java/io/datahubproject/iceberg/catalog/TableOpsDelegateTest.java
=> feat(irc): report partition key field info

docs/advanced/patch.md, metadata-ingestion/examples/library/datajob_add_lineage_patch.py
=> docs(patch): fix patch docs tab & Add datajobpatchbuilder script 

datahub-web-react/src/app/entityV2/dataset/profile/__tests__/schema/translateFieldPath.test.tsx, datahub-web-react/src/app/entityV2/dataset/profile/__tests__/schema/translateFieldPathSegment.test.tsx, datahub-web-react/src/app/entityV2/dataset/profile/schema/utils/translateFieldPathSegment.tsx
=> fix(ui/schema): Remove [] from array v2 field path names

datahub-web-react/src/app/entityV2/group/GroupMembersSidebarSectionContent.tsx, datahub-web-react/src/app/entityV2/group/GroupSidebar.tsx, datahub-web-react/src/app/entityV2/group/GroupSidebarMembersSection.tsx, datahub-web-react/src/app/identity/group/CreateGroupModal.tsx
=> fix(web): improved group setup UX

docs/cli.md, docs/managed-datahub/observe/data-contract.md, metadata-ingestion/examples/library/create_data_contract.yml, metadata-ingestion/src/datahub/cli/specific/assertions_cli.py, metadata-ingestion/src/datahub/cli/specific/datacontract_cli.py
=> refactor(data-contracts): deprecating data contracts

datahub-web-react/src/app/entity/EntityRegistry.tsx, datahub-web-react/src/app/entityV2/EntityRegistry.tsx, datahub-web-react/src/app/ingestV2/source/IngestedAssets.tsx, datahub-web-react/src/app/ingestV2/source/__tests__/tests_utils.test.tsx, datahub-web-react/src/app/ingestV2/source/utils.ts
=> fix(ui/ingest): exclude entities that don't have search card

docs/ownership/ownership-types.md
=> fix(docs) Fix typo in custom ownership types doc

docs/managed-datahub/release-notes/v_0_3_13.md
=> docs(release-notes): saas v3.13.1 release notes

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py, metadata-ingestion/tests/unit/looker/test_looker_common.py
=> fix(ingest/looker): Ignore fields with empty column name to not generate invalid field urns

docs/managed-datahub/release-notes/v_0_3_13.md
=> docs: release note updates for scim

metadata-ingestion/src/datahub/ingestion/source/mock_data/datahub_mock_data.py
=> fix(mock-data): properly add run id

smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js
=> fix(smoke-test): v1 ui group smoke test

datahub-web-react/src/app/entityV2/EntityRegistry.tsx, datahub-web-react/src/app/entityV2/chart/ChartEntity.tsx, datahub-web-react/src/app/entityV2/container/ContainerEntity.tsx, datahub-web-react/src/app/entityV2/container/ContainerSummaryTab.tsx, datahub-web-react/src/app/entityV2/container/preview/Preview.tsx, datahub-web-react/src/app/entityV2/dashboard/DashboardEntity.tsx, datahub-web-react/src/app/entityV2/dataFlow/preview/Preview.tsx, datahub-web-react/src/app/entityV2/dataJob/DataJobEntity.tsx, datahub-web-react/src/app/entityV2/dataProcessInstance/DataProcessInstanceEntity.tsx, datahub-web-react/src/app/entityV2/dataset/DatasetEntity.tsx, datahub-web-react/src/app/entityV2/shared/EntityDropdown/EntityDropdown.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/header/PlatformContent/ContainerIcon.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/header/utils.ts, datahub-web-react/src/app/entityV2/shared/utils.ts, datahub-web-react/src/app/searchV2/autoComplete/AutoCompleteEntity.tsx, datahub-web-react/src/app/searchV2/autoCompleteV2/utils.ts
=> refactor(ui): helper method to get subtypes

build.gradle
=> Upgrading spring version to non-vulnerable version

datahub-web-react/src/app/ingestV2/executions/components/reporting/StructuredReportItem.tsx
Shows the fix https://www.loom.com/share/17026fac2103419d901052738a75602a
=> fix(ui/ingest): expand when clicking anywhere not just icon

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py
=> chore(ingest): update url for GX fork

datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/DomainsTreeView.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/glossary/GlossaryTreeView.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx, datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts
https://github.com/user-attachments/assets/bf185570-991a-4c7c-b841-5eef75bf07de
=> feat(customHomePage/hierarchy): add possibility to automatically expand a single root node

datahub-web-react/src/app/sharedV2/queryBuilder/QueryBuilder.tsx
https://github.com/user-attachments/assets/57cde70e-4cf1-4cfc-aeea-d8d6f22664c4
=> fix(customHomePage): fix removing of nested groups in query builder

datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx
Shows the fix https://www.loom.com/share/ba5dd4fa812a46ec9c0a9cfc88ddc6d5
=> fix(ui/ingest): wrap name to 2 lines before truncate

datahub-actions/src/datahub_actions/utils/kafka_msk_iam.py, datahub-actions/tests/unit/utils/test_kafka_msk_iam.py
=> Add AWS MSK IAM authentication module and unit tests

build.gradle
=> chore(): upgrade netty

metadata-ingestion/tests/integration/grafana/docker-compose.yml, metadata-ingestion/tests/integration/grafana/test_grafana.py
=> fix(ingestion/grafana): stabilize integration tests

datahub-web-react/src/alchemy-components/components/Switch/components.ts, datahub-web-react/src/alchemy-components/components/Switch/utils.ts
=> Updated switch and bg color to gradient updated MD sizing

datahub-web-react/src/alchemy-components/components/Avatar/AvatarPillWithLinkAndHover.tsx, datahub-web-react/src/app/entityV2/summary/SummaryTab.tsx, datahub-web-react/src/app/entityV2/summary/links/AddLinkButton.tsx, datahub-web-react/src/app/entityV2/summary/links/AddLinkModal.tsx, datahub-web-react/src/app/entityV2/summary/links/LinkItem.tsx, datahub-web-react/src/app/entityV2/summary/links/Links.tsx, datahub-web-react/src/app/entityV2/summary/links/LinksList.tsx, datahub-web-react/src/app/entityV2/summary/links/__tests__/useLinkUtils.test.ts, datahub-web-react/src/app/entityV2/summary/links/useLinkUtils.ts
**Linear tickets:**
https://linear.app/acryl-data/issue/CH-674/build-add-link-functionality-in-the-new-summary-tab
https://linear.app/acryl-data/issue/CH-675/display-links-below-documentation
https://linear.app/acryl-data/issue/CH-684/ability-to-delete-existing-links
https://linear.app/acryl-data/issue/CH-705/add-confirmation-modal-when-deleting-links
=> feat(ui/summary): build add, view and delete link functionalities in the new summary tab

docs/managed-datahub/release-notes/v_0_3_13.md
=> docs(release-notes): v0.3.13.2-acryl

metadata-ingestion-modules/airflow-plugin/setup.py, metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/hooks/datahub.py
=> chore(airflow): cleanup deps + lingering print statement

docker/datahub-upgrade/Dockerfile
=> chore(): bump kubectl version

datahub-web-react/src/app/entityV2/shared/tabs/Incident/CreateIncidentButton.tsx, smoke-test/tests/cypress/cypress/e2e/incidentsV2/v2_incidents.js
=> tests(incidents_v2): fix flakiness by waiting for sibling specific test id

datahub-web-react/CLAUDE.md
=> doc(ui): avoiding PropTypes

metadata-events/mxe-utils-avro/src/main/java/com/linkedin/metadata/EventSchemaConstants.java
=> fix(constants): jdk8 support fix

datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/__tests__/useExtractFieldGlossaryTermsInfo.test.ts, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/utils/__tests__/useExtractFieldTagsInfo.test.ts
=> test(ui): Refactor useExtractFieldTagsInfo and useExtractFieldGlossaryTermsInfo tests

.github/workflows/docker-unified-nightly.yml
=> fix(ci): fix nightly tag for smoke-tests

datahub-frontend/app/auth/sso/oidc/OidcConfigs.java, datahub-frontend/app/auth/sso/oidc/OidcProvider.java, datahub-frontend/app/auth/sso/oidc/custom/CustomOidcAuthenticator.java, datahub-frontend/app/auth/sso/oidc/custom/CustomOidcClient.java, datahub-frontend/app/auth/sso/oidc/custom/CustomOidcProfileCreator.java, datahub-frontend/conf/application.conf, datahub-frontend/test/app/ApplicationTest.java, datahub-frontend/test/auth/sso/oidc/OidcConfigsRetryTest.java, datahub-frontend/test/auth/sso/oidc/custom/CustomOidcAuthenticatorTest.java, datahub-frontend/test/auth/sso/oidc/custom/CustomOidcClientTest.java, datahub-frontend/test/auth/sso/oidc/custom/CustomOidcProfileCreatorTest.java
=> test(ci): test stability fix

.github/workflows/docker-unified-nightly.yml
=> fix(): Update docker-unified-nightly.yml

datahub-web-react/src/app/govern/structuredProperties/cacheUtils.ts
https://linear.app/acryl-data/issue/CH-737/creating-structured-property-failed
=> fix(ui/structured-properties): fix error on create structured property

.github/workflows/docker-unified-nightly.yml
=> fix(ci): use image tags from buildLog for nightly tests

datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx, datahub-web-react/src/app/homeV3/module/components/__tests__/LargeModule.test.tsx, datahub-web-react/src/app/homeV3/template/Template.tsx
https://linear.app/acryl-data/issue/CH-727/implement-permissions-for-modules-section
=> feat(ui/summary-tab):implement permissions for modules section

build.gradle
=> chore(): bump netty version

metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/v3/models/Criterion.java, metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/v3/models/GenericEntityScrollResultV3.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java, metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java, metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/controller/EntityControllerTest.java, smoke-test/tests/openapi/v3/entities.json
This PR has two small enhancement over scroll API in openapi v3
- Include totalCount in the response.
- Add additional filter condition `CONTAIN`.
```
curl -X POST 'http://localhost:8080/openapi/v3/entity/scroll?count=10' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6ImNlM2RjNWYxLTg1ZmEtNGViYi04OWMzLWM5YjQ1ZWQ1NWExMyIsInN1YiI6ImRhdGFodWIiLCJleHAiOjE3NTk2MTUzODUsImlzcyI6ImRhdGFodWItbWV0YWRhdGEtc2VydmljZSJ9.npMnyeCyO_qY9otPP4B8QtuLjb3e0m_3Yr6XZ9E9M38' \
-d '{
"sortCriteria": [
{
"field": "name",
"order": "ASCENDING"
}
],
"aspects": [],
"entities": [
"entityType", "dataPlatform"
],
"filter": {
"and": [
{
"criteria": [ …
```
=> feat(openapi-v3) enhance scroll API

metadata-ingestion/src/datahub/ingestion/source/metadata/lineage.py
=> chore(ingestion/file-based lineage): update from com.linkedin.pegasus2avro.dataset to datahub.metadata.schema_classes

.github/workflows/docker-unified.yml
=> fix(ci): revert workaround to enumerate image targets

datahub-web-react/src/alchemy-components/components/InfiniteScrollList/InfiniteScrollList.tsx, datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModule.tsx
=> fix(summaryTab): fix empty state when assets were deleted

docs/managed-datahub/teams/saas-teams-setup.md
Replaced the download link for the Teams App zip file with instructions to contact a DataHub Customer Success Rep for access to the Teams Private Beta.
=> docs(teams): Update Teams App setup instructions

docs/managed-datahub/slack/saas-slack-setup.md
=> docs(slack): Update Slack setup instructions for token generation

datahub-frontend/conf/application.conf
=> fix(security): disable akka dns

datahub-web-react/src/app/ingestV2/ManageIngestionPage.tsx, datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
https://www.loom.com/share/06b626367af849378010b2421e32c39f
=> feat(ui/ingest): make filter params part of url for navigation

datahub-frontend/conf/application.conf
Fix config for akka dns with reference doc
=> fix(): fix config value

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py, metadata-ingestion/src/datahub/ingestion/source/looker/looker_constant.py, metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py, metadata-ingestion/src/datahub/ingestion/source/looker/looker_view_id_cache.py, metadata-ingestion/src/datahub/ingestion/source/looker/lookml_concept_context.py, metadata-ingestion/src/datahub/ingestion/source/looker/lookml_config.py, metadata-ingestion/src/datahub/ingestion/source/looker/lookml_refinement.py, metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py, metadata-ingestion/src/datahub/ingestion/source/looker/view_upstream.py, metadata-ingestion/tests/integration/looker/test_looker.py, metadata-ingestion/tests/integration/lookml/lkml_col_lineage_looker_api_based_golden.json, metadata-ingestion/tests/integration/lookml/lkml_col_lineage_sample/models/dev_project.model.lkml, metadata-ingestion/tests/integration/lookml/lkml_col_lineage_sample/views/purchases.view.lkml, metadata-ingestion/tests/integration/lookml/lkml_col_lineage_sample/views/user_metrics.view.lkml, metadata-ingestion/tests/integration/lookml/lkml_col_lineage_sample/views/users.view.lkml, metadata-ingestion/tests/integration/lookml/test_lookml.py, metadata-ingestion/tests/unit/looker/test_looker_query_api_view_upstream.py, metadata-ingestion/tests/unit/lookml/test_lookml_api_based_view_upstream.py
Enhanced column lineage extraction for Looker
- **New `LookerQueryAPIBasedViewUpstream` class** in `view_upstream.py` for more accurate lineage extraction
- Enhanced column-level lineage extraction using Looker Query API
- Improved field name translation between Looker API format and internal format
- Better handling of view-to-explore mapping for lineage extraction
- Added support for graceful fallback when Query API fails
- **Enhanced error handling** in Looker API integration
- Improved connection validation and authentication error messages
- Better handling of malformed table names and connection issues
- Added comprehensive warning reporting for various edge cases
- Enhanced retry mechanism for Looker SDK transport
- **Enhanced fine-grained lineage generation** with better …
=> feat(ingestion): Enhanced column lineage extraction for Looker/LookML

metadata-ingestion/src/datahub/secret/datahub_secret_store.py, metadata-ingestion/src/datahub/secret/environment_secret_store.py, metadata-ingestion/src/datahub/secret/file_secret_store.py, metadata-ingestion/tests/unit/secret/test_datahub_secret_store.py, metadata-ingestion/tests/unit/secret/test_environment_secret_store.py, metadata-ingestion/tests/unit/secret/test_file_secret_store.py
This is adding a couple of new `SecretStore` implementations:
* `EnvironmentSecretStore`
* and `FileSecretStore`
=> feat(secret): FileSecretStore and EnvironmentSecretStore

.github/workflows/react-cloudflare-pages.yml
=> ci(cloudflare): fix workflow check for secret

datahub-web-react/src/app/entityV2/shared/containers/profile/header/EntityName.tsx
We had an issue where entity names would get collapsed when opening the sidebar and would never reappear if you close the sidebar. This fixes that by keeping track of the sidebar being open or closed and updates the React key to rerender the name once it changes. A timeout is needed to wait for the animation to finish.
**Video of before:**
https://github.com/user-attachments/assets/dfd969a5-9785-4603-a9cd-a61eaeff26e3
**Video after:**
https://github.com/user-attachments/assets/3e1f2359-4aef-45a6-9a3e-82d5fc3218f4
=> fix(ui) Fix re-expanding entity name after sidebar opens/closes

docs/managed-datahub/release-notes/v_0_3_14.md
=> docs(release-notes): disclaimers for 0.3.14

datahub-web-react/src/app/ingestV2/source/__tests__/tests_utils.test.tsx, datahub-web-react/src/app/ingestV2/source/utils.ts
=> feat(ui/ingest): add source errors, warnings

datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearchResults.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Lineage/CompactLineageTab.tsx
Fixing issues where embedded list overflowed in tight spaces and was not responding to the parent width correctly
=> fix(web): embedded search list responsiveness

datahub-web-react/src/app/entityV2/shared/components/legacy/DescriptionModal.tsx, datahub-web-react/src/app/entityV2/shared/components/styled/LinkFormModal.tsx, datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/SidebarSection.tsx, datahub-web-react/src/app/entityV2/shared/externalUrl/ViewInPlatform.tsx, datahub-web-react/src/app/entityV2/shared/externalUrl/components/VeiwMoreDropdown/OptionLabel.tsx, datahub-web-react/src/app/entityV2/shared/externalUrl/components/VeiwMoreDropdown/ViewMoreDropdown.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldDescription.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/LinkList.tsx, datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/editor/Editor.tsx, datahub-web-react/src/app/sharedV2/OverflowList.tsx, smoke-test/tests/cypress/cypress/e2e/mutationsV2/v2_edit_documentation.js, smoke-test/tests/cypress/cypress/support/commands.js
This PR includes cypress tests for custom links
=> test(customLinks): add cypress tests (#274)

smoke-test/tests/institutional_memory/data.json, smoke-test/tests/institutional_memory/institutional_memory_test.py
This PR includes integration tests for custom links
DEPENDS ON: https://github.com/datahub-project/datahub/pull/14854
=> test(customLinks): add integration tests (#275)
