datahub-project/datahub

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/search/SearchFilterLabel.tsx
datahub-web-react/src/app/shared/TagStyleEntity.tsx
datahub-web-react/src/app/shared/tags/DomainLink.tsx

Changes:
1. Truncate long filter values, show full value in popover. 
2. Fix styling when long tags cause the entity title to wrap in search. 
3. Fix Tag Color Picker on profile page to save color when user clicks out of color picker.

fix(ui) Misc styling fixes (truncated filter values, updating tag color on clickaway) 

---

metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py

- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
Datasets created as part of kafka connect ingestion are created with default `PROD` env. This fix is to pass the env variable from the recipe.

fix(ingest) kafka-connect: Pass the env variable as part of making dataset

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/tests/integration/tableau/setup/workbooksConnection_8.json

As reported in  slack [1](https://datahubspace.slack.com/archives/C02GBGG90CU/p1645040303160589?thread_ts=1644881402.488669&cid=C02GBGG90CU) [2](https://datahubspace.slack.com/archives/C02GBGG90CU/p1645204203359639) there is an issue with the ingestion of certain sheets that do not have either a `path` or `containedInDashboards`.
This might happen if the sheet is hidden (i.e. published but not exposed via web interface) or its a viz-in-tooltip (only accessible by hovering over marks in another sheet). As a workaround we can just fallback to the tableau URL

fix(ingest): fix tableau sheets external url ingestion

---

metadata-ingestion/source_docs/elastic_search.md
metadata-ingestion/src/datahub/ingestion/source/elastic_search.py

There are cases where an enterprise would have multiple elastic search clusters. One way for them to manage is to have a single endpoint for all the elastic search clusters and use `url_prefix` for routing requests to different clusters. 
The current elasticsearch source does not support this use case. We can add the support by adding an optional config parameter called `url_prefix` and passing the value of `url_prefix` to the underlying `Elasticsearch` client constructor while creating it like 
```
source:
type: "elasticsearch"
config:
env: "DEV"
host: "localhost:9200"
url_prefix: 'test_cluste1'
```
We need one more change to support this. Right now we use the following call for getting the list of indices from elastisearch `es.indices.get_alias(index="*")` which results into HTTP call …

Add support for url_prefix in elastisearch source

---

metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hydrator/DatasetHydrator.java

fix(mae-comsumer): wrong aspect name in usage event transformer

---

metadata-ingestion/source_docs/openapi.md
metadata-ingestion/src/datahub/ingestion/source/openapi.py
metadata-ingestion/src/datahub/ingestion/source/openapi_parser.py
metadata-ingestion/tests/integration/openapi/openapi_mces_golden.json

In order to interrogate the endpoints, an authentication via token is required.
Before this PR, only a POST request with username/password in the body was available. Now also a GET method, with username/password directly wrote in the url, is available.

Openapi new auth

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/LoadableTypeBatchResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/graphql/policy.graphql

We're currently working on a redesign of the Policies tab, and this will allow us to viz the users and groups attached to a policy more beautifully.

feat(graphql): Adding resolved users and groups to policies

---

metadata-ingestion/src/datahub/cli/timeline_cli.py
metadata-io/src/main/java/com/linkedin/metadata/timeline/differ/GlobalTagsDiffer.java
metadata-io/src/main/java/com/linkedin/metadata/timeline/differ/SchemaDiffer.java
metadata-io/src/main/java/com/linkedin/metadata/timeline/ebean/EbeanTimelineService.java
smoke-test/tests/timeline/timeline_test.py

Fixes issues with semantic versioning
* When multiple categories requested version was per category and looked weird
* Differs per category did not roll up either
* No more empty results w/ None semverchange
* Better colors

bug(schema_version_history): fix semantic version ordering

---

datahub-web-react/src/app/recommendations/renderer/component/TagSearchList.tsx
datahub-web-react/src/graphql/preview.graphql

Tag color configurations not appearing correctly in the recommendations. This PR fixes that

fix(recs ui): fixing tag color in recommendations

---

metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py

Fixes snowflake lineage (table->table via direct_objects_modified instead of base_objects_modified, inspects all MetadataWorkunits instead of just SqlWorkUnits)
Enhances logging and reporting.

fix(ingestion): Fix snowflake lineage + logging & reporting improvements.

---

docker/airflow/local_airflow.md

There is an Error in the "Running airflow locally" documentation: 
As described in the [official airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#initialize-the-database), the doc is missing the airflow-init statement. The result is that the container won´t start properly as the initial database tables and the initial user are missing.
The fix is to add the missing line to the documentation and rearrange the paragraphs.

fix(docs): Error in running airflow locally

---

docs/developers.md
li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json

Our organization uses `DEV`, `PRE`, and `PRO` as standard names for the usual environments.
The missing `PRE` in the `FabricType` forces us to do mappings (_eg_ EI --> PRE) everywhere. So kindly requesting adding `PRE`.

feat(model): adds PRE in the FabricType enum

---

metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py

The existing query can produce false edges between a view and its upstreams. This fix replaces it with a more robust query against the OBJECT_DEPENDENCIES view (see https://docs.snowflake.com/en/user-guide/object-dependencies.html#object-dependencies).

fix(ingestion): Fix snowflake view upstream lineages to eliminate false edges.

---

docker/datahub-gms/start.sh
docker/datahub-mae-consumer/start.sh
docker/datahub-mce-consumer/start.sh

Docker containers of mae, mce and gms uses shell form, so the main process will be the start script, which can't handle signals sent to it. This fixes changes the scripts to use exec form.

fix(docker): use exec form to start container main process

---

metadata-ingestion/source_docs/bigquery.md
metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

- Ability to disable partition profiling
- Creating profiling bigquery temp tables in the schema where the profiling table is by default.

feat(profiling) - Bigquery: Ability to disable partition profiling

---

metadata-ingestion/source_docs/data_lake.md
metadata-ingestion/src/datahub/ingestion/source/data_lake/__init__.py
metadata-ingestion/src/datahub/ingestion/source/data_lake/config.py

Adds a few sentences to the docs clarifying the need to grant S3A permissions when running profiling on files in AWS S3. Also sets the `platform` to `s3` or `file` depending on the `base_path` if `platform` is unspecified.

fix(ingest): clarify s3/s3a requirements and platform defaults

---

docs/how/auth/add-users.md

Small change. <> seems to make docs build complain.

Remove <> from add-users.md doc

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py

The checkpointing state stores the config as well. In the case of BigQuery, the `platform_instance` will have a value of `None`. The BigQueryConfig validator currently raises an exception unconditionally if this member is present, as opposed to it having  a non `None` value. The fix addresses this issue.

fix(ingestion): Fix bigquery stateful ingestion checkpoint reconstruction.

---

datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx

Worked on the UI bug
- Height of editor
- The spacing issue between logo and description

Fixed the UI issue: Height issue of editor and the spacing issue between logo and description

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py

fix(ingest) bigquery: Remove unneeded warning

---

metadata-ingestion/src/datahub/ingestion/source/openapi.py
metadata-ingestion/tests/integration/openapi/openapi_mces_golden.json
metadata-service/war/src/main/resources/boot/data_platforms.json

Revert of casing change https://github.com/linkedin/datahub/pull/4086 of platform

fix: revert changes to OpenApi casing

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/DatasetMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/graphql/browse.graphql
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/preview.graphql
datahub-web-react/src/graphql/relationships.graphql
datahub-web-react/src/graphql/search.graphql
metadata-ingestion/source_docs/tableau.md
metadata-ingestion/src/datahub/emitter/mcp_builder.py
metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
metadata-ingestion/tests/integration/tableau/setup/publishedDatasourcesConnection_2.json
metadata-ingestion/tests/integration/tableau/setup/workbooksConnection_8.json
metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProperties.pdl
metadata-models/src/main/pegasus/com/linkedin/metadata/key/DatasetKey.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json

This PR
- emits Tableau workbook as Container entity and adds charts, dashboards to container
- fixes `View in Tableau` URL for empty/default site in tableau server
- adds workbooks_page_size config parameter which can be tuned to get rid of NODE_LIMIT_EXCEEDED error when querying workbooks

feat(tableau): emit workbook as container entity in tableau source, some minor fixes in tableau source

---

datahub-web-react/src/app/entity/shared/containers/profile/utils.ts

fix(tags) - map tags to globalTags for entities

---

datahub-web-react/src/app/entity/user/UserProfile.tsx

Fallback to the normal username if a display name does not exist. Do not default to None.

fix(ui): Correct display name for users in UI

---

metadata-ingestion/src/datahub/entrypoints.py

This change isolates the `datahub` logger and it's child loggers from inadvertent changes to the root logger by the external modules(site-packages) that we import. This also fixes the current issue with the `INFO` and `DEBUG` log messages of lookml source getting dropped.

fix(ingestion): Insulate 'datahub' and child loggers from external modules.

---

docs/deploy/aws.md
docs/ui-ingestion.md

feat(aws-docs): Add section on attaching policies to the datahub-actions pod

---

metadata-ingestion/source_docs/elastic_search.md
metadata-ingestion/src/datahub/ingestion/source/elastic_search.py

Currently, there is no way to ingest **Elasticsearch** with the default `username=""` and `password=""`, which raises the exception above. This PR fixes the issue by making them optional.

Allow elasticsearch to authenticate without `username` and `password`

---

metadata-ingestion/source_docs/postgres.md

<docs>[postgres]: update the `platform_instance` field of postgres ingestion doc
Add the `platform_instance` field in postgres doc, after testing this field functions normally.
No `BREAKING CHANGE`

docs: Update postgres.md

---

datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/graphql/container.graphql

Graphql query wasn't fetching custom properties so they werent showing up in the UI

fix(containers): query for custom properties on containers

---

.gitignore
docker/docker-compose-without-neo4j.yml
docker/docker-compose.yml
docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
docker/quickstart/docker-compose-without-neo4j.quickstart.yml
docker/quickstart/docker-compose.quickstart.yml

Sometimes actions pod fails. We should restart it a few times to improve user experience.
The format used is undocumented but works as per https://stackoverflow.com/questions/42216017/docker-compose-restart-policy#comment100592024_43006595

feat(quickstart): restart actions pod in case of failures

---

metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-ingestion/src/datahub/entrypoints.py
metadata-ingestion/src/datahub/utilities/memory_leak_detector.py

This change implements `memory_leak_detector.with_leak_detection` decorator that performs memory leak detection when the `--detect-memory-leaks` argument is passed to the `datahub` command. This design allows for decorating any `datahub` command to detect the memory leaks originating from the command. It currently decorates only the `ingest run` command. 
Eg usage: `datahub --detect-memory-leaks ingest -c <path_to_recipe>`.
When `--detect-memory-leaks` is set, the decorator uses python's garbage collector's `DEBUG_LEAK` capability to collect all live objects after a datahub command finishes. Then it collects unique stack traces corresponding to the allocation of these objects if any of the stack frame in the trace originates from a `datahub/*.py` file using tracemalloc. Then it writes the …

feat(ingestion): Add  memory leak detection capability to the datahub cli command.

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/container/mappers/ContainerMapper.java
metadata-ingestion/examples/mce_files/bootstrap_mce.json
metadata-ingestion/examples/mce_files/data_platforms.json
metadata-service/war/src/main/resources/boot/data_platforms.json
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java

**Summary**
Supporting a fallback data platform urn in the case that one cannot be associated with an asset. This is to support the new concept of "data platform instances" which are manifested as individual aspects. Also fixing a bug with containers which will allow the unknown platform type to be returned if one cannot be resolved.
Also adding some default containers to bootstrap_mce.json. 
**Status**

fix(ui): Supporting unknown data platform type

---

datahub-web-react/package.json
datahub-web-react/src/app/shared/TagStyleEntity.tsx
datahub-web-react/yarn.lock

Resolved the alpha slider issue in the tag slider color picker.

Fixed Bug: Alpha slider doesn’t move, only the color slider is movabe in tag color picker

---

metadata-ingestion/integration_docs/great-expectations.md
metadata-ingestion/src/datahub/integrations/great_expectations/action.py
metadata-ingestion/src/datahub/utilities/sql_parser.py
metadata-ingestion/tests/integration/great-expectations/setup/great_expectations/checkpoints/test_checkpoint.yml

feat(GE): add option to disable sql parsing, use default parser

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/service/AnalyticsService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/EntityUtils.java
metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/MostPopularSource.java
metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlyViewedSource.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/RecommendationServiceFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/MostPopularCandidateSourceFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/RecentlyViewedCandidateSourceFactory.java

Also apply removed filter on the metadata analytics charts.

fix(removed): Make sure removed entities do not appear on recommendations

---

metadata-ingestion/src/datahub/telemetry/telemetry.py

fix: telemetry failure should not cause CLI failure

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/api/committable.py

Fixes the following mypy error and restores the mypy version back.
```
src/datahub/ingestion/api/committable.py:42: error: Cannot override final attribute "__match_args__" (previously declared in base class "_StatefulCommittableConcrete")
src/datahub/ingestion/api/committable.py:42: error: Cannot override writable attribute "__match_args__" with a final one
src/datahub/ingestion/api/committable.py:42: error: Definition of "__match_args__" in base class "_CommittableConcrete" is incompatible with definition in base class "_StatefulCommittableConcrete"
```

fix(ingestion): Fix mypy error stateful committable & restore mypy version.

---

metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py

Add try block for query_combiner early return in case a query does not contain attributes (inner_columns | columns) as defined by function get_query_columns().
See discussion in #4389 
Previous code had an early return in case that query did not contain attribute columns. With the new assertion, there is no fallback in the new get_query_columns() function. Hence, some queries fail without a functional fallback. Current work around is to disable the query combiner via: profiling.query_combiner_enabled.

fix(query_combiner): add try block to handle queries of type str

---

metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py

Query svv_tables instead of information_schema.
If a user with metadata access, no data access queries information_schema,
nothing is returned. Querying svv_tables returns all tables in the database.

fix(ingestion): read all tables from redshift

---

metadata-ingestion/src/datahub/ingestion/source/openapi_parser.py
metadata-ingestion/tests/unit/test_openapi.py

This PR prevents a crash on openapi documents that have GET endpoints without a `200` response. For example endpoints that are intended for redirects and only contain `302` responses.

fix(ingest): handle endpoints without 200 response in openapi

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/home/HomePageHeader.tsx

Refactoring the quries into a single one to get the search results on Home Page

---

datahub-frontend/app/auth/AuthModule.java

**Summary**
This PR fixes a recently released issue in version v0.8.29, where the encryption key used to sign session cookies for Pac4j (OIDC only) could be of invalid length depending on what value of DATAHUB_SECRET was used. This was due to a misalignment in the required number of bytes for an AES key (16 or 32) and the number of bytes we were resolving as this key. This PR fixes this.
**Validation**
Reproduced issue and tested the fix locally using Okta. Changed value of DATAHUB_SECRET to many things to confirm.

fix(oidc): Fixing OIDC encryption bug in v0.8.29

---

datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java

**Summary**
Currently, we assume that the groups claim returned by an IdP is a collection is strings. In this PR, we introduce support for claims that are of type "string", which indicates that a single group should be minted, with the user added to it. 
**Verification** 
Verified using a custom "Department" attribute created in Okta.

feat(oidc): Adding support for extracting single string groups claim

---

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

fix(ingest): extract redshift platform correctly from sqlalchemy uri

---

.gitattributes

To avoid the need for dos2unix when checking out the repo on Windows.
See: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

build: Fix line endings for Windows check-out

---

docs/how/delete-metadata.md
metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/cli/delete_cli.py
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandlerTest.java

This PR is a follow-up to https://github.com/linkedin/datahub/pull/4358 that makes rollback operations, soft-deletes by default.
In particular, this PR updates the cli's `delete` command with an extra parameter (`--include-removed`) that includes soft deleted entities in the search result of the entities to be deleted.

Flexible search on soft delete

---

metadata-ingestion/src/datahub/cli/cli_utils.py

Filtered deletes with `--include-removed` where incorrectly ignoring elasticsearch results where the `removed` field was set to removed=false.
This means that semantically the flag should be called `--soft-deleted` only which is not what we want.
Tested locally that flag know does what we intended, which is to see if the removed property exists, effectively making that property a non-consideration when filtering. The reason we have to do it this way is because in the backend (GMS) we add a filter on removed=true except if there is some condition that references the `removed` property.

feat(cli) Makes filtered search deletes include BOTH removed and non-removed

---

metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
metadata-ingestion/tests/unit/test_schema_util.py

1. Adds coverage for computing the SchemaField type for all AVRO logical types.
2. Fixes a minor bug in the 'logicalType' value retrieval logic.
3. Adds test coverage

fix(ingestion): Fix bug in the SchemaField type computation for AVRO logical types.

---

metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/cli/delete_cli.py

Passing entity properly on deletion
Query filter use platform property properly if paltform instance specified

fix(deletion-cli): Deleting properly containers if platform set

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
metadata-ingestion/tests/integration/tableau/setup/customSQLTablesConnection_all.json
metadata-ingestion/tests/integration/tableau/setup/publishedDatasourcesConnection_all.json
metadata-ingestion/tests/integration/tableau/setup/workbooksConnection_all.json

When there are multiple upstreamDatabases in a datasource, current behaviour is to pick the first database in the list. The fix is to get the database attached directly to upstreamTables.

fix(tableau-multiple-upstreamDatabases): fixed wrong database attach to upstream tables

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

Previously, if there were issues with `connect_uri`, the tableau connector would hit an unbound variable error and the `report_failure` message would never reach the user. This makes the connector not throw a stacktrace but instead report a useful error on issue w/ `connect_uri`.

fix(tableau): gracefully handle issues with connect_uri

---

datahub-web-react/src/app/policy/PoliciesPage.tsx

**Summary**
During the Policies Page redesign, a bug was introduced that causes the privileges granted by a policy to appear incorrectly on the "details" modal that shows when you click the policy. This is a display-only bug and did not affect actual policy enforcement. 
This PR addresses this issue.

fix(ui): Fixing privilege option display bug

---

metadata-ingestion/src/datahub/configuration/time_window_config.py
metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
metadata-ingestion/src/datahub/ingestion/source_config/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source_config/usage/bigquery_usage.py
metadata-ingestion/src/datahub/ingestion/source_report/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source_report/usage/bigquery_usage.py
metadata-ingestion/src/datahub/utilities/parsing_util.py
metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py
metadata-ingestion/tests/unit/test_parsing_util.py
smoke-test/tests/__init__.py

- Problem Scenario fixed for bigquery usage
- A person starts DataHu quickstart at 02:00 PM 16-Mar-2022 UTC for a POC
- They go into bigquery and run some sql to create lineage artificially to test things out
- They run the recipe for bigquery
- EXPECTED RESULT = They go to DataHub UI expecting to see lineage
- ACTUAL RESULT = The DataHub UI shows no lineage because Existing code makes end time = 00:15 AM 16-Mar-2022 UTC
- This scenario would cause people to decide that lineage is broken in bigquery.
- Problem fixed for snowflake usage
- If not base objects accessed then we were not getting any usage for snowflake
- Enhance logging

feat(ingestion): snowflake, bigquery - enhancements to log and bugfix

---

metadata-models/src/main/pegasus/com/linkedin/metadata/key/NotebookKey.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/ChartCell.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/CommonCellAttributes.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/EditableNotebookProperties.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/NotebookCell.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/NotebookCellType.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/NotebookContent.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/NotebookInfo.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/QueryCell.pdl
metadata-models/src/main/pegasus/com/linkedin/notebook/TextCell.pdl
metadata-models/src/main/resources/entity-registry.yml

This PR is to add pegasus schema to model Notebook data entity. RFC: https://github.com/datahub-project/datahub/pull/4237

feat(notebook): add data models for Notebook entity

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

Co-authored-by: Ludmila Ferreira <ludmila.ferreira@elo7.com>
Hello!
We are using Datahub for ingesting metadata from Tableau. We were facing an issue when ingesting some Tableau data sources. The execution was crashing in the middle when data was coming with `None` fields, as shown in the following stack trace: 
```
File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/source/tableau.py", line 570, in emit_datasource
upstream_tables = self._create_upstream_table_lineage(datasource, project)
File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/source/tableau.py", line 257, in _create_upstream_table_lineage
table_urn = make_table_urn(
File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/source/tableau_common.py", line 379, in make_table_urn
final_name = …
```

fix(ingest): add fix to tableau connector when table has None fields

---

datahub-web-react/src/app/entity/mlFeatureTable/profile/MLFeatureTableProfile.tsx
datahub-web-react/src/app/entity/mlModel/profile/MLModelProfile.tsx
datahub-web-react/src/app/entity/mlModelGroup/profile/MLModelGroupProfile.tsx

When we migrated the legacy ml pages to use the shared RoutedTabs component, they did not also receive the `display` methods. The long term fix is to bring the ml model pages onto the new entity page framework, but this will re-enable the tabs for the time being.

fix(ml models): re-enabling ml tabs

---

metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
metadata-ingestion/src/datahub/ingestion/source/usage/redshift_usage.py

fix(redshift) Properly handling database alias in redshift usage and redshift lineage generation

---

metadata-ingestion/setup.py

fix(ingestion): pin Jinja2 to version < 3.1.0

---

datahub-web-react/src/app/entity/group/GroupProfile.tsx
datahub-web-react/src/graphql/group.graphql

fix: Update GroupProfile to read from properties over deprecated info aspect

---

metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py

fix(snowflake-usage): do not ingest stage as a dataaset

---

metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py

Currently we continue querying even if there is no usage data. We should stop early

feat(snowflake): stop querying when no mix/max dates for usage

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/EntityTypeMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/DescriptionUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateDescriptionResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/ChangeAuditStampsMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UrnToEntityMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/notebook/NotebookType.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/notebook/mappers/NotebookMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/notebook/mappers/NotebookUpdateInputMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/notebook/NotebookTypeTest.java
li-utils/src/main/javaPegasus/com/linkedin/common/urn/NotebookUrn.java
li-utils/src/main/pegasus/com/linkedin/common/NotebookUrn.pdl
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

This PR contains the GraphQL related logic for Notebook data entity. 
Please refer to https://github.com/datahub-project/datahub/pull/4237 for more info about Notebook entity
Main changes in this PR:
1. GraphQL schema change in entity.graphql  file
2. new EntityType and Mappers in src/main/java/com/linkedin/datahub/graphql/types/notebook folder
3. necessary changes to hook notebook entity
4. Register NotebookUrn in li-utils module

feat(notebook): graphqul related logic change for notebook

---

datahub-web-react/src/app/policy/PolicyDetailsModal.tsx
datahub-web-react/src/app/policy/PolicyPrivilegeForm.tsx

feat(policy): Add tooltip and view button

---

metadata-ingestion/source_docs/bigquery.md

It's kinda hard to distinguish these when reading the paragraph; using the backticks makes is obvious that these are properties

docs(metadata-ingestion): callout properties in paragraph

---

metadata-ingestion/sink_docs/datahub.md

doc(ingestion): add examples of running in docker and Kubernetes

---

metadata-models/src/main/pegasus/com/linkedin/container/Container.pdl

Adding hasContainer filter to search index in preparation for new browse experience!

feat(ui): Adding hasContainer filter to search index

---

metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py
metadata-ingestion/tests/integration/sql_server/mssql_mces_golden.json
metadata-ingestion/tests/integration/sql_server/mssql_to_file.yml

fix(ingest): working mssql aliases

---

metadata-models/src/main/pegasus/com/linkedin/common/BrowsePaths.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
test-models/src/main/pegasus/com/datahub/test/BrowsePaths.pdl

The doc was a bit confusing, mentioning "backslash-separated strings" when the example is using forward slash. The example seems correct to me so changing the description to use "forward slash".

fix(doc): Change to forward slash-separated strings, as in the example

---

docs/cli.md

doc: clarify CLI releases

---

build.gradle
docs/how/build-metadata-service.md
metadata-ingestion/src/datahub/cli/cli_utils.py

https://github.com/datahub-project/datahub/issues/4461

bug(cli): handle case insensitive entity types for cli delete

---

datahub-web-react/build.gradle
docs-website/build.gradle

I may be able to add a section to https://github.com/datahub-project/datahub/blob/master/docs/developers.md to describe the build process behind a corporate firewall, once I have a successfully working build.

build(ui): Allow custom distBaseUrl

---

metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/BatchIngestionRunResource.java

Rollback affected entities computation was incorrectly considering key aspects & status aspects as affected entities.

fix(rollback) Removes status & key aspects from affected aspects count during rollback

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/lineage/LineageEntityNode.tsx
datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
datahub-web-react/src/app/lineage/types.ts
datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
datahub-web-react/src/app/lineage/utils/constructTree.ts
datahub-web-react/src/app/lineage/utils/layoutTree.ts

We recently introduced the concept of display names in dataset properties.  This is the default title for a dataset on the lineage viz. However, sometimes users may want to see the full dataset title. Clicking "Show Full Titles" now does this.

feat(lineage): show fully qualified dataset name on expansion

---

metadata-ingestion/src/datahub/ingestion/source/lookml.py
metadata-ingestion/tests/integration/lookml/expected_output.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json

Pathlib by default removes the leading `/`, which leads to a trailing `/` being present in file_path after striping repo path.
The trailing `/` eventually causes the looker url to be incorrect.
I.e.:
`base_url//file_path`
to 
`base_url/file_path`

(fix): Update path generated when creating LookML URL

---

metadata-ingestion/setup.py

https://github.com/datahub-project/datahub/pull/3782 introduced a regression due to missing dependencies
https://github.com/datahub-project/datahub/pull/4561 fixed usage sources but missed `bigquery`

fix(bigquery): missing dependency

---

README.md
docker/airflow/local_airflow.md
docker/mariadb/init.sql
docker/mysql-setup/init.sql
docker/mysql/init.sql
docker/postgres-setup/init.sql
docker/postgres/init.sql
docs/rfc/active/4237-datadoc-entity/datadoc-entity-rfc.md
metadata-ingestion/examples/mce_files/bootstrap_mce.json
metadata-ingestion/source_docs/lookml.md
metadata-ingestion/src/datahub/cli/docker.py
metadata-ingestion/tests/integration/mysql/setup/setup.sql
metadata-integration/java/datahub-client/build.gradle
metadata-integration/java/spark-lineage/build.gradle
metadata-models/docs/entities/dataPlatform.md
metadata-models/docs/entities/dataset.md
metadata-models/src/main/pegasus/com/linkedin/identity/CorpGroupEditableInfo.pdl
metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserEditableInfo.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
metadata-service/restli-servlet-impl/src/main/resources/DataPlatformInfo.json
metadata-service/war/src/main/resources/boot/data_platforms.json

#4446 changed some links but not all. This PR change some more references from linkedin to datahub-project.
Updata links for github-related links to point to use datahub-project:
* https://github.com
* https://img.shields.io/github/...
* https://raw.githubusercontent.com/...
Also replace references for github repo linkedin/datahub with
datahub-project/datahub.
Removed a few trailing whitespaces too in some files which I opened in my editor...

fix: replace direct and indirect references to linkedin with datahub-project

---

datahub-web-react/src/app/search/SearchPage.tsx
datahub-web-react/src/app/search/utils/navigateToSearchUrl.ts

Commas are special characters in our url params- they are used to separate array items. We need to escape them or our search query will be treated as an array

fix(search): handle commas in search queries in the UI

---

docker/datahub-gms/env/docker.env
metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/KafkaEventConsumerFactory.java
metadata-service/factories/src/main/resources/application.yml

**Summary**
This change exposes the Kafka Listener concurrency for configuration inside the GMS + MAE consumer pods.

feat(gms): Expose kafka listener concurrency as a GMS setting

---

metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/JavaEntityClientFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/DataHubKafkaEventProducerFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/DataHubKafkaProducerFactory.java

fix(upgrade): Renaming kafka producer since it clashes with spring-internal

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/graphql/dataPlatform.graphql

Adding simple "get data platform by urn" query to GraphQL API.

feat(GraphQL): Add data platform query to GraphQL API

---

datahub-graphql-core/src/main/resources/entity.graphql

We missed the PRE fabric type in GraphQL, adding it here!

fix(graphql): Adding PRE FabricType to GraphQL

---

docs/modeling/extending-the-metadata-model.md
entity-registry/src/main/java/com/linkedin/metadata/models/annotation/SearchableAnnotation.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/MappingsBuilder.java

feat(search) - add DATETIME FieldType

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/DeletePolicyResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/GetGrantedPrivilegesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/UpsertPolicyResolver.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizationConfiguration.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizationRequest.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizationResult.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/Authorizer.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizerChain.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizerConfiguration.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/DefaultAuthorizerConfiguration.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/ResourceSpec.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/AuthorizerChain.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/AuthorizerChainFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/DataHubAuthorizerFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/ConfigurationProvider.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
metadata-service/factories/src/main/resources/application.yml
metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java

**Summary**
In this PR, we introduce support for a configurable Authorizer chain in the metadata service. This allows people to write their own implementation of the Authorizer interface and plug it in so that requests to perform specific actions can be authorized on DataHub using custom approaches. 
**Changes**
- Adding a custom AuthorizerChain component, which internally nests the default DataHub Authorizer as a fixed Authorizer. 
- Supporting configuration of custom Authorizer components inside of application.yml 
**Status**
WIP

feat(metadata-service): Supporting a configurable Authorizer Chain 

---

metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/cli/timeline_cli.py
metadata-ingestion/src/datahub/ingestion/graph/client.py
metadata-ingestion/src/datahub/utilities/urns/urn.py
metadata-ingestion/tests/unit/test_urn.py

Urns for datasources with datasetNameDelimiter: "/" was not encoded
correctly, resulting in REST calls not returning any data when querying
with the urn.

fix: urlencode slash in urns too

---

datahub-frontend/conf/user.props
datahub-web-react/src/graphql/fragments.graphql

Recently, there was a bug introduced which prevents dashboard tags from being rendered properly in the UI, even though they do in fact exist.
This PR fixes that.

fix(ui): Fix dashboard tags display

---

datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/graphql/chart.graphql
datahub-web-react/src/graphql/container.graphql
datahub-web-react/src/graphql/dataFlow.graphql
datahub-web-react/src/graphql/dataJob.graphql
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/glossaryTerm.graphql
datahub-web-react/src/graphql/mutations.graphql
datahub-web-react/src/graphql/preview.graphql
datahub-web-react/src/graphql/search.graphql

- GraphQL queries for fetching deprecation status for each entity type inside the UI. Next: displaying it!
- [] Tests for the changes have been added/updated (if applicable)

feat(ui): Adding GraphQL queries to fetch entity deprecation status

---

metadata-ingestion/source_docs/redshift.md

Redshift ingestion sources throw a permission denied error for the tables added in the PR docs. 
To recreate this issue:
1. Create a user on redshift with no data access.
2. Run - ALTER USER datahub_user WITH SYSLOG ACCESS UNRESTRICTED;
3. Ingest data using cli

fix(docs): add grant statements for redshift-ingestion

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/tests/unit/test_athena_source.py
metadata-ingestion/tests/unit/test_bigquery_usage_source.py
metadata-ingestion/tests/unit/test_clickhouse_source.py
metadata-ingestion/tests/unit/test_druid_source.py
metadata-ingestion/tests/unit/test_hive_source.py
metadata-ingestion/tests/unit/test_ldap_source.py
metadata-ingestion/tests/unit/test_utilities.py

- Tableau source lint was broken as noticed in https://github.com/datahub-project/datahub/runs/5883056028?check_suite_focus=true
- unit tests were incorrectly marked as integration. Noticed yesterday by @rslanka and me during a PR review

chore: fix lint and remove incorrect integration mark from unit tests

---

docs/cli.md

doc(cli): add env variables and options for ingest command

---

metadata-ingestion/setup.py

Pytest docker introduced a breaking change by adding an additional non-default parameter to method calls. (https://github.com/avast/pytest-docker/commit/875aee38c99a83f5362b1afa236c6710a725ad39#diff-2b5692d86e8853b3342a3c71d5447bb217a829e3302e857ceb37ff831422279dL162) 
In this fix I'm setting max/min version for this package

fix(ingest): Restricting pytest docker version to <0.12

---

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java

Currently, everytime mappings or settings for a given entity updates, we reindex the whole search index. This has led to us reindexing huge indices every time a new searchable field has been added to the model. This is very unnecessary.
There have been two sources of diffs
a) a new searchable field causes mappings diff
b) a new entity causes changes in urn stop filters (which adds the list of entities to the list of stop words to remove when indexing urns)
This PR aims to make sure we do not reindex on the above two cases. Reindex will only happen when a mappings for an existing field needs to change.

feat(search): Only reindex if the mappings for an existing field changed

---

metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/DataHubKafkaProducerFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/KafkaEventConsumerFactory.java

This fixes an issue where registry SSL properties as described in https://datahubproject.io/docs/how/kafka-config/#schema-registry were being overwritten by empty ones for MCE and MAE consumers.

fix(kafka): Stop overriding kafka registry props with empty values

---

metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py

Sometimes the report does not get printed which makes it hard to debug problems. This should help with that.

fix(ingestion): ensure source/sink reports are always logged

---

metadata-ingestion/src/datahub/emitter/mce_builder.py
metadata-ingestion/src/datahub/ingestion/api/common.py
metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/DatasetUrnNameCasingFactory.java
metadata-service/servlet/src/main/java/com/datahub/gms/servlet/Config.java

This is an experimental temporary workaround for deployments starting fresh to get all dataset urns to use lower-casing for the names, if the environment variable `DATAHUB_DATASET_URN_TO_LOWER` is set to `true` either on the client or server side.
NOTE: Existing deployments would run into issues if this is set, before we ship a migration script that needs to run first.

feat(ingestion): Enable lower-casing of the name part of dataset urn if env variable is set.

---

datahub-web-react/src/app/search/BrowseEntityCard.tsx
metadata-io/src/main/java/com/linkedin/metadata/search/SearchService.java
smoke-test/tests/cypress/cypress/integration/home/home.js
smoke-test/tests/cypress/example_to_datahub_rest.yml

Added smoke tests to make sure this issue does not happen again.

fix(home): Fix issue where some browse cards are missing

---

metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
metadata-ingestion/src/datahub/ingestion/source/kafka.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

Noticed this when running `kafka` source. Then checked the original PR https://github.com/datahub-project/datahub/pull/4496 by @shirshanka and noticed the same problem in `sql_common`. So fixed that too. Should help a bit during debugging.
As this is log in reporting tests are not applicable in my opinion.
- https://github.com/datahub-project/datahub/pull/4496

fix(ingestion): add missing workunit ids

---

metadata-ingestion/setup.py

https://github.com/datahub-project/datahub/pull/4441 broke `bigquery-usage` in the case where `bigquery` plugin is not installed too. This fixes that problem.

fix(bigquery-usage): missing dependency

---

datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/app/search/SearchBar.tsx
datahub-web-react/src/graphql/search.graphql

Defaults fqn to `name` if fqn is unavailable, rather than displayname.

feat(autocomplete): show fully qualified name in autocomplete

---

datahub-web-react/src/app/identity/ManageIdentitiesPage.tsx
datahub-web-react/src/app/shared/RoutedTabs.tsx

Worked on the relative Routing on the Users & Groups screen
- /identities/users (DEFAULT)
- /identities/groups

Added Relative Routing on the Users & Groups screen

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
datahub-graphql-core/src/main/resources/app.graphql
datahub-web-react/README.md
datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/search/SearchHeader.tsx
datahub-web-react/src/appConfigContext.tsx
datahub-web-react/src/graphql/app.graphql
metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/VisualConfigFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
metadata-service/factories/src/main/resources/application.yml

Allows deployers of datahub to customize the homepage and header bar logo via env var.

feat(theming): set custom logo without rebuilding

---

metadata-service/auth-api/src/main/java/com/datahub/authorization/AuthorizedActors.java
metadata-service/auth-api/src/main/java/com/datahub/authorization/Authorizer.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/AuthorizerChain.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java

This function fetches all actors that have been granted the input privilege. 
Implement a merging logic of authorized actors in the AuthorizationChain, where we get the greatest common denominator of all actors.

refactor(authorization): Add authorizedActor function to Authorizer interface

---

docs/how/auth/add-users.md

Include the following in add users doc:
1. Way to change the default datahub user
2. FAQ
3. Update outdated info about searching for custom users.

fix(docs): Improving Add Users Doc

---

datahub-web-react/src/app/entity/shared/containers/profile/header/AddDeprecatedDataModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/AddDeprecationDetailsModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx

Added a button to "deprecate" an entity from inside of the UI from the following entity profile page: dataset, chart, dashboard, data flow, data job, container, glossary term

Deprecate an entity

---

metadata-integration/java/datahub-client/build.gradle

This fix will prevent running metadata-io:test and metadata-integration:java:datahub-clinet:test. This is supposed to fix the issue of datahub-client test failing intermittently

fix(datahub-client): avoid parallel execution of metadat-io:test

---

metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java

What was observed was in case of Postgres Connector for Ebean there seems to be an issue with the `Groupby` causing all aspect, version pair to be returned from the query.
One of the options that was discussed with @jjoyce0510 was to upgrade the ebean dependency from 11.33.3 to the latest versions. 
But, in any case to ensure ordering of the results from the Database added an `orderBy(version)` to resolve the issue in Postgres that we are facing now.
For Discussions in Slack - https://datahubspace.slack.com/archives/CUMUWQU66/p1650039418187819

fix(gms): Ensure Ordering by version when fetching next version

---

metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java

Title explains. No logic changes.

refactor(gms): EbeanAspectDao - make the orderBy clause explicitly ascending in getNextVersions

---

metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py
metadata-ingestion/tests/unit/test_utilities.py

- Fixes https://github.com/datahub-project/datahub/issues/4692

fix(bigquery): error due to not handling data properly

---

metadata-ingestion/src/datahub/ingestion/source/looker.py
metadata-ingestion/src/datahub/ingestion/source/lookml.py

Fix for pydantic validation error for Looker TransportOptions on python 3.8
Previously we used TransportOptions directly in our configs which used typing.TypedDict on python 3.8 and this caused Pydantic validation to fail.
This is how it looked like on python 3.8
```
============================================================================================= short test summary info ==============================================================================================
FAILED tests/integration/looker/test_looker.py::test_looker_ingest - TypeError: You should use `typing_extensions.TypedDict` instead of `typing.TypedDict` with Python < 3.9.2. Without it, there is no way to di...
FAILED tests/integration/looker/test_looker.py::test_looker_ingest_joins - TypeError: You should use …
```

fix(looker): Fix for Pydantic validation error for Looker TransportOptions on python 3.8

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py

Moving bigquery temporary credential deletion to atexit vs __del__ because it is more reliable and deterministic.
Recently with __del__ it threw an error because the logging object was None as it seemed to be cleaned up when the method was called.

fix(ingest) bigquery: Moving bigquery temporary credential deletion to atexit

---

datahub-web-react/src/app/lineage/LineageExplorer.tsx

When the width of a screen is small or an entity has enough path crumbs so that the browse path in the entity profile nav bar is wide enough to push content in this nav bar onto a second line, this second line gets covered up by the `EntityDrawer` that pops out from the left.
Since the `EntityDrawer` is an abolsutely positioned element and there's no easy way to contain it within its parent, we have to set the distance from the top of the page. In order to make this more dynamic for varying heights of `EntityProfileNavBar` I'm setting an empty div above the drawer and a ref on that div to get the `offsetTop` of it so we know how far to push down the drawer.
Here's the issue before the fix:
Here it is after the fix:
And it still looks good when it's only on one line:

fix(lineage): Fix lineage entity drawer height UI bug

---

datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx
datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
datahub-web-react/src/app/entity/mlFeature/MLFeatureEntity.tsx
datahub-web-react/src/app/entity/mlFeatureTable/MLFeatureTableEntity.tsx
datahub-web-react/src/app/entity/mlModel/MLModelEntity.tsx
datahub-web-react/src/app/entity/mlModelGroup/MLModelGroupEntity.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx

**Summary**
In this PR, we limit the newly added "Deprecate" button to specific entity pages, including:
- Datasets, dashboards, charts, data jobs, data flows, glossary terms, and the ML related entities.
Previously, this button was shown on every entity profile. Only certain entities support deprecation, so this was a bug!

fix(ui): Show deprecate button only for specific entity pages. 

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeatureTablePropertiesMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/app/entity/mlFeatureTable/MLFeatureTableEntity.tsx
datahub-web-react/src/graphql/fragments.graphql
smoke-test/tests/cypress/cypress/integration/ml/feature_table.js

Adds the properties tab to MLFeatureTable, which is quite handy to add custom metadata that does not fit with the actual model.

feat(ml): show custom properties for MLFeatureTable in UI

---

metadata-ingestion/scripts/codegen.sh
metadata-models/src/main/pegasus/com/linkedin/mxe/MetadataChangeProposal.pdl

Adding a few new AVSC schemas to python code gen so they are published.

minor fix(metadata-ingestion): Add new schemas to python codegen

---

datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx

Makes two small updates (you can view them separately by commit):
1. Removes the link that was around the entity name (Gabe heard that it was unexpected and annoying, as well as redundant for the non-compact mode)
2. Rearrange some elements in the `EntityHeader` so that when there is an external URL button for the entity as well as multiple other things on the top line in the compact view, things don't look janky. Now, the external URL button is below the copy button and the menu dropdown button. Also added an arrow to the button (as per suggested by John).
I also noticed that things look weird if everything that could get rendered on the top of the entity header is indeed rendered (including entity count) so I added a little old `flex-wrap: wrap;` so things slide to a new line if …

fix(entity header): Fixes two issues in the EntityHeader - update UI and remove link

---

metadata-ingestion/src/datahub/cli/timeline_cli.py

This reverts commit 7bcc2d9f62a7513b8bd8bc74d6eea0c85f07e245 due to server-compatibility concerns.

Revert "fix(timelineCli): fix naming for timeline cli (#4729)"

---

docs-website/sidebars.js
docs/lineage/airflow.md
metadata-ingestion/README.md
metadata-ingestion/integration_docs/great-expectations.md
metadata-ingestion/src/datahub/entrypoints.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py
metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
metadata-ingestion/tests/unit/test_pipeline.py
metadata-integration/java/datahub-protobuf/README.md
metadata-integration/java/spark-lineage/README.md

feat(cli): suppress stacktrace printing on configuration errors

---

datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/search/SearchHeader.tsx

feat(react theming): stop homepage flicker for env-var based logos

---

metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
metadata-ingestion/tests/integration/azure_ad/azure_ad_nested_groups_members.json
metadata-ingestion/tests/integration/azure_ad/test_azure_ad.py

Previous code was failing on AD object types other than user and group, now silently skipping those.  As for what Datahub is expecting from this source, probably only users and groups have value.
Unit test has been updated to make sure it is not failing anymore.
This PR is fixing issue #4693 .

fix(azure_ad): silently discard other Azure AD object types (#4693)

---

metadata-service/factories/build.gradle
metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/LocalEbeanServerConfigFactory.java
metadata-service/factories/src/main/resources/application.yml

We've seen various scaling issues lately due to the number of open connections to the local DB. First, add metrics to track the number of open connections.

feat(ebeans): Add metrics to track connection pool

---

datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx

In absence of  `datasetProperties.qualifiedName`, fallback to  `datasetProperties.name`
If name absent in datasetProperties, fallback to name from dataset urn
The earlier behavior works fine for platforms using qualified name as identifier for dataset urn. However this does not work properly for platforms (e.g. tableau) which use pure guid-based identifier for dataset urn.

fix(ui): fix expandedName for dataset

---

datahub-web-react/src/app/entity/group/GroupInfoSideBar.tsx
datahub-web-react/src/app/entity/group/GroupMembersSideBarSection.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/AddOwnerModal.tsx

- Groups side bar title and member section css fixes 
- Groups side bar- member section tags css breaking, fixed with the character limit and full name will be shown on hover of tag(if the name is long, else only shown the original tag).
- Add owner modal -> When user opens the add owner modal, the value added by default type selected with the first value.
@jjoyce0510 @chriscollins3456

fix(ui): Users and Groups UI bug fixes

---

ingestion-scheduler/src/main/java/com/datahub/metadata/ingestion/IngestionScheduler.java
ingestion-scheduler/src/test/java/com/datahub/metadata/ingestion/IngestionSchedulerTest.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeLogProcessor.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/ingestion/IngestionSchedulerHook.java
metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/ingestion/IngestionSchedulerHookTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/ingestion/IngestionSchedulerFactory.java
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java

**Summary** 
For UI ingestion we periodically refresh all of the scheduled ingestion sources to make sure schedules are all up to date. Previously, doing this only updated the schedules that were explicitly found in the DB. The result is that if an ingestion source failed to clear previously (e.g. missed message) then it will continue to run indefinitely. 
Additionally, this fixes a bug where Deletes are failing to reflect immediately due to a bad assumption on a deleted aspect coming through to the Ingestion Scheduler. This PR makes the ingestion scheduler hook more amenable to entity-level deletes. 
This change unschedules all ingestion sources when we refetch them periodically. It also increases the default refresh freq to 2x per day.

fix(ui ingest): Unschedule all sources on ingestion source refresh, fix delete not being enforced

---

docs/policies.md

**Summary**
Fixing an outdated doc which refers to the slide out control-center menu (replaced by top nav).

fix(docs): Fixing outdated control-center doc on policies.md

---

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/shared/tags/TagTermGroup.tsx

fix(ui): update default preview component with new ui design
@jjoyce0510

fix(ui): update default preview component with new ui design

---

metadata-ingestion/tests/integration/presto-on-hive/test_presto_on_hive.py

Fix failing tests in test_presto_on_hive.
Root-cause: Since the `scheme` field of the config is now excluded, the way the test is building the pipeline config would drop the scheme in the dict() call causing the it to pickup the default value(`mysql+pymysql`), instead of what is being specified in the test(`postgresql+psycopg2`), which lead to an incorrect SQLAlchemyURL for the tests causing the test failures.

fix(ingestion): Fix presto_on_hive tests.

---

datahub-web-react/src/app/entity/shared/components/styled/StripMarkdownText.tsx
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/search/SearchResults.tsx

- fix(ui): update default preview card description text
@jjoyce0510 @chriscollins3456

fix(ui): update default preview card description text

---

datahub-web-react/src/app/search/SearchResults.tsx

Always display the separator between filters and search results by adding a separating div so content can always grow to its full amount.

fix(search) Fixes a UI issue so results and filters are always separated

---

build.gradle

fix(build) Bumps hadoop-client to 3.2.1 with no security vulnerability

---

docs/deploy/aws.md

Adding documentation in the main regarding how to enable auth for the metadata services and some clarifications regarding the frontend service. This would make the installation easier and the documentation centralized in the main guide.

fix(docs): fix the metadata service auth documentation and frontend clarifications

---

metadata-ingestion/archived/source_docs/kafka.md
metadata-ingestion/docs/sources/kafka/kafka.md
metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/extractor/protobuf_util.py
metadata-ingestion/src/datahub/ingestion/source/confluent_schema_registry.py
metadata-ingestion/tests/unit/test_protobuf_util.py

feat(ingestion): Protobuf support for the Kafka source

---

build.gradle
metadata-integration/java/datahub-client/scripts/check_jar.sh
metadata-integration/java/spark-lineage/build.gradle
metadata-integration/java/spark-lineage/scripts/check_jar.sh

Constraining jackson-databind library to 2.13.2.2 to ensure that this vulnerability is addressed: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518

refactor(deps): Bump jackson-databind 2.13.2.2

---

docs/policies.md

Adds documentation on data hub's access policy and the existing set of permissions that exist.

fix(docs): Adds access policy documentation

---

datahub-web-react/src/app/entity/EntityRegistry.tsx

We already hide these entities in the lineage viz, this also hides them in the tab

fix(lineage): hide soft deleted entities in lineage

---

metadata-events/mxe-avro-1.7/build.gradle
metadata-io/build.gradle

Upgrades Velocity to remove vulnerabilities CVE-2020-13936 & CVE-2020-13959

fix(velocity): prevent velocity 1.7 from coming through and use 2.3

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestPoliciesStep.java

Fixes issue where policies are not added to the index on a fresh install.

fix(policies): change order of operations for policies bootstrap step to update index after database

---

build.gradle
docker/datahub-gms/Dockerfile
metadata-integration/java/spark-lineage/README.md
metadata-service/war/build.gradle

This reverts commit 1697bd0641bac248a72ed289bbbcf17c20b2f5a4.

Revert "fix(jetty): upgrade jetty dependency for CVE (#4838)"

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

This PR allows profiling of only those tables that are allowed by both the table_pattern and the profile_pattern.

fix(ingestion): Allow profiling of only those tables that are allowed by the table_pattern.

---

metadata-ingestion/docs/sources/elastic-search/elasticsearch_recipe.yml
metadata-ingestion/examples/recipes/elasticsearch_to_datahub.yml
metadata-ingestion/src/datahub/ingestion/source/elastic_search.py

feat(elasticsearch source): add ability to pass ssl config parameters
Added ssl config parameters to ElasticsearchSourceConfig. Mostly taken from [Urllib3HttpConnection](https://elasticsearch-py.readthedocs.io/en/7.x/connection.html#elasticsearch.Urllib3HttpConnection), these are passed to the ElasticSearch native client.

ssl configuration support for elasticsearch source

---

metadata-ingestion/setup.py

Downgrading typing-extension dependency to work with Airflow 2.0.2
Normally we need typing-extension >=3.10.0.2 but it clashes with Airflow 2.0.2 and we have say we are fine with a lower version which is not true but typing only needs for compilation time (if we can say this at Python :))  and hoping who runs mypy and other typing check has actually a higher version.
This hack should solve the Airflow issue and until the user has >=3.10.0.2 on his machine it will be fine for the static checks as well.
```
The conflict is caused by:
apache-airflow[cncf-kubernetes] 2.0.2 depends on typing-extensions>=3.7.4; python_version < "3.8"
acryl-datahub 0.8.33 depends on typing-extensions>=3.10.0.2
The user requested (constraint) typing-extensions==3.7.4.3
```

fix(ingestion): dependencies - Downgrading typing-extension dependency to work with Airflow 2.0.2

---

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/search/SearchFilter.tsx
datahub-web-react/src/app/search/utils/constants.ts

- Search filter ui update, added the '+ more' for Types, Sub types and Platform.
- SearchFitler.tsx -> styled component added
- Entity Card -> added the space  between the title and description
@chriscollins3456 @jjoyce0510

fix(ui): search filter entity ui update

---

metadata-ingestion/scripts/docgen.py

fix(docs): ingest - sort modules, fix small typos

---

docs/how/updating-datahub.md
metadata-ingestion/src/datahub/ingestion/source/lookml.py
metadata-ingestion/tests/integration/lookml/expected_output.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json

Previously, we were only populating view definitions for derived tables in looker views. 
This PR:
1. expands this to all views (lookml / sql views)
2. removes the population of custom_properties with file contents to avoid duplicate information being stored
3. adds a config variable to control the number of characters from the view file that are stored in the view definition

fix(ingest): lookml - add view definitions for all views

---

metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
metadata-ingestion/tests/unit/test_elasticsearch_source.py

When there's no properties (schema) from the index, it raises ValueError.
However, it's usual that we can have empty schema index.
This PR makes the pipeline gracefully continue when there's an index with no schema.

fix(ingestion): ElasticSearch when no properties from elastic_mappings, gracefully continue

---

metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MaeConsumerApplication.java
metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MceConsumerApplication.java

Cassandra beans were getting instantiated in the consumers when Cassandra isn't even the configured entity store. Excluding `CassandraAutoConfiguration` should fix it.
fixes #4770

fix: exclude CassandraAutoConfiguration from consumer boots

---

datahub-web-react/package.json
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/ProfileSidebarResizer.tsx
datahub-web-react/yarn.lock

The SplitPane component used to implement sidebar resize logic was a bit hard ton work with an inexplicably created scenarios where the right sidebar would render partially offscreen that were hard to debug. I simplified the resize logic and removed our dependency on the SplitPane package.

fix(entity page): fix sidebar resize logic

---

metadata-ingestion/setup.py

Continuation of https://github.com/datahub-project/datahub/pull/4779. Breaking changes are affecting Python 3.9 too

fix(build): Fix breaking changes from GE 0.15.3

---

docs-website/docusaurus.config.js
docs-website/src/components/Hero.js
docs-website/src/styles/global.scss
docs-website/src/styles/hero.module.scss

docs(website): add banner and nav item for metadata day 2022

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/container/ParentContainersResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/container/ParentContainersResolverTest.java
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
datahub-web-react/src/app/entity/container/ContainerEntity.tsx
datahub-web-react/src/app/entity/container/preview/Preview.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dashboard/preview/DashboardPreview.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/dataset/preview/Preview.tsx
datahub-web-react/src/app/entity/shared/containers/profile/__tests__/PlatformContent.test.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityCount.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/ContainerLink.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentContainer.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/index.ts
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/app/entity/shared/utils.ts
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/search/SearchBar.tsx
datahub-web-react/src/graphql/chart.graphql
datahub-web-react/src/graphql/container.graphql
datahub-web-react/src/graphql/dataset.graphql
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/search.graphql

There are 2 main parts to this PR, the backend and the frontend changes.
**backend**
Creates a custom resolver in order to recursively get all parent containers for a given entity. We will be sending back a list in order from direct parent container then that container's container etc. This new field is called `parentContainers`.
**frontend**
Now get all parent containers on the frontend to display on the entity page and the entity search result card. We now show the path of containers all the way and will truncate this path by cutting off the highest level containers first (so you can always see your direct parent container). The platform content at the top of the entity page and search result card has been refactored so now it looks like this:
`Subtype | [logo] Platform > instanceId > …

feat(containers) Get and display all parent containers in header and search

---

docker/docker-compose-with-cassandra.yml
docker/docker-compose-without-neo4j.yml
docker/docker-compose.yml
docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
docker/quickstart/docker-compose-without-neo4j.quickstart.yml
docker/quickstart/docker-compose.quickstart.yml

In this PR, we migrate the use the newly published [datahub-actions](https://hub.docker.com/r/acryldata/datahub-actions) container (published as part of the public [DataHub Actions](https://github.com/acryldata/datahub-actions) repository).
The configurations (env variables) should be compatible with what exists in current actions image.

refactor(actions): Migrate to use new datahub-actions container

---

metadata-ingestion/examples/transforms/custom_transform_example.py
metadata-ingestion/transformers.md

Added superclass init statement in constructor, which takes care of initialising fields like self.entity_map that are used later when applying transformation.
Earlier, one used to get this error
```
File "/python3.9/site-packages/datahub/ingestion/transformer/base_transformer.py", line 252, in transform for urn, state in self.entity_map.items():
AttributeError: 'AddCustomOwnership' object has no attribute 'entity_map' 
```

docs(transformer): fix custom transform example

---

datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx

Makes a few CSS tweaks to clean up the spacing and alignment of different elements on the entity header and search card.
First, properly align the platform icon
Before:
After:
Here's the search results with entities that have different things on their cards:

fix(ui) Fix some spacing issues on the search card

---

metadata-integration/java/spark-lineage/build.gradle
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatahubSparkListener.java
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatasetExtractor.java
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/model/dataset/CatalogTableDataset.java

This PR:
1. support spark sql to get data from iceberg and write data to iceberg
2. support spark sql to get data from cached data in memory
3. support spark sql to get cached data after complex operations like join, filter, union and so on

to support more spark commands

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/ListDomainsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/ListGroupsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/secret/ListSecretsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourcesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/ListPoliciesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/user/ListUsersResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/main/resources/ingestion.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/domain/ListDomainsResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/secret/ListSecretsResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/source/ListIngestionSourceResolverTest.java
datahub-web-react/src/app/domain/DomainsList.tsx
datahub-web-react/src/app/identity/group/GroupList.tsx
datahub-web-react/src/app/identity/user/UserList.tsx
datahub-web-react/src/app/ingest/secret/SecretsList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/policy/PoliciesPage.tsx
datahub-web-react/src/app/search/SearchBar.tsx
metadata-models/src/main/pegasus/com/linkedin/policy/DataHubPolicyInfo.pdl
metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyFetcher.java
metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java

**Summary**
In this PR we add search bars to all list views in the UI.
**Status**

feat(ui): Adding Search Bar to all List Views (groups, users, domains, policies, ingestion)

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddOwnerResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddOwnersResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddTagsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddTermResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddTermsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/LabelUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/OwnerUtils.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/owner/AddOwnersResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/tag/AddTagsResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/term/AddTermsResolverTest.java
smoke-test/tests/containers/data.json

**Summary**
In this PR, we add 3 new mutations + 3 new resolvers and the corresponding tests. These enables clients to add multiple tags, glossary terms, and owners to a resource at one time.
**Status**

feat(graphql): Adding resolvers for adding multiple tags, terms, and owners

---

datahub-graphql-core/src/main/resources/entity.graphql

These fields were in `.pdl` but previously not also represented in gql.

fix(gql): make graphql OperationType enum match up w/ pdl

---

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_schema_tags.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_schema_terms.py
metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py
metadata-ingestion/tests/unit/test_transform_dataset.py
metadata-ingestion/transformers.md

Config examples:
```
transformers:
- type: "pattern_add_dataset_schema_terms"
config:
term_pattern:
rules:
".*email.*": ["urn:li:glossaryTerm:Email"]
".*name.*": ["urn:li:glossaryTerm:Name"]
```
and
```yaml
transformers:
- type: "pattern_add_dataset_schema_tags"
config:
tag_pattern:
rules:
".*email.*": ["urn:li:tag:Email"]
".*name.*": ["urn:li:tag:Name"]
```

feat(transformers): add transformers to provide tags & terms to schema fields based on regex patterns

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

For some cases we are getting "No BigQuery dataset specified. Please specify a default dataset in engine url" from GE for BigQuery when profiling coming from https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/sqlalchemy_dataset.py#L640. This sets the `dataset_id` field for `bigquery`

fix(bigquery): add dataset_id for bigquery for profiling

---

metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatahubSparkListener.java
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatasetExtractor.java
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/model/dataset/CatalogTableDataset.java

Reverts datahub-project/datahub#4882 because it seems to break spark 3 compatibility

Revert "to support more spark commands"

---

datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceExecutionList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx

This PR fixes #4921 by hiding the copy URN buttons when they do not work anyway because the Clipboard API is not available (e.g. in an insecure context or when using an incompatible browser).

fix(ui): do not show copy URN buttons when Clipboard API is not available

---

metadata-ingestion/sink_docs/datahub.md

docs(datahub-kafka-sink): add topic_routes config to doc of datahub-kafka-sink

---

docs-website/docusaurus.config.js
docs-website/src/components/Hero.js
docs-website/src/components/HeroAnnouncement.js
docs-website/src/styles/global.scss
docs-website/src/styles/hero-announcement.module.scss

Removes banner and nav item. Also moves code into a component so we can easily re-add announcements in the future.

docs(website): Remove banner and nav item for metadata day 2022

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/dataset/profile/UsageFacepile.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Dataset/StatsSidebarSection.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/TableStats.tsx
datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/lineage/LineageEntityNode.tsx
datahub-web-react/src/app/lineage/LineageExplorer.tsx
datahub-web-react/src/app/lineage/LineageTree.tsx
datahub-web-react/src/app/lineage/LineageTreeNodeAndEdgeRenderer.tsx
datahub-web-react/src/app/lineage/LineageVizInsideZoom.tsx
datahub-web-react/src/app/lineage/types.ts
datahub-web-react/src/app/search/SearchBar.tsx
datahub-web-react/src/app/search/SearchFilter.tsx
datahub-web-react/src/app/search/SearchFilters.tsx
datahub-web-react/src/app/search/SearchHeader.tsx
datahub-web-react/src/app/search/__tests__/SearchPage.test.tsx
datahub-web-react/src/app/shared/ManageAccount.tsx
datahub-web-react/src/app/shared/admin/AdminHeaderLinks.tsx

Fixes four different usability issues we've heard about in the UI. This PR might be easiest to review by commit as each one fixes its own issue. One of the four issues is broken into two commits (same issue, different places). 
Here are the issues and fixes broken down by commit:
1. Limit number of users for the "Top Users" on entity profiles. Previously we just showed all of the users that interacted with a dataset, but now we pass in a prop to limit the number of users we show, and for this situation let's limit it to 10 (who needs to see their top 43 users?)
2. Users were experiencing issues with the search bar being too small as important parts of their search results were getting cut off in the drop down. So commit 2 simply increases the size of the search bar on the home page.
3. …

fix(UI) Fix multiple UI usability issues

---

metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/TelemetryUtils.java
smoke-test/smoke.sh
smoke-test/tests/telemetry/telemetry_test.py

fix(telemetry): fix hardcoded aspect name and cover errors when producing MAE

---

metadata-ingestion/src/datahub/ingestion/source/redash.py

I tested calling the Redash endpoint with dashboard_id instead of slug and it responded with dashboard info. This should not be happening as per the API docs https://redash.io/help/user-guide/integrations-and-api/api but the actual behavior is different. Using the ID as fallback because the original change must have been tested with some version of Redash.

fix(redash): use dashboard id if slug does not work

---

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

fix(ingest): remove new schema field usage

---

metadata-ingestion/scripts/docgen.py
metadata-ingestion/src/datahub/ingestion/source_config/bigquery.py
metadata-ingestion/src/datahub/ingestion/source_config/usage/bigquery_usage.py

- default `False` was being turned into `None` because of the or conditions
- broken bigquery doc generation
- fix typo in bigquery docs
before
after PR

doc(ingestion): default boolean fix, broken bigquery docgen

---

metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/ESSystemMetadataDAO.java
metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataService.java
metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/SystemMetadataService.java
metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataServiceTest.java
metadata-models/src/main/pegasus/com/linkedin/metadata/run/AspectRowSummary.pdl
metadata-service/restli-api/src/main/idl/com.linkedin.entity.runs.restspec.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/BatchIngestionRunResource.java
metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java

Create a describe endpoint on BatchIngestionRunResource to fetch details about the run. In the process, expose the paging capabilities of elasticsearch (which powers the underlying system metadata service). 
Add a includeAspects flag, which if set returns the actual aspects that were ingested in the run. 
Modify the `datahub ingestion show` cli command to use the new endpoint. When -a / --show-aspects option is set, return the resulting aspect row summaries in json format.

feat(run): Create a describe run endpoint for fetching aspects created by the ingestion run

---

datahub-graphql-core/src/main/resources/entity.graphql
metadata-ingestion/examples/library/dataset_schema.py
metadata-models/src/main/pegasus/com/linkedin/common/OperationType.pdl
metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json

This PR
- adds optional `created`, `lastModified` auditStamps to `SchemaField`  in order to capture who added/updated the field in dataset and exactly when. Earlier field level timestamp details were not captured at model level.
- adds `ALTER` to `operationType` enum to represent operations on dataset as a result of ALTER TABLE to add/update fields or add/update table properties. Earlier, one could use less meaningful `UNKNOWN` operationType.
-  updates descriptions in graphql for operationTypes representing table level operations.

feat(model): add created, lastModified auditstamps to SchemaField

---

metadata-ingestion/src/datahub/emitter/rest_emitter.py
metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
metadata-ingestion/src/datahub/ingestion/source/dbt.py

feat(dbt): enable dbt read artifacts from s3

---

docs/api/graphql/token-management.md

Fixes documentation around v2 access tokens which references incorrect parameters & output field names.

fix(docs): Fixes token docs

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/operation/ReportOperationResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/OperationMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/operation/ReportOperationResolverTest.java
metadata-ingestion/tests/integration/bigquery-usage/bigquery_usages_golden.json
metadata-ingestion/tests/integration/redshift-usage/redshift_usages_filtered_golden.json
metadata-ingestion/tests/integration/redshift-usage/redshift_usages_golden.json
metadata-models/src/main/pegasus/com/linkedin/common/Operation.pdl
metadata-models/src/main/pegasus/com/linkedin/common/OperationSourceType.pdl
metadata-models/src/main/pegasus/com/linkedin/common/OperationType.pdl
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

**Summary**
In this PR, we add a new GraphQL mutation for reporting Dataset operations (inserts, updates, and more). 
We also extend the existing Operation model with some additional fields. 
**Changes**
- New ReportOperationResolver, corresponding test
- Adding custom properties, source type, and more to operation aspect
- Updates to entity.graphql correspondingly.
**Status**

feat(DataHub Operations): Adding GraphQL mutation for reporting Dataset operations

---

metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/DataHubTokenServiceFactory.java

StatefulTokenService was not getting correctly initialised in GMS due to a typo on the configuration for the salt leading to inconsistent hashing logic.

fix(gms): Fix incorrect StatefulTokenService init

---

metadata-ingestion/setup.py

https://github.com/datahub-project/datahub/pull/4935 introduced dependency on aws from dbt. But it was not in setup.py so dbt connector installed standalone will fail

fix(dbt): missing aws dependency

---

metadata-ingestion/docs/sources/pulsar/pulsar.md

Fixes the existing pulsar documentation, removing redundant sections in alignment with the new documentation style.

fix(ingestion): Fix pulsar source docs.

---

metadata-ingestion/src/datahub/configuration/config_loader.py
metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/src/datahub/ingestion/source/s3/config.py
metadata-ingestion/src/datahub/ingestion/source/s3/source.py

fix(ingestion): use raw strings for regexes

---

metadata-ingestion/setup.py
metadata-ingestion/tests/integration/hana/test_hana.py
metadata-ingestion/tests/unit/test_hana_source.py

This PR fixes the build failure for the hana connector when the machine architecture is `aarch64` by preventing installation of the plugin and skipping the tests.

fix(build): Fix for hana build failure for aarch64.

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source_report/sql/bigquery.py

Report shows the info
Info still has the tag
This was added in https://github.com/datahub-project/datahub/pull/4974

fix(bigquery): reduce number of calls for details of partitioning

---

metadata-ingestion/setup.py

Prevent m1 users from running into issues when they run ./gradlew :metadata-ingestion:installDev.

fix(ingestion): Remove hana from base_dev_requirements to unblock m1 users.

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json

We should be always setting platform_instance: none on sources. Verified golden_file now has correct urns for sources.

fix(dbt): dont set platform instances for sources

---

docs/how/delete-metadata.md
metadata-ingestion/src/datahub/cli/cli_utils.py

If we pass env then container are not detected in the cli.

fix(cli): don't use env for container, add example

---

metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
metadata-ingestion/tests/unit/test_schema_util.py

Fixes the nullability determination for the AVRO fixed type.

fix(ingestion): Fix nullability determination for the AVRO fixed type.

---

docs/quickstart.md

Docker-compose 2.x will not work with the current version of the app. Specifying V1 on the getting started guide to avoid compatibility errors

Specify docker-compose version to avoid compatibility issues

---

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/event/EntityChangeEventGeneratorHook.java
metadata-models/src/main/pegasus/com/linkedin/events/metadata/ChangeType.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json

**Summary**
Currently we use the normal UPSERT change type in MCLs produced from running the restore indices job. This change introduces a new RESTORE change type and modifies restore indices / corresponding hooks to recognize only those events with a specific type.

fix(restore indices): Add RESTATE ChangeType to MCL / MCP to permit restore indices

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestPoliciesStep.java

fix(policies): Remove exception on ingest policies

---

build.gradle
datahub-frontend/app/server/CustomAkkaHttpServer.scala
datahub-frontend/conf/application.conf
datahub-frontend/play.gradle
datahub-frontend/run/frontend.env

This PR allows us to override the frontend's Akka HTTP server with a custom DataHub specific instance. This allows us to override Akka HTTP server settings such as the max header count (which currently isn't possible with our versions of Play + Akka). This is useful when we're trying to configure the DataHub frontend to talk to GMS using proxies like envoy. These proxies often add additional headers which often results in the frontend rejecting GMS responses as they exceed the allowed max header limits of 64.

feat(frontend): Allow overriding frontend with a custom akka http server

---

.github/workflows/check-datahub-jars.yml
metadata-integration/java/datahub-client/src/main/java/datahub/client/Emitter.java

feat(ci): add workflow to check jars are ready for publish

---

metadata-ingestion/src/datahub/ingestion/source/redash.py

- Add parallelism support for ingestion
- fix removing all dataset as inputs in case there was any parsing issue
- cleanup logging
- add timing for various parts

feat(redash): add parallelism support for ingestion

---

docker/mysql-setup/init.sh

Mysql setup job is given with a port override to use from helm charts but the job itself does not read that variable. Due to this, it is not possible to setup a MySQL DB if your cluster is serving from a port other than 3306(which is the default port of MySQL)
In this pr, I'm adding the port parameter, which should be already present when using [helm charts](https://github.com/acryldata/datahub-helm/blob/fa53c6d15963760315eeedd3067bc29551cfb92d/charts/datahub/values.yaml#L134), to the mysql-setup-job's connection parameters.  
There is also an issue with the documentation of the port parameter for the MySQL. This is also handled in [this pr](https://github.com/acryldata/datahub-helm/pull/125)

fix(mysql-setup-job): add mysql default port override support

---

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java

Instead log error and move on.

fix(restore-indices): Do not fail while working with each row

---

metadata-ingestion-modules/airflow-plugin/setup.py
metadata-ingestion/scripts/docgen.py

feat(docs): ingest - add tab for config json schema

---

datahub-web-react/src/app/glossary/GlossaryBrowser/GlossaryBrowser.tsx
datahub-web-react/src/app/glossary/GlossarySearch.tsx
datahub-web-react/src/app/search/SearchBar.tsx

We noticed two small issues around the Glossary updates:
1. The Glossary search bar would show search recommendations such as most recent search which hid actual search results.
2. Moving a Node or Term from the root level would not update in the Glossary Browser (the file nav on the left) until you refresh
Here's how I fix them:
1. Pass in an optional prop to skip the request to get search recommendations so we never show them if that prop is passed in.
2. Use the same state system used for updating the browser when moving terms/nodes not in root to also refetch the root nodes and terms when you move something.

fix(glossary) Two quick followup fixes around the new Glossary updates

---

datahub-frontend/app/auth/sso/oidc/OidcConfigs.java
datahub-frontend/app/auth/sso/oidc/OidcProvider.java
datahub-frontend/conf/application.conf
datahub-frontend/play.gradle
datahub-frontend/test/security/DummyLoginModuleTest.java
datahub-frontend/test/security/OidcConfigurationTest.java
datahub-frontend/test/utils/SearchUtilTest.java

feat(oidc): add configurable read timeout

---

datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedEntity.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/graphql/glossaryTerm.graphql

Now displays related entities that are related to any Incoming "IsA" glossary terms on a parent term's related entities tab.
For example:
TermA inherits from TermB (TermA has an Outgoing "IsA" relationship defined with TermA) and therefore shows TermA in its Inherits tab. If you go to TermB's profile, you will see all entities related to TermA in TermB's Related Entities tab.
The way the the Related Terms tab works, though, is that we only show Outgoing "IsA" and "HasA" relationships (Inherits and Contains, respectively). So TermB may not show TermA in its Related Terms tab.
**Note**: This is only 1 level down, so we only show direct Incoming "IsA" relationship children's related entities (much easier and quicker to implement than going all the way through the tree)
A visual example - …

feat(glossary) Display Incoming 'IsA' Glossary related entities

---

metadata-models/src/main/pegasus/com/linkedin/metadata/key/DataHubUpgradeKey.pdl
metadata-models/src/main/pegasus/com/linkedin/upgrade/DataHubUpgradeRequest.pdl
metadata-models/src/main/pegasus/com/linkedin/upgrade/DataHubUpgradeResult.pdl
metadata-models/src/main/resources/entity-registry.yml
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/factories/BootstrapManagerFactory.java
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/RestoreGlossaryIndices.java
metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/RestoreGlossaryIndicesTest.java
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java

Creates a new entity called DataHubUpgrade which will be used in order to keep track of who has run what upgrade steps.
I'm creating a specific instance for `glossary-upgrade` where we will restore indices of Glossary Nodes Info aspects and Glossary Term Info aspects. Once a user boots up GMS, if they haven't run this bootstrap step they will get all of their Terms and nodes and restore their indices. All following times on bootup they will not run this step if there is already a `glossary-upgrade` DataHubUpgrade entity in mysql.

feat(upgrades) Create new DataHubUpgrade + Restore Glossary Entities Bootstrap step

---

metadata-ingestion/setup.py

fix(deps): ingest - moving packaging to framework_common

---

datahub-frontend/conf/application.conf
datahub-frontend/run/frontend.env

Allows overriding `max-header-value-length` via environment variables. This should enable users to solve the following issue:
```akka.actor.ActorSystemImpl - Illegal request, responding with status '431 Request Header Fields Too Large': HTTP header value exceeds the configured limit of 8192 characters```

feat(frontend) Allow overriding akka-max-header-value-length

---

datahub-web-react/src/app/policy/ManagePolicies.tsx
datahub-web-react/src/app/policy/PolicyActorForm.tsx
datahub-web-react/src/app/settings/AccessTokens.tsx

- Worked on the Activate / Deactivate button as the button status was not changing after taking action

Policies page issue

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/entity/EntityExistsResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/entity/EntityExistsResolverTest.java

feat(graphql): add graphql endpoint to check whether an entity exists

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/AddRelatedTermsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/RemoveRelatedTermsResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/AddRelatedTermsResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/RemoveRelatedTermsResolverTest.java
datahub-web-react/src/app/entity/glossaryTerm/profile/AddRelatedTermsModal.tsx
datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTerms.tsx
datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTermsResult.tsx
datahub-web-react/src/app/entity/glossaryTerm/profile/RelatedTerm.tsx
datahub-web-react/src/app/entity/glossaryTerm/profile/useRemoveRelatedTerms.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/graphql/glossaryTerm.graphql

Adds the ability to Add and Remove Related Terms on a Glossary Term's profile page through the UI. Includes two new backend GraphQL endpoints and the associated frontend. You can add multiple terms at once for either the "Contains" or "Inherits" case depending which tab you have selected. You can remove one term at a time thanks to a new menu on each Related Term. This also cleans up the Related Terms UI a bit as it was looking pretty janky.
Screenshots:
**The new look:**
**Adding terms**
**You can add multiple**:
**Removing a term:**

feat(terms) Add ability to Add and Remove Related Terms to Glossary Terms

---

metadata-ingestion/src/datahub/ingestion/run/pipeline.py
metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

- no error when profiling bigquery partitioned table which is empty
- minor perf improvement so we don't run query for every table to find the partitioned table
- improve final error messages as sometimes it gets hard to find number of workunit, error, warnings in big reports
- do not attempt to profile tables when we were not able to get column information

fix(bigquery): handling of empty partitioned tables, improve report message

---

metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py

fix(ingestion): bigquery-usage - Only send operational metadata for allowed tables

---

metadata-ingestion/src/datahub/ingestion/source/tableau_common.py

As per [Common Tableau + Amazon Athena Errors](https://tableaulove.com/common-athena-tableau-errors/) linked in [this tableau blog](https://www.tableau.com/about/blog/2017/5/connect-your-s3-data-amazon-athena-connector-tableau-103-71105) , athena databases (equivalent to schemas in tableau) are grouped under AwsDataCatalog catalog(equivalent to database in tableau). 
In this PR, we ignore tableau upstream db and consider only schema and table name when generating table urn for athena, in order to create urn consistent with other places such as athena source.

fix(ingest): fix table urn for athena connectionType

---

datahub-web-react/src/app/ingest/source/builder/DefineRecipeStep.tsx

**Cannot proceed to next step for Looker ingestion without closing banner**
**Can proceed to next step for Looker ingestion when banner is closed**
**Banner is not shown when editing Looker recipe**
**Banner is not shown when creating a new recipe for other sources**
**Banner is not shown when editing an existing recipe for other sources**

fix(ui-ingestion): show warning banner when configuring looker ui-ingestion for the first time

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/auth/ListAccessTokensResolver.java

**Summary**
When listing access token resolvers, we were directly using the input facet filters to query against Elasticsearch. This differs from how we handle other search query filters, wherein we inject the ".keyword" suffix to the filter to ensure that it is matched against a keyword filter.

fix(tokens): Using keyword search filters for ListAccessTokensResolver

---

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java

A few rows may fail to get restored (i.e. compatibility issues, deprecated aspects, etc.) 
Do not mark job as failed even if some rows fail to get restored.

fix(restore-indices): Do not fail on MAE row count diff

---

datahub-frontend/play.gradle

Attempts to fix CVE-2019-17195 which comes from com.nimbusds:nimbus-jose-jwt dependency transitively from Pac4J. Fix is to exclude jar and include a specific version.

chore(deps): Bump Nimbus Jose JWT dependency

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryNodeMapper.java

If the node has no properties aspect, it will reach the key mapper with a null `properties` field. This fix prevents an NPE.

fix(business glossary): setting properties to be empty if the node has no properties aspect

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dataset/DatasetHealthResolver.java
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHealthStatus.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionDescription.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionLogicModal.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionsSummary.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/ValidationsTab.tsx
metadata-ingestion/examples/recipes/file_to_datahub_rest.dhub.yaml

**Summary**
This PR fixes and improves various aspects of the Assertions UI, including:
1. If you have no assertion runs, you will not see a pass or fail status next to dataset name
2. Default to the assertions tab when assertions are present (do not require an extra click) 
3. Support viewable logic along with an assertion definition (in a logic modal)
4. Fix inconsistent remove assertions flow 

refactor(ui): Misc improvements to Dataset Assertions UI

---

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py

I am trying to modify the line because it seems strange to check the row_count value when allocating the column_count value.
Please let me know if there is anything I'm doing wrong

fix(glue): fix glue profiling config option

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/RestoreGlossaryIndices.java
metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/RestoreGlossaryIndicesTest.java

Previously, we would only check that the datahub upgrade urn existed for the restore glossary indices step to determine if we should run the step. If it existed we did not run, and if not, we ran it.
Now, we may have situations where someone may have run the upgrade step but we want them to run it again, so we can check a version! The `DataHubUpgradeRequest` aspect was already storing a version, and for this step we previously set it to `0`. Now we check to get that aspect, and if it exists, and it has the same version as the const at the top of the file, skip the step. If it doesn't exist or the version is different, run the step.
Now to have users re-run the step we just need to change the `VERSION` at the top of the file. I do so here as we know we want some users to re-run this step. …

feat(upgrade) Check version when determining to run RestoreGlossaryIndices step

---

datahub-frontend/app/auth/JAASConfigs.java

Previous implementation rendered config value as "Quoted(true)", thus value never could be interpreted as true

fix(jaas): fixed auth.jaas.enabled option parsing

---

metadata-ingestion/src/datahub/ingestion/source/ldap.py

The first element of the results3 tuple could be an empty array [], for example, if it is a system account and it has no managers. Thus, the the current code is failing with "out of range" error. I added a quick check if array is not empty which has fixed this error.

fix(ingest): If there is no manager for a LDAP user (example: system account)

---

docker/datahub-gms/env/docker.env
docker/datahub-mae-consumer/env/docker-without-neo4j.env
docker/datahub-mae-consumer/env/docker.env
docker/datahub-mce-consumer/env/docker.env
docs/how/kafka-config.md
docs/how/updating-datahub.md
metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java

**Summary**
Simplify the environment variables for MAE / MCE consumer topic names for the deprecated legacy topics: MetadataChangeEvent, MetadataAuditEvent, FailedMetadataChangeEvent.
Previously, env variables were named inconsistently between GMS and the consumers.
**Changes**
datahub-mae-consumer: KAFKA_TOPIC_NAME --> METADATA_AUDIT_EVENT_NAME
datahub-mce-consumer: KAFKA_MCE_TOPIC_NAME --> METADATA_CHANGE_EVENT_NAME
These changes are backward compatible, so using the previous configuration values OR the new values will work. 
Also updated + improved Kafka documentation to reflect these changes.

refactor(configs): Simplify Kafka Topic name configurations + docs

---

.github/workflows/metadata-ingestion.yml
metadata-ingestion/build.gradle
metadata-ingestion/setup.cfg
metadata-ingestion/tests/integration/data_lake/test_data_lake.py
metadata-ingestion/tests/integration/feast-legacy/test_feast.py
metadata-ingestion/tests/integration/hive/test_hive.py
metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
metadata-ingestion/tests/integration/presto-on-hive/test_presto_on_hive.py

Follow up of https://github.com/datahub-project/datahub/pull/5187 to split integration tests to reduce run time

feat(ci): split integration tests to reduce run time

---

datahub-web-react/craco.config.js
datahub-web-react/package.json
datahub-web-react/src/app/ingest/source/builder/YamlEditor.tsx
datahub-web-react/yarn.lock

This PR adds the monaco-editor as a dependency and loads the editor from the local directory and not from a third party CDN. This fixes potential issues where the CDN is not reachable (see also #4955) and of course it is better to have all dependencies in one place and not relying on a third party service.
As it is quite hard (to not say impossible?) to import the monaco-editor in a Create React App (there are many issues, comments, etc. which describes the issues with it), the files are copied from the monaco-editor package to the build directory using the CopyWebpackPlugin and are then loaded by the @monaco-editor/react package from there.
The version of the added monaco-editor package is exactly the version which is loaded by the current version of the @monaco-editor/react package, …

fix(ui): load monaco-editor as a dependency and not from a third party CDN

---

metadata-ingestion/src/datahub/ingestion/source/sql/hive.py

The default dbapi implementation doesn't pass through struct types. 
This PR patches that function to pass it through.

fix(ingest): databricks - ingest structs correctly through hive

---

metadata-ingestion/docs/sources/tableau/tableau.md
metadata-ingestion/src/datahub/ingestion/source/tableau.py

Currently only `workbooksConnection` query is paginated using config `workbooks_page_size`. This PR introduces `page_size` config for all metadata queries (including `customSQLTablesConnection`, `publishedDatasourcesConnection`) in order to overcome NODE_LIMIT_EXCEEDED error and deprecates workbooksConnection specific `workbooks_page_size` config.

feat(tableau): use pagination for all connection queries

---

metadata-ingestion/src/datahub/ingestion/source/s3/profiling.py

Add check for 0 rows when profiling datasets from s3

---

datahub-web-react/src/app/entity/shared/EntityDropdown/EntityDropdown.tsx

if you do not have the MANAGE DOMAINS privilege, the button to create new term/term group is grayed out:
It should have checked the MANAGE GLOSSARIES privilege instead.

[bug fix]: disabled create buttons

---

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

Noticed missing exclude for password

fix(ingest): do not dump password

---

datahub-web-react/src/app/entity/shared/siblingUtils.ts

In recent work for siblings feature, we've mis-merged the URN field of the siblings by taking whichever is the primary. This does not make sense. This PR fixes this feature.

fix(siblings): Force merged urn to viewed entity urn

---

docs-website/sidebars.js

refactor(docs): Move CLI docs to root level

---

datahub-web-react/src/app/search/SearchPage.tsx
datahub-web-react/src/app/search/SearchResults.tsx

Previously we were hardcoding the number of search results per page to be 10. Now it's dynamic and leverages Ant designs existing component to allow users to set how many results they want to see per page.
Here's what it looks like:

feat(search) Allow users to update the number of search results per page

---

metadata-ingestion/src/datahub/configuration/source_common.py
metadata-ingestion/src/datahub/ingestion/source/aws/path_spec.py
metadata-ingestion/src/datahub/ingestion/source/s3/config.py
metadata-ingestion/src/datahub/ingestion/source/s3/source.py
metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py

Fixing s3 urn generation for Redshift copy in lineage generation

feat(ingest): redshift - Option to define path spec for Redshift lineage generation

---

datahub-web-react/src/graphql/browse.graphql

When working locally, I couldnt get anything to show up on the when browsing at `browse/tasks`(no name, owners, description, etc), even though I had all the entities and could see them getting set in the GraphQL resolvers.
I then checked the demo https://demo.datahubproject.io/browse/tasks/airflow/datahub_really_large_dag and noticed they are all the same. 
This change resolves it for me locally -

fix(ui): Enable previews properly when browsing for DataJob

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/DeleteAssertionResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/DeleteGlossaryEntityResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/RemoveGroupResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/user/RemoveUserResolver.java
metadata-io/src/main/java/com/linkedin/metadata/entity/DeleteEntityService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/DeleteEntityUtils.java
metadata-io/src/test/java/com/linkedin/metadata/entity/DeleteEntityUtilsTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/JavaEntityClientFactory.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/JavaEntityClient.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java

**Summary**
In this PR we add support for maintaining referential integrity when deleting users, groups, assertions, and groups. Prior to this change, deleting these entities would result in dangling pointers to that entity.

fix(ui): Support deleting references to glossary terms / nodes, users, assertions, and groups

---

datahub-web-react/src/app/entity/shared/siblingUtils.ts
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/ValidationsTab.tsx
datahub-web-react/src/graphql/dataset.graphql

Updates the get assertions query to also get all assertions for siblings, then combine that data to show all assertions in the Validation tab for all siblings.

fix(siblings) Display sibling assertions in Validations tab

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateNameResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/UpdateNameResolverTest.java
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/domain/DomainEntity.tsx
datahub-web-react/src/app/entity/shared/containers/profile/__tests__/EntityHeader.test.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx

Extends an existing framework for editing entity names for Domains. Adds the backend check to update the correct aspect and also checks privileges on the frontend before showing the option to edit the name. This works the same as how it does for Terms and Nodes.

Feat(domain) Add ability to edit a Domain name from the UI

---

datahub-web-react/src/app/entity/shared/siblingUtils.ts

After digging into it, we have confirmed that `a` is always the `secondary` sibling of the two and `b` is always the `primary` sibling of the two in the siblings utils comparator functions. This just updates those names appropriately.

fix(siblings) Update the names of siblings utils args for readability

---

metadata-ingestion/setup.py

Adding missing redshift dependencies
Relaxing sqlalchemy deps to make our plugins work with Airflow 2.3 -> This should fix https://github.com/datahub-project/datahub/issues/4809

fix(ingest) redshift: Adding missing dependencies and relaxing sqlalchemy dependency

---

metadata-ingestion/src/datahub/entrypoints.py

fix(cli): suppress secrets in stacktraces

---

datahub-web-react/src/graphql/lineage.graphql

We no longer need sibling's lineage, so we can avoid fetching that.

perf(siblings): reduce data fetched by siblings in lineage

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dashboard/preview/DashboardPreview.tsx
datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx
datahub-web-react/src/app/entity/dataFlow/preview/Preview.tsx
datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
datahub-web-react/src/app/entity/dataJob/preview/Preview.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/domain/DomainEntity.tsx
datahub-web-react/src/app/entity/domain/preview/Preview.tsx
datahub-web-react/src/app/entity/glossaryTerm/preview/Preview.tsx
datahub-web-react/src/app/entity/group/Group.tsx
datahub-web-react/src/app/entity/mlFeature/MLFeatureEntity.tsx
datahub-web-react/src/app/entity/mlFeature/preview/Preview.tsx
datahub-web-react/src/app/entity/mlFeatureTable/MLFeatureTableEntity.tsx
datahub-web-react/src/app/entity/mlFeatureTable/preview/Preview.tsx
datahub-web-react/src/app/entity/mlModel/MLModelEntity.tsx
datahub-web-react/src/app/entity/mlModel/preview/Preview.tsx
datahub-web-react/src/app/entity/mlModelGroup/MLModelGroupEntity.tsx
datahub-web-react/src/app/entity/mlPrimaryKey/MLPrimaryKeyEntity.tsx
datahub-web-react/src/app/entity/mlPrimaryKey/preview/Preview.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
datahub-web-react/src/app/entity/tag/Tag.tsx
datahub-web-react/src/app/entity/user/User.tsx
datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/graphql/search.graphql

**Summary**
In this PR, we 
1. Reduce the amount of data we fetch for autocomplete to only what is necessary to render the name and platform
2. Reduce the amount of data fetched for rendering search bar suggestions on the home page 
3. Correctly fetch and render platform logos based on the Platform Field 
4. Fix some misc consistency bugs where entity search previews didn't have their entity type logos appearing 
**Status**

perf(ui): Performance improvements and misc refactorings in the UI

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionDescription.tsx

Some users were having issues with the Validation tab throwing an error and crashing the app because `getColumnAggregationText` was receiving `undefined` for the `field` arg. Instead of throwing an error, I'm now  tossing a `console.error` and then setting the default text to be "undefined" so the Validations tab at least shows up.

fix(validation) Fail validation error silently instead of crashing

---

datahub-web-react/src/app/shared/ManageAccount.tsx

Makes the profile icon clickable to expand or contract the header menu. This was a recent regression.

fix(ui) Make profile icon clickable to expand header menu

---

datahub-web-react/src/app/ProtectedRoutes.tsx
datahub-web-react/src/app/analyticsDashboard/components/AnalyticsPage.tsx
datahub-web-react/src/app/authorization/UnauthorizedPage.tsx
datahub-web-react/src/app/browse/BrowsableEntityPage.tsx
datahub-web-react/src/app/browse/BrowseResultsPage.tsx
datahub-web-react/src/app/domain/ManageDomainsPage.tsx
datahub-web-react/src/app/entity/EntityPage.tsx
datahub-web-react/src/app/glossary/BusinessGlossaryPage.tsx
datahub-web-react/src/app/ingest/ManageIngestionPage.tsx
datahub-web-react/src/app/search/SearchPage.tsx
datahub-web-react/src/app/search/SearchablePage.tsx
datahub-web-react/src/app/settings/SettingsPage.tsx

This PR prevents page flickering by refactoring the SearchablePage out as a wrapper container around other existing pages

refactor(ui): Extract searchable page into its own component (perf + ux) 

---

metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java

Removes auto-creation of Status aspect when ingesting metadata snapshots that do not include. 
Historically this behaviour was used to ensure that re-ingesting some metadata that was soft deleted would be resurfaced. The typical scenario being to fix an incorrect ingestion recipe.
This approach caused issues in usage ingestion where soft deleted entities come back to life because any sort of associated metadata was ingested.
The correct approach is to have our connectors explicitly send a Status aspect with `removed=false` to re-enable the soft delete entity.

fix(gms) Remove auto-creating status aspect if not present when ingesting

---

datahub-web-react/src/app/entity/shared/siblingUtils.ts

We were seeing duplicate tags and terms if the two siblings had the same tag or term before they were merged as siblings. This uses `unionBy` from lodash to combine arrays of objects but removes duplicates based on a field. So you can see I remove duplicates based on the `urn` for the the fields we're seeing duplicates for.

fix(siblings) Combine siblings data but remove duplicate data

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/useGetAuthenticatedUser.tsx

We call this query on almost every new page or tag, let's cache it.

fix(me) Cache the me query for performance reasons

---

docs/how/updating-datahub.md
metadata-ingestion/examples/demo_data/csv_enricher_demo_data.csv
metadata-ingestion/examples/recipes/csv_enricher_to_datahub_rest.dhub.yml
metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
metadata-ingestion/src/datahub/ingestion/source_config/csv_enricher.py
metadata-ingestion/tests/integration/csv-enricher/csv_enricher_golden.json
metadata-ingestion/tests/integration/csv-enricher/csv_enricher_test_data.csv
metadata-ingestion/tests/integration/csv-enricher/test_csv_enricher.py
metadata-ingestion/tests/unit/test_csv_enricher_source.py

feat(ingest): update CSV source to support description and ownership type

---

docs/features.md

docs(features): update grammar on Features overview

---

metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
metadata-ingestion/tests/integration/mysql/test_mysql.py
metadata-ingestion/tests/test_helpers/docker_helpers.py

fix(ci): fix mysql and kafka-connect ingestion test

---

datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx

We want the Lineage tab to exist in Chart and Dashboard entity profiles, so this PR adds them. They use the same logic for `visible` and `enabled` as other entities do.

feat(lineage) Add Lineage tab to Chart and Dashboard entity profiles

---

datahub-web-react/src/App.tsx
datahub-web-react/src/app/entity/container/ContainerEntity.tsx
datahub-web-react/src/app/entity/container/preview/Preview.tsx
datahub-web-react/src/app/entity/shared/utils.ts
datahub-web-react/src/app/shared/tags/AddTagsTermsModal.tsx
datahub-web-react/src/app/shared/tags/CreateTagModal.tsx
datahub-web-react/src/graphql/tag.graphql
docs/how/updating-datahub.md

**Summary**
In this PR, we migrate to using the new createTag GraphQL API for creating tags via the UI. This API requires that the `Create Tags` platform privilege has been granted to the user, which is a net-new requirement.
**Changes**
- Migrate from updateTag to createTag mutation to make creating tags behind the Create Tag privilege. This should simplify recent confusion over tag privileges.
- [minor fix] Show tags in the Container entity previews
- Add validation for new tag names (no urn-invalid characters like parens, commas)

refactor(ui): Use createTag mutation for creating new tags from the UI

---

docker/docker-compose.override.yml
docker/docker-compose.yml
docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
docker/quickstart/docker-compose.quickstart.yml
docs/quickstart.md
metadata-ingestion/setup.py
metadata-ingestion/src/datahub/cli/docker.py
metadata-ingestion/src/datahub/entrypoints.py

Adding support to configure a different port for all the mapped ports  in quickstart  due to port conflict

feat(quickstart): Adding env variables and cli options for customizing mapped ports in  quickstart

---

metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatefulTokenService.java

Propagates cache exception being thrown by StatefulTokenService when unable to retrieve cache information.

fix(gms): Propagate token cache error

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestDataPlatformsStep.java

**Skipped for existing platforms**
**Ingested for new Test Data Platform**

fix(bootstrap): skip ingesting data platforms that already exist

---

metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py

Change done in https://github.com/datahub-project/datahub/pull/5329 broke multi-project setup. Fixing that.

fix(bigquery): multi-project GCP setup run query through correct project

---

metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardUsageStatistics.pdl
metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardUserUsageCounts.pdl
metadata-models/src/main/resources/entity-registry.yml

**Summary**
In this PR, we introduce a set of PDL models for usage of a Dashboard, so that insights can be extracted from platforms like Looker and Tableau. Stay tuned :)

feat(GMS): Adding Dashboard Usage Models

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardUsageStatsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/mappers/DashboardUsageMetricMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
metadata-ingestion/examples/library/dashboard_usage.py
metadata-ingestion/src/datahub/ingestion/source/looker.py
metadata-ingestion/src/datahub/ingestion/source/looker_common.py
metadata-ingestion/tests/integration/looker/looker_mces_usage_history.json
metadata-ingestion/tests/integration/looker/test_looker.py
metadata-ingestion/tests/integration/s3/test_s3.py
metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardUsageStatistics.pdl
metadata-models/src/main/pegasus/com/linkedin/metadata/query/filter/Condition.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.analytics.analytics.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java

Includes -
**Metadata Model changes**
- dashboard usage time series aspect for dashboard
- Captures usage for a time bucket when eventGranularity is present
- Captures absolute usage when eventGranularity is absent
- Introduce backward incompatible new enum (IS_NULL) in filter condition, need to use -Prest.model.compatibility=ignore when building model
**Example Script**
datahub_usage.py to emit dashboard usage events using python emitter
**GraphQL Wiring**
Add graphql types and wiring with datahub gms using timeseries api.
**Looker Source Changes**
Updates to looker ingestion source to ingest dashboard usage information

feat(model, graphql, ingest): Dashboard usage

---

metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatefulTokenService.java

This PR fixes an issue on StatefulTokenService where the use of a single instance of `MessageDigest.getInstance("SHA-256");` was causing intermittent failures especially visible during ingestion. 
Root cause is that MessageDigest is not thread safe.
To fix this the PR uses instead Apache Commons utility which is thread safe.

fix(gms): Change MessageDigest to be thread safe

---

metadata-ingestion/src/datahub/ingestion/source/looker.py
metadata-ingestion/src/datahub/ingestion/source/looker_common.py
metadata-ingestion/tests/integration/looker/test_looker.py

fix(ingest): pass transport options to usage history looker api calls

---

docker/kafka-setup/kafka-setup.sh
docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml

Requires a change to kafka-setup, so can only be validated locally.

feat(quickstart): moving to official confluent images for m1

---

datahub-web-react/src/app/entity/shared/tabs/Documentation/components/DescriptionEditor.tsx

Fixes a bug we've been hearing about but been having a hard time to reproduce. What happens is while you're editing documentation, if you pause for at least 5 seconds after making an edit, then try to make another edit, your cursor jumps to the end of the content. This makes editing existing documentation nearly impossible if you're editing anything in the middle of the documentation content.
The issue was that we have a debounced function that sets the text content in localStorage after 5 seconds go without making a change. Once we set the value in localStorage, this changes the root `description` value that we get (defaults to what's in localStorage if it exists). We were setting this `description` as the default state for `updatedDescription` (what we pass into our mutation functions) …

fix(documentation) Fix erratic cursor in documentation editor bug

---

datahub-web-react/src/graphql/lineage.graphql

`Show full titles` button on Lineage page does not display dataset `qualifiedName`, because it's missing in `GetEntityLineageQuery` result

fix(ui): add dataset qualifiedName parameter to lineage query

---

datahub-web-react/src/app/entity/shared/EntityDropdown/EntityDropdown.tsx

Fixes an issue where disabled buttons were not truly disabled (although they looked like it).

fix(glossary) Fix dropdown where disabled buttons are still clickable

---

docs/how/updating-datahub.md
metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/tests/unit/test_bigquery_source.py

docs(bigquery): add changelog and unittest for profiling limits

---

datahub-web-react/src/graphql/lineage.graphql
datahub-web-react/src/graphql/relationships.graphql
smoke-test/tests/cypress/cypress/integration/siblings/siblings.js

Makes sure sibling logic is also skipped when testing for upstreams/downstream of newly expanded nodes. This usually won't make a difference unless your only upstream/downstream is also your sibling (e.g., sources).

fix(siblings): fixing lineage fetching for siblings & sources

---

datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/container/preview/Preview.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dashboard/preview/DashboardPreview.tsx
datahub-web-react/src/app/entity/dashboard/profile/DashboardStatsSummarySubHeader.tsx
datahub-web-react/src/app/entity/dashboard/shared/DashboardStatsSummary.tsx
datahub-web-react/src/app/entity/dataFlow/preview/Preview.tsx
datahub-web-react/src/app/entity/dataJob/preview/Preview.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/dataset/preview/Preview.tsx
datahub-web-react/src/app/entity/dataset/profile/stats/stats/DatasetStatsSummarySubHeader.tsx
datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
datahub-web-react/src/app/entity/shared/components/styled/ExpandedActor.tsx
datahub-web-react/src/app/entity/shared/components/styled/ExpandedActorGroup.tsx
datahub-web-react/src/app/entity/shared/components/styled/StatsSummary.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/TableStats.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/graphql/dataset.graphql
datahub-web-react/src/graphql/fragments.graphql

**Summary**
In this PR, we do a few things:
1. Refactor the search preview stats into a shared compont for datasets and dashboards (DatasetStatsSummary, DashboardStatsSummary) 
2. Add a customizable "subheader" to render on the Entity Profile, which reuses these components to show statistics preview on the entity profile
3. Remove the sidebar stats section for datasets
4. Move owners sidebar section up 
5. Fix rendering of Top Users in the Dataset stats tab to show clickable resolved users (not just emails) 
**Status**

feat(ui): Adding Statistics Summary to Dataset + Dashboard Profiles 

---

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py

When using [Glue Virtual Views](https://aws.amazon.com/glue/features/elastic-views/) and tagging data with s3 bucket/object tags, the ingestion currently errors out when it finds a virtual view as there is no location set, and therefore the location doesnt being with s3:// or one of the other acceptable prefixes. This PR checks for the presence of a Location block and then returns `None` if one does not exist.

fix(ingest/glue): handle error when generating s3 tags for virtual view tables

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
datahub-graphql-core/src/main/resources/ingestion.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolverTest.java

Adds a new GraphQL endpoint that allows the user to test an ingestion connection given a recipe. This is only the backend piece, but it will be used by the frontend in order to allow users building new ingestion sources through UI Managed Ingestion to ensure their connection is set up properly.

feat(ingestion) Add new endpoint to test an ingestion connection

---

metadata-ingestion/docs/sources/hive/hive_recipe.yml
metadata-ingestion/src/datahub/ingestion/source/sql/hive.py

This PR extracts column comments and populates in column description. Previously this was being kept empty.

fix(hive): add column comment as a column description

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/AddGroupMembersResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/CreateGroupResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/RemoveGroupMembersResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpgroup/mappers/CorpGroupMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/group/AddGroupMembersResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/group/CreateGroupResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/group/RemoveGroupMembersResolverTest.java
datahub-web-react/src/app/entity/group/GroupInfoSideBar.tsx
datahub-web-react/src/app/entity/group/GroupMembers.tsx
datahub-web-react/src/app/entity/group/GroupProfile.tsx
datahub-web-react/src/app/identity/group/GroupListItem.tsx
datahub-web-react/src/graphql/group.graphql
metadata-models/src/main/pegasus/com/linkedin/common/Origin.pdl
metadata-models/src/main/pegasus/com/linkedin/common/OriginType.pdl
metadata-models/src/main/pegasus/com/linkedin/identity/NativeGroupMembership.pdl
metadata-models/src/main/resources/entity-registry.yml
metadata-service/auth-impl/src/main/java/com/datahub/authentication/group/GroupService.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
metadata-service/auth-impl/src/test/java/com/datahub/authentication/group/GroupServiceTest.java
metadata-service/auth-impl/src/test/java/com/datahub/authorization/PolicyEngineTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/GroupServiceFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java
smoke-test/test_e2e.py

feat(groups): add native groups concept to DataHub

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

fix(tableau): fix tableau db error, add more logs

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/timeline/GetSchemaVersionListResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaBlameMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaVersionListMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/utils/TimelineUtils.java
datahub-graphql-core/src/main/resources/timeline.graphql
datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
datahub-web-react/src/graphql/schemaBlame.graphql

- Adds new getSchemaVersionsList GraphQL endpoint, which also reduces latency
- Instead of the Normal/Blame radio buttons, we have a simple Audit icon you can use to toggle schema history
- The version selector is only show if there is more than one version for a dataset
**One version, schema history closed**
**One version, schema history visible**
**Multiple versions, schema history closed**
**Multiple versions, schema history visible**

feat(schema-history): remove blame language for the schema history feature

---

metadata-ingestion/src/datahub/ingestion/source/sql/trino.py

Under some configuration of access rules in Trino, the user may not have
read access to the content of the table, which will result in an exception
(`fetchone()` returns `None`)
This commit ensures no exception are raised and the ingestion can proceed.

fix(ingest/trino): Avoid exception if $properties table empty or not readable

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/chart/ChartStatsSummaryResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
datahub-web-react/src/app/entity/chart/profile/stats/ChartStatsSummarySubHeader.tsx
datahub-web-react/src/app/entity/chart/shared/ChartStatsSummary.tsx
datahub-web-react/src/graphql/chart.graphql
datahub-web-react/src/graphql/search.graphql
metadata-models/src/main/pegasus/com/linkedin/chart/ChartUsageStatistics.pdl
metadata-models/src/main/pegasus/com/linkedin/chart/ChartUserUsageCounts.pdl
metadata-utils/src/main/java/com/linkedin/metadata/Constants.java

**Summary**
In this PR, we add partial support for rendering usage for Charts. It represents the first part in this feature, and we stil need to implement the ChartStatsSummaryResolver to properly resolve the statistics. It follows existing patterns for Datasets and Dashboards.
**Changes**
- Models for ChartUsageStatistics
- GraphQL Models for ChartUsageStatistics
- UI Changes for rendering usage statistics in search + on the profile (verified locally by mocking api response)
**Status**

feat(ui): Partial support for Chart usage

---

metadata-ingestion/setup.py

A previous PR #5353 mistakenly relaxed the confluent kafka deps to allow for 1.9.0 which doesn't work with all datahub containers (due to a specific librdkafka dependency on 1.9.0). Reverting back that change.

fix(ingest): kafka - revert deps back to < 1.9.0

---

.github/workflows/docker-unified.yml
docker/datahub-upgrade/Dockerfile

Will allow datahub-upgrade to run on m1 as well.

feat(docker): support multiplatform image for datahub-upgrade

---

docker/mysql-setup/init.sql
docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
docs/how/backup-datahub.md
docs/how/restore-indices.md
docs/quickstart.md
metadata-ingestion/setup.cfg
metadata-ingestion/src/datahub/cli/docker.py

This PR
- Adds multiplatform support for the datahub-upgrade container 
- Adds experimental support to backup and restore the primary db of the quickstart using mysqldump
- Adds experimental support to restore indices of the running quickstart using the `datahub-upgrade` container

feat(quickstart): experimental support for backup restore for quickstart

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/tests/integration/dbt/dbt_deleted_actor_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json

Changes default lineage behavior to have models point to dbt source nodes rather than bigquery source nodes. Lineage will now look like this:
Source can be reverted to original logic using the `point_source_lineage_edges_to_target_node` flag.

feat(dbt): updating source lineage logic

---

docs-website/docusaurus.config.js

Migrating to the new crawler config as per https://docsearch.algolia.com/docs/migrating-from-legacy/ and https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration.

docs: fix docsearch config

---

.github/workflows/close-stale-issues.yml

Based on github docs https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

feat(build): automatically mark issues as stale to close inactive issues

---

metadata-ingestion/setup.py

fix(ingest): loosen confluent-kafka dep requirement

---

metadata-ingestion/build.gradle

Using `set -x` with `source venv/bin/activate` produces a ton of extra messages during the build process.

build(ingest): make gradle build less chatty

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
metadata-ingestion/tests/integration/dbt/dbt_deleted_actor_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_with_external_metadata_files_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_with_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_without_schemas_mces_golden.json
metadata-ingestion/tests/integration/dbt/dbt_without_schemas_with_filter_mces_golden.json
metadata-ingestion/tests/integration/dbt/test_dbt.py

Added Trino types for using DBT.
Added manifest_adapter to customProperties
Added `dbt_adapter` to `DBTNode` model which will be used to check for correct sql types
Please let me know if i should update the golden files... The test golden output should be inline with the latest state of Datahub.

fix(ingest): Fixing dbt trino datatypes

---

metadata-ingestion/src/datahub/ingestion/source/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/sql/oracle.py
metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
metadata-ingestion/src/datahub/telemetry/stats.py
metadata-ingestion/tests/integration/lookml/test_lookml.py

In the future, we can discover these using `flake8-noqa`.

fix(ingest): cleanup unused flake8 noqa statements

---

.github/actions/docker-custom-build-and-push/action.yml
.github/workflows/docker-unified.yml

refactor(ci): refactor Docker build-and-push workflows

---

docs/how/delete-metadata.md
metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/cli/delete_cli.py

Add new flag `--only-soft-deleted` to allow soft-deleting soft-deleting entities only and removed `--include-removed` arg which was redundant now.
Workflow now
Refactoring done so dry-run of hard-delete for soft-deleted entities should be faster now.

feat(cli): delete - make delete easier to use

---

metadata-ingestion/tests/unit/test_pipeline.py

fix(ingest): use temp dir for file generated during test

---

datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/search/SearchHeader.tsx
datahub-web-react/src/app/shared/admin/HeaderLinks.tsx

No longer hide the "Govern" header dropdown that contains links to Glossary and Domains. These should be available to everyone especially since we have privileges to prevent users from editing that shouldn't. But anyone should be able to see the Glossary and the Domains.
Involved some renaming now that these links aren't exclusively "Admin".

feat(ui) Show Glossary and Domains header links to everyone

---

datahub-web-react/src/app/search/SearchablePage.tsx

Search Page: Flickering Issue on search input field

---

metadata-ingestion/src/datahub/emitter/rest_emitter.py
metadata-ingestion/tests/conftest.py

The tests were previously hanging for a bit of time because of the retries. With these changes, running `pytest -v
tests/unit/test_pipeline.py` went from ~31s to ~4s on my machine.

test(ingest): limit GMS retries in test

---

datahub-web-react/src/graphql/preview.graphql

Fixes a bug where we weren't displaying the name of a Term Group properly in the Recently Viewed recommendation module. This is because we weren't querying for the name on the graphql side!

fix(ui) Display Term Group name properly in Recently Viewed

---

datahub-web-react/src/app/entity/glossaryNode/ChildrenTab.tsx
datahub-web-react/src/app/entity/glossaryNode/utils.ts
datahub-web-react/src/app/entity/glossaryTerm/utils.ts
datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx
datahub-web-react/src/app/entity/shared/EntityDropdown/MoveGlossaryEntityModal.tsx
datahub-web-react/src/app/glossary/BusinessGlossaryPage.tsx
datahub-web-react/src/app/glossary/GlossaryBrowser/GlossaryBrowser.tsx
datahub-web-react/src/app/glossary/GlossaryBrowser/NodeItem.tsx

This PR fixes two things about the business glossary:
1. For some actions we would show a success message even if there was a failure (such as creating a term without permission). This was happening because we were showing success in the `finally` block but instead should be in the `then` block. The `finally` block will run no matter whether it succeeds or fails.
2. Sort the Business Glossary alphabetically. Multiple users have asked for this and while we could add more sorting functionality, this is better than having no sorting (in my opinion as well as multiple people from the community). We could always add more functionality later but while I was putting up a small glossary PR I wanted to get this in as well.
You can easily review these two changes separately by commit.

fix(glossary) Fix Glossary success messages and sort Glossary

---

metadata-ingestion/src/datahub/__init__.py

Not 100% sure if this is the best place to put the warning - let me know if there's a different place that we should put this or if we should change the messaging (e.g. maybe we should say which version/date will drop support?)
It'll make sense to deploy this change in a CLI release and give it a week or so, and then drop Python 3.6 in a subsequent release.

feat(ingest): add deprecation warning for Python 3.6

---

metadata-ingestion/src/datahub/ingestion/source/ldap.py
metadata-ingestion/tests/integration/ldap/ldap_mces_golden.json
metadata-ingestion/tests/integration/ldap/ldap_memberof_mces_golden.json
metadata-ingestion/tests/integration/ldap/setup/custom/sample.ldif
metadata-ingestion/tests/integration/ldap/test_ldap.py

Current ldap ingester attach users to group when ingesting groups, but not vice versa. These changes attach groups to user when ingesting users

feat(ingestion): add groups to ldap users

---

docker/datahub-gms/env/docker.env
docs/how/updating-datahub.md
metadata-service/factories/src/main/resources/application.yml

This PR fixes the usage of **the boolean analytics tab config** in the gms. Most of the services follow the convention of `DATAHUB_ANALYTICS_ENABLED` usage. 
Also, [the env var in the helm charts of gms](https://github.com/acryldata/datahub-helm/blob/a8f5da4da9197f514ae02ebd4a77708ecf256488/charts/datahub/subcharts/datahub-gms/templates/deployment.yaml#L98) is defined as `DATAHUB_ANALYTICS_ENABLED` which conflicts with `ANALYTIS_ENABLED` env var defined in the source code of gms 😬. After this PR is merged, it should be correctly resolved. So there is no change needed for the helm charts.
---
I tested on my local computer and see that the analytics tab is correctly disabled in the UI. 
---

<fix>[analytics-tab] fix analytics tab config variable for gms

---

docs/schema-history.md

Super small PR - changing "schena" to "schema" because might as well fix typos when you see them 😄

docs(schema history): Correct typo in schema history documentation

---

metadata-ingestion/tests/integration/hana/test_hana.py
metadata-ingestion/tests/integration/trino/test_trino.py

test(ingest): mark trino/hana tests as xfail due to flakes

---

datahub-web-react/package.json
datahub-web-react/src/app/ingest/source/builder/CreateScheduleStep.tsx
datahub-web-react/yarn.lock

Uses a library `react-js-cron` to create a human readable cron job scheduler for managed ingestion. Instead of having to type out the actual cron schedule (confusing for everyone let's be honest), the user can choose exactly what they want from dropdowns that are dynamic depending on what they select.
For example, here's the default view (runs daily at midnight):
Then if you want to get fancier and do certain days of the week:

feat(ingestion) Update managed ingestion scheduler to be easier to use

---

metadata-ingestion/archived/source_docs/elastic_search.md
metadata-ingestion/docs/sources/elastic-search/elasticsearch_recipe.yml
metadata-ingestion/examples/recipes/elasticsearch_to_datahub.dhub.yaml
metadata-ingestion/src/datahub/ingestion/source/elastic_search.py

So this enhancement to the existing ES connector is driven by my company's current practice of using Index Templates as the basis for daily created indices. We don't use the Datastreams feature in ES to automatically rollover the index. As a result, if i use the default ES connector, i get thousands of identical datasets, differing by date, which is not very helpful for finding documentation (can't really expect every index to be populated) So we decided to ingest the index template instead.   
Based on my checks in [Slack](https://datahubspace.slack.com/archives/CUMUWQU66/p1657880726234279), it doesn't seem to be a popular use case, but i thought i will just put it up all the same.   
- [ x] Docs related to the changes have been added/updated (if applicable). If a new feature has been …

feat(ingest) Allow ingestion of Elasticsearch index template

---

smoke-test/tests/cypress/cypress.json
smoke-test/tests/cypress/cypress/integration/mutations/mutations.js
smoke-test/tests/cypress/integration_test.py

fix(ci): flaky smoke test fix

---

docker/datahub-gms/Dockerfile
docker/datahub-gms/start.sh

https://github.com/datahub-project/datahub/pull/5568 did not fix the problem

fix(gms): missing directory

---

datahub-graphql-core/src/main/resources/entity.graphql

The AssertionStdOperator in gql was not up to parity with https://github.com/datahub-project/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/assertion/AssertionStdOperator.pdl
Addresses https://github.com/datahub-project/datahub/issues/5513.

fix(assertions): extending assertion std model

---

smoke-test/requirements.txt
smoke-test/tests/__init__.py
smoke-test/tests/conftest.py
smoke-test/tests/delete/delete_test.py
smoke-test/tests/pytest.ini
smoke-test/tests/read_only/test_analytics.py
smoke-test/tests/read_only/test_ingestion_list.py
smoke-test/tests/read_only/test_policies.py
smoke-test/tests/read_only/test_search.py
smoke-test/tests/read_only/test_services_up.py
smoke-test/tests/test_result_msg.py
smoke-test/tests/tokens/revokable_access_token_test.py
smoke-test/tests/utils.py

Also fixed `os.putenv` to `os.environ` as the former is for subprocesses created not the current process.

feat(test): add read-only smoke tests

---

datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/builder/IngestionSourceBuilderModal.tsx
datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
datahub-web-react/src/app/ingest/source/builder/types.ts

Creates a new button in the managed ingestion builder that allows you to save your newly created source, or update an existing source, and then also run ingestion at the same time. I also update the loading state to show "Loading..." while we have the timeout to refetch all sources.
Here's what it looks like:

feat(ingestion) Add Save & Run button to managed ingestion builder

---

metadata-integration/java/as-a-library.md
metadata-integration/java/datahub-client/src/main/java/datahub/client/file/FileEmitter.java
metadata-integration/java/datahub-client/src/main/java/datahub/client/file/FileEmitterConfig.java
metadata-integration/java/datahub-client/src/main/java/datahub/client/kafka/KafkaEmitter.java
metadata-integration/java/datahub-client/src/test/java/datahub/client/file/FileEmitterTest.java
metadata-integration/java/datahub-client/src/test/resources/golden_files/mcps_golden.json

This PR adds the functionality to dump MCPs into file from java code. It produces json file similar to the one created by "file" sink from python.
Created json file can be used as a source in "File" Source.

feat(datahub-client): add java file emitter

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/tests/integration/delta_lake/test_local_delta_lake.py

fix(ingest): moving delta-lake connector to be 3.7+ only

---

datahub-web-react/src/app/entity/container/ContainerEntity.tsx
metadata-models/src/main/pegasus/com/linkedin/container/ContainerProperties.pdl
metadata-models/src/main/pegasus/com/linkedin/container/EditableContainerProperties.pdl

Currently, the descriptions for containers are not searchable, which is not ideal for me as we put useful, generalized information for users about the datasets in the container. Not sure if this is accidental or deliberate, but i have made the editableDescription and Description searchable, and updated the UI for the editable container description to show up.

(fix) Makes containers description searchable

---

datahub-web-react/src/graphql/preview.graphql
datahub-web-react/src/graphql/search.graphql
datahub-web-react/src/graphql/user.graphql

fix(groups): fix user, search, and preview group membership to be fetched for both external and native group memberships

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/powerbi.py
metadata-ingestion/src/datahub/utilities/dedup_list.py

See https://github.com/simonpercivall/orderedset/issues/36 - the orderedset package is dead.

chore(ingest): remove orderedset dependency

---

smoke-test/test_e2e.py
smoke-test/test_rapid.py
smoke-test/tests/assertions/assertions_test.py
smoke-test/tests/domains/domains_test.py
smoke-test/tests/policies/test_policies.py

fix(ci): cleanup sleeps to instead use retries

---

.github/workflows/docker-ingestion-smoke.yml

Going to use https://hub.docker.com/r/acryldata/datahub-ingestion-smoke so we have separate tags for each build

fix(ci): use different image for smoke base image

---

.github/workflows/docker-unified.yml

fix(ci): cancel docker-unified workflow only on PRs on new commits

---

metadata-ingestion/src/datahub/telemetry/telemetry.py

fix(ingest): use default telemetry ID when config is unwritable

---

datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/mlFeatureTable/MLFeatureTableEntity.tsx
datahub-web-react/src/app/entity/mlModel/MLModelEntity.tsx
datahub-web-react/src/app/entity/mlModelGroup/MLModelGroupEntity.tsx
datahub-web-react/src/app/lineage/LineageEntityNode.tsx
datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
datahub-web-react/src/app/lineage/types.ts

**Summary**
Previously we split asset names in Lineage view by a period. This does not work in cases where the delimiter for a platform should NOT be a period (e.g. S3). This PR fixes that by using the configured Data Platform delimiter to split names in the lineage viz. 
Verified with S3 datasets ending in file extensions.

fix(ui): Split based on Data Platform delimiter in Lineage viz

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/DomainEntitiesResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/domain/DomainEntitiesResolverTest.java
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchSection.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelect.tsx
datahub-web-react/src/app/ingest/source/IngestedAssets.tsx
datahub-web-react/src/app/ingest/source/utils.ts
datahub-web-react/src/app/search/SearchBar.tsx
datahub-web-react/src/app/search/SearchFilter.tsx
datahub-web-react/src/app/search/SearchablePage.tsx
metadata-io/src/main/java/com/linkedin/metadata/search/aggregator/AllEntitiesSearchAggregator.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
metadata-utils/src/main/java/com/linkedin/metadata/utils/SearchUtil.java

**Summary**
In this PR we introduce "sticky" search filters, which are those that do NOT clear when your search query is changed. This is supported across all surface areas. 
In addition to this, we fix a few minor search bugs (URN appearing in autocomplete once selected), ingested assets entities not appearing. 
**Changes**
1. [GMS] Change the ElasticSearch backend to support injecting aggregation results based on a Search Filter (to ensure that fields which are filtered for have result of 0 in aggregation set) 
2. [GMS] Change the ElasicSearch backend to avoid filtering out empty search results for a specific entity type. 
3. [UI] Fix a minor bug in IngestedAssets that prevented the entity breakdown from showing
4. [UI] Fix a styling bug in IngestedAssets for wrapping entity type counts …

feat(search): Sticky search filters + misc bug fixes & improvements

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java

The `sources` fields in both of these entities' properties aspects are optional. However, graphql was assuming they would be non-null and caused NPEs. This pr fixes that.

fix(graphql): handle null source values in ml features & primary keys

---

li-utils/src/main/pegasus/com/linkedin/common/AuditStamp.pdl
metadata-events/mxe-utils-avro-1.7/src/test/resources/test-avro2pegasus-mae.json
metadata-events/mxe-utils-avro-1.7/src/test/resources/test-avro2pegasus-mce.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesV2.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesVersionedV2.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.lineage.relationships.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json

This allows us to track context around audit stamps.

feat(model): Add optional message field to auditstamp

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx

Schema tab: Fixed the header issue 

---

docs-website/generateDocsDir.ts

Bonus: also hides the release candidates from the docs website and tweaks our date formatting to look better.

 build(docs-website): only show release notes for recent releases

---

datahub-web-react/src/graphql/dataProcess.graphql

We were fetching way too much for this tab, most especially relationships of the individual datasets.

perf(operations): performance improvement to operations tab via reduced fetching

---

metadata-ingestion/src/datahub/ingestion/source/identity/okta.py

Since the introduction of async decorators on ingest runs, the okta source fails due to an implicit dependency on running on the main thread (usage of asyncio.get_event_loop() method).
Adding a fail-safe to always initialize a loop.

fix(ingest): okta - make async loop init more robust

---

docs-website/.gitignore
docs-website/README.md
docs-website/build.gradle
docs-website/docs/.gitignore
docs-website/genDocs/.gitignore
docs-website/generateDocsDir.ts
docs-website/package.json

Bonus:
- Correctly handle untracked / deleted files with git
- Rename gradle command yarnServe -> yarnStart
- Correct info in docs-website readme

build(docs-website): make codegen script idempotent

---

datahub-web-react/src/app/search/SearchablePage.tsx

**Summary**
We recently rolled out an improvement to search UX where filters are now sticky, and not clear automatically between searches. In doing so we introduced a minor bug wherein if you've applied filters on a non-search results page (e.g. search embedded in entity profile), then we'll keep those filters even if you type in a new query to the search bar.
This PR ensures that we only reuse the filters for global search results if we are on the search page itself. This ensures that if we are transitioning from any other page that the filters are not persisted.

fix(ui): Fixing minor search redirect filtering issue introduced by sticky filters

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpgroup/mappers/CorpGroupPropertiesMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/app/entity/group/GroupProfile.tsx
datahub-web-react/src/graphql/group.graphql
metadata-ingestion/examples/mce_files/bootstrap_mce.json
metadata-models/src/main/pegasus/com/linkedin/identity/CorpGroupInfo.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesV2.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesVersionedV2.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.lineage.relationships.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json

**Summary**
In this PR, we add support for a slack handle specific in the CorpGroupInfo aspect, by community request.
**Status**
Ready for review!

feat(ui): Adding slack handle to corp group info

---

metadata-ingestion/src/datahub/ingestion/source/delta_lake/config.py
metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py

This PR removes the restriction of providing s3 auth through aws-config

fix(delta-table): allow env, credential file based s3 auth

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/browse/EntityBrowsePathsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/BrowsableEntityType.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/browse/EntityBrowsePathsResolverTest.java

**Summary**
We've heard community requests for fetching browse paths with an entity query all in one go. This PR adds a new 'browsePaths' field to the set of entities which are browsable to achieve this.
**Status**
**Validation**
Did some local sanity checks:
GraphQL query: 
```
query dataset {
dataset(urn: "urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)") {
browsePaths {
path
}
}
}
```
and result:
```
{
"data": {
"dataset": {
"browsePaths": [
{
"path": [
"prod",
"hdfs"
]
}
]
}
},
"extensions": {}
}
```

feat(GraphQL API): Add "browsePaths" field to browsable entity types 

---

metadata-ingestion/src/datahub/ingestion/source/mongodb.py

fix(ingest): use mongodb ping command to test connection

---

smoke-test/tests/read_only/test_search.py

fix(ci): use graphql instead of restli

---

datahub-web-react/src/app/ingest/source/ExecutionRequestDetailsModal.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/utils.ts

When viewing ingestion run details in the modal, continuously refetch to get updated logs every 2 seconds if the status of the ingestion run is `RUNNING`. Related to this, this PR also adds ingestion summary text for all ingestion run statuses and swaps the disabled "Execute" button for the actively running ingestion source to be a "Details" button that opens the summary modal.
This also cleans a few other things up.
- Add the ability to hide expanded logs if you expand them
- Hide "Show more" if you can't expand in the first place
- Prevent indefinite polling to get all ingestion sources after executing a run once we no longer have any sources that are RUNNING. Happens when we execute and even after the run is complete we poll until you refresh the page.
- Related ^ start polling for all …

feat(ingestion) Fetch live logs on an ingestion run from UI

---

metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatahubSparkListener.java

This PR creates datahub setup for spark application on sqlstart event if not done on the spark application start event.

fix(spark-lineage): Create application setup on sqlevent start

---

datahub-web-react/src/app/entity/group/AddGroupMembersModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/EditOwnersModal.tsx
datahub-web-react/src/app/policy/PolicyActorForm.tsx
datahub-web-react/src/app/policy/PolicyPrivilegeForm.tsx

We've received reports that our search UI in some places is weird when search results don't get updated if there are less than 3 characters. It's specifically weird when you type in 3 characters and backspace, still seeing the same results. This simply removes that constraint from submitting search requests with less than 3. If there's less than 3 we'll still show no data, but at least now it updates when you backspace from 3 to 2.

fix(ui) Remove constraint for searching with less than 3 characters

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/RestoreDbtSiblingsIndices.java

This lines dbt step up with the restore glossary step.

fix(siblings): set sleep after checking if the restore step should run

---

datahub-web-react/src/app/home/HomePageRecommendations.tsx
datahub-web-react/src/app/recommendations/renderer/component/DomainSearchList.tsx

Also switches up their link to go to domain entity page rather than search.

feat(domains): highlighting domain recommendation cards on homepage

---

metadata-ingestion/archived/source_docs/business_glossary.md
metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py

A link on our business glossary docs page was broken (check the page [here](https://datahubproject.io/docs/generated/ingestion/sources/business-glossary/) and click the link that goes "An example of one such file is located in the examples directory [here](https://github.com/datahub-project/datahub/blob/master/docs/generated/ingestion/examples/bootstrap_data/business_glossary.yml)." and that "here" has a broken link.
This links directly to the github example file.

fix(docs) Fix link from Business Glossary ingestion page

---

datahub-web-react/src/app/ingest/source/IngestionSourceExecutionList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceTable.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceTableColumns.tsx
datahub-web-react/src/app/ingest/source/RecipeViewerModal.tsx
datahub-web-react/src/app/ingest/source/__tests__/IngestionSourceList.test.tsx
datahub-web-react/src/app/ingest/source/utils.ts

Adds necessary checks and styles for displaying CLI based ingestion sources in the managed ingestion list in the UI. If it's from CLI, disable the execute button, only allow them to view their recipe (not edit), and have a few small styling changes.
The VAST majority of the diff here is from refactoring. If you view the changes by commit, this will be much easier to review.
Some screenshots:
**one snowflake CLI ingestion source**
**when you expand its executions**
**When you click the "View" button for CLI sources - read-only viewer of the recipe**

feat(ingestion-ui) Display CLI-based ingestion sources in UI

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaBlameMapper.java
datahub-graphql-core/src/main/resources/timeline.graphql

fix(schema-history): make latestVersion field on result optional

---

datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/app/ingest/source/utils.ts
metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py
metadata-models/src/main/pegasus/com/linkedin/dataprocess/DataProcessInstanceRunResult.pdl

This PR adds the "UP_FOR_RETRY" Data Process Instance RunResult type. Airflow tasks can go into the "up for retry" state, and we want to be able to reflect that in DataHub.
Tested in our own fork:

Add UP_FOR_RETRY DPI run result

---

datahub-web-react/src/app/ingest/source/IngestionSourceExecutionList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceTable.tsx

Fixes a bug that only occurs sometimes when we're unlucky where we don't fetch the executions list because the `lastRefresh` time did not change. This was happening because `new Date().getMilliseconds()` will return how many milliseconds into the second we are, not the total number of milliseconds since the epoch. That means that since we refresh exactly every 3 seconds, there's a real chance that occasionally this number is the same as the previous `lastRefresh` and we don't refresh the executions list. Fix this by setting `lastRefresh` as the number of milliseconds since the epoch so it's always new.
I also noticed that we were refreshing every executions list from every source that was opened at any point, even if it is now closed. So I added a check to only refresh if the executions …

fix(ui) Refresh executions on Ingestion page when they are visible

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py

This PR adds the option to configure a GitHub repository for dbt, similar to what exists for Looker: https://datahubproject.io/docs/generated/ingestion/sources/looker. Most dbt models should be version controlled and this makes DataHub even more useful.
Tested locally with `DATAHUB_VERSION="v0.8.43"`, `acryl-datahub==0.8.43.1`.
Screenshot:
I just noticed the "View in Dbt ->" should be "View in GitHub" in the UI, there is the same issue with Looker where it shows "View in Looker" while linking to GitHub.

feat(ingestion): add github_info config for dbt

---

datahub-frontend/app/controllers/AuthenticationController.java
datahub-frontend/app/controllers/CentralLogoutController.java
datahub-frontend/app/controllers/SsoCallbackController.java
datahub-frontend/run/frontend.env
datahub-web-react/src/app/auth/LogIn.tsx

**Summary**
Previously, when we failed to login or logout using SSO (oidc), we hit a red screen of death. In this PR we've added logic to 
1. Clearly log the error to the admin / operator
2. Redirect the poor user back to the /login page with a persistent error warning pinned to the top. 
Below is the new error scenario, redirect to login with an error!

fix(ui): Long overdue - Fix red error screens during OIDC login, logout exception scenarios

---

metadata-ingestion/src/datahub/ingestion/source/superset.py
metadata-ingestion/tests/unit/test_superset_source.py

fix(superset): do not crash when display_uri is not set

---

metadata-ingestion/examples/mce_files/bootstrap_mce.json
metadata-service/factories/src/main/resources/application.yml

**Summary**
In this PR we remove malformed tests in bootstrap.json file. We also disable the test engine by default. 
This causes unwanted error logs in the TestEngine component.

fix(bootstrap): Remove malformed test in bootstrap.json

---

metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py
metadata-ingestion/tests/unit/test_utilities.py

Prevents table and column names connected with a hyphen with the special tokens from getting replaced with alternate internal tokens.

fix(ingestion): Fix SQL Lineage Parser to handle special tokens with a hyphen in table and column names.

---

metadata-ingestion/src/datahub/telemetry/telemetry.py

Sending through a proxy server should allow us to easily switch away from Mixpanel in the future, if needed.

chore(ingest): update mixpanel api endpoint

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/RollbackIngestionResolver.java
datahub-graphql-core/src/main/resources/ingestion.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/RollbackIngestionResolverTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/JavaEntityClientFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/JavaEntityClient.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/BatchIngestionRunResource.java

All the backend work for allowing the user to rollback an ingestion run from the UI. Creates a new endpoint that kicks off a rollback of the ingestion run using the `runId` provided. This kick-off to start rolling back is asynchronous, so we first set the status of the request result aspect as ROLLING_BACK and then on a successful result set it to ROLLED_BACK. I have a try catch and if something fails I set it to ROLLBACK_FAILED. The FE is polling while this is all going on, waiting for a result.
I would highly suggest reviewing this ignoring whitespace since the try / catch block I added makes the BatchIngestionRunResource diff extremely hard to review.

feat(ingestion) Add ability to rollback ingestion from UI - BE PR

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/IngestionResolverUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateIngestionExecutionRequestResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/UpsertIngestionSourceResolver.java
datahub-graphql-core/src/main/resources/ingestion.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/source/UpsertIngestionSourceResolverTest.java
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/builder/IngestionSourceBuilderModal.tsx
datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
datahub-web-react/src/app/ingest/source/builder/types.ts
datahub-web-react/src/graphql/ingestion.graphql
ingestion-scheduler/src/main/java/com/datahub/metadata/ingestion/IngestionScheduler.java
metadata-models/src/main/pegasus/com/linkedin/ingestion/DataHubIngestionSourceInfo.pdl

Adds a checkbox under advanced when creating a UI based ingestion source that allows you to set whether or not you want the source to be in debug_mode and get more fine-grained logging.

feat(ingestion-ui) Add ability to set debug_mode on UI ingestion sources

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py

Fixing issue -  UnboundLocalError: local variable 'skip_profiling' referenced before assignment
This issue happens if `profiling.profile_table_level_only` is enabled in snowflake-beta.

fix(ingest): snowflake-beta fix missing initialization of variable

---

datahub-web-react/src/app/shared/tags/TagTermGroup.tsx

- Fixing a bug reported by xL where tag / term max limit on UI editing is 10.

fix(ui): Remove add limit on Entity Profile for glossary terms and tags 

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/tag/CreateTagResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/tag/CreateTagResolverTest.java

When a user creates a tag, now assign that user as an owner of said tag.

fix(tags) Add creator of tag as the owner of it

---

metadata-service/restli-client/src/main/java/com/linkedin/entity/client/JavaEntityClient.java

Previously we were simply setting the actor urn to UNKNOWN when making changes to metadata through the Java Entity Client. This now sets the actor urn so we can have correct audit logs in the mysql createdby column.

fix(audit logs) Set actor urn on audit stamp through Java Entity Client

---

metadata-ingestion/src/datahub/configuration/common.py
metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py

Fixes the oauth config validation in snowflake config.
It is causing test failures on the CI jobs recently like
* https://github.com/datahub-project/datahub/runs/8124353346?check_suite_focus=true#step:5:2469
* https://github.com/datahub-project/datahub/runs/8123466789?check_suite_focus=true#step:5:3243

fix(ingest): Fix oauth config validation in snowflake.

---

datahub-web-react/src/app/auth/LogIn.tsx
datahub-web-react/src/app/auth/ResetCredentials.tsx
datahub-web-react/src/app/auth/SignUp.tsx
datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
metadata-service/auth-impl/src/main/java/com/datahub/authentication/user/NativeUserService.java
metadata-service/auth-servlet-impl/src/main/java/com/datahub/authentication/AuthServiceController.java
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManager.java
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/OnBootApplicationListener.java
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestRolesStep.java
metadata-service/restli-client/src/main/java/com/linkedin/entity/client/JavaEntityClient.java
metadata-service/war/src/main/resources/boot/policies.json

**Summary**
In this PR, we create a dedicated thread pool that will help execute asynchronous bootstrap steps. This prevents the main spring thread from being blocked while async steps run, which causes a strange lag in the deployment experience.
We also fix misc bugs:
- make the roles ingestion step asynchronous to ensure that roles are successfully ingestd on first boot. 
- refactor the default role privileges
- fix NPE recently introduced into JavaEntityClient (sign up and reset password)

fix(bootstrap): Creating dedicated thread pool for executing async bootstrap steps + misc fixes

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

In response to [this issue](https://github.com/datahub-project/datahub/issues/5672).
Adds Glossary Nodes (aka Term Groups) to be targetable entities for adding / editing metadata privileges.

fix(privileges) Add Term Groups as targetable entities for privileges

---

metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserAppearanceSettings.pdl

fix(javadocs): remove ampersand from pdl causing issue in doc generation for openapi

---

metadata-ingestion/src/datahub/cli/docker.py
metadata-ingestion/src/datahub/ingestion/api/report.py
metadata-ingestion/src/datahub/ingestion/api/sink.py
metadata-ingestion/src/datahub/ingestion/api/source.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py
metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/utilities/lossy_collections.py
metadata-ingestion/tests/unit/api/test_report.py
metadata-ingestion/tests/unit/utilities/test_lossy_collections.py

feat(cli): add support for sampled reporting to keep logs manageable

---

smoke-test/tests/managed-ingestion/managed_ingestion_test.py

test(smoke-test): check debug arg in executor requests

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_usage.py

Changing the process to conserve memory. 
Instead of caching dashboards, we cache the explores.

feat(ingest): looker - reduce memory requirements

---

metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-ingestion/src/datahub/ingestion/api/report.py
metadata-ingestion/src/datahub/ingestion/api/source.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py
metadata-ingestion/src/datahub/ingestion/source/file.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_usage.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/src/datahub/utilities/memory_leak_detector.py

Main improvements:
- Memory usage reduced significantly
- All api access funneled through a single class
- More streamlined incremental progress and reporting

feat(ingest):looker - reduce mem usage, misc reporting improvements

---

metadata-ingestion/docs/sources/snowflake/README.md
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py

feat(model, ingest): populate sizeInBytes in snowflake, fall back to table level profiling for large tables

---

metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatahubSparkListener.java

Gracefully handling null parameters in sql start event

fix(ingest): spark-lineage: Adding additional debug logs to spark lineage

---

docker/docker-compose-with-cassandra.yml
docker/docker-compose-without-neo4j.override.yml
docker/docker-compose-without-neo4j.yml
docker/quickstart/docker-compose-without-neo4j.quickstart.yml

fix(docker): add missing port mappings for non-neo4j quickstart

---

metadata-ingestion/src/datahub/ingestion/run/pipeline.py

feat(cli): report memory usage during ingest

---

metadata-ingestion/docs/sources/s3/s3.md
metadata-ingestion/src/datahub/ingestion/source/aws/s3_boto_utils.py
metadata-ingestion/src/datahub/ingestion/source/delta_lake/config.py
metadata-ingestion/src/datahub/ingestion/source/s3/config.py

The `AwsSourceConfig` contains some extra config options and was
poluting the source config tables on the generated docs.

fix(ingest): use `AwsConnectionConfig` instead of `AwsSourceConfig`

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py

fix(ingest): profiling - memory usage reduction

---

metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeLogProcessor.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/MetadataChangeLogHook.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/event/EntityChangeEventGeneratorHook.java
metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/event/EntityChangeEventGeneratorHookTest.java
metadata-service/factories/src/main/resources/application.yml

Adds the possibility to skip MCL processor hooks. 
Starts with adding toggle for Entity Change Events.

feat(hooks): Add toggle for enabling/disabling platform event hook

---

metadata-ingestion/scripts/docgen.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

Relying on the correct import directly, rather than going through SQLAlchemy's import wrapper (in their dialect.py) allows us to bypass this strange error in doc generation.

fix(ingest): fix doc generation import ordering issue with postgres

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py

chore(ingest): remove outdated GE compatibility hack

---

metadata-ingestion/scripts/datahub_preflight.sh

fix(m1): preflight works with brew postgres@14

---

datahub-web-react/src/app/domain/DomainListItem.tsx
datahub-web-react/src/app/entity/shared/constants.ts
datahub-web-react/src/app/identity/group/GroupListItem.tsx

Adds clarity to domain list page for domains that have more than 10,000 elements

fix(domains): adding 10,000+ text when domain list caps out elastic count capacity

---

docker/datahub-frontend/Dockerfile
docker/datahub-gms/Dockerfile
docker/datahub-mae-consumer/Dockerfile
docker/datahub-mce-consumer/Dockerfile
docker/datahub-upgrade/Dockerfile
docker/kafka-setup/Dockerfile

Bumps JRE11 version from `"11.0.14"` to `"11.0.16.1"` which includes container support.
Validated by running: `docker run --rm -it -m 1GB datahub-mae-consumer-test java -XX:+UnlockDiagnosticVMOptions -XshowSettings:vm -version`
Where `datahub-mae-consumer-test` is a locally built image.

fix(docker): Bumps JRE 11 to latest

---

metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-ingestion/src/datahub/configuration/config_loader.py

feat(ingest): support reading config file from stdin

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
metadata-ingestion/tests/integration/dbt/test_dbt.py

This option was added for backwards compat and can be dropped now.

fix(ingest): remove dbt `delete_tests_as_datasets` option

---

metadata-ingestion/setup.py
metadata-ingestion/tests/unit/serde/test_serde.py

See https://github.com/acryldata/avro_gen/pull/13

fix(ingest): avrogen handling for missing fields with default values

---

metadata-ingestion/src/datahub/configuration/source_common.py
metadata-ingestion/src/datahub/utilities/urns/data_flow_urn.py
metadata-ingestion/src/datahub/utilities/urns/dataset_urn.py

refactor(ingest): add ALL_ENV_TYPES constant

---

.github/workflows/publish-datahub-jars.yml
metadata-integration/java/datahub-client/build.gradle
metadata-integration/java/datahub-protobuf/build.gradle
metadata-integration/java/spark-lineage/build.gradle
metadata-integration/java/versioning.gradle

Supports SNAPSHOT, rc versioning schemas.

feat(jars): better jar versioning for datahub-client, spark-lineage and protobuf

---

docker/docker-compose.dev.yml

fix(dev-docker): set right context for frontend dev build

---

datahub-web-react/package.json
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx
datahub-web-react/src/app/entity/dataset/profile/schema/utils/schemaTitleRenderer.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/__tests__/filterSchemaRows.test.ts
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/filterSchemaRows.ts
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/getSchemaFilterFromQueryString.ts
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/updateSchemaFilterQueryString.ts
datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useTagsAndTermsRenderer.tsx
datahub-web-react/src/app/shared/tags/TagTermGroup.tsx
datahub-web-react/yarn.lock
smoke-test/tests/cypress/cypress/integration/mutations/mutations.js

Adds the ability to filter search in the schema tab for datasets. Now you can type in the search bar and it will find fields where either their `fieldPath`, their glossary terms, or their tags match the filter text. Highlight what is matched in the UI.
Also, when making changes to the filter text we set a new query param in the url so that you can link someone to a filtered schema.
Here's what it looks like!

feat(schema) Add search filter to Schema tab

---

datahub-web-react/src/app/entity/shared/EntitySearchInput/EntitySearchInput.tsx
datahub-web-react/src/app/entity/shared/EntitySearchInput/EntitySearchInputResult.tsx

Creates a new generalized component that allows you to search and select entities of a given type. This can and will be used in different forms across the app.

feat(ui) Add entity search input to shared folder

---

metadata-ingestion/src/datahub/ingestion/graph/client.py
metadata-ingestion/src/datahub/ingestion/reporting/datahub_ingestion_reporting_provider.py
metadata-ingestion/src/datahub/ingestion/run/pipeline_config.py
metadata-ingestion/tests/unit/test_pipeline.py

fix(ingest): datahub-api - move instantiation to the right config class

---

datahub-frontend/app/controllers/Application.java

When Host header is forwarded as-is, service meshes such as Istio will erroneously send the request to the the host specified there instead of the intended target.

fix(frontend): forward Host header as X-Forwarded-Host

---

metadata-ingestion/src/datahub/ingestion/api/registry.py
metadata-ingestion/src/datahub/ingestion/api/sink.py
metadata-ingestion/src/datahub/ingestion/sink/console.py
metadata-ingestion/src/datahub/ingestion/sink/datahub_kafka.py
metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
metadata-ingestion/src/datahub/ingestion/sink/file.py
metadata-ingestion/src/datahub/ingestion/sink/sink_registry.py
metadata-ingestion/tests/test_helpers/sink_helpers.py
metadata-ingestion/tests/unit/test_kafka_sink.py

Overall this should reduce the amount of code required to define a sink type.

feat(ingest): make sink use type annotations

---

metadata-ingestion/src/datahub/emitter/mcp.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/integrations/great_expectations/action.py
metadata-ingestion/tests/unit/test_mcp_builder.py
metadata-ingestion/tests/unit/test_usage_common.py

feat(ingest): add entity type inference to mcpw

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/tests/integration/snowflake-beta/snowflake_beta_golden.json
metadata-ingestion/tests/integration/snowflake-beta/test_snowflake_beta.py
metadata-ingestion/tests/unit/test_snowflake_beta_source.py
metadata-ingestion/tests/unit/test_usage_common.py

- Reduce verbosity of source report. Report dropped columns only if `profiling.report_dropped_profiles` is set
- some minor refractors for clarity and robustness
- unit tests for snowflake-beta

feat(ingest): minor changes in snowflake-beta source, add basic tests

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/Constants.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/BatchLoadUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/BatchGetEntitiesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/EntityTypeBatchResolver.java
datahub-graphql-core/src/main/resources/entity.graphql

Adds a new endpoint to graphql that allows you to supply a list of entity urns of any type and get their resolved entities. Leverages work done in the `BatchGetEntities` resolver that only resolves entities of the same type (since we leverage the entity type loaders) to put that logic into a batch load utility class and share with my new resolver. The new resolver bunches the urns into groups based on entity type and resolves each batch of urns based on type together.

feat(graphql) Add new 'entities' endpoint to batch get entities by urn

---

docker/datahub-ingestion/base-requirements.txt

fix(docker): skip zoneinfo backport on newer python versions

---

.github/workflows/close-stale-issues.yml

We are not processing older issues because of some limits https://github.com/actions/stale#operations-per-run. It makes more sense to process in ascending order so older things are processed first.

fix(ci): process older issues first

---

docs/modeling/extending-the-metadata-model.md
entity-registry/src/main/java/com/linkedin/metadata/models/annotation/SearchableAnnotation.java
entity-registry/src/test/java/com/linkedin/metadata/models/EntitySpecBuilderTest.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/MappingsBuilder.java
metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java
metadata-io/src/test/java/com/linkedin/metadata/TestEntityUtil.java
metadata-io/src/test/java/com/linkedin/metadata/extractor/FieldExtractorTest.java
metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/MappingsBuilderTest.java
metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilderTest.java
metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandlerTest.java
metadata-io/src/test/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformerTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/SearchDocumentTransformerFactory.java
metadata-service/factories/src/main/resources/application.yml
test-models/src/main/pegasus/com/datahub/test/TestEntityInfo.pdl

This change will add support for object field type through `@Searchable` annotations. 
As large number of keys on an object field type would create equally large number of columns in the index - I've also added a setting `elasticsearch.index.maxObjectKeys` to limit how many keys can be indexed.

feat(search): Add support for Elasticsearch object field type

---

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_schema_terms.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_terms.py

Usage of `AuditStampClass.construct_with_defaults()` introduced in this [commit](https://github.com/datahub-project/datahub/commit/2f65e2f226123ab115c8960922213f631d9c001e) create AuditStamp with empty string actor urn, leading to invalid record. Reverting to auditStamp entry, that was used earlier.
Issue was reported on [Slack](https://datahubspace.slack.com/archives/C029A3M079U/p1662968709729969)

fix(transformer): fix invalid lastModified.actor entry in transformers

---

metadata-ingestion/src/datahub/ingestion/source/git/git_import.py
metadata-ingestion/tests/integration/git/test_git_clone.py

feat(ingest): skip ssh known_hosts verification for git clone

---

datahub-web-react/src/app/ingest/source/builder/RecipeForm/FormField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/lookml.tsx

Secrets do not work with ssh keys right now. Instead, let's allow them to paste the key in this text area to set on the recipe. I auto add a new line for them to format properly.

fix(ui) Make LookML deploy key a textarea and format key

---

metadata-ingestion/src/datahub/ingestion/source/git/git_import.py

fix(ingest): add trailing newline to ssh keys

---

docs/lineage/airflow.md

I read airflow integration(https://datahubproject.io/docs/lineage/airflow/#using-datahubs-airflow-lineage-plugin-new), and found that `datahub_conn_id` should be changed to `conn_id`.
I add some conversation with @treff7es in Slack (https://datahubspace.slack.com/archives/C029A3M079U/p1663069150243549?thread_ts=1662611232.747409&cid=C029A3M079U)
This is my first contribution..!
If something is wrong, plz let me know!
Thank you.

docs: datahub_conn_id => conn_id in Airflow Integration

---

docs/lineage/airflow.md

Seems https://github.com/datahub-project/datahub/pull/5703 was accidentally reverted.

docs(airflow) add back auth token info for airflow

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/container/mappers/ContainerMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
metadata-ingestion/src/datahub/emitter/mcp_builder.py
metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
metadata-ingestion/tests/unit/glue/glue_deleted_actor_mces_golden.json
metadata-ingestion/tests/unit/glue/glue_mces_golden.json
metadata-ingestion/tests/unit/glue/glue_mces_platform_instance_golden.json
metadata-ingestion/tests/unit/test_glue_source_stubs.py

This PR brings 2 changes:
1. It seemed that ContainerProperties lacked qualifiedName field when querying GMS GraphQL (even though it was there in .pdl files). This PR adds this field of ContainerProperties to the graphQL definition and ContainerMapper so it can be retrieved for a container.
2. Glue connector stores ARN for each entity it ingests (table and database) as qualifiedName. ARN for glue resources is not available in AWS REST API response (this is confirmed by AWS documentation), so we build it on the fly according to the methodology described by AWS docs.

feat: qualifiedName support + populating glue ARN

---

docker/elasticsearch-setup/create-indices.sh

feat(elastic-setup): add better error handling

---

metadata-ingestion/docs/sources/mysql/mysql_recipe.yml

docs(ingest): add example of ssl with mysql

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
datahub-graphql-core/src/main/resources/ingestion.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolverTest.java
datahub-web-react/src/app/ingest/source/builder/DefineRecipeStep.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeBuilder.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/RecipeForm.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/TestConnection/TestConnectionButton.tsx

If there's a CLI version of ingestion set on this source, use that when running test connections. Otherwise continue to use the default as normal.

feat(ingestion-ui) Use CLI version defined in recipe for test connection

---

metadata-ingestion/src/datahub/ingestion/source/s3/config.py
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_files.json
metadata-ingestion/tests/integration/s3/test_s3.py

Issue reported on [Slack](https://datahubspace.slack.com/archives/CUMUWQU66/p1663170116868469?thread_ts=1663022987.129919&cid=CUMUWQU66)

fix(ingest): continue validation of s3 path_specs even if platform is set

---

docker/elasticsearch-setup/create-indices.sh

PR #5887 caused a failure in the elasticsearch-setup script when insecure mode is not used, due to a sneaky bug. 
```
curl -o /dev/null .. -s "$ELASTICSEARCH_INSECURE" "$ELASTICSEARCH_PROTOCOL://...." 
will result in:
curl -o /dev/null .. -s "" "http://localhost:9002/..." 
which results in curl trying to hit 2 urls... the first being an empty string. 
```
This PR fixes this by re-attaching the ELASTICSEARCH_INSECURE flag to the beginning of the url 
`"${ELASTICSEARCH_INSECURE}$ELASTICSEARCH_PROTOCOL://..."`
a better fix would probably be to refactor the CURL_OPTS into a separate variable that adds the `-k` flag if needed. 
Would like to get this PR in first to limit the refactor. 
Tested locally by building the docker image and verifying that a clean quickstart now completes cleanly with …

fix(quickstart): elasticsearch-setup script fails on curl

---

.github/workflows/build-and-test.yml
metadata-ingestion-modules/airflow-plugin/setup.py

This should make the build-and-test job fast again.
Also removes edge case handling for datahub-frontend unzipAssets, since this was fixed by #3452 and should not be an issue anymore.

ci: reduce pip backtracking in airflow plugin

---

metadata-ingestion/setup.py

Issue raised on [Slack](https://datahubspace.slack.com/archives/C029A3M079U/p1663583509751329)

fix(ingest): pin great-expectations dependency to fix profiling error

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
metadata-ingestion/tests/integration/looker/golden_test_allow_ingest.json
metadata-ingestion/tests/integration/looker/golden_test_ingest.json
metadata-ingestion/tests/integration/looker/golden_test_ingest_joins.json
metadata-ingestion/tests/integration/looker/golden_test_ingest_unaliased_joins.json
metadata-ingestion/tests/integration/looker/looker_mces_usage_history.json
metadata-ingestion/tests/integration/lookml/expected_output.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_deny_pattern.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json
metadata-ingestion/tests/integration/lookml/lookml_reachable_views.json

**Summary**
In this PR, we migrate the browse paths produced by looker sources to the new format, which does NOT mandate that the path ends with the asset's name or id. Learn more about the migration here: https://github.com/datahub-project/datahub/blob/648d10c16e2591e43b96f930997fa5490e27aa06/docs/advanced/browse-paths-upgrade.md

refactor(looker): Migrating to new browse path format 

---

docs-website/sidebars.js
metadata-ingestion/schedule_docs/kubernetes.md

Adds documentation on how to use DataHub's ingestion cron sub chart to schedule ingestion runs in Kubernetes.

feat(docs): Adds docs on K8s scheduled ingestion

---

metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
metadata-ingestion/tests/integration/presto-on-hive/docker-compose.yml
metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_1.json
metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_2.json
metadata-ingestion/tests/integration/presto-on-hive/test_presto_on_hive.py

1. Stateful ingestion for presto on hive
2. `use_catalog_subtype` bool config. I think most people refer those as Catalog instead but defaulted to Database
3. `use_dataset_pascalcase_subtype` bool config. Giving people the choice of PascalCase for subtype due to subtype like example `MLFeatureType` and we didn't want this `mlfeaturetype`
4. Updated test to better cover Presto view and new configs
I think we can add Trino integration test to this next time, since most people have shifted to Trino already.
(Most Presto related images in the docker-compose are really old)

feat(ingest): presto-on-hive stateful, catalog and pascalcase subtype config

---

docs/cli.md
metadata-ingestion/src/datahub/cli/put_cli.py
metadata-integration/java/datahub-protobuf/README.md

Adds support to create a dataplatform entity using the cli. 
e.g.
```
datahub put platform --name custom_platform --logo https://custom_platform_logo.png --display_name "Custom Platform"
```

feat(cli): extend put command to support platform creation

---

datahub-frontend/app/controllers/Application.java
datahub-frontend/app/controllers/AuthenticationController.java
datahub-frontend/app/controllers/CentralLogoutController.java
datahub-frontend/app/security/AuthenticationManager.java

**Summary**
In this PR, we address a few improvements to datahub-frontend container, including:
1. Case insensitive compare when removing X-DataHub-Actor header
2. Verifying that the relative path provided in URL starts with a slash
3. Explicitly deleting Play session on logout 
4. Catching all errors during JaaS login, failing closed
**Status**
READY FOR REVIEW

refactor(frontend): Misc frontend improvements

---

docs-website/docusaurus.config.js

This is not a full fix - desktop looks better but mobile is still pretty bad.

fix(docs-site): make banner a bit smaller

---

metadata-ingestion/src/datahub/cli/docker_cli.py

feat(ingest): add --no-pull-images option to docker quickstart

---

datahub-web-react/src/app/ingest/secret/SecretsList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/permissions/roles/ManageRoles.tsx

Worked to hide the recent search from search bar

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java
metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
metadata-io/src/main/java/com/linkedin/metadata/search/cache/CachedEntityLineageResult.java
metadata-io/src/test/java/com/linkedin/metadata/search/LineageSearchServiceTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/LineageSearchServiceFactory.java
metadata-service/factories/src/main/resources/application.yml

fix(gms): Write back lineage search results to in-memory cache bound to feature flag

---

docs-website/docusaurus.config.js
docs-website/src/styles/global.scss

The docusaurus version update changed the class names on the announcement bar which broke the custom styles for it. Adjusting the selector brought back the styles. Also updated the link url while I was in there.

fix(docs-site): style custom announcement bar

---

metadata-ingestion/src/datahub/ingestion/source/state/dbt_state.py
metadata-ingestion/src/datahub/ingestion/source/state/kafka_state.py
metadata-ingestion/src/datahub/ingestion/source/state/sql_common_state.py
metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
metadata-ingestion/tests/integration/dbt/test_dbt.py
metadata-ingestion/tests/integration/kafka/test_kafka_state.py
metadata-ingestion/tests/unit/test_glue_source.py
metadata-ingestion/tests/unit/test_kafka_source.py
smoke-test/tests/test_stateful_ingestion.py

This PR adds fail-safe mode to the stateful ingestion `Stale Entity Removal` use-case.
If the percentage of entities that have changed in the current run relative to the previous state is above the configurable `fail_safe_threshold`, then the fail-safe mode will trigger and
1. the stale entity removal work units won't be emitted corresponding the removed entities in the current run.
2. the latest state won't be committed.

feat(ingestion): Add fail-safe stale entity removal via configurable 'fail_safe_threshold' param.

---

metadata-ingestion/src/datahub/configuration/kafka.py
metadata-ingestion/src/datahub/configuration/validate_field_rename.py
metadata-ingestion/src/datahub/configuration/validate_host_port.py
metadata-ingestion/src/datahub/emitter/kafka_emitter.py
metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
metadata-ingestion/tests/unit/test_elasticsearch_source.py
metadata-ingestion/tests/unit/test_kafka_emitter.py

refactor(ingest): move common host_port validation

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/configuration/common.py
metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py

- Adds support for `external_id` and other options in `assume_role`
- Makes it possible to use assume_role in conjunction with the other credential configs.
- Improves docs for all AWS config options.

feat(ingest): aws - support extra args to role config

---

datahub-frontend/app/client/AuthServiceClient.java
datahub-frontend/app/controllers/AuthenticationController.java
datahub-frontend/conf/routes

Refactors AuthServiceClient to:
- Create JSON requests using Jackson ObjectMapper to guard against JSON injection
- Migrate away from using deprecated methods under the Play framework. Note there are a still few left to migrate

fix(frontend): refactoring AuthServiceClient

---

metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatelessTokenService.java
metadata-service/auth-impl/src/test/java/com/datahub/authentication/token/StatelessTokenServiceTest.java

**Summary**
In this PR, we improve how JWTs are parsed by the StatelessTokenService. We ensure that the token is signed by a specific signature and also treat as a JWS. 
**Status**

refactor(gms): Improving JWT parsing logic

---

datahub-web-react/src/app/analytics/event.ts
datahub-web-react/src/app/browse/BrowseResults.tsx
datahub-web-react/src/app/home/HomePage.tsx
datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/search/BrowseEntityCard.tsx

feat(tracking): add additional home page telemetry

---

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

- Getting datasets with biquery client instad of with SQL query because it did not work everywhere
- Changing lists to lossylist in report
- Fixing table name

fix(ingest): bigquery-beta - Getting datasets with biquery client

---

metadata-ingestion/docs/sources/dbt/dbt.md

Removed the yaml/json switcher + reformatted the markdown.

docs(ingest): add example of dbt column_meta_mapping

---

datahub-web-react/src/App.tsx
datahub-web-react/src/app/entity/dataPlatform/DataPlatformEntity.tsx

**Summary**
Adding an explicit UI entity for a data platform. This will be needed in the near future. For now, it simply serves as a placeholder. 
**Status**

feat(ui): Adding placeholder entity for DataPlatform

---

metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
metadata-ingestion/tests/unit/stateful_ingestion/state/test_checkpoint.py

Stateful ingestion - add and enable by default bz2 compression and base85 encoding for CheckpointState

feat(ingest): implement compression for CheckpointState

---

datahub-web-react/src/app/entity/container/ContainerEntity.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/action/GlossaryTermsDropdown.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/action/TagsDropdown.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Container/ContainerSelectModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/EditOwnersModal.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Platform/SelectPlatformModal.tsx
datahub-web-react/src/app/search/AdvancedFilterSelectValueModal.tsx
datahub-web-react/src/app/search/ChooseEntityTypeModal.tsx
datahub-web-react/src/app/search/EditTextModal.tsx
datahub-web-react/src/app/shared/tags/AddTagsTermsModal.tsx
datahub-web-react/src/app/shared/tags/TagTermGroup.tsx
datahub-web-react/src/app/shared/tags/TagTermLabel.tsx

This is a helper component that advanced search filters will use to select values.

feat(advanced-search): adding select value modal

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/src/datahub/ingestion/source/redash.py
metadata-ingestion/src/datahub/integrations/great_expectations/action.py
metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py
metadata-ingestion/src/datahub/utilities/sql_parser.py
metadata-ingestion/src/datahub/utilities/sql_parser_base.py

- Apply lineage extraction enable parameter for views as well
- Range partitioned tables are partitioned on the last partition
- Making lineage parser exceptions less verbose to don't freak out users
- Fixing invalid partition in report

fix(ingest): bigquery-beta - Additional fixes for Bigquery beta

---

metadata-ingestion/docs/sources/s3/s3.md

docs(ingest): add path spec examples for s3

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaBlameMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/utils/TimelineUtils.java
metadata-io/build.gradle
metadata-io/src/main/java/com/linkedin/metadata/timeline/SemanticVersion.java
metadata-io/src/main/java/com/linkedin/metadata/timeline/TimelineServiceImpl.java

fix(deps): metadata-io - remove parquet dependency

---

metadata-ingestion/src/datahub/configuration/config_loader.py
metadata-ingestion/tests/unit/config/test_config_loader.py

feat(ingest): list referenced env variables in recipe

---

SECURITY.md
docs-website/generateDocsDir.ts

docs: create SECURITY.md

---

metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
metadata-io/src/main/java/com/linkedin/metadata/search/client/CachingEntitySearchService.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java

**Summary**
In this PR, we improve the browse feature performance via 2 changes:
1. Remove wasteful, unnecessary aggregations performed in our browse query to elastic search. 
2. Add a browse path cache to make subsequent traversals painless.
These improvements will especially be noticeable at scale! 
**Summary**

refactor(browse): Improving Browse Feature Performance

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py

Other changes
- fix missing view upstream lineage
- remove customProperties with column-lineage info
Note:
- Direct Column level lineage is available only for tables(as downstream) and not for views(as downstream).
- The bag of columns lineage as available in customProperties earlier is not used as fine grained lineage, but could be used if required with small code change, if required.

feat(ingest): add column-level lineage support for snowflake

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/tests/integration/lookml/expected_output.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json
metadata-ingestion/tests/integration/lookml/lookml_reachable_views.json

Adds very simple column level lineage for looker
Table -> View
and 
View -> Explore.

feat(ingest): looker - support for simple column level lineage

---

docker/elasticsearch-setup/create-indices.sh

Fixes https://github.com/datahub-project/datahub/issues/6060, tested locally by reproducing issue with Quickstart, building the updated image and deploying it using quickstart.

fix(elastic-setup) Fixing env var logic

---

metadata-ingestion/src/datahub/ingestion/source/source_registry.py

Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1664374799979859?thread_ts=1664289608.112209&cid=CUMUWQU66

fix(ingest): alias for mssql-odbc source

---

metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_1.json
metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_2.json

fix(ingest): presto-on-hive - Setting display name properly

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx

If no `expandedRowsFromFilter` is provided then the schema will infinite rerender. This breaks Chart pages for Looker charts with inputs.

fix(schema filter): fix schema infinite rerender

---

metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py

Regex was overly broad and matching whitespace as well.

fix(ingest): lookml - extract column correctly

---

.github/pr-labeler-config.yml
metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/RetentionService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraRetentionService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanRetentionService.java
metadata-io/src/main/java/com/linkedin/metadata/entity/retention/BulkApplyRetentionArgs.java
metadata-io/src/main/java/com/linkedin/metadata/entity/retention/BulkApplyRetentionResult.java
metadata-service/restli-api/src/main/idl/com.linkedin.entity.entities.restspec.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
metadata-service/war/src/main/resources/boot/retention.yaml

feat(retention): change default policy, add API to apply retention

---

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py

- Lowering a bit of memory footprint of bigquery usage
- Filtering out not seen tables from usage generation

fix(ingest): bigquery-beta - Lowering a bit memory footprint of bigquery usage

---

docs/quickstart.md

docs: add information about mapping ports for datahub-gms

---

docker/datahub-mae-consumer/start.sh

JDK_JAVA_OPTIONS is loaded twice by java (probably alpine bug).
As a workaround using: JAVA_TOOL_OPTIONS

fix(mae): use JAVA_TOOL_OPTIONS instead of JDK_JAVA_OPTIONS

---

datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/dataset/DatasetSearchSnippet.tsx
datahub-web-react/src/app/entity/shared/__tests__/utils.test.ts
datahub-web-react/src/app/entity/shared/utils.ts

1. We used to only show search snippets for datasets if there was no description or title match. Now, we will show them regardless.
2. We used to just pluck out the first search snippet that came back & was relevant. Now, we do a few passes to try and find the best search snippet based on your query.
Added some unit tests & comments since we are encoding some business logic in this utility.

feat(search): improved search snippet FE logic

---

datahub-frontend/play.gradle
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/post/CreatePostResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/post/ListPostsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/post/PostMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/post/CreatePostResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/post/ListPostsResolverTest.java
datahub-web-react/src/app/home/HomePagePosts.tsx
datahub-web-react/src/app/home/HomePageRecommendations.tsx
datahub-web-react/src/app/search/PostLinkCard.tsx
datahub-web-react/src/app/search/PostTextCard.tsx
datahub-web-react/src/graphql/mutations.graphql
datahub-web-react/src/graphql/post.graphql
li-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-models/src/main/pegasus/com/linkedin/common/Media.pdl
metadata-models/src/main/pegasus/com/linkedin/common/MediaType.pdl
metadata-models/src/main/pegasus/com/linkedin/metadata/key/PostKey.pdl
metadata-models/src/main/pegasus/com/linkedin/post/PostContent.pdl
metadata-models/src/main/pegasus/com/linkedin/post/PostContentType.pdl
metadata-models/src/main/pegasus/com/linkedin/post/PostInfo.pdl
metadata-models/src/main/pegasus/com/linkedin/post/PostType.pdl
metadata-models/src/main/resources/entity-registry.yml
metadata-service/auth-impl/src/main/java/com/datahub/authentication/post/PostService.java
metadata-service/auth-impl/src/test/java/com/datahub/authentication/post/PostServiceTest.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/PostServiceFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

feat(posts): add posts feature to DataHub

---

metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
metadata-ingestion/tests/unit/stateful_ingestion/state/test_stale_entity_removal_handler.py

1. Fixes the bug in percent change computation for stale entity removal
2. Changes the `fail_safe_threshold` value to 20.0 from 95.0 per our discussion.

fix(ingestion): fix percent change computation in stale_entity_removal

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py

refactor(ingest): use pydantic utilities for NamingPattern

---

metadata-ingestion/src/datahub/ingestion/api/committable.py
metadata-ingestion/src/datahub/ingestion/api/common.py
metadata-ingestion/src/datahub/ingestion/api/source.py

Possible now that we're on mypy 0.980. It used to have issues with `@dataclass` on abstract classes, but was fixed by https://github.com/python/mypy/pull/13398.

refactor(ingest): remove typing workarounds

---

docs/authentication/guides/sso/configure-oidc-react-okta.md

Added information about AUTH_OIDC_EXTRACT_GROUPS_ENABLED

---

datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts

Allows option to see full name of a task (data flow . task) in lineage viz.

feat(lineage): show fully qualified task name in lineage UI

---

metadata-ingestion/docs/sources/bigquery/bigquery-beta_pre.md
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py

- updating bigquery permission doc
- adding some more context if no dataset or project returned

fix(ingest): bigquery-beta -  fix for missing key error if dataset list was empty

---

datahub-web-react/src/graphql/search.graphql

We fetch input fields to enrich search snippets when relevant, but its causing some perf issues for large dashboards. Temporarily disabling that fetch for now.

perf(search): temporarily disable fetching input fields for search results

---

datahub-frontend/app/auth/AuthModule.java
datahub-frontend/app/client/AuthServiceClient.java
datahub-frontend/app/controllers/TrackingController.java
datahub-frontend/conf/routes
li-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-service/auth-impl/src/main/java/com/datahub/telemetry/TrackingService.java
metadata-service/auth-impl/src/test/java/com/datahub/telemetry/TrackingServiceTest.java
metadata-service/auth-servlet-impl/src/main/java/com/datahub/authentication/AuthServiceController.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/MixpanelApiFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/MixpanelMessageBuilderFactory.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/TelemetryUtils.java
metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/TrackingServiceFactory.java

feat(tracking): add telemetry for frontend events

---

metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
metadata-ingestion/tests/integration/tableau/setup/workbooksConnection_all.json
metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json

The code to populate the tags is already in place, however the graphql query was not fetching the tags earlier.

fix(ingest): fetch workbook tags in workbooks graphql query

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UpstreamLineagesMapper.java

If there's no upstreams or downstreams on fineGrainedLineage then we get a null pointer exception. Adds a check to ensure they exist before mapping them to the final result object.

fix(lineage) Fix possible null pointer exception in UpstreamLineagesMapper

---

metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java

Properly batch the urns that we send to elasticsearch for the searchAcrossLineage endpoint. ES can only take 65,000 terms at once, so we batch into sets of 50,000, but we were actually still sending all the urns to it anyways. Now let's send only the batched urns!

fix(lineage) Fix batching to ES for impact analysis

---

datahub-web-react/src/app/entity/domain/DomainEntitiesTab.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
datahub-web-react/src/app/entity/shared/tabs/Lineage/generateUseSearchResultsViaRelationshipHook.ts
smoke-test/tests/cypress/cypress/integration/lineage/impact_analysis.js

Fixed a bug that was introduced with a final refactor of the filters. Also adding a few cypress tests to cover common cases of impact analysis to prevent this from happening in the future.

fix(impact analysis): fixing filtering on impact analysis + cypress tests

---

datahub-web-react/README.md

Add docs for customizing the favicon of your datahub installation

docs(favicon): add docs for customizing favicon

---

datahub-web-react/src/app/ingest/source/builder/DefineRecipeStep.tsx
datahub-web-react/src/app/ingest/source/builder/LookerWarning.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeBuilder.tsx

feat(ui): looker, lookml - add banner to cross-link ingestion

---

metadata-ingestion/examples/library/dataset_add_column_tag.py
metadata-ingestion/examples/library/dataset_add_column_term.py
metadata-ingestion/examples/library/dataset_add_documentation.py
metadata-ingestion/examples/library/dataset_add_owner.py
metadata-ingestion/examples/library/dataset_add_tag.py
metadata-ingestion/examples/library/dataset_add_term.py
metadata-ingestion/src/datahub/ingestion/graph/client.py
metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
metadata-ingestion/src/datahub/ingestion/source/aws/s3_boto_utils.py
metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
metadata-ingestion/tests/unit/test_csv_enricher_source.py

feat(ingest): infer aspect name from type in get_aspect

---

datahub-web-react/src/app/ingest/secret/SecretBuilderModal.tsx

Previously we had a regular input as the value field for secrets. Then we changed that to type "Password" so that the browser doesn't automatically remember the value (for security reasons). However we also want to allow mutliline secret values (like ssh keys) so the values field is now a textarea. Browsers don't automatically save textarea values like they do for inputs, so we will be good there security-wise. Just to be safe I put `autoComplete="false" to ensure the browser isn't saving this value.
On top of that I fixed a bug where after you save a secret and open up the modal again, the old values remained populated. We needed to be calling `form.resetValues` as well as resetting the state.

feat(secrets) Allow creating secrets with multiline values in the UI

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json

feat(ingest/tableau): support dashboard tags

---

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
metadata-ingestion/tests/unit/test_bigquery_lineage.py

- Parsing view ddl definition for lineage
- Fixing lineage generation when edge was not generated if query contained view and dataset as well
- Changing default values

feat(ingest): bigquery-beta - Parsing view ddl definition for lineage

---

docs-website/sidebars.js
docs/posts.md

docs(posts): add posts feature guide

---

metadata-ingestion/setup.py

- ujson 5.2.0 has the JSONDecodeError type, which we need https://github.com/ultrajson/ultrajson/releases/tag/5.2.0 for our error handling
- FIxes https://github.com/datahub-project/datahub/issues/6181

fix(ingest): add lower bound for ujson dep version

---

metadata-ingestion/src/datahub/ingestion/api/workunit.py
metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
metadata-ingestion/src/datahub/ingestion/source/state/tableau_state.py
metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/src/datahub/utilities/source_helpers.py
metadata-ingestion/tests/integration/tableau/tableau_mces_golden_deleted_stateful.json

- Emit status aspects for all entities
- Track containers in stateful ingestion
- Simplify stateful ingestion code

feat(ingest/tableau): emit status aspects + streamline stateful ingestion

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

feat(ingest): support self-signed certs in Tableau

---

datahub-web-react/src/app/entity/glossaryNode/ChildrenTab.tsx
datahub-web-react/src/app/glossary/GlossaryBrowser/NodeItem.tsx
datahub-web-react/src/app/glossary/GlossaryEntitiesList.tsx
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/glossaryNode.graphql

Improves the performance of our business glossary by reducing the amount of information we're fetching from the server. We were overfetching and getting data that we didn't use that more than doubled the amount of trips to the graph index. This should significantly improve loading times for larger glossaries with lots of terms under nodes.
I also add a loading spinner on the side when data is loading and fix loading UI on a term group page to not show the "empty glossary" state when data is still loading.

fix(glossary) Improve business glossary loading performance

---

metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
metadata-ingestion/tests/unit/stateful_ingestion/state/test_checkpoint.py

The previous base85 implementation used pickle to serialize and deserialize state. This would throw an error if the state model ever changed. See this SO answer for context on pickle's lack of backwards compatibility: https://stackoverflow.com/questions/64894061/renaming-python-package-with-backwards-compatibility-for-pickle. 
Other benefits:
- Pickle allows arbitrary code execution which is a pretty unexpected attack vector, so it'd be good to get rid of it.
- Using base85 + bz2 + JSON is actually smaller than base85 + bz2 + pickle.

feat(ingest): replace base85's pickle with json

---

docker/datahub-frontend/env/docker.env
docker/datahub-frontend/start.sh

Add custom truststore settings. It is required for frontend to use self-signed certificates to connect 3rd party services

feat(frontend): add custom ssl truststore settings

---

metadata-integration/java/spark-lineage/README.md

docs(spark): add configuration instructions for databricks

---

docs/what/relationship.md
metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py

fix(ingest): use corpGroup instead of corpgroup

---

metadata-ingestion/setup.py

Follow-up on https://github.com/datahub-project/datahub/pull/5980.
Related to https://github.com/great-expectations/great_expectations/issues/6146.

fix(ingest): only restrict GE version for hive

---

metadata-ingestion/setup.py
metadata-ingestion/tests/test_helpers/docker_helpers.py

This will help improve compat with newer versions of Airflow.
**markupsafe**: It looks like the aws-sam-cli package has updated their versions appropriately, which means that we are clear to remove this. Note: I'm not sure where we're actually depending on aws-sam-cli, since it never gets installed for me locally despite all sources being enabled.
**pytest-docker**: This was a simple upgrade - moving to 1.x introduced some extra non-defaulted parameters, so we just needed to fill those out.
Previous PRs:
- https://github.com/datahub-project/datahub/pull/4188
- https://github.com/datahub-project/datahub/pull/4388
- https://github.com/datahub-project/datahub/pull/4639

build(ingest): remove markupsafe dep and bump pytest-docker

---

datahub-web-react/src/app/glossary/GlossaryBrowser/GlossaryBrowser.tsx
datahub-web-react/src/app/glossary/GlossaryBrowser/TermItem.tsx
datahub-web-react/src/app/glossary/GlossaryEntitiesList.tsx
datahub-web-react/src/graphql/glossary.graphql
datahub-web-react/src/graphql/glossaryNode.graphql

Similar to the previous glossary performance PR, this reduces overfetching when getting root glossary terms to minimize the number of trips to our graph index. Now, fetch only the fields we need for the UI.

fix(glossary) Improve performance when getting root glossary terms

---

datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/constants.ts
datahub-web-react/src/app/ingest/source/builder/sources.json

Removes the option `include_view_lineage` from bigquery and redshift UI sources as that field doesn't exist on those sources. Instead, have the option just be for `include_table_lineage` instead of both.

fix(ui) Fix bigquery and redshift forms for lineage fields

---

datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
datahub-web-react/src/app/lineage/utils/useSortColumnsBySelectedField.ts

Fixes column-level lineage with v2 field paths to always use v1 field paths. This is necessary because `fineGrainedLineage` always produces v1 field paths while `schemaMetadata` on the entity uses v2 field paths. So we just need to be consistent here. So I always convert fields to v1 field paths when creating our source of truth `columnsByUrn`.

fix(ui) Properly display column-level lineage with v2 field paths

---

datahub-web-react/src/app/analytics/event.ts
datahub-web-react/src/app/domain/CreateDomainModal.tsx
datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
metadata-service/auth-impl/src/main/java/com/datahub/telemetry/TrackingService.java

feat(telemetry): add telemetry events to the glossary, domains, and managed ingestion pages

---

metadata-ingestion/src/datahub/ingestion/source/tableau_common.py

fix(ingest): remove back-ticks from table name when creating urn

---

metadata-ingestion/src/datahub/emitter/mce_builder.py
metadata-ingestion/src/datahub/utilities/checkpoint_state_util.py

fix(ingest): stateful-ingestion - keep dataset urn case in checkpoints

---

datahub-web-react/src/app/shared/constants.ts
datahub-web-react/src/app/shared/tags/AddTagsTermsModal.tsx

Create Tag Modal Issue: Clear the input value on press.

---

smoke-test/tests/cypress/cypress/integration/glossary/glossary.js
smoke-test/tests/cypress/cypress/integration/mutations/deprecations.js
smoke-test/tests/cypress/cypress/integration/mutations/mutations.js
smoke-test/tests/cypress/cypress/support/commands.js

feat(build): add cypress tests for glossary and deprecation

---

metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py

Don't create schema container if it is filtered out

feat(ingest): hive-on-presto - Add option to properly filter hive schemas

---

datahub-frontend/app/controllers/SsoCallbackController.java
datahub-frontend/run/frontend.env

**Summary**
- Previously we stored the entire pac4j OIDC profile in the user cookie, in encrypted form. This sometimes caused the OIDC cookie to grow too large, when attributes grew beyond a certain size. In this PR we remove that cookie, as it's not strictly required for subsequent requests.
**Status**

fix(oidc): Avoid storing Pac4j profile in cookie 

---

metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlySearchedSource.java
metadata-io/src/main/java/com/linkedin/metadata/search/cache/CacheableSearcher.java
metadata-io/src/main/java/com/linkedin/metadata/search/client/CachingEntitySearchService.java
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java

feat(metrics): add metrics around search caching

---

datahub-web-react/package.json
datahub-web-react/src/App.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/shared/EntityHead.tsx
datahub-web-react/yarn.lock

Currently it's hard for users to navigate DataHub when there's multiple tabs opened because all the tab titles would be labelled 'DataHub'. This PR helps to resolve this UX by adding the Entity's Name and SubType/Type to the browser tab's title in the format:
@aezomz 
```
<entityName> | <subType or type>
```
- Added `react-helmet` to help manage the `<title />`
- Added `<EntityHead />` to render entity titles
- Added `<title />` on `App.tsx` to allow falling back to default title when navigating away from the entity page

feat(ui): display entity names in browser tab titles

---

datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
datahub-web-react/src/app/entity/container/preview/Preview.tsx
datahub-web-react/src/app/entity/dashboard/preview/DashboardPreview.tsx
datahub-web-react/src/app/entity/dataFlow/preview/Preview.tsx
datahub-web-react/src/app/entity/dataJob/preview/Preview.tsx
datahub-web-react/src/app/entity/dataset/preview/Preview.tsx
datahub-web-react/src/app/entity/domain/preview/Preview.tsx
datahub-web-react/src/app/entity/glossaryNode/preview/Preview.tsx
datahub-web-react/src/app/entity/glossaryTerm/preview/Preview.tsx
datahub-web-react/src/app/entity/mlFeature/preview/Preview.tsx
datahub-web-react/src/app/entity/mlFeatureTable/preview/Preview.tsx
datahub-web-react/src/app/entity/mlModel/preview/Preview.tsx
datahub-web-react/src/app/entity/mlModelGroup/preview/Preview.tsx
datahub-web-react/src/app/entity/mlPrimaryKey/preview/Preview.tsx
datahub-web-react/src/app/entity/shared/ExternalUrlButton.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
datahub-web-react/src/app/entity/tag/Tag.tsx
datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx

We often hear that people use the `externalUrl` aspect to send links to github, and it looks weird if the button says "View in Looker" and takes you to github. As a quick solution, check if the link contains "github.com" and if so, display "View in GitHub".
Also this does some refactoring to bring the two uses of this link into one shared component.

feat(ui) Display 'View in Github' if externalUrl is link to GitHub

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/src/datahub/utilities/sql_parser.py
metadata-ingestion/src/datahub/utilities/sql_parser_base.py
metadata-ingestion/tests/conftest.py
metadata-ingestion/tests/integration/lookml/expected_output.json
metadata-ingestion/tests/integration/lookml/lkml_samples/ability.view.lkml
metadata-ingestion/tests/integration/lookml/lkml_samples/data.model.lkml
metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json
metadata-ingestion/tests/integration/lookml/lookml_reachable_views.json
metadata-ingestion/tests/test_helpers/mce_helpers.py

This PR fixes a few issues:
- looker connector dependencies: combined dependencies for both looker and lookml
- fixes explore -> view lineage for fields
- improves sql parsing for lookml views
- limits column level lineage inference only for non-sql based views (sql parsing for column level lineage will be addressed later)
- adds a config flag to control external process spawning for sql parsing

fix(ingest): looker - deps, column level lineage fixes

---

metadata-ingestion/src/datahub/ingestion/graph/client.py

The [Issue 5542](https://github.com/datahub-project/datahub/issues/5542) might have been closed prematurely - the _disable_ssl_verification_ value was not passed to DatahubRestEmitter.

fix(ingestion): passing disable_ssl_verification param value to DatahubRestEmitter

---

docs/quickstart.md
docs/wip/get-started.md
metadata-ingestion/src/datahub/cli/docker_check.py
metadata-ingestion/src/datahub/cli/docker_cli.py

This PR fixes a couple of issues:
- Docker desktop 4.13 introduces the preference of using user-level sockets, which make the docker python library fail on instantiating a docker client. [Example issue](https://github.com/docker/for-mac/issues/6529) where this is affecting other projects as well. We now look for the user-level socket if the default docker client instantiation fails. A longer term fix might be to remove our dependency on the docker python lib and use os.subprocess exclusively for all docker operations.
- Detection of Apple silicon can be buggy if terminal emulation is enabled or the installed python is x86 based. We add a `--arch` option to allow the specification of architecture explicitly as a stop-gap measure while we improve our detection logic.

fix(quickstart): support for user-level sockets, arch option for forcing quickstart architecture

---

datahub-web-react/src/app/lineage/utils/layoutTree.ts
metadata-io/src/main/java/com/linkedin/metadata/graph/SiblingGraphService.java
metadata-io/src/test/java/com/linkedin/metadata/graph/sibling/SiblingGraphServiceTest.java
smoke-test/tests/cypress/cypress/integration/siblings/siblings.js

Fixes two bugs we've seen with lineage visualization for a bit now.
1. Switching your base/center node (by double clicking another node) causes a duplicate of the previous base node and weird dragging behavior. Fix this on the frontend by adding a check to ensure we don't render the same node twice. When we were drawing the tree, we were rendering the base node two times (once for upstream and once for downstream), and that would throw off our tree causing a duplication of the previous node if we had a previous base node.
2. Sometimes dragging nodes would cause replication of arrows/edges between nodes looking very weird. This would only happen when Compress Lineage was on (so we would get lineage for all siblings and combine them). What was happening is that if two siblings have the same …

fix(ui) Fix two lineage visualization bugs

---

docs/how/updating-datahub.md
metadata-ingestion/src/datahub/ingestion/source/dbt.py

fix(ingest/dbt): lowercase external urns + cleanup config

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ResolverUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionRunEventResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/TimeSeriesAspectResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionRunEventResolverTest.java

This pr: https://github.com/datahub-project/datahub/commit/ce90310dd0c7cc8506006cb667bbd7d4deb2070b
Introduced a change where filter creation added the `.keyword` suffix to the elasticsearch query for status. However, based on the es mapping of this timeseries index, the `status` field of the assertion run result was not a `.keyword` field.
Reverting this.

fix(assertion tab): fixing up regression in assertion resolver

---

datahub-web-react/src/app/ingest/source/builder/RecipeForm/SecretField/SecretField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx

Now allow users to type whatever text they want in secret field while still being able to select from a list of existing secrets and create a secret on the fly.
Do this by changing the input type from `Select` to `AutoComplete` with the secrets as options to select and filter down from (if you start typing). If you don't select anything from the dropdown, we store whatever it is that you're typing as your value then.
Things still look the same.

feat(ui) Allow a user to type in a custom value in ingestion Secret Fields

---

datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx

When creating Terms and Nodes, now allow users to input their desired documentation so they don't have to immediately do and add it afterwords. All the backend/graphql stuff is already in place for this so it's just adding this piece to the modal.
Here we are:
**When clicking add documentation:**
**After adding it, it now says "Edit Documentation" which you can click to see your documentation or edit it**

feat(ui) Add documentation to term/node creation modal

---

metadata-ingestion/docs/transformer/dataset_transformer.md

The interface changed in #5514 to switch from DatasetSnapshotClass to entity_urn as string.
Updated the docs accordingly

fix(docs): fix custom transformer example interface

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/mappers/InputFieldsMapper.java
datahub-web-react/src/app/entity/EntityRegistry.tsx
datahub-web-react/src/app/lineage/LineageEntityColumns.tsx
datahub-web-react/src/app/lineage/LineageEntityNode.tsx
datahub-web-react/src/app/lineage/types.ts
datahub-web-react/src/app/lineage/utils/__tests__/columnLineageUtils.test.tsx
datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
datahub-web-react/src/app/lineage/utils/constructTree.ts
datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
datahub-web-react/src/app/lineage/utils/layoutTree.ts
datahub-web-react/src/app/lineage/utils/titleUtils.ts
datahub-web-react/src/app/lineage/utils/useSortColumnsBySelectedField.ts
datahub-web-react/src/graphql/lineage.graphql

Add the wirings to render `inputFields` from charts and dashboards just like we do for schema fields on datasets. `inputFields` have a `SchemaField` underneath them so the main piece of work is just getting this new aspect from the entity at hand, mapping over the `inputFields` to get their `schemaField` objects, and passing those around to render and be added to our `fineGrainedMap`. This includes displaying lineage between columns as well.
In order to display lineage for `inputFields` we are simply getting the `schemaFieldUrn` which maps to the upstream schemaField that this inputField comes from. Usually the source is from some upstream Explore, in which case we can draw the edge between the explore's field and the chart's field. Less common, the `schemaFieldUrn` references the chart …

feat(ui) Display inputFields in column-lineage visualization

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
datahub-web-react/src/app/lineage/LineageExplorer.tsx
datahub-web-react/src/app/settings/AccessTokens.tsx

- Added Sorted methods to the usage column
- Worked on the Entity type name issue on Lineage Side Drawer

Worked on the Usage column & Lineage Drawer

---

datahub-web-react/src/app/entity/shared/EntityDropdown/EntityDropdown.tsx
datahub-web-react/src/graphql/glossaryNode.graphql

If a term group has children, disable the ability to delete it from the UI. This is a degradation from another fix, just putting it back to how it was.
Soon we'd like to allow the ability to delete the whole tree underneath the node, but this is a quick revert to the way things used to work.

fix(ui) Disable deleting Term Groups with children

---

datahub-web-react/src/app/entity/dataset/DatasetSearchSnippet.tsx
datahub-web-react/src/app/entity/shared/__tests__/siblingsUtils.test.ts
datahub-web-react/src/app/entity/shared/siblingUtils.ts
datahub-web-react/src/graphql/dataset.graphql

1) When there is no primary sibling, whichever urn is being fetch in the query wins out. Added tests for this logic as well.
2) Downgrade field paths in search snippets.

fix(ui): two small ux fixes

---

datahub-web-react/src/graphql/container.graphql
datahub-web-react/src/graphql/domain.graphql

fix(perf): trim down unnecessary fields from container and domain GraphQl queries

---

metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java

Making sure that es utils properly does query expansion for edited tags.

fix(adv search): fixing typo in es utils

---

datahub-web-react/src/app/entity/domain/DomainEntity.tsx
datahub-web-react/src/app/entity/glossaryNode/GlossaryNodeEntity.tsx
datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/ownershipUtils.ts

Based on multiple requests, we are enabling Ownership Type on Glossary Node + Domains. We already have for all asset types + Glossary Terms.

Enable Owner Type for Glossary Node + Domain 

---

datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchSection.tsx

Remove filters from `baseParams` so that we can properly remove filters from the EmbeddedListSearch component. If query params are not starting with `filter` then we want to keep them so they don't get overwritten on the Lineage Tab for impact analysis.

fix(ui) Fix filters in embedded list search component

---

metadata-ingestion/src/datahub/ingestion/run/pipeline.py

Without this, logging calls will throw an error.
We really should add linting for this, but only pylint has logging-format-interpolation and the flake8 support for this warning is lacking.

fix(ingest): fix log line interpolation

---

datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx

fix(schema-history): remove unnecessary margin on version selector

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/auth/AccessTokenUtil.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/entity/EntityPrivilegesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/AddRelatedTermsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryNodeResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryTermResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/DeleteGlossaryEntityResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/RemoveRelatedTermsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateNameResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateParentNodeResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/GlossaryUtils.java
datahub-graphql-core/src/main/resources/auth.graphql
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/entity/EntityPrivilegesResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/GlossaryUtilsTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/UpdateNameResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/glossary/UpdateParentNodeResolverTest.java
datahub-web-react/src/app/entity/shared/EntityDropdown/EntityDropdown.tsx
datahub-web-react/src/app/entity/shared/containers/profile/__tests__/EntityHeader.test.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/graphql/glossaryNode.graphql
datahub-web-react/src/graphql/glossaryTerm.graphql
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

This PR does a few things, all with the goal of allowing users to manage children of entities using our permissions framework. Specifically, the desire was to allow a way for users to allow owners of Glossary Nodes to create, delete, and move Terms and Nodes underneath it. So this PR creates the generic privileges than apply to Nodes but could be applied to other entities. Same thing with a new GraphQL privileges object on an entity. Broken down:
- Create a new `Manage Children` privilege that's applied to Glossary Nodes right now
- Create utility class for Glossary entities to check privileges and other shared methods (including privileges for managing children)
- Create new `EntityPrivileges` object that can be returned on an entity itself
- Create new `EntityPrivilegesResolver` to …

feat(privileges) Create privileges to allow for managing children of entities

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaRow.tsx
datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionDescription.tsx
datahub-web-react/src/app/entity/shared/tabs/Lineage/utils.ts
datahub-web-react/src/app/lineage/utils/__tests__/columnLineageUtils.test.tsx
datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
datahub-web-react/src/app/preview/EntityPaths/ColumnsRelationshipText.tsx
datahub-web-react/src/app/preview/EntityPaths/DisplayedColumns.tsx
metadata-ingestion/src/datahub/utilities/urn_encoder.py

Our ingestion crew had to encode `schemaField` urns so that the `fieldPath` of the schema is encoding a few special characters (`(`, `)`, and `,`). We need to decode those on the frontend wherever we display fieldPaths that we get from `upstreamLineage` aspects. We also need to encode fieldPaths for CLL impact analysis since the urn in our graph index will have the encoded urns.
I also added a comment where we ingestion calls this encoding to make sure they are always in sync with the frontend code as well.

fix(ui) Handle encoded schemaField urns on the frontend

---

datahub-web-react/src/app/entity/container/ContainerEntitiesTab.tsx
datahub-web-react/src/app/entity/domain/DomainEntitiesTab.tsx
datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedEntity.tsx
datahub-web-react/src/app/entity/group/GroupAssets.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/DownloadAsCsvModal.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchHeader.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchModal.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchSection.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/SearchExtendedMenu.tsx
datahub-web-react/src/app/entity/shared/components/styled/search/navigateToEntitySearchUrl.ts
datahub-web-react/src/app/entity/shared/components/styled/search/types.ts
datahub-web-react/src/app/entity/user/UserAssets.tsx
datahub-web-react/src/app/ingest/source/IngestedAssets.tsx
datahub-web-react/src/app/search/SearchFiltersSection.tsx
datahub-web-react/src/app/search/SearchResults.tsx
datahub-web-react/src/app/search/__tests__/filterUtils.test.tsx
datahub-web-react/src/app/search/utils/constants.ts
datahub-web-react/src/app/search/utils/filterUtils.ts
datahub-web-react/src/app/shared/TagStyleEntity.tsx
metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
smoke-test/tests/cypress/cypress.json
smoke-test/tests/cypress/cypress/integration/glossary/glossaryTerm.js
smoke-test/tests/cypress/cypress/integration/search/search.js
smoke-test/tests/cypress/data.json

In this PR we remove dependency on the search query string for looking up entities related to a given glossary term or tag.  This makes the result set much more reliable, as previously special characters in the URN of a glossary or tag URN could cause failures to match at the indexing layer (do to how we tokenize the urn). This fixes those issues.
Ready to Review. Working on some final cypress tests to cover this.

refactor(ui): Refactor the Glossary Related Entities, Tag Profiles to use search filters instead of query API. 

---

metadata-ingestion/README.md
metadata-ingestion/src/datahub/cli/check_cli.py
metadata-ingestion/src/datahub/cli/get_cli.py
metadata-ingestion/src/datahub/cli/ingest_cli.py
metadata-ingestion/src/datahub/cli/timeline_cli.py
metadata-ingestion/src/datahub/configuration/__init__.py
metadata-ingestion/src/datahub/configuration/common.py
metadata-ingestion/src/datahub/entrypoints.py
metadata-ingestion/src/datahub/ingestion/reporting/datahub_ingestion_run_summary_provider.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py

Adds a global `--debug-vars` flag, which is disabled by default. Removes the SensitiveError type, which was producing confusing error messages.

fix(ingest): only log vars if requested

---

docker/datahub-ingestion/base.Dockerfile

The `acryldata/datahub-ingestion` image is missing Java, meaning that the Kafka connect ingestion can't be run. This is fixed in the PR by installing openjdk 11 JRE in the base ingestion image. This fixes https://github.com/datahub-project/datahub/issues/6310 and possibly also https://github.com/datahub-project/datahub/issues/4741
The fix was tested like this:
```
docker build -t acryldata/datahub-ingestion-base  -f docker/datahub-ingestion/base.Dockerfile .
docker build -t acryldata/datahub-ingestion  -f docker/datahub-ingestion/Dockerfile .
docker run -it --entrypoint="/bin/bash" acryldata/datahub-ingestion 
$ java --version 
> openjdk 11.0.16 2022-07-19
> OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
> OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, …
```

Install openjdk in base ingestion image

---

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

feat(ingest): enable container stateful ingestion

---

metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py

fix(ingest): unity - add missing date type

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

feat(ingest/tableau): re-authenticate if the token expires

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage.py

Currently, if columns are returned as None from snowflake query, such error is thrown - 
`TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

fix(ingest): handle error when query returns no columns in snowflake lineage

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/tests/integration/snowflake-beta/test_snowflake_beta.py

fix(ingest): fix missing snowflake lineage when table_pattern is set

---

metadata-ingestion/src/datahub/ingestion/source/s3/source.py
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_file_without_extension.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_no_partition.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_no_partition_exclude.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_no_partition_filename.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_no_partition_glob.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_partition_basic.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_folder_partition_keyval.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_multiple_files.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_multiple_spec_for_files.json
metadata-ingestion/tests/integration/s3/golden-files/local/golden_mces_single_file.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_file_without_extension.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_exclude.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_filename.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_glob.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_basic.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_keyval.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_files.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_spec_for_files.json
metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_single_file.json

[Issue](https://datahubspace.slack.com/archives/C029A3M079U/p1667284071274729) reported on slack

fix(ingest/s3): add status aspect for detected s3 datasets

---

metadata-ingestion/setup.py

SQLAlchemy version 1.4.42 removed a function that the snowflake package used - see https://github.com/snowflakedb/snowflake-sqlalchemy/issues/350. Since `snowflake-sqlalchemy` 1.4.3 fixes that bug, we need to loosen our requirements to support it.
Follow up for https://github.com/datahub-project/datahub/pull/6204.

fix(ingest/snowflake): loosen snowflake connector version requirement

---

metadata-service/factories/src/main/java/com/linkedin/gms/factory/timeline/EntityChangeEventGeneratorRegistryFactory.java

fix(change-event): remove unnecessary dependencies on EntityChangeEventGeneratorRegistryFactory

---

docker/datahub-mae-consumer/start.sh

JMX_OPTS and JAVA_OPTS are properly expanded in start.sh script of MAE docker image. Before they were missing dollar sign (`$`) and instead of being expanded, in case they were defined, they were passed as strings causing exception like below in MAE container:
```
Picked up JAVA_TOOL_OPTIONS:  JMX_OPTS
Unrecognized option: JMX_OPTS
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

fix(mae-consumer): Set proper variable expansion for JMX_OPTS and JAVA_OPTS in MAE docker

---

datahub-web-react/src/graphql/dataset.graphql

Improves the performance of loading datasets by reducing the amount of information being fetched from the graph database. Data was being fetched that wasn't used and resulted in potentially hundreds of calls to the graph database. This issue is explained more in issue #6395.
The heavy use of fragments in the affected portion of the graphql query means that the problematic code (in the [glossaryNode fragment](https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/fragments.graphql#:~:text=%7D-,fragment%20glossaryNode%20on%20GlossaryNode%20%7B,%7D,-fragment%20glossaryTerm%20on)) cannot be changed directly as this additional information is needed by other queries which use this fragment, namely [getGlossaryNode()](https://github.com/datahub-project/datahub/blob/m …

fix(dataset): improve glossary term load performance for datasets

---

datahub-web-react/src/app/entity/shared/tabs/Lineage/ColumnLineageSelect.tsx
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
metadata-jobs/mae-consumer/src/test/resources/test-entity-registry.yml

Currently, impact analysis only works for `fineGrainedLineage` but it needs to work for `inputFields` as well. Both of these aspects use `schemaFields` so all the infrastructure for fetching impact analysis for schema fields is already there, we just were not indexing `inputFields` to draw lines between `schemaFields` like we were for the `upstreamLineage` aspect yet. This adds that step to draw those edges manually.
Something to note is that we need to encode the `fieldPath` of the `schemaField` urn that we generate for the graph index. this is because ingestion always does that for `schemaField` urns but here we are creating a schemaField urn from the `schemaField` prop of `inputFields` and the `fieldPath` there is not encoded. `schemaField` urns need to be consistent across our DB and …

feat(lineage) Implement CLL impact analysis for inputFields

---

metadata-service/factories/src/main/java/com/linkedin/metadata/boot/factories/BootstrapManagerFactory.java
metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/RestoreColumnLineageIndices.java
metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/RestoreColumnLineageIndicesTest.java

Adds a new upgrade step for restoring indices for the `upstreamLineage` aspects as well as the `inputFields` aspect. The `upstreamLineage` aspect has `fineGrainedLineage` that needs to be reindexed with our new logic for impact analysis. Same this with `inputFields`. After this, users will have their graph index set up properly to do impact analysis with all columns.

feat(ui) Add upgrade step to enable CLL impact analysis for existing data

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/MenuColumn.tsx

Added functionality to copy fieldpath and urn of each column

---

datahub-web-react/src/graphql/dataset.graphql
datahub-web-react/src/graphql/fragments.graphql

Builds off of what was done in [this PR](https://github.com/datahub-project/datahub/pull/6396) and makes it more generalized so everyone benefits from the lack of overfecthing.
Basically we don't need `children` from each of the parentNodes and this was causing many more trips to the graph index for no reason.

fix(ui) Fix parentNodes overfetching everywhere it's used

---

metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py

Not sure why CI passed on https://github.com/datahub-project/datahub/pull/6134 though

chore(ingest): fix mssql lint

---

datahub-web-react/src/app/glossary/BusinessGlossaryPage.tsx

When a user has a long glossary term / term group name and you switch tabs on a term/node page, the width of the sidebar browser flickers and that looks bad. This fixes it by setting the `width` as well as the `min-width` of the sidebar. It's still dynamic based on page size when you load the page.
**Here's what it looked like before:**
https://user-images.githubusercontent.com/28656603/202214666-2049fe85-05f8-475d-947c-8dfb3927735e.mov
**Here's what it looks like with this change:**
https://user-images.githubusercontent.com/28656603/202214860-078d80b4-8597-4ec0-a6e9-1913b9869b85.mov

fix(ui) Fix glossary side browser width fluctuating

---

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_schema_tags.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_schema_terms.py

Handles the case when `schema_metadata_aspect` is None.

fix(ingest): handle missing schema in transformer

---

datahub-web-react/src/app/home/HomePageBody.tsx
datahub-web-react/src/app/home/HomePageRecommendations.tsx

fix(home-page): remove redundant getAuthenticatedUser query

---

docs/quickstart.md
metadata-ingestion/src/datahub/cli/docker_check.py
metadata-ingestion/src/datahub/cli/docker_cli.py
metadata-ingestion/tests/integration/sql_server/test_sql_server.py

feat(ingest): detect old or missing docker compose

---

metadata-ingestion/src/datahub/ingestion/source/dbt.py
metadata-ingestion/tests/integration/dbt/test_dbt.py

Temporary fix due to an issue in GMS. Can be reverted once that is resolved.

fix(ingest/dbt): disable incremental lineage by default

---

metadata-ingestion/docs/sources/trino/trino_recipe.yml

Via https://datahubspace.slack.com/archives/C029A3M079U/p1668552189392719?thread_ts=1666881195.949359&cid=C029A3M079U.

docs(ingest/trino): add example of http connection

---

datahub-web-react/src/app/glossary/BusinessGlossaryPage.tsx

Removing the duplicative "browse" bar in the Glossary page.
Before:
After:

refactor(ui): Simplify base glossary page toolbar  

---

metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py

This reverts commit cf6fb91f8dbf180b5a54ee9af701a26e608f2737.

revert: mssql - lowercase db name in mssql ingestion

---

metadata-ingestion/setup.py

`Jinja2` dependencies not needed in `Superset` extra

build: remove `Jinja2` dependency from `superset`

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/role/AcceptRoleResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/role/BatchAssignRoleResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/role/ListRolesResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/role/AcceptRoleResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/role/BatchAssignRoleResolverTest.java
datahub-web-react/src/app/identity/user/AssignRoleConfirmation.tsx
datahub-web-react/src/app/identity/user/SelectRole.tsx
datahub-web-react/src/app/identity/user/UserList.tsx
metadata-service/auth-impl/src/main/java/com/datahub/authentication/invite/InviteTokenService.java
metadata-service/auth-impl/src/main/java/com/datahub/authorization/role/RoleService.java
metadata-service/auth-impl/src/test/java/com/datahub/authorization/RoleServiceTest.java

Admins can now remove roles, or send an invite link with No Role attached to remove a role from a user

fix(roles): allows role service to unassign roles

---

metadata-ingestion/examples/library/dataset_add_owner.py

fix: ownership type is deprecated
the ownership type is deprecated (described in OwnershipTypeClass), thats why it should be changed from DATAOWNER to TECHNICAL_OWNER

Ownership type is deprecated

---

datahub-web-react/src/app/analytics/event.ts
datahub-web-react/src/app/home/HomePageHeader.tsx
datahub-web-react/src/app/search/SearchBar.tsx

Adding a button for browsing all entities from the Home page. This allows users to start exploring before they know exactly what exists inside of DataHub. 
https://user-images.githubusercontent.com/17549204/202368305-1082a09f-cccf-472c-b0bb-9b847798bd6e.mov

feat(ui): Adding Explore all button on home page search

---

datahub-web-react/src/app/lineage/LineageTreeNodeAndEdgeRenderer.tsx
metadata-io/src/main/java/com/linkedin/metadata/graph/SiblingGraphService.java
metadata-io/src/test/java/com/linkedin/metadata/graph/sibling/SiblingGraphServiceTest.java

We were seeing an issue where users would drag a node on the lineage viz graph and arrows would be replicated and it looked real bad. This was happening when siblings would have the same lineage as each other, so we would render duplicate nodes causing the viz to get all wacky. This filters out duplicates when combining sibling lineage.
Also adds a safety measure on the frontend as well to ensure all edges have unique keys _just in case_ someone wants duplicate edges on their lineage graph (saw this in OSS slack once). The arrows were bugging out because the `key`s were not all unique.

fix(ui) Fix lineage graph rendering with duplicate nodes

---

metadata-service/README.md

[Issue](https://datahubspace.slack.com/archives/CV2KB471C/p1667368057551499) reported on Slack

docs(gms): update search example, do not use deprecated  clause

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/src/datahub/ingestion/source/state/looker_state.py
metadata-ingestion/src/datahub/ingestion/source/state/lookml_state.py
metadata-ingestion/tests/integration/looker/golden_looker_mces.json
metadata-ingestion/tests/integration/looker/golden_test_allow_ingest.json
metadata-ingestion/tests/integration/looker/looker_mces_golden_deleted_stateful.json
metadata-ingestion/tests/integration/looker/test_looker.py
metadata-ingestion/tests/integration/lookml/lookml_mces_golden_deleted_stateful.json
metadata-ingestion/tests/integration/lookml/test_lookml.py

feat(ingest): add stateful ingestion support to looker and lookml source

---

metadata-ingestion/src/datahub/ingestion/source/tableau.py

We were previously seeing this error:
```
AttributeError: 'NoneType' object has no attribute 'get'
```

fix(tableau): extra defensive error-handling

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/cli/docker_cli.py
metadata-ingestion/src/datahub/cli/ingest_cli.py

Possible since https://github.com/python/typeshed/pull/9220 was merged.

fix(ingest): remove redundant types

---

docs-website/sidebars.js
docs/how/updating-datahub.md

Moving the doc to top-level as updating is part of managing a deployment and not an advanced operation.

fix(docs): add missing docs for 0.9.1

---

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_browse_path.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_properties.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_tags.py
metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_terms.py
metadata-ingestion/src/datahub/ingestion/transformer/dataset_domain.py
metadata-ingestion/src/datahub/ingestion/transformer/remove_dataset_ownership.py
metadata-ingestion/tests/unit/test_transform_dataset.py

The ownership transformer contains a clever optimization, where if it is set to PATCH and does not need to make any changes, no aspect is generated. The surrounding code did not handle this logic correctly, and would issue an upsert with the original ownership object, hence overwriting anything that lived on the server. This bug would only be triggered if the server already contained a superset of what the transformer was trying to add.
Many other dataset transformers also had a similar, subtle bug. For example, if using the `pattern_add_dataset_tags` transformer and a no new tags applied to a given dataset, the server's tags would get overwritten even if PATCH was specified. This PR should also resolve that class of bugs.
Tested manually with the ownership, props, and tags transformers.

fix(ingest): correctly handle transformer patch semantics

---

.github/actions/docker-custom-build-and-push/action.yml
.github/workflows/docker-feast-source.yml
.github/workflows/docker-ingestion-base.yml
.github/workflows/docker-ingestion-smoke.yml
.github/workflows/docker-ingestion.yml
.github/workflows/docker-postgres-setup.yml
.github/workflows/docker-unified.yml
.github/workflows/metadata-model.yml
.github/workflows/publish-datahub-jars.yml

This does not completely solve the problem. But 53 warnings -> 21 warnings in docker unified workflow.
ref https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
ref https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Asked https://github.com/ishworkh/docker-image-artifact-download/issues/8 regarding a new release with upgrade nodejs version

fix(build): remove warnings in github actions

---

metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py

feat(ingest): disable stateful_ingestion fail-safe by default

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/CreateDomainResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/ListDomainsResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/domain/CreateDomainProposalMatcher.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/domain/CreateDomainResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/domain/ListDomainsResolverTest.java
datahub-web-react/src/app/domain/CreateDomainModal.tsx
datahub-web-react/src/app/domain/DomainListItem.tsx
datahub-web-react/src/app/domain/DomainsList.tsx
datahub-web-react/src/app/domain/utils.ts
datahub-web-react/src/graphql/domain.graphql
li-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-models/src/main/pegasus/com/linkedin/domain/DomainProperties.pdl

In this PR, we do our first POC of list view caching on the Domains page. No longer will we have the 3 second delay to see newly created domains. Also when navigating between pages, the Domains will be cached so another fetch is not required. 
As part of this, I also added a new indexed field to Domains index that tracks the "created time" of a Domain. This allows us to consistently and correctly sort the list of domains, even when a new one is added locally. 
https://user-images.githubusercontent.com/17549204/202796754-1ba8668f-e0d0-428c-9a64-e0527e90cd7b.mov

refactor(ui): Adding apollo caching to manage domains page. 

---

metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/MostPopularSource.java
metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlyEditedSource.java
metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlyViewedSource.java
metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecommendationUtils.java
metadata-io/src/test/java/com/linkedin/metadata/recommendation/candidatesource/RecommendationUtilsTest.java

Recently an issue was introduced wherein we will serve last edited recommendations for ANY entity type. Unfortunately this causes issues for Entity Types which are not well supported by the UI. So to gate this, we are adding a specific set of entity types that are considered "in scope" for recommendations including Most Popular, Recently Viewed, and Recently Edited. This will ensure that entities which are surfaced can be rendered properly by the UI.

refactor(recommendations): Filtering for specific entity types in recommendations

---

datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx

Schema field descriptions that were sufficiently long were getting cut off so that we couldn't see the "Read More" option to expand the description. All it takes is passing in a simple `shouldWrap` prop to the component and then "Read More" wraps when the description is too long to always show it.
**How it looked before:**
**How it looks now**

fix(ui) Wrap schema field descriptions to allow read more/less always

---

metadata-ingestion/src/datahub/ingestion/source/superset.py

style(ingest): fix lint checks for superset

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py

fix(ingest): bigquery - missing sqlalchemy dep and row count fix

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py

Adding to the source report the number of non-eligible tables for profiling

fix(ingest): bigquery - Fixing querying non-date partition columns in profiling

---

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py

- Setting partition id for profiling data
- Don't list projects if project_id is set to eliminate the need for `resourcemanager.projects.list` permission

fix(ingest): bigquery - Setting partition id for profiling data and project_id fix

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/cli/docker_cli.py

fix(ingest): handle docker-compose version `v` prefix

---

li-utils/src/main/pegasus/com/linkedin/common/TimeStamp.pdl
metadata-models/src/main/pegasus/com/linkedin/container/ContainerProperties.pdl
metadata-models/src/main/pegasus/com/linkedin/datajob/DataFlowInfo.pdl
metadata-models/src/main/pegasus/com/linkedin/datajob/DataJobInfo.pdl
metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProperties.pdl
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json

Adding a 'createdAt' timestamp to Datasets, Containers, DataJobs, DataFlows. This is useful for reporting the native platform created time for data assets when ingesting into DataHub. 
We are not using an AuditStamp here because the Actor field inside is _required_. We do not always know that the actor will be resolvable to an URN for created actions, so we are choosing to omit for now. 

feat(models): Adding 'created', 'lastModified' timestamp to Dataset, Container, Dashboard, Chart

---

metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py

In the dataJob runs tab (which shows dataProcessInstances), the "Time" column displays the `dataProcessInstanceProperties.created` timestamp. This change makes the emitter actually show the start times when provided.
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1669108847712609?thread_ts=1669020230.808929&cid=CUMUWQU66

fix(ingest): set DataProcessInstance created ts to start time

---

smoke-test/tests/delete/delete_test.py

This is required since a delete executed for the healthcheck prevents the actual test from working because elasticsearch recalls that the fixture was deleted for around 60s.

fix(test): fix delete smoke test

---

datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
docs/how/updating-datahub.md
gradle/versioning/versioning.gradle

Changes as part of 0.9.3 release.

chore(): Updating default CLI version, update updating-datahub.md

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py

Fix for `UnboundLocalError: local variable 'nonnull_count' referenced before assignment` error

fix(ingest): profiling - Profiling failed if column cardinality threw an error

---

metadata-ingestion/docs/sources/bigquery/bigquery-legacy_pre.md
metadata-ingestion/docs/sources/bigquery/bigquery_pre.md
metadata-ingestion/examples/recipes/bigquery_to_datahub.dhub.yaml
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
metadata-ingestion/src/datahub/ingestion/source/profiling/common.py
metadata-ingestion/src/datahub/ingestion/source/s3/profiling.py
metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source_config/sql/bigquery.py

feat(ingest/bigquery): avoid creating/deleting tables for profiling

---

build.gradle
buildSrc/build.gradle
datahub-frontend/play.gradle
datahub-ranger-plugin/build.gradle
entity-registry/build.gradle
metadata-io/build.gradle
metadata-service/auth-ranger-impl/build.gradle

fix(security): security version updates

---

docs/architecture/metadata-ingestion.md
docs/architecture/metadata-serving.md
metadata-jobs/README.md
metadata-jobs/mae-consumer-job/README.md
metadata-jobs/mce-consumer-job/README.md

docs: remove Kafka Streams from documentation

---

datahub-web-react/src/app/domain/CreateDomainModal.tsx
datahub-web-react/src/app/ingest/secret/SecretBuilderModal.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/DictField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/FormField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/RecipeForm.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/SecretField/CreateSecretButton.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/SecretField/SecretField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/kafka.ts
datahub-web-react/src/app/ingest/source/builder/sources.json
datahub-web-react/src/app/ingest/source/conf/kafka/kafka.ts

In this PR, we introduce various improvements to Kafka Ingestion Form, Create Domain Form, Create Secret Form, and UI ingestion more broadly.
- Support Form Fields changing the value of the form.. (by passing the FormInstance object as a prop) 
- Support required / optional Form Fields 
- Support clearing Form Field selects
- AutoPopulate Input Fields once secrets are created (see video below) 
- Refactor Create Domain Form to correctly support suggested names, and to correctly display 'Create' button
- Refactor Create Secret Form to remove use of state, migrate to using Ant forms. Correctly display 'Create' button
- Fix: Make secret names more restrictive in type. Exclude special characters. 
- Fix: Fix Kafka default ingestion source bug (extra ' ) 
- Fix: Improve the copy for tooltips …

refactor(ui): Improving Kafka UI Ingestion Form, Create Domain, Create Secret Modals 

---

docker/datahub-gms/start.sh

This PR resolves a security _risk_ (not vuln) where credentials are logged in plaintext during GMS docker start.sh execution.

fix(gms/startup): remove set -x from start.sh

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/tests/integration/snowflake-beta/snowflake_beta_golden.json
metadata-ingestion/tests/integration/snowflake-beta/snowflake_privatelink_beta_golden.json
metadata-ingestion/tests/integration/snowflake-beta/test_snowflake_beta.py

feat(ingest): add external url for snowflake objects

---

metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py

fix(ingest): only require github_info for lookml and not looker

---

metadata-ingestion/schedule_docs/airflow.md
metadata-ingestion/setup.py
metadata-ingestion/src/datahub_provider/example_dags/.airflowignore
metadata-ingestion/src/datahub_provider/example_dags/generic_recipe_sample_dag.py
metadata-ingestion/src/datahub_provider/example_dags/mysql_sample_dag.py
metadata-ingestion/src/datahub_provider/example_dags/snowflake_sample_dag.py
metadata-ingestion/tests/unit/test_airflow.py

docs(ingest): add airflow docs that use the `PythonVirtualenvOperator`

---

datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx
datahub-web-react/src/app/search/AdvancedSearchFilters.tsx
datahub-web-react/src/app/search/SearchFiltersSection.tsx
datahub-web-react/src/app/search/SimpleSearchFilters.tsx

Fixes a situation where filters were not scrolling by themselves and were causing a double scroll in embedded list search situations by adding correct scrolling behavior inside of filters (advanced and basic).
**Before:**
https://user-images.githubusercontent.com/28656603/205368635-4825f5ae-ce56-473d-b9c1-c0ab88824530.mov
**After:**
https://user-images.githubusercontent.com/28656603/205368416-4382167d-efbc-480e-8026-3e0de5ecf398.mov

fix(ui) Fix double scroll in embedded list search sections

---

datahub-web-react/src/app/analyticsDashboard/components/AnalyticsPage.tsx

fix(analytics): skip ListDomains if user cannot manage domains and have only one loading message

---

docs/how/updating-datahub.md
metadata-ingestion/src/datahub/configuration/pattern_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/tests/integration/snowflake-beta/test_snowflake_beta.py

feat(ingest/snowflake): support filtering by fully qualified schema_pattern

---

entity-registry/src/main/java/com/linkedin/metadata/models/annotation/RelationshipAnnotation.java
entity-registry/src/test/java/com/linkedin/metadata/models/registry/LineageRegistryTest.java
metadata-io/src/main/java/com/linkedin/metadata/graph/Edge.java
metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ElasticSearchGraphService.java
metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java
metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/ElasticSearchGraphServiceTest.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/GraphIndexUtils.java
metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/GraphIndexUtilsTest.java
metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java

This PR adds the mechanism to define what the `createdOn` and `updatedOn` timestamps are on a graph index edge as well as the `createdActor` and `updatedActor`. In order to specify, all you need to do is set the path to the field on the aspect inside of the Relationship annotation. As an example, this is what you can do to set these fields on `Upstream` in `UpstreamLineage`
```
/**
* The upstream dataset the lineage points to
*/
@Relationship = {
"name": "DownstreamOf",
"entityTypes": [ "dataset" ],
"isLineage": true,
"createdOn": "upstreams/*/created/time"
"createdActor": "upstreams/*/created/actor"
"updatedOn": "upstreams/*/auditStamp/time"
"updatedActor": "upstreams/*/auditStamp/actor"
}
@Searchable = {
"fieldName": "upstreams",
"fieldType": "URN",
"queryByDefault": false
}
dataset: …
```

feat(graph) Add createdOn, createdActor, updatedOn, updatedActor to graph edges

---

datahub-web-react/src/app/ingest/source/builder/LookerWarning.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/FormField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/RecipeForm.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/SecretField/CreateSecretButton.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/SecretField/SecretField.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/bigquery.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/bigqueryBeta.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/constants.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/hive.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/kafka.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/looker.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/lookml.tsx
datahub-web-react/src/app/ingest/source/builder/RecipeForm/mariadb.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/mssql.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/mysql.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/postgres.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/presto.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/redshift.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/snowflake.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/tableau.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/trino.ts
datahub-web-react/src/app/ingest/source/builder/sources.json

In this PR, we add a new form to UI ingestion for
- MySQL
- Trino
- Presto
- MSSQL
- MariaDB
We also refactor every other form for copy edits, required field status, and more.

refactor(ui): Making improvements to UI ingestion forms, adding MySQL, Trino, Presto, MSSQL, MariaDB forms

---

datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
datahub-web-react/src/app/ingest/source/IngestionSourceTable.tsx
datahub-web-react/src/app/ingest/source/utils.ts

**Adding a Source**
https://user-images.githubusercontent.com/19418814/205800167-75b8c351-1053-4718-91e2-3214e897842a.mov
**Invalidating Cache on Add Failure**
https://user-images.githubusercontent.com/19418814/205808636-ede4e509-36d9-4ffa-87f4-def7c8f26bb5.mov
**Deleting a Source**
https://user-images.githubusercontent.com/19418814/205800737-d035845b-50b2-4550-a89d-0db195c41985.mov

perf(ui-ingestion): cache on creation or deletion of ingestion sources to reduce latency

---

docs/how/updating-datahub.md
metadata-ingestion/docs/sources/powerbi/powerbi-report-server_recipe.yml
metadata-ingestion/src/datahub/ingestion/source/powerbi_report_server/report_server.py
metadata-ingestion/tests/integration/powerbi_report_server/test_powerbi_report_server.py

The source use graph from ctx so graphql_url is not needed.

fix(ingest/powerbi-report-server): deprecate unused graphql config

---

metadata-integration/java/datahub-protobuf/build.gradle

Ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1670378846831849

fix(datahub-protobuf): fix missing httpclient dependency

---

metadata-ingestion/docs/sources/salesforce/salesforce_pre.md

Added more detail to Salesforce ingestions source docs to address https://github.com/datahub-project/datahub/issues/6529
- [x ] Links to related issues (if applicable)

docs(ingest/salesforce): list required permissions

---

.github/workflows/test-results.yml

The results will still be surfaced under the "Test Results" action workflow, but the results won't be commented on the PR itself.

ci: stop commenting test results on PR

---

metadata-auth/auth-api/build.gradle

Using the standard versioning logic when generating versions for the auth-api jar that gets published to Maven.

fix(auth-api): Attempting to fix publish for auth-api

---

metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/entrypoints.py
metadata-ingestion/src/datahub/ingestion/graph/client.py
metadata-ingestion/src/datahub/integrations/great_expectations/action.py
metadata-ingestion/src/datahub/telemetry/telemetry.py

When I have tried to set the environment variable DATAHUB_SKIP_CONFIG, I have noticed that the handling of the boolean environment variables (DATAHUB_SKIP_CONFIG, DATAHUB_DEBUG and DATAHUB_TELEMETRY_ENABLED) are quite different: For example the DATAHUB_SKIP_CONFIG variable had to be set to "True" to be true, while the DATAHUB_DEBUG would also be treated as true with the value "false" (the string "false" is a truthy value in Python).
This PR changes/fixes this behaviour by converting all boolean environment variables to lowercase first and comparing them to the strings "true" and "1" (e.g., [here](https://github.com/datahub-project/datahub/blob/3758bcbe348082ea511d8605e3e01e18742283dd/metadata-ingestion/tests/conftest.py#L9) the value "1" is assigned to DATAHUB_DEBUG, therefore the value …

fix(config): unify the handling of boolean environment variables

---

docker/datahub-ingestion/Dockerfile

Details in the code comment. This is a workaround for https://github.com/gradle/gradle/issues/18124

build: add retries to gradle wrapper download in ingestion docker

---

metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py

In the SQL statement querying BigQuery table metadata, the `table_type` is incorrectly filtered for external tables:
According to the [official documentation](https://cloud.google.com/bigquery/docs/information-schema-tables#schema), the `table_type` will be `EXTERNAL` for external tables.
The query incorrectly expected it to be `EXTERNAL TABLE` instead.

fix(ingest): rectify filter for BigQuery external tables

---

metadata-ingestion/tests/integration/hive/docker-compose.yml
metadata-ingestion/tests/integration/presto-on-hive/docker-compose.yml
metadata-ingestion/tests/integration/trino/docker-compose.yml
metadata-ingestion/tests/test_helpers/docker_helpers.py

Previously a number of our tests would fail with errors like this (from https://github.com/datahub-project/datahub/actions/runs/3679561688/jobs/6224157643) 
```
ERROR: for namenode  Cannot start service namenode: driver failed programming external connectivity on endpoint pytest3625-trino_namenode_1 (f38a8c43128e0cd8cb57ecf54af9b1bda7d03aeb087696975adb80d5ac1154cd): Error starting userland proxy: listen tcp4 0.0.0.0:50070: bind: address already in use
```
The issue is that the OS is allowed to use high-numbered ports for its own purposes. This change lets docker automatically assign host port numbers to avoid conflicts. 
Note that because we weren't using these ports anywhere, it would've been possible to remove the port mappings entirely. However, I opted to leave the ports accessible …

test(ingest): make hive/trino test more reliable

---

metadata-ingestion/scripts/install_editable_versions.sh
metadata-ingestion/setup.py
metadata-ingestion/tests/unit/serde/test_serde.py

The code changes in https://github.com/acryldata/avro_gen/pull/16, but tests are written here. Prior to this change, the test_read_empty_dict test would give `nativeResults = None` instead of `{}`.

fix(ingest): fix codegen `from_obj` for empty dicts in unions with null

---

metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java

* Refactored logic in class, pushed down useSSL to the RestClientBuilder logic rather than splitting into two functions that did mostly the same thing except set up SSL. 
* Changed methods to be non-static so variables did not need to be passed between methods and could just access the class level variables. 
* Added logic to setup connection manager since ElasticSearch doesn't provide a way to set the low level exception handler using their top level config object, has to be done using the connection manager override.
This will provide resilience against normal exception cases, but will not handle Out Of Memory Error failures still, for those cases a JVM restart is the easiest way without adding a wrapper class around the RestHighLevelClient that checks that the low level client is …

fix(elasticsearch): build in resilience against IO exceptions on httpclient

---

docker/datahub-ingestion/Dockerfile

Fixes issues like this https://github.com/datahub-project/datahub/actions/runs/3689069804/jobs/6244612348.
The `**` operator wasn't supported on the version of `sh` that's installed in our Docker image.

ci: fix ingestion gradle retry

---

metadata-ingestion/src/datahub_provider/_plugin.py

Airflow plugin was crashing when trying to apply task policies to dynamically generated tasks (i.e., MappedOperators). This fix will support current versions of Airflow and future versions when the following issue is addressed: https://github.com/apache/airflow/issues/24547.
Related Datahub issue: https://github.com/datahub-project/datahub/issues/6606

fix(ingest): support airflow mapped operators

---

docs/actions/actions/slack.md
docs/actions/actions/teams.md

wrong base url variable
change DATAHUB_ACTIONS_DATAHUB_BASE_URL to DATAHUB_ACTIONS_SLACK_DATAHUB_BASE_URL

fix(actions): fix mistype slack/teams base url

---

metadata-ingestion/src/datahub/ingestion/graph/client.py
metadata-ingestion/tests/unit/graph/test_client.py

Context: https://datahubspace.slack.com/archives/C029A3M079U/p1670257620431059

fix(python-sdk): DataHubGraph get_aspect should accept empty responses

---

docs/lineage/airflow.md

Specifically, this makes it more clear on Airflow 1.x, the old Airflow plugin works and you don't have to use the lineage backend.

docs(ingest/airflow): clarify Airflow 1.x docs for airflow plugin

---

docker/README.md

docs(docker): add section for adding community images

---

smoke-test/tests/test_stateful_ingestion.py

Regression from https://github.com/datahub-project/datahub/pull/6722.

fix(smoke-test): remove stateful ingestion config check

---

metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/tests/integration/snowflake-beta/test_snowflake_beta.py
metadata-ingestion/tests/unit/test_snowflake_beta_source.py

Earlier approach did not work when using snowflake account identifiers of the form <org-name>-<account-name> in snowflake recipe. Also there is no clear way to identify whether input is in with account locator OR account and org name. The revised approach makes no assumptions and fetches account and region details by querying snowflake.

fix(ingest): correct external url for account identifier with account name

---

datahub-web-react/src/app/ingest/source/builder/RecipeForm/common.tsx
datahub-web-react/src/app/ingest/source/builder/sources.json

In this PR, we make include_tables and include_views selected (True) as default for the SQL sources. This fixes an issue where previously created recipes will appear with include views and include tables as false. This should reduce confusion going forward.
We also make small tweaks to the indentation on the Tableau base recipe. 

refactor(ui): Make include_tables and include_views default to True. Improve Tableau default recipe. 

---

docs/architecture/metadata-ingestion.md
docs/architecture/metadata-serving.md

- metadata-serving: [Metadata Change Logs]s -> [Metadata Change Log]s in Metadata Index Applier (mae-consumer-job)
- metadata-ingestion: add Metadata Change Proposal link and edit text-link (Metadata Change Proposals to Metadata Change Proposal)

docs(architecture): edit documents in architecture section

---

metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
metadata-ingestion/src/datahub/ingestion/source/kafka.py
metadata-ingestion/src/datahub/ingestion/source/ldap.py
metadata-ingestion/src/datahub/ingestion/source/state/dbt_state.py
metadata-ingestion/src/datahub/ingestion/source/state/kafka_state.py
metadata-ingestion/src/datahub/ingestion/source/state/ldap_state.py
metadata-ingestion/src/datahub/ingestion/source/state/sql_common_state.py
metadata-ingestion/tests/integration/dbt/test_dbt.py
metadata-ingestion/tests/integration/kafka/test_kafka_state.py
metadata-ingestion/tests/integration/ldap/test_ldap_stateful.py
metadata-ingestion/tests/unit/stateful_ingestion/test_kafka_state.py
metadata-ingestion/tests/unit/test_ldap_state.py

The only remaining state class, `BaseSQLAlchemyCheckpointState`, has become an alias for `GenericCheckpointState`. This was because a number of tests rely on `BaseSQLAlchemyCheckpointState` and I didn't want to change all of them just yet.
The removed dbt test was for testing the upgrade of `BaseSQLAlchemyCheckpointState` to `DbtCheckpointState`, but it's not required now that those are the same class. The other state migration tests already cover that case.

refactor(ingest/stateful): remove most remaining state classes

---

docker/monitoring/docker-compose.consumers.monitoring.yml
docker/monitoring/docker-compose.monitoring.yml
docker/monitoring/grafana/dashboards/datahub_dashboard.json
docker/quickstart/docker-compose.monitoring.quickstart.yml

- Update grafana image tag from default to v9.1.4
- Add `Data Source` variable in dashboard panel to filter by datasource.
- Update metrics for old metrics which were missing
-  Add new panels for metrics 
```
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_MetadataTestHook_latency
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_NotificationGeneratorHook_latency
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_SiblingAssociationHook_latency
metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_UpdateIndicesHook_latency
```

Update Grafana Dashboard

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/post/DeletePostResolver.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/post/DeletePostResolverTest.java
metadata-service/auth-impl/src/main/java/com/datahub/authentication/post/PostService.java
metadata-service/auth-impl/src/test/java/com/datahub/authentication/post/PostServiceTest.java

fix(posts): add deletePost GraphQL endpoint

---

metadata-ingestion/src/datahub/cli/state_cli.py
metadata-ingestion/src/datahub/ingestion/api/ingestion_job_checkpointing_provider_base.py
metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
metadata-ingestion/src/datahub/ingestion/source/state/redundant_run_skip_handler.py
metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
metadata-ingestion/src/datahub/ingestion/source/state_provider/datahub_ingestion_checkpointing_provider.py
metadata-ingestion/tests/unit/stateful_ingestion/provider/test_datahub_ingestion_checkpointing_provider.py
metadata-ingestion/tests/unit/stateful_ingestion/state/test_checkpoint.py

This PR resolves a long-standing issue with our stateful ingestion implementation.
Previously, the URNs under which we stored state were generated like this:
```
urn:li:dataJob:(urn:li:dataFlow:(datahub,<pipeline_name>_<platform>_<platform_instance_id>,prod),<platform>_stale_entity_removal)
```
While this seems reasonable at first glance, it turns out that most of our `get_platform_instance_id()` implementations did not actually produce a stable identifier. For example, Tableau and Looker's were implemented as `self.config.platform_instance or self.platform` and SQL common implemented it like this:
https://github.com/datahub-project/datahub/blob/44cfd21a653e23f869526a3c1a83e11d51b42a86/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L521-L529
As an example of why this is …

feat(ingest/stateful): remove platform_instance_id from state urn

---

datahub-web-react/src/app/ingest/source/builder/RecipeForm/constants.ts
datahub-web-react/src/app/ingest/source/builder/RecipeForm/dbt_cloud.tsx
datahub-web-react/src/app/ingest/source/builder/constants.ts
datahub-web-react/src/app/ingest/source/builder/sources.json

In this PR, we add a form for ingesting from DBT Cloud. 

feat(ui): Adding DBT Cloud support for UI ingestion

---

metadata-ingestion/src/datahub/ingestion/api/sink.py
metadata-ingestion/src/datahub/ingestion/run/pipeline.py

This is a PoC - I'm hoping we can use a similar pattern in `Report` to call `report_failure` or `report_warning`, which should help us reduce the `except Exception` sprawl and improve error reporting.

refactor(ingest): clean up pipeline init error handling

---

metadata-ingestion/src/datahub/utilities/source_helpers.py

Patches generate a raw MCP because MCPW doesn't support patches right now, so we need to handle that correctly downstream.

fix(ingest): support patches in `auto_status_aspect`

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/EntityLineageResultResolver.java
metadata-io/src/main/java/com/linkedin/metadata/graph/SiblingGraphService.java
metadata-io/src/test/java/com/linkedin/metadata/graph/sibling/SiblingGraphServiceTest.java

Fixes a bug we were seeing in the lineage visualization where there were multiple sibling nodes. The bug was that we weren't getting all of the sibling lineages for non-central nodes so if the node with multiple siblings wasn't the sibling node, we would only get their lineage from the urn we have, and not any of the lineages of their siblings. So it wouldn't show non-central node siblings lineage at all, and things would look like the explicit lineage described by individual aspects, not the combined siblings lineage. If we the center node is the one with multiple siblings it worked just fine.
This fixes it by calling the sibling graph service `getLineage` method for all siblings as well as the center, original request node (as opposed to the regular graph service that just gets lineage …

fix(lineage) Fix lineage viz with multiple siblings

---

metadata-integration/java/spark-lineage/README.md
metadata-integration/java/spark-lineage/src/main/java/datahub/spark/DatasetExtractor.java

This PR adds support for Spark lineage with Delta Lake writes.
Here is an example of a Delta Lake write:
```
df.write.format("delta").mode("overwrite").save("s3://bucket/prefix")
```
This creates a `SaveIntoDataSourceCommand` that has the output path `path` included in the `options`.

feat(ingestion): support lineage for delta lake writes

---

datahub-web-react/src/app/domain/CreateDomainModal.tsx
datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx
datahub-web-react/src/app/identity/group/CreateGroupModal.tsx
datahub-web-react/src/app/shared/textUtil.ts

Support setting a custom UUID for Glossary Term and Glossary Term Group.

feat(ui): Support defining the ID for Glossary Term and Glossary Term Group in UI

---

build.gradle
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateIngestionExecutionRequestResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/source/UpsertIngestionSourceResolver.java
ingestion-scheduler/src/main/java/com/datahub/metadata/ingestion/IngestionScheduler.java
metadata-utils/build.gradle
metadata-utils/src/main/java/com/linkedin/metadata/utils/IngestionUtils.java
metadata-utils/src/test/java/com/linkedin/metadata/utils/IngestionUtilsTest.java

Now inject a pipeline_name into recipes that is the urn of the ingestion source at execution time instead of setting it on the recipe that we save and display in the UI. So I also am now removing the logic that was added to put this pipeline_name into the recipe when creating an ingestion source since we don't want that anymore.
Also note that we only inject this pipeline name in if there is not a pipeline_name already set. I don't want to overwrite it if the user is technically savvy enough to control that themselves.

fix(ingestion) Inject pipeline_name into recipes at runtime

---

metadata-ingestion/src/datahub/emitter/mcp_builder.py
metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py

This allows subclasses to add extra properties to containers.
Unblocks https://github.com/datahub-project/datahub/pull/6785.

feat(ingest): add db/schema properties hook to SQL common

---

docs/deploy/confluent-cloud.md

docs(confluent): add details for actions pod for confluent

---

datahub-web-react/src/app/domain/CreateDomainModal.tsx
datahub-web-react/src/app/domain/DomainItemMenu.tsx
datahub-web-react/src/app/domain/DomainListColumns.tsx
datahub-web-react/src/app/domain/DomainsList.tsx
datahub-web-react/src/app/domain/utils.ts
smoke-test/tests/cypress/cypress/integration/mutations/domains.js

Fixing issues where cache was not updated when a Domain is created.
Added back a test-id for domains smoke test.
Fix caching consistency issues when a query is active

refactor(ui): Misc domains improvements 

---

.github/actions/docker-custom-build-and-push/action.yml
.github/workflows/docker-ingestion.yml
.github/workflows/docker-postgres-setup.yml

Reverts datahub-project/datahub#6735 as that is causing problem of `head` tag not being published

Revert "fix(ci): remove warnings due to deprecated action"

---

metadata-ingestion/src/datahub_provider/_airflow_compat.py
metadata-ingestion/src/datahub_provider/_airflow_shims.py
metadata-ingestion/src/datahub_provider/_lineage_core.py
metadata-ingestion/src/datahub_provider/_plugin.py
metadata-ingestion/src/datahub_provider/client/airflow_generator.py
metadata-ingestion/src/datahub_provider/entities.py
metadata-ingestion/src/datahub_provider/example_dags/lineage_backend_demo.py
metadata-ingestion/src/datahub_provider/example_dags/lineage_backend_taskflow_demo.py
metadata-ingestion/tests/unit/test_airflow.py

This PR also
- resolves a reported circular import issue
- refactors the Airflow tests to reduce duplication

feat(ingest/airflow): support raw dataset urns in airflow lineage

---

metadata-ingestion/src/datahub/ingestion/source/kafka.py

feat(ingest): pass timeout config in kafka admin client api calls

---

docker/datahub-ingestion/base-requirements.txt

These deps will be installed by Airflow anyway. This was causing failures in the docker image build e.g. https://github.com/acryldata/datahub/actions/runs/3789366976/jobs/6443053780

chore(ingest): loosen requirements file

---

datahub-web-react/src/app/analytics/README.md

docs(google-analytics): Correct grammatical error in README.md

---

docs-website/sidebars.js
docs/authentication/README.md
docs/authentication/guides/add-users.md
docs/authentication/personal-access-tokens.md
docs/authorization/access-policies-guide.md

Various additions and refactoring of the docs around onboarding new users to DataHub. Trying to also clarify which parts apply to Self-Hosted vs Managed DataHub. 

docs(adding users): Refreshing the docs for adding new DataHub Users 

---

smoke-test/tests/cypress/cypress/integration/login/login.js
smoke-test/tests/utils.py

minor cleanup to use env variables consistenly

refactor(smoke): use env variables

---

metadata-ingestion/setup.py

A new version `1.10.3` was released 2 hours ago which broke all our builds. Pinning this version so builds do not break randomly.

fix(lint): pin pydantic version

---

metadata-ingestion/src/datahub/ingestion/source/identity/okta.py

If `ingest_groups` was set to `false` but `ingest_group_membership` was set to `true` we would get a referenced before assignment error.

fix(ingest): okta undefined variable error

---

.github/workflows/docker-unified.yml
docker/docker-compose.dev.yml
smoke-test/tests/cypress/cypress/integration/analytics/analytics.js
smoke-test/tests/cypress/cypress/integration/mutations/add_users.js
smoke-test/tests/cypress/cypress/integration/siblings/siblings.js
smoke-test/tests/cypress/cypress/support/commands.js
smoke-test/tests/cypress/integration_test.py
smoke-test/tests/managed-ingestion/managed_ingestion_test.py

fix(ci): reduce flakiness in add_users, siblings smoke test

---

metadata-ingestion/src/datahub/ingestion/source/sql/trino.py

This fixes #6759. We can simply ignore the specific type of error that Trino returned, since falling back to the default method provided by the SQLAlchemy dialect is better than nothing.

fix(ingest): fall back to default table comment method for all Trino query errors

---

.github/workflows/docker-unified.yml
datahub-web-react/build.gradle
docker/docker-compose.dev.yml
metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
smoke-test/requirements.txt
smoke-test/run-quickstart.sh
smoke-test/tests/utils.py

A few test speed-ups when tearing down fixtures (support parallel deletes). Adjusting the frontend build to avoid nodejs memory errors in Saas when using the system native nodejs.

test(misc):  misc test updates

---

metadata-ingestion/src/datahub/cli/docker_cli.py

Fixes https://github.com/datahub-project/datahub/issues/6872

fix(cli): Make datahub quickstart work with latest docker compose in M1

---

metadata-ingestion/src/datahub/cli/delete_cli.py
metadata-ingestion/src/datahub/telemetry/telemetry.py

Ran into an issue where `datahub delete --urn <urn> --soft` crashed. This fixes the bug and adds type annotations to `with_telemetry` so we catch similar issues in the future.

fix(cli): fix delete urn cli bug + stricter type annotations

---

metadata-ingestion/docs/sources/looker/looker_pre.md
metadata-ingestion/docs/sources/looker/lookml_pre.md

docs(ingest/looker): fix typos + update lookml github action example

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/embed/UpdateEmbedResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/entity/EntityPrivilegesResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/EmbedUtils.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/ChartType.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/mappers/ChartMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/EmbedMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/DashboardType.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/mappers/DashboardMapper.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/DatasetType.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/DatasetMapper.java
datahub-graphql-core/src/main/resources/auth.graphql
datahub-graphql-core/src/main/resources/entity.graphql
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/embed/UpdateEmbedResolverTest.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/common/mappers/EmbedMapperTest.java
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/chart/ChartEntity.tsx
datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
datahub-web-react/src/app/entity/shared/tabs/Embed/EmbedTab.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/graphql/chart.graphql
datahub-web-react/src/graphql/dataset.graphql
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/mutations.graphql
li-utils/src/main/java/com/linkedin/metadata/Constants.java
metadata-models/src/main/pegasus/com/linkedin/common/Embed.pdl
metadata-models/src/main/resources/entity-registry.yml
metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java

In this PR, we introduce support for attaching an "embed" render URL to a dataset, dashboard or chart. We also introduce logic for rendering these URLs inside of an iframe when they are present. This allows us to do things like directly embed Looker / Tableau / Mode / Redash Looks, Dashboards, Explores into the Dataset pages themselves. 

feat(backend): Supporting Embeddable Previews for Dashboards, Charts, Datasets 

---

metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

feat(ingest): add `include_table_location_lineage` flag for SQL common

---

metadata-ingestion/docs/sources/snowflake/snowflake_pre.md
metadata-ingestion/src/datahub/ingestion/source/snowflake/constants.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_tag.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/src/datahub/ingestion/source_config/usage/snowflake_usage.py
metadata-ingestion/tests/integration/snowflake/common.py
metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
metadata-ingestion/tests/integration/snowflake/test_snowflake.py

Adding support to extracts tags object tags from Snowflake. The scope is limited to database, schema, table/view, and column tags. It also (optionally) creates the extracted tags. Only the tags that are applied to objects are created; it does not pull all existing tags in Snowflake. Caters to https://feature-requests.datahubproject.io/p/ingest-snowflake-object-tags
There are some peculiarities about Snowflake tags that should be considered.
This is handled in this PR by converting the key-value tag into a simple string with the following formatting: `<db_name>.<schema_name>.<tag_name>=<tag_value>`, where `db_name` and `schema_name` are the DB and schema in which the tag is defined, respectively. While not the prettiest, this format should allow users to quite easily define a formatter to …

feat(ingest): allow extracting snowflake tags

---

metadata-ingestion/setup.py

Now that 1.10.4 is released and 1.10.3 has been yanked, we can loosen our requirement.

chore(ingest): unpin pydantic dep

---

metadata-ingestion/src/datahub/configuration/github.py
metadata-ingestion/src/datahub/ingestion/source/git/git_import.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/tests/integration/git/test_git_clone.py

Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1672751484288009?thread_ts=1672649757.234549&cid=CUMUWQU66

fix(ingest): use branch info when cloning git repos

---

metadata-ingestion/src/datahub/emitter/mcp_builder.py
metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
metadata-ingestion/src/datahub/ingestion/source/kafka.py
metadata-ingestion/src/datahub/ingestion/source/pulsar.py
metadata-ingestion/src/datahub/ingestion/source/salesforce.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source/unity/source.py
metadata-ingestion/tests/unit/test_kafka_sink.py
metadata-ingestion/tests/unit/test_rest_sink.py
metadata-ingestion/tests/unit/test_source.py
metadata-ingestion/tests/unit/test_transform_dataset.py

Follow up on https://github.com/datahub-project/datahub/pull/6819.

chore(ingest): remove inferred args to MCPW, part 2

---

metadata-ingestion/setup.py

`0.15.42` of GE was released today which broke our builds. Pinning it to fix builds
https://pypi.org/project/great-expectations/0.15.42/#history

fix(ci): restrict GE to fix build issues

---

metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py

This PR will extend the Postgres source so that it emits table lineage for Views. 
The lineage is generated from Postgres' own internal metadata about view and table dependencies. The primary information this exposes is which other Views or Tables a View references. In the simplest case, these are the tables referenced in the `FROM` or a `JOIN`. 
This feature is optional and controlled by a new config value for the Postgres source, so it will not impact any installations of Datahub and is completely opt-in for users. I also tried to respect any name or schema filters that might already be configured.
I was not able to find any prior issues or PRs for this.
The implementation is based on a package we just published, so you can also see how it behaves using just this package …

feat(ingest/postgres): emit lineage for postgres views

---

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py

Currently, glue metadata ingestion doesn't emit s3 lineage when data was written with an s3a/s3n client. This changes makes it so glue metadata ingestion emits the s3 lineage even when the scheme in the location property is s3a/s3n.

feat(ingest/glue): emit s3 lineage for s3a and s3n schemes

---

datahub-graphql-core/src/main/resources/entity.graphql
docs/glossary/business-glossary.md
docs/tags.md

- Clarifying deprecated field docs. 
- Updating tag docs to point to correct GraphQL methods.
- Adding glossary docs to point to correct GraphQL methods.

fix(docs): Updating Tag, Glossary Term docs to point to correct GraphQL methods

---

docs-website/sidebars.js
docs/authorization/policies.md
docs/domains.md
docs/lineage/lineage-feature-guide.md
docs/lineage/manual-lineage-feature-guide.md

Adds the feature guide for Manual Lineage. Check out the photos that are referenced in this doc in this PR here: https://github.com/datahub-project/static-assets/pull/28

feat(docs) Add feature guide for Manual Lineage

---

docs/glossary/business-glossary.md

In this PR, I rename the title of the Business Glossary Feature guide to be aligned with other names.

fix(docs): Renaming Business Glossary Doc

---

metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py

In the latest releast of types-PyOpenSSL, they removed their dep on types-cryptography (https://github.com/python/typeshed/pull/9459). This caused mypy to start using the type annotations provided by the cryptography package, which caused an issue in our build. Example build failure: https://github.com/datahub-project/datahub/actions/runs/3888835554/jobs/6636552750

fix(ingest/snowflake): fix type annotations + refactor get_connect_args

---

docs/how/kafka-config.md

 fix(docs): Changing the platform event topic name in kafka custom topic docs

---

datahub-frontend/app/auth/AuthUtils.java
datahub-frontend/app/auth/sso/SsoConfigs.java
datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java
datahub-frontend/app/controllers/AuthenticationController.java
datahub-frontend/conf/application.conf
datahub-frontend/play.gradle

In order to display our chrome extension's iFrame properly, we need to set same-site=NONE and secure=true so that we can authenticate users from an iFrame from another host (like Looker).
An article discussing this change: https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e

feat(auth) Update auth cookies to have same-site none for chrome extension

---

README.md

Right now it looks huge on this page: https://datahubproject.io/docs/introduction/

docs: resize datahub logo

---

metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
metadata-ingestion/tests/integration/powerbi/golden_test_report.json

Report page has the page ID (format `ReportSectioneaaaaa6eaaadb2b20414`) in name field, therefore it's more meaningful to use human readable name of the page as title.
- [x ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

fix(ingest): powerbi # use display name field as title for powerbi report page

---

docs-website/sidebars.js
docs/architecture/search_improvements.md
docs/architecture/stemming_and_synonyms.md

feat(eso): add docs

---

datahub-frontend/conf/application.conf

Allow users to set the session TTL with an env variable. Defaults to 720 hours, the default that we already had in code.

feat(auth) Allow session ttl to be configurable by env variable

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolverTest.java

When stateful ingest is enabled in the recipe, test connection fails unless a pipeline_name is provided (due to config constraints). We are fixing it here by doing the same thing we do for other ingestion sources, simply injecting it when we run the pipeline.

fix(ui ingest): Fix test connection when stateful ingest is enabled

---

docs/authentication/guides/sso/configure-oidc-react-azure.md
docs/authentication/guides/sso/configure-oidc-react-google.md
docs/authentication/guides/sso/configure-oidc-react-okta.md
docs/authentication/guides/sso/configure-oidc-react.md

Moves root user warning to earlier in Overview docs and adds Warning icon/callout box.
Warning also added to individual OIDC guides.

docs(sso) move root user warning to earlier in SSO guides

---

.github/workflows/docker-unified.yml

Earlier fix to only run on `master` did not work. Trying offline scanning as per https://github.com/aquasecurity/trivy-action/issues/190

fix(ci): use trivy offline scanning

---

metadata-ingestion/src/datahub/ingestion/source/kafka.py

fix(ingest/kafka): fix ResourceType import error for confluent_kafka<1.9.0

---

metadata-ingestion/setup.py
metadata-ingestion/tests/integration/vertica/test_vertica.py

Something weird has happened that is causing our vertica tests to be failing now. Specifically, there's a conflict with SQLAlchemy 1.3.24.
Note that the CI did pass here: https://github.com/datahub-project/datahub/issues/7010.
Looking at https://pypi.org/project/vertica-sqlalchemy-dialect/0.0.1/#files, it seems like new files were uploaded ~6 hours ago, despite the original release having been from a week ago. I'm not sure how this happened, since PyPI releases are supposed to be immutable.
I've let the relevant folks know of the issue - we expect they'll be responsible for actually fixing this.

fix(ingest): temporarily disable vertica tests

---

metadata-service/war/src/main/resources/boot/policies.json

fix(bootstrap): add EDIT_LINEAGE privilege to some default policies

---

metadata-ingestion/src/datahub/ingestion/source/metabase.py

This is a follow up to https://github.com/datahub-project/datahub/pull/5647 to:
- pull the database name from the raw query when possible, see https://github.com/datahub-project/datahub/pull/5647#issuecomment-1242298818
- pull the schema name from the API when possible; this is not documented in https://www.metabase.com/docs/latest/api/database but the default schema can be stored in the API response under `[].details.schema`
Tested locally with `acryl-datahub==0.9.3.2`.

feat(ingestion): pull metabase database, schema names from raw query and api

---

datahub-web-react/src/app/entity/shared/__tests__/siblingsUtils.test.ts
datahub-web-react/src/app/entity/shared/siblingUtils.ts

We had an issue reported by several users where scrolling on their schema caused the same field to be repeated and take over the whole schema. This was happening because the `key` of one (or more) the schema rows had a duplicate, causing bad rendering issues and duplicating the same rows.
This could happen when two siblings had different schemas. If one of the schemas had an extra row or two inserted in the middle, the two schemas would be merged by index and therefore we would produce duplicate fields, causing duplicate rows, breaking the schema renderer.
This fixes the issue by merging based on the `fieldPath` instead, so now we get a combined schema of the siblings with unique field paths, preventing duplicated.

fix(ui) Fix duplicate schema field rendering with siblings

---

metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
metadata-ingestion/tests/unit/test_athena_source.py

This PR is an outcome of this [Slack discussion](https://datahubspace.slack.com/archives/CUMUWQU66/p1673249859730469).
It deprecates the parameter `s3_staging_dir` in the Athena source and introduces `query_result_location` instead.
Downwards compatibility is ensured.
While writing the tests I didn't found an integration test for Athena.
If someone could provide me with some background information about writing integration tests for sources, I could add one to this PR.

refactor(ingest/athena): Replace `s3_staging_dir` parameter in Athena source with `query_result_location`

---

metadata-ingestion/src/datahub/emitter/serialization_helper.py
metadata-ingestion/tests/unit/serde/test_serde.py
metadata-ingestion/tests/unit/test_rest_sink.py

feat(ingest): fix handling of unions with aliases in post restli conversion

---

metadata-ingestion/src/datahub/configuration/github.py
metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
metadata-ingestion/tests/integration/git/test_git_clone.py

fix(ingest): support git clone of non-github repos

---

docs/datahub_lite.md
metadata-ingestion/src/datahub/cli/lite_cli.py
metadata-ingestion/src/datahub/lite/duckdb_lite.py

feat(datahub-lite): adding tab completion, small serialization fixes

---

metadata-ingestion/src/datahub/ingestion/api/source.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py

Prior to this change, we would correctly soft-delete entities, but we wouldn't clear them out of the state payload. This means that every subsequent ingestion run would also try to soft delete those entities. This should require no intervention to roll out the changes.
Minor related change: fixes the reporting usage so that we only report each entity once. This ensures that the ingestion reports we produce are accurate. We were previously double-counting everything.

fix(ingest/bigquery): clear stateful ingestion correctly

---

datahub-web-react/src/app/settings/CreateTokenModal.tsx

Previously the AccessTokenModal constantly displays the token expiry date as 1 month away regardless of the user's selected option. This was caused by Line 65 where the input state was resetting before the confirmation modal was shown. This PR shows the correct information per user's selection by separating form state and selected state. There is a little refactor to maximise usage of Ant Design's inbuilt form state utility rather than relying on the component's state.

fix(ui): display the correct access token expiry in AccessTokenModal

---

docs/datahub_lite.md
metadata-ingestion/setup.py
metadata-ingestion/src/datahub/cli/lite_cli.py
metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
metadata-ingestion/src/datahub/ingestion/source/tableau.py
metadata-ingestion/src/datahub/lite/lite_server.py

fix(cli/lite): fix datahub lite serve command

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/DatasetMapper.java
li-utils/src/main/javaPegasus/com/linkedin/common/uri/Uri.java
li-utils/src/main/javaPegasus/com/linkedin/common/uri/UriCoercer.java
metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProperties.pdl

fix(uri): marks uri field as deprecated, removes problem code, and adds coercer for usages of URI typeref

---

metadata-ingestion/setup.py
metadata-ingestion/src/datahub/cli/cli_utils.py
metadata-ingestion/src/datahub/entrypoints.py

- excludes datahub-lite from docker images, which was causing issues for the arm64 build (https://github.com/datahub-project/datahub/actions/runs/3969149206/jobs/6803397567)
- also adds the shim for actions
Looks like this:

feat(ingest): move datahub-lite to optional dep and add shim when missing

---

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py

feat(ingest): hide cartesian product warnings in GE profiler

---

metadata-ingestion/src/datahub/cli/delete_cli.py

fix(ci): do not confirm on force for deletion

---

datahub-web-react/src/app/shared/ManageAccount.tsx
smoke-test/tests/cypress/cypress/integration/mutations/add_users.js
smoke-test/tests/cypress/cypress/support/commands.js

Smoke test for add_users was recently broken. This change ensures that the log out flow goes through the normal browser flow to fix this issue.

fix(tests): Fixing add_users smoke test

---

metadata-service/README.md

docs(gms): clarify behavior of soft deletion in UI

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetMetadataAnalyticsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/service/AnalyticsUtil.java

Previously, we hydrated glossary term names based off the entity key name. Now that's just a UUID. We need to get the term name from the info aspect, but we can fall back on the key if the info aspect or the name on that aspect doesn't exist.
**Before the fix:**
**After the fix:**

fix(ui) Display glossary term name in analytics page properly

---

datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
datahub-web-react/src/app/entity/shared/EntityContext.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/entity/shared/containers/profile/header/EntityTabs.tsx
datahub-web-react/src/app/entity/shared/types.ts

This PR fixes a bug when the first tab in an entity profile is not visible and/or is not enabled, but is selected by default when the url does not specify a tab. It also prevents an invisible and/or disabled tab from being manually selected by modifing the url (e.g. [here](https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:looker,long_tail_companions.view.ability,PROD)/Queries) the Queries tab is disabled, but is selected by adding "/Queries" to the url).
As I have noticed this bug after PR #5864, I have also moved the Datasets tabs after the Charts tab (the Charts and Datasets tab are conditionally visible or not, therefore the Datasets tab should be the first tab, when the Charts tab is not visible).

fix(ui): only use visible and enabled tabs for selected tab and routing in entity profiles

---

metadata-ingestion/src/datahub/lite/duckdb_lite.py
metadata-ingestion/src/datahub/lite/lite_local.py
metadata-ingestion/src/datahub/lite/lite_util.py

Simplifies the response to `datahub lite get` to make it simpler to consume:
- Avoids nesting of aspect under the `value` node. 
- Inlines systemMetadata as a special field `__systemMetadata`

feat(datahub-lite): simplify get response

---

.github/workflows/build-and-test.yml
.github/workflows/metadata-ingestion.yml

We want other runs to still go on in case of failure in one. Not having these fail fast causes situations where others also get cancelled which we don't want.

fix(ci): do not fail fast for matrix runs

---

metadata-ingestion/src/datahub/cli/delete_cli.py
metadata-ingestion/src/datahub/cli/put_cli.py
metadata-ingestion/src/datahub/cli/state_cli.py
metadata-ingestion/src/datahub/ingestion/graph/client.py

refactor(cli): extract method, change wording

---

docs/deploy/confluent-cloud.md

- fix typo
Next, configure datahub-frontend --> Next, configure datahub-actions
- add missing line
SCHEMA_REGISTRY_URL=https://plrm-qwlpp.us-east-2.aws.confluent.cloud
- attach overwriting system action config
See [Overwriting a System Action Config](https://github.com/acryldata/datahub-actions/blob/main/docker/README.md#overwriting-a-system-action-config) for detailed reflection procedures.
When i built self hosted datahub, find overwriting system action config document.
If there is a detailed document link together, it will be helpful to others.

[docs] fix typo / add missing line for docker compose / attach overwriting system action config for confluent.

---

datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/TableStats.tsx

Currently the top users within the stats tab of a Dataset is not sorted by their query count. This change reflects the top users by their counts.
||
| ------ |
|<img width="1164" alt="image" src="https://user-images.githubusercontent.com/49811128/214918201-f829bac7-0255-435d-bb9e-d2f6c7328ab9.png">|
`    "aspectName" : "datasetUsageStatistics",
"aspect" : {
"value" : "{ \"timestampMillis\":1674749347000,\"partitionSpec\": {\"type\": \"FULL_TABLE\", \"partition\": \"FULL_TABLE_SNAPSHOT\"}, \"totalSqlQueries\": 155, \"uniqueUserCount\": 1, \"userCounts\": [{\"user\": \"urn:li:corpuser:datahub\", \"count\": 21, \"userEmail\": \"datahub@abc.COM\"},{\"user\": \"urn:li:corpuser:jkadambi\", \"count\": 100, \"userEmail\": \"jkadambi@OPTUM.COM\"},{\"user\": \"urn:li:corpuser:eaipeas\", \"count\": …

fix(ui): Sort top users by their query count in datasets stats tab

---

datahub-web-react/src/app/lineage/manage/AddEntityEdge.tsx

In this PR we tune the experience of searching for entities within the Add entities modal, including:
1. A loading indicator when search results are loading
2. Remove select behavior that was filtering results unnecessarily
3. Add no entities found indicator in case of no results.
4. Auto-select the input box when modal opens
See screen capture below for demo. 
https://user-images.githubusercontent.com/17549204/214965581-08a8a6e8-3e09-4835-89e3-d861a2f15c46.mov

refactor(ui): Updates to Manual Lineage search

---

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/entity/EntityExistsResolver.java
datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/DatasetMapper.java
datahub-graphql-core/src/main/resources/entity.graphql
datahub-web-react/src/Mocks.tsx
datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
datahub-web-react/src/app/entity/shared/embed/EmbeddedProfile.tsx
datahub-web-react/src/app/entity/shared/entity/NonExistentEntityPage.tsx
datahub-web-react/src/app/entity/shared/types.ts
datahub-web-react/src/graphql/chart.graphql
datahub-web-react/src/graphql/container.graphql
datahub-web-react/src/graphql/dataFlow.graphql
datahub-web-react/src/graphql/dataset.graphql
datahub-web-react/src/graphql/fragments.graphql
datahub-web-react/src/graphql/glossaryNode.graphql
datahub-web-react/src/graphql/glossaryTerm.graphql

In the embedded profile for the chrome extension as well as any entity profile, we want to show a page saying that an entity doesn't exist in datahub if that's the case instead of pretending like we know about the entity and showing a bare bones page (like we do in the main app).
This adds a new `exists` field on entities that you can query in graphql. It reuses an existing `EntityExistsResolver` that was meant as its own endpoint with a `urn` in the params, but I repurpose it to get the urn from the source entity if it's not in the params so it can be used for both purposes.
Here's what the page looks like for embedded profiles:
and for regular profiles:

feat(ui) Build entity doesn't exist page for entity profiles

---

metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py

fix(ingest): azuread group mapping do not stop ingestion

---

datahub-web-react/src/app/ingest/source/builder/CreateScheduleStep.tsx
datahub-web-react/src/app/ingest/source/builder/IngestionSourceBuilderModal.tsx
smoke-test/tests/cypress/cypress/integration/mutations/managed_ingestion.js

We've received feedback that clearing a schedule for an ingestion run is non-obvious. In this PR, we introduce a button for explicitly enabling or disabling scheduling of an ingestion source. We also remove the confusing "Skip" button. 
Also fixed naming consistency issues, moving from "Execution" to "Ingestion" vocab. 

refactor(ui ingest): Allow enabling / disabling ingestion schedule easily 
