- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/pulsar.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
> fix(ingest): switch various sources to `auto_stale_entity_removal` helper

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
Fixes broken CI. Example failure: https://github.com/datahub-project/datahub/actions/runs/4036967595/jobs/6958714314
> test(ingest/delta-lake): fix spurious directory creation

- .github/workflows/docker-ingestion-smoke.yml
- .github/workflows/docker-unified.yml
- .github/workflows/lint-actions.yml
> feat: add a linter for github actions workflows

- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.kafka-setup.yml
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- docker/kafka-setup/kafka-setup.sh
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.kafka-setup.quickstart.yml
- docker/quickstart/docker-compose.monitoring.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- docker/quickstart/generate_and_compare.sh
- docker/quickstart/generate_docker_quickstart.py
- metadata-ingestion/src/datahub/cli/docker_cli.py
> fix(quickstart): adding back kafka-setup 

- metadata-ingestion/README.md
Fixes the broken links details in this Issue here: https://github.com/datahub-project/datahub/issues/7133
We git ignore the generated files in docs, so we never check them in - that's why the links don't work. Instead let's just link to our docs site that hosts these generated docs.
> fix(docs) Fix broken links in ingestion docs

- metadata-ingestion/integration_docs/great-expectations.md
- metadata-ingestion/src/datahub/integrations/great_expectations/action.py
- Fixes [Issue](https://datahubspace.slack.com/archives/CUMUWQU66/p1674713093455199) reported on slack. Issue existed for both snowflake and trino connection strings based GX datasources.
- Minor change in doc
> fix(ingest/GX): fix snowflake urn generated from connection string

- metadata-ingestion/src/datahub/ingestion/api/workunit.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
- metadata-ingestion/src/datahub/utilities/source_helpers.py
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
Follow up on https://github.com/datahub-project/datahub/pull/7158.
- This also resolves a long-standing bug where we would add non-dbt entities to the dbt state object
- Adds status aspects for assertions
> feat(ingest): switch dbt to use `auto_stale_entity_removal`

- metadata-service/war/src/main/resources/logback.xml
Follow up of https://github.com/datahub-project/datahub/pull/6474 to do this for GMS too.
> fix(log): logging timestamp in ISO8601 format instead of time

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
> fix(ingest/vertica): Fixing missing container properties

- build.gradle
- datahub-frontend/play.gradle
This update fixes two security vulnerabilities:
* [CVE-2022-41811](https://access.redhat.com/security/cve/CVE-2022-41881)
* [CVE-2022-41915](https://nvd.nist.gov/vuln/detail/CVE-2022-41915)
> chore(deps): bump Netty from 4.1.85.Final to 4.1.86.Final

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
Quoting a column name with doublequote here produces wrong results because it's equal to calling `APPROX_COUNT_DISTINCT` on a string constant. Column names should be quoted with the backtick character, see https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#quoted_identifiers.
> fix(ingest/bigquery): quoting for APPROX_COUNT_DISTINCT in BigQuery

- smoke-test/tests/read_only/test_analytics.py
This was causing exceptions in gms logs as follows
```
[ForkJoinPool.commonPool-worker-7] ERROR c.datahub.graphql.GraphQLController:100 - Errors while executing graphQL query: "\n            query getMetadataAnalyticsCharts($input: MetadataAnalyticsInput!) {\n                getMetadataAnalyticsCharts(input: $input) {\n                    groupId\n                    title\n                }\n            }\n        ", result: {errors=[{message=Variable 'input' has an invalid value: Variable 'input' has coerced Null value for NonNull type 'MetadataAnalyticsInput!', locations=[{line=2, column=46}], extensions={classification=ValidationError}}], data=null, extensions={tracing={version=1, startTime=2023-02-01T12:29:51.971957Z, endTime=2023-02-01T12:29:51.976488Z, duration=4550667, …
```
> fix(test): missing variables in test causing error in logs

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/tests/unit/glue/glue_deleted_actor_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_mces_golden.json
- metadata-ingestion/tests/unit/glue/glue_mces_platform_instance_golden.json
(re-raised from #7190)
The FQN includes the catalog ID and database name. Add in the 'name' field that is just the table name, like the SQL-based sources, to make it more readable in the UI
Before:
After:
> feat(glue): Use table name as human-readable name for Glue ingestion

- metadata-io/src/main/java/com/linkedin/metadata/entity/DeleteEntityService.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/DeleteEntityServiceTest.java
Deleting Container references were broken. This PR fixes that.
Root cause is https://github.com/datahub-project/datahub/pull/5248 which changed the MCP change type to DELETE for cases where an aspect after getting the reference removed was no longer valid. We do not support  DELETE operations for MCPs.
The solution is then to execute EntityService#deleteAspect rather than emit a sync MCP.
A regression test was made to prevent this from happening again.
> fix(gms): Fixes delete references for single relationship aspects

- metadata-ingestion/docs/sources/file-based-lineage/datahub-lineage-file.md
…neage file
From Slack Thread: https://datahubspace.slack.com/archives/CUMUWQU66/p1675312380286099
> docs(ingest/lineage): clarify name field in entity config for file based lineage

- datahub-web-react/src/app/entity/shared/EntityDropdown/CreateGlossaryEntityModal.tsx
Fixed typo of 'Documenataion' to 'Documentation' in CreateGlossaryEntityModal.
> fix(ui): typo 'Documenataion'

- metadata-ingestion/src/datahub/cli/delete_cli.py
If you're trying to delete a single aspect, we shouldn't ask you to delete all references to the entire entity.
> fix(cli/delete): skip references prompt if deleting an aspect

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
This is a follow-up on https://github.com/datahub-project/datahub/pull/7068 to resolve lingering page_size issues.
> fix(ingest/tableau): implement workbook_page_size parameter

- metadata-dao-impl/kafka-producer/src/main/java/com/linkedin/metadata/dao/producer/KafkaEventProducer.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/event/EventProducer.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
Fixes issue with async ingestion on GMS when using managed ingestion, where the entityUrn was not specified.
> fix(gms): Corrects MCP generation in async mode

- metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
Change `like` to `ilike` as sometimes SQL is written in upper case.
> fix(ingest): redshift # build late binding view lineage when sql written in upper case

- docs-website/sidebars.js
- docs/api/restli/restore-indices.md
- docs/how/restore-indices.md
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- Exception log was incomplete which made it hard to see what is happening. 
- Restore indices endpoint API doc was hard to find. Moved it under Rest.li docs.
> chore(log/docs): improve error log, docs

- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
Previously, we use the urn name as a fallback in the case that the qualified name is not present (autocomplete). This caused the raw entity asset ID to appear in the autocomplete incorrectly.
> fix(autocomplete): Use normal properties name instead of urn name in autocomplete

- datahub-frontend/app/log/LogMessageFilter.java
- datahub-frontend/app/security/AuthenticationManager.java
- datahub-frontend/conf/logback.xml
- datahub-frontend/run/logback.xml
In this PR I've introduced a custom logback filter that will accept partial log messages and filter them out on a case by case basis. 
This is useful for hushing specific warnings or errors coming from the underlying libraries (like Pac4j) without having to silence them completely. (e.g. at class or package level). 
We only silence in the stdout logger, but keep in the file appender for our debugging purposes.
Specific warnings which are hushed:
- [Pac4j] Preferred JWS algorithm: null not available. Using all metadata algorithms: [RS256]
- [Pacj] Unable to renew the session. The session store may not support this feature
- [Our Code]2023-02-03 16:42:28,995 [application-akka.actor.default-dispatcher-16] WARN  application - The submitted callback is unsupported! type: class …
> fix(frontend logs): Silencing harmless log messages (and adding path for future) 

- datahub-graphql-core/README.md
Issue reported in this slack thread - https://datahubspace.slack.com/archives/C029A3M079U/p1675416618086009
> docs(graphql): remove reference of non-existent gms.graphql

- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
Also measure call for every graphql call. This would help to identify ratio of failures and alert better
> Add graphql error and call metrics at startuptime

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
Fixes https://github.com/datahub-project/datahub/issues/7182
> fix(ingest/tableau): handle missing query in tableau views

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/timeline/GetSchemaBlameResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaBlameMapper.java
> fix(schema-blame): check if list of ChangeTransactions is empty before processing

- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/DataProcessInstanceRunEventChangeEventGenerator.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
> fix(change-events): guard against NPE's

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
We missed this reference to the MCP entity urn (instead of the safely converted urn). This caused async ingest to not work on head of acryl-main.
> fix(async ingest): Fix async ingest path

- metadata-ingestion/src/datahub/upgrade/upgrade.py
The current upgrade prompt only checks for server versions 0.8.x and 0.9.x as valid versions for suggesting upgrades. 
Adding 0.10.x to the mix as we prepare the server release.
> feat(cli): add 0.10 awareness to upgrade prompt

- .github/workflows/check-quickstart.yml
- smoke-test/run-quickstart.sh
> chore(ci): ensure kafka setup runs for smoke tests

- docs/developers.md
> getting rid of build locally(broken) for ./gradlew quickstart(working)

- docs/authorization/access-policies-guide.md
Makes more sense to have heading above the image
> doc(access): move heading above the images

- datahub-web-react/src/app/auth/ResetCredentials.tsx
- datahub-web-react/src/app/auth/SignUp.tsx
> fix(ui): fix styling on sign up and reset screens

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- Fix for BigQuery usage extraction rate limiting
- Fix for BigQuery lineage extraction when audit logs exported
> fix(ingest/bigquery): Usage rate limiting and lineage exported log fix

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandlerTest.java
The GraphQL query below only returns datasets that contains the `user identifier` tag, whereas it should return datasets that contain either `user identifier` or `email address` tag.
```
query getSearchResultsForMultiple {
searchAcrossEntities(input: {
types: [DATASET], 
query: "",
orFilters: [
{
and: [
{
field: "fieldTags",
values: ["urn:li:tag:user identifier", "urn:li:tag:email address"],
condition: EQUAL
}
]
}
]
}) {
searchResults {
entity {
urn
type
}
}
}
}
```
The problem is that `values` is lost when we construct the new `Criterion` for a field that belongs to `EDITABLE_FIELD_TO_QUERY_PAIRS`. As a result, the query to ES doesn't have the terms query.
The fix is one line, but I took the opportunity to boost the test coverage a bit.
See below for details. …
> fix(search): correctly filter fields in EDITABLE_FIELD_TO_QUERY_PAIRS with a list of values

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/ingestion/api/ingestion_job_checkpointing_provider_base.py
- metadata-ingestion/src/datahub/ingestion/api/sink.py
> chore(ingest): upgrade to mypy 1.0.0

- metadata-ingestion/src/datahub/emitter/mcp.py
In my local tests with an MCPW with a dataset schema of 3000 columns, this reduced runtime from ~676 ms to ~189 ms, which is a 3-4x improvement. It seems to scale linearly with the size of the MCPW object, but I didn't test that extensively.
Note that almost 200ms is still pretty bad for basic data validation. With the changes from https://github.com/acryldata/avro_gen/pull/18, I was able to get it down to ~130 ms. Not sure how much further it is worth pushing it.
> perf(ingest): speed up MCPW.validate()

- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/tests/unit/test_bigquery_profiler.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
- Fix for not clearing BigQuery table cache, which caused to carry over tables from one project to the other
- Fixing range partition profiling
- Fixing peak memory report
> fix(ingest/bigquery): Fix for table cache was not cleared 

- docs-website/src/pages/_components/Logos/index.js
- docs/cli.md
- metadata-ingestion/scripts/docgen.py
- metadata-ingestion/src/datahub/ingestion/source/nifi.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic.py
- metadata-service/war/src/main/resources/boot/data_platforms.json
This PR fixes the order of the sources in the sidebar of the documentation: Previously the sources were automatically sorted by the name of the corresponding markdown file resp. the platform id (the files are named by the platform id). The fix ensures that the corresponding [sidebar_position metadata attribute](https://docusaurus.io/docs/sidebar/autogenerated#doc-item-metadata) is added to the generated markdown files after the sources were sorted by the platform name (the attribute is needed for the autogenerated sidebar [here](https://github.com/datahub-project/datahub/blob/76846b417548aaf8b30049505fe825d7feb2b7f1/docs-website/sidebars.js#L126-L129)).
This fixes/reverts #7244 by renaming the SAP HANA source to "SAP HANA" instead of "HANA". I have also seen that the Apache NiFi source …
> fix(docs): sort sources by display name in doc's sidebar

- metadata-ingestion/src/datahub/ingestion/transformer/dataset_domain.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
Propagates the `replace_existing` config flag and adds tests for the pattern add domain transformer.
Note, as demonstrated by the tests, that if the pattern does not match and `replace_existing = True`, it still replaces the domains for that entity, just with `[]`. This is the same behavior as other transformers with the `replace_existing` flag and patterns, like the pattern add dataset ownership transformer.
> fix(transformers): pattern add domain transformer - enable replace_existing

- .github/workflows/metadata-ingestion.yml
The hash will be the same for all metadata tests. So we don't need to keep separate cache for all. That was taking us over the limit which removes the cache thus limiting the usefulness.
> fix(ci): remove command from cache key as irrelevant for dependency

- metadata-service/auth-impl/src/main/java/com/datahub/telemetry/TrackingService.java
Removing unnecessary 'title' field from tracking.
> fix(tracking): Remove 'title' field from tracking

- metadata-io/src/main/java/com/linkedin/metadata/config/CacheConfiguration.java
- metadata-io/src/main/java/com/linkedin/metadata/config/EntityDocCountCacheConfiguration.java
- metadata-io/src/main/java/com/linkedin/metadata/config/HomepageCacheConfiguration.java
- metadata-io/src/main/java/com/linkedin/metadata/config/PrimaryCacheConfiguration.java
- metadata-io/src/main/java/com/linkedin/metadata/search/aggregator/AllEntitiesSearchAggregator.java
- metadata-io/src/main/java/com/linkedin/metadata/search/cache/EntityDocCountCache.java
- metadata-io/src/test/java/com/linkedin/metadata/ESSampleDataFixture.java
- metadata-io/src/test/java/com/linkedin/metadata/ESSearchLineageFixture.java
- metadata-io/src/test/java/com/linkedin/metadata/search/LineageSearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/SearchServiceTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/CacheConfig.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/ConfigurationProvider.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/AllEntitiesSearchAggregatorFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/SearchServiceFactory.java
- metadata-service/factories/src/main/resources/application.yml
- metadata-utils/src/main/java/com/linkedin/metadata/utils/ConcurrencyUtils.java
> fix(homepage): make entity counts execute in parallel and make cache configurable

- datahub-frontend/app/auth/AuthModule.java
- datahub-frontend/app/auth/AuthUtils.java
- datahub-frontend/app/auth/CookieConfigs.java
- datahub-frontend/app/auth/sso/SsoConfigs.java
- datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java
- datahub-frontend/app/controllers/AuthenticationController.java
- datahub-frontend/app/controllers/SsoCallbackController.java
Grabs the configs for setting out Actor cookie through the SSO from the configs object instead of trying to shoe-horn them into the SSO configs object. This fixes an issue where if you try to configure SSO through the UI and have these env variables set, we still read these values properly.
> fix(sso) Retrieve cookie configs separately from SSO configs

- metadata-ingestion/src/datahub/cli/docker_cli.py
The original log message in the cli was added when DataHub's default graph backend was neo4j and we wanted to make sure that people were in the know when we selected elastic by default for them.
1.5 yrs later: people are actually more confused about this message and wonder whether they should instead be using neo4j and why. 
Example: https://datahubspace.slack.com/archives/CV2KB471C/p1676324646452419
This PR drops that message to debug level.
> logging(cli): dropping neo4j message to debug to avoid confusion

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/UpgradeCli.java
Remove any whitespace around upgrade name before executing. As per this thread: https://datahubspace.slack.com/archives/C02AD211493/p1676395703658869
> refactor(upgrade): Trim upgrade name before executing

- metadata-ingestion/src/datahub/cli/cli_utils.py
Fixes search in cli where the filter was using the incorrect field syntax.
> fix(cli): Corrects search filter for delete

- metadata-ingestion/docs/sources/athena/athena_recipe.yml
This PR updates the Athena sample recipe to replace the deprecated parameter `s3_staging_dir` by it's successor `query_result_location`
> refactor(ingest,athena): update athena sample recipe

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
Haven't been able to test end-to-end, but was able to run `datahub ingest -c looker.dhub.yaml --test-source-connection` on a basic looker recipe
> fix(ingest/looker): do not instantiate LookerDashboardSource on test_connection

- docs/README.md
This fixes a broken link to the `Feature Guide Template`-section in the Documentation. GitHub web-editor also added a newline at end of file.
I just discovered this project. Thanks for this amazing tool!
> docs: fix broken link

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/EntityLineageResultResolver.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/entity/EntityRegistry.tsx
- datahub-web-react/src/app/lineage/utils/navigateToLineageUrl.ts
- datahub-web-react/src/graphql/lineage.graphql
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/shared/ValidationUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/sibling/SiblingGraphServiceTest.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/graph/EntityLineageResult.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.lineage.relationships.snapshot.json
Currently, there is a longstanding bug with the Upstream and Downstream count shown on the Entity Profile, where the counts can be invalid in the presence of bad references:
Specifically, this is because the counts are generated without accounting for 
1. Soft Deleted
2. Non-Existent
References in the relationship graph. 
In this PR, we add the following capabilities:
1. Filtering _both_ soft-deleted AND non-existent entities from the relationship graph
2. Adding a `filtered` field to EntityRelationshipResult which indicates how many results were post-filtered out of the result set (for these reasons). 
Ready for review. Verified locally using both hard-deletes + soft-deletes for Datasets, Dashboards, and Charts.
> fix(lineage): Fix Upstream + Downstream Count in presence of Soft-Deleted / Non-Existent references

- metadata-ingestion/setup.py
> chore(ci): relax bigquery dependency

- metadata-ingestion/build.gradle
Automatically marks the metadata-ingestion `src` and `tests` directories as such in IntelliJ project structure. I find myself having to do this multiple times, so hopefully this makes it happen automatically
> build(idea): mark metadata-ingestion sources and tests

- metadata-ingestion/docs/transformer/intro.md
It's a common problem in OSS to use transformers and add tags, terms, etc. urns that don't actually exist in DataHub yet. Then it results in unexpected behavior where entities aren't created and therefore you can't use them in Advanced Search (biggest one we hear about) and profiles aren't created (they don't see their domain in the Domains page)
> fix(docs) Update transformers docs to note not minting urns

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_common.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/ldap.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/ingestion/source/pulsar.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/ingestion/source_config/pulsar.py
- metadata-ingestion/tests/unit/test_kafka_source.py
Following the changes from https://github.com/datahub-project/datahub/pull/6795, I believe that `get_platform_instance_id` can now return `None`. See its only usage:
In `StatefulIngestionSourceBase._get_last_checkpoint`
```
try:
platform_instance_id = self.get_platform_instance_id()
except NotImplementedError:
pass
else:
last_checkpoint_aspect = self.ingestion_checkpointing_state_provider.get_latest_checkpoint(  # type: ignore
pipeline_name=self.ctx.pipeline_name,
job_name=job_id,
platform_instance_id=platform_instance_id,
)
```
Note that in that PR, `get_latest_checkpoint` was configured to accept an optional `platform_instance_id` (and also note that in the not implemented case, `None` is implicitly passed?)
Since we still want to keep implementations of `get_platform_instance_id` for …
> fix(ingest): Do not require platform_instance for stateful ingestion

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
For scenarios such as 
Table->View1->View2
1. Lineage generated for View2 by parsing audit logs : Table, View1 -> View2
2. Lineage generated for View2 by parsing View DDL : View -> View2
Second is more accurate over first one. Hence in this PR we use SQL parsing lineage over lineage from audit logs, if SQL parsing lineage is available.
Another approach to fix this would be to fix point 1 above to not include tables that are not directly accessed in View DDL. However currently that happens only if config `lineage_use_sql_parser` is enabled
> fix(ingest/bigquery): Prefer parsed lineage for view over lineage from audit logs

- datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTermsResult.tsx
- datahub-web-react/src/app/entity/glossaryTerm/profile/RelatedTerm.tsx
- datahub-web-react/src/app/entity/shared/constants.ts
- datahub-web-react/src/graphql/glossaryTerm.graphql
Add "Contained by" and "Inherited by" tabs to glossary related terms view as requested in feature request https://feature-requests.datahubproject.io/p/list-inbound-relationships-to-glossary-terms
> feat(frontend): add additional tabs to glossary terms view

- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/tests/integration/kafka/kafka_mces_golden.json
- metadata-ingestion/tests/unit/test_kafka_source.py
Still missing some context here. How come we used to include topics in the browse path but now we don't?
> fix(ingest/kafka): Remove topic from browse path

- metadata-ingestion/tests/integration/lookml/expected_output.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_golden_deleted_stateful.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_offline_deny_pattern.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_offline_platform_instance.json
- metadata-ingestion/tests/integration/lookml/lookml_mces_with_external_urls.json
- metadata-ingestion/tests/integration/lookml/lookml_reachable_views.json
Normalizing golden files so that future diffs will be easier to understand.
> refactor(ingest): lookml - fix up golden files in normalized form

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
SqlAlchemy quotes with '"' but we prefer ` quoting on BigQuery and currently there are columns where we double quoting.
See example from logs how it looks now:
```
[2023-02-23 08:32:38,107] DEBUG    {datahub.utilities.sqlalchemy_query_combiner:270} - Executing query normally: SELECT APPROX_COUNT_DISTINCT(`"My_Column"`) 
```
And this is how it should after the fix:
```
[2023-02-23 08:32:38,107] DEBUG    {datahub.utilities.sqlalchemy_query_combiner:270} - Executing query normally: SELECT APPROX_COUNT_DISTINCT(`My_Column`) 
```
> fix(ingest/bigquery): Fixing double quoting in profiling approx count query

- docs-website/src/pages/_components/Logos/logos.module.scss
CSS order/specificity was different on the production build causing the logo size class heights to be overridden by the default height.
> docs(website): fix homepage logo sizing

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
- datahub-web-react/src/app/analyticsDashboard/components/TimeSeriesChart.tsx
- datahub-web-react/src/app/analyticsDashboard/components/__tests__/timeSeriesChart.test.tsx
- datahub-web-react/src/app/shared/time/__tests__/timeUtils.test.tsx
> fix(analytics): remove zero values being added in charts

- datahub-web-react/src/app/lineage/LineageEntityEdge.tsx
- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/graphql/lineage.graphql
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/TimeFilterUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAOTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/TimeFilterUtilsTest.java
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_query_filters_1.json
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_time_query_filters_1.json
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/GraphIndexUtils.java
Few Changes
- Fix the "runId" filter query to correctly use the keyword field (fixes Ingestion Run Summaries)
- Fix the Lineage Tab and Lineage View Time Selectors to correctly filter by time. This correctly excludes edges where createdOn or updatedOn are both considered "missing" (null or 0). 
- Only add custom extracted createdOn / updatedOn to edges if they are non-zero. 
- Fix the UI side Lineage Graph View to always include the timestamp millis
- Small UI Improvements to the Lineage Graph View
Ready to review
> fix(lineage): Fixing Timeline Lineage Filters

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/tests/unit/test_glue_source.py
This has been deprecated for 10 months now.
> chore(ingest/glue): cleanup deprecated `underlying_platform` config

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
If you provide a custom endpoint in the s3 datalake source configuration, it is used to scan the bucket and identifying the datasets, but the endpoint and the region are not propagated to the spark job responsible for profiling the data. So in our case, we had a custom minio setup and noticed that the profiling job still used the aws s3 endpoint (resulting in not authorized errors)
> fix(ingest/s3): propagate s3 endpoint to profiling

- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
These labels helps the CLI changes in PR state to know which compose file is a setup job and which is a service. 
Since the new CLI uses these labels AND it uses the compose file from the release version, it won't work for older releases. `datahub docker quickstart --version <v0.10.1`
To prevent failures CLI will use the compose files from merge commit of this PR for all `--version <v0.10.1`
> Add setup job labels to compose files

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
fix(manifest-parser): checks to ensure nodes key is present
dbt's manifest file can have seeds that list a depends_on key without the nodes key. this change checks to ensure the nodes key is present before appending to the upstream_nodes list. Example node from our dbt project:
`{seed.***.customer:{'database': '***', 'schema': '***', 'name': 'customer', 'resource_type': 'seed', 'package_name': '***', 'path': 'customer.csv', 'original_file_path': 'seeds/customer.csv', 'unique_id': 'seed.***.customer', 'fqn': ['***', 'customer'], 'alias': 'customer', 'checksum': {'name': 'sha256', 'checksum': '***'}, 'config': {'enabled': True, 'alias': None, 'schema': 'example', 'database': None, 'tags': [], 'meta': {}, 'materialized': 'seed', 'incremental_strategy': None, 'persist_docs': {}, 'quoting': …
> fix(ingest/dbt): check for nodes key before accessing

- datahub-web-react/src/app/entity/shared/tabs/Lineage/LineageTab.tsx
- smoke-test/tests/cypress/cypress/e2e/lineage/impact_analysis.js
- smoke-test/tests/cypress/cypress/e2e/lineage/lineage_graph.js
- smoke-test/tests/cypress/cypress/support/commands.js
- smoke-test/tests/cypress/integration_test.py
- smoke-test/tests/cypress/package.json
- smoke-test/tests/cypress/yarn.lock
- smoke-test/tests/setup/lineage/constants.py
- smoke-test/tests/setup/lineage/helper_classes.py
- smoke-test/tests/setup/lineage/ingest_data_job_change.py
- smoke-test/tests/setup/lineage/ingest_dataset_join_change.py
- smoke-test/tests/setup/lineage/ingest_input_datasets_change.py
- smoke-test/tests/setup/lineage/ingest_time_lineage.py
- smoke-test/tests/setup/lineage/utils.py
- smoke-test/tests/utils.py
> tests(cypress): add improved Cypress tests for timeline lineage

- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
We recently introduced a change that will capitalize the first letter of subtype names. There's only one place in the frontend that I could find that would be affected and it's checking whether or not we show the "View Definition" tab for datasets. This will lowercase the subtype name and the name it checks against to make it standard.
> fix(ui) Standardize subtypes casing with View Definition tab

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/elasticsearch/steps/BuildIndicesPostStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/elasticsearch/steps/BuildIndicesPreStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/elasticsearch/util/IndexUtils.java
Attempt to validate the index.blocks.write setting is set as expected based on reports of increasing document counts even after the update setting is being accepted by elasticsearch. Not able to reproduce this behavior locally, however reading the setting back should not impact the operation.
> feat(elasticsearch): validate index.blocks.write setting

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
We don't talk about using dataclass for non-ingestion-data classes in the contribution guidelines, but I like this as it reduces the repeated types and is more declarative
EDIT: I guess the downside is we lose "private" status on some variables that shouldn't be adjusted by outside code. I feel like it should be obvious you're not supposed to change these values though (after init)
> refactor(ingest): Convert FileBackedDict to dataclass for cleaner init

- metadata-ingestion/src/datahub/ingestion/source/git/git_import.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
- metadata-ingestion/tests/unit/test_cli_logging.py
> fix(ingest): prevent logging from blowing up on TypeErrors

- datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
We've heard that the tooltip for the "changed <time ago>" on search results cards is not helpful. This makes things a bit clearer.
> fix(ui) Make tooltip on search results stats summary clearer

- docs/how/updating-datahub.md
- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion/setup.py
As described at length in
<https://github.com/datahub-project/datahub/blob/v0.10.0/metadata-ingestion/setup.py#L62> the current state of platform compatibility for the confluent_kafka is complicated.  It can be a source of installation incompatibility and general friction.  To make the airflow plugin easier to include in resolvable dependencies sets across a variety of platforms, unbundle the datahub-kafka emitter into extras_require.
- [X ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ X] Docs related to the changes have been added/updated (if applicable). If a new …
> feat(ingest): unbundle airflow plugin emitter dependencies

- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
- metadata-ingestion/tests/cli/test_quickstart_version_mapping.py
Now that the branch containg the change has been merged we have the merge commit, so we can look for it from the cli (1d3339276129a7cb8385c07a958fcc93acda3b4e)
> feat(cli): finalizing quickstart config commit hash

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
Due to incorrect table_type in query, materialized views were not getting ingested earlier.
See here for list of table_types in BigQuery - https://cloud.google.com/bigquery/docs/information-schema-tables#:~:text=the%20tableId.-,table_type,-STRING
> fix(ingest/bigquery): fix missing materialized views

- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/ingestion/api/ingestion_job_checkpointing_provider_base.py
- metadata-ingestion/src/datahub/ingestion/api/sink.py
Depending on python versions, the minimum typing_extensions is
`>=3.7.4.3` or `>=3.10.0.2`. (And needs to stay that way for Airflow.)
However, typing_extensions.Self is only available starting in `4.0.0` https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#added-in-version-400
This partially reverts #7313 to avoid the use of
typing_extensions.Self.
Fixes #7370
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ x] Links to related issues (if applicable)
> fix(ingest): limit typing_extensions classes to those available in min version

- metadata-ingestion/setup.py
This library has packages `googleapiclient` and `apiclient` and these are not used anywhere in codebase for BigQuery.
> chore(ingest): remove unused dependency for bigquery

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateIngestionExecutionRequestResolver.java
We were setting pipeline_name into manual ingestion runs (if there wasn't one already) inconsistently from how we injected it into scheduled runs. We should be doing the same thing for both and that's going to be the ingestion source urn.
> fix(ui-ingestion) Fix UI manual ingestion runs by consistently setting pipeline_name

- docs-website/sidebars.js
This way we can get rid of all those "Overview" docs and just make them the category header.
I'd suggest reviewing this PR with "hide whitespace changes" enabled.
> feat(docs-website): support category links

- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/parser.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/tree_function.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi-lexical-grammar.rule
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
Right now this only works for non-admin API. Implementing this for the admin API interface will require additional investigation.
> feat(ingest/powerbi): support PowerBI parameter references

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Queries/QueryCardDetails.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Queries/QueryModal.tsx
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/kafka/DataHubUpgradeKafkaListener.java
- Fixing the horizontal scroll for the Query Modal by making the Query full height of the parent container.
- Fixing a bug where a "0" will appear in the cast that createdAt time does not exist
- Adding a log info when GMS fails to startup due to waiting on kafka. 
Ready to review
> fix(): Fix Query Detail Modal Scroll + add misc log messages

- datahub-frontend/app/controllers/Application.java
We recently upgraded to a newer version of Play framework (thanks @david-leifker ) which unlocked the ability to use a new config provided by Play to disable the automatic encoding that was being performed on inbound requests. This means that the proxy will be able to be used more effectively with the APIs served by gms.
> fix(frontend proxy): Disable unnecessary URL encoding at the proxy layer

- docker/monitoring/grafana/dashboards/datahub_dashboard.json
Make all panels use the datasource variable. There are 107 panels using the variable and 12 that dont.
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
> fix(grafana): use variable datasource uid

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> fix(ingest/looker): stringify looker user ids

- metadata-ingestion/tests/integration/s3/test_s3.py
The s3 test has suddenly become flaky with respect to a few fields. 
This PR suppresses those fields in the test to ensure CI stays green while we try to understand why this has happened.
> fix(test): suppress s3 golden file test for specific paths

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
- Sets pickle as the default serde method
- Fixes a subtle bug around the close() method
- Adds much better comments
> feat(ingest): fix edge cases + interface cleanup for file-system APIs

- .github/workflows/qodana-scan.yml
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/DescriptionUtils.java
Adds a scan https://github.com/datahub-project/datahub/actions/runs/4406880321. If we go to summary we can download `qodana-report` which can be viewed  as explained here https://www.jetbrains.com/help/qodana/html-report.html
It shows up as 
Trying to upload the report to github code scans
> chore(ci): try Qodana Scan for quality

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/kafka/DataHubUpgradeKafkaListener.java
…grade job to complete before starting
Users have been confused why GMS is not starting when there is no visible error in the logs. Increase log level to error for the log indicating that it is still waiting for the datahub-upgrade job to run.
> fix(logging): increase log level for system-upgrade job to complete before starting

- datahub-web-react/src/app/ingest/source/IngestionSourceTable.tsx
If `total` is greater than 0 but we still somehow get no `executionRequests` then we will throw an error on the frontend and whitepage it. This checks the right thing before getting the first element in an array.
> fix(ui) Safeguard ingestion execution request check

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/mlFeature/MLFeatureEntity.tsx
- datahub-web-react/src/app/entity/mlPrimaryKey/MLPrimaryKeyEntity.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/nav/EntityProfileNavBar.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/nav/LineageSelector.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/nav/ProfileNavBrowsePath.tsx
- datahub-web-react/src/graphql/chart.graphql
- datahub-web-react/src/graphql/dashboard.graphql
- datahub-web-react/src/graphql/dataJob.graphql
- datahub-web-react/src/graphql/dataset.graphql
- datahub-web-react/src/graphql/lineage.graphql
- datahub-web-react/src/graphql/mlFeature.graphql
- datahub-web-react/src/graphql/mlFeatureTable.graphql
- datahub-web-react/src/graphql/mlModel.graphql
- datahub-web-react/src/graphql/mlModelGroup.graphql
- datahub-web-react/src/graphql/mlPrimaryKey.graphql
We've found that retrieving lineage counts can sometimes take much longer than the other parts of the primary entity query. In this PR, we extract out fetching the upstream and downstream count from the primary entity query and instead move it into a new LineageSelector.tsx sub-component within the nav bar.
Much better!
> refactor(ui): Separate entity lineage counts query from rest of entity query

- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/src/datahub/utilities/urns/data_flow_urn.py
- metadata-ingestion/tests/conftest.py
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_after_golden_mces.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_before_golden_mces.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_mces_golden.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_mongo_mces_golden.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_mongo_to_file.yml
- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
Items covered in this PR
- add platform instance support for kafka connect platform entities
- add stateful ingestion support
- move connector pattern allow/deny check earlier in the code execution, to avoid processing lineage for denied connectors
- rewrite tests for reducing overall kafka connect test time
It also appears that this source can use some refractor for readability and better exception handling, however, I would create separate PR for that after this PR is merged, in order to avoid difficulty in reviewing.
> feat(ingest/kafka-connect): add stateful ingestion and platform instance support

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
Rather than handle sharing sqlite connections via the filename-based `_SqliteConnectionCache`, creates a SQlite `ConnectionWrapper` that can be passed into `FileBacked` objects. Personally liked this more, but happy to discuss pros and cons.
Pros:
- Connection sharing is more transparent, via a shared object, rather than via a shared filename Path
- User doesn't need to worry about creating a ingestion-run-unique filename
- Allows for automatic file cleanup
- Removes complexity around SqliteConnectionCache
Cons:
- Adds complexity / another layer with a wrapper around the SQlite connection
* I considered inheriting from `sqlite.Connection` directly, rather than wrapping it, but didn't want to worry about interfering with its internals
- Filenames no longer can be specified when creating …
> refactor(ingest): Use shared connection wrapper over connection cache

- metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
support lineage time filter for neo4j backend graphservice.
1. modify addEdge to support createdOn, createdActor, updatedOn, updatedActor, startUrn, endUrn, properties (store lineage source from ui)
1.1 startUrn is real source node and endUrn is real destination node
1.2 add r_ relationships for real upstream downstream lineage
```mermaid
graph LR
B(table_B) --> |DownstreamOf| A(table_A)
A(table_A) --> |startUrn: table_A -r_DownstreamOf- endUrn: table_B| B(table_B)
```
2. implement upsertEdge, removeEdge
3. modify getLineage to support:
3.1 start, end time filtering on (createdOn or updatedOn)
3.2 createdOn not exists and updatedOn not exists
3.3 lineage created from ui
3.4 pattern matching for case by using r_ relationships:
```mermaid
graph LR
C(job1) --> |Consumes| A(table_A) …
```
> feat(metadata-io): add support in Neo4jGraphService for lineage time filter

- metadata-ingestion/src/datahub/cli/docker_cli.py
- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
Thanks to @pedro93 for finding the fix here.
> fix(docker): fix gradle quickstart version parsing

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/utilities/source_helpers.py
- metadata-ingestion/src/datahub/utilities/urns/urn_iter.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Currently adding it for dbt and BigQuery, but it's pretty easy to add support for more sources in the future.
> feat(ingest): add auto_materialize_referenced_tags helper

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
A PR went in for support of diffMode for Neo4J, the class check is no longer necessary although could cause an issue if someone is using DGraph.
> fix(revert): remove unnecessary class check

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/RetentionService.java
- metadata-io/src/test/java/com/linkedin/metadata/AspectGenerationUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> lint(test): remove unused imports, other test fixes

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> fix(ingest/bigquery): Pass whether view is materialized; pass last_altered correctly

- metadata-ingestion/examples/cli_usage/gen_schemas.py
- metadata-ingestion/examples/cli_usage/group/foo.group.dhub.yaml
- metadata-ingestion/examples/cli_usage/group/group.dhub.yaml_schema.json
- metadata-ingestion/examples/cli_usage/group/run_example.sh
- metadata-ingestion/examples/cli_usage/user/bar.user.dhub.yaml
- metadata-ingestion/examples/cli_usage/user/run_example.sh
- metadata-ingestion/examples/cli_usage/user/user.dhub.yaml_schema.json
- metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py
- metadata-ingestion/src/datahub/api/entities/corpuser/corpuser.py
- metadata-ingestion/src/datahub/cli/specific/file_loader.py
- metadata-ingestion/src/datahub/cli/specific/group_cli.py
- metadata-ingestion/src/datahub/cli/specific/user_cli.py
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/entrypoints.py
- smoke-test/tests/cli/user_groups_cmd/test_group_cmd.py
- smoke-test/tests/cli/user_groups_cmd/test_user_cmd.py
This PR:
- Introduces two new commands `user` and `group` and starts the pattern for creating new commands in the future like `dataset` to work with entities in the metadata model. 
- Creates a simple yaml based format for specifying users and groups.
Companion docs PR: #7574
> feat(cli): add user and group commands to create users and groups

- .github/workflows/check-datahub-jars.yml
- metadata-ingestion/src/datahub/ingestion/graph/client.py
Previously we'd just return None, which was a confusing response for users.
> fix(cli): protect against timeseries get_aspects

- metadata-ingestion/src/datahub/ingestion/graph/client.py
Bumps default max_threads from 1 to 15
> perf(ingest): Increase default rest sink parallelism

- docs-website/.gitignore
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/test_dbt.py
This reverts https://github.com/datahub-project/datahub/pull/6467.
> fix(ingest/dbt): enable incremental lineage by default

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> fix(ingest/bigquery): Fix BigQueryTableType enum accesses

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
> fix(ingest/looker): correct looker/lookml capability reports

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
Quotes accidentally removed in [this PR](https://github.com/datahub-project/datahub/pull/7660/files#r1149112271).
> fix(ingest/bigquery): quote string constants in query

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
- Refactors `__iter__`
- Manually implements `.items()` and `.values()`
- Adds `sql_query_iterator` and `filtered_items`
- Renames `connection` -> `shared_connection`
- Removes unnecessary flush during `close` if connection is not shared
- Adds context manager dunder methods
> perf(ingest): Improve FileBackedDict iteration performance; minor refactoring

- metadata-ingestion/src/datahub/utilities/mapping.py
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/sample_dbt_manifest.json
- metadata-ingestion/tests/integration/dbt/test_dbt.py
This was working previously as well. The other changes are simply refactoring.
> test(ingest/dbt): add test for column meta match

- metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
Fixing the Redshift lineage query, which got broken with the latest redshift upgrade
> fix(ingest/redshift): Lineage query fix to work with the latest redshift

- metadata-ingestion/src/datahub/cli/lite_cli.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/extractor/json_schema_util.py
- metadata-ingestion/src/datahub/ingestion/source/confluent_schema_registry.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/parser.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
- metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_utils.py
- metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/lite/duckdb_lite.py
- metadata-ingestion/tests/cli/test_quickstart_version_mapping.py
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
- metadata-ingestion/tests/integration/powerbi/test_powerbi.py
- metadata-ingestion/tests/integration/powerbi/test_stateful_ingestion.py
- metadata-ingestion/tests/unit/test_check_upgrade.py
> chore(ingest): formatting + cleanup MCPW usages

- docs-website/generateDocsDir.ts
- metadata-ingestion/setup.cfg
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/tests/performance/README.md
- metadata-ingestion/tests/performance/__init__.py
- metadata-ingestion/tests/performance/bigquery.py
- metadata-ingestion/tests/performance/data_generation.py
- metadata-ingestion/tests/performance/data_model.py
- metadata-ingestion/tests/performance/test_bigquery_usage.py
Performance testing framework that contains:
- A simplified model of a data warehouse's metadata (tables, views, queries, etc.)
- A function for generating examples of such a model of different sizes
- A function for converting generic `Query`s into BigQuery `AuditEvent`s
- An unfinished test for testing bigquery usage performance
> test(ingest/bigquery): Add performance testing framework for bigquery usage

- docs/how/delete-metadata.md
Currently the timeseries delete doc is mis-leading, allowing users to delete the wrong fields. Removing this so no one shoots themselves in the foot.
> fix(docs): Fixing timeseries delete doc until code path is fixed 

- docs-website/sidebars.js
- docs/quick-ingestion-guides/bigquery/setup.md
- docs/quick-ingestion-guides/redshift/configuration.md
- docs/quick-ingestion-guides/redshift/overview.md
- docs/quick-ingestion-guides/redshift/setup.md
- docs/quick-ingestion-guides/snowflake/setup.md
Adding Redshift ingestion quickstart guide
Small fix for BigQuery and Snowflake doc
> doc(redshift) - Adding Redshift ingestion quickstart guide

- metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
- metadata-ingestion/src/datahub/ingestion/source/file.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/lineage.py
- metadata-ingestion/src/datahub/ingestion/source_config/csv_enricher.py
- metadata-ingestion/src/datahub/utilities/source_helpers.py
- metadata-ingestion/tests/integration/remote/golden/remote_lineage_golden.json
- metadata-ingestion/tests/unit/test_file_lineage_source.py
A few followups to https://github.com/datahub-project/datahub/pull/7552, + some modernization of the sources, with `auto_workunit_reporter`.
Refactoring got the most complicated on the file lineage source but logic should still be the same, sorry if it's a difficult review.
> refactor(ingest): Minor cleanup of File, CsvEnricher, BusinessGlossary, and FileLineage sources

- datahub-web-react/src/app/domain/CreateDomainModal.tsx
- smoke-test/tests/cypress/cypress.config.js
- smoke-test/tests/cypress/cypress/e2e/mutations/domains.js
The domains test was flaky due to changes in how search ranking is performed. This change addresses the issue. It also makes the test more resilient to re-runs by generating a unique urn on each run. 
> fix(ci): Fixing broken Domains Test 

- metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py
When emitting `CorpGroups` with the current codebase, the following error occurs: 
```python
File "/usr/local/lib/python3.10/site-packages/datahub/api/entities/corpgroup/corpgroup.py", line 236, in emit                                                                                        
datahub_graph = self._datahub_graph_from_datahub_rest_emitter(emitter)      
TypeError: unhashable type: 'CorpGroup'      
```
As far as I could trace back, this is caused by the cache-decorator `@lru_cache(maxsize=32)`.
> fix(sdk): remove rest emitter to graph cache in CorpGroup

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
- metadata-ingestion/src/datahub/utilities/stats_collections.py
Bit again by not separating out some changes into a smaller PR. Takes changes from https://github.com/datahub-project/datahub/pull/7663 and extends them for lineage.py, i.e.:
- Moves `get_sanitized_table_ref` calls to ReadEvent / QueryEvent creation
- Standardizes how the audit log is read and parsed, unifying code when reading from gcp logging vs audit metadata (exported logs)
- Adds error handling around the parsing of each event, to catch errors from the new `get_sanitized_table_ref` calls
Also. makes `TopKDict` inherit from `DefaultDict` and cleans up calls around that.
> refactor(ingest/bigquery): Standardize audit log parsing and make TopKDict a DefaultDict

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/utilities/source_helpers.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Now our subtypes will mirror those from dbt e.g. model, source, snapshot, etc. Models will get a second one that represents the materialization status, but those don't get shown in the UI to my knowledge.
They're also capitalized for consistency with other subtypes elsewhere in the codebase.
> feat(ingest/dbt): update subtypes for dbt

- docs/api/tutorials/creating-users-and-groups.md
- metadata-ingestion/examples/library/upsert_group.py
- metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py
- Fix a bug where only the last admin was saved under ownership
- Renaming admin -> owner to match the UI
- Also uses the new file inlining support to reduce copying.
> feat(sdk): fix ownership emission for groups

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteForMultipleResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutocompleteUtils.java
- datahub-graphql-core/src/main/resources/search.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteForMultipleResolverTest.java
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/editor/extensions/mentions/MentionsComponent.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/SearchablePage.tsx
- datahub-web-react/src/app/search/autoComplete/quickFilters/QuickFilters.tsx
- datahub-web-react/src/providers/QuickFiltersProvider.tsx
We should be filtering auto-complete results by a view but we weren't before. This adds a new optional `viewUrn` param to the auto-complete endpoint and does mostly the same logic for combining entity types and filters as we do in the search endpoint. The difference here is that we don't pass in entity types as a filter, but get the actual entity class and call `autocomplete` on each of them. So here we just filter those out based on what's passed in the view combined with what's passed into the input.
This also passes in a viewUrn from the FE to quick filters. The backend was already built to accept this, it was just missed on implementation.
> fix(auto-complete) Pass in views to auto-complete endpoint for filtering

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/tests/unit/test_bigquery_lineage.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> fix(ingest/bigquery) - Lineage edges use datetime with timezone

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
Converted getting views and tables to iterators. Even though this is slightly less clean for usage, I think we should try to generate iterators as a default for memory efficiency
Fixes bug around expiration time being impossible to represent in python because it's too far in the future
> fix(ingest/bigquery): Raise report_failure threshold; add robustness around table parsing

- datahub-web-react/src/app/entity/tag/Tag.tsx
- datahub-web-react/src/graphql/fragments.graphql
- datahub-web-react/src/graphql/search.graphql
Previously, we were using the urn-derived "name" field in some cases to render the name of a Tag. In this PR, we change to use the correct "name" field of the properties aspect, which can be changed once the Tag has been created.
This fixes a few different scenarios:
1. search preview
2. autocomplete dropdown
3. entity profile tags section
Ready for review 
Before (notice the URN derived name): 
(Fixed color in autocomplete)
> fix(ui): Fix tags display name + color in UI for autocomplete, search preview, entity profile

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useTagsAndTermsRenderer.tsx
When we updated ant design, I believe they introduced a new bug where the `rowIndex` for nested table rows is inconsistent depending on the method you're using. The `onCell` function gives the overall index as if it were a flat list of rows while the `render` method gives the index of the row in the nested field context (this is not how it used to work).
Therefore, the `tagHoveredIndex` piece of state would never line up with the row and it would never think you're hovering over it so we would never show the option to add tags and terms. Since `fieldPath` is unique in a schema anyways, we don't need the `rowIndex` here so I simply remove it.
> fix(ui) Fix tags and terms columns on nested schema fields

- build.gradle
Upgrade to version without stack overflow vulnerability: https://research.jfrog.com/vulnerabilities/stack-exhaustion-in-json-smart-leads-to-denial-of-service-when-parsing-malformed-json-xray-427633/
> (build) Upgrade json-smart dependency to 2.4.9

- build.gradle
Upgrade to version which does not include CVE-2023-1436 
https://github.com/datahub-project/datahub/security/code-scanning/689
> build: Upgrade jettison dependency to 1.5.4

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/kafka-setup/Dockerfile
We have to update Snakeyaml to use Snakeyaml 2.0 instead of 1.33
Context: https://www.veracode.com/blog/research/resolving-cve-2022-1471-snakeyaml-20-release-0
> fix(snakeyaml): cve-2022-1471 upgrade

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
Need to sanitize the refs to remove shard information, to match what we do when parsing events from the audit log. Also generate view table refs when usage but not lineage is enabled.
> fix(ingest/bigquery): Fix lineage / usage table ref checks

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
**The issue**
When processing this situation: Base Project file -> includes External Project file A -> includes External Project file B, the second include directive was not being processed correctly. This was because we were looking for file B's include path in the base project rather than realizing that file A was in the external project and hence internal links should stay within the External Project.
**How does this PR solve it?**
We properly retain the context of a file so that we can process its includes correctly. We're doing that by deriving `base_folder` (now called `resolved_project_folder`) from the active `project_name` + any include directives.
**What else is happening?**
- Because we now derive the `base_folder` from the `base_projects_folder` and the active `project_name`, …
> feat(ingest/lookml): correctly handle include directives from imported projects

- datahub-web-react/src/app/context/useInitialRedirect.ts
Due to these composite condition, we only mark the initial path as "bootstrapped" once we've hit the HOME page. However, this causes a subtle bug wherein if you link directly to a particular page that is not the home page, clicking to go home will result in a one-time redirect. This in turn marks the "bootstrap" process as completed. 
In this fix, we always mark the initial path as bootstrapped after the initial page load. If you go to the home page, this may involve a redirect to the previous page that you were on. If you go directly to a url that is not the home page, we will skip the redirect process altogether as the user is showing intent to navigate to the page directly. 
> fix(ui): Fix subtle initial redirect bug

- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
> feat(ingest): Track disk usage in report

- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
- Removing the need for pg_user table as it needed additional permission which did not need before
- Fixing a lineage query which was broken on newer redshift version
> fix(ingest/redshift) - Remove pg_user table from metadata queries

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/tests/unit/test_bigquery_usage.py
> fix(ingest/bigquery): Handle null values from usage aggregation

- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/performance/README.md
- metadata-ingestion/tests/performance/data_generation.py
- metadata-ingestion/tests/performance/test_bigquery_usage.py
- metadata-ingestion/tests/unit/test_bigquery_usage.py
Not very happy with these changes, but includes a few optimizations to improve speed and disk usage.
Think the handling around hash collisions is super ugly, but hopefully is fine? I considered compressing the queries in the queries filebackeddict but reversed those changes -- hopefully truncating is enough.
Overall, this adds:
- Truncating of queries to at most 24000 characters
- Stores hashes of queries, handling hash collisions with an in-memory map (should be very rare), and converting back with a file-backed map. Is there a better way to reduce disk size specifically of the main file? Sqlite performance seems to severely degrade for large files, around 5-10GB size.
- Compresses values (ReadEvent and QueryEvent) of FileBackedDicts
- Delays sqlite index creation on extra_columns until …
> perf(ingest/bigquery): Improve bigquery usage disk usage and speed

- datahub-web-react/src/app/SearchRoutes.tsx
There's a routing bug in the app right now where if a user goes to a route that doesn't exist, instead of showing them our 404 page, we show them an empty business glossary page. This is because routes were getting caught in the `GlossaryRoutes` component and never making it past it to show the `NoPageFound` component.
This PR fixes that by adding a real route that anything that starts with `glossary` will render the `GlossaryRoutes` component. So now a broken link will actually render our 404 page.
> fix(ui) Fix 404 page routing bug

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
The column name is `directSources`
https://docs.snowflake.com/en/sql-reference/account-usage/access_history
> fix(ingest/snowflake): fix column name in snowflake optimised lineage

- docs-website/docusaurus.config.js
- docs-website/package.json
- docs-website/src/components/MarkpromptHelp/index.jsx
- docs-website/src/components/MarkpromptHelp/markprompthelp.module.scss
- docs-website/src/styles/global.scss
- docs-website/src/theme/Footer/index.js
- docs-website/yarn.lock
Adds Markprompt help chat bot. It will appear in the lower right of the viewport on all pages.
- New dependencies for the markprompt component itself and a simple modal package.
- Adds new environment variable `DOCUSAURUS_MARKPROMPT_PROJECT_KEY` for the markprompt project key
- Default Markprompt styling uses Tailwind classes so rather than adding Tailwind just for this, added some basic styling. (It appears there are plans for a future headless version of the component.)
> docs(): add markprompt help chat

- metadata-ingestion/src/datahub/cli/docker_check.py
- metadata-ingestion/src/datahub/cli/docker_cli.py
- Increase quickstart timeout from 8 to 10 minutes.
- Only run `docker compose up` when required, instead of wasting compute by running it every 30 seconds.
Hopefully this will reduce quickstart errors in OSS and in CI.
> feat(cli): improve quickstart stability

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionRunEventResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardUsageStatsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardUsageStatsUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/TimeSeriesAspectResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/assertion/AssertionRunEventResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardStatsSummaryTest.java
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-ingestion/examples/mce_files/bootstrap_mce.json
- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/TimeseriesAspectService.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-io/src/test/java/com/linkedin/metadata/ESTestConfiguration.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectServiceTest.java
- metadata-service/restli-api/src/main/idl/com.linkedin.entity.aspects.restspec.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
Currently, we have a bug where the Operations for a dataset should be sorted descending with respect to time by the "lastUpdatedTimestamp" field of the aspect, which represents the actual time of the Operation. This was previously not possible because when fetching time-series aspects, there was no way to provide a custom sort-order (other than the default of sorting by timestampMillis field descending). 
In this PR, we add the ability to sort by non-timestampMillis fields for any Time-Series Aspects. Additionally, we make a small change to the resolution of Dataset "operations" to sort by the "lastUpdatedTimestamp" by default.
Included other misc refactoring and javadocs, nothing major. Specifically:
1. Remove the "getLatestValue" parameter of the TimeseriesAspectService getAspectValues …
> feat(timeseries): Support sorting timeseries aspects by non-timestampMillis field + fix operations resolver

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
A bad merge took this out of the updates for patch PR, this change is necessary to prevent downstream errors where the dataMap is modified.
> fix(mcl): fix improper pass by reference

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/utils/ESUtilsTest.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/query/filter/Condition.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.analytics.analytics.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
In this PR, we support a new filter condition inside Criterion.pdl for checking whether a field EXISTS in elasticsearch. We also add some unit tests to ESUtils.java and refactor to place private methods below public ones. 
Change summary
1. Refactor ESUtils.java for readability
2. Support EXISTS operation inside Condition.pdl 
3. Add unit tests to confirm that ES Filters are consistently constructed as expected in various cases
Why make this change? This unlocks the ability to easily support EXISTS style filters from the UI and elsewhere against particular index fields. 
> refactor(platform): Refactoring ES Utils, adding EXISTS condition support to Filter Criterion

- datahub-web-react/src/app/entity/domain/DomainEntitiesTab.tsx
- datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedEntity.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchSection.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
- datahub-web-react/src/app/glossary/GlossaryRoutes.tsx
User's were experiencing bugs with the cache after adding Glossary Terms and Domains to entities and their Related Entities pages not updating. This skips the cache for those two specific pages all the time.
This also fixes a fe UX overflow scrolling issues that I noticed while working on this ticket.
> fix(ui) Disable cache on Domain and Glossary Related Entities pages

- metadata-ingestion/docs/sources/dbt/README.md
- metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
- metadata-ingestion/src/datahub/ingestion/source/s3/config.py
> docs(ingest): update dbt and aws docs

- metadata-ingestion/src/datahub/cli/docker_cli.py
Updates `datahub docker ingest-sample-data` to bootstrap whatever DataHub server is configured in `~/.datahubenv`
> feat(cli): Modifies ingest-sample-data command to use DataHub url & token based on config

- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.monitoring.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- docker/quickstart/generate_and_compare.sh
- docker/quickstart/generate_docker_quickstart.py
- docker/quickstart/generate_docker_quickstart.sh
Initially reported in #7878. Looks like we fail to run with some versions of Docker / compose.
I'm also refactoring some of our code to be a bit more maintainable / readable moving forwards.
> fix(cli): remove duplicate labels from quickstart files

- docker/mysql-setup/Dockerfile
This PR fixes a bug found when running the `datahub-mysql-setup` job within a kubernetes cluster that connects to a MySQL 8 database instance. It appears the current mysql-setup script uses the `mysql-client` alpine package that does not include files necessary to support the MySQL `caching_sha2_password` plugin. An additional package is required to get the setup script to work. 
1. I am running a MySQL 8.0.32 instance in Azure with the `caching_sha2_password` plugin active (which occurs by default).
```sql
mysql> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.0.32    |
+-----------+
1 row in set (0.04 sec)
```
```sql
mysql> SELECT * FROM INFORMATION_SCHEMA.PLUGINS WHERE PLUGIN_NAME = 'caching_sha2_password';
+-----------------------+----------------+---------------+------ …
```
> fix(deploy): add missing plugin files for mysql-client library in mysql-setup

- metadata-ingestion/setup.py
> fix(ingest/unity-catalog): Add usage_common dependency to unity catalog plugin

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/unity_catalog.tsx
- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
In our logs, we already display the fully qualified names for catalogs/schemas whenever we drop something. This changes the actual patterns to use the things that it's already printing out, and hence yields more explainable behavior.
This also updates some stuff in the UI ingestion form which just filled the wrong values into certain fields.
Closes https://github.com/datahub-project/datahub/issues/7489.
> fix(ingest/unity): use fully qualified catalog/schema patterns

- metadata-ingestion/src/datahub_provider/hooks/datahub.py
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1682106348136369
> feat(airflow): respect port parameter if provided

- docs/glossary/business-glossary.md
In this PR I extend the Business Glossary docs to contain examples of each type of supported relationship.
> fix(docs): Adding relationship types section to Business Glossary docs

- datahub-web-react/src/app/shared/tags/TagProfileDrawer.tsx
The Tag Details button was sending users directly to a link with the `urn` in it - but that urn needs to be encoded. So let's use our handy entity registry method which handles this stuff for us.
> fix(ui) Fix Tag Details button to use url encoding

- docs/managed-datahub/metadata-ingestion-with-acryl/ingestion.md
Fixed some formatting in the docs https://datahubproject.io/docs/managed-datahub/metadata-ingestion-with-acryl/ingestion.
> docs: amend italic formatting

- metadata-ingestion/examples/bootstrap_data/business_glossary.yml
- metadata-ingestion/src/datahub/ingestion/source/confluent_schema_registry.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
- metadata-ingestion/tests/integration/business-glossary/glossary_events_auto_id_golden.json
- metadata-ingestion/tests/integration/business-glossary/glossary_events_golden.json
- metadata-ingestion/tests/integration/remote/golden/remote_glossary_golden.json
- metadata-ingestion/tests/unit/test_kafka_source.py
- Add status aspects
- Avoid global variables
- Materialize urns up front
> refactor(ingest/biz-glossary): simplify business glossary source

- datahub-web-react/src/app/entity/EntityRegistry.tsx
- datahub-web-react/src/app/entity/shared/utils.ts
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- datahub-web-react/src/app/lineage/__tests__/LineageTree.test.tsx
- datahub-web-react/src/app/lineage/__tests__/adjustVXTreeLayout.test.tsx
- datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
- datahub-web-react/src/app/lineage/types.ts
- datahub-web-react/src/app/lineage/utils/constructTree.ts
- datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
We had an issue where we sometimes were not displaying column level lineage properly for nodes that have siblings. This was happening because we had one "main" node that we display and if that node didn't have CLL, then we wouldn't show it. But one of its siblings may have CLL and we should be showing that if so.
This fixes that by creating a mapping of urns to inputs so we can create this `fineGrainedMap` (that's used to draw the lines between columns) and we check through each entity's siblings against this new mapping and update this `fineGrainedMap` to account for siblings and show CLL on the "visible" sibling node.
This ultimately this combines CLL between siblings and shows it as if it were one node.
> fix(ui) Fix displaying column level lineage for sibling nodes

- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/embed/EmbeddedPage.tsx
- datahub-web-react/src/app/entity/shared/embed/EmbeddedHeader.tsx
- metadata-io/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
Adds two new tracking events for our chrome extension experience. The first `ChromeExtensionProfileViewEvent` happens when they open the drawer to see a profile page with the chrome extension. The second `ChromeExtensionViewInDataHubEvent` is called when they click "view in datahub" from the chrome extension drawer.
> feat(tracking) Add tracking events to our chrome extension page

- metadata-models/src/main/pegasus/com/linkedin/common/ExternalReference.pdl
In this PR we add the https://github.com/searchable annotation to the externalUrl field shared across entities! This enables us to find unique assets based on their unique URL, for use within the Chrome extension :)
Tested using this search input
```
{
"input": {"types": ["DATASET"], "query": "*", "start": 0, "count": 10, "orFilters": [ { "and": [ { "field": "externalUrl", "values": ["https://www.google.com/"] } ] } ] }
}
```
> feat(models): Make assets searchable by their external URLs

- metadata-ingestion/docs/sources/salesforce/salesforce_pre.md
- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
Enable authorisation to Salesforce with JSON web tokens, by a direct passthrough to the Simple Salesforce authorisation.
> fix(ingest/salesforce): support JSON web token auth

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
We have found that sometimes LineageRunner parser throws exceptions when dealing with some queries. 
We are handling the exception same way as we do for example here https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/metabase.py#L462-L491
> fix(ingest/tableau): Add a try catch to LineageRunner parser

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.consumers-without-neo4j.yml
- docker/docker-compose.consumers.dev.yml
- docker/docker-compose.consumers.yml
- docker/docker-compose.dev.yml
- docker/docker-compose.kafka-setup.yml
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- docker/monitoring/docker-compose.monitoring.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.consumers-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.consumers.quickstart.yml
- docker/quickstart/docker-compose.kafka-setup.quickstart.yml
- docker/quickstart/docker-compose.monitoring.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- docker/quickstart/generate_docker_quickstart.py
Several unstable behaviours of the startup through `docker compose` were noticed ; often requiring to `down` and `up` again, after a first unsuccesful `up`, whether it was just after containers' creation or restart of Docker / host machine.
This PR brings several improvements in corresponding `docker-compose*.yml` files (esp. `/quickstart` ones but then more extensively, trying to be consistent as much as possible), especially by:
- using more services' [`healthcheck` definitions](https://docs.docker.com/compose/compose-file/05-services/#healthcheck) (in `/quickstart` ones, only `elasticsearch` had one)
- making dependency of `service-A` on `service-B` more robust by relying on those `healthcheck`･s, thanks to [the `depends_on`'s _long …
> fix(docker-compose): make startup more robust with deterministic services' dependencies

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/usage.py
Introduces https://github.com/databricks/databricks-sdk-py, which seems like a more developed library for the databricks API. Using it should provide better error logging around the usage query.
> refactor(ingest/unity): Use databricks-sdk over databricks-cli for usage query

- datahub-web-react/package.json
- datahub-web-react/src/App.tsx
- datahub-web-react/src/app/entity/dataset/profile/stats/stats/DatasetStatsSummarySubHeader.tsx
- datahub-web-react/src/app/entity/group/GroupMembers.tsx
- datahub-web-react/src/app/entity/group/GroupMembersSideBarSection.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityName.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Container/ContainerSelectModal.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/EditOwnersModal.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Platform/SelectPlatformModal.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/ColumnStats.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionDetails.tsx
- datahub-web-react/src/app/home/HomePageRecommendations.tsx
- datahub-web-react/src/app/ingest/secret/SecretsList.tsx
- datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
- datahub-web-react/src/app/permissions/policy/PolicyBuilderModal.tsx
- datahub-web-react/src/app/permissions/policy/PolicyDetailsModal.tsx
- datahub-web-react/src/app/recommendations/renderer/component/TagSearchList.tsx
- datahub-web-react/src/app/search/autoComplete/ParentContainers.tsx
- datahub-web-react/src/app/search/autoComplete/quickFilters/QuickFilter.tsx
- datahub-web-react/src/app/shared/EntityHead.tsx
- datahub-web-react/src/utils/test-utils/TestPageContainer.tsx
- datahub-web-react/yarn.lock
Had some free time and thought I could clean up some of our js console / eslint warnings, make it a bit cleaner. A minimal amount of refactoring. To keep the PR small I'm only tackling one of the dropdowns.
Before
After
> chore: cleanup some devtool console warnings

- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/SearchBar.tsx
- datahub-web-react/src/app/search/SearchablePage.tsx
- datahub-web-react/src/app/search/ViewAllSearchItem.tsx
Adds support for searching via a quick filter without entering any text in the autocomplete. Handles both home page and search results page autocompletes. Also adds a little "return key" component to the right per the figma designs.
With just quick filter
With data
> feat(search): support only searching by quick filter

- metadata-io/src/main/java/com/linkedin/metadata/config/search/CustomConfiguration.java
- metadata-io/src/test/java/com/linkedin/metadata/ESSampleDataFixture.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/CustomizedQueryHandlerTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilderTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java
- metadata-service/factories/src/main/resources/application.yml
> fix(search): fix custom search config parsing

- metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardInfo.pdl
Adding @Searchable for chart and dashboard URL. This enables us to find dashboards and charts by their external URL.
> feat(models): Adding searchable for chart and dashboard url

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_basic.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_keyval.json
If sampling is on get the the latest folder instead of the first one.
Walking the directories in a way entering the alphabetically last folder when getting file to infer schema. 
This way hopefully we will get the latest schema.
> feat(ingest/s3): Inferring schema from the alphabetically last folder

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/tableau.ts
Fix incorrect mapping found for token_name, token_value fields which are provided instead of username / password.
> fix(ui ingest): Fix mapping for token_name, token_value form fields for Tableau

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/SettingsBuilder.java
We were not able to do the types of queries on the new `browsePathV2` field in elastic search that we expected due to some unexpected defaults from elasticsearch itself. This updates mappings so that we have a path_hierarchy tokenizer using our desired delimiter (instead of forward slash which is default for elastic) on our `BROWSE_PATH_V2_HIERARCHY_ANALYZER`.
> fix(es) Fix browseV2 index mappings

- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/SearchablePage.tsx
This did end up being as simple as removing the checks (oops). I figured out what I was hung up on earlier. There's another unrelated bug where the selectedQuickFilter is not persisted from home->results and is also cleared out after toggling quick filters on the results page and searching. I'll file another bug for that but this should provide an improvement without breaking other functionality.
> fix(search): enter key with no query should search all

- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
This restores backwards compatibility w/ old versions
Tableau connector compatibility  for versions <2022.x and >2021.1.10 has broken due to this [PR](https://github.com/datahub-project/datahub/pull/7561)
This PR attempts to fix that.
> fix(ingest/tableau): don't use unsupported sql condition field

- .github/workflows/qodana-scan.yml
We're currently using 74GB of our allowed 10 GB - https://github.com/datahub-project/datahub/actions/caches
> ci: prevent qodana from using all of our cache

- metadata-ingestion/tests/integration/clickhouse/clickhouse_to_file.yml
- metadata-ingestion/tests/integration/clickhouse/docker-compose.yml
Avoid "port in use" failures like this one https://github.com/datahub-project/datahub/actions/runs/4955237788/jobs/8864458075
> ci(ingest/clickhouse): don't use kernel ephemeral ports

- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityName.tsx
A very recent merge updated CSS on entity names that makes displaying deprecation, failing tests, failing assertions, etc (whatever is next to the name) look bad.
This reverts that change that was made so things look good again.
Before:
After:
> fix(ui) Fix entity name styling to show deprecation and others properly

- metadata-ingestion/.gitignore
- metadata-ingestion/tests/unit/cli/test_quickstart_version_mapping.py
Our gradle tests were previously not running the tests/cli directory so we were just missing these tests entirely.
> test(sdk): move cli tests into the unit dir

- datahub-web-react/src/app/entity/group/GroupAssets.tsx
- datahub-web-react/src/app/entity/user/UserAssets.tsx
Ownership is something that will regularly be updated through the UI, we should have those changes be reflected immediately.
> feat(caching): skip cache on ownership tabs

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
Main issue is https://github.com/datahub-project/datahub/issues/8049, which this fixes by yielding full paths in the `get_folders` method rather than piecing together paths.
Also does some refactoring to clean things up and fetch credentials / create clients less, pass fewer params, etc.
> fix(ingest/delta-lake): Walk through directory structure with full path; reduce resource creation

- docker/datahub-upgrade/datahub-upgrade.sh
Currently shell script fetches newest image. When using `SystemUpdate` and target system is lower level, the indexes are fixed due to newest version and this causes problems.
> feat: datahub-upgrade.sh to support old versions

- metadata-ingestion/setup.py
> fix(ingest/build): setting typing extension <4.6.0 because it breaks tests

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/UpgradeStep.java
This sleep got moved into this abstract class during a refactor when it was only ever intended to execute once per start up, it instead executes with every upgrade step. With other robustness improvements around the start up process this shouldn't be needed.
> fix(upgrade): removes sleep from bootstrap process

- datahub-web-react/src/app/entity/dataset/profile/__tests__/SchemaDescriptionField.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entity/mlFeatureTable/profile/features/TableOfMlFeatures.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useDescriptionRenderer.tsx
fix: SchemaDescriptionField 'read-more' doesn't affect table height
`SchemaDescriptionField` is a component used to display descriptions in
`SchemaTable` via `useDescriptionRenderer`.
When `SchemaDescriptionField` expands, `SchemaTable` (antd `Table`)
doesn't know to adjust for the change in height.  This is relevant
when the table starts out shorter than the expanded row, e.g. a table
with only a couple rows, where one of those rows has a long description.
With the expansion state only in SchemaDescriptionField, a change in state
doesn't result in a re-render of the table.
The solution I've come up with is to make `SchemaDescriptionField` a
controlled component wrt expansion, with the state living in
`useDescriptionRenderer`.
`SchemaDescriptionField` is also used by `TableOfMlFeatures` …
> fix(ui): SchemaDescriptionField 'read-more' doesn't affect table height

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
- datahub-graphql-core/src/main/resources/app.graphql
- datahub-web-react/src/app/entity/user/UserEditProfileModal.tsx
- datahub-web-react/src/appConfigContext.tsx
- datahub-web-react/src/graphql/app.graphql
- metadata-service/factories/src/main/resources/application.yml
This PR adds a new feature flag plus the routing to pass feature flags back to the frontend through the AppConfig so get a boolean for `readOnlyModeEnabled`. Right now this flag only disables editing a profile image URL but can be extended to anything else that should be read only on the frontend if this flag is on.
When the flag is on we also render a tooltip saying that editing this field has been disabled. check out the tooltip when this is on (not on by default):
> feat(ui) Add readOnly flag that disables profile URL editing

- metadata-ingestion/src/datahub/ingestion/api/common.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
- metadata-ingestion/src/datahub/ingestion/source/state/entity_removal_state.py
- metadata-ingestion/src/datahub/ingestion/source/state/profiling_state_handler.py
- metadata-ingestion/src/datahub/ingestion/source/state/redundant_run_skip_handler.py
- metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
- metadata-ingestion/tests/integration/azure_ad/test_azure_ad.py
- metadata-ingestion/tests/integration/iceberg/test_iceberg.py
- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
- metadata-ingestion/tests/integration/kafka/test_kafka_state.py
- metadata-ingestion/tests/integration/ldap/test_ldap_stateful.py
- metadata-ingestion/tests/integration/looker/test_looker.py
- metadata-ingestion/tests/integration/lookml/test_lookml.py
- metadata-ingestion/tests/integration/okta/test_okta.py
- metadata-ingestion/tests/integration/powerbi/test_stateful_ingestion.py
- metadata-ingestion/tests/integration/superset/test_superset.py
- metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
- metadata-ingestion/tests/test_helpers/state_helpers.py
- metadata-ingestion/tests/unit/stateful_ingestion/state/test_stale_entity_removal_handler.py
- metadata-ingestion/tests/unit/test_glue_source.py
- smoke-test/tests/test_stateful_ingestion.py
The main goal here is to decouple the source from the stateful ingestion provider logic. This also fully replaces `StaleEntityCheckpointStateBase` with `GenericCheckpointState` and adds a helper method to our stateful ingestion tests.
> refactor(ingest): simplify stateful ingestion provider interface

- datahub-web-react/src/app/entity/domain/DomainEntity.tsx
- smoke-test/tests/cypress/cypress/e2e/domains/domains.js
It's been requested to show the documentation page for Domains first and foremost. This does that.
> feat(ui) Show documentation on Domain pages first

- README.md
This pull request adds PITS Global Data Recovery Services to the adopters list in README.md file's adopters section.
> docs(readme): adds PITS Global Data Recovery Services to the adopters list

- datahub-web-react/src/app/shared/share/items/EmailMenuItem.tsx
Description: 
Some Apple/Chrome users have Chrome set to handle `mailto` links by opening them in a specific webmail client (e.g. gmail). In this situation, when DataHub's "email" link is clicked, the current DataHub page is replaced with a gmail-compose page, which then disappears once the message is sent.
The fix here is adding `target="_blank"` to the anchor tag. I tried out this change and verified that behavior is what we'd want for both situations:
1. When Chrome is set to handle `mailto` links, they open in a new tab
2. When that's not the case, an external client is opened as usual, without opening an extra tab
Other browsers:
- Safari has this capability but only with installing an extension. I did not test this.
- [Firefox ignores `target="_blank"` for `mailto` …
> fix(ui): Open mailto link in new tab

- docker/datahub-ingestion-base/base-requirements.txt
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
This Pull Request makes extracting Lineage from Google Data Catalog API possible. https://github.com/datahub-project/datahub/pull/7137 first introduced this feature, but there were some limitations on the API at the time, making the API not return Lineage metadata for Views. However, now it's possible to retrieve this information, and it's much faster than parsing all Views SQL.
> feat(ingest/bigquery): Add BigQuery Views lineage extraction from Google Data Catalog API

- metadata-ingestion/docs/sources/csv/csv-enricher_recipe.yml
- metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
The example we gave is hard to reference since it doesn't indicate the exact format. Users will be creating `.csv` files, so for simplicity I replace the table with an example csv file. Also adds an example recipe & rephrases the documentation for concise-ness.
> docs(csv-enricher): add example csv file & recipe

- datahub-web-react/src/app/entity/shared/tabs/Lineage/ColumnLineageSelect.tsx
We recently made a change to fetch schemas separately from the main dataset fetch (for performance reasons) so the schema info was no longer in `entityData`. This uses that nice hook that only fetches schemas when we need to and will render that in the dropdown now for CLL impact analysis. Things still work the same and are all good for charts/dashboards and inputFields.
> fix(ui) Fix selecting columns in Lineage tab for CLL

- build.gradle
- metadata-service/factories/build.gradle
https://github.com/hazelcast/hazelcast/issues/23565
> chore(json): fix json vulnerability

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/EntityCountsResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/SiblingGraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/shared/ValidationUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/sibling/SiblingGraphServiceTest.java
The pill counts do not match the number of entities shown in the table. This is because in both cases, we filter out non-existent and duplicate entities between siblings. However, in the sibling case, when duplicates are removed, they were double counted in the total, but not added to the filtered count. The pill calculates the number to show as the total minus the filtered. Thus, the pill was overcounting the number of results. 
Update the logic to add the number of filtered entities to the result, so that the count is displayed correctly on the UI
> fix(lineagecounts) Include entities that are filtered out due to sibling logic in the filtered count of lineage counts

- datahub-web-react/src/app/entity/dataset/profile/stats/stats/DatasetStatsSummarySubHeader.tsx
- datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/StatsTab.tsx
Show statsSummary query count consistently and fallback to usageStats if it was missing.
> fix(stats): display consistent query count on stats tab

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
Removes two methods that we never overridden and were no-ops.
Also fixes the docs for mongodb.
> fix(ingest): remove `original_table_name` logic in sql source

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
> feat(ingest/snowflake): support for more operation types

- datahub-web-react/src/app/entity/domain/DomainEntity.tsx
Revert a recent change to show Entities instead of documentation tab first on Domain pages again.
> fix(ui) Show Entities first on Domain pages again

- metadata-ingestion/src/datahub/ingestion/source/nifi.py
- metadata-ingestion/tests/unit/test_nifi_source.py
The connector earlier assumed the nifi is hosted at root level. e.g. `https://domain-name/nifi/`
However for hosted nifi solutions this may not be the case. This PR adds support to nifi with context. e,g. `https://domain-name/context-path/nifi`
Also includes some refractors to use pydantic validators.
> fix(ingest/nifi): allow nifi site url with context path

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
Optimized lineage seems stable enough to make default.
Also optimizes query history joins, limiting to specified time range, based on John's work for observability.
> feat(ingest/snowflake): Deprecate legacy lineage and optimize query history joins

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/glossary/datahub_classifier.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake_legacy_lineage.py
- metadata-ingestion/tests/unit/test_classification.py
> feat(classification): support for regex based custom infotypes

- metadata-ingestion/scripts/modeldocgen.py
- metadata-ingestion/setup.py
- metadata-ingestion/tests/integration/feast/feature_store/feature_store.yaml
Bumped feast so that I could generate docs locally on M2 machine
> fix(ingest): Fix modeldocgen; bump feast to relax pyarrow constraint

- docs/lineage/lineage-feature-guide.md
> docs(lineage): document timestamp filtering in lineage feature

- metadata-ingestion/src/datahub/ingestion/source/kafka.py
> fix(ingest/kafka): Better error handling around topic and topic description extraction

- build.gradle
- datahub-frontend/app/controllers/AuthenticationController.java
- datahub-frontend/app/security/AuthenticationManager.java
- datahub-frontend/conf/application.conf
- datahub-upgrade/build.gradle
- metadata-service/factories/build.gradle
- metadata-service/graphql-servlet-impl/build.gradle
- metadata-service/war/build.gradle
> fix(vulnerabilities)/vulnerabilities_fixes_datahub (#8075)

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
Since we emit a log when ingestion stage is changed, discussing how long the previous stage took, this was producing confusion results where we'd say "process project y" and then "time spent in stage <project x>: ..."
> fix(ingest/bigquery): Swap log order to avoid confusion

- metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/ConfigurationProvider.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/HealthCheckConfiguration.java
- metadata-service/factories/src/main/resources/application.yml
- metadata-service/health-servlet/src/main/java/com/datahub/health/controller/HealthCheckController.java
So far, only checks ElasticSearch client, the first one we implemented
Example response on quickstart for URL: http://localhost:8080/health/check/combined
200 response with body
```
{"elastic":{"headers":{},"body":"{\"cluster_name\":\"docker-cluster\",\"status\":\"yellow\",\"timed_out\":false,\"number_of_nodes\":1,\"number_of_data_nodes\":1,\"active_primary_shards\":65,\"active_shards\":65,\"relocating_shards\":0,\"initializing_shards\":0,\"unassigned_shards\":62,\"delayed_unassigned_shards\":0,\"number_of_pending_tasks\":0,\"number_of_in_flight_fetch\":0,\"task_max_waiting_in_queue_millis\":0,\"active_shards_percent_as_number\":51.181102362204726}","statusCodeValue":200,"statusCode":"OK"}}
```
> Add combined health check endpoint which can check multiple components

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/CreateDomainResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryNodeResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryTermResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddOwnerResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/OwnerUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/tag/CreateTagResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/OwnerMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/OwnerUpdateMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/tag/mappers/TagUpdateInputMapper.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/owner/AddOwnersResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/owner/BatchAddOwnersResolverTest.java
> fix(ownership): Corrects graphQL resolver for entity operations

- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- metadata-ingestion/src/datahub/cli/docker_cli.py
- Handle retries when docker compose up hangs.
- Tweaks our healthchecks so that the startup grace periods are longer.
The changes in docker/quickstart are autogenerated from the ones in the docker/ dir.
> fix(cli/quickstart): handle docker hangs gracefully

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
Cherry-pick of 743439c11df8fbcbd7ec6a08b57dcdcb69e2e07e
> feat(ingest/bigquery_v2): enable platform instance using project id

- datahub-web-react/src/app/entity/chart/shared/ChartStatsSummary.tsx
- datahub-web-react/src/app/entity/dashboard/shared/DashboardStatsSummary.tsx
- datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
- datahub-web-react/src/app/entity/dataset/shared/ExpandingStat.tsx
- datahub-web-react/src/app/entity/shared/components/styled/StatsSummary.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Dataset/StatsSidebarSection.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/TableStats.tsx
- datahub-web-react/src/app/search/autoComplete/AutoCompleteItem.tsx
- datahub-web-react/src/app/search/autoComplete/AutoCompleteTooltipContent.tsx
- datahub-web-react/src/utils/formatter/index.ts
Formats the numeric display for the row count (10K, 10M, etc) like other numbers around Datahub. At some point we will want to consolidate `src/utils/formatter/index.ts` and `src/app/shared/formatNumber.ts`. They're similar but not quite, one uses the `Intl.NumberFormat` which may be a more flexible approach.
To still provide a way for users to get to the true number values in the UI, you can still hover the row/cols and they'll expand. A tooltip was another approach that felt a little too busy on the UI and covers up the dataset name. This feels a little more out of the way and inline with the rest of the content. I didn't refactor all the fields to use this new approach right away because that would take quite a bit more time and we'll want to see how people feel about this new approach …
> feat(stats): make rowcount more human readable

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
> fix(ingest): Call validator on the base urn as well as aspect components when ingesting

- docs-website/src/components/MarkpromptHelp/markprompthelp.module.scss
> docs(website): adjust markprompt z-index so it's not covered by nav

- smoke-test/tests/consistency_utils.py
In https://github.com/datahub-project/datahub/pull/8094 an assumption was made that these tests will only be running in docker environments. In the case where that is not the case adding back static sleep as an option until those specific cases can be supported.
> chore(ci): add back optional static sleep for tests

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/DeleteAssertionResolver.java
We are not seeing logs in some cases where we expected to see them when deleting assertions. It could be because we're not catching all kinds of exceptions in the async future.
> chore(assertions): catch any exception on assertion delete

- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
According to the ES documentation, this is a best practice as it results in fewer small files: https://www.elastic.co/guide/en/elasticsearch/reference/7.14/index-rollover.html
> feat(opensearch): Rollover usage events at a file size rather than time-based manner

- datahub-web-react/src/app/search/filters/utils.tsx
- datahub-web-react/src/app/search/sidebar/EntityNode.tsx
- datahub-web-react/src/app/search/sidebar/EnvironmentNode.tsx
- datahub-web-react/src/app/search/sidebar/PlatformNode.tsx
- datahub-web-react/src/app/search/sidebar/useAggregationsQuery.ts
Changes
* Sort aggregations by display name on the frontend
* Align counts vertically
> fix aggregation sorting in browsev2 sidebar

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/DeleteDomainResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/DeleteGlossaryEntityResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/RemoveGroupResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/tag/DeleteTagResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/user/RemoveUserResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/service/DataProductService.java
- metadata-io/src/test/java/com/linkedin/metadata/client/JavaEntityClientTest.java
Since we suspect failing calls to deleteReferencesTo (there may be other places) this PR adds retry logic. Normally, retries would not be the best thing to do here, but since we don't have a great way to rollback resolvers on failure at the moment this may help reduce the frequency of data inconsistencies. Also address other places we may not be catching all exceptions in runAsync so we get better logging.
Could use some pointers on testing / appropriate way to structure this.
> Add retries to JavaEntityClient:deleteReferencesTo

- docs/posts.md
added graphql examples for creating, listing and deleting posts.
> docs(posts): add examples

- datahub-web-react/src/app/context/userContext.tsx
- datahub-web-react/src/app/search/SearchResults.tsx
- datahub-web-react/src/app/search/ToggleSidebarButton.tsx
- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
- datahub-web-react/src/app/search/useToggleSidebar.ts
- datahub-web-react/src/app/shared/useToggle.ts
- smoke-test/tests/cypress/cypress/e2e/browse/browseV2.js
The sidebar now remembers whether you had previously opened or closed it. Per device via localStorage. Tooltip is now added on the toggle button.
> Sidebar local storage setting + toggle tooltip

- datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
- datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
- datahub-web-react/src/app/lineage/utils/highlightColumnLineage.ts
If you have columns on a dataset that you set as self-referencing with column level lineage, we try to draw an arrow from the column to itself, but it looks off in the UI. A safer bet is to simply not try and draw that edge in the first place. Also, this self referencing would cause a call-stack issue with a recursive function we have, so this PR protects against that in case we somehow start showing self-referencing CLL again.
> fix(ui) Fix UI issues with self-referencing column level lineage

- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/ChartAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DashboardAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DataFlowAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DataJobAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DatasetAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/MLFeatureAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/MLFeatureTableAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/MLModelAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/MLModelGroupAspect.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
We were seeing error logs in GMS when ingesting data that included browsePathsV2 when we tried to produce MAE events. This is because browse pathsV2 are not in any entity snapshots. In order to reduce noise, this PR simply adds that aspect to relevant entity snapshots.
Ingestion would still successfully run anyways as this is a legacy thing, but we want to prevent unnecessary noise for now.
> fix(ingestion) Fixes producing MAE events with browsePathsV2 aspect

- datahub-web-react/src/app/entity/chart/ChartEntity.tsx
- datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
It takes some FE work to enable previews for any source. Recently, preview links for tableau were added on the source side but they did not work on the UI due to auth/XSS/etc.
Adding a safeguard here to only show previews in looker for the time being.
> fix(embed): hide chart & dashboard previews if not for looker

- datahub-web-react/src/app/search/SearchPage.tsx
Optionally show the 2 new onboarding steps for new search and new browse experiences if their respective flags are enabled.
> fix(ui) Only show search and browse V2 onboarding steps if flag is on

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
Getting errors here, just looks like a typo to me
> fix(ingest/looker): Fix typo on ViewField creation for measures

- metadata-io/src/main/java/com/linkedin/metadata/search/cache/CachingAllEntitiesSearchAggregator.java
Our `aggregateAcrossEntities` endpoint uses our search under the hood and passes in a list of `facets` that we want to fetch. There were cache collisions between our normal search and `aggregateAcrossEntities` where we would get the same results unexpectedly between them. This is because `facets` weren't being added to our cache key. This PR does that.
> fix(search) Add facets list to our cache key to avoid cache collisions

- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/context/userContext.tsx
- datahub-web-react/src/app/search/ToggleSidebarButton.tsx
- datahub-web-react/src/app/search/sidebar/BrowseNode.tsx
- datahub-web-react/src/app/search/sidebar/ContainerLink.tsx
- datahub-web-react/src/app/search/sidebar/EntityLink.tsx
- datahub-web-react/src/app/search/sidebar/EntityNode.tsx
- datahub-web-react/src/app/search/sidebar/ExpandableNode.tsx
- datahub-web-react/src/app/search/sidebar/PlatformNode.tsx
- datahub-web-react/src/app/search/sidebar/SidebarLoadingError.tsx
- datahub-web-react/src/app/search/sidebar/useSidebarAnalytics.ts
- metadata-io/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
Changes
* Adds a container link to the browse v2 sidebar
* Analytics when clicking the container link
* Delay the sidebar tooltips by 2s
* Removes flex gap and replaces with padding because some button components inherently are padding their contained icons so it was doubling their padding with the extra gap.
* Shrink the ellipsis maxWidth when we're dealing with a container, would be really nice to use a dynamic width ellipsis here but it doesn't work and I've wrestled it a few times with no success.
* Fixes a UI glitch in the error component when we're more nested.
> Container link in browse v2 sidebar

- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/query/ESAggregatedStatsDAO.java
* Set count to 0 so results are not returned (just aggregations)
* Apply the filter on the query and not the aggregations as the query results can be filtered before aggregations are applied, purportedly more efficient
Tested using unit tests (`ElasticSearchTimeseriesAspectTest.java` has pretty comprehensive unit tests for this) as well as ensuring the output for the test query here https://datahubproject.io/docs/metadata-modeling/metadata-model/ against quickstart was identical before and after the change
```
curl --location --request POST 'http://localhost:8080/analytics?action=getTimeseriesStats' \
--header 'X-RestLi-Protocol-Version: 2.0.0' \
--header 'Content-Type: application/json' \
--data-raw '{
"entityName": "dataset",
"aspectName": "datasetUsageStatistics",
"filter": { …
```
> feat(usagestats): Optimize elasticsearch query for usage stats aggregations

- metadata-ingestion/tests/integration/trino/test_trino.py
There's basically a 0% chance https://github.com/datahub-project/datahub/pull/8339 passes so in the meantime...
> test(ingest/trino): xfail test to unblock CI

- docs/act-on-metadata/impact-analysis.md
- docs/api/tutorials/lineage.md
- metadata-ingestion/examples/library/read_lineage_rest.py
This adds an example for read lineage to the docs. Here's a preview:
github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
> docs(lineage): add read lineage example

- metadata-ingestion/tests/integration/s3/test_s3.py
Making sure the order of the uploaded s3 files are always the same in test
> fix(ingest/s3): Fix for flaky s3 test - uploading s3 files in consistent order

- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
- datahub-web-react/src/app/search/sidebar/EntityNode.tsx
- datahub-web-react/src/app/search/sidebar/EnvironmentNode.tsx
- datahub-web-react/src/app/search/sidebar/useAggregationsQuery.ts
- datahub-web-react/src/app/search/sidebar/useSidebarEntities.ts
Changes
* Filters the entities further via a second query for possible entities in the instance
* If the base queried error'd for some reason, we fallback to the base filteredEntities
* Makes the aggregation queries retryable
> fix(browse): filter entities by whether they might exist in the instance

- metadata-ingestion/scripts/install_deps.sh
Caused by a new release of lxml.
> ci(docs): add missing deps for lxml package for vercel

- datahub-web-react/src/app/analyticsDashboard/components/TimeSeriesChart.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/historical/HistoricalStats.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/historical/charts/ProfilingRunsChart.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/historical/charts/StatChart.tsx
Changes
* New sizeInBytes chart
* Scale y values on stat charts at the min
After:
Before:
> feat(stats): show size in bytes and scale at y=min

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/BackfillBrowsePathsV2Step.java
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/BackfillBrowsePathsV2StepTest.java
If there's one bad urn in someone's instance or something unexpected when ingesting a singular browsePathsV2 aspect, we raise an error and the whole process terminates. This catches that error and logs it while allowing us to continue on with the other entities to backfill.
> fix(java) Add try catch block when backfilling browse v2

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLPlugin.java
This is an extremely small PR meant to create a pathway for extensions to the GraphQL engine to be managed without requiring code changes to the monolith. This should result in an easier merge experience for teams running DataHub forks. 
I intentionally didn't make larger scale changes to the core engine because I wanted existing forks to have the simplest merge experience.
> refactor(graphql): make graphql engine extensible

- metadata-ingestion/src/datahub_provider/_airflow_shims.py
- metadata-ingestion/tests/unit/test_airflow.py
Old date serialization broke new regex for run_id. Also swaps DummyOperator -> EmptyOperator as per deprecation message
> test(ingest/airflow): Fix test for airflow 2.6.3

- metadata-ingestion/src/datahub/testing/compare_metadata_json.py
- metadata-ingestion/src/datahub/testing/mcp_diff.py
For some reason, the custom operator doesn't seem to be working when running connector tests, resulting in the diffs printing `AspectForDiff` objects. I wasn't able to debug the custom operator, so I'm just adding the ignore path back to ignore the delta info object... It seemed to be working before, so I'd like to leave it in, e.g. if the error is due to a change by deepdiff -- it causes no harm.
I also add a custom repr method to AspectForDiff in case this happens again just to make the error messages a bit nicer, but we really shouldn't hit this.
> test(ingest/testing-utils): Add back delta info ignore path

- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
We used to have 70s of sleep here, trying to avoid that. If this doesn't work though maybe I'll just stick in a sleep.
> test(ingest/kafka-connect): Attempt to fix flaky test

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
- metadata-ingestion/tests/conftest.py
- metadata-ingestion/tests/unit/test_cli_logging.py
- metadata-ingestion/tests/unit/test_pipeline.py
- Only raise SystemExit if there's an error, not if the exit code was supposed to be 0. 
- Run Pipeline.create in the same thread as pipeline.run() to avoid weird threading issues.
cc @anshbansal - this will reduce the system exit exceptions that you see and hopefully makes the code a bit more clear.
> fix(ingest): tweak ingestion exit codes

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/feature_groups.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/models.py
> build(ingest/boto3): Update boto3-stubs to fix CI

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_legacy.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_schema.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
cc @mayurinehate just for visibility
Looking to remove legacy lineage in another PR
Some questions / comments:
- I'd like to make the schema resolver take in a callable `dataset_urn_builder` like I do for the lineage and usage extractors, rather than taking in platform and env and calling the mce_builder method itself. It likely won't make a difference but I like having one function so we can be sure all dataset urns are generated in the same way, since we do that in a lot of places
- I added a close method to the schema resolver and call it in the snowflake source's close method. However, the bigquery source notes that doesn't get called if ingestion is not successful and thus has its own cleanup method. Can we unify this, ideally around the source's close method?
- We mention how we …
> feat(ingest/snowflake): View CLL from sql parsing of view definition

- docker/kafka-setup/Dockerfile
- docker/quickstart/generate_and_compare.sh
- docker/quickstart/requirements.txt
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion/setup.py
See https://github.com/yaml/pyyaml/issues/601.
- use wheels for quickstart-compose-validation
- pin cython in kafka-setup
- fix airflow builds
> ci: workarounds for pyyaml installation

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
Referring table variable in the view for loop gets the below error
```packages/datahub/ingestion/source/redshift/redshift.py", line 818, in cache_tables_and_views
f"View {database}.{schema}.{table.name} is filtered by view_pattern"
UnboundLocalError: local variable 'table' referenced before assignment
> fix(ingestion-redshift): Fix Redshift ingestion logs

- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
These were confusing folks more than they helped, so hiding them from the public docs to make them "advanced-only" features.
> chore(ingest): hide ignore old/new state options

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
Also improves some warning messages.
> feat(ingest/lookml): fail when nothing was produced

- smoke-test/tests/cypress/cypress/e2e/query/query_tab.js
Fixed some duplicated steps
Added verifications for Query added/edited/removed notifications
Fixed a case when query tab was verified instead of query view
Main fix: This test been failing on CI with error "Timed out retrying after 10000ms: Expected to find content: '+ Test Query-1689481016643 + Edited Query-1689481016643' but never did."
This happened because cypress scrolled queries view and at some point this element become invisible for cypress while still present on UI and DOM.
Note: 'waitTextVisible' function always check for visibility of element(not only if it present in DOM)
To fix this I've used 'scrollIntoView' Cypress function for the Test query element.
https://linear.app/acryl-data/issue/OBS-46/qa-query-tab-smoke-test
> Fix query_tab test that was failing on CI run

- metadata-service/war/src/main/resources/boot/data_platforms.json
This was typo'd when the source was initially introduced. The source emits MCPs using presto-on-hive syntax, see for example:
https://github.com/datahub-project/datahub/blob/bec018257c8c7c9af7dc79d91e8db34414188ff0/metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_2.json#L491
> Update presto-on-hive URN in data_platforms.json

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/tests/integration/mysql/mysql_table_row_count_estimate_only.json
Quick follow up of https://github.com/datahub-project/datahub/pull/8420
`mysql` only has `database name` and `table name` unlike postgres so after splitting the dataset name we will have only 2 parts unlike 3 in case of `postgres`. Fixing that.
> fix(mysql): getting table name correctly

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/BrowsePathV2Utils.java
Noticed this for elasticsearch indices where names started with `.`
> fix(browsepathv2): default browse path with empty space

- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion/build.gradle
- Also fixes the pyyaml workaround.
> ci: fix commandLine usage in build.gradle

- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/source/state_provider/datahub_ingestion_checkpointing_provider.py
- metadata-ingestion/tests/unit/stateful_ingestion/test_configs.py
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1690491969370859
> fix(ingest): respect max_threads for ingestion reporter

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/test_usage_common.py
Avoids a vuln in sqlparse 0.4.3. See
https://datahubspace.slack.com/archives/C04DK4ADVL3/p1689951722620909?thread_ts=1689175860.274659&cid=C04DK4ADVL3 for details.
Follow up since https://github.com/datahub-project/datahub/pull/8098 was closed.
> chore(ingest): bump sqllineage and sqlparse

- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/SearchUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/LineageSearchServiceTest.java
Moved the logic to remove degree filter from slow cache to apply to both slow and fast caching.
> fix(search): fix lightning cache enable logic

- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
Parity with `search` in the same file.
Among other things, the flags turn off highlighting which can improve query performance for a lineage query such as this where highlighting is not needed.
> feat(lineage): Apply search flags to scroll query in LineageSearchService

- datahub-web-react/src/app/entity/shared/__tests__/siblingsUtils.test.ts
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/SidebarSiblingsSection.tsx
- datahub-web-react/src/app/entity/shared/siblingUtils.ts
- datahub-web-react/src/app/search/SearchResultList.tsx
- datahub-web-react/src/graphql/dataset.graphql
- datahub-web-react/src/graphql/search.graphql
We should treat ghost siblings same as ghost lineage edges- hide them! This is in anticipation of our snowflake-shares-as-siblings work which may introduce ghost sibling edges if shares are done to external accounts.
> feat(siblings): hiding non-existant siblings in FE

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilderTest.java
aggregateAcrossEntities endpoint should allow for arbitrary aggregation on any index fields that are valid. This PR enables that behavior, removing a filter that is used when custom facets are provided which requires that the facet is marked as "addToFilters" in the searchable annotation, which really should be used for providing the _default_ set of facets that are generated when none are explicitly requested.
> feat(search): Allow aggregating on facets that are not explicitly part of default filter set

- metadata-ingestion/docs/sources/metabase/metabase.md
- metadata-ingestion/docs/sources/metabase/metabase.yml
- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/tests/unit/test_metabase_source.py
Since DataHub supports [platform instances](https://datahubproject.io/docs/platform-instances/) there may be several distinct instances with the same platform in the same environment. When ingesting charts from Metabase it should be possible to find the corresponding datasets (tables) in DataHub.
For example, the dataset URN searched during ingestion is:
- *without* the patch: `urn:li:dataPlatform:clickhouse,event.new_app,PROD`
- *with* the patch: `urn:li:dataPlatform:clickhouse,clichouse_analytics_prod.event.new_app,PROD`
with only the latter URN being valid for dataset ingested with `platform_instance` specified.
The change still leaves `name_to_instance_map` optional and if `platform_instance` is not used, the mapping may be skipped.
Also the change adds a case for Metabase user not …
> feat(ingest): Add metabase database id to platform instance mapping

- smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js
- smoke-test/tests/cypress/cypress/support/commands.js
https://linear.app/acryl-data/issue/OBS-54/qa-create-cypress-tests-for-managing-groups
Test steps:
1. Create test user
2. Create a group
3. Add test user to a group
4. Edit group info
5. Test user verify group participation
6. Remove group
> Cypress test for managing groups

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
- metadata-ingestion/tests/integration/sql_server/source_files/mssql_with_lower_case_urn.yml
tableau table lineage to upstream was broken because of mssql connector ingestion. 
mssql connector was ingesting qualified table name (i.e <db-name>.<schema>.<table>) in same case as retrieved from database.
We have added a flag `convert_urns_to_lowercase` (default to false) to enable converting qualified table-name to lowercase.
> fix(ingetion/mssql): convert dataset urns to lowercase

- .github/actions/docker-custom-build-and-push/action.yml
This seems to shave off a few minutes per Docker build.
> feat(ci): use docker registry cache

- docs/how/updating-datahub.md
> docs(release): Update updating-datahub.md for 0.10.5 release

- docs/docker/development.md
(docs) Using Docker Images During Development: Minor grammatical error
https://datahubproject.io/docs/docker/development/
> docs(development.md): Minor grammatical error

- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/policy.json
The UI can display up to 1 year of history, so we should not delete events after 60 days.
> fix(usage): Update index lifecycle policy to not delete old datahub usage events

- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHealthPopover.tsx
Tiny change which ensures the entire popover, including the arrow, is a consistent color.
> fix(ui): Simplify background color for Entity Health Status popover

- .pre-commit-config.yaml
This will automatically modify the files that are out of format with prettier when running pre-commit.
> fix: add --write args on pre-commit prettier

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
- metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
- metadata-ingestion/src/datahub/ingestion/source/glue_profiling_config.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_common.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/profile.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/s3/config.py
- metadata-ingestion/src/datahub/ingestion/source/s3/datalake_profiler_config.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/connection_test.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/ingestion/source_config/operation_config.py
- metadata-ingestion/tests/unit/test_elasticsearch_source.py
This allows us to have a common interface that we can use across connectors. Currently it is only to allow for better control of ingestion profiling but we can use the same interface to control various aspects of ingestion.
This is required for profiling currently because it is a costly operation and organisations want to do profiling at a lower cadence. Day of week or date of month is simple enough to implement in python code that we do not have to do anything source config and we can easily allow this on all sources compared to doing source specific changes.
Doing it initially only for elasticsearch for review. Once the approach is reviewed will add this for all sources where profiling is present.
> feat(ingest): allow lower freq profiling based on date of month/day of week

- metadata-ingestion/src/datahub/configuration/common.py
> fix(ingest): handle redaction of configs with int keys

- datahub-web-react/src/app/entity/shared/containers/profile/utils.ts
- datahub-web-react/src/graphql/lineage.graphql
Following up on https://github.com/datahub-project/datahub/pull/8528, gives platform icons a similar UX to the other ways ghost siblings are hidden.
> feat(siblings): dont show multiple platform icons if the siblings are ghost nodes

- smoke-test/tests/cypress/cypress/e2e/mutations/dataset_ownership.js
- smoke-test/tests/cypress/cypress/support/commands.js
Dataset ownership test steps:
1. Create test group and test user(add user to a group)
2. Open dataset page add and remove user ownership(test every type)
3. Open dataset page add and remove group owner(test every type)
> Dataset ownership test

- metadata-ingestion/setup.py
Related to https://github.com/acryldata/PyHive/commit/c6085e067b77060731df0ddd179ba7aa9b6e4eb9 in service of https://github.com/datahub-project/datahub/pull/6485.
Also fixes https://github.com/datahub-project/datahub/issues/8405.
> fix(ingest): use hive pure_sasl variant

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/assertion/DeleteAssertionResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/deprecation/UpdateDeprecationResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/SetDomainResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/UnsetDomainResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/embed/UpdateEmbedResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/AddRelatedTermsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/RemoveRelatedTermsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/DescriptionUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/MutationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateNameResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateParentNodeResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/UpdateUserSettingResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/DeleteUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/DeprecationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/DomainUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/LabelUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/LinkUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/OwnerUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/tag/SetTagColorResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/aspect/utils/DeprecationUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityUtils.java
> refactor(graphql): extract code into metadata-io part 1

- metadata-io/build.gradle
- metadata-models/build.gradle
> fix(cleanup): cleanup of 2 sub-modules

- metadata-ingestion/src/datahub/ingestion/source/s3/config.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
> feat(ingest/s3): Adding option to pass in any spark config property to s3 source

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/emitter/aspect.py
- metadata-ingestion/src/datahub/emitter/mcp.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_kafka_reader.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_mysql_reader.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/report.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/state.py
- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
- metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
- metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
- metadata-ingestion/src/datahub/ingestion/source/state_provider/datahub_ingestion_checkpointing_provider.py
- metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
- metadata-ingestion/tests/unit/stateful_ingestion/state/test_checkpoint.py
- metadata-ingestion/tests/unit/test_sql_common.py
Some remaining questions on deserialization and workunit ids -- see TODOs. Also needs to be more thoroughly tested, have only run on my local machine to a file sink. Already got one error from that test:
```
'mysql_parse_errors': {'com.linkedin.pegasus2avro.common.CostCost is missing required field: fieldDiscriminator': {'cost': ['urn:li:mlModel:(urn:li:dataPlatform:science,scienceModel,PROD)']}},
```
which makes me think I should probably not try to deserialize into MCPWs
> feat(ingest): Add DataHub source

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
This PR addresses [bug #8636](https://github.com/datahub-project/datahub/issues/8636). Proper fix for it depends on intended behavior of the `okta` connector - if nesting event loops is desired behavior then `nest_asyncio` should be used.
For more considerations see:
https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python
Fixes #8636.
> fix(ingest/okta): fix event_loop RuntimeError with nested asyncio

- metadata-ingestion/src/datahub/ingestion/source/confluent_schema_registry.py
- metadata-ingestion/tests/unit/test_confluent_schema_registry.py
Fixes #8366.
`schema_ref`:`SchemaReference`, was treated like a dictionary.
After update, now schema references attributes are accessible by 
`SchemaReference` properties instead of dictionary subscription.
e.g. `schema_ref.name` ,  `schema_ref.version` , `schema_ref.subject`
> fix(ingest/kafka): use SchemaReference properties instead of dict access

- datahub-graphql-core/src/main/resources/search.graphql
Tiny PR for adding the exists operator to GraphQL API. This was confirmed to work locally, because we already support this in Condition.pdl on the Elasticsearch backend. 
Tested queries:
```
query searchAcrossEntities {
searchAcrossEntities(input:{
types: [MONITOR],
start: 0,
count: 20,
query: "*",
orFilters: [
{
and: [
{ field: "executorId", condition: EXISTS }
]
}
]
}) {
total
start
searchResults {
entity {
...on Monitor {
urn
}
}
}
}
```
> feat(graphql) Support exists operator in GraphQL Search API

- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
In this PR we use ternary instead of && to remove the possibility of getting 0's when the length of the health array is 0.
> [fix] [health ui] Removing ghost 0 for health signals on search cards

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
Without the .value, it would produce 'BucketDuration.DAY' instead of 'DAY'.
> fix(ingest/snowflake): fix usage enum bug

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
The old type-based ones will be deprecated on Sept 7.
> feat(ingest/dbt-cloud): use job-based graphql queries

- metadata-ingestion/docs/sources/kafka-connect/kafka-connect.md
- metadata-ingestion/docs/sources/kafka-connect/kafka-connect_recipe.yml
- metadata-ingestion/src/datahub/ingestion/extractor/json_schema_util.py
> docs(ingest/kafka-connect): add details on platform instance mapping

- datahub-web-react/src/app/entity/view/select/ViewSelect.tsx
- datahub-web-react/src/app/entity/view/select/ViewSelectHeader.tsx
- datahub-web-react/src/app/search/SearchBar.tsx
> Fix a few view select issues

- .github/workflows/docker-unified.yml
Follow up on https://github.com/datahub-project/datahub/pull/8677.
> ci: add `needs_artifact_download` output for ingestion image

- metadata-ingestion/setup.py
Follow up on https://github.com/datahub-project/datahub/pull/8592.
> fix(ingest/powerbi): add sqlglot python dep

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
The data platform instance results in redundancy in the UI browse path for bigquery entities, which is confusing some users. We keep the option to create the DPI aspect for users who want it
> fix(ingest/bigquery): Add config option to create DataPlatformInstance, default off

- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/tests/integration/metabase/metabase_mces_golden.json
- metadata-ingestion/tests/integration/metabase/setup/card.json
- metadata-ingestion/tests/integration/metabase/setup/card_3.json
- metadata-ingestion/tests/integration/metabase/test_metabase.py
Metabase question (datahub Card) may not query database table directly but rather use another question as source. The change makes ingestion to attempt finding the source database table from source question in recursive manner.
Example API response for questions getting data from other question results:
```
{
. . .
"dataset_query": {
"database": 42,
"query": {
"source-table": "card__31337",
"filter": [
. . .
],
"aggregation": [
. . .
],
"breakout": [
. . .
]
},
"type": "query"
},
"id": 123
. . .
}
```
The proposed patch is trying to resolve source database and tables recursively from Metabase question specified as data source for target question. Recursion depth is statically limited.
Retrieving question (Card) information by its ID from Metabase API has been moved to method to ease …
> feat(ingest/metabase): detect source table for cards sourced from other cards

- metadata-service/configuration/src/main/resources/application.yml
We want to turn this on for the next release!
> feat(config): Turn on new search & browse experience by default

- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHealth.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHealthPopover.tsx
- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/constants.ts
- datahub-web-react/src/app/lineage/types.ts
- datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
- datahub-web-react/src/app/lineage/utils/constructTree.ts
- datahub-web-react/src/app/shared/health/healthUtils.tsx
- datahub-web-react/src/graphql/lineage.graphql
In this PR, we add the Entity Health Status to the Lineage Graph View.
Note that we are not yet supporting Siblings. That will come in a followup PR. 
> feat(health): Adding Entity Health Status to the Lineage Graph View 

- metadata-ingestion/docs/sources/datahub/README.md
- metadata-ingestion/docs/sources/datahub/datahub_pre.md
- metadata-ingestion/docs/sources/datahub/datahub_recipe.yml
- metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_database_reader.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_kafka_reader.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/report.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/state.py
- metadata-ingestion/src/datahub/testing/compare_metadata_json.py
- metadata-ingestion/tests/unit/stateful_ingestion/state/test_checkpoint.py
Makes the following changes:
- Add CASE on version = 0 for improved ordering. Note this only matters when comparing aspects with the same exact `createdon` for the same urn and aspect. In general, we rely on `created` to impart the correct ordering, not version
- Do not overwrite lastObserved time in system metadata
- Allow `database_connection` and `kafka_connection` to be None, if you only want to ingest from one of them
- Rename mysql -> database
- Store `stop_time` in report
- Report workunits
Still need to test with postgres and in general, I'd like to set up an integration test to make development of this source safer
> feat(ingest/datahub): Improvements, bug fixes, and docs

- metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
After previous change [#8637](https://github.com/datahub-project/datahub/pull/8637) okta connector could start but not finish properly, since line closing the event loop caused exception shown below. I am a little bit confused as to why it started failing now as before we run it with `0.9.6.1` version released in January 2023 and everything was fine - even though `event_loop` code was present both in `ingestor_cli.py` and `okta` ingestor. My conclusion is that this change done a month ago might have caused the issue to appear:
https://github.com/datahub-project/datahub/commit/4fb77e4a25890c84b165a1b21265c0d9dee33be5#diff-97f18760199a7ea8722507b31d24f6520b4c1bbf9145d3b3ad24748ecfa831adR125
(making the function `async`)
What I wonder though is that why nobody else seemed to experience the …
> fix(ingest/okta): Removed code closing okta's event_loop

- datahub-web-react/public/robots.txt
Needed to make demo.datahubproject.io have fewer errors during Google indexing.
> fix(ui): hide pages from web crawlers

- docs/how/delete-metadata.md
- metadata-ingestion/src/datahub/cli/delete_cli.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
Currently only works on single urns and requires browsepathv2 to be ingested for it to work correctly.
Closes  https://github.com/datahub-project/datahub/pull/8709.
> feat(cli): support recursive deletes

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/usage.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/usage/clickhouse_usage.py
- metadata-ingestion/src/datahub/ingestion/source/usage/redshift_usage.py
- metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
- metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py
- metadata-ingestion/tests/unit/test_usage_common.py
Note I left this hidden from docs
> feat(ingest/usage): Make cumulative query character limit configurable

- datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
- datahub-web-react/src/app/search/autoComplete/AutoCompleteEntity.tsx
A couple of notes for this PR:
* Search cards suffered from the same icon spacing issue as the new siblings autocomplete that was shown at town hall. The reason it was missed is that dbt/bigquery combo look fine together due to the unique design of those icons.
* I remember why I didn't reuse the search card logo component. It's currently a bit of tangled up component handling a lot of different icon rendering scenarios for different props (entityLogoComponent, platformLogoUrl, platformLogoUrls) and digging in and consolidating all of that would've taken more time than I had available for this project. For another day I suppose!
Search card after:
Autocomplete after:
---
Autocomplete before:
Search card before:
> fix(siblings): space icons out

- datahub-frontend/app/controllers/CentralLogoutController.java
The logout action used to clear the session but did not trigger SSO to deactivate the token. Therefore, when the session was cleared, the user remained logged into the system.
Fixed issue #8369
> fix(frontend): Fix"Logout with OIDC not working"

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/profiler.py
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/tests/unit/test_bigquery_profiler.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
1. Remove unnecessary function wrapped around partition column (issue reported on [slack](https://datahubspace.slack.com/archives/C029A3M079U/p1692340226912199?thread_ts=1691562761.868829&cid=C029A3M079U))
2. Use approx_quantiles for median 
3. Set partitionSpec if limit..offset is used. This captures that profiling was not on full table. also fixes row_count for bigquery profiling if limit..offset were used. Earlier row_count would have been same as limit.
4. use string constants for dialects, etc
5. remove redundant if checks - they are already checked in code flow.
6. report skipped profiles with reason details
> fix(ingest/bigquery): fix partition and median queries for profiling

- docs-website/src/pages/docs/_components/SearchBar/index.jsx
- docs-website/src/pages/docs/_components/SearchBar/search.module.scss
- docs-website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
A couple of fixes for the docs website versioning:
1. Swizzles the `DocsVersionDropdownNavbarItem` component in order to disable the link on the primary nav item. Clicking the version nav item now just opens the dropdown instead of linking anywhere.
2. Changes the default selected version in the search dropdown on the docs homepage. Since the docs homepage is actually a custom page and not versioned, we can't know the selected version as there is none. The active version displayed in the nav will always be the `latest` version. So we just select the second version available in the dropdown by default instead of the first. May need to revisit when another version is added to confirm. Styles for version dropdown also updated to make it look nicer.
> docs: minor fix on versioning navbar and dropdown

- metadata-ingestion/src/datahub/emitter/mcp_builder.py
It's been deprecated for 8 months.
> fix(ingest): drop `wrap_aspect_as_workunit` method

- smoke-test/tests/cypress/cypress/e2e/glossary/glossary_navigation.js
Test steps:
1. create a new term group and term, move term to the group
2. ensure the new term is under the parent term group in the navigation sidebar
3. move a term group from the root level to be under a parent
4. ensure it is no longer on the sidebar navigator at the top level but shows up under the new parent
5. delete a term group
6. ensure it is no longer in the sidebar navigator
> Glossary Navigation Cypress test

- .github/workflows/check-datahub-jars.yml
- .github/workflows/docker-unified.yml
- .github/workflows/metadata-io.yml
- .github/workflows/publish-datahub-jars.yml
- .github/workflows/spark-smoke-test.yml
Note that ingestion will continue to be tested with a python version matrix. This is purely for internal python usage (e.g. smoke test).
> ci: upgrade python to 3.10 for builds

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/MappingsBuilder.java
Using the same analyzer for the index and search is already the default: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-analyzer.html
`By default, queries will use the analyzer defined in the field mapping`
So, no need to specify it explicitly, and doing so causes the system update job to detect a difference between the field as exists in ES and the defined mapping when there isn't one.
> fix(index): Do not override the search analyzer for ngram fields

- metadata-ingestion/src/datahub/cli/ingest_cli.py
Corrects graphQL query for uploading an ingestion recipe for the first time. Also removes the schedule parameter as the input when it is not specified.
> feat(cli): fix upload ingest cli endpoint

- metadata-ingestion/docs/transformer/dataset_transformer.md
Fixing a small typo in the docs
> docs(transformer): fix names in sample code of 'pattern_add_dataset_domain'

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataproduct/mappers/DataProductMapper.java
If someone creates a Data Product without a name (not possible through the UI but is possible in the model) we need to return something for the name and not null since graphql and the frontend are always expecting it. If we get in this weird situation, just return the ID of the urn instead.
> fix(java) Update DataProductMapper to always return a name

- metadata-ingestion/setup.py
For airflow 2.7 support, which requires `jsonschema>=4.18.0`
> build(ingest): Bump jsonschema for Python >= 3.8

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_11.md
> docs(managed datahub): release notes 0.2.11

- metadata-ingestion/setup.py
> build(ingest): Remove constraint on jsonschema for Python >= 3.8

- smoke-test/tests/cypress/cypress/e2e/glossary/glossary_navigation.js
- smoke-test/tests/cypress/cypress/e2e/mutations/edit_documentation.js
> Fix for edit_documentation and glossary_navigation cypress tests

- metadata-service/auth-impl/src/main/java/com/datahub/telemetry/TrackingService.java
Using two lines so debug logs still have the stack trace
> fix(gms): lower telemetry error log level

- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/__init__.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/hooks/datahub.py
- metadata-ingestion/setup.py
Would previously see this from the plugin manager.
```
Exception: The package 'acryl-datahub' from setuptools and acryl-datahub-airflow-plugin do not match. Please make sure they are aligned
```
Also fixes + registers hook types for new Airflow versions.
> fix(airflow): fix provider loading exception

- smoke-test/tests/cypress/cypress/e2e/glossary/glossary_navigation.js
This should fix the flaky glossary_navigation.js Cypress test
> Fix glossary_navigation.js

- smoke-test/tests/cypress/cypress/e2e/mutations/managing_secrets.js
Test steps:
1. Navigate to the manage ingestion page → Secrets
2. Create a new secret
3. Create an ingestion source using a secret
4. Remove a secret
5. Verify secret is not present during ingestion source creation for password dropdown
6. Verify secret can be added during ingestion source creation and used successfully.
7. Remove secret and ingestion source
> Managing Secrets Cypress test

- datahub-web-react/src/app/domain/nestedDomains/ManageDomainsPageV2.tsx
- datahub-web-react/src/app/entity/user/UserEditProfileModal.tsx
- datahub-web-react/src/app/settings/SettingsPage.tsx
Disables a few more things if the read only mode is enabled (specifically on the demo site)
Also fixes a styling issue on the manage domains page.
> feat(ui) Make certain things disabled if read only mode is enabled

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_ambiguous_column_no_schema.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
Extra changes:
- a new test case to check that ambiguous columns are skipped
- some memory usage optimization in lineage generation
> feat(ingest): bump acryl-sqlglot

- docs-website/markdown-link-check-config.json
- docs-website/package.json
It had too many false positives, so can't be a blocking step in CI. However, it was still super useful so we'll just need to manually run it every now and then.
> fix(docs): remove link-checker from CI

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
Follow up on https://github.com/datahub-project/datahub/pull/8626.
The report currently shows the object refs:
```
'schema_api_perf': '<datahub.ingestion.source.bigquery_v2.bigquery_report.BigQuerySchemaApiPerfReport object at 0x7f27859c5ba0>',
'audit_log_api_perf': '<datahub.ingestion.source.bigquery_v2.bigquery_report.BigQueryAuditLogApiPerfReport object at 0x7f27859c5bd0>',
```
> fix(ingest/bigquery): show report in output

- docker/postgres-setup/init.sh
Solves this issue:
```
psql: error: connection to server at "181.00.00.1", port 5432 failed: FATAL:  database "datahub" does not exist
```
See https://datahubspace.slack.com/archives/CV2UVAPPG/p1694026652007379?thread_ts=1693937473.676269&cid=CV2UVAPPG
> fix(docker): support alternate postgres db in postgres-setup

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
While investigating following error:
```
cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}
```
we found that was produced because of the following messages including call stacks were added to the reports:
```
'products_events_behaviour.formsaveerror': ['unable to get column information due to an error -> (pyhive.exc.OperationalError) TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error running query: org.apache.spark.sql.AnalysisException: s3a://data-sch-products-pro/events_behaviour/formsaveerror doesn\'t exist:140:139", \'org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$:runningQueryError:HiveThriftServerErrors.scala:47\', …
```
> fix(report): too long report causes MSG_SIZE_TOO_LARGE in kafka

- metadata-ingestion/setup.py
We should be able to loosen this once https://github.com/python/typeshed/issues/10764 is fixed. I have a PR up for it: https://github.com/python/typeshed/pull/10776.
> fix(ingest): bound types-requests

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
> fix(ingest/s3): Converting windows style path to posix one on local fs

- docs/managed-datahub/observe/freshness-assertions.md
Added a sentence to the Freshness Assertion guide explaining the use case of filtering by Operation Type
> docs(observability): Freshness Assertion Operation Types

- docs/ownership/ownership-types.md
Updates ownership type documentation image urls to map to the main branch.
There is a possible concern that this may break v0.10.5 documentation if we delete the branch behind this PR: https://github.com/datahub-project/static-assets/pull/40
> feat(docs): Update ownership-types image urls

- metadata-ingestion/setup.py
Added pin based on https://github.com/databricks/databricks-sdk-py/issues/200. Hopefully that has been fixed since. databricks-sdk on version 0.8.0 so even if this isn't fixed, I think it's worth gaining the improvements since then
> build(ingest/databricks): Relax databricks-sdk pin

- .github/scripts/docker_helpers.sh
- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
> fix(docker): slim tags

- .github/scripts/docker_helpers.sh
- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
> ci: Docker slim tag fix

- datahub-web-react/src/app/entity/dataProduct/DataProductEntity.tsx
- datahub-web-react/src/app/home/HomePageRecommendations.tsx
In this PR, I added EntityType.DataProduct into the view entity filter so that the DataProduct(s) will display as a card under "Explore your Data" section on the home page.
> fix(data-product): show data product card on home page

- metadata-ingestion/src/datahub/cli/docker_cli.py
> fix(cli): make quickstart docker compose up command more robust

- metadata-ingestion/docs/sources/databricks/unity-catalog_pre.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/emitter/mcp_builder.py
- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/report.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/ingestion/source/unity/usage.py
We don't get notebook upstreams directly, instead we get tables' upstreams and downstreams which can include notebooks. Am open to suggestions on how to solve this in a cleaner way
> feat(ingest/unity): Ingest notebooks and their lineage

- datahub-web-react/src/app/search/SearchBar.tsx
- datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
- datahub-web-react/src/conf/theme/theme_dark.config.json
- datahub-web-react/src/conf/theme/theme_light.config.json
1. Add focus border
2. Alter placeholder text
3. Support command-k focus of the search input
4. Fixed the View All Results for Query bug with quick filters (selecting quick filter automatically selected a query text). This is just a simplification. Any time there is a query we show the "View all results for" option now. 
Moving ingestion nav tab to the far right (as per designs)
> refactor(style): Improve search bar input focus + styling

- metadata-ingestion/src/datahub/configuration/source_common.py
- metadata-ingestion/src/datahub/configuration/validate_field_deprecation.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/file.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/config.py
- metadata-ingestion/src/datahub/ingestion/source/s3/config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/tests/unit/test_pydantic_validators.py
There were both long-requested items, so finally adding them. `test_warnings_are_errors` having a default of true is technically a breaking change.
It might be easier to review this by commit.
> feat(ingest/dbt): support `use_compiled_code` and `test_warnings_are_errors`

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/emitter/mcp_builder.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
It's not pretty but it gets the job done...
> fix(ingest/unity): Remove metastore from ingestion and urns; standardize platform instance; add notebook filter

- docs-website/download_historical_versions.py
> fix: add retry for fetch_url

- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/report.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
> feat(ingest/unity): Use ThreadPoolExecutor for CLL

- docker/mariadb/init.sql
- docker/mysql-setup/init.sql
- docker/mysql/init.sql
- docker/postgres-setup/init.sql
- docker/postgres/init.sql
Attempt number 2 for https://github.com/datahub-project/datahub/pull/8669 with only dropping older table if exists
> fix(setup): drop older table if exists

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
- metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
I recognize this is a decent refactor, but I didn't want to keep contributing to this scattered urn generation process. This is meant to replicate existing behavior, aside from adding the ability to parse `[database].[schema].[table]` from `fullName`. Also now parses table name from `[schema].[table]`, when it used to only parse the schema name
> feat(ingest/tableau): Allow parsing of database name from fullName

- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_create_view_with_cte.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_from_sharded_table_wildcard.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_nested_subqueries.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_sharded_table_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_star_with_replace.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_view_from_union.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_create_view_as_select.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_expand_select_star_basic.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_insert_as_select.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_ambiguous_column_no_schema.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_count.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_from_struct_subfields.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_from_union.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_max.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_ctes.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_full_col_name.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_case_statement.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_column_cast.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_column_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_ctas_column_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_default_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(ingest): add output schema inference for sql parser

- metadata-ingestion/docs/sources/teradata/teradata_pre.md
- metadata-ingestion/docs/sources/teradata/teradata_recipe.yml
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
- metadata-ingestion/src/datahub/testing/check_sql_parser_result.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_teradata_default_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(ingest/teradata): Teradata source

- datahub-graphql-core/src/main/resources/search.graphql
Example usage:
```
{
searchAcrossEntities
(
input: {types: [], query: "*", orFilters: 
[{and: [{field: "<numeric property>", condition: GREATER_THAN, values:["400"], negated: false}]}]}
) {
searchResults {
entity {
urn,
type
}
} 
}
}
```
This PR is so short because the condition is parsed from GraphQL using Condition.valueOf:
https://github.com/datahub-project/datahub/blob/a8f0080c08b5c816f0dae9d3bef07ea00220541e/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ResolverUtils.java#L177
And these already exist as conditions:
https://github.com/datahub-project/datahub/blob/a8f0080c08b5c816f0dae9d3bef07ea00220541e/metadata-models/src/main/pegasus/com/linkedin/metadata/query/filter/Condition.pdl#L4
So, simply add them as options in the GraphQL API to support filtering …
> feat(graphql): support filtering based on greater than/less than criteria

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit_log_api.py
- metadata-ingestion/src/datahub/utilities/ratelimiter.py
- metadata-ingestion/tests/unit/utilities/test_ratelimiter.py
> build(ingest): remove ratelimiter dependency

- metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
> feat(ingest/teradata): Add option to not use file backed dict for view definitions

- metadata-ingestion/src/datahub/ingestion/source/aws/s3_util.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/report.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
@treff7es can you explain why `make_s3_urn` removes the period in the extension. I had to undo that for external lineage to match urns, as the S3 source creates urns with periods in them. Do you know if we can make this consistent?
> feat(ingest/unity-catalog): Support external S3 lineage

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
On Windows the File Backed Collection's close failed when it tried to remove the temporary director it was created because the files were open.
This only caused issues on Windows because on Linux you can delete opened files while on windows you cannot.
The files were open because TemporayDirectory's close got called earlier than it should.
In my fix I got rid of TemporaryDirectory and handled temporary directory removal manually (which actually we did as well in the code). (Unfortunately with TemporayDirectory you can't control temp directory removal (you can only in [Python 3.12](https://docs.python.org/3.12/library/tempfile.html#tempfile.TemporaryDirectory))
> fix(ingest) - Fix file backed collection temp directory removal

- datahub-web-react/src/graphql/scroll.graphql
Now when you download the lineage csv, there is a `level of dependency` column listing the degree.
> add dependency level to scrollAcrossLineage search results

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit.py
https://cloud.google.com/bigquery/docs/tables#table_naming makes no mention of $ or @ being forbidden. We don't know why this was there in the first place, so we're removing it
> fix(ingest/bigquery): Remove table name restrictions (allow $ and @)

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py
- metadata-ingestion/tests/unit/test_athena_source.py
- metadata-ingestion/tests/unit/test_clickhouse_source.py
- metadata-ingestion/tests/unit/test_snowflake_source.py
Previously we would not alter `sqlalchemy_uri` even when trying to access a different database, resulting in errors. Since we provide this option we should support.
I replace our custom `make_sqlalchemy_uri` with one provided by the sqlalchemy sdk. I have to parse host and port out of `at` but still think this is preferred. This method can handle multiple values for the same key, for example.
> fix(ingest/sqlalchemy): Fix URL parsing when sqlalchemy_uri provided

- datahub-web-react/src/app/ingest/source/executions/ExecutionRequestDetailsModal.tsx
- datahub-web-react/src/app/ingest/source/utils.ts
- datahub-web-react/src/graphql/ingestion.graphql
Prepares frontend to be able to render new ingestion statuses. I was going to put these statuses in the metadata model, but that seems kind of committal. I make two changes to the existing statuses on the frontend:
- Change cancelled status icon
- Adds periods to the status description copy
Also adds a recipe section because I want this all the time when debugging.
> feat(frontend/ingestion): Support flagged / warning / connection failure statuses; add recipe

- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/search/TimeseriesAspectServiceTestBase.java
Previously, ElasticSearch would respond with a 400 bad request message.
Prepending a / to the path makes it happy
> fix(api): Add preceding / to get index sizes path

- docker/datahub-frontend/start.sh
Fixes issue introduced in https://github.com/datahub-project/datahub/pull/9031 where frontend would start with debug flags by default. This breaks quickstartDebug gradle task used in development.
> feat(frontend): Remove debug flag from start script

- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator_no_dag_listener.json
- metadata-ingestion/src/datahub/emitter/sql_parsing_builder.py
- metadata-ingestion/src/datahub/testing/check_sql_parser_result.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_create_view_with_cte.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_from_sharded_table_wildcard.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_nested_subqueries.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_sharded_table_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_star_with_replace.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_view_from_union.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_create_table_ddl.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_create_view_as_select.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_from_struct_subfields.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_full_col_name.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_teradata_default_normalization.json
> feat(sqlparser): parse create DDL statements

- datahub-web-react/src/app/permissions/policy/PolicyDetailsModal.tsx
- datahub-web-react/src/app/permissions/policy/PolicyPrivilegeForm.tsx
- datahub-web-react/src/app/permissions/policy/policyUtils.ts
- docs/authorization/policies.md
- metadata-ingestion/tests/unit/serde/test_serde.py
Fixes https://github.com/datahub-project/datahub/issues/9085 in the UI part. Pending changes to the update logic. Additional changes to make repo consistent with the usage of the mentioned fields.
> fix(ui): Fixes handling of resources filters in UI

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
- metadata-ingestion/src/datahub/utilities/sqlalchemy_type_converter.py
The types in the mapping need to be valid inputs for SchemaFieldDataType, which means they must come from the codegen'd class. This fixes a regression from https://github.com/datahub-project/datahub/pull/8137.
Fyi @bossenti - I don't think this should have any impact on the functionality of your PR, since the mappers are only used by dbt/looker/similar sources, whereas the custom athena dialect handles it for the athena source itself. This was necessary to avoid a sqlalchemy dependency in dbt/looker since they import sql_types.py.
> fix(ingest): update athena type mapping

- metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_api_reader.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
Hiding from docs as we should encourage pulling from the database directly, which is more performant.
> feat(ingest/datahub-source): Allow ingesting aspects from the entitiesV2 API

- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/model/ProtobufField.java
This PR resolves https://github.com/datahub-project/datahub/issues/9072
If nested message has a reserved field, it will not try to parse the comment of the field (skip it).
> fix(datahub-protobuf): add check if nested field is reserved

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
> fix(ingest/bigquery): Fixing lineage filter query

- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
> (fix): Avoid java.util.ConcurrentModificationException

- datahub-web-react/src/app/search/useGetSearchQueryInputs.ts
- datahub-web-react/src/app/search/utils/__tests__/generateOrFilters.test.ts
- datahub-web-react/src/app/search/utils/generateOrFilters.ts
Wherever we submit orFilters, we're using `generateOrFilters` which converts out nested filters into the correct format. Unfortunately we were only separating out these nested filters in one function above this one for the main search page (the only place we have nested filters). However we also use this function without using the main function above this to filter out nested vs non-nested filters for `scrollAcrossEntities` - which means we were getting errors in the incorrect format.
> fix(ui) Fix filtering logic for everwhere generating OR filters

- datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
- gradle/versioning/versioning.gradle
- smoke-test/tests/cypress/cypress/e2e/mutations/managed_ingestion.js
> build(release): Update files for 0.12.0 release

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_with_filter.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_to_file.json
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_with_lower_case_urn.json
- metadata-ingestion/tests/integration/sql_server/setup/setup.sql
> fix(ingest/sql-server): update queries to use escaped procedure name

- docs-website/sidebars.js
- docs/managed-datahub/chrome-extension.md
> docs: fix saasonly flags for some pages

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- commit 1 - add a test case to repro the behavior
- commit 2 - update code and test case to fix this
> fix(ingest/snowflake): missing view downstream cll if platform instance is set

- smoke-test/tests/cypress/cypress/e2e/lineage/download_lineage_results.js
- smoke-test/tests/cypress/cypress/e2e/mutations/dataset_ownership.js
Fix for flaky download_lineage_results cypress test
> Fix for flaky download_lineage_results cypress test

- docs/how/updating-datahub.md
> docs: Update updating-datahub.md

- metadata-ingestion/src/datahub/ingestion/api/workunit.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
> feat(ingest/looker): cleanup error handling

- metadata-ingestion/src/datahub/emitter/mcp_builder.py
- metadata-ingestion/tests/unit/test_mcp_builder.py
> feat(ingest): add `entity_supports_aspect` helper

- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_postgres_select_subquery.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_update_from_table.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_update_hardcoded.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_update_self.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
Handles more edge cases in `UPDATE` statement CLL, and also fixes a bug with our generation of CLL of subqueries (we'd previously miss some columns, and also generate some incorrect lineage).
Adds test cases related to those, and also checked that this has no negative impact with our private query corpus. For some queries that we don't handle correctly right now, I've also added test cases in skip mode so that we can turn them on once we get them to work properly.
> feat(sqlparser): support more update syntaxes + fix bug with subqueries

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
Our previous Docker volume declaration was at too high a level in the file tree, which meant that the actual data was stuck in docker anonymous volumes instead of our named volume. As such, those volumes would be lost, causing zookeeper to start fresh instead of loading it's previous state. The kafka broker, which retained its state correctly, would then throw an InconsistentClusterIdException.
Repro - this sequence now works, whereas it didn't before.
```
datahub docker quickstart -f <file>
datahub docker quickstart --stop
datahub docker quickstart -f <file>
```
Closes https://github.com/datahub-project/datahub/issues/9047.
> feat(quickstart): fix broker InconsistentClusterIdException issues

- smoke-test/tests/cypress/cypress/e2e/lineage/download_lineage_results.js
Fix for a test that passed on Oss and failed on Saas
> Fix for a test that passed on Oss and failed on Saas

- metadata-ingestion/docs/sources/teradata/teradata_pre.md
This PR fixes a broken documentation url in the docs website.The link is now correctly set to the intended documentation.
> docs(teradata): teradata doc external link 404 fix

- gradle.properties
Honestly not sure what the right options are here, so just trying some things out.
See a lot of issues in CI https://github.com/datahub-project/datahub/actions/runs/6631594104/job/18015463615?pr=9061
> build: increase gradle retries

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(ingest): bump sqlglot parser

- metadata-ingestion/src/datahub/utilities/urns/urn_iter.py
- metadata-ingestion/tests/unit/serde/test_urn_iterator.py
We previously would have an issue with urns nested with the MCP's aspect.
Fixes https://github.com/datahub-project/datahub/pull/9111.
> fix(ingest): fully support MCPs in urn_iter primitive

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_config.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
Enable by setting `emit_used_explores_only: false`.
> feat(ingest/looker): support emitting unused explores

- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
> refactor(policy): refactor policy locking, no functional difference

- smoke-test/tests/privileges/test_privileges.py
> API test for managing access token privilege

- docker/mysql-setup/init.sql
Some database names are only accepted if quoted. See [Schema Object Names](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html) in the MySQL documentation for background. This changes the init SQL file to always quote the database name.
> fix(mysql-setup): quote database name

- docker/elasticsearch-setup/create-indices.sh
In old index management policies, old indices could be dropped. The setup script assumes the index is always present. Adjusting the logic slightly to not rely on the 000001 index specifically.
> fix(elasticsearch): fix elasticsearch-setup for dropped 000001 index

- datahub-web-react/src/app/onboarding/config/LineageGraphOnboardingConfig.tsx
This PR updates the frontend lineage link in `LineageGraphOnboardingConfig.tsx` component to the new lineage docs location made in #8899.
> fix: bad lineage link in `LineageGraphOnboardingConfig.tsx`

- datahub-web-react/src/app/entity/dashboard/shared/DashboardStatsSummary.tsx
- datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
- datahub-web-react/src/app/entity/dataset/shared/ExpandingStat.tsx
> fix: expand the stats row in search preview cards

- .github/workflows/docker-ingestion-smoke.yml
Every PR that comes from a fork gets spammed with a "ingestion smoke" workflow failed email. While the workflow is disabled for datahub-project, forks aren't spared.
If we need this in a private elsewhere, we can just tweak the if condition to be `publish == 'true' || repo = 'org/name'` as needed.
> chore: stop ingestion-smoke CI errors on forks

- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion/src/datahub/ingestion/api/decorators.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
> docs(ingest): inherit capabilities from superclasses

- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_database_reader.py
- metadata-ingestion/tests/unit/test_datahub_source.py
Ordering via query wouldn't use the timeIndex for some reason... not sure why, but didn't want to spend too much time on it.
This looks like a lot of complexity but it's a pretty simple process at its core: hold version = 0 rows in a queue until we get to a new timestamp. This only applies when you're ingesting all versions, which won't work 100% correctly right now anyway (with async rest sink), so most important change is to change the query back, so it can be run efficiently again.
> fix(ingest/datahub-source): Order by version in memory

- datahub-web-react/src/app/lineage/LineageExplorer.tsx
We are trying to move away from displaying raw entity names here.
> refactor(ui): Rename "dataset details" button text to "view details" on lineage sidebar profile

- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/CommandK.tsx
- datahub-web-react/src/app/search/SearchBar.tsx
- datahub-web-react/src/app/search/SearchHeader.tsx
Previously, you could auto-select search using command k but this feature was hidden. In this PR we add iconography to search bar to display that you can select the bar using command k. 
We also fix a minor issue where on some search bars command k was showing when it should not have.
> feat(ui): Add command-k icons to search bar 

- datahub-web-react/codegen.yml
- datahub-web-react/package.json
- datahub-web-react/src/App.tsx
- datahub-web-react/yarn.lock
Dynamically generate possible types that we pass into our Apollo cache so we can cache union types properly. Previously, Apollo cache simply wouldn't cache anything that was based on a union field, making it very difficult to use.
Here are some docs on the new library added that allows us to get these union types using our existing apollo auto-gen tool: https://the-guild.dev/graphql/codegen/plugins/other/fragment-matcher
> feat(ui) Update Apollo cache to work with union types

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/ListPoliciesResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/search/SearchService.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyFetcher.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java
- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/DataHubAuthorizerFactory.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js
Fetching policies was previously limited to 30 policy pages. This PR increases to 1000 by default. Secondly, moving to the scroll API which performs better with deep pagination in the 10k+ policy counts.
The graphql API changes are not included so we're forced to stay compatible with the current start/offset and count by paginating in the background when needed for the UI.
> feat(policy): enable support for 10k+ policies

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/entity/steps/BackfillBrowsePathsV2Step.java
- docker/datahub-upgrade/env/docker-without-neo4j.env
- docker/datahub-upgrade/env/docker.env
- docker/docker-compose.dev.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- metadata-io/src/main/java/com/linkedin/metadata/search/client/CachingEntitySearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/services/src/main/java/com/linkedin/metadata/search/EntitySearchService.java
Create browsePathV2 reprocessing of default browse paths.
Fix search cache keys for search flags
> feat(browsepathv2): Allow system-update to reprocess browse paths v2

- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/SearchablePage.tsx
Auto-complete would make a graphql call to the backend on every keystroke which creates unnecessary load. Let's debounce that by half a second and only call when they stop typing for that long.
> feat(ui) Debounce auto-complete in search bar

- metadata-auth/auth-api/src/main/java/com/datahub/authorization/AuthorizedActors.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/AuthorizerChain.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/PolicyEngineTest.java
- metadata-service/plugin/src/test/sample-test-plugins/src/main/java/com/datahub/plugins/test/TestAuthorizer.java
Adds roles as a new set of actor that is allowed to perform operations on DataHub.
> feat(auth): Add roles to policy engine validation logic

- metadata-events/mxe-schemas/rename-namespace.sh
- metadata-ingestion/scripts/docgen.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/mode.py
> chore(ingest): cleanup various methods

- build.gradle
- datahub-upgrade/build.gradle
- metadata-events/mxe-registration/build.gradle
- metadata-events/mxe-utils-avro/build.gradle
- metadata-io/build.gradle
- metadata-service/factories/build.gradle
- metadata-service/restli-api/build.gradle
> chore(security): version adjustments for security vulns

- metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
This should fix https://github.com/datahub-project/datahub/issues/9238
This is my first PR in the DataHub Open Source project. I tried to followed the contributors guidelines, but let me know if I missed anything here.
> docs(ingest): fix typo in snowflake ingestion docs

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/kafka-setup/Dockerfile
> chore(security): jre to headless, removes x11 dependency

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/test/java/com/linkedin/metadata/search/TestEntityTestBase.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopPlatformsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/search/EntitySearchService.java
This fixes a UI bug where if slack is configured or a custom platform for non-searchable entities is added, then those platforms are not counted towards platforms to be shown above the fold in the homepage.
> feat(recomendations): Make top platforms account only for searchable entities

- datahub-web-react/src/app/identity/group/GroupList.tsx
- datahub-web-react/src/app/identity/user/UserList.tsx
- datahub-web-react/src/app/ingest/secret/SecretsList.tsx
- datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
- datahub-web-react/src/app/permissions/policy/ManagePolicies.tsx
- datahub-web-react/src/app/permissions/roles/ManageRoles.tsx
> fix:fix search on paginated lists

- datahub-web-react/src/app/search/SearchBar.tsx
> fix: increase the search bar highlight border to double the width

- datahub-web-react/src/app/domain/DomainSearch.tsx
- datahub-web-react/src/app/domain/DomainSearchResultItem.tsx
- datahub-web-react/src/app/domain/nestedDomains/domainNavigator/DomainNavigator.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
> feat: Add loading indicator to Manage Domains sidebar

- datahub-web-react/src/app/entity/container/ContainerEntity.tsx
Only a really small fix, but currently in the entity profile of a container the "View in XYZ"-link is not visible - this PR fixes this (for all other entities the link should already be visible in the entity's profile).
> fix(ui): show external url also in entity profile of containers

- datahub-web-react/.env
- datahub-web-react/README.md
- datahub-web-react/src/setupProxy.js
Most of the customizations made by my team are only in the datahub-web-react component (for example: some styling or button addition). However, in order for developers to test their changes in a local environment, they need to use `quickstart.sh` and setup a whole set of services that have a certain complexity. Given that we have a dedicated DataHub environment for Homologation/Development, this change allows developers to use this cloud-hosted server and use "real" data during their customization tests, without the need to setup an entire local environment.
> refactor(datahub-web-react): allows proxying to external datahub-frontend servers

- metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
Closes https://github.com/datahub-project/datahub/issues/8986
> feat(ingest): support advanced configs for aws

- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/test_schemaresolver.py
A naive approach for fixing #9172. I simply transform the platform instance to lower case when required.
> fix(sql-parser): convert platform instance to lowercase when building table urns

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dataproduct/ListDataProductAssetsResolver.java
Without the distinct a data product list query would potentially query the same entity index 10s of times for the same entity.
> fix(graphql): prevent duplicate index queries for dataproducts

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/MapperUtils.java
Highlighted value is never guaranteed to be a valid urn. Often results in confusion when debugging other errors even though it is WARN. Additionally remove stacktrace which also indicated more importance then it really has.
> logging(search): log level highlight value urn detection

- .gitignore
- docs/developers.md
This change adds Python 3.10 to the Local Development README page. Currently, if Python 3.11+ is used then the build process fails.
```
> Task :metadata-ingestion:checkPythonVersion FAILED
File "<string>", line 1, in <module>
AssertionError: Python version (3, 11) not allowed
```
Py3.7 and 3.10 are technically both valid (see: https://github.com/datahub-project/datahub/blob/master/.github/workflows/metadata-ingestion.yml#L34), however, 3.7 is already EOL.
I also added the [pyenv](https://github.com/pyenv/pyenv) local version config file to .gitignore since this popular tool allows developers to use pyenv to control their python version.
> Add Python version in Developer README

- .github/scripts/docker_helpers.sh
- .github/workflows/docker-unified.yml
- Add sha tag to every image
- Sync demo-head deployment on merge to head
@david-leifker @darnaut
> Sync datahub-head on merge

- datahub-web-react/src/app/entity/ownership/ManageOwnership.tsx
- datahub-web-react/src/app/entity/view/ManageViews.tsx
- datahub-web-react/src/app/identity/ManageIdentities.tsx
- datahub-web-react/src/app/identity/group/GroupList.tsx
- datahub-web-react/src/app/identity/user/UserList.tsx
- datahub-web-react/src/app/permissions/ManagePermissions.tsx
- datahub-web-react/src/app/permissions/policy/ManagePolicies.tsx
- datahub-web-react/src/app/permissions/roles/ManageRoles.tsx
- datahub-web-react/src/app/settings/AccessTokens.tsx
- datahub-web-react/src/app/settings/SettingsPage.tsx
- datahub-web-react/src/app/settings/posts/ManagePosts.tsx
- datahub-web-react/src/app/settings/posts/PostsList.tsx
- datahub-web-react/src/app/shared/RoutedTabs.tsx
> PRD-742/fix:Settings tab should have 2 scrollable sections

- datahub-web-react/build.gradle
- datahub-web-react/package.json
> fix(node): fix node_options

- docs-website/src/pages/_components/Hero/index.js
- docs-website/src/pages/_components/TownhallButton/index.jsx
- docs-website/src/pages/_components/TownhallButton/townhallbutton.module.scss
Displays the townhall RSVP button for 2 weeks before each event. 
2 weeks before ~ the day of the townhall
the rest of the month 
Any feedback on the design is welcome!
> feat: add townhall RSVP link on the main page 

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/trino.ts
This is minor tooltip PR. It is not obvious that host should be provided specifically without the protocol, and example of `trino-server:5432` does not state it explicitly.
> docs(ingestion): Added mention of host without protocol

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/tests/integration/lookml/lkml_same_name_views_different_file_path_samples/data.model.lkml
- metadata-ingestion/tests/integration/lookml/lkml_same_name_views_different_file_path_samples/data2.model.lkml
- metadata-ingestion/tests/integration/lookml/lkml_same_name_views_different_file_path_samples/path1/foo.view.lkml
- metadata-ingestion/tests/integration/lookml/lkml_same_name_views_different_file_path_samples/path2/foo.view.lkml
- metadata-ingestion/tests/integration/lookml/lookml_same_name_views_different_file_path.json
- metadata-ingestion/tests/integration/lookml/test_lookml.py
if using file_path in view_naming_pattern config.
> fix(ingest/lookml): emit all views with same name and different file path

- datahub-web-react/src/app/settings/SettingsPage.tsx
> fix: fix the settings height when there are not many items

- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/factories/BootstrapManagerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestOwnershipTypesStep.java
Changes logic of ownership types bootstrap process:
* Now it runs with every start of the GMS (instead of only during upgrade)
* It is possible to provide file path to custom ownership types instead of hard-coded ones
In case the new environmental variable (`BOOTSTRAP_OWNERSHIP_TYPES_FILE`) is not set, the old one is used. In such case the only change of behavior of the app will be the fact that the process will be run with every restart of the GMS instead of only running during the upgrade (similarly to how policies are set).
Change similar to the https://github.com/datahub-project/datahub/pull/8812
> feat(config): Configurable bootstrap of ownership types

- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
- metadata-ingestion/tests/integration/sql_server/golden_files/golden_mces_mssql_no_db_to_file.json
- metadata-ingestion/tests/integration/sql_server/setup/setup.sql
> fix(ingest/mssql): Add MONEY and SMALLMONEY data types as Number

- metadata-ingestion/docs/dev_guides/add_stateful_ingestion_to_source.md
The changes to the redundant run handler portion are just the autoformatter. Only updating the stale entity removal docs here.
> docs(ingest): update docs on adding stateful ingestion

- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
We found a visual bug in safari when sidebar is collapsed
> fix(sidebar): remove a space reserved for scroll bars when sidebar is collapsed

- docker/build.gradle
- docker/docker-compose-without-neo4j.postgres.override.yml
> feat(gradle): quickstart postgres gradle task

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
Super annoyed with this bug and it looks really bad. Bandaid solution, but it's pretty simple. I don't think we have to worry about storing all these in memory... can't be that many.
> fix(ingest/browse): Re-emit browse path v2 aspects to avoid race condition

- docs-website/filterTagIndexes.json
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
Adding Teradata to list of Integrations
Adding column level lineage capability to redshift
> doc(ingest/teradata): Adding Teradata to list of Integrations

- datahub-web-react/src/app/search/SearchResults.tsx
> fix: show formatted total result count in Search

- metadata-ingestion/src/datahub/cli/migrate.py
Currently this just failed to connect to a server due to earlier connection to `127.0.0.1`. This gets it past that.
> fix(migrate): connect with token without dry-run

- datahub-web-react/src/app/entity/shared/tabs/Entity/components/EntityList.tsx
- datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx
> fix(ui): Minor: fix unnecessary lineage tab scroll by removing -1 margin on lists

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityTabs.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/useGetDataForProfile.ts
- datahub-web-react/src/app/entity/shared/tabs/Lineage/generateUseSearchResultsViaRelationshipHook.ts
- datahub-web-react/src/app/search/SearchPage.tsx
- datahub-web-react/src/app/search/SearchResultList.tsx
- datahub-web-react/src/app/search/SearchResults.tsx
- datahub-web-react/src/app/search/SearchResultsLoadingSection.tsx
- datahub-web-react/src/app/search/__tests__/SearchPage.test.tsx
- datahub-web-react/src/app/search/filters/BasicFilters.tsx
- datahub-web-react/src/app/search/filters/BasicFiltersLoadingSection.tsx
- datahub-web-react/src/app/search/filters/SearchFilters.tsx
- Adding caching for search page
- Adding caching for entity profile page
- Adding caching to embedded list search components 
- Adding skeleton loader for search results page
> feat(ui): Add caching to search, entity profile for better UX

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
Fixes https://github.com/datahub-project/datahub/issues/9340
> fix(ingest/bigquery): Fix format arguments for table lineage test (#9340)

- datahub-web-react/package.json
- datahub-web-react/yarn.lock
> fix: node-fetch forwards secure headers to untrusted sites

- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/resolver.py
- metadata-ingestion/tests/unit/test_powerbi_parser.py
> fix(ingest/powerbi): Allow old parser to parse [db].[schema].[table] table references

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/cli/put_cli.py
- metadata-ingestion/src/datahub/cli/specific/file_loader.py
- metadata-ingestion/src/datahub/configuration/config_loader.py
- metadata-ingestion/src/datahub/configuration/json_loader.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/lineage.py
- metadata-ingestion/tests/unit/config/test_config_loader.py
Also adds support for parsing .json files, and refactors some other code.
> feat(ingest): support stdin in `datahub put`

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/tests/unit/api/source_helpers/test_source_helpers.py
- metadata-ingestion/tests/unit/utilities/test_perf_timer.py
We're starting to see issues like this in CI, likely due to a dependency upgrade (probably freezegun https://pypi.org/project/freezegun/ - see discussion here https://github.com/spulec/freezegun/issues/521)
When using `caplog`, we see a stray asyncio log message before the rest of the logs. This should clear that out.
```
FAILED tests/unit/api/source_helpers/test_source_helpers.py::test_auto_empty_dataset_usage_statistics - assert not [<LogRecord: asyncio, 10, /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/asyncio/selector_events.py, 58, "Using selector: %s">]
+  where [<LogRecord: asyncio, 10, /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/asyncio/selector_events.py, 58, "Using selector: %s">] = <_pytest.logging.LogCaptureFixture object at 0x7f067d18d9d0>.records
FAILED …
```
> fix(ingest): resolve issue with caplog and asyncio

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
Add view lineage parsing for Athena
> feat(ingest/athena): Enable Athena view ingestion and view lineage

- .github/workflows/docker-unified.yml
- smoke-test/smoke.sh
- smoke-test/test_e2e.py
- smoke-test/tests/privileges/test_privileges.py
- smoke-test/tests/timeline/timeline_test.py
> feat(ci): split no cypress test suite

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py
Two bug fixes
- Fix Too Many values to unpack error in case we have platform instance specified for Redshift
> fix(ingest/redshift): too many values unpack

- docs-website/src/pages/_components/TownhallButton/index.jsx
- docs-website/src/pages/_components/TownhallButton/townhallbutton.module.scss
> docs: add youtube link to townhall button on docs

- docker/datahub-frontend/start.sh
This changes lets us configure the Java memory options (-Xms and -Xmx) of the frontend via ENV variable.
> feat(datahub-frontend): make Java memory options configurable via ENV variable

- metadata-ingestion/docs/sources/sql-queries/sql-queries.md
- metadata-ingestion/docs/sources/sql-queries/sql-queries_recipe.yml
- metadata-ingestion/src/datahub/ingestion/source/sql_queries.py
> docs(ingest/sql-queries): Add documentation

- metadata-ingestion/src/datahub/ingestion/source/redshift/profile.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
> fix(ingest/profiling): Add back db_name to sql_generic_profiler methods

- docs/modeling/extending-the-metadata-model.md
- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/scripts/custom_package_codegen.py
- metadata-ingestion/src/datahub/_codegen/aspect.py
Also moves the _Aspect type to a common location to prevent it from being defined twice in the eyes of type checkers.
> fix(ingest): fix metadata for custom python packages

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
context: java-snappy is missing from recently released alpine 3.19, pinning down to 3.18 temporarily as a workaround.
@david-leifker
> Pin alpine base image version to 3.18

- metadata-ingestion/docs/sources/sql-queries/sql-queries_pre.md
- metadata-ingestion/src/datahub/ingestion/source/sql_queries.py
> docs(ingest/sql-queries): Rearrange sections

- metadata-ingestion/src/datahub/ingestion/source/schema/json_schema.py
> fix(json-schema): do not send invalid URLs

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
> feat(ingest): add retries for tableau

- datahub-web-react/src/app/entity/ownership/table/ActionsColumn.tsx
> Add button to copy urn of an Ownership Type

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
- metadata-ingestion/tests/unit/test_pipeline.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
Changed behavior of both ownership transformers by adding possibility to define `ownership_type_urn`, as well as removing default value of ownership_type (it will be populated as CUSTOM if user defines ownership_type_urn). This way the transformers maintain backward compatibility as long as the users don't base on default value for `ownership_type` (if `ownership_type` is set but not `ownership_type_urn` transformers work as before, setting the ownership without `typeUrn`.
Fixes https://github.com/datahub-project/datahub/issues/8441
> feat(ingestion): Add typeUrn handling to ownership transformers

- datahub-web-react/src/app/permissions/policy/ManagePolicies.tsx
- datahub-web-react/src/app/permissions/policy/_tests_/policyUtils.test.tsx
- datahub-web-react/src/app/permissions/policy/policyUtils.ts
- datahub-web-react/src/app/permissions/policy/usePolicy.ts
> fix: support Apollo caching for settings / Policies

- docs/how/extract-container-logs.md
> docs: fix sample command for container logs

- datahub-web-react/src/app/identity/user/UserList.tsx
https://linear.app/acryl-data/issue/PRD-568/searching-for-users-on-users-page-shows-incorrect-roles
Description: 
When the user removes the query from the search bar completely, like when the query length is 0 then we were using the cache-first so it was not updated data, so with no-cache will get the updated data and it will show the correct role on searching as well
[PRD-568_Searching_on_Users.webm](https://github.com/datahub-project/datahub/assets/81357546/7138df77-bc1a-495e-8152-5bab928fb7c2)
> Searching for users on Users page shows incorrect roles: Issue resolved

- datahub-web-react/src/app/ingest/source/executions/ExecutionRequestDetailsModal.tsx
> Fade recipe section to transparent on Ingestion Run Details

- docker/quickstart/quickstart_version_mapping.yaml
- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
Fixes quickstart errors related to the mysql version being interpreted as a float instead of a string.
> fix(quickstart): force strings for mysql version

- docs-website/download_historical_versions.py
- docs/developers.md
- metadata-ingestion/src/datahub/configuration/git.py
- metadata-ingestion/src/datahub/configuration/validate_multiline_string.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/src/datahub/ingestion/source_config/usage/bigquery_usage.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
- metadata-ingestion/tests/unit/config/test_pydantic_validators.py
> feat(ingest): handle multiline string coercion

- docs/modeling/extending-the-metadata-model.md
- metadata-ingestion/scripts/custom_package_codegen.py
- metadata-ingestion/src/datahub/telemetry/telemetry.py
> feat(ingest): rename custom package path from models to metadata

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_redshift_materialized_view_auto_refresh.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_count.json
- metadata-ingestion/tests/unit/sql_parsing/test_sql_detach.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
Extra stuff:
- bumps acryl-sqlglot to v20, which requires a couple other changes
- refactors certain things into constants
- refactors some of the test logic
> feat(ingest): support CLL for redshift materialized views with auto refresh 

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Queries/utils/constants.ts
- datahub-web-react/src/app/ingest/secret/SecretsList.tsx
- datahub-web-react/src/app/ingest/source/IngestionSourceList.tsx
> Add debounce on search on ingestion listing page

- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/LinkList.tsx
> fix: correct the color of edit links

- datahub-frontend/app/auth/AuthModule.java
- datahub-frontend/app/auth/AuthUtils.java
- datahub-frontend/app/auth/sso/SsoConfigs.java
- datahub-frontend/app/auth/sso/SsoManager.java
- datahub-frontend/app/auth/sso/oidc/OidcConfigs.java
- datahub-frontend/app/client/AuthServiceClient.java
- datahub-frontend/app/controllers/SsoCallbackController.java
- datahub-frontend/test/app/ApplicationTest.java
- datahub-frontend/test/security/OidcConfigurationTest.java
- metadata-models/src/main/pegasus/com/linkedin/settings/global/GlobalSettingsInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/settings/global/OidcSettings.pdl
- metadata-models/src/main/pegasus/com/linkedin/settings/global/SsoSettings.pdl
- metadata-models/src/main/pegasus/com/linkedin/settings/global/SsoType.pdl
- metadata-service/auth-servlet-impl/src/main/java/com/datahub/auth/authentication/AuthServiceController.java
> feat(frontend): align frontend sso code with refactors

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/tests/integration/mongodb/test_mongodb.py
fix: allow mongodb source connector to have a 0 input for field schemaSamplingSize
Fixes https://github.com/datahub-project/datahub/issues/9287
> fix(ingest/mongodb): support disabling schemaSamplingSize

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
The current mongodb ingestion will fail if the platform instance is missing from the recipe with `UnboundLocalError`:
`UnboundLocalError: local variable 'data_platform_instance' referenced before assignment`
This PR initiates this local variable to avoid this issue
> fix(ingest): Fix mongodb ingestion when platform_instance is missing from recipe

- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
> fix | PRD-901 | Border is too thick for sidebar

- datahub-web-react/src/app/settings/posts/utils.ts
> fix posts are failing to be created as Admin user

- datahub-web-react/src/app/identity/user/SelectRole.tsx
- datahub-web-react/src/app/identity/user/UserList.tsx
https://linear.app/acryl-data/issue/PRD-568/searching-for-users-on-users-page-shows-incorrect-roles
Description:
[PRD-568.webm](https://github.com/datahub-project/datahub/assets/81357546/36670c38-404d-4c1c-963a-a3add4b189e5)
> search user functionality added

- smoke-test/tests/read_only/test_services_up.py
Forks of the main repo will use git-sha as the py cli version resulting in the version test failing.
This PR makes the test allow those version strings.
> fix(ci): make test flexible to allow sha-based cli versions

- metadata-ingestion/tests/integration/kafka/docker-compose.yml
This mirrors the fixes from https://github.com/datahub-project/datahub/pull/9148.
> fix(ingest): improve kafka-connect test stability

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/BatchGetEntitiesResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/load/BatchGetEntitiesResolverTest.java
Fixes a bug in BatchGetEntitiesResolver to ensure that it respects ordering of inputs when stitching together the response.
> fix(graphql): BatchGetEntitiesResolver respects order

- docker/profiles/docker-compose.actions.yml
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/docker-compose.prerequisites.yml
smoke tests and other code assumes broker instead of kafka-broker for the quickstart kafka broker hostname
> fix(compose-profiles): hostname kafka-broker -> broker

- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_usage.py
> feat(ingest): track thread count in ingestion report

- .github/workflows/airflow-plugin.yml
- .github/workflows/build-and-test.yml
- .github/workflows/docker-unified.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-io.yml
- .github/workflows/spark-smoke-test.yml
- metadata-ingestion/build.gradle
Certain PRs take ~2 minutes to upload artifacts, so this should help speed that up.
Example action run with the issue: https://github.com/datahub-project/datahub/actions/runs/7402378135/job/20140133202?pr=9559
This also removes the slack failure notifications, which never worked in the first place due to a missing secret.
> fix(ci): ignore binaries from test results upload

- .github/workflows/pr-labeler.yml
In previous PR my changes were overwritten https://github.com/datahub-project/datahub/pull/9558 and the logic did not have `!` removed. This was causing labels to be added incorrectly
> fix(ci): fix label logic

- docker/README.md
- docker/airflow/local_airflow.md
- docker/dev-with-cassandra.sh
- docker/dev-without-neo4j.sh
- docker/dev.sh
- docker/ingestion/ingestion.sh
- docker/nuke.sh
- docker/quickstart.sh
- docs/developers.md
- docs/quickstart.md
v1 `docker-compose` is deprecated as of July 2023
Notes:
docker-compose vs docker compose
Unlike Compose V1, Compose V2 integrates into the Docker CLI platform and the recommended command-line syntax is docker compose.
Ref: https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose
> bump(docker-compose): migrate to v2 docker compose cli

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/domain/CreateDomainResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryNodeResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/CreateGlossaryTermResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddOwnerResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddOwnersResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/BatchAddOwnersResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/BatchRemoveOwnersResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/RemoveOwnerResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/OwnerUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/tag/CreateTagResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/utils/OwnerUtilsTest.java
- Fix last modified not being updated on adding owner via the UI
- Some cleanup in OwnerUtils to avoid copy-paste
- Rename some confusing variable names
- `Optional` should not be an argument to methods
- Extract code out to make code readable in OwnerUtils
Things to pay special attention to
- With the ownership type how do we define equality of an Owner? If owner urn is same but ownership type is different then is owner obj considered equal? There were 2 different definitions of equality in add owner and remove owner in OwnerUtils here.  I have updated it to be what I consider to be correct equality definition. But please pay attention to that.
> fix(owner): last modified on adding owner

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
Also updates docs on lineage generation.
> fix(ingest/redshift): include table type in custom properties

- metadata-ingestion/src/datahub/emitter/sql_parsing_builder.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
The query_job attr was made public / tweaked. See https://pypi.org/project/google-cloud-bigquery/ and https://github.com/googleapis/python-bigquery/pull/1747
This also includes a few misc changes that probably didn't merit standalone PRs.
> fix(ingest/bigquery): support google-cloud-bigquery 3.15.0

- metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
- metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py
- metadata-ingestion/src/datahub/ingestion/source/usage/clickhouse_usage.py
This changes the `clickhouse` and `clickhouse-usage` ingestion sources to respect the config value `database_pattern` instead of the deprecated `schema_pattern`. The latter can't be used anymore since its deprecation, so it's currently impossible to filter for databases in these modules.
Note: there are also a lot of other occurrences of "schema" in the code that might be renamed to "database" as well, but I didn't want to do a full blown refactoring here. If you think it is useful, let me know and I'll adjust the PR.
> fix(ingest): support `database_pattern` in clickhouse and clickhouse-usage

- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/utilities/advanced_thread_executor.py
- metadata-ingestion/tests/unit/utilities/test_advanced_thread_executor.py
We've had issues where the default browsePathV2 aspects overwrite the custom ones generated by ingestion sources. It usually happened for a random ~50% of the entities.
We previously attempted to fix this by double-emitting browsePathV2 aspects (https://github.com/datahub-project/datahub/pull/9227). I suspect this didn't fully work because the data in MySQL might already be correct (e.g. the correct browsePathV2 won that race), meaning that no MCL event would get generated, and hence the ES index would remain stale.
Fixes https://github.com/datahub-project/datahub/issues/9276. Note that because of mae consumer lag and delays in the bulk updating of the ElasticSearch indexes, it can take a few minutes after initial ingestion for the browse paths to stabilize into their correct forms in the …
> feat(ingest): key-partitioning for rest emitter

- smoke-test/tests/cypress/cypress/e2e/glossary/glossary.js
- smoke-test/tests/cypress/cypress/e2e/glossary/glossaryTerm.js
- smoke-test/tests/cypress/cypress/support/commands.js
> Fix - Changed popup text visibility and removed unnecessary code

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/SchemaFieldMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
`JsonProps` is a property of SchemaField in the PDL definitions but it was not surfaced at the graphQL layer. This PR addresses that.
> fix(graphql): Add jsonProps to SchemaField type

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/utilities/advanced_thread_executor.py
- metadata-ingestion/tests/integration/lookml/test_lookml.py
- metadata-ingestion/tests/unit/utilities/test_advanced_thread_executor.py
In some cases, the source can produce metadata faster than the sink can consume it. In most cases, our pipeline orchestration pauses the source's execution until the sink is less overwhelmed. This PR extends that throttling capability into the ThreadPoolExecutor.
> feat(ingest/looker): add backpressure-aware executor

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
We noticed from recurring ingestion of MongoDB that there are changes of fields in the dataset while there is no modification of the source data. 
The root cause is the ingestion will downsample the collection schema based on `max_schema_size` we set in the config. The collection fields are sorted by count but there is no further sorting applied when the count is the same. We should add a secondary element delimited_name to the sorted function so the output is consistent
> fix(ingest/mongodb): Fix downsampling the collection schema output undetermined

- smoke-test/tests/cypress/cypress/e2e/settings/homePagePost.js
- smoke-test/tests/cypress/cypress/support/commands.js
> Added Homepage Post Steps

- datahub-graphql-core/build.gradle
Required to improve application logging which is required to debug issues
Validated locally generated code.
> feat(graphql): generate ToString method

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteForMultipleResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchUtils.java
Fixes an intermittent 500 coming from the search bar autocomplete query.
> fix(autocomplete): Filter default entity types based on those present in types map 

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/EmbedRoutes.tsx
- datahub-web-react/src/app/ProtectedRoutes.tsx
- datahub-web-react/src/app/__tests__/Routes.test.tsx
- datahub-web-react/src/app/embed/EmbeddedPage.tsx
A change was recently added that threw off our routes for the embedded pages breaking our chrome extension. What broke it is that the provider for entity registry was a direct parent of where we wanted to use the context and context requires that you must be within one functional component (or more) underneath the context.
This fixes that by breaking the embed routes into a new component that then properly have access to the entity registry provider. This is also cleaner if you ask me anyways.
> fix(extension) Fixes routing for the embed pages for chrome extension

- docs-website/src/pages/index.js
- metadata-ingestion/docs/sources/mssql/mssql_recipe.yml
> fix(docs-website): update copy around the video on index

- datahub-web-react/src/app/settings/posts/CreatePostForm.tsx
- datahub-web-react/src/app/settings/posts/CreatePostModal.tsx
- datahub-web-react/src/app/settings/posts/PostItemMenu.tsx
- datahub-web-react/src/app/settings/posts/PostsList.tsx
- datahub-web-react/src/app/settings/posts/PostsListColumns.tsx
- datahub-web-react/src/graphql/mutations.graphql
> feat(posts): add edit support for posts

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/group/CreateGroupResolver.java
- metadata-models/src/main/pegasus/com/linkedin/identity/RoleMembership.pdl
- metadata-models/src/main/resources/entity-registry.yml
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/DataHubAuthorizerTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/PolicyEngineTest.java
- smoke-test/tests/privileges/test_privileges.py
- smoke-test/tests/privileges/utils.py
- Adds support for roles to be assigned roles by adding `roleMembership` aspect to the CorpGroup entity.
- Updates policy engine to check for roles assigned to the groups of a given actor by:
- Quering for group membership (native and non-native) when resolving roles for a given actor alongside user role membership.
- Batch quering for each group membership type for their respective role memberships.
- Finally, merge all groups together and check permissions based on that.
- Fixes a bug in CreateGroupResolver which was not accounting for `description` to be an optional field when creating groups.
> feat(roles): Add support for roles in groups in GMS

- .github/workflows/airflow-plugin.yml
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_airflow_shims.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/tox.ini
Slack ref: https://datahubspace.slack.com/archives/CV2KB471C/p1705531663262509?thread_ts=1705398317.401379&cid=CV2KB471C
Also fixes tests for Airflow after the new Flask-Session release. See https://github.com/pallets-eco/flask-session/issues/209
> feat(ingest/airflow): support airflow 2.8 dataset listeners

- .github/actions/ci-optimization/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/docker-unified.yml
This PR introduces an action which determines which major component has changes (frontend, backend, ingestion, setup jobs). Based on the changes it will selectively run CI jobs.
In the unified workflow:
* images are pulled from head/head-slim and swapped with the expected image tags when needed just before smoke-tests are run
* the smoke test matrix is also dynamic based on the changed component
* when publishing is enabled everything is run to ensure images are built and tested
A new custom action local to this repository will maintain the mapping from file paths to major component. That action will then be used in any workflow which needs selective jobs/steps. Currently this means the primary unified image build and the build and test workflows.
For example: a frontend change would …
> feat(build): conditional ci

- docs-website/docusaurus.config.js
Adds links to YouTube Playlists via the `Resources` dropdown on the DataHub Docs site.
> docs: Add Case Studies and DataHub Basics to Resources tab

- smoke-test/tests/cypress/cypress/e2e/settings/homePagePost.js
> Added to Verify  Edit Post Steps

- metadata-ingestion/tests/unit/sql_parsing/goldens/test_redshift_temp_table_shortcut.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
Including sortkey and distkey clauses
> feat(ingest/sql-parser): test redshift temp tables

- docker/datahub-mae-consumer/start.sh
- docker/datahub-mce-consumer/start.sh
Kafka consumers in `datahub-{mce|mae}-consumer` need the Schema Registry to be up and ready before they start consuming. This change delays the start of the consumers until Schema Registry is ready.
> fix(consumer): wait for internal schema registry

- .github/workflows/build-and-test.yml
- build.gradle
- entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/AspectsBatch.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/GenericJsonPatch.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/PluginFactory.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/config/PluginConfiguration.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/validation/AspectRetriever.java
- entity-registry/src/main/java/com/linkedin/metadata/models/registry/ConfigEntityRegistry.java
- entity-registry/src/main/java/com/linkedin/metadata/models/registry/PatchEntityRegistry.java
- entity-registry/src/main/java/com/linkedin/metadata/models/registry/config/EntityRegistryLoadResult.java
- ingestion-scheduler/build.gradle
- metadata-events/mxe-avro/build.gradle
- metadata-events/mxe-registration/build.gradle
- metadata-events/mxe-schemas/build.gradle
- metadata-events/mxe-utils-avro/build.gradle
- metadata-integration/java/datahub-client/build.gradle
- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/service/UpdateIndicesService.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-jobs/common/build.gradle
- metadata-models/build.gradle
- metadata-models/src/main/resources/JavaSpring/model.mustache
- metadata-service/configuration/build.gradle
- metadata-service/restli-servlet-impl/build.gradle
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/EntityRecommendationSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/RollbackService.java
- metadata-utils/build.gradle
The Spring 6 changes along with the gradle build configuration introduced a situation where all modules were mostly building with the newer jdk17. This was a bug since we still want to rely on jdk11 for modules like the `datahub-client`. This restores `datahub-client` to jdk11 as well as support jdk8 for the spark lineage plugin.
This was accomplished with some dynamic logic at the beginning of the main gradle file to determine if there is a Spring 6 or Spring Boot 3 dependency. If so, then jdk17 is the only supported option.
For modules supporting the `datahub-client`, such as `metadata-models`, we ensure that the target class version is used with the addition of the jdk8 spark test. If that ci test fails to compile then we've broken an expected jdk constraint.
As a side-effect, …
> feat(build): support jdk8 spark lineage

- docker/datahub-ingestion-base/Dockerfile
Required for SQL Server ingestion.
> feat(ingest): add ODBC library and tools to base image

- datahub-frontend/app/auth/AuthUtils.java
- datahub-frontend/app/auth/sso/oidc/OidcConfigs.java
- datahub-frontend/play.gradle
- datahub-frontend/test/security/OidcConfigurationTest.java
- metadata-models/src/main/pegasus/com/linkedin/settings/global/OidcSettings.pdl
- metadata-service/auth-servlet-impl/build.gradle
- metadata-service/auth-servlet-impl/src/main/java/com/datahub/auth/authentication/AuthServiceController.java
- metadata-service/auth-servlet-impl/src/test/java/com/datahub/auth/authentication/AuthServiceControllerTest.java
- metadata-service/auth-servlet-impl/src/test/java/com/datahub/auth/authentication/AuthServiceTestConfiguration.java
Due to a bug in `OidcConfigs`, the `preferredJwsAlgorithm` setting was never used when OIDC "dynamic" settings are set/enabled. Probably to workaround this bug, a change was made to use `auth.oidc.preferredJwsAlgorithm` from the application configuration (same as `AUTH_OIDC_PREFERRED_JWS_ALGORITHM` environment variable) if the `preferredJwsAlgorithm` setting was not specified in the OIDC dynamic settings - which is always the case due to the bug. This workaround also prevents us from simply using an existing `preferredJwsAlgorithm` setting as it could differ from an actually used configuration option which might have a different value - causing breakage to existing deployments.
This change introduces a new `preferredJwsAlgorithm2` field in the OIDC settings that is actually used if set. …
> fix(oidc settings): effective JWS algorithm setting

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/assertion/AssertionMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/Assertions.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionDescription.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionsList.tsx
- datahub-web-react/src/graphql/assertion.graphql
In this PR, I'm adding support for rendering a custom description for any assertion ingested into Datahub. This makes the model much more flexible to accommodate more custom needs. 
Simply fill in the "description" field of the AssertionInfo aspect and you'll see it take precedence over our auto-generated description:
Also made sure to support super long descriptions:
> feat(ui): Supporting rendering custom assertion descriptions

- datahub-web-react/src/App.tsx
- datahub-web-react/src/CustomThemeProvider.tsx
- datahub-web-react/src/customThemeContext.tsx
- adding new context object which allows children to update theme conf variables
> infra(ui): Add a react context provider allowing sub-components to update theme conf

- entity-registry/src/main/java/com/linkedin/metadata/models/ConfigEntitySpec.java
- entity-registry/src/main/java/com/linkedin/metadata/models/DefaultEntitySpec.java
- entity-registry/src/main/java/com/linkedin/metadata/models/EntitySpec.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AutocompleteRequestHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/query/ESAggregatedStatsDAO.java
- metadata-io/src/test/java/com/linkedin/metadata/search/fixtures/SampleDataFixtureTestBase.java
> fix(search): fix filters for hasX and numValues fields

- datahub-graphql-core/build.gradle
Removes requirement to list all graphql files by hand in the build file.
> build(graphql): simplify gradle graphql codegen task

- .github/workflows/metadata-ingestion.yml
- docs/cli.md
- docs/how/updating-datahub.md
- docs/quickstart.md
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/tests/unit/test_airflow.py
- metadata-ingestion/build.gradle
- metadata-ingestion/cli-ingestion.md
- metadata-ingestion/developing.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/__init__.py
- metadata-ingestion/src/datahub/ingestion/api/report.py
- metadata-ingestion/src/datahub/ingestion/source/feast.py
- metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
- metadata-ingestion/src/datahub/ingestion/source/mlflow.py
- metadata-ingestion/src/datahub/ingestion/source/schema_inference/object.py
- metadata-ingestion/tests/integration/feast/test_feast_repository.py
- metadata-ingestion/tests/integration/iceberg/test_iceberg.py
- metadata-ingestion/tests/integration/mlflow/test_mlflow_source.py
- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/unit/test_iceberg.py
- metadata-ingestion/tests/unit/test_mlflow_source.py
Targeting this for the 0.13.0 release.
> chore(cli): drop support for python 3.7

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
- metadata-ingestion/tests/integration/tableau/setup/publishedDatasourcesConnection_all.json
- metadata-ingestion/tests/integration/tableau/tableau_cll_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_extract_all_project_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_mces_golden_deleted_stateful.json
- metadata-ingestion/tests/integration/tableau/tableau_nested_project_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_signout_timeout_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_with_platform_instance_mces_golden.json
> feat(ingestion/tableau) Ingest tags from datasource

- datahub-frontend/build.gradle
Avoids yarnInstall when building docker image for datahub-frontend
> chore(gradle): datahub-frontend docker dependency avoid yarnInstall

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/test/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationCandidateSourceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/AggregationQueryBuilderTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/DomainsCandidateSourceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTagsCandidateSourceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTermsCandidateSourceFactory.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/DomainsCandidateSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopPlatformsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTagsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTermsSource.java
- metadata-service/services/src/main/java/com/linkedin/metadata/search/utils/QueryUtils.java
* Co-located aggregation functions in AggregationQueryBuilder
* Default list of entity specs for aggregation should include query by default field (at least 1)
* Improved error message for field Display Name collisions
If the PDL models include a facet field with a conflicting display name and those entities are being queried together, a much more readable message is displayed.
Roughly something like this
java.lang.IllegalStateException: Facet field collision on field `type`. Incompatible Display Name across entities. Multiple Display Names detected: {Type=[(anomaly,Type), (incident,Type)], Chart Type=[(chart,Chart Type)]}
> fix(search): fix default entities for aggregation filters

- metadata-ingestion/setup.py
Feast upstream has handled this since v0.30
https://github.com/feast-dev/feast/pull/3542
> chore(ingest/feast): drop redundant typeguard constraint

- metadata-ingestion/setup.py
There isn't a consistent way to do this for projects that start with a zero.  Circa 0.20 or so Feast was undergoing significant api churn. Since then it has been relatively stable.
> feat(ingestion/feast): loosen feast dependency

- .github/scripts/check_python_package.py
- .github/workflows/docker-unified.yml
- metadata-ingestion/src/datahub/cli/config_utils.py
> feat(ci): check for packages, change location of lint

- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
Add descriptions to elasticseach args
> docs(elastricsearch): add description fiels

- docs/managed-datahub/observe/column-assertions.md
- docs/managed-datahub/observe/custom-sql-assertions.md
- docs/managed-datahub/observe/freshness-assertions.md
- docs/managed-datahub/observe/volume-assertions.md
> docs(observe): add upsert assertion monitor graphql examples

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/chart/BrowseV2Resolver.java
- datahub-graphql-core/src/main/resources/search.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/browse/BrowseV2ResolverTest.java
- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/QueryConfiguration.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- metadata-service/services/src/main/java/com/linkedin/metadata/search/EntitySearchService.java
Fixes issue in some scenarios for exact match queries where aggregation counts did not match browse counts due to different query flows under certain configurations. Also updates structured query path with some of the custom query configuration logic to keep in alignment. NOTE: OSS users would likely not run into this unless using custom query config with simpleQuery set to false or setting exclusive to true for quoted exact match queries due to the default configurations.
> fix(browsev2): align browse and aggregate queries

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/WeaklyTypedAspectsResolver.java
- datahub-graphql-core/src/main/resources/entity.graphql
> feat(graphql): get raw aspects for assertions, allow aspectNames filter

- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/FormInfo/utils.ts
- datahub-web-react/src/app/entity/shared/entityForm/prompts/StructuredPropertyPrompt/MultiSelectInput.tsx
- datahub-web-react/src/app/entity/shared/entityForm/prompts/StructuredPropertyPrompt/MultipleStringInput.tsx
- datahub-web-react/src/app/entity/shared/entityForm/prompts/StructuredPropertyPrompt/NumberInput.tsx
- datahub-web-react/src/app/entity/shared/entityForm/prompts/StructuredPropertyPrompt/StructuredPropertyPrompt.tsx
- datahub-web-react/src/app/entity/shared/entityForm/prompts/StructuredPropertyPrompt/useStructuredPropertyPrompt.ts
- datahub-web-react/src/app/entity/shared/entityForm/prompts/usePromptCompletionInfo.ts
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/useGetEntitySchema.tsx
This PR introduces new styles for the submit button to have it be below the inputs and also introduces a "confirm" button when a prompt's metadata is already there but they haven't submitted it through the form. This is the bulk of the diff (specifically indenting a component).
This also fixes a bug where we wouldn't show the number zero in number inputs.
> fix(forms) Update styles of submit/confirm button and fix num input bug

- metadata-service/services/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopPlatformsSource.java
Tested this works by deploying DataHub locally, ingesting the default MCPs via: `datahub ingest mcps metadata-ingestion/examples/mce_files/bootstrap_mce.json` and great expectations does not show up as a top platform whereas before it did.
> feat(recommendations): Correct searchable entities for top platform

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> feat(ingest/dbt): speed up test result only ingestion

- docker/cassandra/docker-compose.cassandra.yml
- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose-without-neo4j.postgres.override.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.consumers-without-neo4j.yml
- docker/docker-compose.consumers.yml
- docker/docker-compose.override.yml
- docker/docker-compose.tools.yml
- docker/docker-compose.yml
- docker/ingestion/docker-compose.yml
- docker/mariadb/docker-compose.mariadb.yml
- docker/monitoring/docker-compose.monitoring.yml
- docker/mysql/docker-compose.mysql.yml
- docker/profiles/docker-compose.actions.yml
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/docker-compose.prerequisites.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.consumers-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.consumers.quickstart.yml
- docker/quickstart/docker-compose.monitoring.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- metadata-ingestion/src/datahub/cli/docker_cli.py
- smoke-test/tests/consistency_utils.py
Because we have `--remove-orphans` in the quickstart cli, this should be ok to use on existing quickstarts as well.
Related to https://github.com/datahub-project/datahub/pull/9808
> feat(quickstart): remove `container_name` from compose files

- metadata-ingestion/src/datahub/ingestion/source/openapi.py
- metadata-ingestion/src/datahub/ingestion/source/openapi_parser.py
I need to authenticate with a Bearer token to my APIs.
> feat(openapi): allow Bearer token

- docker/mysql-setup/init.sql
Instead of relying on the database's default charset and collation. Increases resilience to cases where the database might have been previously created with a different charset/collation.
> fix(mysql-setup): specify charset and collation when creating table

- metadata-models/src/main/pegasus/com/linkedin/form/FormPrompt.pdl
This PR default sets form prompts as not required so that users have to explicitly say what's required for a form to be complete.
> fix(forms) Set form prompts default not required

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/chart/ChartStatsSummaryResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardStatsSummaryResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dataset/DatasetStatsSummaryResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/dataset/DatasetUsageStatsResolver.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/dashboard/DashboardStatsSummaryTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/dataset/DatasetStatsSummaryResolverTest.java
- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClientCache.java
- metadata-service/restli-client/src/main/java/com/linkedin/usage/UsageClientCache.java
* remove parallel stream from cache loader
* remove duplicate cache in graphql stats resolvers
> refactor(graphql): consolidate cache for stats

- metadata-ingestion/src/datahub/api/entities/forms/forms.py
For now, prevent any schema field prompts from being required. This could change later.
> fix(forms) Prevent schema field prompts from being required

- datahub-web-react/src/app/settings/AccessTokens.tsx
> fix(ui/token): token page failing to render

- metadata-ingestion/src/datahub/cli/check_cli.py
- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/source_report/ingestion_stage.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
These take advantage of `stacklevel`, which is supported in Python 3.8+.
> feat(ingest): reporting logging tweaks

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
Opted for the simpler fix here since we're likely refactoring how Filters are constructed soon anyway. The core issue here is that in ResolverUtils we append ".keyword" blindly and then on ESUtils we're doing manual fixup in spots where we don't need it using the toFacetField method. This logic is intertwined in large swathes of code so makes sense to fix it up in a larger refactor rather than a bug fix.
> fix(search): fix inequality filters for count fields

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/redash.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
This is a quick follow up on https://github.com/datahub-project/datahub/pull/9835
We can do the bigger removal of these methods incrementally / later. I just want the log lines to show up correctly for now.
> feat(ingest): clean up reporting methods

- metadata-ingestion/src/datahub/ingestion/source/dynamodb/dynamodb.py
- metadata-ingestion/tests/integration/dynamodb/dynamodb_default_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dynamodb/dynamodb_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dynamodb/test_dynamodb.py
This PR implements flattening the `map` attribute type when scanning table items for DynamoDB ingestion. The majority of expanding nested field code logic is adopted from
`metadata-ingestion/src/datahub/ingestion/source/schema_inference/object.py`, where it recursively calls `append_schema` for `map` data type field and constructs the field path delimited by `FIELD_DELIMITER`.
According to data types supported in DynamoDB in aws [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes), `List` and `Map` type both support recursive structure and since it would add more complexity for expanding list or list of maps, for now we'll only expand `Map` type and will handle expanding list in the future.
This PR also adopts a …
> feat(ingest/dynamoDB): flatten struct fields

- metadata-ingestion/src/datahub/ingestion/source/redash.py
Addressing the problem described in #9575
For large Redash deployments, the `filtered` and `timing` fields can grow to be very large. By using the LossyList and LossyDict data structures in a similar way as used in other SourceReports, we will limit the number of lines printed during an ingestion run which makes the logs more usable and improves performance for ingestion against Redash deployments with a large number of queries filtered.
Closes #9575
> fix(ingest/redash): Limit size of RedashSourceReport

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchAcrossLineageResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-service/configuration/src/main/resources/application.yml
- smoke-test/tests/lineage/test_lineage.py
> fix(lineage): logging reduction and fixes

- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_aggregate_operations.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_basic_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_column_lineage_deduplication.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_known_lineage_mapping.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_overlapping_inserts.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_temp_table.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_view_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/test_sql_aggregator.py
> feat(ingest): add escape hatch methods to SqlParsingAggregator

- docs/cli.md
Saw some confusion from users of this. It's unclear since `datahub ingest -c` will use the sink in the recipe, but `ingest deploy` will prefer the sink of the CLI.
> docs(ingest): document remote for ingest deploy

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/tests/integration/mongodb/mongodb_mces_small_schema_size_golden.json
- metadata-ingestion/tests/integration/mongodb/test_mongodb.py
When downsampling the collection schema, we would like to further improve the sorting:
1. first sort by `count` in descending order, higher count represent a larger portion of the schema
2. when fields share with same `count`, sort by `delimited_name` in ascending alphabetical order
Test case also added with a small `maxSchemaSize` to make sure the test output is consistent and ingested fields are in alphabetical order
> feat(ingest/mongodb): improve sorting when downsampling collection schema

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/9269.
> feat(ingest/snowflake): speed up snowflake usage query

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/policy/ListPoliciesResolver.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillPolicyFieldsConfig.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/SystemUpdateConfig.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/SystemUpdate.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/entity/steps/BackfillPolicyFields.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/entity/steps/BackfillPolicyFieldsStep.java
- metadata-models/src/main/pegasus/com/linkedin/policy/DataHubPolicyInfo.pdl
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyFetcher.java
- metadata-service/configuration/src/main/resources/application.yml
Adds searchable annotations to DataHubPolicyInfo fields: `privilege`, `type`, `status` and `editable` fields so that we can use these fields for filtering in graphQL queries + a filter parameter when listing policies. 
For backfilling pre-existing policies, adds a system update step to RESTATE existing policies. This is enabled by default so the mae processor updates documents in ES for all pre-existing DataHub policies.
Tested it works by checking elasticsearch directly to see new properties are available:
And that using the graphQL command I am able to filter by the new features:
> feat(policies): Make policies searchable by privilege, type, status or editable fields

- metadata-ingestion/src/datahub/emitter/mcp_patch_builder.py
- metadata-ingestion/src/datahub/specific/chart.py
- metadata-ingestion/src/datahub/specific/dashboard.py
- metadata-ingestion/src/datahub/specific/datajob.py
- metadata-ingestion/src/datahub/specific/dataset.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
- metadata-ingestion/tests/unit/api/source_helpers/incremental_table_lineage_golden.json
- metadata-ingestion/tests/unit/patch/complex_dataset_patch.json
- metadata-ingestion/tests/unit/patch/test_patch_builder.py
> fix(ingest/patch): Adding proper json patch path quoting

- datahub-frontend/app/auth/AuthModule.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/hooks/OwnerTypeMapTest.java
- metadata-auth/auth-api/src/main/java/com/datahub/plugins/auth/authorization/Authorizer.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESAccessControlUtil.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/search/SearchGraphServiceTestBase.java
- metadata-io/src/test/java/com/linkedin/metadata/search/utils/ESAccessControlUtilTest.java
- metadata-operation-context/build.gradle
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/ActorContext.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/AuthorizerContext.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/OperationContext.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/SearchContext.java
- metadata-operation-context/src/main/java/io/datahubproject/test/metadata/context/TestOperationContexts.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/ActorContextTest.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/OperationContextTest.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/SearchContextTest.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/AuthorizerChain.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/elasticsearch/IndexConventionImpl.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/elasticsearch/IndexConventionImplTest.java
Adds unit tests with a few quality of life fixes around constructors, lists v. sets for repeatable tests, and constants.
> feat(search): search access controls unit tests

- .github/workflows/airflow-plugin.yml
- .github/workflows/build-and-test.yml
- .github/workflows/check-datahub-jars.yml
- .github/workflows/code-checks.yml
- .github/workflows/docker-ingestion-smoke.yml
- .github/workflows/docker-postgres-setup.yml
- .github/workflows/docker-unified.yml
- .github/workflows/documentation.yml
- .github/workflows/lint-actions.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-io.yml
- .github/workflows/metadata-model.yml
- .github/workflows/publish-datahub-jars.yml
- .github/workflows/qodana-scan.yml
- .github/workflows/spark-smoke-test.yml
https://github.com/acryldata/sane-checkout-action/commit/ceba7e47efaeb2b3b1124f4ad45d50f7d7fbe08e
Uses treeless clone to optimize checkout action while still getting full tag details and only pull PR changes instead of merging with main prior to building.
> fix(pr): make prs only pull changes from pr branch instead of head merge

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngineArgs.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/EntityLineageResultResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UrnToEntityMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/entitytype/EntityTypeMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/restricted/RestrictedMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/restricted/RestrictedType.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/buildEntityRegistry.ts
- datahub-web-react/src/app/entity/restricted/RestrictedEntity.tsx
- datahub-web-react/src/app/entity/restricted/RestrictedEntityProfile.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityName.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/PlatformContent/PlatformContentView.tsx
- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- datahub-web-react/src/graphql/lineage.graphql
- datahub-web-react/src/images/restricted.svg
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESAccessControlUtil.java
- metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/cache/CacheableSearcherTest.java
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/SearchContext.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/RestrictedServiceFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/RestrictedService.java
- metadata-service/services/src/test/java/com/linkedin/metadata/service/RestrictedServiceTest.java
This PR adds a new graphql entity type that will map back obfuscated entities to the UI. The main purpose of this right now is to allow us to restrict lineage nodes in our lineage graph.
Adds a check in the entity lineage resolver, which is used to populate this graph, to map back entities the user doesn't have view permissions on to a Restricted entity. This Restricted entity will also include encrypting the urn so that we don't give any relevant info to the user.
We can then decrypt this urn to make lineage requests and keep our graph full.
Screenshots:
> feat(lineage) Restrict lineage nodes in the lineage graph if user lacks view permissions

- metadata-ingestion/build.gradle
- metadata-ingestion/src/datahub/emitter/mcp_patch_builder.py
- metadata-ingestion/src/datahub/specific/chart.py
- metadata-ingestion/src/datahub/specific/custom_properties.py
- metadata-ingestion/src/datahub/specific/dashboard.py
- metadata-ingestion/src/datahub/specific/datajob.py
- metadata-ingestion/src/datahub/specific/dataproduct.py
- metadata-ingestion/src/datahub/specific/dataset.py
- metadata-ingestion/src/datahub/specific/ownership.py
- metadata-ingestion/src/datahub/specific/structured_properties.py
Passing a tuple to `_add_patch` does this automatically. I only modified a few instances to use the tuple form - we can do the cleanup later.
> feat(ingest/patch): add helper for auto-quoting

- .github/actions/ci-optimization/action.yml
- .github/workflows/docker-unified.yml
> feat(ci): skip smoke-test lint if there are no changes

- metadata-ingestion/scripts/avro_codegen.py
> feat(ingest): throw codegen error on duplicate class names

- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-ingestion/Dockerfile
- docker/datahub-ingestion/Dockerfile-slim-only
> feat(docker): respect pip mirrors with uv

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_helper.py
- metadata-ingestion/tests/integration/bigquery_v2/bigquery_mcp_golden.json
- metadata-ingestion/tests/unit/test_bigqueryv2_usage_source.py
> fix(ingest/bigquery): escape special characters for table descriptions

- datahub-web-react/src/app/entity/shared/tabs/Dataset/AccessManagement/AccessManagement.tsx
> feat(ui): add loading spin to access management table

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
> fix(ingestion/fivetran): Fix fivetran get connector jobs bug

- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Adds CLL support for target platform nodes and dbt source nodes.
> feat(ingest/dbt): generate CLL for all node types

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
- metadata-service/configuration/src/main/resources/application.yml
Allows for configuring reprocessing of UI Sourced events. This allows users to replay UI events asynchronously if they occur during an ingestion pipeline run or other non UI based ingestion.
> feat(config): add configuration to reprocess UI sourced events

- entity-registry/src/main/java/com/linkedin/metadata/models/registry/PluginEntityRegistryLoader.java
- entity-registry/src/test/java/com/linkedin/metadata/models/registry/PluginEntityRegistryLoaderTest.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/EntityRegistryPluginConfiguration.java
- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityregistry/PluginEntityRegistryFactory.java
- metadata-service/openapi-entity-servlet/src/test/java/io/datahubproject/openapi/config/OpenAPIEntityTestConfiguration.java
Runnable was running every 5 seconds with no way to configure it, reduced default execution rate to every minute and added config
> feat(pluginRegistry): add configuration to reduce runnable frequency

- .github/workflows/documentation.yml
- docs-website/docusaurus.config.js
Possibly a regression from https://github.com/datahub-project/datahub/pull/9937 
This fixes the massive huge build times that we were seeing in CI.
Debugging in https://github.com/hsheth2/datahub/pull/4
> feat(docs): disable last update timestamps

- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
> fix(ingest/redshift): fix stl scan lineage for lineage v2

- metadata-ingestion/src/datahub/ingestion/source/redshift/config.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
Also uses the old usage generator for now, since we aren't getting select queries in the lineage code flow.
> feat(ingest/redshift): make query generation configurable

- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
The [rollover](https://opensearch.org/docs/latest/im-plugin/ism/policies/#rollover) operation rolls an alias over to a new index when the managed index meets **_one_** of the rollover conditions. Since the rollover conditions are `min_index_age: 1d` and `min_size: 5gb` conditions, the index ends up being rolled over every day since the minimum index age condition will evaluate to true.
Instead of time-based rollover, this changes the rollover condition to only be based on the minimum size.
> fix(opensearch): Rollover usage events at a file size rather than time-based manner

- docker/elasticsearch-setup/create-indices.sh
Previously the ISM policy was never updated if it already existed. Now the policy is updated whenever `elasticsearch-setup` runs and the policy already exists. The response of the update operation is saved to a temporary directory for debugging purposes.
> feat(opensearch): support for updating ISM policy used for usage events

- datahub-web-react/src/App.tsx
- datahub-web-react/src/AppConfigProvider.tsx
- datahub-web-react/src/CustomThemeProvider.tsx
- datahub-web-react/src/app/ProtectedRoutes.tsx
- datahub-web-react/src/app/Routes.tsx
- datahub-web-react/src/appConfigContext.tsx
This will allow loading the theme based on a local variable instead.
> refactor(react): Provide option to skip importing theme in CustomThemeProvider; rearrange toplevel components

- metadata-ingestion/src/datahub/ingestion/source/superset.py
> feat(ingest/superset): map awsathena platform name to athena

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/cli/specific/user_cli.py
- metadata-ingestion/src/datahub/configuration/source_common.py
- metadata-ingestion/src/datahub/emitter/mcp.py
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/api/workunit.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- Makes the DataHubGraph init method not call test_connection.
- Refactors some of the workunit id generation logic.
> feat(ingest): add DataHubGraph.emit_all method

- metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
- Adding support for PERIOD types
-  Using QryLogV and QryLogSqlV instead of DBQLogTbl and DBQLSqlTbl
- Disabling our optimized view definition extraction as it only works if the last ddl against the table was the create ddl
> fix(ingest/teradata): small teradata improvements

- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchSection.tsx
- datahub-web-react/src/app/entity/shared/tabs/Lineage/ImpactAnalysis.tsx
- datahub-web-react/src/app/entity/shared/tabs/Lineage/LineageTab.tsx
> fix(ui/lineage): show data is too large error when limitation exceeds

- build.gradle
- datahub-upgrade/build.gradle
- docker/kafka-setup/Dockerfile
- metadata-service/factories/build.gradle
Bump `aws-msk-iam-auth` to pick up new AWS SDK version dependency - `third-party-jackson-core` was previously excluded due to pulling an AWS SDK and respective `third-party-jackson-core` version which contained a vulnerability.
> chore(aws-msk-iam-auth): bump dependency version

- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
According to https://stackoverflow.com/questions/72770890/redshift-result-size-exceeds-listagg-limit-on-svl-statementtext Redshift limits strings to be 64k in length. Since `text` field in `SYS_QUERY_TEXT` table can have at most 4k characters and then is split into chunks ordered by `sequence` we can allow at most 16 (16*4 = 64) chunks to be included.
> fix(ingestion): Handle Redshift string length limit in Serverless mode

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/src/datahub/utilities/hive_schema_to_avro.py
- metadata-ingestion/tests/unit/utilities/test_hive_schema_to_avro.py
**Issue**:
When the Optional field `Type` of `PartintionKeys` (`PartitionKey["Type"]`) is missing of a Table, the glue connector is failing with below exception.
```
File "/datahub-ingestion/.local/lib/python3.10/site-packages/datahub/ingestion/source/aws/glue.py", line 1168, in get_schema_metadata
hive_column_type=partition_key["Type"],
KeyError: 'Type'
```
**Fix**: 
When the Optional`Type` field of `Partitionkey` is missing, we are mapping(avro schema mapping) the `unknown` Type with `null` Type for producing the MCE.
UI screenshot:
Additionally, adding a debug logger while extracting data from tables, which will help to debug any issue when connector failed to process data for a particular table.
> fix(metadata-ingestion)glue connector failure when Optional field Type of PartitionKey is absent for a Table

- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
- smoke-test/tests/structured_properties/test_structured_properties.py
Before this PR, this logic only allowed uploading structured properties, downstreams, tags, glossary terms, and owners to schema fields.
What this does:
1. Moves that out to be on a dataset-level
2. Keeps schema-level logic for attaching structured_properties, tags, terms
3. Cleans up a few unused functions
Tested locally.
In a follow up PR I'll clean this up so there's not a mix of camel case and snake case for some of these fields. That requires some modification of pdl files so I won't include in this PR.
> Clean up logic for dataset.py yaml loader

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> fix(ingest/dbt): fix config validator for skip_sources_in_lineage

- metadata-ingestion/tests/integration/sql_server/docker-compose.yml
- metadata-ingestion/tests/integration/sql_server/source_files/mssql_no_db_to_file.yml
- metadata-ingestion/tests/integration/sql_server/source_files/mssql_no_db_with_filter.yml
- metadata-ingestion/tests/integration/sql_server/source_files/mssql_to_file.yml
- metadata-ingestion/tests/integration/sql_server/source_files/mssql_with_lower_case_urn.yml
This currently causes test flakes. Example: https://github.com/datahub-project/datahub/actions/runs/8380098358/job/22948505013?pr=10101
```
E           Error response from daemon: driver failed programming external connectivity on endpoint testsqlserver (1d5c212229e8c26777f660620d74d31851808daa2de92df89e510eb0584f124e): Error starting userland proxy: listen tcp4 0.0.0.0:51433: bind: address already in use
```
> test(ingest/mssql): use non-ephemeral mapping port

- datahub-web-react/src/graphql/browseV2.graphql
- datahub-web-react/src/graphql/fragments.graphql
With the (new) browse paths v2 it is possible to have in theory any entity as part of the browse path by referencing it via its urn. Unfortunately the UI is currently not "requesting" the display name of the dataset entity as part of the browse path v2, therefore only the URN is shown.
Most of the time it makes no sense to have datasets as part of the browse path (e.g., if you think of SQL databases, most of the time you have databases or schemas, which are ingested as containers, but there is no entity "below" a dataset), but in case of SAP BW (we are still working on a source for it ;-)) it makes sense to also have a dataset as part of the browse path because of the special relationship between InfoProviders and Queries (Queries in SAP BW cannot be compared to SQL queries in SQL …
> fix(ui): show dataset display name in browse paths v2

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/MapperUtils.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/mappers/MapperUtilsTest.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/ValidationUtilsTest.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/EntityKeyUtilsTest.java
> test(urn): add test case

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldUsageStats.tsx
Adds a min-width to the usage stats in the schema field sidebar so we always see something even when the percentage is super small.
> fix(ui) Add min width to the usage stats component

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/BulkListener.java
Elasticsearch bulk execution logs currently always print `Took time ms` as `-1`:
```
INFO  c.l.m.s.e.update.BulkListener:51 - Successfully fed bulk request. Number of events: 5 Took time ms: -1
```
The problem is that the printed time is actually the bulk ingest preprocessing time, which is -1 if ingest is not enabled.
This change now logs how long bulk execution took. The bulk ingest preprocessing time is only logged if available.
```
INFO  c.l.m.s.e.update.BulkListener - Successfully fed bulk request. Number of events: 12 Took time ms: 542
```
> fix(elasticsearch logging): log how long bulk execution took

- datahub-upgrade/src/main/resources/logback.xml
- metadata-jobs/mae-consumer-job/src/main/resources/logback.xml
- metadata-jobs/mce-consumer-job/src/main/resources/logback.xml
- metadata-service/war/src/main/resources/logback.xml
See also #9745 for details - this PR simply provides the patterns for ignoring the log messages.
> fix: exclude Elasticsearch ignore_throttled warnings from log

- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MaeConsumerConfig.java
- metadata-jobs/mae-consumer-job/src/test/java/com/linkedin/metadata/kafka/MaeConsumerApplicationTest.java
> fix(mae-consumer): fix aspect retriever injections mae-consumer

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/AggregationQueryBuilderTest.java
Take into account the searchFlags max bucket when specified,
```java
int maxTermBuckets =
Math.min(
opContext.getSearchContext().getSearchFlags().getMaxAggValues(),
configs.getMaxTermBucketSize());
```
> fix(search): respect the search flags term bucket size

- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
> fix(ingestProposal): fix/handle no-op ingestion

- .github/workflows/documentation.yml
- docs-website/build.gradle
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/airflow-plugin/scripts/release.sh
- metadata-ingestion-modules/dagster-plugin/build.gradle
- metadata-ingestion-modules/dagster-plugin/scripts/release.sh
- metadata-ingestion/scripts/release.sh
- vercel.json
Also removes a dependency on git in the scripts
> fix(ci): simplify python release process

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
Similar to when ingesting lineage via GCP audit logs: 
https://github.com/datahub-project/datahub/blob/06ef2ad5def7eb1de5d0b19ca2154ddbf96e1692/metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py#L733-L742 
Currently, when using `extract_lineage_from_catalog=True` a request is issued for every table in the project.
> feat(ingest/bigquery): Respect dataset and table patterns when ingesting lineage via catalog api

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx
Move partition keys to the top of the schema table so that users can easily see all available partition keys on the table at first glance.
(Love the move to Vite folks! ❤️ )
> feat(ui): sort partition keys to the top of the table for better visibility

- .github/workflows/airflow-plugin.yml
- metadata-ingestion-modules/airflow-plugin/README.md
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
- metadata-ingestion-modules/airflow-plugin/tests/unit/test_airflow.py
- metadata-ingestion-modules/airflow-plugin/tests/unit/test_packaging.py
- metadata-ingestion-modules/airflow-plugin/tests/utils.py
- metadata-ingestion-modules/airflow-plugin/tox.ini
- metadata-ingestion/developing.md
Also changes the tests to use the Airflow constraints files for recent versions.
> feat(ingest): loosen airflow plugin dependencies requirements

- docker/postgres-setup/init.sql
> WITH [ NO ] DATA
This clause specifies whether or not the data produced by the query should be copied into the new table. If not, only the table structure is copied. The default is to copy the data.
The default behavior is bad because it copies all data which causes unnecessary load, especially if the table is large.
> fix(setup): fix postgres setup to create temp table with no data

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
> feat(ingest): bump sqlglot dep

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/RelationshipController.java
- metadata-service/services/src/main/java/com/linkedin/metadata/graph/Edge.java
> fix(openapi): fix index out of bounds for sort order

- .github/scripts/docker_helpers.sh
> Revert docker helper changes

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/BulkListener.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/ESBulkProcessor.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessor.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeLogProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
- metadata-jobs/pe-consumer/src/main/java/com/datahub/event/PlatformEventProcessor.java
- metadata-service/restli-servlet-impl/src/test/java/com/linkedin/metadata/resources/entity/AspectResourceTest.java
Currently consumer logs do not record any events processed, making it difficult to analyze, troubleshoot or gain insights from event processing. This change improves logging so that consumer logs record all events processed.
Additionally, the timer measuring how long `ingestAspectsToLocalDB` takes no longer includes time spent in `emitMCL`.
For reference, new log output for an MCL event:
```
INFO  c.l.m.k.MetadataChangeLogProcessor - Got MCL event key: urn:li:dataHubExecutionRequest:modeldoc-generated, topic: MetadataChangeLog_Versioned_v1, partition: 0, offset: 20613, value size: 64766, timestamp: 1711856258850
INFO  c.l.m.k.MetadataChangeLogProcessor - Invoking MCL hooks for urn: urn:li:dataHubExecutionRequest:modeldoc-generated, aspect name: dataHubExecutionRequestResult, entity type: …
```
> feat(metadata-jobs): improve consumer logging

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/vianodes/ReindexDataJobViaNodesCLLStep.java
- datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/DatahubUpgradeNonBlockingTest.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-jobs/mce-consumer-job/src/test/java/com/linkedin/metadata/kafka/MceConsumerApplicationTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/OperationsController.java
- metadata-service/restli-api/src/main/idl/com.linkedin.entity.aspects.restspec.json
- metadata-service/restli-api/src/main/idl/com.linkedin.operations.operations.restspec.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/operations/OperationsResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/operations/Utils.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/restoreindices/RestoreIndicesArgs.java
restoreIndices batchSize was being used as a limit instead of batchSize
added timestamp filters based on createdOn
> fix(restoreIndices): batchSize vs limit

- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
> feat(ingest/gc): add index truncation logic

- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraRetentionService.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanRetentionService.java
There was a bug when maxAgeInSeconds (Integer) is greater than Integer.MAX_VALUE / 1000 (about 24 days). For example, if maxAgeInSeconds = Integer.MAX_VALUE / 1000 + 1, then maxAgeInSeconds * 1000 = -2147483296, and therefore all previous versions will be deleted.
Another option to fix this is to change the type of maxAgeInSeconds into long:
https://github.com/datahub-project/datahub/blob/088e7a87d823a4776a80ebc5498a8edd47cc294f/metadata-models/src/main/pegasus/com/linkedin/retention/TimeBasedRetention.pdl#L6-L8
> fix(retention): fix time-based retention

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/EntityLineageResultResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/MapperUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/UrnSearchAcrossLineageResultsMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/main/resources/search.graphql
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/graph/LineageRelationship.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/LineageSearchEntity.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.lineage.relationships.snapshot.json
Gives additional information in lineage responses, whether a node was ignored as a hop as well as returning paths for an alternative flow.
> feat(lineage): give via and paths in entity lineage response

- docker/profiles/docker-compose.actions.yml
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/empty.env
> fix(dev): fix env file overrides for profiles

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
> fix(ingestion/hive): ignore sampling for tagged column/table

- datahub-web-react/src/app/entity/shared/tabs/Properties/StructuredPropertyValue.tsx
> fix(ui/property): add collapse for long dataset properties

- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/airflow-plugin/scripts/release.sh
- metadata-ingestion-modules/dagster-plugin/build.gradle
- metadata-ingestion-modules/dagster-plugin/scripts/release.sh
- metadata-ingestion/build.gradle
- metadata-ingestion/scripts/release.sh
> fix(build): avoid nested gradle commands

- metadata-ingestion/src/datahub/integrations/great_expectations/action.py
- metadata-ingestion/tests/unit/test_great_expectations_action.py
Closes #9810
**Describe the feature**
Adding the ability to publish metadata related to  [in-memory Data Assets](https://docs.greatexpectations.io/docs/oss/guides/connecting_to_your_data/fluent/in_memory/connect_in_memory_data/) . 
**Context**
Use it when the data Source is not implemented yet ( victoria metrics  , ..... ) .
**Expected behavior**
Assertion metadata are pushed to Datahub.
> feat(ingest/great_expectations): support in-memory (Pandas) data assets

- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
> fix(ingestion/mongodb): MongoDB source unable to parse datetimes with years > 9999  

- metadata-io/src/test/java/com/linkedin/metadata/search/fixtures/GoldenTestBase.java
- metadata-io/src/test/java/io/datahubproject/test/SearchRetry.java
> test(search): introduce retry for search test

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_audit.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_partitioned_table_insert.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(ingest/sql): normalize bigquery partitioned tables when parsing

- metadata-ingestion/docs/sources/datahub/datahub_pre.md
- metadata-ingestion/docs/sources/datahub/datahub_recipe.yml
- metadata-ingestion/src/datahub/ingestion/run/pipeline_config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/config.py
- metadata-ingestion/src/datahub/ingestion/source/datahub/datahub_source.py
> fix(ingestion/datahub): moved urn_pattern config to source config

- .github/workflows/docker-unified.yml
> fix(ci): unified workflow login logic

- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
- metadata-io/src/test/java/com/linkedin/metadata/search/LineageServiceTestBase.java
> fix(lineage): fix lighting cache dataJob platform

- metadata-ingestion/src/datahub/entrypoints.py
> docs(init): Update entrypoints.py to be more clear about acryl init

- datahub-web-react/src/app/ingest/source/executions/IngestionExecutionTable.tsx
- datahub-web-react/src/app/ingest/source/executions/IngestionSourceExecutionList.tsx
> feat(ui/ingestion): add pagination on ingestion executions

- metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl
Slack thread: https://datahubspace.slack.com/archives/CUMUWQU66/p1711845235044419
> fix(docs): update docs for SchemaField.label

- metadata-ingestion/src/datahub/entrypoints.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/utilities/_custom_package_loader.py
> feat(ingest): show custom model info

- metadata-ingestion/src/datahub/configuration/common.py
When dealing with large allow pattern lists get_allowed_list is extremely inefficient, because each allow pattern is validated against all other allow pattern - as we are already dealing with all allowed patterns in the list we don't have to validate them whether they are allowed, because they are...we only have to check whether they are denied or not.
Example: For a list of 2730 allow patterns up to 2730^2 resp. 7.452.900 unnecessary regular expression checks are performed.
This PR adds a new method "denied" to AllowDenyPattern which is used to filter the allow patterns in get_allowed_list.
Of course this logic only works in case the allow list is a fully specified allow list, but this is already checked/asserted* in get_allowed_list. It seems currently the get_allowed_list is not used …
> fix(ingest): improve performance of get_allowed_list in AllowDenyPattern when dealing with large lists

- datahub-frontend/app/auth/sso/oidc/OidcConfigs.java
- datahub-frontend/test/security/OidcConfigurationTest.java
The response from the `auth/getSsoSettings` endpoint uses the `preferredJwsAlgorithm` path.
> fix(oidc settings): use correct path for preferredJwsAlgorithm

- datahub-web-react/src/graphql/search.graphql
We recently had some changes into what we're querying that caused clashing in a query where we were querying `parent` on schema fields twice in search results. I updated the queries to remove this clashing, so now everything should work as expected.
> Cc  fix broken cll impact analysis

- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_config.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_plugin_v22.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/lineage/_lineage_core.py
> feat(ingest/airflow): support disabling iolet materialization

- metadata-ingestion/src/datahub/ingestion/source/sigma/config.py
- metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
- metadata-ingestion/src/datahub/ingestion/source/superset.py
Closes https://github.com/datahub-project/datahub/issues/10298
> feat(ingest/sigma): fix stateful ingestion

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
This bug would cause incorrect numbers for the null percentages and distinct percentages. Because of some subtle caching, we would use the full table's row count instead of the sample's row count.
> fix(ingest/profiling): compute sample row count correctly

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
This moves us from issuing one unique count query per column to one per table.
> feat(ingest/profiling): allow unique count queries to be combined

- metadata-ingestion/docs/sources/kafka/kafka.md
> fix(ingest/kafka): clarify meta-mapping docs

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_max_with_schema.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_default_normalization.json
Related to https://github.com/datahub-project/datahub/issues/10184
> feat(ingest): bump acryl-sqlglot dep

- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
- metadata-ingestion/tests/integration/salesforce/mock_files/account_fields_soql_response.json
- metadata-ingestion/tests/integration/salesforce/salesforce_mces_golden.json
> fix(ingestion/salesforce): escape markdown char for multiline description

- metadata-io/src/main/java/com/linkedin/metadata/service/BusinessAttributeUpdateHookService.java
- metadata-jobs/pe-consumer/build.gradle
- metadata-jobs/pe-consumer/src/main/java/com/datahub/event/hook/BusinessAttributeUpdateHook.java
- metadata-jobs/pe-consumer/src/test/java/com/datahub/event/hook/BusinessAttributeUpdateHookTest.java
- metadata-service/configuration/src/main/resources/application.yaml
Fix the mae consumer when in standalone mode with platform event consumer enabled.
* Refactor BusinessAttributeService/Hook to use `UpdateIndicesService` instead of `EntityService` allowing execution in standalone consumer mode.
* Removed default configuration with 100,000 limit ES query to avoid performance issues
* Implemented pagination for ES query
* Converted to the GraphRetriever client. (Updated test for pagination test)
* Added page/batch size configuration option (`BUSINESS_ATTRIBUTE_RELATED_ENTITIES_BATCH_SIZE`)
* Converted MCL producer to write directly to Elasticsearch rather then emit additional MCLs
> fix(mae): fix mae standalone platform consumer

- docker/datahub-ingestion-base/Dockerfile
* override default venv cacerts
> docker(ingestion-base): set certificate location for python

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetMetadataAnalyticsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/service/AnalyticsUtil.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/util/DateUtil.java
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserStatus.pdl
- smoke-test/tests/cypress/cypress/e2e/analytics/analytics.js
In this PR, we add 2 basic charts to analytics tabs:
1. New Users -> New Users in the past month.
2. Top Users -> Users who are the most active on DataHub in the past month 
This includes their name, title, and email for reference.
> feat(ui): Adding new analytics charts for new users, top users past month

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
> feat(ingest/mssql): improve docs on using odbc

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
This only takes effect when using `dbt compile` instead of `dbt docs generate`. We recommend using the latter.
> feat(ingest/dbt): use columns from manifest as a fallback

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_utils.py
- metadata-ingestion/tests/unit/test_sql_utils.py
> fix(ingest/profiling): Filter tables early based on profile pattern filter

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AggregateAcrossEntitiesResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchAcrossEntitiesResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchUtils.java
This PR fixes a problem that occurs with legacy views where they explicitly defined entity types in a different field and we intersected that with `types` provided by the user. This then determines which indexes we search through. If the intersection between these two is empty, we should return no results. We default add all SEARCHABLE_ENTITY_TYPES if `types` is empty from the API input, so if the intersection is empty, it truly should be an empty search.
> fix(graphql) Fix entity type filter clash with legacy filters

- README.md
- docs-website/src/pages/_components/CardCTAs/index.js
- docs-website/src/pages/_components/Hero/index.js
- docs-website/src/pages/index.js
- docs/act-on-metadata/impact-analysis.md
- docs/api/tutorials/lineage.md
- docs/architecture/architecture.md
- docs/dataproducts.md
- docs/features.md
- docs/features/feature-guides/ui-lineage.md
- docs/managed-datahub/managed-datahub-overview.md
- docs/roadmap.md
- docs/townhall-history.md
- metadata-ingestion/scripts/docgen.py
> feat: add keywords for SEO

- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
- metadata-service/war/src/main/resources/logback.xml
- Log GraphQL requests received and being executed
- Log GraphQL queries to a separate debug log file
- Log duration and result size of executed requests
```
2024-05-01 05:14:59,354 [qtp752848266-28] INFO  c.datahub.graphql.GraphQLController:120 - Processing request, operation: getQuickFilters, actor urn: urn:li:corpuser:datahub
2024-05-01 05:14:59,355 [ForkJoinPool.commonPool-worker-6] INFO  c.datahub.graphql.GraphQLController:125 - Executing operation getQuickFilters for qtp752848266-28
2024-05-01 05:14:59,406 [ForkJoinPool.commonPool-worker-6] INFO  c.datahub.graphql.GraphQLController:148 - Executed operation getQuickFilters in 50 ms
2024-05-01 05:14:59,407 [ForkJoinPool.commonPool-worker-6] INFO  c.datahub.graphql.GraphQLController:153 - Operation getQuickFilters execution result …
```
> feat(graphql): Improve logging of GraphQL requests

- docs/api/datahub-apis.md
We have a graphql example and should link it from this table.
> docs(apis): Update datahub-apis.md to add link to search example

- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/SpringQueryContext.java
GraphQL operation name is an optional field only required if multiple operations are present. If not present, use query name for logging.
> feat(graphql): log query name if operation name is not provided

- docs/how/updating-datahub.md
- metadata-ingestion/docs/sources/dynamodb/dynamodb_pre.md
- metadata-ingestion/docs/sources/dynamodb/dynamodb_recipe.yml
- metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
- metadata-ingestion/src/datahub/ingestion/source/dynamodb/dynamodb.py
- metadata-ingestion/tests/integration/dynamodb/test_dynamodb.py
> DynamoDB IAM auth

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/transformer/dataset_transformer.py
- metadata-ingestion/src/datahub/ingestion/transformer/pattern_cleanup_dataset_usage_user.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> fix(ingestion/transformer): new transformer to clean user URN for DatasetUsageStatistics aspect

- datahub-web-react/src/app/entity/shared/entityForm/Form.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/editor/Editor.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/editor/EditorTheme.tsx
This PR adds support for rich text in form descriptions so users can add links, images, all that good stuff right underneath the form title. If they supply normal text we display that same as usual as well.
> feat(ui) Support rich text for form descriptions

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/ReindexDataJobViaNodesCLLConfig.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/AbstractMCLStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/vianodes/ReindexDataJobViaNodesCLL.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/vianodes/ReindexDataJobViaNodesCLLStep.java
- datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/DatahubUpgradeNonBlockingTest.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/restoreindices/RestoreIndicesArgs.java
> feat(upgrade): common base for mcl upgrades

- docker/profiles/docker-compose.actions.yml
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/empty.env
- docker/profiles/empty2.env
Fixes support with newer versions of docker compose, which throw an error with our existing setup.
> fix(docker): use distinct empty env files

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
> feat(ingest/snowflake): use system sampling on very large tables

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
> feat(cli): cache sql parsing intermediates

- docs/managed-datahub/datahub-api/entity-events-api.md
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/EditableSchemaMetadataChangeEventGenerator.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/event/EntityChangeEventGeneratorHookTest.java
> fix(changeEvents): add description-parameter to the change-event of a schemaField-description

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> fix(ingestion/airflow-plugin): warning log for non-materialized iolets

- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
- metadata-ingestion/tests/integration/salesforce/mock_files/account_fields_soql_response.json
- metadata-ingestion/tests/integration/salesforce/salesforce_mces_golden.json
> fix(ingestion/salesforce): handle the label with none value scenario

- metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java
datahub-project/datahub#10290 removed `com.linkedin.metadata.service` and `com.datahub.event` from GMS' component scan but these are required in order to instantiate `com.datahub.event.PlatformEventProcessor` when `PE_CONSUMER_ENABLED` is set to `true` for GMS.
> fix(metadata-service): add PE processor to component scan

- .github/workflows/airflow-plugin.yml
- docker/datahub-ingestion-base/base-requirements.txt
- metadata-ingestion-modules/airflow-plugin/setup.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> fix(ingestion/airflow-plugin): bumping up the openlineage-airflow version

- docs/how/updating-datahub.md
- metadata-ingestion/docs/sources/dynamodb/dynamodb_pre.md
`aws_session_token` is still optional and only required when using temporary credentials.
> fix(docs): adjust new requirements for DynamoDB ingestion

- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/report.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
> feat(ingest/redshift): add timers for lineage v2

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/structuredproperty/StructuredPropertyMapper.java
- datahub-graphql-core/src/main/resources/properties.graphql
- datahub-web-react/src/app/entity/shared/tabs/Properties/Edit/EditColumn.tsx
- datahub-web-react/src/graphql/fragments.graphql
- entity-registry/src/main/java/com/linkedin/metadata/aspect/validation/StructuredPropertiesValidator.java
- entity-registry/src/test/java/com/linkedin/metadata/aspect/validators/StructuredPropertiesValidatorTest.java
- entity-registry/src/test/java/com/linkedin/test/metadata/aspect/batch/TestMCP.java
- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
- metadata-models/src/main/pegasus/com/linkedin/structured/StructuredPropertyDefinition.pdl
- metadata-models/src/main/resources/entity-registry.yml
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
> feat(structured-properties): immutable flag

- docker/docker-compose.dev.yml
- docker/profiles/docker-compose.gms.yml
Mounting is required in order to support dev workflows that use cached images.
> fix(docker): mount newly added jetty-jmx.xml

- docs/api/tutorials/lineage.md
We previously only showed a table-level impact analysis query. I've been asked questions about this from Datahub users who thought there was no way to programmatically access column lineage.
> docs(impact analysis): Add column level impact analysis graphql example

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
> fix(openapi-v3): comprehensive aspect name casing fix

- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> feat(ingest/slack): Support profile ingestion using users:info

- docs/developers.md
Although Windows is not officially supported (only via WSL), it seems I am not the only one who came across the described issue (see the description in the commit and/or the links below), therefore it might be worth including a section in the developer's guide how to fix the issue.
Fixes https://github.com/datahub-project/datahub/issues/10078
https://datahubspace.slack.com/archives/CV2KB471C/p1694618702396499
https://datahubspace.slack.com/archives/C06E4EMMQDR/p1707229403758969
https://datahubspace.slack.com/archives/CV2KB471C/p1712783867963919
https://datahubspace.slack.com/archives/CV2KB471C/p1713691688337789
https://datahubspace.slack.com/archives/C029A3M079U/p1713775766452869
https://datahubspace.slack.com/archives/C029A3M079U/p1715218311540369
> docs(developers): add section regarding symbolic links on Windows 10/11 to developer's guide

- metadata-ingestion/src/datahub/ingestion/source/sql/hive_metastore.py
- metadata-ingestion/src/datahub/testing/compare_metadata_json.py
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_1.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_2.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_3.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_4.json
- metadata-ingestion/tests/integration/hive-metastore/hive_metastore_mces_golden_5.json
- metadata-ingestion/tests/integration/hive-metastore/test_hive_metastore.py
- metadata-ingestion/tests/test_helpers/mce_helpers.py
> chore(ingest/presto-on-hive) Set enable_properties_merge to True by default

- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_extractors.py
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1715147183172729?thread_ts=1712847298.005519&cid=CUMUWQU66
> feat(ingest/airflow): support BigQueryInsertJobOperator

- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ChangeItemImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
> fix(mcp): fix mcp key aspect

- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/tests/unit/api/source_helpers/test_incremental_lineage_helper.py
- metadata-ingestion/tests/unit/api/source_helpers/test_incremental_lineage_pass_through.json
Fixes a bug introduced by https://github.com/datahub-project/datahub/pull/10090
This bug would cause all non-lineage aspects to disappear when `incremental_lineage` was enabled. Incremental lineage should be considered broken for all versions after v0.13.1.3rc2 that don't include this fix.
> fix(ingest): fix bug in incremental lineage

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
> Wrap non-required $ref properties in an object to mark as nullable

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
- Remove conflicting `operationId`
- SystemMetadata aspect is modeled as an object, rather than a single text field
- Fix incorrect default values
> OpenAPI v3 Spec bug fixes:

- datahub-graphql-core/src/main/resources/entity.graphql
- metadata-models/src/main/pegasus/com/linkedin/assertion/AssertionInfo.pdl
Fixes: https://github.com/datahub-project/datahub/issues/10456
> fix(assertions) aligned graphql AssertionType definition with the AssertionType defined in metadata-models

- smoke-test/requirements.txt
Requests version `2.32.0` breaks Docker client.
> fix(smoke-test): pin requests to 2.31.0

- li-utils/src/main/javaPegasus/com/linkedin/common/urn/UrnUtils.java
Instead of using a statically mapped string -> enum conversion, just use the `Enum.valueOf` when converting from String -> FabricType
> consider all values of FabricType enum in DatasetUrn util

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/tests/integration/powerbi/golden_test_cll.json
This is mostly a refactor. The main change is lowercasing the fake ephemeral names and fixing a minor bug in the lineage generator.
> fix(ingest/dbt): resolve more dbt ephemeral node lineage gaps

- datahub-web-react/src/app/entity/view/menu/ViewDropdownMenu.tsx
There was a bug where we weren't showing the option to delete a personal view from the manage views page in settings because we aren't passing in whether the user is an owner or not. Well, this is determined on whether or not this view is a personal view, so we can default set that value and the problem is solved.
> fix(ui) Fix preventing users from deleting personal views

- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/unity/test_unity_catalog_ingest.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
> fix(ingest/unity-catalog) upstream lineage for hive_metastore external table with s3 location

- metadata-ingestion/src/datahub/configuration/source_common.py
> fix(ingest): Remove env deprecation message

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_extractors.py
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator.json
- metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
- metadata-ingestion-modules/airflow-plugin/tox.ini
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/api/report.py
- metadata-ingestion/src/datahub/sql_parsing/_models.py
- metadata-ingestion/src/datahub/sql_parsing/query_types.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_multiple_select_subqueries.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_select_with_complex_ctes.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_sqlite_insert_into_values.json
- metadata-ingestion/tests/unit/sql_parsing/test_sql_aggregator.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> test(ingest/sql): refactor CLL generator + add tests

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/assertion/AssertionMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/assertion/AssertionType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/incident/IncidentMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/incident/IncidentType.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/main/resources/incident.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/incident/IncidentMapperTest.java
- datahub-web-react/src/graphql/assertion.graphql
- datahub-web-react/src/graphql/incident.graphql
- metadata-models/src/main/resources/entity-registry.yml
This will enable us to find assertions and incidents by tags applied via API!
> feat(graphql): Support tagging incidents and assertions via GraphQL API 

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/MeResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/test/ListTestsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/test/TestUtils.java
- datahub-graphql-core/src/main/resources/app.graphql
- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/graphql/me.graphql
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
> feat(auth): add viewTests platform privilege

- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/common.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/job_classes.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/jobs.py
- metadata-ingestion/tests/unit/sagemaker/sagemaker_mces_golden.json
- metadata-ingestion/tests/unit/test_sagemaker_source_stubs.py
This PR has the following improvements:
1. remove deprecated APIs: Amazon Sagemaker Edge retired on April 26th, 2024, so the calls to any edge packaging-related jobs will fail with errors: https://docs.aws.amazon.com/sagemaker/latest/dg/edge-eol.html, we should clean up all edge packaging related code
2. according to https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeAutoMLJobV2.html, DescribeAutoMLJobV2 are the new versions of CreateAutoMLJob and DescribeAutoMLJob which offer backward compatibility, the PR updates this API call to use this newer API
3. adds stateful ingestion capability to SageMaker ingestion
> feat(ingestion/SageMaker): Remove deprecated apis and add stateful ingestion capability

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
When the forceIndexing property is set to true, the UpdateIndicesHook should never ignore an event...the current logic is causing missing entities in the search index when using the restore indices job...
See here on Slack for details: https://datahubspace.slack.com/archives/C029A3M079U/p1716563376088529?thread_ts=1715145976.054479&cid=C029A3M079U
> fix(mae-consumer): fix UpdateIndicesHook ignoring events with forceIndexing property set to true

- entity-registry/src/main/java/com/linkedin/metadata/models/SearchableRefFieldSpecExtractor.java
- entity-registry/src/main/java/com/linkedin/metadata/models/annotation/SearchableRefAnnotation.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchQueryBuilderTest.java
> fix(search): implement queryByDefault annotation for SearchableRef

- metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
> feat(neo4j): improve neo4j read query performance by specifying labels

- metadata-ingestion/src/datahub/configuration/connection_resolver.py
- metadata-ingestion/src/datahub/ingestion/api/global_context.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/graph/connections.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
- metadata-ingestion/tests/unit/config/test_connection_resolver.py
~Stacked on top of https://github.com/datahub-project/datahub/pull/10504~
> feat(ingest): fetch connections from the backend

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_test_model_performance_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
> fix(ingest/dbt): only generate one subtype

- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
> fix(ingest): move status aspect fixer logic

- build.gradle
- metadata-dao-impl/kafka-producer/build.gradle
- metadata-dao-impl/kafka-producer/src/main/java/com/datahub/metadata/dao/producer/KafkaProducerThrottle.java
- metadata-dao-impl/kafka-producer/src/test/java/com/datahub/metadata/dao/producer/KafkaProducerThrottleTest.java
- metadata-jobs/mce-consumer/build.gradle
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/MetadataChangeProposalConfig.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/ConfigurationProvider.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/DataHubKafkaProducerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/KafkaEventConsumerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/SimpleKafkaConsumerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/throttle/KafkaProducerThrottleFactory.java
- metadata-service/schema-registry-servlet/src/test/java/io/datahubproject/openapi/test/SchemaRegistryControllerTestConfiguration.java
> feat(consumers): mce-consumer throttling based on mae-consumer lag

- metadata-models/src/main/pegasus/com/linkedin/settings/global/GlobalViewsSettings.pdl
- metadata-service/services/src/main/java/com/linkedin/metadata/service/ViewService.java
Adds relationship annotation to `GlobalViewsSettings`'s `defaultView` property & executes referential delete in `ViewService`. 
This is to delete by reference modification when deleting Views that were assigned as the default.
> fix(views): Add relationship annotation to GlobalViewsSettings urn

- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
> feat(ingest): measure sink bottlenecking

- metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/service/BusinessAttributeUpdateHookService.java
- metadata-jobs/pe-consumer/src/test/java/com/datahub/event/hook/BusinessAttributeUpdateHookTest.java
- metadata-service/configuration/src/main/resources/application.yaml
> feat(businessAttribute): parallelize-business-attribute-propagation

- metadata-ingestion/docs/sources/athena/athena_pre.md
Policy copy-and-paste is not working properly because of the trailing comma in the example.
> docs(ingest): remove trailing comma on athena permission

- docs/managed-datahub/subscription-and-notification.md
Preview here: https://docs-website-git-jp-assertion-subs-docs-acryldata.vercel.app/docs/managed-datahub/subscription-and-notification#subscribing-to-individual-assertions
> docs(subscriptions): adding docs for assertion level subscriptions on managed DH

- metadata-ingestion/src/datahub/entrypoints.py
- metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_utils.py
This should improve snowflake lineage perf.
> feat(ingest): add fast query fingerprinting

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
> fix(ingest/trino): variable reference before define

- metadata-ingestion/src/datahub/ingestion/source/qlik_sense/config.py
- metadata-ingestion/src/datahub/ingestion/source/qlik_sense/data_classes.py
- metadata-ingestion/src/datahub/ingestion/source/qlik_sense/qlik_api.py
> fix(ingest/qlik): improve logging for debug

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
Enum in `openapi` should be modeled as `type: "string"`, not "object"
> Use type: string for enum schemas

- docs/lineage/airflow.md
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> fix(ingestion/airflow-plugin): airflow remove old tasks

- metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
The Azure AD ingestion goes into an infinite loop if a request returns a response code other than 200. This changes the request to retry up to 5 times and only for retriable error codes.
> fix(azure_ad): fix infinite loop on request error
