- backend-service/app/actors/CmdUtil.java
- backend-service/app/actors/EtlJobActor.java
- hadoop-dataset-extractor-standalone/src/main/java/wherehows/SchemaFetch.java
- metadata-etl/src/main/java/metadata/etl/EtlJob.java
- metadata-etl/src/main/java/metadata/etl/dataset/hive/HiveViewDependency.java
- metadata-etl/src/main/resources/jython/AvroColumnParser.py
- metadata-etl/src/main/resources/jython/HdfsTransform.py
- metadata-etl/src/main/resources/jython/HiveColumnParser.py
- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
- metadata-etl/src/main/resources/jython/HiveTransform.py
- metadata-etl/src/main/resources/log4j.properties
- metadata-etl/src/test/java/metadata/etl/LaunchJython.java
- metadata-etl/src/test/java/metadata/etl/dataset/hive/AvroColumnParserTest.java
- metadata-etl/src/test/java/metadata/etl/dataset/hive/HiveColumnParserTest.java
- metadata-etl/src/test/resources/jython-test/AvroColumnParserTest.py
- metadata-etl/src/test/resources/jython-test/HiveColumnParserTest.py
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldRecord.java
* Fix bug of process hanging:
- Reason is the process stdout and stderr need to be consumed, otherwise when buffer full, it will hanging there.
* Add Hive field ETL process
- Hive schema get from two different source, COLUMN_V2 and SERDE_PARAM. Two schemas are totally different.
- SERDE_PARAM : Schema is avro schema. We can reuse the schema parse procedure in HDFS transform steps. So I reorganize HDFS transform steps to separate them out, for the ease of reuse.
- COLUMN_V2 : Get type from table and construct the schema by ourself. But the 'type' is nested. see here: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types. Thanks for @ericsun2 help, and leverage his script to parse it out.
> Fix process hanging bug. Add hive field ETL process.

- web/public/javascripts/routers/datasets.js
- web/public/javascripts/routers/search.js
After search, in order to highlight the search keyword, we need change the schema content.
We need to reset the schema content to original before Ember go to detail page.
> fix the invalid json error for schema

- backend-service/app/models/daos/CfgDao.java
- data-model/DDL/ETL_DDL/dataset_metadata.sql
- data-model/DDL/ETL_DDL/etl_configure_tables.sql
- metadata-etl/src/main/resources/jython/HdfsLoad.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
- metadata-etl/src/main/resources/jython/TeradataLoad.py
- metadata-etl/src/test/java/metadata/etl/LaunchJython.java
- metadata-etl/src/test/java/metadata/etl/dataset/hdfs/HdfsMetadataEtlTest.java
- metadata-etl/src/test/java/metadata/etl/dataset/hive/AvroColumnParserTest.java
- metadata-etl/src/test/java/metadata/etl/dataset/hive/HiveColumnParserTest.java
- metadata-etl/src/test/java/metadata/etl/dataset/hive/HiveTest.java
- metadata-etl/src/test/resources/jython-test/AvroColumnParserTest.py
- metadata-etl/src/test/resources/jython-test/HiveColumnParserTest.py
* Add license header of last commit
* Add field comments ETL process
* `dict_dataset_field_comment` is the mapping table store which field contain which comments
* `dict_field_detail` have the field info
* `field_comments` have the comments info
* the ETL process is 
1. raw info load into `stg_dict_field_detail` first, insert into `field_comments` and `dict_field_detail`
2. delete old record of `stg_dict_dataset_field_comment` based on db_id
3. insert into `stg_dict_dataset_field_comment` 
4. compare and insert into final table
* if the field already have a default comment, insert ignore the new comment with default set to 0
* if the field doesn't have this comments before, insert ignore the new comment with default set to 1. ( notice if we already insert this record in the first step, …
> Add field comments ETL

- data-model/DDL/ETL_DDL/dataset_metadata.sql
- metadata-etl/src/main/resources/jython/HdfsLoad.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
- metadata-etl/src/main/resources/jython/TeradataExtract.py
- metadata-etl/src/main/resources/jython/TeradataLoad.py
- wherehows-common/src/main/java/wherehows/common/Constant.java
* Change dict_dataset, dict_field_detail table engine to InnoDB. We always found the front end is blocking when there is some backend job loading in these tables. This is because MyISAM will optimize some query to table lock in some situation. For now the easier way is change database engine from MyISAM to InnoDB. InnoDB have better support for concurrency. 
* As we change to InnoDB, we need to set `innodb_lock_wait_timeout` to a higher value as some query will exceed the default timeout of a transaction.
* Add an option configuration that can skip Teradata sample data ETL. Default is doing the ETL.
> Innodb engine DDL. Add config for timeout and load sample.

- README.md
…rather than git.  A contributor would probably want the git: link, but someone just trying the software out won't want to have to do so from a computer with a github auth on it.
> To avoid requiring the user to be logged into github, use https:

- backend-service/app/actors/SchedulerActor.java
- backend-service/app/shared/Global.java
- backend-service/conf/application.conf
- metadata-etl/src/main/java/metadata/etl/lineage/AzExecMessage.java
- metadata-etl/src/main/java/metadata/etl/lineage/AzLineageExtractorMaster.java
- metadata-etl/src/main/java/metadata/etl/lineage/AzLineageMetadataEtl.java
- metadata-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java
- metadata-etl/src/test/java/metadata/etl/lineage/AzLineageExtractorTest.java
- metadata-etl/src/test/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractorTest.java
* Add optional `scheduler.jobid.whitelist` configuration. So we can specify a white list of jobs this instance will schedule. In this way we can have several instances running.
If config file does not have this variable, every job that is scheduled will execute. Otherwise will only executed the jobs whose id is in this list.
* HadoopNameNodeExtractor --> HadoopJobHistoryNodeExtractor. Correct name.
* Clean up deprecated function.
> Add optional config of ETL job white list

- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
1. The field list fetched from COLUMN_V2 table need to be ordered by 'IntegerIndex'.
2. Using dataset_id in staging table to optimize the ETL performance.
3. Remove all "analyze table" statements, as they will introduce blocking.   [reference link](https://www.percona.com/blog/2013/02/27/mysql-optimizer-analyze-table-and-waiting-for-table-flush/)
4. Adjust ETL order to optimize performance
> Fix hive field ETL bug

- data-model/DDL/ETL_DDL/executor_metadata.sql
Hello,
after last changes DDLs support MySQL 5.7.x, thanks a lot! Unfortunately, tables `job_execution_ext_reference` and `stg_job_execition_ext_reference` still having problems:
`ERROR 1171 (42000) at line 441 in file: 'ETL_DDL/executor_metadata.sql': All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`
and
`ERROR 1171 (42000) at line 470 in file: 'ETL_DDL/executor_metadata.sql': All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`.
I'm understand that this NULLs in definition should be removed or changed to NOT NULL. This PR assumes that it can be removed (this works with MySQL 5.7.10). If that is not the case please let me know to change. 
Kind regards,
Rafal Kluszczynski
> update DDL for job_execution_ext_reference tables for mysql 5.7.x

- metadata-etl/src/main/resources/jython/DatasetTreeBuilder.py
- metadata-etl/src/main/resources/jython/FlowTreeBuilder.py
Hello, 
after adding ES support for search, Jython scripts building trees have been broken. Here is the fix and also if url or port for ES is not configured in *wh_property* table, pushing data to ES is skipped (our case at the moment).
Could you review this PR?
Kind regards,
Rafal Kluszczynski
> Fixing tree builder scripts when ES is not used

- backend-service/app/controllers/DatasetController.java
- backend-service/app/models/daos/DatasetDao.java
- backend-service/build.gradle
- backend-service/conf/routes
- backend-service/test/controllers/DatasetControllerTest.java
- metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
- metadata-etl/src/main/resources/jython/HiveExtract.py
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetDependencyRecord.java
2 options for input:
option 1:
- Input: 2 parameters
1. cluster name (optional): such as ltx1-holdem, lva1-war, lva1-tarock, ltx1-holdem is the default value provided in application config
2. dataset uri in 1 of 3 formats:
-    db_name.table_name
-    hive:///db_name/table_name
-    dalids:///db_name.table_name
option 2
-    Input: 1 parameter
1. dataset uri in 
-   cluster_name:db_name.table_name
-   hive://cluster_name/db_name/table_name
-   dalids://cluster_name/db_name.table_name
Output:
```
{
deployment_tier: string (gird/corp/prod/*),
data_center: string (ltx1/lva1/lsg1/lca1/*),
cluster: string (ltx1-holdem/lva1-war/lva1-tarock/ltx1-uno/*),
dataset_type: string (dalids/hive/teradata/...),
database_name: string (search_mp/tracking/feed_mp_versioned/...),
table_name: string …
```
> provide the dataset dependency api

- metadata-etl/src/main/resources/jython/HiveLoad.py
- metadata-etl/src/main/resources/jython/HiveTransform.py
- wherehows-common/src/main/java/wherehows/common/schemas/HiveDependencyInstanceRecord.java
When update cfg_object_name_map table, the duplicated key exception raised since the t_deleted_depend table does not include all records
> update dependency property name and fix the duplicated key issue

- web/app/controllers/api/v1/Dataset.java
- web/app/dao/DatasetsDAO.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetSchemaRecord.java
Currently, the table cfg_object_name_map stores the dependencies for all versions of a dataset, before only store the latest version of a dataset
> update the get relations code since info stored by version instead of dataset

- backend-service/build.gradle
- build.gradle
- hadoop-dataset-extractor-standalone/build.gradle
- hadoop-dataset-extractor-standalone/src/main/java/wherehows/SchemaFetch.java
- metadata-etl/build.gradle
- metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java
- metadata-etl/src/main/resources/jython/HdfsLoad.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
- "schemaFetch.jar' can randomly hang due the issue described in http://dhruba.name/2012/10/16/java-pitfall-how-to-prevent-runtime-getruntime-exec-from-hanging
Need to switch to ProcessBuilder.redirectErrorStream(true) later. Temporarly discard the log from getRuntime().exec() 
- exclude log4j from the build
> temp fix for hdfs_schema_crawler getRuntime().exec() hangs problem

- backend-service/app/models/utils/Urn.java
- backend-service/build.sbt
- metadata-etl/build.gradle
- metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java
- metadata-etl/src/main/resources/jython/HdfsLoad.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
schemaFetch.jar will generate log file along side with the output temp metadata file (which is defined in wh_etl_job_property under the name "hdfs.local.raw_metadata"). 
If hdfs.local.raw_metadata is set to /my_data/hdfs/abc.json, the log file will be /my_data/hdfs/abc.json.log
> Use ProcessBuilder and redirected log file for HDFS Extract

- web/app/controllers/api/v1/Dataset.java
- web/app/dao/DatasetsDAO.java
- web/app/models/DatasetAccessItem.java
- web/app/models/DatasetAccessibility.java
- web/app/models/DatasetPartition.java
- web/app/views/index.scala.html
- web/conf/routes
- web/public/javascripts/components/components.js
- web/public/javascripts/routers/datasets.js
- web/test/ControllersTest.java
Display Operational metadata from 2 metadata event/stream sources (Gobblin and Hive Metastore) for datasets:
- cluster
- operation (publish full, publish delta, publish daily, publish hourly, add partition, modify external table...)
- partition type/grain
- partition name/expression
- partition data time
- num of records
- time of log event
The UI typically takes dataset_id as the input first, and find all its instances (across multiple clusters), then retrieve the most recent load status, and display them as pivot table.
> implement the dataset accessiblities section

- web/app/views/index.scala.html
- web/public/javascripts/components/components.js
- web/public/javascripts/components/schema-comment.js
- web/public/javascripts/main.js
- web/public/javascripts/routers/datasets.js
After upgrade the ember to 2.6, the component can't call the parent action directly
> fix the issue that action getSchema did not fired

- backend-service/app/models/daos/DatasetInfoDao.java
- backend-service/app/utils/MetadataChangeProcessor.java
- data-model/DDL/ETL_DDL/dataset_info_metadata.sql
- data-model/DDL/ETL_DDL/dataset_metadata.sql
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetConstraintRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldIndexRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldPathRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldSchemaRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetGeographicAffinityRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetLocaleRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionKeyRecord.java
The MatadataChangeEvent processor checks for the changed items and calls the corresponding APIs with the Event avro record transferred JSON. 
If there are several change event including schema change, the schema change will be called first, since it can possibly insert new dataset so the other changes can use this dataset id.
> Add MatadataChangeEvent processor to call seperate APIs

- backend-service/app/actors/EtlJobActor.java
- backend-service/app/models/daos/EtlJobDao.java
- data-model/DDL/ETL_DDL/etl_configure_tables.sql
- metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java
- metadata-etl/src/main/resources/jython/HdfsLoad.py
1. Modify HdfsLoad job to improve speed on some tasks
2. Add exec_id info in HdfsLoad job logging
3. Add host_name and process_id in wh_etl_job_execution table to provide better execution tracking of ETL jobs.
> Modify HdfsLoad to improve speed, Add process_id and hostname to wh_etl_job_execution

- data-model/DDL/readme.MD
Currently, when copying the recommended command from the README, MySQL throws a missing database error.
> Add Database to create_tables readme

- backend-service/app/controllers/DatasetInfoController.java
- backend-service/app/models/daos/DatasetInfoDao.java
- data-model/DDL/ETL_DDL/dataset_info_metadata.sql
- wherehows-common/src/main/java/wherehows/common/schemas/AbstractRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetCapacityRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetCaseSensitiveRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetChangeAuditStamp.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetConstraintRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetDeploymentRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldIndexRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldPathRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldSchemaRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetIndexRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetInventoryItemRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetInventoryPropertiesRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetOwnerRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionKeyRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetReferenceRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetSchemaInfoRecord.java
- wherehows-common/src/main/java/wherehows/common/schemas/DatasetTagRecord.java
- wherehows-common/src/main/java/wherehows/common/utils/StringUtil.java
backend APIs related to MetadataChangeEvent will cast the Mysql query results Map<String, Object> to corresponding Java Record, then serialize the record to Json and send to REST reply. This way, the post and get Json format is consistent. 
This is for better debugging and easier frontend usage. 
Also correct the multiple escape characters in return Json string issue.
> Update backend APIs to cast SQL results back to Java record then to Json

- backend-service/app/actors/KafkaConsumerWorker.java
- metadata-etl/src/main/java/metadata/etl/kafka/GobblinTrackingCompactionProcessor.java
- metadata-etl/src/main/java/metadata/etl/kafka/GobblinTrackingDistcpNgProcessor.java
- metadata-etl/src/main/java/metadata/etl/kafka/GobblinTrackingLumosProcessor.java
- metadata-etl/src/main/java/metadata/etl/kafka/KafkaConsumerProcessor.java
- metadata-etl/src/main/java/metadata/etl/kafka/MetastoreAuditProcessor.java
- wherehows-common/src/main/java/wherehows/common/kafka/serializers/AbstractKafkaAvroDeserializer.java
- wherehows-common/src/main/java/wherehows/common/kafka/serializers/KafkaAvroDeserializer.java
1. Update casting of Gobblin metadata field from Object to Map<String, String>. Instead of force cast, now iterate through the Map<Object, Object> and cast each one to String. This correct many deserialization errors. 
2. Improve debug information if client can't fetch schema from Registery (may due to lack of schemaId). Exception now contains topic name and first 40 bytes of message.
> Update Kafka processor casting Object to String

- backend-service/app/actors/KafkaConsumerMaster.java
- backend-service/app/actors/KafkaConsumerWorker.java
- backend-service/app/controllers/DatasetController.java
- backend-service/app/controllers/DatasetInfoController.java
- backend-service/app/controllers/LineageController.java
- backend-service/app/models/daos/DatasetInfoDao.java
- backend-service/app/models/daos/LineageDao.java
- backend-service/app/models/kafka/GobblinTrackingAuditProcessor.java
- backend-service/app/models/kafka/GobblinTrackingCompactionProcessor.java
- backend-service/app/models/kafka/GobblinTrackingDistcpNgProcessor.java
- backend-service/app/models/kafka/GobblinTrackingLumosProcessor.java
- backend-service/app/models/kafka/KafkaConfig.java
- backend-service/app/models/kafka/KafkaConsumerProcessor.java
- backend-service/app/models/kafka/MetadataChangeProcessor.java
- backend-service/app/models/kafka/MetadataInventoryProcessor.java
- backend-service/app/models/kafka/MetastoreAuditProcessor.java
- backend-service/app/msgs/KafkaCommMsg.java
- backend-service/app/msgs/KafkaResponseMsg.java
- backend-service/app/utils/Urn.java
- build.gradle
- wherehows-common/src/main/java/wherehows/common/utils/StringUtil.java
1. Move database writing from KafkaConsumerMaster to KafkaConsumerWorker. Eliminate record passing from worker to master, increase database writing speed (each worker writing independently to different table), and resolved the Out-of-memory exception at Kafka system start-up. The reason being that the workers will process another message after a DB writing, instead of keeping processing and throwing records into Master message queue, which, at start-up, can eat up memory rapidly. 
2. Refactor/move some Kafka processors to the same models.kafka package under backend-service.
3. Turned off the population of OldInfo and NewInfo in MetastoreAuditProcessor due to storage concern.
4. Create generic KafkaCommMsg for communication between Kafka Master and Worker in futurn use.
5. Move some string …
> Update Kafka consumer actors to reduce memory usage

- backend-service/app/actors/KafkaConsumerMaster.java
- data-model/DDL/WEB_DDL/users.sql
- web/app/dao/UserDAO.java
- web/app/security/AuthenticationManager.java
- web/conf/application.conf
1. Web login authentication now supports multiple LDAP servers configurations as '|' separated strings. AuthenticationManager will iterate through all LDAP servers until one success or have tried all servers.
2. Each user login attempt (Success or failure) will now be inserted to user_login_history table.
> Login authentication support multiple LDAP servers, add login history

- build.gradle
- hadoop-dataset-extractor-standalone/src/main/java/wherehows/SchemaFetch.java
- metadata-etl/build.gradle
- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/SchemaUrlHelper.py
- wherehows-common/src/main/java/wherehows/common/Constant.java
Some Avro datasets have schema url only, we need to visit schema url in one of the 3 options:
* full hdfs uri, such as hdfs://server:port/path/path
* hdfs path only, such as /path/path
* http or https uri, such as http://server:port/api/schema_name
> Add get_schema_literal_from_url() to fetch schema literal based on schema url

- web/app/views/index.scala.html
- web/app/views/main.scala.html
- web/public/javascripts/components/components.js
- web/public/javascripts/controllers/datasets.js
- web/public/javascripts/routers/datasets.js
- web/public/javascripts/search.js
- web/public/stylesheets/wherehows.css
*DSS-5677: Refactors matching field feature for typeahead on DatasetComplianceComponent and DatasetConfidentialComponent components. Will render all possible results before search input is recieved on component
*DSS-5677: Adds ability to create a new PrivacyCompliancePolicy and SecuritySpecification from the client UI. Also fixes issue with matching fields and data type properties on schema with inconsistent shapes
*DSS-5677: Changes component from block syntax to inline. Add property for creating a new PrivacyCompliancePolicy and SecuritySpecification for datasets without either
> WhereHows UI: display empty "create" UI form for Privacy Compliance and Confidential Spec

- web/app/controllers/api/v1/ScriptFinder.java
Use URLDecoder to decode the query option string before parsing as Json.
> ScriptFinder Controller add URL decoding for Json fields

- metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
The static boosting score default value should be set as 1, as it will be used to product with other values. If set as 0, then the result will be always 0, which ends with wrong ranking.
> change default value for static boosting score to 1

- backend-service/app/actors/EtlJobActor.java
- metadata-etl/src/main/java/metadata/etl/EtlJob.java
- metadata-etl/src/main/java/metadata/etl/Launcher.java
- metadata-etl/src/main/resources/jython/AzkabanExtract.py
- metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
If ETL jobs fails within short time after start, and the Error message is of ImportError or IndexError (args), then the etljob actor will retry the job at most 2 more times. 
Those initialization error will have return status code 2 instead of 1.
> Add retry for ETL jobs failed at initialization

- metadata-etl/src/main/resources/jython/CodeSearchExtract.py
Add exception handling for this ETL job to avoid job failures, and catch the problematic returned JSON for further analysis
> Add exception handling for code search job

- web/public/javascripts/components/components.js
- web/public/javascripts/routers/datasets.js
DSS-6198: Fixes issue with nested fields not getting rendered in the schema for compliance and confidential tabs
DSS-6197: Adds default value for classification property on security
specification if not defined
> DSS-6197 & DSS-6198 Fixes render issues with compliance confidential tabs and field values

- backend-service/build.gradle
- backend-service/build.sbt
- backend-service/project/plugins.sbt
- backend-service/test/controllers/DatasetControllerTest.java
- build.gradle
- metadata-etl/build.gradle
- metadata-etl/src/test/java/metadata/etl/lineage/AzDbCommunicatorTest.java
- metadata-etl/src/test/java/metadata/etl/lineage/AzJobCheckerTest.java
- metadata-etl/src/test/java/metadata/etl/lineage/AzLineageExtractorTest.java
- metadata-etl/src/test/java/metadata/etl/lineage/AzLogParserTest.java
- metadata-etl/src/test/java/metadata/etl/lineage/AzServerCommunicatorTest.java
- web/build.gradle
- web/build.sbt
- web/project/plugins.sbt
- web/test/IntegrationTest.java
- wherehows-common/src/test/java/LineageCombinerTest.java
Run gradlew playCoverage for web & backend and the HTML report is generated under target/scala-2.10/jacoco/html
Run gradlew jacocoTestReport for wherehows-common & metadata-etl and the HTML report is generated under build/reports/jacoco/test/html, **if all tests pass**, which is not the case for metadata-etl currently.
> Generate code coverage reports

- metadata-etl/src/main/resources/jython/EspressoTransform.py
The combined_schema.keySchema will not need the "key:" prefix for Espresso
> only add "key:" prefix to fields[] but not to combined_schema

- data-model/DDL/ETL_DDL/dataset_info_metadata.sql
- data-model/DDL/ETL_DDL/kafka_tracking.sql
These columns cannot be NULL in order to create the tables in MySQL 5.7 as they are part of the tables' primary keys.    Updated the DDL to make them NOT NULL.
> myql57_pk_not_null - primary key columns must be not null

- data-model/DDL/ETL_DDL/git_metadata.sql
Each entity now contains  identifierField and logicalType, similar to compliance. Previously it's only a field path.
> Modify Confidential info schema to add identifierField and logicalType

- data-model/DDL/ETL_DDL/git_metadata.sql
- metadata-etl/src/main/resources/jython/HdfsLoad.py
- metadata-etl/src/main/resources/jython/HiveLoad.py
- metadata-etl/src/main/resources/jython/OracleExtract.py
- metadata-etl/src/main/resources/jython/OracleLoad.py
- metadata-etl/src/main/resources/jython/TeradataLoad.py
- Use NULL-safe equal to operator <=> when comparing dateset field parent_path, which can be null. 
- Refactor some SQL code
> Fix null comparison in SQL, refactor some queries

- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/HiveTransform.py
- web/app/security/AuthenticationManager.java
For Hive extract:
- Fix Hive extract json.dumps Out Of Memory issue by writing to file line by line.
- Catch exception in writing to CSV file : 'unescaped char'
For frontend authentication:
- differentiate AuthenticationException with CommunicationException
- add more logging
> Fix Hive Extract job file writing issues, add more authentication log

- data-model/ELASTICSEARCH/index_mapping.json
- metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
- web/app/dao/SearchDAO.java
- web/app/utils/Search.java
In this check in, 
1, Updated ES custom analyzers with whitespace tokenizer and word delimiter filter
For the fields of dataset name, metric name, flow name and job name
2, Adopted Elastic search completion suggester which is optimized for speed. This also eliminates the access to mySQL in DAO for auto complete. In addition, this also lays the foundation for future scoring of type aheads. For all datasets/metrics/flows
> Elastic search completion suggester for type ahead

- backend-service/app/actors/ConfigUtil.java
- backend-service/app/actors/EtlJobActor.java
- backend-service/application.env.template
- backend-service/conf/application.conf
- backend-service/conf/etl_logback.xml
- backend-service/test/actors/ConfigUtilTest.java
See https://logback.qos.ch/manual/configuration.html#variableSubstitution for more details.
> Allow the logback directory for ETL jobs to be overridden using system property

- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/HiveTransform.py
Closed the previous pull request, recreated a clean repo, and retested on Holdem
Retrieve source modification time for hive and dalids and clean up some code in Hive job.
The test was run against Db34, on Holdem. To check results, you can log in and see the field updated for datasets. Next step is to integrate with UI to display this info and filter/sort by this info.
> retrieve source modification time for hive and dalids

- metadata-etl/src/main/java/metadata/etl/dataset/hive/HiveMetadataEtl.java
- metadata-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java
- metadata-etl/src/main/resources/jython/HiveExtract.py
- metadata-etl/src/main/resources/jython/SchemaUrlHelper.py
- wherehows-common/src/main/java/wherehows/common/Constant.java
This requires setting the additional krb5.kdc & krb5.realm job properties.
> Fix Kerberos authentication so that HIVE_DATASET_METADATA_ETL jobs can run in non-grid cluster

- metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
I got a following exception when use Elasticsearch.
`KeyError: static_boosting_score`
```
[ERROR] [05/15/2017 06:21:33.455] [WhereHowsETLService-akka.actor.default-dispatcher-65] [akka://WhereHowsETLService/user/TreeBuilderActor] null
File "<iostream>", line 95, in <module>
File "<iostream>", line 90, in saveTreeInElasticSearchIfApplicable
File "__pyclasspath__/jython/ElasticSearchIndex.py", line 223, in update_dataset
KeyError: static_boosting_score
at org.python.core.Py.KeyError(Py.java:249)
at org.python.core.PyObject.__getitem__(PyObject.java:738)
at jython.ElasticSearchIndex$py.update_dataset$7(__pyclasspath__/jython/ElasticSearchIndex.py:248)
at jython.ElasticSearchIndex$py.call_function(__pyclasspath__/jython/ElasticSearchIndex.py)
at …
```
> Fix KeyError: static_boosting_score

- wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java
Temporariliy disable the broken updateKafkaDatasetOwner call.
Add extra blacklist pattern.
> Actually write properties to dict_dataset table

- wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java
Also treat "_" as a word boundary.
> Filter out HDFS datasets with "temporary" in path name.

- docker/mysql/copy-ddl.sh
This script is failed when it's executed outside the mysql directory.
Change the destination so that the file is copied correctly.
Thank you.
> Fix copy-ddl.sh about file destination.

- wherehows-backend/app/actors/ActorRegistry.java
- wherehows-backend/app/actors/SchedulerActor.java
- wherehows-backend/conf/application.conf
Instead simply schedule an entry and wait for its time to come.
> Do not automatically kick off all jobs that yet have an entry in wh_etl_job_schedule table.

- metadata-etl/src/main/resources/jython/OracleExtract.py
- metadata-etl/src/main/resources/jython/OracleLoad.py
global name 'schema' is not defined (#457) is fixed
> fix:Change global name 'schema' is not defined (#457)

- wherehows-common/src/main/java/wherehows/common/utils/StringUtil.java
Temporary fix on legacy code. Tested on one kafka message.
Should not manually generate string for saving to DB at the first place.
> Fix DBstring Util to handle Java Boolean type

- wherehows-dao/src/main/java/wherehows/models/User.java
This causes the frontend to crash at start up, due the UserSetting field not mapped to any column.
> Mark transient field for hibernate to fix mapping issue

- gradle/scripts/dependency.gradle
Edit dependency.gradle to pull in org.apache.hive:hive-exec:1.2.1:core for hive_exec
> Changing hive_exec dependency to :core

- wherehows-kafka/src/main/java/wherehows/main/ApplicationStart.java
decided to remove the CFG cluster info since the related processor is not being used right now. It blocks the application start in dev.
> remove unused DB call from ApplicationStart

- wherehows-data-model/ELASTICSEARCH/index_mapping.json
Introduced customized keyword analyzer 
- To support URN search
- Less irrelevant Name field search result. 
- If Name field still uses standard analyzer, URN search score is always lower 
- If both use not_analyzed, we lose scoring 
- If making other fields such as schema/properties using keyword analyzer, then query performs drops 10X more
- The keyword analyzer basically make search non-case sensitive, but do not tokenize as much as standard analyzer
> introduce customized analyzer for wherehows es index

- wherehows-web/app/components/dataset-compliance.js
- wherehows-web/app/styles/components/dataset-compliance/_compliance-container.scss
- wherehows-web/app/styles/components/dataset-compliance/_compliance-table.scss
- wherehows-web/app/styles/components/nacho/_nacho-select.scss
- wherehows-web/app/templates/datasets/dataset-compliance/-dataset-classification.hbs
- wherehows-web/app/templates/datasets/dataset-compliance/-dataset-compliance-entities.hbs
dataset classification edit modes. adds reset edit mode function to reset the aforementioned flags to initial state of false. renames isShowingAllMemberData to shouldShowAllMemberData. hides seeMore/Less button in edit mode. adds derived indicator value for datasets marked as excluding member data
adds the option to view less dataset level fields
adds empty state for dataset level fields. increases classification column width and creates --pre-wrap modifier for select component to wrap text.
>  adds explicit flags on compliance component for compliance policy and

- wherehows-etl/src/main/resources/jython/ElasticSearchIndex.py
The dataset and metric bulk insert fails on some because the params[] are not set correctly, during code reformat. Fixed the bug.
> fix a  bug in ETL

- wherehows-backend/build.gradle
- wherehows-backend/jobs/templates/ELASTIC_SEARCH_ETL.job
- wherehows-common/src/main/java/wherehows/common/Constant.java
- wherehows-data-model/ELASTICSEARCH/index_mapping.json
- wherehows-etl/src/main/resources/jython/ElasticSearchIndex.py
* Support elastic search auto-re-index
* Use alias switch to achieve zero down time. 
* If it is first time index created or alias does not exist yet, create new alias for the first time
* The job will be schedule running ever 12hrs, so our search data can be kept up-to-date. In the past, this was manually done every few weeks
* The index alias name can be defined in elastic search ETL job configuration file
* The index mapping data model changes for 5.5
* The index mapping file location needs to be specified in job configuration file via env variables
> support elasticsearch auto re-index with zero downtime via alias switch

- wherehows-etl/src/main/resources/jython/ElasticSearchIndex.py
Fix a bug in ETL. 
The current ETL in prod is temporarily disabled. Until this is deployed.
> need to use new index name in reindex

- wherehows-data-model/ELASTICSEARCH/auto_completion_query_template.json
- wherehows-data-model/ELASTICSEARCH/comment_query_template.json
- wherehows-data-model/ELASTICSEARCH/dataset_query_template.json
- wherehows-data-model/ELASTICSEARCH/filter_unit.json
- wherehows-data-model/ELASTICSEARCH/flow_query_template.json
- wherehows-data-model/ELASTICSEARCH/metric_query_template.json
- wherehows-data-model/ELASTICSEARCH/suggester_query_template.json
- wherehows-frontend/app/utils/Search.java
* Remove error prone string concat for query template
* Use ObjectNode/ArrayNode to build query template instead
* remove unnecessary empty spaces in the old query
* new query is compared using text comparision
* Regression test on dataset, flows, metrics, filters, auto complete are all tested in local:9001
> refacoring elastic search query template by building json objects

- wherehows-etl/src/main/resources/jython/OozieExtract.py
Changing from int to str since the OozieFlowScheduleRecord class itself is already expecting a str.
```public class OozieFlowScheduleRecord extends AzkabanFlowScheduleRecord {
public OozieFlowScheduleRecord(Integer appId, String flowPath, String frequency, Integer interval,
String cronExpression, Long effectiveStartTime, Long effectiveEndTime, String refId, Long whExecId) {
super(appId, flowPath, frequency, interval, cronExpression, effectiveStartTime, effectiveEndTime, refId, whExecId);
}
}
```
This is causing issue: https://github.com/linkedin/WhereHows/issues/903
> Changing from int to str

- wherehows-web/app/components/dataset-compliance-row.ts
- wherehows-web/app/components/dataset-compliance.js
- wherehows-web/app/constants/dataset-compliance.ts
- wherehows-web/app/constants/datasets/compliance.ts
- wherehows-web/app/routes/datasets/dataset.js
- wherehows-web/app/templates/datasets/dataset-compliance/-dataset-compliance-entities.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
- wherehows-web/app/typings/api/datasets/compliance.d.ts
- wherehows-web/app/typings/api/list/compliance-datatypes.d.ts
- wherehows-web/app/utils/api/list/compliance-datatypes.ts
- wherehows-web/mirage/config.ts
- wherehows-web/mirage/fixtures/compliance-data-types.ts
- wherehows-web/mirage/helpers/config.ts
- wherehows-web/mirage/models/compliance-data-types.js
- wherehows-web/mirage/scenarios/default.js
- wherehows-web/tests/unit/constants/dataset-compliance-test.js
- wherehows-web/tests/unit/utils/api/list/compliance-datatypes-test.js
tatypes type definitions to the list directory.
- implements getFildIdentifierOptions to extract dropdown options from complianceDataTypes list returned from GET /complianceDataTypes endpoint. adds unit tests. adds mirage mock for complianceDataTypes response and fixtures.
>  adds a reader for compliance data types. moves the list compliance da

- wherehows-web/app/components/dataset-compliance-row.ts
- wherehows-web/app/components/dataset-compliance.js
- wherehows-web/app/constants/datasets/compliance.ts
- wherehows-web/app/constants/metadata-acquisition.ts
- wherehows-web/app/styles/components/nacho/_nacho-select.scss
- wherehows-web/app/templates/datasets/dataset-compliance/-dataset-compliance-entities.hbs
- wherehows-web/app/utils/array.ts
- wherehows-web/tests/unit/utils/datasets/metadata-acquisition-test.js
- removes obsolete tests. updates compliance table to render all user updatable compliance info in single column
- removes unused import in test: metadata-acquisition
>  transitions to complianceDataTypes mid tier api for default security classification

- wherehows-web/app/components/dataset-authors.ts
- wherehows-web/app/utils/api/datasets/owners.ts
- wherehows-web/mirage/fixtures/owners.ts
Match mapping on frontend with mapping on backend as `DataOnwer` instead of `Owner`. Check for confirmed owners using `@each.type` to rerun check when type is changed by user, not just when owners are added or removed. 
Testing done:
`just ember test` results:
```
ok 1 Chrome 65.0 - ESLint | mirage: mirage/factories/access.js
ok 2 Chrome 65.0 - ESLint | mirage: mirage/factories/column.js
...
ok 347 Chrome 65.0 - Unit | Utility | validators/urn: buildLiUrn
ok 348 Chrome 65.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
1..348
```
> fix ownership checking bug

- wherehows-web/app/components/dataset-authors.ts
- wherehows-web/app/routes/datasets/dataset.ts
- wherehows-web/app/styles/components/dataset-author/_dataset-author.scss
- wherehows-web/app/styles/components/dataset-author/_owner-table.scss
- wherehows-web/app/styles/components/user-lookup/_user-lookup.scss
- wherehows-web/app/templates/components/dataset-author.hbs
- wherehows-web/app/templates/components/dataset-authors.hbs
- wherehows-web/app/templates/components/user-lookup.hbs
- wherehows-web/tests/integration/components/datasets/containers/dataset-ownership-test.js
Modify ownership table to include the trigger to add owner and slight styling revamps to fit new UX
```
ok 1 Chrome 66.0 - ESLint | mirage: mirage/factories/access.js
ok 2 Chrome 66.0 - ESLint | mirage: mirage/factories/column.js
...
ok 351 Chrome 66.0 - Unit | Utility | validators/urn: buildLiUrn
ok 352 Chrome 66.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
1..352
```
> Dataset owner selection revamp

- wherehows-web/app/components/search-bar-form.js
- wherehows-web/app/templates/components/search-bar-form.hbs
Hitting enter on a suggestion will also trigger a search with that autocomplete value as the keyword. Previously, hitting enter would only autocomplete, and the user would need to press enter again to trigger the search, leading to an awkward user experience.
Change is to create an action that muts the `search` value in `search-bar-form` component and also triggers a search instead of just muting `search`
`just ember test` results:
```
ok 1 Chrome 66.0 - ESLint | mirage: mirage/factories/access.js
ok 2 Chrome 66.0 - ESLint | mirage: mirage/factories/column.js
ok 3 Chrome 66.0 - ESLint | mirage: mirage/factories/comment.js
...
ok 352 Chrome 66.0 - Unit | Utility | validators/urn: buildLiUrn
ok 353 Chrome 66.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly …
```
> Remove extra step to trigger typeahead search

- wherehows-web/app/utils/validators/urn.ts
so that logic flow allows wildcards when transitioning into dataset route. 
```
1..361
```
> Add wildcard to linkedin urn regex check for a dataset id

- wherehows-web/app/components/pwr-user-lookup.ts
- wherehows-web/app/constants/keyboard.ts
- wherehows-web/app/constants/typeahead.ts
- wherehows-web/app/styles/components/user-lookup/_all.scss
- wherehows-web/app/styles/components/user-lookup/_pwr-user-lookup.scss
- wherehows-web/app/styles/components/user-lookup/_user-lookup.scss
- wherehows-web/app/templates/components/dataset-authors.hbs
- wherehows-web/app/templates/components/notifications/partials/_stale-search-alert.hbs
- wherehows-web/app/templates/components/pwr-user-lookup.hbs
- wherehows-web/app/typings/modules/power-select.d.ts
- wherehows-web/package.json
- wherehows-web/tests/integration/components/pwr-user-lookup-test.js
- wherehows-web/yarn.lock
- Minor change to show suggested owners box even if # system suggested owners is 0
- Install `ember-power-select-typeahead` and leverage it to build a `pwr-user-lookup` component that revamps the old typeahead UX
- Using arrow keys or mouse to click on suggestions remains the same behavior as before
- Using enter key now automatically confirms a selection for the autocompleted value
- Using tab key now autocompletes the text without an official selection
- Fixes an issue with the "+" icon being confusing - it now disappears when user focuses on typeahead box to not seem like a button
- After a selection, typeahead now properly clears the current entry
```
ok 1 Chrome 66.0 - ESLint | mirage: mirage/factories/access.js
ok 2 Chrome 66.0 - ESLint | mirage: …
```
> Implement new user lookup with ember power select typeahead

- wherehows-web/app/components/pwr-user-lookup.ts
- wherehows-web/app/styles/components/dataset-author/_suggested-owners.scss
- wherehows-web/app/styles/components/notifications/_banner-alerts.scss
- wherehows-web/app/templates/components/datasets/owners/suggested-owners.hbs
- wherehows-web/app/templates/components/notifications/partials/_stale-search-alert.hbs
Fix issue where typeahead in ownership tab losing focus would incorrectly display placeholder without a clear. Also fix padding issues on no owners suggested state for suggested owners box. Make change to wording banner for stale search.
```
1..364
```
> Minor bug fix for ownership tab change stale banner wording

- wherehows-web/app/router.js
- wherehows-web/app/utils/build-url.ts
Redirection is handled on the play mid tier layer now that serves the page. Deletion only
```
1..457
```
> remove client side redirection to https

- wherehows-web/app/components/dataset-authors.ts
- wherehows-web/app/components/datasets/containers/dataset-ownership.ts
- wherehows-web/app/controllers/login.ts
- wherehows-web/app/templates/components/datasets/containers/dataset-ownership.hbs
- wherehows-web/app/utils/api/datasets/owners.ts
Uses owners/suggestion api to get suggested owners rather than using frontend filtering. Also, changes timing so that 2FA notice banner alert won't be prematurely removed if login is not successful.
```
ok 1 Chrome 67.0 - ESLint | mirage: mirage/data/schema.js
ok 2 Chrome 67.0 - ESLint | mirage: mirage/factories/access.js
...
ok 462 Chrome 67.0 - Unit | Utility | validators/urn: buildLiUrn
ok 463 Chrome 67.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
1..463
```
> Implement suggested owners api and 2fa banner change

- wherehows-backend/README.md
The original link is broken, changing to the relevant one.
> Point to the correct link of architecture design

- wherehows-web/app/components/browser/containers/data-systems.ts
- wherehows-web/app/routes/browse/entity.ts
- wherehows-web/app/templates/components/more-info.hbs
- wherehows-web/app/utils/entities/bake-urn-breadcrumbs.ts
- wherehows-web/app/utils/validators/urn.ts
- fixes issue with urn navigation when data system prefix does not exist
>  removes title attribute from more-info tags. clears out sticky params on browse/:entity route on exit

- wherehows-web/app/components/datasets/containers/dataset-health.ts
- wherehows-web/app/components/visualization/charts/horizontal-bar-chart.ts
- wherehows-web/app/styles/abstracts/_functions.scss
- wherehows-web/app/styles/base/_all.scss
- wherehows-web/app/styles/base/_visualization.scss
- wherehows-web/app/styles/components/_all.scss
- wherehows-web/app/styles/components/visualization/_all.scss
- wherehows-web/app/styles/components/visualization/charts/_all.scss
- wherehows-web/app/styles/components/visualization/charts/_bar-chart.scss
- wherehows-web/app/templates/components/datasets/containers/dataset-health.hbs
- wherehows-web/app/templates/components/visualization/charts/horizontal-bar-chart.hbs
- wherehows-web/app/typings/app/visualization/charts.d.ts
- wherehows-web/tests/integration/components/visualization/charts/horizontal-bar-chart-test.js
Add a horizontal bar chart component and styling in preparation for new metadata health tab.
```
ok 1 Chrome 68.0 - ESLint | mirage: mirage/data/schema.js
ok 2 Chrome 68.0 - ESLint | mirage: mirage/factories/access.js
...
ok 420 Chrome 68.0 - Unit | Utility | validators/urn: buildLiUrn
ok 421 Chrome 68.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
1..421
```
Reference:
> Horizontal bar graphs

- wherehows-web/app/components/datasets/containers/dataset-health.ts
- wherehows-web/app/constants/data/temp-mock/health.ts
Since we do not use mirage in staging, importing directly from mirage directory caused an error. Instead, put the mock data to show in staging in a constants folder to keep mock data modular away from code without using mirage.
```
1..376
```
> Move import of staging mock data to constants file in app instead of mirage

- wherehows-frontend/app/security/DummyLoginModule.java
- wherehows-frontend/conf/jaas.conf
- wherehows-frontend/test/DummyLoginModuleTest.java
This change adds a new login module for WH authentication that works for a username (that is in the user table) and any password. In future, we would like this module to work for any username.
> Add dummy login module to jaas config

- wherehows-frontend/app/security/DummyLoginModule.java
- wherehows-frontend/test/DummyLoginModuleTest.java
License headers were missing in the relevant files. This change adds them.
> Adding license header to dummy login module

- wherehows-web/app/styles/layout/_dataset.scss
- wherehows-web/app/templates/datasets/dataset.hbs
Rearrange items to fit in the current iteration of the header, but only for case `showDatasetHealth == true`
```
1..379
```
> Add health score gauge to the dataset meta header

- wherehows-docker/.env
- wherehows-docker/README.md
- wherehows-docker/docker-compose.yml
- wherehows-frontend/README.md
Now that we are not restricting ourselves to using LDAP for authentication, let's get rid of it's references from documentation and config files.
> More cleanup to get rid of WHZ_LDAP_* references

- wherehows-web/app/components/datasets/containers/dataset-health.ts
- wherehows-web/app/typings/api/datasets/health.d.ts
- wherehows-web/app/typings/ember-cli-mirage.d.ts
- wherehows-web/app/utils/api/datasets/health.ts
- wherehows-web/mirage/config.ts
- wherehows-web/mirage/factories/dataset.ts
- wherehows-web/mirage/factories/health.ts
- wherehows-web/mirage/helpers/dataset-health.ts
- wherehows-web/mirage/scenarios/default.ts
- wherehows-web/tests/integration/components/datasets/containers/dataset-health-test.js
- Add typings for expected health response and health score objects
- Implement util api function to retrieve dataset health information (TODO: Actually apply this once we have a real backend)
- Create mirage factory to generate health information
```
1..379
```
> Ui health typings and api handler

- wherehows-web/app/components/datasets/containers/dataset-health.ts
- wherehows-web/app/templates/components/datasets/containers/dataset-health.hbs
- wherehows-web/app/templates/components/datasets/health/metrics-charts.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
- wherehows-web/tests/integration/components/datasets/health/metrics-charts-test.js
- wherehows-web/tests/test-helper.js
Highcharts calculates size and other chart details upon initial render and doesn't rerender when we switch tabs. Because of this we want those calculations to take place when dataset health is the currently active tab, otherwise we will insert elements off screen and size will default to 0 and we lose our charts.
Also remove annoying deprecation warnings that aren't relevant yet.
```
1..482
```
> Health tab fix

- wherehows-web/app/utils/validators/urn.ts
> Modify regex test for urn to allow dollar signs in pathname

- wherehows-web/app/components/dataset-authors.ts
- wherehows-web/app/controllers/datasets/dataset.ts
- wherehows-web/app/templates/components/datasets/containers/dataset-ownership.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
###v1:
- Creates a red dot on the ownership tab (similar to compliance tab) when requirements for this are not met. 
```
1..487
```
> Red dot ownership

- wherehows-web/app/utils/validators/urn.ts
> Allow for equals sign in urn validator

- wherehows-frontend/app/controllers/Application.java
Sets up config for wiki link for export policy added by PR https://github.com/linkedin/WhereHows/pull/1351
Removing the linkedin prepend from all the wiki links as these are items used in the UI for "more info" links and should be open source friendly, not LinkedIn specific.
> Add export policy wiki link to config and remove linkedin prepend from wiki links

- wherehows-web/app/components/hotkeys/global-hotkeys.ts
Original implementation of global hotkeys used a wrapper ember component to handle all keystrokes that bubbled up to it. However, it seems like this approach isn't perfect as when a user is browsing and enters a new page, the only element that has focus for keystrokes is the `<body>`. Because of this, changing implementation to add an event listener to the body in order to capture all keystrokes. 
```
1..520
```
> Change global hotkeys to use native event listener

- wherehows-web/app/components/dataset-compliance.ts
- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/utils/api/datasets/compliance.ts
This fixes an issue where the export policy UI was not updating after a POST request.
```
1..508
```
> Update the export policy immediately based on response to POST request

- wherehows-web/app/components/datasets/schemaless-tagging.ts
- wherehows-web/app/templates/components/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/schemaless-tagging.hbs
- Previously, editing was done with a wizard, but we moved to allowing each component in dataset compliance tab to be individually editable. However, this change did not incorporate the scenario in which a dataset was schemaless.
- We now give this component the same UX as the purge policy or export policy edits
- Also taking the chance to isolate most functionality in the component rather than depending on the parent dataset-compliance complex component.
`ember test` results
```
1..507
```
> Fixes issues where schemaless tagging component was permanently uneditable

- wherehows-web/app/components/dataset-compliance.ts
- wherehows-web/app/components/datasets/compliance/export-policy.ts
- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/templates/components/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/compliance/export-policy.hbs
- wherehows-web/app/utils/api/datasets/compliance.ts
- Remove see more and see less from export policy component as there are only 3 fields
- Fix typo that prevented disable of save button for compliance policy when fields were incomplete
- Improve UX for export policy by showing "No policy defined" when getting a 404 vs showing all fields as "no" which can be confusing
```
1..507
```
> Compliance tab fix and cleanup

- wherehows-web/app/components/dataset-compliance.ts
- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/templates/components/datasets/containers/dataset-compliance.hbs
- wherehows-web/app/utils/api/datasets/compliance.ts
###v1:
- Because we are allowing editing of compliance tab components individually, we need to split up the save requests as putting them together is causing issues on the mid-tier/backend
```
1..507
```
> Separate compliance and retention post requests on save

- wherehows-frontend/app/controllers/Application.java
- wherehows-web/app/components/datasets/containers/dataset-acl-access.ts
- wherehows-web/app/controllers/datasets/dataset.ts
- wherehows-web/app/routes/datasets/dataset.ts
- wherehows-web/app/services/configurator.ts
- wherehows-web/app/templates/components/dataset-aclaccess.hbs
- wherehows-web/app/templates/components/datasets/containers/dataset-acl-access.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
- wherehows-web/app/typings/api/configurator/configurator.d.ts
Removes a bit of "linkedin" ness from open source world and also improves getconfigs to have one extra optional fallback instead of returning the whole config object
```
1..507
```
> Add jitacl contact to configs update getconfigs to take default value

- wherehows-frontend/app/controllers/Application.java
- wherehows-web/app/components/datasets/compliance/export-policy.ts
- wherehows-web/app/routes/application.js
- wherehows-web/app/services/banners.ts
- wherehows-web/app/typings/api/configurator/configurator.d.ts
- wherehows-web/app/typings/app/datasets/export-policy.d.ts
- In calculation for export policy form, default to `undefined` rather than false so that nothing is selected and user has to choose instead of the "lazy method"
- For our private production environment, show a live data warning banner so that users know they are messing with real data
```
1..504
```
> Do not default to false for export policy. Give live data warning banner

- wherehows-dao/src/main/java/wherehows/dao/table/LineageDao.java
- wherehows-dao/src/main/java/wherehows/models/view/LineageView.java
- wherehows-frontend/app/controllers/api/v2/Dataset.java
- wherehows-web/app/typings/api/datasets/relationships.d.ts
Creates a new response type for relationships tab for lineage to be able to fill out all our necessary lineage information (actor, modified, type, etc). `dataset/<urn>/upstream` and `dataset/<urn>/downstream` will use this new response format instead.
`../gradlew build` results:
```
BUILD SUCCESSFUL in 1m 7s
21 actionable tasks: 6 executed, 15 up-to-date
```
> Modify upstream downstream relationships api to use new lineage model

- wherehows-frontend/app/controllers/Application.java
- wherehows-web/app/styles/components/visualization/charts/_score-gauge.scss
- wherehows-web/app/templates/components/datasets/containers/health-score-gauge.hbs
- wherehows-web/app/templates/components/more-info.hbs
- wherehows-web/app/templates/components/visualization/charts/score-gauge.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
- Clicking on the health score gauge now moves you to the health tab
- The healthscore comes with a tooltip that leads to a wiki page to explain metadata health
- Removes "more info" from the helper tooltips and just leaves the question mark thing
- Mid tier returns a custom wiki link for metadata health
```
Note: 
The two failing tests are the avatar ones being fixed in PR https://github.com/linkedin/WhereHows/pull/1390
```
```
1..502
```
> Add a tooltip for health score and remove more info from tooltip messages

- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/components/datasets/containers/upstream-dataset.ts
- wherehows-web/app/templates/components/datasets/containers/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/upstream-dataset.hbs
...to determine whether or not we should show parent datasets.
- Use the upstreams API to show parents since this is more reliable
- For now, we still rely on resolved compliance from the `/compliance` call to indicate whether or not the upstream parent has compliance (check mark in the table)
- Passes the upstreams from the dataset compliance container to the upstreams container to avoid making a separate api call to fetch upstreams when we already needed to do that
```
1..500
```
> Use upstream lineage instead of resolved compliance

- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/templates/components/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/containers/dataset-compliance.hbs
As we are already splitting up the save requests for compliance and retention, the next logical step would be to decouple the GET for this information as well. Additionally, some datasets may not have compliance but still have a retention policy, which relying on compliance to find this information would not work.
```
1..500
catran@ca
```
> Use retention API instead of compliance to determine purge policy

- wherehows-web/app/components/dataset-compliance.ts
- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/templates/components/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/containers/dataset-compliance.hbs
- wherehows-web/app/utils/datasets/retention.ts
Follow up to previous PR, this PR completes the decoupling of compliance and retention by using retention policy as source of data for purge policy form instead of `complianceInfo`. We also create a separate reset that can be called to reset the retention policy and modify the POST request to retention to use retentionPolicy instead of compliance. This should completely solve the issue where, in cases where a dataset does not have compliance, a user was not able to update the purge policy.
```
1..500
```
> Use retention policy for form and create separate reset retention

- wherehows-frontend/app/controllers/Application.java
- wherehows-web/app/components/dataset-deprecation.ts
- wherehows-web/app/styles/base/_checkbox.scss
- wherehows-web/app/styles/components/search/_facet.scss
- wherehows-web/app/templates/components/dataset-deprecation.hbs
- wherehows-web/app/templates/components/datasets/containers/dataset-properties.hbs
- wherehows-web/app/templates/components/search/search-facet.hbs
- wherehows-web/app/templates/datasets/dataset.hbs
- wherehows-web/tests/integration/components/dataset-deprecation-test.js
###v1:
- Deprecated datasets should still have updated compliance. Part of the workflow should include acknowledging that deprecating the dataset does not remove responsibility for keeping compliance updated
- We include a message with checkbox above the update dataset deprecation status button that must be clicked in order to un-disable the update message. This is positioned as such to become a natural part of the user workflow
- We also add an additional link 
- Change the `Properties` tab to `Status`
```
1..500
```
> Dataset deprecation acknowledgement

- wherehows-web/app/components/dataset-aclaccess.ts
- wherehows-web/app/templates/components/dataset-aclaccess.hbs
###v1:
- Moves "more info" link to the request access header to make it easier for users to notice.
- `minSelectableExpirationDate` set to `Date.now() + 24HoursInMilliseconds` creates an interesting issue where the next day on the calendar is actually not selectable and makes the minimum number of days to be 2 days from current time. Setting the property to `Date.now() + 1HourFromNow` in order to allow user to select the next day in most cases. 
```
1..502
```
> UX improvements for acl access tab

- wherehows-web/app/components/dataset-compliance.ts
- wherehows-web/app/components/datasets/containers/dataset-compliance.ts
- wherehows-web/app/templates/components/dataset-compliance.hbs
###v1:
- The original logic is outdated and in a situation where a dataset doesn't have `complianceInfo` but the user tries to edit the purge policy, it creates a false error "Please specify a Compliance Purge Policy"
- This logic also helps fix an issue where you can select multiple radio buttons (due to undefined issue)
- The fix is to create an empty object for `retentionPolicy` when API returns `null`
```
1..502
```
> Moves fe check for compliance purge policy to retentionPolicy instead of complianceInfo

- wherehows-web/app/styles/layout/_dataset.scss
###v1:
- Sometimes a dataset name that's too long can overlap with the health gauge. Small CSS fix for this
```
1..502
```
> Fix issue where dataset names that are too long overlap health gauge

- wherehows-web/app/components/datasets/containers/dataset-health.ts
- wherehows-web/app/components/datasets/containers/health-score-gauge.ts
Minor changes only.
```
1..502
```
> Start migrating code in dataset health components away from get helper

- wherehows-web/app/styles/components/dataset-author/_suggested-owners.scss
- wherehows-web/app/styles/components/dataset-property/_dataset-pill.scss
- wherehows-web/app/styles/components/dataset-relationships/_dataset-relationships.scss
- wherehows-web/app/templates/components/dataset-compliance.hbs
- wherehows-web/app/templates/components/datasets/dataset-relationship-table.hbs
###v1:
- Corrects some CSS that caused dataset pills did not have the correct text color and made it difficult to read
- Fix a CSS issue where owner names in the suggested owners list in the ownership tab would be under the picture instead of to the right when the text overflowed
- Add platform column to lineage table and resize the cells to better fit the expected content we get
```
1..504
```
Old vs New
> Various ux fixes

- metadata-ingestion/src/avro_cli.py
- metadata-ingestion/src/resources/sample_MCE.dat
- metadata-models/src/main/pegasus/com/linkedin/mxe/MetadataChangeEvent.pdsc
This change aimed to apply the Avro type in MetadataChangeEvent to resolve the multiple kinds of the Snapshots.
> Resolved union type in avro serialization.

- datahub-web/@datahub/data-models/addon/entity/person/person-entity.ts
This PR aims to use the pictureLink property from the person entity as a primary fallback image URL.
> feature: :camera: - Use pictureLink property to show person picture

- datahub-web/README.md
- datahub-web/build.gradle
1. adjust gradew to gradlew for doc
2. watchmman need proxy URL
```
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
You need to include a protocol with the proxy URL.
Try --proxy http://localhost:9001
```
> fix typo and watchman error

- docker/kafka/docker-compose.yml
- docker/quickstart/docker-compose.yml
- metadata-events/mxe-utils-avro-1.7/src/main/java/com/linkedin/metadata/EventUtils.java
- metadata-events/mxe-utils-avro-1.7/src/test/java/com/linkedin/metadata/EventUtilsTests.java
- metadata-events/mxe-utils-avro-1.7/src/test/resources/test-pegasus2avro-fmce.json
- metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MceStreamTask.java
No Failed MCE was sent when a MCE was rejected by the system
- Added FailedMetadataChangeEvent kafka topic
- Created FailedMCE event from the MCE record
- Added Kafka Producer to send FailedMCE to the FailedMetadataChangeEvent Topic
> feat: Enable Failed Metadata Change Event for MCE Processor

- datahub-web/@datahub/metadata-types/addon/constants/common/fabric-type.ts
- gms/api/src/main/snapshot/com.linkedin.dataset.datasets.snapshot.json
- li-utils/src/main/java/com/linkedin/common/urn/UrnUtils.java
- li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdsc
These enums are for internal use and are causing confusion in open source
> Drop LI internal fabrics

- contrib/nix/README.md
- contrib/nix/sandbox.nix
use physical machine to setup database service.
do configure, then it works.
> add nix sandbox

- datahub-web/build.gradle
This significantly speeds up `gradlew idea`
> build: bypass testing datahub-web when running idea gradle task

- contrib/kubernetes/README.md
- contrib/kubernetes/datahub-configmap.yaml
- contrib/kubernetes/datahub-frontend-deployment.yaml
- contrib/kubernetes/datahub-gms-deployment.yaml
- contrib/kubernetes/datahub-mae-consumer-deployment.yaml
- contrib/kubernetes/datahub-mce-consumer-deployment.yaml
- contrib/kubernetes/datahub-secret.yaml
This is the first version of Kubernetes based deployment.  This PR contains kubernetes YAML configuration files.   If this work is in alignment with the owners, I can go ahead and create Helm chart for easy installation of Datahub on Kubernetes.  Open for feedback.  Thank you.
> feat: support for Kubernetes-based deployment

- gms/api/src/main/snapshot/com.linkedin.dataset.datasets.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpGroups.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpUsers.snapshot.json
- gms/impl/build.gradle
- metadata-dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java
- metadata-dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java
- metadata-dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/ESUtils.java
- metadata-dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
- metadata-dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/ESUtilsTest.java
- metadata-dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/browse/BrowseDAOTest.java
- metadata-dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java
- metadata-dao-impl/elasticsearch-dao/src/test/resources/RangeFilterQuery.json
- metadata-dao/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
- metadata-dao/src/main/pegasus/com/linkedin/metadata/query/Condition.pdsc
- metadata-dao/src/main/pegasus/com/linkedin/metadata/snapshot/SnapshotKey.pdsc
- metadata-events/mxe-utils-avro-1.7/src/main/java/com/linkedin/metadata/EventUtils.java
- metadata-events/mxe-utils-avro-1.7/src/test/java/com/linkedin/metadata/EventUtilsTests.java
- metadata-events/mxe-utils-avro-1.7/src/test/resources/test-pegasus2avro-fmce.json
- metadata-restli-resource/build.gradle
- metadata-restli-resource/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java
- metadata-restli-resource/src/test/java/com/linkedin/metadata/restli/BaseVersionedAspectResourceTest.java
- metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUpdate.pdsc
Changes include:
Remove all keys that can be moved back to respective GMS
Add support for <, <=, >, >= conditions for the filter API
Update Conditions model for <, <=, >, >= conditions
MP_VERSION=metadata-models:58.0.1
MP_VERSION=wherehows-samza:1.0.56
> metadata-models 54.0.1 -> 58.0.1

- contrib/metadata-ingestion/README.md
- contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs
- contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs.nix
add oracle driver, and plan to add hive driver later
> add oracle driver

- docker/quickstart/quickstart.sh
The `chown 1000:1000` trick mentioned in https://discuss.elastic.co/t/elastic-elasticsearch-docker-not-assigning-permissions-to-data-directory-on-run/65812/4 only works on Linux. Make the directory world writeable instead so that it works on both Mac & Linux.
> fix: elasticsearch not starting on Mac

- gradle.properties
Snapshot & IDL will not be regenerated consistently when gradle caching is enabled.
> build: pegasus plugin doesn't work well with gradle caching

- gms/README.md
- gms/war/build.gradle
Also make sure the task depends on build so it'll rebuild if needed.
This make it more consistent with other modules such as mce-consumer-job.
> build(gms): rename JettyRunWar task to run

- datahub-frontend/app/controllers/api/v1/User.java
This will print the full stacktrace in log to help identify various gms issues
> refactor(frontend): fails loudly to help debug gms issue

- docker/gms/Dockerfile
Getting `sh: dockerize: not found` from datahub-gms container while running quickstart. Copying dockerize to /usr/local/bin while extracting it to resolve the issue.
Built Docker image locally & tested by running quickstart docker-compose without pulling from latest. Confirmed that datahub-gms starts as expected.
> fix(Docker): Fixing 'dockerize not found' issue while starting datahub-gms container using quickstart

- contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs
add support for postgresql metadata and enforce utf8 encode on various machine.
it seesm mysql run on non-utf8 locale will lead to chinese messy character to display.
some chinese friend report it to me even  in docker setup.
so i force the utf8 in my script.
anyway, i can enforce utf8 for database using the following statement for database setup and gms ebean connection.
```
echo "CREATE DATABASE datahub default character set utf8" | mysql -u root -S /nix/var/run/mysqld.sock
export EBEAN_DATASOURCE_URL="jdbc:mysql://localhost:3306/datahub?useSSL=false&useUnicode=yes&characterEncoding=UTF-8"
```
> add postgresql metadata support and force utf8 encode on non-utf8 locale

- metadata-ingestion/mce-cli/mce_cli.py
> fix(metadata-ingestion): pass schema_record to mce-cli cosumer

- docker/quickstart/docker-compose.yml
> fix(quickstart): set utf8mb4 for mysql

- datahub-frontend/conf/logback.xml
- gms/war/src/main/resources/logback.xml
- metadata-jobs/mae-consumer-job/src/main/resources/logback.xml
- metadata-jobs/mce-consumer-job/src/main/resources/logback.xml
The original location (/local/log) is not a commonly writable location on Mac & Linux.
The new default location also matches the default data location for docker containers.
> refactor: change the default log location

- README.md
- docker/quickstart/README.md
- docker/quickstart/docker-compose.yml
- docker/quickstart/quickstart.sh
- docs/debugging.md
Volume is the preferred method over bind mount (https://docs.docker.com/storage/volumes/) for persistent container data.
This also eliminates the need for the ugly chmod hack for elasticsearch and hopefully fixes https://github.com/linkedin/datahub/issues/1650
> refactor: use named volume instead of bind mount in quickstart

- metadata-dao/src/main/java/com/linkedin/metadata/dao/equality/AlwaysFalseEqualityTester.java
- metadata-dao/src/main/java/com/linkedin/metadata/dao/equality/DefaultEqualityTester.java
- metadata-dao/src/main/java/com/linkedin/metadata/dao/equality/EqualityTester.java
- metadata-dao/src/test/java/com/linkedin/metadata/dao/equality/DefaultEqualityTesterTest.java
This fixes https://github.com/linkedin/datahub/issues/1663
Also change the signature of EqualityTester to compare only DataTemplates
> fix: use semantic instead of literal comparison in DefaultEqualityTester

- li-utils/src/main/java/com/linkedin/common/urn/DataJobUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DataProcessUrn.java
refer to [this issue](https://github.com/linkedin/datahub/issues/1659) for the details
> add DataProcess Urn

- li-utils/src/main/java/com/linkedin/common/urn/AzkabanFlowUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/AzkabanJobUrn.java
- li-utils/src/main/pegasus/com/linkedin/common/AzkabanFlowUrn.pdsc
- li-utils/src/main/pegasus/com/linkedin/common/AzkabanJobUrn.pdsc
Add AzkabanFlow urn to represent an azkaban flow defined on a specific cluster
and inside a project.
Add AzkabanJob urn to represent an azkaban job defined as part of an azkaban
flow.
For more details on Azkaban flow and job see - https://azkaban.readthedocs.io/en/latest/
> feat(urn): add AzkabanFlow and AzkabanJob urn

- build.gradle
- metadata-jobs/mae-consumer-job/build.gradle
- metadata-jobs/mce-consumer-job/build.gradle
This will ensure the version of org.springframework.boot plugin is defined at one place which is the top level build.gradle file
> refactor: move springframework gradle plugin version to top level build.gradle

- README.md
- docker/ingestion/Dockerfile
- docker/ingestion/README.md
- docker/ingestion/docker-compose.yml
- docker/ingestion/ingestion.sh
- add "build" option to docker-compose file to simplify rebuilding of images
- move command from docker-compose.yml to Dockerfile
- add ingestion.sh script to simplify quickstart instruction and to reduce confusion
Fix https://github.com/linkedin/datahub/issues/1689
> build(docker): refactor ingestion docker build script

- docker/elasticsearch/Dockerfile
- docker/frontend/Dockerfile
- docker/frontend/README.md
- docker/frontend/docker-compose.yml
- docker/gms/Dockerfile
- docker/gms/README.md
- docker/gms/docker-compose.yml
- docker/gms/start.sh
- docker/kafka/Dockerfile
- docker/kafka/README.md
- docker/kafka/docker-compose.yml
- docker/mae-consumer/Dockerfile
- docker/mae-consumer/README.md
- docker/mae-consumer/docker-compose.yml
- docker/mae-consumer/start.sh
- docker/mce-consumer/Dockerfile
- docker/mce-consumer/README.md
- docker/mce-consumer/docker-compose.yml
- docker/mce-consumer/start.sh
- docker/quickstart/docker-compose.yml
- add "build" option to docker-compose files to simplify rebuilding of images
- create "start.sh" script so it's easier to override "command" in the quickstart's docker-compose file
- use dockerize to wait for requisite services to start up
- add a dedicated Dockerfile for kafka-setup
This fixes https://github.com/linkedin/datahub/issues/1549 & https://github.com/linkedin/datahub/issues/1550
> build(docker): refactor docker build scripts

- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
Some of the current helm container commands are not compatible with the latest
docker images. Instead, rely on CMD in the docker images.
> fix: remove helm container commands

- contrib/kubernetes/datahub/charts/datahub-gms/templates/configmap.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
The new var is needed by the recently added docker start.sh scripts
> fix: add missing neo4j.host helm var

- datahub-dao/src/main/java/com/linkedin/datahub/util/CorpUserUtil.java
Tested on DataHub UI. Ownership tab earlier would throw an error since http://localhost:9001/api/v1/party/entities throws Null pointer exception when picture link is not provided in `CorpUserEditableInfo` aspect. Now it doesn't throw an error.
> [fix] Fix NPE while loading picture link

- metadata-ingestion/README.md
- metadata-ingestion/hive-etl/hive_etl.py
- metadata-ingestion/hive-etl/requirements.txt
- metadata-ingestion/kafka-etl/kafka_etl.py
- metadata-ingestion/kafka-etl/requirements.txt
- metadata-ingestion/ldap-etl/ldap_etl.py
- metadata-ingestion/ldap-etl/requirements.txt
- metadata-ingestion/mce-cli/mce_cli.py
- metadata-ingestion/mce-cli/requirements.txt
- metadata-ingestion/mysql-etl/mysql_etl.py
- metadata-ingestion/mysql-etl/requirements.txt
Fix https://github.com/linkedin/datahub/issues/1688
> refactor(py3): Refactor all ETL scripts to using Python 3 exclusively

- docker/elasticsearch/dataprocess-index-config.json
- docker/elasticsearch/st
- gms/api/src/main/idl/com.linkedin.dataprocess.dataProcesses.restspec.json
- gms/api/src/main/snapshot/com.linkedin.dataprocess.dataProcesses.snapshot.json
- gms/client/src/main/java/com/linkedin/dataprocess/client/DataProcesses.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataprocess/DataProcesses.java
- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/CorpGroupIndexBuilderTest.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/CorpUserInfoIndexBuilderTest.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilderTest.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/DataProcessDocument.pdl
The following screenshot proves this feature works.
> Implemented data process search feature

- metadata-ingestion/ldap-etl/requirements.txt
- metadata-ingestion/mysql-etl/requirements.txt
- metadata-ingestion/sql-etl/common.py
- metadata-ingestion/sql-etl/common.txt
After verification, the function `producer.produce` will not throw exceptions. The exception will be returned as a callback.
Such as:
```
Message delivery failed: KafkaError{code=INVALID_MSG,val=2,str="Broker: Invalid message"}
```
> fix: correct the way to catch the exception

- docs/README.md
- docs/rfc.md
- docs/rfc/templates/000-template.md
- docs/slack.md
Other repos have similar RFC processes (though they seem to have a separate repo for their RFC docs).
This provides a more structured way for contributors to make siginficant design contributions.
https://github.com/linkedin/datahub/issues/1692
> Add documentation around the DataHub RFC process.

- docs/how/kafka-config.md
Fix name of spring-kafka property to pass SASL_JAAS config
> docs(Kafka-config): Fix name of spring-kafka property to pass SASL_JAAS config

- .github/workflows/check-pr.yml
- .github/workflows/docker-frontend.yml
- .github/workflows/docker-gms.yml
- .github/workflows/docker-mae-consumer.yml
- .github/workflows/docker-mce-consumer.yml
PRs are setup to skip docs.
Also, only run docker actions on linkedin/datahub (i.e. disable on forks; makes forks nicer since you don't have failing actions).
See it in action in my fork (and it should also show up in this PR?):
- https://github.com/jplaisted/datahub/pull/1
- (test the disabled feature) https://github.com/jplaisted/datahub/pull/2
- (test enabling) https://github.com/jplaisted/datahub/pull/3
> Add workflow to check build and tests on PRs + releases.

- .github/workflows/docker-frontend.yml
- .github/workflows/docker-gms.yml
- .github/workflows/docker-mae-consumer.yml
- .github/workflows/docker-mce-consumer.yml
We renamed directories in docker/ which broke the actions.
Also try to refactor the action files a little so that we can run (but not publish) these images on pull requests that change the docker/ dir as an extra check. Note this only seems to be supported by the dockerhub plugin; the github plugin doesn't support this (so that will be an issue when we move to it only).
> build: fix docker actions.

- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
Fixes https://github.com/linkedin/datahub/issues/1798
Also verified end-to-end
1. Set the dataset description
2. Make sure it's searchable
3. Clear dataset description
4. Make sure it's unsearchable
> fix(search): clear description from dataset index when it's cleared

- gms/api/src/main/idl/com.linkedin.dataprocess.dataProcesses.restspec.json
- gms/api/src/main/idl/com.linkedin.dataset.datasets.restspec.json
- gms/api/src/main/idl/com.linkedin.identity.corpGroups.restspec.json
- gms/api/src/main/idl/com.linkedin.identity.corpUsers.restspec.json
- gms/api/src/main/snapshot/com.linkedin.dataprocess.dataProcesses.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dataset.datasets.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpGroups.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpUsers.snapshot.json
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataprocess/DataProcesses.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/Datasets.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpGroups.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpUsers.java
The last PR to sync internal code broke the external GMS, as code was now expected aspectNames to be null rather than empty by default. This preventing me logging into DataHub as the corp user request would fail (it assumed I asked for no aspects rather than all aspects).
TESTED: Built locally, launched with docker/dev.sh (so used latest frontend, but whatever). Verified I can now log into DataHub, browse and search for datasets, and view my profile.
> fix: update defaults of aspectNames params

- README.md
- docs/links.md
> docs: add external link

- build.gradle
- datahub-web/build.gradle
Looks like the current node gradle plugin is already broken: https://github.com/linkedin/datahub/pull/1837/checks?check_run_id=1047367684
> build(node): replace broken & unmaintained gradle node plugin

- metadata-ingestion/mce-cli/kafka.config
- metadata-ingestion/mce-cli/mce_cli.py
feat: Adding SSL support to mce_cli.py
Related to: https://github.com/linkedin/datahub/issues/1849
Test result:
MCE7: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DataProcessSnapshot", {"urn": "urn:li:dataProcess:(sqoop,DEMO,PROD)", "aspects": [{"owners":[{"owner":"urn:li:corpUser:datahub","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpUser:datahub"}},{"inputs":["urn:li:dataset:(urn:li:dataPlatform:cassandra,barEarth,DEV)","urn:li:dataset:(urn:li:dataPlatform:cassandra,barMars,DEV)"],"outputs":["urn:li:dataset:(urn:li:dataPlatform:hbase,barSky,PROD)","urn:li:dataset:(urn:li:dataPlatform:hbase,barOcean,PROD)"]}]}), "proposedDelta": None}
Flushing records...
> 1849 support ssl to mce cli.py

- build.gradle
- gms/factories/build.gradle
- metadata-jobs/mae-consumer-job/build.gradle
- metadata-jobs/mce-consumer-job/build.gradle
Should fix this issue as well, but since I do not have an SSL enabled schema registry I could not verify the fix: https://github.com/linkedin/datahub/issues/1861
> Allow configuration of schema registry basic auth in gms

- docs/rfc/templates/000-template.md
This seems helpful to reviewers (and probably also the author). Motivation is too high level to be able to properly review a design. We need a clear set of requirements to review the design against.
Stems from comments on https://github.com/linkedin/datahub/pull/1778#pullrequestreview-461847439
> doc(rfc): Add requirements / non requirements section to RFC.

- metadata-ingestion-examples/common/build.gradle
- metadata-ingestion-examples/kafka-etl/build.gradle
`kafkaSerializers` is already included transitively via `kafkaAvroSerde`
> build: fix build

- datahub-frontend/app/controllers/api/v2/Dataset.java
- datahub-web/@datahub/data-models/addon/entity/dataset/dataset-entity.ts
- datahub-web/@datahub/shared/tests/integration/components/dynamic-components/entity/field-test.ts
This PR fixes the following issues:
- https://github.com/linkedin/datahub/issues/1827
- https://github.com/linkedin/datahub/issues/1823
Both of which likely stem from the same root cause: that the datasets response for the open source midtier (datahub-frontend) no longer matches with how we are handling datasets in datahub-web internally. This PR doesn't create a perfect parity between the two but should bring us a little closer to how components are currently consuming dataset data. 
Upon testing, it looks like the lineage issue is solved and other components are currently working fine. 
Will rely on automated tests with the build for the rest.
> fix (frontend): Partially fixes lineage issues and dataset API handling

- datahub-web/@datahub/shared/addon/services/current-user.ts
Because of differences in the midtier for the current user `/me` api, we created a workaround that doesn't necessarily populate the current user's entity object correctly. This was expected to not have a significant impact on the operation of the application, however it turns out the ownership tab in datasets depends on the logged in user's entity object to validate ownership selections. As such, we went back and looked into how this object is being populated and see that we can simply make a second API call to populate the full information.
```
Locally tested.
Manually tested with docker images to ensure that application builds and behaves as expected for sample data
```
> fix(frontend): Fixes current user entity not being populated correctly

- .github/workflows/build-and-test.yml
- metadata-ingestion-examples/common/build.gradle
- metadata-ingestion-examples/kafka-etl/build.gradle
> build: add failure notification on push

- docker/datahub-frontend/Dockerfile
Chrome is required to run the tests during the building of the frontend. The frontend `Dockerimage` fails to install Chrome properly, as required dependencies are missing initially. This PR makes the fixes the install by installing Chrome and it's dependencies at the same time using `apt-get`.
> fix (docker): Fix install of Chrome in frontend Dockerimage

- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
Update mae and mce consumer images to include glibc compat layer. This allows the consumer jobs to deal with snappy compressed kafka topics when running on alpine linux. Otherwise you get errors like this:
```
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-bb847a5e-21b5-4d9b-babd-f31afc7109a7-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-bb847a5e-21b5-4d9b-babd-f31afc7109a7-libsnappyjava.so)
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```
An alternative approach is upgrading the snappy-java client library to a higher version that supports a purely java implementation of snappy so there is no dependence on native libraries. See here for more details: …
> fix(docker): update mae and mce consumer images to include glibc compat

- build.gradle
- contrib/kubernetes/datahub/README.md
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/values.yaml
- docs/faq.md
fix: Support Datahub to connect to Kafka Schema Registry using SSL
Related to: #1861
Test result:
1. Change kafkaAvroSerde to version io.confluent:kafka-streams-avro-serde:5.5.1
2. Rebuilt app 
3. Ran COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -p datahub build
4. Pushed to dockerhub
5. Deployed to our AWS EKS cluster using Helm
6. Verify that Datahub can connect to Confluent Schema Registry using SSL
7. Opened Datahub frontend and confirmed that data was loaded
You should also configure Schema Registry to use security (contrib/kubernetes/datahub/values.yaml):
- kafkastore.security.protocol=SSL
- kafkastore.ssl.truststore.location=/var/ssl/private/kafka.server.truststore.jks
- kafkastore.ssl.truststore.password=test1234
Note! The logs might say something similar to …
> Bump up kafkaAvroSerde to support SSL for Schema Registry

- gms/factories/src/main/java/com/linkedin/common/factory/TopicConventionFactory.java
- gms/factories/src/main/java/com/linkedin/dataprocess/factory/DataProcessDAOFactory.java
- gms/factories/src/main/java/com/linkedin/dataset/factory/DatasetDaoFactory.java
- gms/factories/src/main/java/com/linkedin/identity/factory/CorpGroupDaoFactory.java
- gms/factories/src/main/java/com/linkedin/identity/factory/CorpUserDaoFactory.java
- metadata-ingestion-examples/common/src/main/java/com/linkedin/metadata/examples/configs/TopicConventionFactory.java
New env vars:
- METADATA_CHANGE_EVENT_NAME: The name of the metadata change event topic.
- METADATA_AUDIT_EVENT_NAME: The name of the metadata audit event topic.
- FAILED_METADATA_CHANGE_EVENT_NAME: The name of the failed metadata change event topic.
This will need to be consistent throughout your ecosystem.
CLOSES: #1840
> Add new spring factories to customize metadata event topic names.

- docs/faq.md
- docs/how/kafka-config.md
> docs: Update for topic name configuration

- datahub-web/@datahub/data-models/addon/constants/entity/dataset/tab-properties/all.ts
- datahub-web/@datahub/data-models/addon/constants/entity/dataset/tab-properties/properties.ts
- datahub-web/@datahub/data-models/addon/constants/entity/dataset/tabs.ts
- datahub-web/@datahub/data-models/addon/entity/dataset/dataset-entity.ts
- datahub-web/@datahub/datasets-core/addon/components/datasets/containers/dataset-main.ts
- datahub-web/@datahub/metadata-types/types/entity/dataset/dataset-entity.d.ts
- datahub-web/packages/data-portal/app/templates/components/datasets/dataset-page.hbs
This PR is the final piece to address a feature request for custom dataset properties. 
Please reference https://github.com/linkedin/datahub/pull/1881 for how the sample data should look when ingested. The presentation is currently a basic table configured to read key value pairs. 
Fixes https://github.com/linkedin/datahub/issues/1730
Will rely on build to ensure that tests still pass. 
Spun up docker images and ensured that application still built and behaved correctly with the mock data. Reference image below:
> feat(frontend): Adds UI support for custom dataset properties

- docs/how/search-over-new-field.md
> doc: update search-over-new-field.md

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
This PR fixes the issue of the services being run as root, which is suboptimal as the code executed in the container can get root access on the host machine. We add a `datahub` user and group in the Docker images, and the services are run using that user.
> fix(docker): Run as non-root user in docker

- metadata-ingestion/sql-etl/common.py
Datahub was expecting this timestamp to be in milliseconds since epoch, not seconds. This change makes the lastModified timestamp render correctly in the UI when it is converted to a datetime string.
> fix(metadata-ingestion): Fix auditStamp unix timestamp format in sql etl ingestion

- gms/client/src/main/java/com/linkedin/dataprocess/client/DataProcesses.java
- gms/client/src/main/java/com/linkedin/identity/client/CorpGroups.java
- gms/client/src/main/java/com/linkedin/identity/client/CorpUsers.java
SearchableClient is deprecated
> refactor: make use of BaseSearchableClient

- docs/debugging.md
- docs/how/search-over-new-field.md
> docs: correct search over new field docs

- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilder.java
- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilderTest.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
> refactor: store urns parts in search index builder efficiently

- datahub-dao/src/main/java/com/linkedin/datahub/util/CorpUserUtil.java
Check if the aspects are present before extracting the values.
##Testing Done
- Created a test user without corpusereditableinfo
```
curl 'http://localhost:8080/corpUsers?action=ingest' -X POST -H 'X-RestLi-Protocol-Version:2.0.0' --data '{"snapshot": {"aspects": [{"com.linkedin.identity.CorpUserInfo":{"active": true, "displayName": "Bar", "fullName": "Bar", "email": "fbar@linkedin.com"}}], "urn": "urn:li:corpuser:barUser"}}'
```
- login to DataHub as `barUser` works.
> fix(login): Fix login error when corp user editable information is not present. Fixes #1948

- datahub-dao/src/main/java/com/linkedin/datahub/util/DatasetUtil.java
- gms/api/src/main/pegasus/com/linkedin/dataset/Dataset.pdl
- gms/api/src/main/snapshot/com.linkedin.dataset.datasets.snapshot.json
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/Datasets.java
> feat: add aspects to VALUE model of datasets

- li-utils/src/main/java/com/linkedin/common/urn/AzkabanFlowUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/AzkabanJobUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/ChartUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/CorpGroupUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/CorpuserUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DashboardUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DataPlatformUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DataProcessUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DatasetUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/MLModelUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/Urn.java
There is no consistent way of validating the type of an urn. This changes attempts to fix it.
> fix: validate entity type for an urn

- li-utils/src/main/java/com/linkedin/common/urn/AzkabanFlowUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/AzkabanJobUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/ChartUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/CorpGroupUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/CorpuserUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DashboardUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DataPlatformUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DataProcessUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/DatasetUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/MLModelUrn.java
- li-utils/src/main/java/com/linkedin/common/urn/Urn.java
This change should've been made in datahub-gma instead.
This reverts commit 127d84e3f9bc8b0638df535a594f21d8e34a508b.
> Revert "fix: validate entity type for an urn (#1958)"

- docker/docker-compose.yml
- docker/neo4j/env/docker.env
- docs/debugging.md
LinkedIn internally migrated to Neo4j 4.0. To better serve OSS, it's better to upgrade Neo4j to 4.0 here as well. The Java clients are already on 4.0 and they are compatible with 3.5 and 4.0. In this change, only Neo4j server is being upgraded from 3.5 to 4.0. If a user already has a Neo4j docker volume with a graph db created with Neo4j 3.5, with this change, that will be auto upgraded to 4.0 without any extra work.
1. Run ./docker/dev.sh without this diff (Neo4j 3.5 running). 
2. Run ./docker/ingestion/ingestion.sh to ingest sample data.
3. Stopped all containers.
4. Run ./docker/dev.sh with this diff (Neo4j 4.0 running).
5. Did tests using Neo4j browser and also confirmed that relationship tab for datasets (served by graph) is working as expected.
1. Removed all Docker containers, …
> feat: upgrade Neo4j to 4.0

- build.gradle
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataprocess/DataProcesses.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/Datasets.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpGroups.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpUsers.java
Main purpose of this change is using the latest version of datahub-gma dependency. There is one [breaking](https://github.com/linkedin/datahub-gma/commit/eca6240d110b0de27dbb8e14768e144500bce7e6) change in that version of the dependency that requires us to change the key types which we use in all of the top level resources. In this diff, all available top level resources are changed to benefit from that.
If any fork of this repo does have its own top level resource on their GMS with a complex key, they need to be changed similarly.
Locally tested by running `./docker/dev.sh` to bring up Docker containers. Then used `./docker/ingestion/ingestion.sh` to ingest some sample data. Did monkey tests on DataHub UI and confirmed no functionality is affected.
> [BREAKING] feat: Bump to datahub-gma 0.1.0

- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java
The error message was passed as a parameter for the log call but the lack of the `{}` placeholder was, as a matter of fact, excluding it from the resulting log line.
> fix: Add placeholder for logging call parameter

- build.gradle
- gms/war/build.gradle
- gms/war/src/main/webapp/WEB-INF/beans.xml
Fixes https://github.com/linkedin/datahub/issues/1966
Verified that doc page shows at http://localhost:8080/restli/docs
> feat: enable default restli documentation

- build.gradle
- metadata-builders/build.gradle
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
The other index builders need similar improvements, but after #1937 some coverage is better than no coverage.
> test: improve test coverage for DatasetIndexBuilder.

- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilder.java
- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DataProcessIndexBuilderTest.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
Tested the following way
1. Run ./docker/dev.sh with this diff
2. Ingested a new dataset using the following command
`curl 'http://localhost:8080/datasets?action=ingest' -X POST -H 'X-RestLi-Protocol-Version:2.0.0' --data '{"snapshot": {"aspects":[{"com.linkedin.common.Ownership":{"owners":[{"owner":"urn:li:corpuser:fbar","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"}}},{"com.linkedin.dataset.UpstreamLineage":{"upstreams":[{"auditStamp":{"time":0,"actor":"urn:li:corpuser:fbar"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:foo,barUp,PROD)","type":"TRANSFORMED"}]}},{"com.linkedin.common.InstitutionalMemory":{"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":0,"actor":"urn:li:corpuser:fbar"}}]}},{"com.linkedin.schem …
> refactor search index builder to store urn parts efficiently (#1937)

- datahub-web/yarn.lock
- gms/factories/src/main/java/com/linkedin/gms/factory/dataprocess/DataProcessDAOFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/dataset/DatasetDaoFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpGroupDaoFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpUserDaoFactory.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataprocess/BaseDataProcessesAspectResource.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/identity/BaseCorpUsersAspectResource.java
> refactor(gms): use BaseLocalDAO as the interface in factories & rest.li resources

- gms/api/src/main/pegasus/com/linkedin/dashboard/Chart.pdl
- gms/api/src/main/pegasus/com/linkedin/dashboard/ChartKey.pdl
- gms/api/src/main/pegasus/com/linkedin/dashboard/Dashboard.pdl
- gms/api/src/main/pegasus/com/linkedin/dashboard/DashboardKey.pdl
- li-utils/src/main/javaPegasus/com/linkedin/common/urn/ChartUrn.java
- li-utils/src/main/pegasus/com/linkedin/common/ChartUrn.pdl
- li-utils/src/main/pegasus/com/linkedin/common/DashboardUrn.pdl
- metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/chart/ChartQuery.pdl
- metadata-models/src/main/pegasus/com/linkedin/chart/ChartQueryType.pdl
- metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/ChartDocument.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/DashboardDocument.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/Snapshot.pdl
Changes in this PR are as below:
- Adding rest.li API models & resource key models
- Make ChartQueryType a separate model instead of an inline model
- Add Chart & Dashboard snapshots to Snapshot.pdl
- Make fields in chart & dashboard search document models strongly typed by using enum models instead of primitive types (we support enums in search document models)
- Remove fields which help to find relationships between dataset-chart-dashboard from search document models because we ideally surface relationships and serve relationship queries through graph not search
- Add `chartUrl` and `dashboardUrl` into chartInfo & dashboardInfo aspects
> feat(dashboard): Dashboard models update

- docs/docker/development.md
- gms/factories/src/main/java/com/linkedin/gms/factory/common/Neo4jDriverFactory.java
This PR aims at exposing Neo4j Driver Configs as env variables.
Following Variables have been exposed:
- `NEO4J_MAX_CONNECTION_POOL_SIZE`
- `NEO4J_MAX_CONNECTION_ACQUISITION_TIMEOUT_IN_SECONDS`
- `NEO4j_MAX_CONNECTION_LIFETIME_IN_HOURS`
- `NEO4J_MAX_TRANSACTION_RETRY_TIME_IN_SECONDS`
> refactor: Exposing Neo4j Driver Configs

- docs/how/kafka-config.md
1. Add topic-name configuration for each component
2. How to configure them in the deployable
> docs: Update doc for configuring topic names

- build.gradle
- metadata-models/src/test/java/com/linkedin/metadata/ModelValidation.java
- metadata-models/src/test/java/com/linkedin/metadata/ModelValidationConstants.java
Involves fixing some types. Bright side is that ModelValidation actually checks aspects now (it did not before because aspects are not records but unions!).
> Bump GMA to latest

- li-utils/src/main/javaPegasus/com/linkedin/common/urn/DataFlowUrn.java
- li-utils/src/main/javaPegasus/com/linkedin/common/urn/DataJobUrn.java
- li-utils/src/main/pegasus/com/linkedin/common/DataFlowUrn.pdl
- li-utils/src/main/pegasus/com/linkedin/common/DataJobUrn.pdl
- metadata-models/src/main/pegasus/com/linkedin/datajob/DataFlowInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/datajob/DataJobInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/datajob/DataJobInputOutput.pdl
- metadata-models/src/main/pegasus/com/linkedin/datajob/azkaban/AzkabanJobType.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DataFlowAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DataJobAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/DataFlowSnapshot.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/DataJobSnapshot.pdl
Add DataFlow and DataJob urn and aspect models.
The aspects include metadata associated with Data processing flow and job entities,
associated inputs and outputs of a job based on RFC #1820
> feat(jobs): Add DataFlow and DataJob models

- metadata-models-generator/src/main/java/com/linkedin/metadata/rythm/StreamTemplateResource.java
The connection  field with type URLConnection is not Serializable. An allegedly Serializable object with non-transient, non-serializable data members could cause program crashes. Method toURL() of URL class is deprecated.
> fix: Added transient to connection field. Replace deprecated method.

- gms/impl/src/main/resources/index/dataset/mappings.json
- gms/impl/src/main/resources/index/dataset/settings.json
Fix the unintentional rollback(#2028) of dataset index to search by field paths. Fixes #2019
Context: Refer #2019.  Dataset Index mappings defined in #2001 got overriden later by #2028.
> fix(search): Fix the unintentional rollback(#2028) of dataset index to search by field paths.

- README.md
- docs/CONTRIBUTING.md
> docs: add links to GMA repo and RFC process from relevant places

- docker/kafka-topics-ui/env/docker.env
Fixes error when acessing http://localhost:18000 where the Kafka-UI was unable to connect to Rest Proxy
> Fix for Kafka-UI Connectivity Error with Kafka-Rest Proxy

- contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/values.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/values.yaml
Support optional [initContainers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to setup extra initialization (for example creating keytab files to be used by `SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG`)
> feat(helm): add extraInitContainers

- gms/README.md
- gms/api/src/main/idl/com.linkedin.dataplatform.dataPlatforms.restspec.json
- gms/api/src/main/pegasus/com/linkedin/dataPlatforms/DataPlatform.pdl
- gms/api/src/main/snapshot/com.linkedin.dataplatform.dataPlatforms.snapshot.json
- gms/client/src/main/java/com/linkedin/dataplatform/client/DataPlatforms.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dataplatform/DataPlatforms.java
- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/DataPlatformActionRequestBuilder.java
- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/RequestBuilders.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/DataPlatformSnapshot.pdl
Convert dataPlatforms to GMA aspect models and associated resource to GMA resource.
BREAKING CHANGE: /datasets/dataPlatforms API is now changed to become GMA resource. The schema of the resource also changes.
**What breaks**: Get method of /dataset/dataPlatforms will return com.linkedin.dataPlatforms.DataPlatform schema. Earlier the API returns schema com.linkedin.dataplatform.DataPlatformInfo. 
**How to fix for existing readers**: dataPlatformInfo is a field in then new schema returned by the API. This field should be the same as previous response of the API
> (refactor): Convert dataPlatforms to GMA aspect models and associated resource to GMA resource.

- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/IndexBuildersConfig.java
Fixing the issue where ingested CorpUsers are not appearing on the frontend. This is because the CorpUsersInfo search index is not being updated, because the index builder is not registered by default. 
This is the PR where the issue was introduced: https://github.com/linkedin/datahub/pull/2024/
https://datahubspace.slack.com/archives/CUMUWQU66/p1611759465003400
> fix(User Search): Fixing CorpUsers Search Bug

- datahub-web-react/src/components/Routes.tsx
- datahub-web-react/src/components/search/SearchFilters.tsx
- datahub-web-react/src/components/search/SearchPage.tsx
- datahub-web-react/src/components/search/SearchablePage.tsx
- datahub-web-react/src/components/search/utils/constants.ts
- datahub-web-react/src/components/search/utils/filtersToQueryStringParams.ts
- datahub-web-react/src/components/search/utils/navigateToSearchUrl.ts
- datahub-web-react/src/components/search/utils/useFilters.ts
- datahub-web-react/src/components/shared/EntityTypeUtil.tsx
- datahub-web-react/src/conf/Global.tsx
Moving filters into search query params and consolidating all routing logic into shared utils.
> refactor(React Incubation): Search routing refactor

- datahub-frontend/conf/datahub-frontend.graphql
Upon check-in of [Arun's PR](https://github.com/linkedin/datahub/commit/84e952e13831033aaada9bc0582d3498f222fb95 
), we disabled the base Mutation type in datahub-graphql-core. This PR ensure that the `datahub-frontend` graph still works, removing the assumption that the Mutation type had already been registered.
> fix(GraphQL): Enable Mutation type only in frontend graph

- build.gradle
Title says it. Bumping GMA to get the changes in 0.2.40 release: https://github.com/linkedin/datahub-gma/releases/tag/v0.2.40.
> fix(integ test): Bumping GMA to 0.2.40

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/DatasetType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/DatasetMapper.java
This PR contains 2 small fixes to the GraphQL API within `datahub-graphql-core`. 
1. Map the schemaMetadata Pegasus object to the "schema" field in GQL
2. Correct format a "path" string for browse Query Type, specifically do not include "/" when the provided path array is empty.
> fix(GraphQL): Add schemaMetadata mapping & correctly form path string

- datahub-web-react/src/components/auth/LogIn.stories.tsx
- datahub-web-react/src/components/entity/dataset/profile/Lineage.tsx
- datahub-web-react/src/components/entity/dataset/profile/Profile.tsx
- datahub-web-react/src/components/entity/dataset/profile/__tests__/Lineage.test.tsx
- datahub-web-react/src/components/entity/dataset/profile/stories/Lineage.stories.tsx
- datahub-web-react/src/components/entity/dataset/profile/stories/lineageEntities.ts
Upcoming: wire this into the graphql endpoint
> feat(React Incubation): adding lineage page with sample data

- datahub-web-react/src/components/entity/dataset/profile/Ownership.tsx
- datahub-web-react/src/components/shared/ManageAccount.tsx
**Scope**
This PR only changes the incubating React app. It is part of the initiative to achieve feature parity with the existing Ember app.
**Changes**
The PR fixes broken profile links on ownership page and header (top right corner). 
Broken links
After Clicking
**Status**
> fix(React): Fix broken profile link on ownership and header

- datahub-web-react/src/components/browse/BrowseResults.tsx
- datahub-web-react/src/components/entity/dataset/profile/Lineage.tsx
- datahub-web-react/src/components/entity/dataset/profile/Profile.tsx
- datahub-web-react/src/components/entity/dataset/profile/__tests__/Lineage.test.tsx
- datahub-web-react/src/components/entity/dataset/profile/stories/Lineage.stories.tsx
- datahub-web-react/src/components/entity/dataset/profile/stories/lineageEntities.ts
- datahub-web-react/src/components/preview/DefaultPreviewCard.tsx
- datahub-web-react/src/components/search/SearchPage.tsx
- datahub-web-react/src/components/search/SearchResults.tsx
- datahub-web-react/src/graphql/dataset.graphql
In addition to the lineage change, there is a small refactor of the preview card and how it is used elsewhere in the app to better support lineage.
> feat(React): Powering lineage page through graphql endpoint

- datahub-web-react/src/components/entity/dataset/profile/Ownership.tsx
- datahub-web-react/src/components/entity/dataset/profile/Profile.tsx
- datahub-web-react/yarn.lock
**Scope**
This change only affects the incubating React App.
**Description**
We used to not be able to update the role for an owner. I've changed to experience to match the Documentation tab experience and corrected the bug.
> fix(React): Fix Dataset Ownership Role Update Bug

- .github/workflows/docker-frontend-react.yml
- datahub-frontend/play.gradle
- datahub-frontend/run/frontend.env
- datahub-frontend/run/run-local-frontend
- datahub-web-react/.env
- datahub-web-react/package.json
- datahub-web-react/src/App.tsx
- docker/README.md
- docker/datahub-frontend/Dockerfile
- docker/docker-compose.react.yml
- docker/docker-compose.yml
- docker/quickstart-react.sh
**Scope**
This PR introduces a new Docker compose extension file (docker-compose.react.yml) that can be used to deploy a version of `datahub-frontend` configured for serving the incubating React app. All changes are backward compatible. 
**Details**
As background: we'd like to enable the following flows: 
1. Spin up all of datahub system with react ui (quickstart script)
2. Spin up datahub-system with *both* react and ember app 
3. Spin up only datahub react and required dependencies (docker-compose)
So that folks can more easily contribute to the React App as well as perform side-by-side deployment of React & Ember. 
To support this, I have introduced an optional container called `datahub-frontend-react` that is defined within a compose extension file `docker-compose.react.yml`. …
> feat(React): Serve React via Docker

- docker/docker-compose.graphql-service.yml
- docker/docker-compose.yml
`datahub-gms-graphql-service` is a nascent service that exposes a GMS GraphQL API (code under `datahub-graphql-core`). It was added to the default docker-compose.yml file some commits ago ([PR](https://github.com/linkedin/datahub/pull/2071/files)), however there is no registered repo in the LinkedIn Docker Hub so people trying to build `docker-compose.yml` are being forced to build locally. 
Since this is a very new service not on the critical path, we will remove the service from `docker-compose.yml` for now.
> bug(docker): Removing datahub-gms-graphql-service from default docker-compose.yml

- datahub-graphql-core/src/main/resources/gms.graphql
**Scope**
This PR affects the GMS GraphQL schema located within `datahub-graphql-core`. Implementation of this schema to coming in followup PR. 
**Changes**
In this PR, I have transposed the GMS concepts of Dashboard + Chart into GQL.
> feat(GraphQL API): Adding Dashboard + Chart Models

- metadata-ingestion/README.md
- metadata-ingestion/examples/airflow/generic_recipe_sample_dag.py
- metadata-ingestion/examples/airflow/mysql_sample_dag.py
>  docs(ingest): add example DAGs for Airflow

- .github/workflows/docker-frontend-react.yml
- docker/datahub-frontend/Dockerfile
- docker/docker-compose.react.yml
A build arg syntax issue is causing the `datahub-frontend:react` image to ignore the correct port arg (defaulting to 9001 instead of 9002). This PR should resolve the issue.
> bug(docker react): Fix react docker image build

- datahub-frontend/run/run-local-frontend
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsClientFactory.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/load/LoadableTypeBatchResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/ChartType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/DashboardType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/DatasetType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/ChartMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/DashboardMapper.java
- datahub-graphql-core/src/main/resources/gms.graphql
- gms/api/src/main/pegasus/com/linkedin/dashboard/Chart.pdl
- gms/api/src/main/pegasus/com/linkedin/dashboard/Dashboard.pdl
- gms/api/src/main/snapshot/com.linkedin.chart.charts.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dashboard.dashboards.snapshot.json
- gms/client/src/main/java/com/linkedin/chart/client/Charts.java
- gms/client/src/main/java/com/linkedin/dashboard/client/Dashboards.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dashboard/Charts.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/dashboard/Dashboards.java
- metadata-ingestion-examples/mce-cli/example-bootstrap.json
**Scope**
This PR primarily is scoped to the GQL API within`datahub-graphql-core`. 
However, there are a few changes at GMS layer: 
- updated value PDLs for Chart + Dashboard to add their respective URNs. Other value models do include urns, so I've added for consistency (and to avoid the client having to know how to construct urns). 
- implemented gms "client" classes for Dashboards and Charts.
**Changes**
1. Added GraphQL implementation in datahub-graphql-core. 
2. Added Dashboards GMS client
3. Added Charts GMS client
4. Added URN field to Dashboard.pdl and Chart.pdl (These models are not available via the frontend and had no client previously so I don't think anyone is actively using them)
5. Added mock entity dashboard / chart entities to the ingestion example dataset. 
**Validation** …
> feat(GraphQL API): GQL implementation of Charts + Dashboards

- datahub-web-react/src/app/shared/ManageAccount.tsx
**Scope**
This PR changes all page that includes the header bar. 
**Changes**
This PR adds new feature which pops up a menu when hovering on profile on top right corner of the page. Currently, there is only 1 option, that is to log out. After this option is clicked, user session is cleared and users are redirected to the login page. 
_This PR also contains a overwritten changes in https://github.com/linkedin/datahub/pull/2095 where multiple clicking on the profile will redirect users to url like "user/user/user/user/..."_
> feat(React): Avatar dropdown menu and logout function

- datahub-web-react/src/app/search/SearchablePage.tsx
- datahub-web-react/src/app/useGetAuthenticatedUser.tsx
**Scope**
This change fixes a small react app issue where the logged in user profile does not show any information. 
**Changes**
Added a hook wrapper for fetching details about the currently authenticated user. Use this hook to popular the URN, profile picture of the currently logged in user.
> fix(React): Fix authenticated user profile

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
- datahub-web-react/src/app/search/SearchBar.tsx
- datahub-web-react/src/app/search/SearchFilters.tsx
- datahub-web-react/src/app/search/SearchPage.tsx
- datahub-web-react/src/app/search/__tests__/SearchPage.test.tsx
- datahub-web-react/src/utils/test-utils/TestPageContainer.tsx
This PR
Introduces tests for search facet filtering
Fixes mock search data so it can be used properly with tests, and enforcing that it will stay correct in the future
Fixes bug where selecting multiple filters provides a broken UI experience.
Fixes key warnings across other tests
> fix(React): Adding test coverage for search page & fixing filter select bug

- datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx
- datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx
**Scope**
This change only impacts the React app. 
**Changes**
Simply add a button to Chart / Dashboard profile that redirects user to the chart / dashboard link. See screenshots below.
> feat(React): Add URL link to dashboard / chart page

- docker/docker-compose.dev.yml
- docker/elasticsearch-setup/Dockerfile
- docker/elasticsearch-setup/create-indices.sh
Make it easy to test mapping/setting.json changes by adding an elasticsearch-setup:debug image to docker-compose.dev.yml 
The overridden elasticsearch-setup container mounts the local mapping/setting.json files and uses them to create indices. 
Followed the method used in the dev setup for gms/mae-consumer/mce-consumer containers
**Test**
`./docker/dev.sh` runs correctly and confirmed that the local changes to mappings got picked up
Running the prod path by doing the following (Thanks @jplaisted)
```
cd docker
./nuke.sh # start from scratch to really verify things
docker compose pull # pull latest images
docker image rm docker_elasticsearch-setup # delete pulled image
docker-compose build elasticsearch-setup # rebuild image
docker-compose -p datahub up # launch docker without pulling
``` …
> refactor(docker-dev): set up elasticsearch using local mapping on docker-compose.dev

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/DatasetMapper.java
- datahub-graphql-core/src/main/resources/gms.graphql
- datahub-web-react/src/app/entity/dataset/profile/stories/sampleDataset.ts
- datahub-web-react/src/graphql/chart.graphql
- datahub-web-react/src/graphql/dataset.graphql
- datahub-web-react/src/graphql/search.graphql
This fixes a bug in the GraphQL API where Dataset model had required "created" and "lastModified" timestamps. This was initially modeled as such because it was based off of the [Dataset.pdl](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/Dataset.pdl) model, which includes ChangeAuditStamp _which are never populated_. 
In order to populate, we were incorrectly using the SchemaMetadata timestamps, which will break reads if SchemaMetadata has not been provided for a Dataset. Fixing by removing these timestamps from the Dataset GQL model to match [Dataset.pdl](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/Dataset.pdl) served by GMS. 
Note that these fields were not actively consumed by any client …
> fix(GraphQL): Fixing required Dataset audit stamps bug 

- build.gradle
- repositories.gradle
Bintray is set for deprecation and EoL in a few months.
We still need bintray for pegasus until restli team migrates off of it.
> Switch GMA dep from bintray to artifactory.

- build.gradle
- gms/impl/build.gradle
Bumping version of neo4j-java-driver to include encryption support that came in 4.0.1.
Also neeed to compile neo4j-java-driver in gms as well to include it in the WAR.
> feat: neo4j Bolt TLS support (#2100)

- .dockerignore
- metadata-ingestion/scripts/ci.sh
> build(docker): add large generated directories to dockerignore

- datahub-web-react/src/app/Routes.tsx
- datahub-web-react/src/conf/Global.tsx
Starting the react app locally opens /assets by default. For a smoother dev experience, we'll redirect /assets to the homepage so developers aren't defaulted to a 404 page.
> feat(react): redirecting `/assets` to `/`

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
- datahub-web-react/src/app/search/EntitySearchResults.tsx
- datahub-web-react/src/app/search/utils/filtersToGraphqlParams.ts
Facet params need to be in a comma separated string in order for multiple to be applied at once. They are propagated directly to elastic search, and this is the format elastic search expects. Updated the test mocks to correctly reflect what elastic expects.
> fix(react): fixing format we propagate filters to graphql in

- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
Makes username/password/database config properties optional to allow sqlachemy to connect with alternative authentication methods such as kerberos.
This was tested by specifying only the mandatory host_port config and then passing extra required properties through the `options` map which is specific to each `<SQL database, Auth Method>` combination.
> feat(ingest): Support alternative authentication in sql ingestion

- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/integration/mysql/mysql_mce_golden.json
- metadata-ingestion/tests/integration/mysql/setup/setup.sql
- metadata-ingestion/tests/integration/mysql/test_mysql.py
- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/test_helpers/fs_helpers.py
> feat(ingest): capture table descriptions

- docker/datahub-ingestion/Dockerfile
This will reduce the final image size a bit.
> build(ingest): use multistage build for datahub-ingestion

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/browse/BrowsePathsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/browse/BrowseResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchResolver.java
Including underlying exception in GQL resolver exceptions. Useful for debugging.
> fix(GraphQL): Bubbling up exceptions logged in GraphQL resolvers

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/configuration/kafka.py
> docs(ingest): clarify Kafka connection config

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/ChartType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/DashboardType.java
- datahub-web-react/src/app/entity/chart/ChartEntity.tsx
- datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
- datahub-web-react/src/graphql/browse.graphql
- gms/client/src/main/java/com/linkedin/chart/client/Charts.java
- gms/client/src/main/java/com/linkedin/dashboard/client/Dashboards.java
**Scope**
These changes are limited to datahub-frontend GraphQL API and the React app.
**Changes**
This PR implements the UI for Browse Charts and Dashboards. It builds on[ Dexters PR](https://github.com/linkedin/datahub/pull/2143) that implemented this functionality on the GMS side. 
- Make ChartType, DashboardType a BrowsableType. 
- Extend client side browse query to include Charts, Dashboards. 
- Fix minor URN type bug in GMS client.
> feat(React): Impl browse UI for Dashboards and Charts

- metadata-ingestion/README.md
Also moves the migration guides to the bottom of the page and adds the host_port option for SQL Server.
> docs(ingest): clarify setuptools requirement

- README.md
- docs-website/README.md
- docs-website/generateDocsDir.ts
- docs/demo.md
Streamlines the readme and points links towards the hosted docs site.
> docs: point to hosted docs site

- datahub-web-react/.eslintrc.js
- datahub-web-react/src/app/entity/dataset/profile/__tests__/Schema.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
- datahub-web-react/src/app/entity/dataset/profile/stories/sampleSchema.ts
Table schema now has `View Raw` button:
And that takes you to a raw view:
> feat(react): adding raw schema view option for table schemas

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/home/__tests__/HomePage.test.tsx
- datahub-web-react/src/utils/test-utils/TestPageContainer.tsx
**Scope**
This change only affects the React app. 
**Changes**
This change includes new react tests for the homepage.
> test(React): Home page tests

- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
- datahub-web-react/src/app/entity/tag/__tests__/TagProfile.test.tsx
The source of the first issue was here:
https://github.com/linkedin/datahub/commit/adfe60e97a824dbd318f6fd5de18ec1a08ba6343#diff-5c20ca9f49771819e70acc9b2f908109988f1010d07b0dca6413827716495b50L5
I removed the styles import in the tags pr because I removed the last `styled` component in that file in the commit. However, in https://github.com/linkedin/datahub/pull/2179, the styled import was needed for new styling being added. #2179 was merged first, so when #2164 landed it removed the import.
The source of the second issue was here:
https://github.com/linkedin/datahub/pull/2184/files#diff-350db4e8bd35a6898bda713bffb601ed934b67166cf9add1d4abf32c3829e616R14
#2184 altered test data that was referenced in #2179. When #2179 and #2184 landed, the test data was altered but the assertions were …
> fix(react): fixing test issues that arose from ill-timed merges

- contrib/elasticsearch/es7-upgrade/transfer.py
This script is by no means comprehensive, but seems to be working well for LI.
> (feat) Simple python script to carry over ES indices from 5 to 7.

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mappers/SchemaFieldMapper.java
**Scope**
The GraphQL API 
**Changes**
This change fixes a bug in the GraphQL API where the "fixed" data type is not included in the mapping. Also improves the error message logged so that we can tell exactly which type doesn't match going forward. 
**Acknowledgements**
Thanks to Ming Jiang for finding this!
> fix(GraphQL API): Add "fixed" SchemaFieldDataType mapping 

- .github/workflows/docker-frontend-react.yml
- .github/workflows/docker-frontend.yml
- .github/workflows/docker-gms.yml
- .github/workflows/docker-ingestion.yml
- .github/workflows/docker-mae-consumer.yml
- .github/workflows/docker-mce-consumer.yml
- docker/docker-compose.react.yml
Changes included in PR
1. Add short SHA based tagging for pushes to master. Solves issue https://github.com/linkedin/datahub/issues/2162
2. Upgrade to v2 of docker/build-and-push-action which simplifies our workflow
3. Make sure the push actions do not run when docker password is not set
> feat(ci): Add SHA based tagging before pushing to docker registries

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
> feat(ingestion): add option for optimized skipping of schemas

- datahub-web-react/craco.config.js
- datahub-web-react/src/App.tsx
- datahub-web-react/src/conf/theme/theme_dark.config.json
- datahub-web-react/src/conf/theme/theme_light.config.json
The complexity of removing the less `@` prefixes in react introduced build issue- I'm moving that logic out into the craco.config.js file so the types are simpler on the react side.
This should have been caught in CI, but the build failure did not cause CI to fail:
https://github.com/linkedin/datahub/runs/2062749573#step:6:1145
Corrective action: ensure that build failures in react will cause CI to fail (#2217)
> fix(react): fixing theming test in react

- datahub-web-react/package.json
When our build script was delimitated by semicolons, errors to build would not prevent the gradle script from completing. This meant certain build issues that (a) did not fail any tests and (b) did not cause any lint issues could slip by. Such an example was:
https://github.com/linkedin/datahub/pull/2215
> ci(react): fail CI on build errors

- .github/workflows/datahub-kafka-setup.yml
- .github/workflows/docker-elasticsearch-setup.yml
Add git workflows to upload docker for elasticsearch and kafka setup.
Once latest version of Images for these two is uploaded, I will put out the PR to use the images on dockerhub instead of cached images.
> fix(es-setup): Add git workflows to upload docker for elasticsearch and kafka setup

- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
If there is no raw schema, or the raw schema is empty, do not show `Raw` button
> feat(react): hiding raw schema button when no raw schema exists

- datahub-web-react/package.json
With CI=true, we fail on warnings
> fix(react): setting CI to false for builds

- .github/workflows/datahub-kafka-setup.yml
- .github/workflows/docker-elasticsearch-setup.yml
Apparently, paths and paths_ignore can't both be set.
> fix(es-setup): Remove paths ignore for es/kafka-setup git workflows

- docker/docker-compose.yml
Added the new docker images created for elasticsearch-setup and kafka-setup. 
Tested on local env after nuking. It gets latest versions of mappings and settings and both tasks finish successfully.
> fix(es-setup): Added images to es/kafka-setup

- docker/datahub-gms/start.sh
- docker/datahub-mae-consumer/start.sh
- docker/datahub-mce-consumer/start.sh
- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/KafkaConfig.java
Fixes #2225
If we set KAFKA_BOOTSTRAP_SERVERS as a comma separated list of brokers, we need to wait for each one separately.
> fix(kafka-servers): Fix the issue of gms/mae/mce not starting when multiple kafka servers are set

- contrib/elasticsearch/es7-upgrade/Dockerfile
- contrib/elasticsearch/es7-upgrade/transfer.py
- docs/advanced/es-7-upgrade.md
The script requires ssl configuration even if we disable ssl. Update the script to take optional disable-ssl params for source and destination. 
Add simple Dockerfile to run a docker container that runs the script. 
Update migration doc with recommendations on how to migrate to es7.
> feat(es-7-migration): Update script and migration docs and add a simple Dockerfile

- gms/impl/src/main/resources/datasetESSearchQueryTemplate.json
- gms/impl/src/main/resources/index/dataset/mappings.json
- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/DatasetDocument.pdl
Add search by tags functionality for datasets where if the user queries for a tag, it shows all datasets with the given tag. 
Note, it does not look at the tags of the schema fields.
Also note, query "tags:Legacy" and "Legacy" both work.
> feat(tags): Enable search for datasets by tags

- datahub-web-react/src/app/entity/dataset/profile/DatasetProfile.tsx
Viewing the schema is more likely the primary use case for visiting a dataset profile than viewing ownership- for this reason we should switch the order of the tabs
> feat(react): moving schema tab to be default

- datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx
- datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx
Charts & dashboards had some custom non-themable css. Removing that here so they can also be configured by the global theme.
> fix(react): enabling charts and dashboards to be supported by theme

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/DatasetType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/tag/TagType.java
Dataset was incorrectly using the result of `getActor`, and that error was duplicated over to TagsType when I copied the logic. Addressing them both here.
> fix(tags): fix ownership on tag create

- datahub-web-react/src/app/shared/tags/AddTagModal.tsx
- gms/impl/src/main/resources/datasetESSearchQueryTemplate.json
- gms/impl/src/main/resources/index/dataset/mappings.json
- gms/impl/src/main/resources/index/tags/settings.json
Accomplishes two things:
1) allows searching by tags using prefix-matching if they didn't search for the full tag name
2) starts autocomplete earlier when search for tags in the add tag flow
> feat(tags): improving elastic search templates for tags

- datahub-web-react/src/app/browse/BrowseResultCard.tsx
- datahub-web-react/src/app/browse/BrowseResults.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/AllEntitiesSearchResults.tsx
- datahub-web-react/src/app/search/BrowseEntityCard.tsx
- datahub-web-react/src/app/search/EntityGroupSearchResults.tsx
- datahub-web-react/src/app/search/EntitySearchResults.tsx
- datahub-web-react/src/conf/theme/theme_light.config.json
- datahub-web-react/src/conf/theme/types.ts
- docker/quickstart-ember.sh
**Scope**
React app
**Changes**
Adding box shadow as theme option, and using for the cards throughout the UI. See screenshots below.
> feat(React): Styling: Adding box shadow to theme + deeper linear gradient

- datahub-web-react/src/app/shared/EntityProfile.tsx
Long descriptions pushed the tag module to the side because it didn't have a min-width.
fixed version:
> fix(tags): fixing margins on tags for long descriptions

- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
Now, the result looks natural without tags, and with them:
> fix(react): fixing search result formatting issues

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/home/__tests__/HomePage.test.tsx
Search suggestions are fetched from elastic by querying for `*` and then randomizing the order of the result
> feat(react): show search suggestions

- datahub-web-react/src/app/entity/user/UserProfile.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/utils/customGraphQL/useGetAllEntitySearchResults.ts
useGetAllEntitySearchResults is not referentially equal even when the apollo cache hasn't changed. we cant depend on it- removing it from the dependency array for recalculating suggestions.
> fix(react): fix randomizing suggestions on autocorrect

- datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx
- datahub-web-react/src/app/shared/EntityProfile.tsx
The header layout used to look strange on small viewport sizes. This change improves that:
wide layout remains the same:
> feat(react): updating entity layouts to be friendly to smaller viewport sizes

- docker/datahub-frontend/Dockerfile
Should fix the issue shown here: https://github.com/linkedin/datahub/runs/2172716066?check_suite_focus=true#step:6:4499. Not a best practice violation since there's another `USER datahub` directive later in the Dockerfile. Tested locally.
> fix: remain as root until final datahub-frontend build stage

- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- gms/war/src/main/webapp/WEB-INF/web.xml
frontend, mae/mce-consumers already have an exposed healthcheck end point, but GMS does not. This PR adds a simple healthcheck end point for GMS and adds HEALTHCHECK commands for the datahub docker images. 
Tested locally and all containers are marked healthy.
> feat(healthcheck): Add healthchecks to datahub docker images

- metadata-ingestion/src/datahub/ingestion/source/druid.py
Modifies druid dataset URNs to exclude the table name since that is duplicated by the platform urn.
I.e, for a druid datasource called data.jobexecutionview (in the druid console UI):
- old Urn: `"urn:li:dataset:(urn:li:dataPlatform:druid,druid.data.jobexecutionview,PROD)"`
- new Urn: `"urn:li:dataset:(urn:li:dataPlatform:druid,data.jobexecutionview,PROD)"`
> fix(ingest): Add druid-specific identification logic

- metadata-ingestion/examples/mce_files/bootstrap_mce.json
- metadata-ingestion/setup.py
- See https://github.com/hsheth2/avro_gen/compare/d350c70587210e3b29e01e5c42673f010044d254...c8a4eeeddeef4816acf8d055e6623013fc23680e.
- Also removes the dependency on the `frozendict` library, which is outdated and unmaintained. See https://github.com/slezica/python-frozendict/issues/25.
> fix(ingest): resolve array serialization bug

- datahub-web-react/src/app/home/HomePageHeader.tsx
Here is the new no-data layout, improves padding and hides `try searching for...`
> fix(react): improving layout of no data state

- metadata-ingestion/src/datahub/emitter/kafka_emitter.py
Hotfix for a breaking change introduced by https://github.com/confluentinc/confluent-kafka-python/pull/1000. We will remain compatible with both new and old versions of `confluent_kafka`.
> fix(ingest): hotfix for breaking change from confluent_kafka

- docker/mysql-setup/Dockerfile
- docker/mysql-setup/init.sql
MySQL docker container has a way of inputting a set of SQL commands to be run as the container is starting up. However, this is not the case when hooking up an external MySQL server. 
The mysql-setup docker container runs the init.sql scripts on the inputted MySQL server, which creates the datahub database and adds the tables needed to start up Datahub. 
Note, I am not adding it to docker-compose since it is not needed for local development.
> feat(docker): Add dockerfile for initializing an existing mysql server

- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
Remove block to make sure the tag doesn't fill the whole vertical.
> fix(search-by-field): Fix styling for column match snippet

- contrib/kubernetes/datahub/charts/datahub-frontend/README.md
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/config-jmx-exporter.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/values.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/README.md
- contrib/kubernetes/datahub/charts/datahub-gms/templates/config-jmx-exporter.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/values.yaml
- contrib/kubernetes/datahub/charts/datahub-jmxexporter/Chart.yaml
- contrib/kubernetes/datahub/charts/datahub-jmxexporter/templates/_container.tpl
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/README.md
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/config-jmx-exporter.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/README.md
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/config-jmx-exporter.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/values.yaml
- docker/datahub-gms/Dockerfile
- docker/datahub-gms/start.sh
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mae-consumer/start.sh
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-mce-consumer/start.sh
Fixes https://github.com/linkedin/datahub/issues/2214
Added JMX exporter container to Helm charts.
Also added JVM_OPTS and JMX_OPTS to such that it is easy to configure the JMX on the original container.
> feat(Kubernetes): Add JMX exporter containers to all DataHub components

- gms/client/src/main/java/com/linkedin/tag/client/Tags.java
- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/RequestBuilders.java
- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/TagActionRequestBuilder.java
We are able to create tags based on MCE's because the relevant `ActionRequestBuilder` is not listed in the `RequestBuilders`. This PR fixes that issue. We also rename the class to conform with the convention set by the sibling classes.
> feat(tags): Support creating tags with MCE

- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/DataFlowActionRequestBuilder.java
- metadata-dao-impl/restli-dao/src/main/java/com/linkedin/metadata/dao/DataJobActionRequestBuilder.java
We fix a couple of typos in the the `BASE_URI_TEMPLATE` for both DataJob and DataFlow
> feat(datajob): Fix URI templates for datajob and dataflow

- README.md
- docs-website/docusaurus.config.js
- docs-website/src/pages/index.js
- docs/CODE_OF_CONDUCT.md
- docs/faq.md
- docs/roadmap.md
- docs/slack.md
> doc: update slack links to https

- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/api/closeable.py
- metadata-ingestion/src/datahub/ingestion/api/registry.py
- metadata-ingestion/tests/integration/ldap/test_ldap.py
- metadata-ingestion/tests/integration/mongodb/test_mongodb.py
- metadata-ingestion/tests/integration/mysql/test_mysql.py
- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/unit/test_check.py
- metadata-ingestion/tests/unit/test_plugin_system.py
Also adds tests for the Registry class and creates a pytest mark for the slow integration tests. Follow up to #2316.
> feat(ingest): verify dynamic registry types at runtime

- contrib/metadata-ingestion/python/looker/dashboard_ingestion/README.md
- contrib/metadata-ingestion/python/looker/dashboard_ingestion/looker_dashboard_ingestion.py
- contrib/metadata-ingestion/python/looker/dashboard_ingestion/requirements.txt
- contrib/metadata-ingestion/python/looker/lookml_ingestion/README.md
- contrib/metadata-ingestion/python/looker/lookml_ingestion/lookml_ingestion.py
- contrib/metadata-ingestion/python/looker/lookml_ingestion/requirements.txt
Adds (very experimental) support for ingesting Looker metadata (views, charts, dashboards) into datahub through scraping LookML and scraping the Looker API. 
SpotHero built this POC a few months ago before datahub officially supported ingesting dashboards into datahub. As a workaround, we created "virtual" datasets corresponding to Looker dashboards/charts so we could test out lineage between dashboards. 
We are sharing these scripts since there is some interest around ingesting Looker metadata into datahub, but SpotHero does not have the time to robustly build this support out. If others are curious and want to try ingesting Looker metadata, this would be a good place to start!
> Add looker metadata ingestion examples

- docker/elasticsearch-setup/create-indices.sh
- gms/impl/src/main/resources/index/chart/settings.json
- gms/impl/src/main/resources/index/corp-user/settings.json
- gms/impl/src/main/resources/index/dashboard/settings.json
- gms/impl/src/main/resources/index/data-process/settings.json
- gms/impl/src/main/resources/index/dataflow/settings.json
- gms/impl/src/main/resources/index/datajob/settings.json
- gms/impl/src/main/resources/index/dataset/settings.json
- gms/impl/src/main/resources/index/ml-model/settings.json
- gms/impl/src/main/resources/index/tags/settings.json
> feat(es-setup): add logic in elasticsearch setup to compare-and-update index if already exists

- metadata-ingestion/README.md
- metadata-ingestion/examples/recipes/glue_to_datahub.yml
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/glue.py
- metadata-ingestion/tests/unit/test_glue_source.py
Adding Glue ingestion support.
> feat: adding support for glue

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/lineage/__tests__/adjustVXTreeLayout.test.tsx
- datahub-web-react/src/app/lineage/dev/complicated_lineage_mces.json
- datahub-web-react/src/app/lineage/utils/adjustVXTreeLayout.ts
Fixes two issues that arose when an entity had dependencies on multiple entities at multiple levels of the dependency tree.
Included another test case to catch this issue as well as an interconnected lineage mce file to help with debugging and local development.
> fix(lineage): fixing lineage layout bugs + adding additional test case

- docker/docker-compose.override.yml
- docker/mariadb/docker-compose.mariadb.yml
- docker/mysql/docker-compose.mysql.yml
- docker/postgres/docker-compose.postgres.yml
Only the DB containers had `restart: always` specified. This will make the behavior consistent across all the containers. Also fixes a typo: postgre -> postgres.
> fix: remove `restart: always` from docker-compose for consistency

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/ingestion/source/glue.py
- metadata-ingestion/tests/unit/test_allow_deny.py
> fix(ingest): add support for database and table patterns to glue source

- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/LineageTreeNodeAndEdgeRenderer.tsx
- datahub-web-react/src/app/lineage/LineageViz.tsx
- datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
- datahub-web-react/src/app/lineage/types.ts
- datahub-web-react/src/app/lineage/utils/adjustVXTreeLayout.ts
- datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
When we are not able to expand out all the dependencies of a node, we will show a ghost edge indicating a dependency does exist. This dependency can then be viewed when the user focuses on that node specifically.
> feat(lineage): adding ghost edges indicating hidden dependencies

- datahub-web-react/src/app/lineage/LineageViz.tsx
This marker was removed in consecutive merging of a few lineage followups. This adds it back in.
> fix(lineage): add upstream arrows back in

- metadata-builders/src/main/java/com/linkedin/metadata/builders/graph/RegisteredGraphBuilders.java
- metadata-builders/src/main/java/com/linkedin/metadata/builders/graph/TagGraphBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/graph/TagGraphBuilderTest.java
- metadata-testing/metadata-models-test-utils/src/main/java/com/linkedin/metadata/testing/Urns.java
We add a tag graph builder so that tags can be ingested properly.
> feat(tags): Add tag graph builder

- metadata-ingestion/setup.py
Now that https://github.com/googleapis/python-bigquery-sqlalchemy/pull/116 has been merged and version 0.6.0 has been released, we no longer need to install `pybigquery` from source via Git.
> fix(ingest): bump pybigquery version

- metadata-ingestion/plugin_requirements.txt
We have already transitioned to using setup.py extra requirements
instead of this separate file. I must've missed this file as part of
those changes.
> chore(ingest): remove unused `plugin_requirements.txt` file

- contrib/metadata-ingestion/python/looker/dashboard_ingestion/requirements.txt
We update pyyaml to >=5.4 as lower version includes a [vulnerability](https://github.com/advisories/GHSA-8q59-q68h-6hv4) and our dependabot doesn't like it.  
Unfortunatley, I dont have a easy way of testing this. Ping @grantatspothero.
> feat(ingestion): Update pyyaml

- datahub-gms-graphql-service/README.md
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsClientFactory.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataflow/DataFlowType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataflow/mappers/DataFlowMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datajob/DataJobType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datajob/mappers/DataJobMapper.java
- datahub-graphql-core/src/main/resources/gms.graphql
We add GraphQL Query functionality for the DataJob and DataFlow entities.
> feat(datajob): Datajob graphql query

- metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
- metadata-ingestion/tests/unit/test_schema_util.py
> fix(ingestion): properly detect optional fields in avro schemas

- datahub-web-react/src/app/entity/Entity.tsx
- datahub-web-react/src/app/entity/EntityPage.tsx
- datahub-web-react/src/app/entity/EntityRegistry.tsx
- datahub-web-react/src/app/entity/chart/ChartEntity.tsx
- datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
- datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
- datahub-web-react/src/app/entity/tag/Tag.tsx
- datahub-web-react/src/app/entity/user/User.tsx
- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- datahub-web-react/src/app/lineage/LineageViz.tsx
- datahub-web-react/src/app/lineage/LineageVizInsideZoom.tsx
- datahub-web-react/src/app/lineage/__tests__/LineageTree.test.tsx
- datahub-web-react/src/app/lineage/__tests__/adjustVXTreeLayout.test.tsx
- datahub-web-react/src/app/lineage/__tests__/constructTree.test.ts
- datahub-web-react/src/app/lineage/types.ts
- datahub-web-react/src/app/lineage/utils/constructTree.ts
- datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
- datahub-web-react/src/app/lineage/utils/getChildren.ts
- datahub-web-react/src/app/lineage/utils/useGetEntityQuery.ts
- datahub-web-react/src/app/lineage/utils/useLazyGetEntityQuery.ts
- datahub-web-react/src/graphql/chart.graphql
- datahub-web-react/src/graphql/dashboard.graphql
- metadata-ingestion/plugin_requirements.txt
- metadata-ingestion/setup.py
Initially, the lineage viz only supported dataset <> dataset relationships. This adds support for onboarding any type of entity to the lineage graph.
> feat(lineage): support arbitrary entity types in lineage viz

- datahub-web-react/src/app/browse/BrowseResults.tsx
- datahub-web-react/src/app/entity/user/UserDetails.tsx
> feat(react): add null state indicator in user profile when no entities

- metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
- metadata-ingestion/tests/unit/test_schema_util.py
> fix(ingestion): dont crash on non-RecordSchema topics

- contrib/kubernetes/datahub/Chart.yaml
- contrib/kubernetes/datahub/README.md
- contrib/kubernetes/datahub/charts/datahub-frontend/README.md
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/ingress.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/secrets.yaml
- contrib/kubernetes/datahub/charts/datahub-frontend/values.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/README.md
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/templates/secrets.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/README.md
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/values.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/README.md
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/values.yaml
- contrib/kubernetes/datahub/templates/kafka-setup-job.yml
- contrib/kubernetes/datahub/templates/mysql-setup-job.yml
- contrib/kubernetes/datahub/values.yaml
List of changes:
1. Add readiness/liveness probes for all datahub pods (with correct initial delay and period)
2. Remove file dependencies in main datahub chart (Since all subcharts are under the chart/ directory there is no need to specify file dependencies)
3. Add redirect paths to frontend ingress (Can be used for ssl-redirects)
4. Change frontend port to 9002
5. Add setup jobs for kafka and mysql
> feat(k8s): Update pods with correct probes and remove unnecessary dependencies

- docker/kafka-setup/Dockerfile
- gms/factories/src/main/java/com/linkedin/gms/factory/dashboard/ChartDaoFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/dashboard/DashboardDaoFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/datajob/DataFlowDAOFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/datajob/DataJobDAOFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/ml/MLModelDAOFactory.java
- gms/factories/src/main/java/com/linkedin/gms/factory/tag/TagDaoFactory.java
- metadata-dao-impl/kafka-producer/src/main/java/com/linkedin/metadata/dao/producer/KafkaMetadataEventProducer.java
- metadata-ingestion-examples/kafka-etl/src/main/java/com/linkedin/metadata/examples/kafka/KafkaEtl.java
TopicConvention was created to define how the topic names are decided. It was not being referenced by a lot of DAOs i.e. they were using the defaults even though the topic name is specifically set.
Changes:
1. Fix the above issue. Remove the constructor with default TopicConvention to prevent future issues.
2. Add the ability to set topic name for kafka-setup job
** Test **
Deployed locally. Works correctly when topic names are set.
> fix(kafka-topic-convention): Fix DAOs that do not refer to TopicConvention

- contrib/kubernetes/datahub/templates/elasticsearch-setup-job.yml
- contrib/kubernetes/datahub/templates/kafka-setup-job.yml
- contrib/kubernetes/datahub/templates/mysql-setup-job.yml
Add ability to add service accounts to setup jobs. Note if not set, doesn't change.
> feat(k8s): Add ability to add service accounts to setup jobs

- docker/mysql-setup/Dockerfile
- docker/mysql-setup/init.sh
- docker/mysql-setup/init.sql
Add the ability to specify database name for mysql-setup
Does a simple string replace on the init.sql to change the db name.
> feat(mysql-setup): Add the ability to specify database name for mysql-setup

- gms/impl/src/main/java/com/linkedin/metadata/resources/tag/Tags.java
Description is optional. If we try to set it when the value is null in the aspect, GMS will raise an error
> fix(tags): check description existence on tags

- datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx
This makes access to pictureLink in charts & dashboards safe in the case no editableInfo aspect exists.
> fix(react): fix access to pictureLink in charts and dashboards

- docker/kafka-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/mysql-setup/init.sh
Fix env variable setup for kafka/mysql-setup docker containers
> fix(setup-jobs): Fix env variable setup for kafka/mysql-setup docker containers

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/src/datahub/ingestion/source/glue.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/ldap.py
- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/integration/ldap/ldap_mce_golden.json
- metadata-ingestion/tests/test_helpers/docker_helpers.py
- metadata-ingestion/tests/unit/serde/test_serde.py
- metadata-ingestion/tests/unit/test_glue_source.py
- Gets rid of the `@overload` hack that was used to make static types work
- Ensures arguments to the constructor are set properly
- Enables normal `==` equality checks between objects
- Fixes a hack used in the glue test to check equality
> fix(ingest): streamline codegen init methods

- metadata-ingestion/examples/mce_files/bootstrap_mce.json
The sample MCEs construct an airflow dag with two tasks, each constructing another table in our sample data.
> feat(datajobs+dataflows): adding sample mces for dataflows and datajobs

- datahub-web-react/src/app/shared/EntityProfile.tsx
- datahub-web-react/src/app/shared/avatar/CustomAvatar.tsx
> feat(react): add padding between tags and description on datasets profile page

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/lineage/__tests__/adjustVXTreeLayout.test.tsx
- datahub-web-react/src/app/lineage/dev/complicated_lineage_mces.json
- datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts
- datahub-web-react/src/app/lineage/utils/constructTree.ts
This change makes the lineage viz ignore circular dependencies in downstream or upstream lineage. This prevents the hierarchy library we use from entering an infinite loop.
> fix(lineage): allow lineage viz to handle circular dependencies

- contrib/kubernetes/datahub/README.md
- contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
- contrib/kubernetes/datahub/templates/elasticsearch-setup-job.yml
- contrib/kubernetes/datahub/templates/kafka-setup-job.yml
- contrib/kubernetes/datahub/templates/mysql-setup-job.yml
- contrib/kubernetes/datahub/values.yaml
Add the same credentials setup for kafka-setup-job used in gms, mae/mce-consumer jobs. 
Change name of the config override from springKafkaConfigurationOverrides to kafkaConfigurationOverrides as it is also used by the kafka-setup-job
Minor clean up of yaml scripts
> fix(k8s): Add credentials to kafka-setup job and clean up

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/api/transform.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py
- metadata-ingestion/tests/test_helpers/sink_helpers.py
- metadata-ingestion/tests/unit/test_pipeline.py
> feature(ingestion): Adding the concept of transformers

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/api/registry.py
- metadata-ingestion/tests/unit/test_plugin_system.py
Makes the datahub CLI tool a bit snappier by speeding up the loading of plugins by using the `entrypoints` library (https://entrypoints.readthedocs.io/en/latest/)
Before:
```
❯ /usr/bin/time datahub --version
acryl-datahub, version 0.1.3
0.72 real         0.66 user         0.06 sys
```
After:
```
❯ /usr/bin/time datahub --version
acryl-datahub, version unavailable (installed editable via git)
0.30 real         0.25 user         0.04 sys
```
> fix(ingest): use entrypoints lib instead of pkg_resources

- docs/docker/development.md
The correct file name in `datahub/docker` is `docker-compose.override.yml`
> docs: Fix spelling error

- docker/nuke.sh
- metadata-ingestion/src/datahub/configuration/common.py
Current nuke.sh only destroys the containers created by the main docker-compose.yml files. Because ingestion uses a separate docker-compose.yml, these containers are not destroyed. As a result, when we bring up the containers again after nuking, the ingestion script fails as the container points to an old network instance. This change makes sure the ingestion containers are also nuked so that the above issue does not happen.
> fix(docker): Nuke ingestion containers when calling docker/nuke.sh

- metadata-ingestion/pyproject.toml
- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/tox.ini
This will help us test with Airflow 1.10.x and 2.x. Will add this to CI in a later PR.
> feat(ingest): setup scaffolding for tox testing

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/unit/test_glue_source.py
- metadata-ingestion/tests/unit/test_pipeline.py
- metadata-ingestion/tests/unit/test_rest_sink.py
- Fields like `customProperties` and `tags` are now optional, and default to `{}` or `[]`
- Enum fields have documentation from the Avro schema
- The `.from_obj()` method is slightly more strict about what it accepts
> fix(ingest): fields with defaults should be optional

- metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
- metadata-ingestion/tests/unit/test_schema_util.py
Also refactors the tests to use pytest instead of unittest.
> feat(ingest): capture default values in Avro schemas

- metadata-ingestion/src/datahub/ingestion/source/postgres.py
Standardize on `postgres`, since we already use that in the data platforms JSON file and a couple other spots.
> fix(ingest): use postgres data platform

- gms/client/src/main/java/com/linkedin/BatchGetUtils.java
- gms/client/src/main/java/com/linkedin/chart/client/Charts.java
- gms/client/src/main/java/com/linkedin/dashboard/client/Dashboards.java
- gms/client/src/main/java/com/linkedin/datajob/client/DataFlows.java
- gms/client/src/main/java/com/linkedin/datajob/client/DataJobs.java
- gms/client/src/main/java/com/linkedin/dataprocess/client/DataProcesses.java
- gms/client/src/main/java/com/linkedin/dataset/client/Datasets.java
- gms/client/src/main/java/com/linkedin/identity/client/CorpGroups.java
- gms/client/src/main/java/com/linkedin/identity/client/CorpUsers.java
- gms/client/src/main/java/com/linkedin/ml/client/MLModels.java
- gms/client/src/main/java/com/linkedin/tag/client/Tags.java
Batch requests were not reinstantiating the requestBuilder on each batch, so the batches grew by increments of the BATCH_SIZE on each request. this should fix the issue.
> fix(lineage): fixing batch requests

- metadata-ingestion/src/datahub/__init__.py
- metadata-ingestion/tests/unit/test_airflow.py
- metadata-ingestion/tests/unit/test_schema_util.py
No functional change, just makes the pytest output a bit nicer to read.
> test(ingest): add test names and IDs using pytest

- metadata-ingestion/tests/unit/test_pipeline.py
Class names that start with Test are picked up by pytest, so this resolves that warning.
> test(ingest): rename TestSource -> FakeSource

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/integrations/airflow/lineage_backend.py
- metadata-ingestion/tests/unit/serde/test_serde.py
- metadata-ingestion/tests/unit/test_rest_sink.py
We don't need three distinct ways to import the model classes. This is the first step of simplification.
> fix(ingest): remove datahub.metadata import shortcut

- datahub-web-react/src/app/entity/dataset/profile/Documentation.tsx
Here in document.tsx we are fetching userUrn from cookie rather than localstorage as we are not storing anything in localstorage anywhere.
> fix(react) Fetch userUrn from cookie while uploading document

- contrib/metadata-ingestion/python/looker/lookml_ingestion/lookml_ingestion.py
- contrib/metadata-ingestion/python/looker/lookml_ingestion/requirements.txt
This PR adds support for ingesting Looker views built from SQL-based derived tables (https://docs.looker.com/data-modeling/learning-lookml/derived-tables).
Tested with success on our Looker instance, with the lineage of Looker views built from SQL-based derived tables showing up in DataHub.
Also updates the lkml dependency to better parse .lkml files.
> feat(ingest): add support for Looker view built from SQL-based derived tables

- datahub-web-react/src/app/lineage/LineageTreeNodeAndEdgeRenderer.tsx
Address the case where we do not expand nodes away from one another even when we should.
> fix(lineage): fixing layout adjustments in lineage viz

- datahub-web-react/src/app/entity/dataset/search/highlights.ts
- gms/impl/src/main/java/com/linkedin/metadata/configs/DatasetSearchConfig.java
- gms/impl/src/main/resources/datasetESSearchQueryTemplate.json
- gms/impl/src/main/resources/index/dataset/mappings.json
- metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
- metadata-models/src/main/pegasus/com/linkedin/metadata/search/DatasetDocument.pdl
Add search for field level description and tags. Also add search for dataset description. 
For field-level description and tags, we have two sources - one from ingest one from UI (editable). We simply add multiple search fields instead of merging them.
> feat(search): Add search for field level description and tags

- metadata-ingestion/examples/airflow/generic_recipe_sample_dag.py
- metadata-ingestion/examples/airflow/lineage_backend_demo.py
- metadata-ingestion/examples/airflow/mysql_sample_dag.py
- metadata-ingestion/src/datahub/ingestion/api/registry.py
- metadata-ingestion/src/datahub/integrations/airflow/__init__.py
- metadata-ingestion/src/datahub/integrations/airflow/hooks.py
- metadata-ingestion/tests/unit/test_airflow.py
- metadata-ingestion/tests/unit/test_plugin_system.py
Using the more specific exception will prevent us from accidentally
ignoring errors that should be handled.
> fix(ingest): replace ImportError with ModuleNotFoundError

- metadata-builders/src/main/java/com/linkedin/metadata/builders/graph/relationship/RelationshipBuilderFromDataJobInputOutput.java
- metadata-builders/src/test/java/com/linkedin/metadata/builders/graph/relationship/RelationshipBuilderFromDataJobInputOutputTest.java
We can infer these relationships with graph queries if need be- for now it muddles the lineage visualization. Let's remove it until we have a practical use case.
> feat(lineage): removing dataset<>dataset edge in job index builder

- datahub-kubernetes/README.md
You need to run `helm dep update` in the prerequisites directory to run helm install.
> fix(k8s): Add helm dep update command to readme

- metadata-ingestion/scripts/release.sh
- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/test_airflow.py
- metadata-ingestion/tests/unit/test_packaging.py
- metadata-ingestion/tests/unit/test_plugin_system.py
- metadata-ingestion/tox.ini
In order to include package data in sdist Python distributions, we actually need to remove the `include_package_data` option. This article gives some insight http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/ but, is also somewhat outdated. The actual setuptools documentation is more up-to-date, but is also less clear about this issue: https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html#data-files-support. The best reference I found was here: https://stackoverflow.com/a/13783919/5004662. 
Since `sdist` now works properly, we can also remove the `use_develop` option from our `tox` configuration and use the more standard configuration options.
Prior to this PR, `pip install --no-binary 'acryl-datahub' 'acryl-datahub'` …
> build(ingest): include package data in sdist

- metadata-ingestion/src/datahub/ingestion/source/postgres.py
> fix(ingest): add support for custom postgres types

- datahub-kubernetes/prerequisites/values.yaml
By default, it should start up elasticsearch with default settings defined in the elasticsearch helm charts. These minikube specific settings should only be set when testing on minikube. (The resource values were intentionally set to a low number since minikube is running on a local machine)
> fix(k8s): Comment out minikube specific settings for elasticsearch

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsClientFactory.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/GlossaryTermType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/GlossaryTermUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryTermInfoMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryTermMapper.java
- datahub-graphql-core/src/main/resources/gms.graphql
- datahub-web-react/src/graphql/search.graphql
- gms/api/src/main/idl/com.linkedin.glossary.glossaryTerms.restspec.json
- gms/api/src/main/snapshot/com.linkedin.glossary.glossaryTerms.snapshot.json
- gms/client/src/main/java/com/linkedin/glossary/client/GlossaryTerms.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/glossary/GlossaryTerms.java
resolve #2142 
This PR is dependent on #2228
> feat(business_glossary): add business glossary entity in frontend-graphql layer

- datahub-frontend/app/react/controllers/GraphQLController.java
- datahub-frontend/app/react/resolver/IsAnalyticsEnabledResolver.java
- datahub-frontend/conf/datahub-frontend.graphql
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/graphql/analytics.graphql
**Scope**
These changes affect the React app and GraphQL server in datahub-frontend.
**Changes**
This change disables the "Analytics[Beta]" link from appearing on the HomePage of DataHub when analytics feature flag has been disabled. 
Validated locally!
> fix(React): Disable analytics link display

- docker/elasticsearch-setup/create-indices.sh
- gms/impl/src/main/resources/index/usage-event/aws_es_index_template.json
- gms/impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
- gms/impl/src/main/resources/index/usage-event/policy.json
AWS Elasticsearch uses OpenDistro version of elasticsearch which does not support index lifecycle policies and data streams. Add separate policies and templates for AWS elasticsearch.
> fix(ProductAnalytics): Add support for AWS Elasticsearch

- .github/workflows/docker-elasticsearch-setup.yml
- .github/workflows/docker-frontend-react.yml
- .github/workflows/docker-gms.yml
- .github/workflows/docker-ingestion.yml
- .github/workflows/docker-kafka-setup.yml
- .github/workflows/docker-mae-consumer.yml
- .github/workflows/docker-mce-consumer.yml
The GitHub Docker registry (docker.pkg.github.com) is [deprecated](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry) and
will be removed. We're already starting to see build flakiness due to
the instability of the image push operations, so this PR disables it
entirely.
Given that almost all DataHub users rely on the Docker Hub images and
[almost nobody](https://github.com/orgs/linkedin/packages?repo_name=datahub) uses the GitHub Docker registry images, we should be clear
to simply disable them. As such, I'm not migrating to the newer GitHub
Container registry (ghcr.io) right now. Additionally, I suggest that we
also remove the images currently present on GitHub, or the `latest` tags
on those images at a minimum.
> ci(docker): disable GitHub Docker registry

- docker/datahub-gms/env/docker.env
- docker/datahub-mae-consumer/env/docker.env
- docker/datahub-mce-consumer/env/docker.env
- docker/kafka-setup/env/docker.env
- metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessor.java
Both Kafka Listeners from DataHubUsageEventProcessor and MetadataAuditEventProcessor used the same environment variable for the topic name. This results in both listening on the same topic if this env variable is set.
Additionally, I documented the env variables for topic names in the docker.env files similar to all the SSL-Options to make them more accessible.
> Fix(Analytics): use seperate env variable for tracking topic in MAE-Consumer

- datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
Let's hide the business glossary from the homepage and search until we are ready to show it to the community. For now, folks working on the feature can revert these changes for local development
fyi @saxo-lalrishav @shubham49
> feat(business glossary): hiding business glossary until all features completed

- datahub-web-react/src/app/entity/user/UserDetails.tsx
Source of the issue: https://github.com/linkedin/datahub/pull/2474
The `toLowerCase()` strategy worked in many cases, but not in the case of pipelines or tasks where the entity type does not match up with the url.
> fix(owner): fixing ownership routing

- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/Chart.yaml
- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/README.md
- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/templates/cron.yaml
- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/values.yaml
This PR allows users of the DataHub Metadata Ingestion Chart Component to run custom logic beyond that which is available by the `datahub ingest` command line python tool.
This is being used in production at DefinedCrowd to manipulate metadata models crawled from Druid datasources prior to sending them to DataHub. 
At the time [transformations](https://datahubproject.io/docs/metadata-ingestion/#transformations) were not ready as far we knew, so it is unlikely that an exact use-case should require the same method. Regardless we feel this greater flexibility in this component makes sense for less trivial scenarios.
> feat(K8s) Generalizes CronJob metadata ingestion resource for custom logic

- metadata-ingestion/src/datahub_provider/hooks/datahub.py
- metadata-ingestion/src/datahub_provider/lineage/datahub.py
- metadata-ingestion/src/datahub_provider/operators/datahub.py
This PR adds Sphinx templated docstrings to the Airflow modules in the datahub_provider package. Sphinx docstrings are the usual way Airflow modules are documented and these docstrings will be rendered by the Astronomer Registry. Suggestions welcome!
> Add Sphinx Docstrings to Airflow Modules 

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/glue.py
This PR aims to add IAM Roles support to the existing Glue Source. This could allow importing the Glue Metadata cross AWS accounts by chaining roles or by allowing the current instance to assume an external role.
> feat(ingest): :lock: - Add AWS IAM Roles Support to the Glue Source

- metadata-ingestion/README.md
- metadata-ingestion/examples/recipes/dbt_to_datahub.yml
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/tests/integration/dbt/test_dbt.py
Driver: https://datahubspace.slack.com/archives/CUMUWQU66/p1619190330199800
TL/DR: DBT metadata will likely be loaded to provide DBT metadata (tags and lineage) and we will want the dbt ingestion tooling to enhance existing data.  That data will likely be loaded from another platform.
IE: 
```
urn:li:dataset:(urn:li:dataPlatform:dbt,pagila.public.payment_p2020_01,PROD)
vs.
urn:li:dataset:(urn:li:dataPlatform:postgresql,pagila.public.payment_p2020_01,PROD)
```
We will provide either the ability to specify a target_platform or infer it from the dbt metadata.
> (fix) DBT metadata ingest can add metadata to existing dataplatforms

- metadata-ingestion/tests/integration/mysql/docker-compose.yml
- metadata-ingestion/tests/integration/mysql/mysql_to_file.yml
Somehow the 53306 port is often in use on the CI machines and causes
conflicts. This changes to a slightly different port number.
For example, from https://github.com/linkedin/datahub/runs/2604009138:
```
E           ERROR: for testmysql  Cannot start service testmysql: driver failed programming external connectivity on endpoint testmysql (c764a27faba8d8643e59c223bfe06200665704ac4572e254140387e6aa382080): Error starting userland proxy: listen tcp4 0.0.0.0:53306: bind: address already in use
E           Encountered errors while bringing up the project.
E           """.
```
> test(ingest): use different mysql test port

- datahub-web-react/src/app/entity/dataset/profile/schema/SchemaDescriptionField.tsx
If there is an edited description, the UI will display a "(edited)" label
As brought up in #2506
> feat(react): Add label to edited dataset descriptions

- datahub-web-react/src/app/shared/tags/AddTagModal.tsx
Tag autocomplete used to cache on the client. This was problematic, since actions taken by the client could create new tags, in which case the cache would be invalid. Here I remove the caching so we always get most up to date autocomplete.
> fix(tags): fixing tag autocomplete caching

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/src/datahub/ingestion/source/superset.py
> fix(ingest): default values for env

- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/conf/theme/types.ts
- [n/a] Links to related issues (if applicable)
- [n/a] Tests for the changes have been added/updated (if applicable)
- [n/a] Docs related to the changes have been added/updated (if applicable)
If subtitle is provided in the theme config file, looks like this:
Otherwise it looks unchanged.
> feat(react): add optional subtitle to home page

- metadata-ingestion/src/datahub/ingestion/source/looker.py
I'm not sure, but it seems the chart pattern was not well defined since it forced me to define it in the inverted way:
```
chart_pattern:
allow: []
deny: [".*"]
```
@frsann  could you validate it too?
> fix(ingest): Misuseage of the Allow Pattern

- metadata-ingestion/tests/integration/looker/expected_output.json
- metadata-ingestion/tests/integration/looker/test_looker.py
One test was broken. This PR fixes it, and adds a test for the `chart_pattern`.
> feat(ingestion): Fix looker test

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
This PR fixes the lineage (upstream/downstream urns) generated after dbt metadata ingestion when tables tables name and identifier differ in the dbt manifest.json file:
- if `load_catalog` is False and a table (node) has an identifier field, use this instead of the table name to link to the actual source table in the urn
- if `load_catalog` is True, nothing is changed
See https://github.com/linkedin/datahub/pull/2483#issuecomment-840724995 for more context, and https://docs.getdbt.com/reference/resource-properties/identifier for the dbt doc on `identifier` vs `name`.
> fix(ingest): fix lineage after dbt metadata ingestion when tables name and identifier differ

- datahub-web-react/src/app/search/utils/navigateToSearchUrl.ts
Fixes bug where selecting an autocomplete tag result takes the user to a malformatted url
> fix(autocomplete): fixing tags autocomplete bug

- datahub-frontend/app/react/controllers/TrackingController.java
- datahub-frontend/conf/application.conf
Title says it. Allow configuration of SSL configs for datahub-frontend.
> feat(Analytics): Support configuration of Kafka SSL in datahub-frontend 

- datahub-web-react/src/app/entity/EntityPage.tsx
- datahub-web-react/src/app/entity/EntityRegistry.tsx
- datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
- datahub-web-react/src/app/entity/dashboard/preview/DashboardPreview.tsx
- datahub-web-react/src/app/entity/dataFlow/preview/Preview.tsx
- datahub-web-react/src/app/entity/dataJob/preview/Preview.tsx
- datahub-web-react/src/app/entity/dataset/preview/Preview.tsx
- datahub-web-react/src/app/entity/glossaryTerm/preview/Preview.tsx
- datahub-web-react/src/app/entity/shared/utils.ts
- datahub-web-react/src/app/entity/tag/TagProfile.tsx
- datahub-web-react/src/app/entity/user/preview/Preview.tsx
- datahub-web-react/src/app/entity/userGroup/preview/Preview.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
Fixes two bugs:
- encodes key url characters in urns so that we dont link to malformed urls
- fixes tag search module for tags w/ whitespace in their name
related github issues:
https://github.com/linkedin/datahub/issues/2588
and https://github.com/linkedin/datahub/issues/2581
> fix(react): url encoding urns and tag profile fix

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/InstitutionalMemoryMetadataMapper.java
- datahub-graphql-core/src/main/resources/gms.graphql
- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/dataset/profile/DatasetProfile.tsx
- datahub-web-react/src/app/entity/dataset/profile/Documentation.tsx
- datahub-web-react/src/app/entity/dataset/profile/__tests__/Documentation.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/stories/documentation.ts
- datahub-web-react/src/app/entity/dataset/profile/stories/sampleDataset.ts
- datahub-web-react/src/graphql/dataset.graphql
- datahub-web-react/src/graphql/fragments.graphql
Showing username instead of user's urn.
Added 1 more field in graphql schema for showing username.
> feat(react): replace user urn with username

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
Uses batch requests to speed up ingestion and help prevent race conditions. Closes #2627.
> fix(ingest): improve redshift ingestion performance

- metadata-ingestion/build.gradle
Since #2503 was merged, we don't want to remove the `metadata-ingestion/src/datahub/metadata` directory when running clean.
> fix(ingest): don't purge codegen on gradle clean

- docker/datahub-upgrade/datahub-upgrade.sh
Fix docker image tag for run_upgrade script
> fix(NoCode): Fix docker image tag for run_upgrade script

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java
Previously, "shell" entities were returned when GMS could not find aspects for a requested entity (get or batchGet). Matching this behavior in NoCode to maintain active deployment's functionality.
Note that we are considering materialization of all references nodes in the graph in the DB, such that every node has at minimum a single aspect associated with it once it's been created or referenced by another node.
> fix(gms): Return empty snapshots when one does not exist

- docs/advanced/no-code-upgrade.md
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
> docs(nocode): fix links to datahub-upgrade

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocode/UpgradeQualificationStep.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectStorageValidationUtil.java
> feat(datahub-upgrade): Improve no code upgrade logging

- docker/ingestion/ingestion.sh
- docker/quickstart-ember.sh
- docker/quickstart.sh
> fix(docker): pin containers to golden hash for release

- docs/advanced/no-code-upgrade.md
> docs(no-code): Adding documentation for no-migration upgrade option

- docker/ingestion/ingestion.sh
- docker/quickstart-ember.sh
- docker/quickstart.sh
This reverts commit a483933eab6d072ba6d2a414e378eee1e80dbdc6 and moves us back to using HEAD in quickstart on the master branch, since the release has now been cut.
> revert: "fix(docker): pin containers to golden hash for release (#2654)"

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/mssql.py
- metadata-ingestion/tests/integration/sql_server/mssql_to_file.yml
> fix(ingest): support mssql encryption via ODBC

- gms/api/src/main/snapshot/com.linkedin.chart.charts.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dashboard.dashboards.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dataflow.dataFlows.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.datajob.dataJobs.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dataprocess.dataProcesses.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.dataset.datasets.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.glossary.glossaryNodes.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.glossary.glossaryTerms.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpGroups.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.identity.corpUsers.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.ml.mlModels.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.tag.tags.snapshot.json
Snapshot json files seems to not get updated on annotation changes. As such latest changes have not been applied.
> fix(NoCode): Update snapshot json to latest

- docs/modeling/extending-the-metadata-model.md
Often times, the `./gradlew :gms:impl:build -Prest.model.compatibility=ignore` command will need to be run when adding or updating an existing entity.
> docs(no code): adding documentation to handle backwards incompatibility issues

- docs/advanced/no-code-modeling.md
The key should be enableAutocomplete not enableAutoComplete
> fix(NoCode): Fix typo in no-code-modeling doc

- metadata-ingestion/src/datahub/metadata/schema.avsc
- metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl
This annotation meant relationships between charts and their input datasets were not being ingested.
> fix(no-code): Adding Chart input relationship annotations

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/hive.py
- metadata-ingestion/tests/unit/test_hive_source.py
The hive source currently does not include the catalog name
in the schema name. This is due to the SQLAlchemy
reflection that pyhive performs. Without the catalog
name, multiple hive sources could have collisions
with the urns generated. This function will add
the database name where applicable and solve this problem.
> Add get_identifier to hive source in metadata ingestion

- metadata-ingestion/setup.py
Also removes `dataclasses`, since it's already specified as a dependency elsewhere. Follow up on #2666.
> fix(ingest): pin to new mypy version

- gms/factories/src/main/java/com/linkedin/gms/factory/common/Neo4jDriverFactory.java
Makes it possible for a user to fix the issue described in #2592
This change might affect some users since a property got a new name.
I added another Neo4j connection property and changed the name of an existing property. 
I changed the name of `NEO4j_MAX_CONNECTION_LIFETIME_IN_HOURS` since _hours_ isn't granular enough and that _seconds_ are used by all the other connection properties. 
New: **NEO4J_CONNECTION_LIVENESS_CHECK_TIMEOUT_IN_SECONDS**
Changed: 
old name: **NEO4j_MAX_CONNECTION_LIFETIME_IN_HOURS**
new name: **NEO4j_MAX_CONNECTION_LIFETIME_IN_SECONDS**
> Fix 2592 neo4j connection options

- metadata-ingestion/setup.py
This resolves some MacOS build issues, which stem from the release of XCode10. See https://github.com/cloudera/python-sasl/pull/13 for details about the issue itself. The [python-sasl3 fork](https://github.com/sparkur/python-sasl3) contains these changes.
The change to acryl-pyhive is here: https://github.com/hsheth2/PyHive/commit/a02428fc018095dc948bf0bd71251c0d8b0a4149.
> fix(ingest): upgrade acryl-pyhive to use sasl3 instead of sasl

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/oracle.py
- metadata-ingestion/tests/unit/test_oracle_source.py
- Add add schema registry options to Kafka sink docs.
- Ref on the Oracle service_name option: https://github.com/zzzeek/sqlalchemy/commit/3db84b174ad9a6c7ba64a8dfd1746905651ca04f.
> feat(ingest): support Oracle service names

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
Tested with MS SQL Server, this solution should work with other SQLAlchemy manageable DBs.
Now the ingestion recipe accept, optionally, two more options:
include_views: False
include_tables: True
To assure retro-compatibility they can be omitted, and in such case the default arguments are those ones expressed up here.
- [-] Links to related issues (if applicable)
- [-] Tests for the changes have been added/updated (if applicable)
> feat(sql_views): added views as datasets for SQLAlchemy DBs

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
This PR avoid loading additional metadata found in the dbt manifest such as tests, macros, etc. that are not present in the catalog and should not be ingested when `load_catalog` is false (see https://docs.getdbt.com/reference/artifacts/manifest-json and https://docs.getdbt.com/reference/artifacts/catalog-json).
In fact entities/nodes in the manifest file should probably not be ingested at all and be only used to build the upstream/downstream lineage...
> fix(ingest): do not load metadata from the dbt manifest file when load_catalog is false

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/integration/mysql/mysql_mce_golden.json
- metadata-ingestion/tests/integration/mysql/setup/setup.sql
> feat(ingest): Add test case and docs for SQL view ingestion

- gms/impl/src/main/resources/DataPlatformInfo.json
- metadata-ingestion/examples/mce_files/bootstrap_mce.json
- metadata-ingestion/examples/mce_files/data_platforms.json
- metadata-ingestion/scripts/update_golden_files.sh
- metadata-ingestion/src/datahub/ingestion/source/looker.py
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
- metadata-ingestion/tests/integration/looker/expected_output.json
- metadata-ingestion/tests/integration/lookml/expected_output.json
> fix(ingest): use `looker` data platform

- metadata-ingestion/setup.py
- metadata-ingestion/tests/test_helpers/docker_helpers.py
Now that https://github.com/avast/pytest-docker/pull/58 has been merged and published via a release, we can remove the hack that was added to force the context manager into cleaning up containers even if a test failed.
> test(ingest): simplify docker cleanup commands

- datahub-kubernetes/datahub/charts/datahub-frontend/templates/service.yaml
- datahub-kubernetes/datahub/charts/datahub-frontend/values.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/templates/service.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/values.yaml
> feat: Adding annotation option to frontend service

- metadata-ingestion/README.md
Added node_type_pattern in dbt source yml file. This option can be used to filter node_types using allow or deny methods.
PR - Removed key not in catalog filter from dbt and added node filter using AllowDenyPattern #2702
> Added node_type_pattern in dbt yml file

- docker/quickstart.sh
> feat(quickstart): use versioned docker images when on a release tag

- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entity/shared/DescriptionModal.tsx
- datahub-web-react/src/app/entity/shared/MarkdownViewer.tsx
> fix(react): update schema description edit behavior

- metadata-ingestion/src/datahub/ingestion/source/lookml.py
This PR fixes the urn format when ingesting lookml metadata.
Note: this PR allows the ingestion of lookml metadata but those cannot be browsed or searched from the UI... This error shows up in the logs:
`com.linkedin.data.template.TemplateOutputCastException: Invalid URN syntax: Urn doesn't start with 'urn:'. Urn: looker at index 0: looker`
> fix(ingest): fix lookml ingestion urn format

- metadata-ingestion/tests/integration/feast/test_feast.py
> fix(ingest): Increase timeout for setting up test Feast containers

- metadata-ingestion/tests/integration/lookml/expected_output.json
Follow up on #2737. CI didn't catch this because it can't run the LookML
tests because of Python versioning issues.
> fix(ingest): update lookml test

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ResolverUtils.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java
1) fixes case where the aspect was not fetched from local context because of an incorrect null comparison
2) updates getAspect logic for negative versions. Currently, this code path is not hit so tests did not catch it.
> fix(version aspects): fixes for version aspect fetching

- gms/impl/src/main/java/com/linkedin/metadata/resources/ResourceUtils.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- li-utils/src/main/javaPegasus/com/linkedin/common/urn/UrnValidator.java
Previously, Rest.li endpoints were not validating incoming data against their respective schema. Typically, this is performed inside of a Rest.li Validation Filter that runs before the endpoints are hit. However, that filter does not support Action method requests. Thus, we've had to implement our own manual validation for Entity ingestion. This PR does exactly that.
Before
- Model validation issues would go undiscovered until read time :(
With these changes
- Model validation happens at Rest.li endpoint level, the front door. :)
> fix(GMS): Adding Rest.li Validation in GMS

- datahub-kubernetes/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
- datahub-kubernetes/datahub/values.yaml
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocode/CreateAspectTableStep.java
- docker/datahub-upgrade/README.md
- docker/mariadb/init.sql
- docker/mysql-setup/init.sql
- docker/mysql/init.sql
- docker/postgres/init.sql
- docs/advanced/no-code-upgrade.md
This PR introduces datahub-upgrade SQL suitable for Postgres. Previously, we had only supported MySQL and Maria officially.
> fix(datahub-upgrade): Add support for Postgres migration

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
This PR adds the option to specify the source platform database in the `connection_to_platform_map` configuration in order to generate proper upstream urns and lineages to the source tables in DataHub.
The source platform(s) and associated database(s) are configured in https://<subdomain>.looker.com/admin/connections and the tables in the lkml files are in the format `schema.table`.
Also changed the sql tables names to lowercase because urns are case sensitive in DataHub and the sqlalchemy-based metadata ingestion generates lowercase urns (at least Snowflake does).
> feat(ingest): add option to specify source platform database in lookml ingestion

- gms/client/src/main/java/com/linkedin/entity/client/EntityClient.java
"get" method in EntityClient incorrectly returned a weakly typed RecordTemplate. This PR updates it to return a strongly Entity object. 
No callers are using the API at this time, so should be a safe fix.
> fix(EntityClient): Make get return Entity type

- docker/docker-compose-without-neo4j.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/generate_and_compare.sh
This was removed spuriously- we still need it for product analytics.
> fix(elastic-as-graph): adding elasticsearch setup back in

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java
Add sorting by doc count (desc) and then name (asc) when showing browse groups.
> feat(browse): Add sorting by doc count for browse groups

- datahub-kubernetes/README.md
- docker/README.md
- docker/quickstart.sh
- metadata-ingestion/src/datahub/cli/docker.py
- metadata-ingestion/src/datahub/cli/docker_check.py
This PR defaults `datahub docker quickstart` and`./docker/quickstart.sh` to use Elasticsearch as a graph database. Although Neo4j will have some slight performance improvements compared to elastic for expensive queries, Datahub does not take advantage of this at the moment. Elasticsearch is preferable for single-node installations since it removes a dependency on Neo4j for startup. Neo4j will continue to be supported as an implementation for the Graph Service.
**Why use elastic as a graph service?**
Neo4j is optimized for complex graph queries. However, there are reasons Elasticsearch may be a preferable Graph backend for some users.
1) Currently, all graph queries in DataHub are single hop. Elasticsearch is well optimized for single hop queries, and is actually slightly more performant …
> feat(elastic-as-graph): defaulting to elastic in quickstart

- README.md
- docs-website/docusaurus.config.js
- docs-website/src/pages/index.js
- docs/townhalls.md
> docs: update for Jun townhall

- datahub-frontend/app/react/resolver/GetHighlightsResolver.java
- datahub-web-react/public/index.html
> fix(react): move percent sign after number and update meta tag

- datahub-web-react/src/app/entity/dataset/profile/DatasetHeader.tsx
> fix(react): update platform text in dataset profile header

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/src/datahub/ingestion/source/glue.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/src/datahub/ingestion/source/looker.py
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/test_helpers/mce_helpers.py
This will make testing and refactoring easier in the future.
> refactor(ingest): use common get_sys_time method

- datahub-frontend/app/react/analytics/AnalyticsServiceModule.java
This change fixes an issue where all SSL configs were required when it was enabled.
> fix(elastic ssl): Making nested SSL configs optional 

- docs/quickstart.md
Mentioning `docker system prune` in case of docker deploy problems.
> docs(quickstart): Adding troubleshooting notes to quickstart

- datahub-upgrade/build.gradle
Adding logbackClassic dependency to datahub-upgrade so that logging is all captured.
> fix(datahub-upgrade): Adding runtime dependency on logbackClassic

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
This PR:
- updates the sql-metadata dependency version that add supports to more SQL dialects and improve the detection of sql derived tables.
- add cascading derived tables to the lineage of lookml views (see https://docs.looker.com/data-modeling/learning-lookml/derived-tables#cascading_derived_tables)
> Improve lookml sql derived tables detection, add cascading derived tables to lineage

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
Superseeds https://github.com/linkedin/datahub/pull/2638 cc @gabe-lyons 
Co-authored-by: Gabe Lyons <itsgabelyons@gmail.com>
> fix(ingest): better warnings and error handling for rest sink

- metadata-ingestion/src/datahub/ingestion/source/athena.py
- metadata-ingestion/src/datahub/ingestion/source/aws_common.py
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/src/datahub/ingestion/source/druid.py
- metadata-ingestion/src/datahub/ingestion/source/feast.py
- metadata-ingestion/src/datahub/ingestion/source/glue.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/src/datahub/ingestion/source/looker.py
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
- metadata-ingestion/src/datahub/ingestion/source/mongodb.py
- metadata-ingestion/src/datahub/ingestion/source/mssql.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake_usage.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/superset.py
Also refactors the code to use the DEFAULT_ENV constant
> refactor(ingestion): extract sqlalchemy uri generation logic

- docker/docker-compose-without-neo4j.yml
- docker/quickstart/generate_docker_quickstart.py
- docker/quickstart/generate_docker_quickstart.sh
- docker/quickstart/mysql/init.sql
When you manually run quickstart for mysql container (using quickstart.sh), the container will fail to spin up the first time you run "up" because the init.sql file cannot be found in the `docker/quickstart` directory. 
This fixes it by adding logic to copy the `init.sql` file from the mysql/init.sql file into the expected `docker/quickstart` location when `generate_docker_quickstart.sh` is executed.
> fix(quickstart): Fixing manual mysql quickstart

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/entrypoints.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_usage.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/unit/test_snowflake_source.py
Stacked on #2786, so merge that first.
> feat(ingest): support ingesting from multiple snowflake dbs

- build.gradle
- datahub-upgrade/build.gradle
Fix datahub-upgrade vulnerabilities
> fix(docker): Fix datahub-upgrade vulnerabilities

- datahub-kubernetes/datahub/Chart.yaml
- datahub-kubernetes/datahub/README.md
- datahub-kubernetes/datahub/charts/datahub-frontend/README.md
- datahub-kubernetes/datahub/charts/datahub-frontend/values.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/README.md
- datahub-kubernetes/datahub/charts/datahub-gms/values.yaml
- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/README.md
- datahub-kubernetes/datahub/charts/datahub-ingestion-cron/values.yaml
- datahub-kubernetes/datahub/charts/datahub-mae-consumer/README.md
- datahub-kubernetes/datahub/charts/datahub-mae-consumer/values.yaml
- datahub-kubernetes/datahub/charts/datahub-mce-consumer/README.md
- datahub-kubernetes/datahub/charts/datahub-mce-consumer/values.yaml
- datahub-kubernetes/datahub/quickstart-values-without-neo4j.yaml
- datahub-kubernetes/datahub/quickstart-values.yaml
- datahub-kubernetes/datahub/values.yaml
> feat(k8s): Upgrade to v0.8.5

- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- handle TextClause view definitions
- handle views where we can't fetch the columns
Tested against Redshift.
> fix(ingest): view handling resilience

- docker/datahub-frontend/env/docker.env
- docs/how/auth/sso/configure-oidc-react-google.md
- docs/how/auth/sso/configure-oidc-react-okta.md
- docs/how/auth/sso/configure-oidc-react.md
**Changes**
- remove reference to removes docker compose react file
- update command from "restart" to "up" (uses new env vars) 
**Acknowledgements**
Thanks to Martha Edwards from NYT for catching these!
> fix(docs): Update OIDC docs 

- datahub-kubernetes/README.md
- docs-website/sidebars.js
- docs/how/migrating-graph-service-implementation.md
- metadata-ingestion/src/datahub/cli/docker.py
> docs(elastic-for-graph): Add migrating from neo4j to elastic instructions

- metadata-ingestion/src/datahub/ingestion/source/superset.py
Previous values were in seconds, which rendered incorrectly in the UI:
> fix(ingest): convert superset timestamps to micros

- .github/workflows/build-and-test.yml
- metadata-ingestion/build.gradle
> build: separate metadata-ingestion into a separate workflow

- metadata-ingestion/src/datahub/cli/docker.py
> fix(cli): change docker nuke to also remove stopped containers

- docker/datahub-gms/start.sh
- docker/datahub-mae-consumer/env/docker-without-neo4j.env
- docker/datahub-mae-consumer/start.sh
- docker/dev-without-neo4j.sh
- docker/docker-compose.consumers-without-neo4j.yml
Extends mae consumer docker compose files to include one that supports an elastic-as-graph compose file. Also updates start.sh scripts to conditionally wait on neo if neo is the graph service.
> fix(standalone mae consumer): support standalone mae consumer without neo4j

- docs/roadmap.md
> docs: update H2 2021 roadmap

- metadata-ingestion/src/datahub/ingestion/source/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- fix ingestion for BigQuery views
- resolve a name resolution bug when skipping schemas
- add support for the Geography type
- map JSON columns properly
Tested locally against a live BigQuery project.
> fix(ingest): various BigQuery source fixes

- datahub-kubernetes/datahub/Chart.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/Chart.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/templates/ingress.yaml
- datahub-kubernetes/datahub/charts/datahub-gms/values.yaml
Add ingress template for helm chart to enable access from outside the cluster
Linked issue: https://github.com/linkedin/datahub/issues/2831
> feat (helm datahub-gms): add ingress template to datahub-gms helm chart

- docs-website/generateDocsDir.ts
- docs/how/build-metadata-service.md
- docs/links.md
- docs/modeling/extending-the-metadata-model.md
- docs/what/mxe.md
> fix(docs): fix some broken links in the docs

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
This PR fixes the glob pattern, which didn't allow for having `*.model.lkml` files in the root of the `base_folder` and also handles a possible scenario of recursion.
> fix(ingest): Fix glob pattern and handle possible recursion in lookml

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/entrypoints.py
Also adds a couple extra log lines.
> feat(ingest): prettify stack traces in CLI

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json
> fix(ingest): check for dbt materialization before proceeding

- metadata-ingestion/README.md
Closes #2850. Thanks for catching this @jameslamb.
> docs(ingest): remove hanging sentence from docs

- metadata-ingestion/src/datahub/ingestion/source/bigquery_usage.py
> fix(ingest): handle 'fields' list missing in bigquery-usage

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/aspect/AspectType.java
Restli specifies resources should return 404s when a resource is fetched but does not exist:
https://linkedin.github.io/rest.li/user_guide/restli_server#returning-nulls
However, in graphql we do not special case 404 errors and propagate the error to the client. In the Entity world, this makes sense because we mint an empty entity when a non-existent entity is fetched. This means the entity resource always returns something. The Aspect resource cannot return an empty aspect, since we do not have the ability to dynamically construct empty aspects (nor do we necc. want to).
This fix handles 404 errors and passes a null version of the aspect to the client.
> fix(versioned aspects): handle fetching null aspects from AspectType

- metadata-ingestion/src/datahub/configuration/import_resolver.py
- metadata-ingestion/src/datahub/ingestion/api/registry.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_tags.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> feat(ingest): support dynamic imports for transformer methods

- .github/workflows/build-and-test.yml
Also excludes docs-website from standard build since it's covered by the docs workflow
> build(ingest): separate metadata-ingestion build workflow fully

- docs/quickstart.md
> docs(quickstart): add default password to quickstart

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/tests/integration/dbt/dbt_catalog.json
- metadata-ingestion/tests/integration/dbt/dbt_manifest.json
- metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json
> feat(ingest): extract dbt meta fields

- metadata-ingestion/tests/test_helpers/mce_helpers.py
> feat(ingest): update golden files only when diff fails

- metadata-ingestion/build.gradle
- metadata-ingestion/developing.md
- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/tests/integration/feast/test_feast.py
- metadata-ingestion/tests/integration/hive/test_hive.py
- metadata-ingestion/tests/integration/ldap/test_ldap.py
- metadata-ingestion/tests/integration/mongodb/test_mongodb.py
- metadata-ingestion/tests/integration/mysql/test_mysql.py
- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/unit/test_hive_source.py
- metadata-ingestion/tests/unit/test_ldap_source.py
- metadata-ingestion/tox.ini
> build(ingest): reduce dependencies for dev install

- metadata-ingestion/src/datahub/ingestion/source/bigquery_usage.py
- metadata-ingestion/src/datahub/utilities/delayed_iter.py
- metadata-ingestion/tests/unit/test_utilities.py
This will help us ensure correctness, at the cost of higher memory usage. However, it can always be tuned via config.
> fix(ingest): default to unlimited query log delay in bigquery-usage

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/IndexBuilder.java
Currently it checks aliases and deletes aliases for all indices, which is unnecessary. Check for the specific indices we want to look at. 
This allows us to set index permissions based on the index template.
> fix(search): Fix index builder to access minimum required indices

- gms/api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- gms/api/src/main/snapshot/com.linkedin.ml.mlModels.snapshot.json
- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/sagemaker.py
- metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/jobs.py
- metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/models.py
- metadata-ingestion/src/datahub/metadata/schema.avsc
- metadata-ingestion/src/datahub/metadata/schema_classes.py
- metadata-ingestion/src/datahub/metadata/schemas/MetadataAuditEvent.avsc
- metadata-ingestion/src/datahub/metadata/schemas/MetadataChangeEvent.avsc
- metadata-ingestion/tests/unit/sagemaker/sagemaker_mces_golden.json
- metadata-ingestion/tests/unit/sagemaker/test_sagemaker_source.py
- metadata-ingestion/tests/unit/test_sagemaker_source_stubs.py
- metadata-models/src/main/pegasus/com/linkedin/ml/metadata/MLModelProperties.pdl
> feat(ingest): extract lineage between SageMaker jobs and models

- datahub-web-react/src/app/entity/dataset/profile/__tests__/SchemaDescriptionField.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/SchemaTable.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/components/CustomPagination.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/components/TypeIcon.tsx
> feat(react): update schema history visualizing, truncate long type, original desc bug

- metadata-ingestion/src/datahub/ingestion/source/lookml.py
This PR proposes changing the method `datahub.ingestion.source.lookml.LookMLSource._get_upsteam_lineage()` to `_get_upstream_lineage()`. I believe `upsteam` is a typo.
I'm not aware of any functional issues caused by that typo, but it does mean that this method might be missed if searching through the codebase for lineage-related code (as I did this morning with something like `git grep -i upstream metadata-ingestion/src`).
I checked with `git grep _get_upsteam_lineage` and can confirm there are no other places in this project's code referencing this method. Since the method name begins with `_`, I'm assuming that it is considered private and can safely be changed.
Thanks for your time and consideration.
> fix(ingest): change LookMLSource._get_upsteam_lineage() to _get_upstream_lineage()

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/src/datahub/ingestion/source/looker.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake.py
The logger.warn method is deprecated in favor of warning.
> fix(ingest): use logger.warning instead of logger.warn

- datahub-web-react/src/app/search/SearchPage.tsx
This was fixed on a few other pages successfully but this check was actually referencing an external variable. Updated to check the new query rather than the old one.
> fix(blank searches on search page): fixing case where someone issues a null query on the search page

- datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx
- datahub-web-react/src/app/entity/shared/Ownership.tsx
In react:
```js
(0 && 'foo') renders 0
(false && 'foo') renders nothing
(truthy && 'foo') renders foo
```
Using `!!value` forces conversion to a bool, which will prevent a stay "0" from being rendered.
> fix(react): avoid displaying "0" for ignored timestamps

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
This PR change the dbt node description from the node key (for ex. `model.source.table`) to the node metadata comment if it's available (manifest nodes do not have metadata) and defined (typically a more descriptive string than the key).
> feat(metadata-ingestion): use node comment as description in dbt

- datahub-web-react/src/app/home/HomePageHeader.tsx
Simply don't use the local cache when fetching. Ensures the config is properly updated on change.
> fix(frontend): Don't use Apollo Cache for IsAnalyticsEnabled query. 

- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/tox.ini
> test(ingest): update tox test configurations and test airflow 2.x by default

- metadata-ingestion/README.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/postgres.py
- metadata-ingestion/src/datahub/ingestion/source/sql_common.py
- metadata-ingestion/tests/unit/test_postgres_source.py
> feat(ingest): Add option to change name of database for postgres

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/test_snowflake_source.py
Version 1.2.5 was released today (https://pypi.org/project/snowflake-sqlalchemy/1.2.5/), but yields errors for us, as below. We pin our version to 1.2.4 for now, since we still depend on SQLAlchemy 1.3.24.
```
tests/unit/test_snowflake_source.py:1: in <module>
from datahub.ingestion.source.snowflake import SnowflakeConfig
src/datahub/ingestion/source/snowflake.py:7: in <module>
import snowflake.sqlalchemy  # noqa: F401
venv/lib/python3.8/site-packages/snowflake/sqlalchemy/__init__.py:25: in <module>
from . import base, snowdialect
venv/lib/python3.8/site-packages/snowflake/sqlalchemy/base.py:17: in <module>
from .custom_commands import AWSBucket, AzureContainer, ExternalStage
venv/lib/python3.8/site-packages/snowflake/sqlalchemy/custom_commands.py:14: in <module>
from sqlalchemy.sql.roles …
```
> fix(ingestion): pin snowflake sqlalchemy connector

- metadata-ingestion/src/datahub/ingestion/source/glue.py
Without this fix was getting errors due to `varchar(x)` and `decimal(x, y)` types in our glue catalog
> fix(ingest): Glue mapping patch

- metadata-ingestion/src/datahub/ingestion/source/glue.py
The name of the workunit caused confusion when I was testing with `console` sink that the ingestion would be named `glue-FULL_TABLE_NAME`. Changing it so it is consistent with rest of the sources and not add this prefix.
> fix(ingest): fix workunit name to be consistent with other sources

- metadata-ingestion/src/datahub/ingestion/source/bigquery_usage.py
- metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py
- Add the `max_query_duration` param
- Add links to the docs for bigquery audit logs
> feat(ingest): improve bigquery-usage robustness and docs

- metadata-ingestion/setup.cfg
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
- metadata-ingestion/tests/integration/lookml/expected_output.json
- metadata-ingestion/tests/integration/lookml/lkml_samples/foo.view.lkml
- metadata-ingestion/tests/integration/lookml/lkml_samples/included_view_file.view.lkml
- metadata-ingestion/tests/integration/lookml/lkml_samples/nested/second.model.lkml
- metadata-ingestion/tests/integration/lookml/lkml_samples/view_declarations.view.lkml
Also improves the error messages and logging throughout the source, and add an additional test.
> fix(ingest): refactor + fix recursion in lookml file loading logic

- metadata-ingestion/src/datahub/ingestion/source/glue.py
Currently fails if trying to extract the DAG for a custom Python script; this PR catches this exception.
> fix(ingest): allow custom Glue scripts

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
We initially cached data platforms in the graphql layer because data platforms were hardcoded. With no-code, data platforms no longer are hardcoded and may be updated at any time. As a result, we should no longer cache them in graphql.
> fix(gql): removing data platform caching in gql

- metadata-ingestion/src/datahub/ingestion/source/lookml.py
The LookML metadata ingestion logic includes a method, `resolve_includes()`, whose goal is to turn [LookML `include` statements](https://docs.looker.com/reference/model-params/include) into valid Python `glob` patterns. This is used to identify `.lkml` files to be read in and used to create MCE messages.
I believe that a mistake in that logic leads to files in deeply-nested directories being ignored by `datahub ingest`.
the LookML
```text
include: "/**/some_cool_view.view.lkml"
```
is treated as equivalent to
```python
glob.glob(f"{config['base_folder']}/**/some_cool_view.lkml")
````
But I believe that's incorrect. According to https://docs.looker.com/data-modeling/getting-started/ide-folders#wildcard_examples, `**` matches all directories at any level of nesting. Without …
> fix(ingestion): match nested LookML files mentioned in 'include' statements

- metadata-ingestion/src/datahub_provider/hooks/datahub.py
- metadata-ingestion/tests/unit/test_airflow.py
> fix(ingestion): isolate dependency requirements of airflow hooks

- docs-website/sidebars.js
- metadata-ingestion/README.md
- metadata-ingestion/examples/transforms/README.md
- metadata-ingestion/examples/transforms/custom_transform_example.py
- metadata-ingestion/examples/transforms/setup.py
- metadata-ingestion/transformers.md
> feat(docs): tutorial for writing a custom transformer

- metadata-ingestion/examples/mce_files/bootstrap_mce.json
- metadata-ingestion/examples/mce_files/mce_list.json
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/file.py
- metadata-ingestion/tests/unit/serde/test_serde.py
- metadata-ingestion/tests/unit/serde/test_serde_extra_field.json
- metadata-ingestion/tests/unit/serde/test_serde_missing_field.json
> feat(ingestion): stricter deserialization for MCE JSONs

- metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
Also refactor by moving `get_identifier` and `standardize_schema_table_names` into the source rather than leaving it in the config.
> fix(ingestion): infer bigquery project identifier

- metadata-ingestion/src/datahub/ingestion/source/looker.py
I've been looking at opportunities to contribute on metadata ingestion, so I ran  `pylint metadata-ingestion/src/datahub` today.
This PR proposes fixing one of the warnings raised by `pylint`.
> metadata-ingestion/src/datahub/ingestion/source/looker.py:163:16: W0612: Unused variable 'expression' (unused-variable)
This PR proposes removing that variable, which I think should make the Looker ingestion code a tiny tiny tiny bit faster and, more importantly, eliminates the risk of that code breaking if the key `"expression"` doesn't show up in the parsed fields.
Thanks for your time and consideration.
> perf(ingest): remove unused variable in Looker ingestion

- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/entity/tag/TagProfile.tsx
The search query that populates this module was not quoting the search term, so tags with colons were not properly being found.
> fix(tags): fixing tag applied to module for tags w/ colons in the name

- metadata-ingestion/src/datahub/ingestion/source/lookml.py
In metadata ingestion for LookML files, the method `LookerViewFileLoader.load_viewfile()` is responsible for reading in a `.view.lkml` file, parsing it with `lkml`, and returning a `LookerViewFile` instance from it.
https://github.com/linkedin/datahub/blob/328b098d0156f01a91a226e03003152fadc1ac03/metadata-ingestion/src/datahub/ingestion/source/lookml.py#L207-L213
Since one view file could be matched by `include` statements in multiple model/view files, it's possible for `datahub ingest` to result in multiple `load_viewfile()` calls for the same view file. To avoid re-parsing the same file multiple times, the `LookerViewFileLoader` holds a cache of parsed files.
https://github.com/linkedin/datahub/blob/328b098d0156f01a91a226e03003152fadc1ac03/metadata-ingestion/src/datahub/ingestion/source/ …
> fix(ingest): ensure workunits are created for all LookML views

- metadata-ingestion/src/datahub/ingestion/source/lookml.py
Metadata ingestion for LookML requires a few operations that list files using `glob.glob()`. This PR proposes sorting those lists of files by name, to ensure that given the same set of `.lkml` files, `datahub ingest` will process them in the same order every time.
The ordering of results from `glob.glob()` is not guaranteed to be the same on different filesystems. See https://stackoverflow.com/a/6773661 for more details.
I faced a really difficult bug today. I created a docker image with an entrypoint that ran something like `datahub ingest -c /recipes/recipe.yaml`.
I found that I got different behavior in these two methods of running containers using that image:
* in a container on my laptop
- ```shell
git clone https://lookml-files.git
docker run -v $(pwd)/lookml-files:/model-files …
```
> fix(ingest): ensure that LookML files are always parsed in the same order

- metadata-ingestion/README.md
> docs(ingest): Add instructions to install dependency for airflow lineage

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
> fix(ingestion): Safeguard against empty values for profile ingestion

- metadata-io/src/test/java/com/linkedin/metadata/graph/ElasticSearchGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/Neo4jGraphServiceTest.java
This refactors `ElasticSearchGraphServiceTest.java` and `Neo4jGraphServiceTest.java` to reduce code duplication and establish a set of tests shared across those `GraphService` implementations. This ensures all implementations are tested in the same way, while individual implementations can still add implementation specific tests.
Adding another `GraphService` implementation can then easily be tested at the same level as existing implementations.
> refactor(test): Refactor GraphService tests

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsClientFactory.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/mappers/DataPlatformSnapshotMapper.java
Fix for https://github.com/linkedin/datahub/pull/2947- this uses the batch get endpoint to fetch data platforms by Urn, rather than the getAll endpoint which triggered a full table scan.
> fix(graphql): fetching data platforms using standard procedure

- datahub-web-react/src/App.tsx
Apollo caching has created some strange scenarios for us lately. In certain cases, it appears to swallow responses from graphql and return null entities even when the response has a fully fleshed out entity.
We should disable the apollo cache until we have time to thoroughly understand apollo's caching behavior.
> fix(blank pages): removing apollo caching

- docker/datahub-frontend/env/docker.env
- docker/datahub-gms/env/docker-without-neo4j.env
- docker/datahub-gms/env/docker.env
- docker/datahub-gms/env/docker.mariadb.env
- docker/datahub-gms/env/docker.postgres.env
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
Recently there have been reports of GMS failing on quickstart due to OOM. This PR addresses this by bumping the default heap allocation back up.
> fix(quickstart): Bumping Default Memory for GMS and Frontend

- metadata-ingestion/src/datahub/emitter/kafka_emitter.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_kafka.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/tests/unit/test_kafka_emitter.py
- metadata-ingestion/tests/unit/test_kafka_sink.py
Add support for MCP in kafka sink which allows us to ingest timeseries aspect through kafka.
> feat(ingest-proposal): adding support for MCP in kafka sink

- datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
- datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx
- datahub-web-react/src/app/entity/dataFlow/profile/DataFlowProfile.tsx
- datahub-web-react/src/app/entity/dataJob/profile/DataJobProfile.tsx
- datahub-web-react/src/app/entity/dataset/profile/DatasetProfile.tsx
Adds a refetch of the entity query on mutation. Previously, updating the cache was an effective solution. However, after disabling the cache in https://github.com/linkedin/datahub/pull/3008, this update logic became a no-op.
> fix(caching): refetch query on update

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/tests/integration/dbt/dbt_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_without_schemas_mces_golden.json
> feat(ingest): extract dbt versions into custom properties

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
- metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataService.java
- metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/SystemMetadataService.java
- metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataServiceTest.java
Now, restore indices will also restore system metadata index.
Also, in the case MAE sees null system metadata, we should ignore updating the system metadata service rather than throwing a NPE.
> fix(restore-indices): add system metadata restoration to restore-indices

- datahub-frontend/app/react/controllers/AuthenticationController.java
- datahub-web-react/src/app/Routes.tsx
- datahub-web-react/src/app/auth/LogIn.tsx
- docker/datahub-frontend/env/docker.env
Today, authentication checks erase the original URL path in cases where a user is not authenticated. This PR fixes this behavior and implements a redirect back to the original target URI on successful authentication, including when logging in via username and password.
> Encode Original URI in Authentication Redirect

- gms/client/src/main/java/com/linkedin/entity/client/EntityClient.java
- gms/impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- metadata-models/src/main/pegasus/com/linkedin/mxe/SystemMetadata.pdl
- smoke-test/test_e2e.py
If a partially constructed system metadata was received by GMS, it would error. Adding logic to fill in whatever blanks exist in system metadata here. Also adding smoke tests to test the various states we may receive system metadata
> fix(gms): handling partial system metadata in gms

- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
Avoid showing a blank lineage node for entities whose names end in `.`
> fix(lineage): fixing lineage abbreviations

- metadata-ingestion/src/datahub/cli/docker.py
The DataHub slack community is the best place to learn more about DataHub. This adds a link to the Slack community from Quickstart so new users can have the best experience onboarding to DataHub.
> feat(quickstart): linking to slack from quickstart

- datahub-web-react/src/app/home/HomePageHeader.tsx
Setting the container of the homepage elements to a fixed height so it doesn't jitter on load.
(review suggestion: selecting hide widespace changes makes the diff much simper)
> fix(homepage): fix homepage jitter

- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- docker/quickstart/generate_docker_quickstart.py
Remove mem_limit for datahub containers. Instead rely on JAVA_OPTS
```
051e80257213   datahub-frontend-react   1.78%     295.1MiB / 3.844GiB   7.50%     3.04kB / 555B   5.07MB / 0B       25
4deef6cf82ec   schema-registry          1.10%     182.4MiB / 3.844GiB   4.63%     364kB / 352kB   58.2MB / 8.19kB   34
b7ea3a0c4d62   datahub-gms              50.27%    840.5MiB / 3.844GiB   21.35%    679kB / 749kB   209MB / 0B        93
fb96b242a938   broker                   10.59%    299.7MiB / 3.844GiB   7.61%     948kB / 749kB   26.7MB / 537kB    73
fc47d4917b17   mysql                    3.01%     170.3MiB / 3.844GiB   4.33%     315kB / 241kB   40.8MB / 347MB    31
5af639f9b884   neo4j                    1.53%     393.1MiB / 3.844GiB   9.98%     11kB / 6.78kB   172MB / 119MB     44
75f0b5e36084 …
```
> fix(quickstart): Remove mem_limit for datahub containers

- docs/how/delete-metadata.md
- metadata-ingestion/src/datahub/cli/cli_utils.py
- metadata-ingestion/src/datahub/entrypoints.py
Add an easy way to configure datahub cli for remote instances.
```
(venv) ➜  datahub init
Configure which datahub instance to connect to
Enter your DataHub host [http://localhost:8080]: 
(Optional) Enter your DataHub access token []: 
Written to /Users/gabe/.datahubenv
(venv) ➜ datahub init
/Users/gabe/.datahubenv already exists. Overwrite? [y/N]: y
Configure which datahub instance to connect to
Enter your DataHub host [http://localhost:8080]: 
(Optional) Enter your DataHub access token []: 
Written to /Users/gabe/.datahubenv
```
> feat(datahub-cli): datahub init & docs for it

- metadata-ingestion/source_docs/glue.md
- metadata-ingestion/transformers.md
> docs(ingest): fix typos

- docker/docker-compose-without-neo4j.yml
Following a previous cleanup PR, removing unnecessary components from docker-compose-without-neo4j.yml to match docker-compose.yml
> fix(docker-compose): Remove unnecessary components from docker compose

- datahub-web-react/src/app/entity/dataset/profile/schema/utils/constants.ts
- datahub-web-react/src/app/entity/dataset/profile/schema/utils/translateFieldPathSegment.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/utils/utils.ts
- docs/advanced/field-path-spec-v2.md
- metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py
- metadata-ingestion/tests/unit/test_schema_util.py
A snippet of the MetadataAuditEvent visualized in Datahub:
> feat(nested avro): Adding clarity around qualified unions and removing extra lines for structs

- datahub-web-react/src/app/entity/dataset/profile/__tests__/schema/translateFieldPath.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/__tests__/schema/translateFieldPathSegment.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/__tests__/schema/utils.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/utils/utils.ts
- metadata-ingestion/examples/mce_files/bootstrap_mce.json
Key/Value schemas broke after adding the version prefix. This pr fixes that case, and also adds tests & sample data to prevent this from happening again so easily.
> fix(nested avro): fixing key / value schemas after adding version

- metadata-ingestion/sink_docs/datahub.md
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
After the latest release, there are numerous reports that ingestion is timing out for folks due to latencies in environments. 
Increasing the default timeout to 30 seconds to avoid unnecessary failures, while still being robust to complete outages.
> fix(ingest): increasing default ingestion REST timeout to 30 seconds

- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx
Schema version in its current form has caused some confusion for users, hiding it until we can iterate a bit more.
> fix(schema version): temporarily hide schema version tab

- datahub-frontend/app/controllers/CentralLogoutController.java
- datahub-frontend/app/react/auth/AuthModule.java
- datahub-frontend/conf/routes
- datahub-web-react/src/app/shared/ManageAccount.tsx
https://github.com/linkedin/datahub/issues/2735
calling identity provider to kill the logout session
> logout with oidc

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/IndexBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/SettingsBuilder.java
Add custom browse paths for kafka sources, so it does not separate on dots. 
Also removed the lowercase filter for browse, and added a way to reindex all indices on settings change.
> feat(ingest): Add custom browse paths for kafka sources and remove browse lowercase filter

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
The consumer id env variable is the same between MAE/MCE processor. This was fine before when the mae/mce containers were separated, but not that they are in the same gms pod, setting the env variable causes exception. Details https://github.com/linkedin/datahub/issues/3133
> fix(kafka): Change consumer id of mae/mce processor

- metadata-ingestion/setup.py
> fix(deps): Adding min version to python-dateutil to guard against isoparse failures

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/tests/integration/mysql/mysql_mces_golden.json
- metadata-ingestion/tests/integration/mysql/mysql_to_file.yml
- metadata-ingestion/tests/integration/mysql/setup/setup.sql
`res["unexpected_percent"]` is `NoneType` when profiling empty datasets and the division causes an exception. This PR is preventing that scenario.
Issue https://github.com/linkedin/datahub/issues/3132
> prevent NoneType exception when profiling empty datasets

- datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx
Currently hasKeySchema flag is mis-computed in cases where the index of the key field is 0, due to how Javascript handles 0 values (falsey).
> fix(kafka key schema): Refactoring hasKeySchema computation 

- metadata-ingestion/source_docs/lookml.md
- metadata-ingestion/src/datahub/ingestion/source/lookml.py
- metadata-ingestion/src/datahub/utilities/sql_parser.py
- metadata-ingestion/tests/unit/test_utilities.py
This PR makes it possible to configure the the SQL Parser used in the LookML-source. The rational is that Looker supports DB backends that common SQL parsers don't support (an example being Snowflake), and relying on the default SQL parser might fail or, even worse, produce erroneous results. After this change, users can define their own SQL parsers, which e.g. relying on EXPLAIN-queries to the database, producing more reliable results.
> feat(ingestion): Bring your own SQL parser

- metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/ElasticsearchSSLContextFactory.java
Looks like the `ElasticsearchSSLContextFactory` wasn't loading keys from the keystore, just certs.
> fix(gms): actually load keys from keystore for elastic connections

- metadata-service/auth/src/main/resources/graphiql/index.html
- metadata-service/graphql-api/src/main/java/com/datahub/metadata/graphql/GraphQLController.java
- metadata-service/graphql-api/src/main/java/com/datahub/metadata/graphql/GraphiQLController.java
This PR introduces a GraphQL Explorer accessible via the browser at the following locations:
- your-gms-domain/api/graphiql (example: `localhost:8080/api/graphiql`) 
- your-datahub-frontend-domain/api/graphiql (example: `localhost:9002/api/graphiql`) 
Enjoy exploring the Graph + documentation!
> Adding GraphQL Explorer! (GraphiQL) 

- metadata-ingestion/source_docs/kafka-connect.md
- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
This PR improves the Kafka connect source:
* Unknown connector classes are reported as failures, and does not crash the ingestion anymore. 
* Clarifies some typing and fixes some bugs due to accessing `NoneType`
* Makes it optional to construct the lineage dataset entities (input database table and output Kafka topic).
> feat(ingest): Minor Kafka Connect source improvements

- metadata-service/graphql-api/src/main/java/com/datahub/metadata/graphql/GraphQLController.java
When merging the graphql server into GMS an encoding bug was introduced. This change propagates the correct encoding header to the client.
> fix(frontend): fix utf-8 encoding bug

- datahub-web-react/src/app/entity/dataset/profile/__tests__/SchemaDescriptionField.test.tsx
- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entity/shared/components/styled/StripMarkdownText.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/__tests__/EntityProfile.test.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/SidebarAboutSection.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/DocumentationTab.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/__tests__/DocumentationTab.test.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/DescriptionEditor.tsx
- metadata-ingestion/examples/mce_files/bootstrap_mce.json
A bug was introduced in the redesign that hid the ingested description, even if no edited description was present. This PR:
1) fixes that issue
2) adds a test to check for this
3) adds default description to some tables in our sample data (none existed before)
Also fixes the issue where short descriptions were not rendered as markdown.
> fix(dataset redesign): show ingested description

- metadata-ingestion/source_docs/dbt.md
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
This PR adds an additional option `use_identifiers` to the dbt configuration to use nodes identifiers instead of names if those are defined, and default back to names if not.
Previously this was achieved by setting `load_schemas=False` however there are cases when we want to load schemas while using node identifiers instead of names (for ex. dbt does not write column descriptions to Snowflake on views* and those need to be ingested with `load_schemas=True`, while using identifiers to preserve the lineage).
*see https://github.com/dbt-labs/dbt/issues/3291
Also:
- renamed `load_catalog` to `load_schemas` in dbt.py for consistency with the config file
- fixed a case issue when reading columns from catalog vs manifest files (names are upper case in the catalog but lower case in the …
> fix(dbt): add use_identifiers option and avoid duplicate descriptions

- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
- metadata-ingestion/transformers.md
This is adding the ability to specify the ownership type in the ownership transformations. `DATAOWNER` is the default value if not given or if an unexpected value is given.
> add optional config for ownership type in ownership transforms

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManagerApplicationListener.java
- metadata-service/restli-client/src/main/java/com/linkedin/common/client/BaseClient.java
404 causes process to exit for previous upgrades. Need to figure out how to make backwards incompatibility checks more robust. 
Also removing a cheeky log line John added during a period of great dev frustration
> fix(404): Fix 404 Exit Error.

- datahub-web-react/src/app/entity/shared/components/styled/AddLinkModal.tsx
During redesign refactoring, the actor being passed became a full user instead of an urn. Fixing.
> fix(ui): Fix adding Links to assets 

- datahub-web-react/src/graphql-mock/schema.ts
Remove the `datahub-frontend.graphql` from the mock server, the schema definition is already covered in the `gms.graphql`.  And the original file (`'../../../datahub-frontend/conf/datahub-frontend.graphql'`) is been removed.
> Remove the `datahub-frontend.graphql`

- metadata-service/graphql-api/src/main/java/com/datahub/metadata/graphql/GraphQLController.java
Title says it. GraphiQL passes an explicit null value when variables are not present. Supporting this case.
> fix(graphql): Allow explicit JSON null in GraphQL endpoint 

- .github/workflows/build-and-test.yml
This uploads the test reports to GitHub so that they can be investigated when test fails:
> ci: Upload test reports

- metadata-service/auth/src/main/java/com/datahub/metadata/authorization/AuthorizationManager.java
- metadata-service/auth/src/main/java/com/datahub/metadata/authorization/PolicyEngine.java
- metadata-service/auth/src/test/java/com/datahub/metadata/authorization/AuthorizationManagerTest.java
- metadata-service/auth/src/test/java/com/datahub/metadata/authorization/PolicyEngineTest.java
- metadata-service/graphql-api/src/main/java/com/datahub/metadata/graphql/AuthorizationManagerFactory.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/OwnershipClient.java
- metadata-utils/src/main/java/com/linkedin/metadata/Constants.java
2 changes:
1. Fixing issue where "ALLOW_ALL" mode was not being honored (misconfigured test)
2. Adding an "authorizedActors" method to AuthorizationManager to allow asking the question: "Who is authorized for this privilege against this resource?" 
3. Introducing a thin wrapper called OwnershipClient to make fetching the standard Ownership aspect easier. 
4. Unit tests
> feat(access control): Adding "authorizedActors" method to AuthorizationManager

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManagerApplicationListener.java
Currently, bootstrap manager invoked 2 times for each spring context: root context and that created by the API servlet dispatcherservlet. This PR ensures that we only run when the Root context is refreshed at boot time. 
Validated locally.
> fix(bootstrap): Invoke BootstrapManage once

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
Properties may not have model groups. Thus we need to return either an empty list of a list of group urns.
> fix(ML): Fix ML Model Properties resolver 

- datahub-web-react/src/app/ProtectedRoutes.tsx
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/search/SearchHeader.tsx
- datahub-web-react/src/app/shared/admin/AdminHeaderLinks.tsx
The admin hamburger floater would sometimes overlap important information. Moving to header for now so it won't conflict with other content.
> fix(admin): moving admin links to header

- metadata-ingestion/source_docs/looker.md
- metadata-ingestion/src/datahub/ingestion/source/looker.py
[all_dashboards()](https://github.com/looker-open-source/sdk-codegen/blob/6f9c8b0065acebe0304b0db121ac0ccdfb1466d4/python/looker_sdk/sdk/api31/methods.py#L2027-L2034) does not return deleted dashboards (even says so in the comments).
> fix(ingest): ingest deleted looker dashboards

- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
- datahub-web-react/src/app/entity/shared/components/legacy/UpdatableDescription.tsx
- datahub-web-react/src/app/entity/shared/components/styled/AddLinkModal.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/DescriptionEditor.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/LinkList.tsx
Update in a few places to safely access caught Error properties via typescript4 `unknown on catch Clause Bindings`  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#unknown-on-catch-clause-bindings
> Safely access caught Error properties

- datahub-web-react/src/setupProxy.js
Logging in while developing on the react app caused some proxy issues. This only occurred while loading the react app in development mode while not logged in.
The issue was that the login page was proxied to the frontend server and served from there. It in turn had references to the frontend server's generated bundles. However, the bundle fetching was not proxied. Since the generated bundle ids are randomly created, the development react server would not find the frontend server's bundle ids.
This fix stops the login page from being proxied to the frontend server so the correct bundle ids are included in the page.
> fix(local-development): fix proxy for login route

- datahub-web-react/src/app/entity/shared/containers/profile/nav/ProfileNavBrowsePath.tsx
- datahub-web-react/src/conf/theme/theme_dark.config.json
- datahub-web-react/src/conf/theme/theme_light.config.json
- datahub-web-react/src/conf/theme/types.ts
The button group would previously indicate that lineage was unavailable thru grey text on the Lineage button. This fixes it!
> fix(ui): fix lineage button color

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/tag/mappers/TagSnapshotMapper.java
Removing the 2nd place that tag name is set in tag mapper- this caused issues when TagProperties were set but name was not set equal to name in the urn.
> fix(tags): fix tag name overwrite

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManagerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestDataPlatformsStep.java
- metadata-service/war/src/main/resources/boot/data_platforms.json
> feat(ingest): Auto Ingestion Data Platforms on GMS boot

- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
- metadata-ingestion/examples/mce_files/bootstrap_mce.json
Refresh add description button and remove jitter when hovering over it
> fix(UI): fix jitter on schema when adding description

- metadata-io/src/test/java/com/linkedin/metadata/ElasticSearchTestUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/ElasticSearchGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectServiceTest.java
This improves `syncAfterWrite` for ElasticSearch GraphService tests, which reduces test time to the possible minimum (0,08s per test, not waiting 5s per test any more). This fixes #3124.
The logic of `syncAfterWrite` is used by all ElasticSearch tests in metadata-io now, speeding up those tests as well.
> test(metadata-io): Improve speed of ElasticSearch tests

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManager.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestPoliciesStep.java
This PR ensures that we only ingest bootstrap policies when a clean start occurs, or when no bootstrap policies have already been ingested.
Thanks to @aseembansal-gogo for reporting!
> fix(policies): Only ingest bootstrap policies on clean start

- datahub-web-react/src/app/browse/BrowseResultCard.tsx
- datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
- datahub-web-react/src/app/entity/shared/utils.ts
- datahub-web-react/src/app/shared/tags/TagTermGroup.tsx
1) added spacing btwn Add Term & Add Tag buttons in the case that no tags or terms were applied
2) change glossary term collection name from Business Glossary to Glossary Terms
3) add logic in browse to singularize in the case only 1 entity exists in a directory
> fix(glossary terms & browse): some cosmetic fixes

- datahub-frontend/app/controllers/TrackingController.java
- datahub-frontend/conf/application.conf
Requested config: analytics.kafka.sasl.login.callback.handler.class
This should be resolved once we move Tracking module to GMS.
> fix(frontend): Add additional sasl config for kafka producer in datahub-frontend

- metadata-service/restli-impl/src/main/java/com/linkedin/metadata/resources/usage/UsageStats.java
> fix(usage statistics): populate the email field

- datahub-web-react/src/app/entity/shared/constants.ts
- datahub-web-react/src/app/entity/shared/containers/profile/__tests__/EntityProfile.test.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/SidebarTagsSection.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useTagsAndTermsRenderer.tsx
- datahub-web-react/src/app/shared/tags/TagTermGroup.tsx
Render tags and terms in separate sections.
Terms present:
Empty state:
> feat(glossary): splitting apart tags & terms into their own visual sections

- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
This PR allows ingesting Business Glossary terms defined at the root level (without nodes).
Tested locally with DataHub v0.8.13.
> fix(ingest): allow ingestion of glossary terms without nodes

- docs/how/delete-metadata.md
- metadata-ingestion/src/datahub/cli/cli_utils.py
- metadata-ingestion/tests/unit/test_cli_utils.py
> feat(ingest): support for env variable in cli

- metadata-io/src/main/java/com/linkedin/metadata/graph/GraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/Neo4jGraphService.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/ElasticSearchGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/Neo4jGraphServiceTest.java
Adds a more complex test graph and tests all `GraphService` methods thoroughly. In the current implementation, tests depend on the order of test execution, as they share the state of the tested service.
As the interface is not documented, a couple of questions on which results to expect from the given graph arose:
- Is it expected that `findRelatedUrns` returns duplicates, i.e. Urns may occur multiple times?
- Answer: findRelatedUrns should not return duplicates.
- Should `findRelatedUrns` with `RelationshipDirection.UNDIRECTED` return the union of `RelationshipDirection.OUTGOING` and `RelationshipDirection.INCOMING`?
- Answer: It should return the union of outgoing & incoming.
- The `sourceType` and `destinationType` of `findRelatedUrns` are explicitly `@Nullable`. Does `null` represent …
> test(GraphService): Thorough graph service tests

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestPoliciesStep.java
**Changes**
We want to ingest non-editable (super user privileges, or those which cannot be edited via the UI) on every boot just in case the default policies have changed, for example in cases where new Privileges are added. 
As for editable policies, we should only ingest these on a clean boot so that any custom changes that are made are saved and not overwritten on restart.
> fix(policies): Always ingest non-editable policies on boot

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/mappers/ChartSnapshotMapper.java
Inputs is optional, can cause NPE if accessed when null.
> fix(chartinfo): only map chartinfo inputs if exists

- metadata-ingestion/tox.ini
> fix(tox): allow tox to recreate testenv when new dependencies are added to setup.py

- docs/what/entity.md
This link needed a `.md` suffix.
> docs(entity): fix link in entity docs

- datahub-frontend/app/auth/sso/oidc/OidcProvider.java
- datahub-frontend/app/auth/sso/oidc/custom/CustomOidcAuthenticator.java
- datahub-frontend/app/auth/sso/oidc/custom/CustomOidcClient.java
- datahub-frontend/app/auth/sso/oidc/custom/EmptyAuthentication.java
- datahub-frontend/run/frontend.env
We've received a few asks from the community to supporting the "NONE" OIDC authentication method. This PR introduces that support by extending Pac4j's default OIDC Client + Authenticator classes. 
An alternative solution to this would have been upgrading Play & Pac4j, which proved very challenging due to the Play Gradle plugin we are leveraging. The long term solution will involve performing this upgrade, if possible.
> feat(oidc): Support NONE client auth method in OIDC (stopgap) 

- metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DataProcessAspect.pdl
- metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/DataProcessSnapshot.pdl
We now recommend using the Data Job model to model one-off data processes.
> feat(metadata-model): marking data process aspect & snapshot as deprecated

- datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
Lineage UI throwing a client side error due to removal of a field that was assumed to be unused. Fixing to remove an unnecessary method, as suggested by @gabe-lyons
> fix(ui): Fixing lineage UI for charts + dashboards

- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/AddOwnerModal.tsx
- datahub-web-react/src/app/policy/PolicyActorForm.tsx
- datahub-web-react/src/app/policy/PolicyPrivilegeForm.tsx
Previously, adding an owner required a selection of "user" or "group" type along with using a strange ldap field to find them. I've gone ahead and simplified the flow, replacing it with a simple search bar that finds users and groups for you as you type. 
Before:
After:
> feat(ui): Improve add owner search experience

- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
The current implementation of aspect versioning relies on the transactions to be with the isolation level of repeatable read in order to avoid lost updates (as discussed in https://datahubproject.io/docs/advanced/aspect-versioning/#transaction-isolation-1 and illustrated in https://github.com/linkedin/datahub/issues/3231).
Although the default isolation level is repeatable read for MySQL, ebean sets the default transaction isolation to be read committed (https://github.com/ebean-orm/ebean-datasource/blob/master/ebean-datasource-api/src/main/java/io/ebean/datasource/DataSourceConfig.java#L38); this PR ensures that the transactions use the repeatable read isolation level.
Another option would be to set it as the default/make it configurable (e.g. in …
> (fix) Set ebean transaction level to be repeatable read

- docker/datahub-frontend/README.md
An issue came up in the community Slack with someone trying to build the `datahub-frontend` docker image to test changes they had made.
Current docs point you to the datahub-frontend folder where the Dockerfile exists, but did not include any instructions for building. I added a few simple instructions after discussing in Slack and testing locally.
Small addition, but hope it helps.
> docs(datahub-frontend): add build instructions for the datahub-frontend docker image

- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_browse_path.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
- metadata-ingestion/transformers.md
This is adding `replace_existing` config option to `set_dataset_browse_path` transform enabling two different behaviours for the transform: adding browse paths (default) or set browse paths (so overwriting existing browse paths if any).
> feat(transform): adds replace_existing config to set_dataset_browse_path

- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
This PR proposes to ingest redshift external tables and links the external tables to the corresponding external database and its table as upstream lineage. Currently, only supporting glue external database.
> feat(redshift): added ability to extract external schema from Redshift spectrum

- docker/datahub-ingestion/Dockerfile
Hive ingestion receives the following exception.
```
thrift.transport.TTransport.TTransportException: Could not start SASL: b’Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found’
```
In order to fix that, we added `libsasl2-modules` in datahub ingestion docker image.
> fix(ingest): Fix sasl exception for hive ingestion

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> fix(ingest): no error when there are no partition keys

- datahub-graphql-core/src/main/resources/entity.graphql
External url has moved twice now- updated first deprecation notice
> fix(docs): fix graphql deprecated comment

- datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java
Allow "null" value when setting the email for OIDC profile
> fix(oidc): Tolerate null emails

- metadata-ingestion/examples/recipes/redash_to_file.yml
- metadata-ingestion/setup.py
- metadata-ingestion/source_docs/redash.md
- metadata-ingestion/src/datahub/ingestion/source/redash.py
- metadata-ingestion/tests/unit/test_redash_source.py
- Add feature parse table names from SQL
- Adding `QualifiedNameParser` and several extended dataclasses for parsing table name into fully qualified name based on database type. As an example, table name `orders` in Postgres database should be normalized into `databaseName.public.orders` if only table name part given
- Some small refactors to improve
> feat(ingest): Redash add parse_table_names_from_sql feature and multiple refactor

- metadata-ingestion/source_docs/dbt.md
- metadata-ingestion/src/datahub/ingestion/source/dbt.py
This PR allows the dbt tag prefix that was introduced in https://github.com/linkedin/datahub/pull/3270 to be configurable instead of hard-coded.
Tested locally with DataHub v0.8.15.
> fix(ingestion): make dbt tag prefix configurable

- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/LineageVizInsideZoom.tsx
1) expands the click area of expand buttons so they will be harder to miss
2) shows hover feedback when hovering over expand buttons
3) shows loading indicator after clicking and before the additional lineage pops in
4) Recentering the viz on a new node clears all stored drag state so the user isn't dropped into a very confusing situation
> feat(lineage): some ux improvements to lineage interactions

- metadata-io/src/main/java/com/linkedin/metadata/search/utils/BrowsePathUtils.java
During a recent code cleanup, we moved the logic of computing browse paths to BrowsePathUtils, which uses entity keys to compute default browse path. We were mistakenly taking the DataPlatform URN associated with a Dataset instead of its platform name (the legacy behavior).
> fix(browse paths): Adjust Default browse path logic for datasets

- datahub-web-react/src/app/entity/shared/components/styled/ExpandedOwner.tsx
> add tooltip for owner category in dataset profile page

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/RollbackResult.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeLogProcessor.java
Historically, deletes were only processed by the MAE processor. This meant only aspects that existed within the universe of Snapshots could be deleted. This presents an issue as Datahub moves away from the snapshot model. This PR:
1) removes deletion logic from MAE processor
2) adds deletion logic for non-timeseries aspects to MCLProcessor
Test plan:
- ingest snapshot aspects
- revert the snapshot aspects
- verify the data is gone from search, entity, and graph services
- ingest mcp only aspects
- revert mcp only aspects
- verify the data is gone from search, entity, and graph services
> feat(deletes): support deletion of non-snapshot aspects

- metadata-ingestion/setup.py
A recent change in botocore causes issues with older versions of urllib3. A fix has already been merged into the library here https://github.com/boto/botocore/pull/2563, so we simply need to restrict the versions we allow in our requirements.
This should fix the build, which is currently broken on master.
Also fixes setup.py formatting issues.
> fix(ingest): restrict botocore version to fix urllib3 build issue

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/DatasetSnapshotMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/Mocks.tsx
- datahub-web-react/src/app/browse/BrowseResultsPage.tsx
- datahub-web-react/src/app/entity/chart/ChartEntity.tsx
- datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
- datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx
- datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/SidebarAboutSection.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/DocumentationTab.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/__tests__/DocumentationTab.test.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/DescriptionEditor.tsx
- datahub-web-react/src/app/entity/shared/types.ts
- datahub-web-react/src/app/home/HomePageHeader.tsx
- datahub-web-react/src/app/shared/entitySearch/__tests__/RelatedEntity.test.tsx
- datahub-web-react/src/app/shared/entitySearch/__tests__/RelatedEntityResult.test.tsx
- datahub-web-react/src/graphql/browse.graphql
- datahub-web-react/src/graphql/chart.graphql
- datahub-web-react/src/graphql/dataFlow.graphql
- datahub-web-react/src/graphql/fragments.graphql
- datahub-web-react/src/graphql/preview.graphql
- datahub-web-react/src/graphql/relationships.graphql
- datahub-web-react/src/graphql/search.graphql
This PR migrates to using the description field of the standard "properties" bag in the GraphQL API, moving away from using the deprecated "info" fields sporadically. It also addresses a few description-rendering related bugs:
- Browse previews will correctly reflected edited descriptions
- All entity pages will correctly reflect system-provisioned descriptions
This is part of an initiative to more toward convergence of common entity fields to make UI development a simpler proecss.
> ui: Migrate UI to use "properties" field of entity for descriptions

- datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryTermProfile.tsx
Addressing https://github.com/linkedin/datahub/issues/3540
> fix(glossary terms): Fix 'Glossary Term on Dataset Columns doesn't show in Related Entities'

- docs/api/graphql/querying-entities.md
- docs/debugging.md
Previously our CURLs were pretty formatted which doesn't work on copy n paste. This change fixes that. Verified each works locally.
> docs(graphql): Updating example CURLs to work on copy and paste + misc FAQ doc improvements 

- .github/workflows/docker-frontend-react.yml
- docker/datahub-frontend/Dockerfile
Build frontend docker on build platform instead on target platform
> [fix] Build frontend docker on build platform instead on target platform

- datahub-frontend/app/controllers/Application.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
Our client libs don't like when we set `content-type` and `content-length` headers manually.. this change removes those headers and thus hushes the warnings.
> fix(frontend): Hush noisy datahub-frontend warnings 

- metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
changes to bigquery_usage ingestion:
- fix: add partition decorator to partitioned table regex
- refactor: move invalid table exception handling to after regex matching
- feat: add bigquery table snapshot handling
- Add partition decorator `$` to regex 
- Documentation: https://cloud.google.com/bigquery/docs/managing-partitioned-table-data
- Check for partitioned table matching (and table snapshot matching) before handling exceptions that don't match
- Add bigquery table snapshot regex and matching
- Documentation: https://cloud.google.com/bigquery/docs/table-snapshots-intro
> fix(bigquery_usage ingestion): add partition decorator to regex, move exception handling to after matching, add table snapshots

- .github/workflows/build-and-test.yml
- build.gradle
- metadata-io/build.gradle
- metadata-io/src/main/java/com/linkedin/metadata/graph/DgraphExecutor.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/DgraphGraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/DgraphSchema.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/DgraphContainer.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/DgraphGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java
This implements the GraphService API for Dgraph (https://dgraph.io). This implementation passes all GraphService tests added in #3011. Integration of Dgraph into GMS factories and the Docker setup is happening in a follow-up PR.
Fixes #3084.
> feat(GraphService): Add Dgraph implementation of GraphService

- metadata-io/build.gradle
This repeats #3358. This has been reverted accidentally by #3379.
> Run metadata-io tests in parallel

- datahub-web-react/src/graphql/user.graphql
Ownership count was not being fetched in the user graphql query.
Long term fix:
- we should make sure to cover this case in the upcoming cypress test pass on the UI
> fix(users): fix ownership count on user page

- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryTermProfile.tsx
Making the GlossaryTermInfo Nullable within GlossaryTerm. This is to make sure when there is no info returned we are not constrained to always set GlossaryTermInfo. reference: https://github.com/linkedin/datahub/blob/master/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryTermSnapshotMapper.java#L36
> fix(graphql): making glossaryTermInfo nullable in glossaryTerm.

- datahub-web-react/src/app/search/SearchBar.tsx
If a user presses Enter while their search query matches an autocomplete suggestion, both `onPressEnter` of the search bar and `onSelect` are triggered. Adding a `stopPropogation` call to prevent the autocomplete component's method from getting fired.
> fix(autocomplete): fix case where autocomplete interferes with search

- metadata-ingestion/README.md
- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Adds `--dry-run` and `--preview` options to `datahub ingest` command.
The `--dry-run` option of the `ingest` command performs all of the ingestion steps, skipping the writing to the sink step, producing the standard run summary.
The `--preview` option of the `ingest` command performs all of the standard ingestion steps, except that it restricts processing to at most 10 work units.
> feat(ingestion): Adds --dry-run and --preview options to datahub ingest command.

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json
This PR fixes an issue when dbt metadata is ingested with `disable_dbt_node_creation == False` where source nodes get assigned the `dbt` platform instead of the `target_platform`.
Before:
`dbt,source_db.source_schema.source_table -> dbt,model_db.model_schema.model_table -> target_platform.model_db.model_schema.model_table`
After:
`target_platform,source_db.source_schema.source_table -> dbt,model_db.model_schema.model_table -> target_platform.model_db.model_schema.model_table`
No changes when `disable_dbt_node_creation == True`.
Tested with v0.8.16.
> fix(ingest): fix dbt source platform when disable_dbt_node_creation is False

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESBrowseDAO.java
Restrict aggregation size as elasticsearch can only take up to 10K aggregations. 
Also add include/exclude for the ALL_PATHS aggregation to make sure we don't return all browse paths.
> fix(browse): Fix browse response size issue when there are too many browse paths

- docker/README.md
- docs/how/delete-metadata.md
This is needed because it seems people don't know where the CLI is present for usage when datahub is deployed.
e.g. https://datahubspace.slack.com/archives/CUMUWQU66/p1637050607405700?thread_ts=1637043099.404900&cid=CUMUWQU66
> fix(docs): Add docs on accessing datahub CLI

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/snapshot/ColumnStats.tsx
- datahub-web-react/src/app/entity/shared/tabs/Properties/PropertiesTab.tsx
This fixes style inconsistency where `Roboto Mono` isn't installed on the end-users machine. In this instance, it defaults to a serif font. It is defined properly in [other parts of the React App ](https://github.com/linkedin/datahub/blob/a36fefaa33df8c518faf2a9daf63c94e74bc33a1/datahub-web-react/src/app/entity/dataset/profile/schema/utils/schemaTitleRenderer.tsx#L27)codebase
`bad`
`good`
> style(react-app): add default monospace font to font-family

- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/BootstrapManagerFactory.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestRootUserStep.java
- metadata-service/war/src/main/resources/boot/root_user.json
This PR introduces a bootstrap step to ingest the DataHub root user, to make how we ingest the root user similar to how we ingest data platforms etc.
> feat(boot): Ingest datahub root user info on boot

- metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
1. Fix allow deny filters when patterns are not present
2. Still produce read events when join does not happen.
3.
> fix(bigquery-usage): Fix filters and event joining logic.

- metadata-ingestion/setup.cfg
- metadata-ingestion/setup.py
- metadata-ingestion/source_docs/sql_profiles.md
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py
The GE profiler issues a ton of queries that each return a single number or a single row. This PR adds support for dynamically combining these queries together at runtime, which reduces the total number of queries issued.
Using the same testing setup as #3369 and #3510.
Small table - 9 columns, 500 rows
- previous: 8.8-10.2 seconds
- with changes: 5.4-6.4 seconds
Medium table - 16 columns, 60k rows
- previous: 17.4-18.5 seconds
- with changes: 12.2-14 seconds 
These changes really shine when `turn_off_expensive_profiling_metrics` is enabled, where it yields a 2-3x speedup.
> feat(profiler): dynamically combine queries

- metadata-io/src/main/java/com/linkedin/metadata/timeseries/TimeseriesAspectService.java
- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/EntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/JavaEntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
Profiling NPE was thrown due to the nullability of the "limit" argument when fetching timeseries aspects. This bug was recently introduced (since prev release) when we ported from RestliEntityClient to JavaEntityClient
> fix(java client): Fix Profiling NPE + misc improvements

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/search/SearchService.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- smoke-test/test_e2e.py
Logic in EntityResource was bypassed as we moved to using JavaClient which did not have this logic.
> fix(search): Fix issue when query is empty

- metadata-ingestion/setup.py
Looks like CI failures might be related to new version of GE.
> fix(ci): pin great expectations version

- metadata-ingestion/src/datahub/cli/cli_utils.py
Remove logic that adds an invalid filter for platform field. This is causing an issue when entity_type is dataFlow and platform filter is set.
> fix(delete): Remove logic that adds an invalid filter for platform field

- metadata-dao-impl/kafka-producer/src/main/java/com/linkedin/metadata/dao/producer/EntityKafkaMetadataEventProducer.java
remove double string formatting to prevent `IllegalFormatConversionException`
when aspect urn contains formatting strings
closes: https://github.com/linkedin/datahub/issues/3625
This is just a possible proposal. Let me know if you prefer a different logging format and if you think that tests are necessary
> fix(kafka-producer): fix debug logging

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
Add config to specify ca certificate path for datahub-rest sink
> fix(ingestion): Add config to specify ca certificate path for datahub-rest sink

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
Waiting on https://github.com/great-expectations/great_expectations/issues/3758 for a full fix.
> fix(ingest): workaround great-expectations compatibility issue

- datahub-web-react/src/app/entity/group/GroupProfile.tsx
A bug was introduced in a recent PR. This reverts the change.
Huge thanks to @serefacet for finding this!
> fix(group ownership): Fixing Groups Profile ownership

- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
Enhance supported and unsupported base_objects_accessed.
Capture queries from Internal/External stages such as COPY FROM/TO.
SKIP base objects such as S3 locations accessed.
> fix(ingestion): Enhance supported and unsupported base_objects_accessed for Snowflake Usage

- datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaDescriptionField.tsx
Added in https://github.com/linkedin/datahub/pull/2707. This stopProp & preventDefault does not appear do anything productive- tested a few scenarios of expanding/contracting, editing/unediting, etc. All seemed to function with these lines removed. This also allows links to work again!
> fix(description): fix issue where markdown links are unclickable

- metadata-io/src/test/java/com/linkedin/metadata/DockerTestUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/DgraphGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/ElasticSearchGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/SearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectServiceTest.java
Adds docker engine check during docker-based tests in setup stage to validate that the system running the tests has sufficient memory resources for the successful execution of the test.
PR was tested and validated by manually changing docker engine configurations to not meeting 8GB requirements. Tests failed as expected:
This follows a convention akin to https://github.com/linkedin/datahub/blob/2f6fca169a2bce24d5c0ccecd5a0bbe177286fdb/metadata-ingestion/src/datahub/cli/docker_check.py#L70
- [x ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
> fix(metadata-io) Adds docker engine configuration checks before running docker-based tests

- metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
- metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
It seems there was a new version of `black`, so we need to reformat some code.
> fix(ingestion): black formatting

- metadata-ingestion/scripts/datahub_preflight.sh
Non m1 computers have `uname` of Darwin as well. We need to also verify the machine hardware name in order to run m1 checks.
> fix(metadata-ingestion): fix requirements for m1 preflight checks

- docs-website/docusaurus.config.js
Pointing nav links to roadmap back to docs instead of HelloNext until that's more built out.
> docs: change roadmap link in docs

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/tag/TagType.java
This fix changes tag create privileges to be correctly assigned to TAGs. Huge thanks to xL for reporting this on Slack originally. 
Issue: https://github.com/linkedin/datahub/issues/3609
> fix(tags): Fixing Tag Create Privileges (issue #3609) 

- README.md
- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_tags.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_terms.py
- metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
- metadata-ingestion/transformers.md
> feat(transformer) Adds glossary terms transformer

- metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
Disable query parser failure reporting to Datahub in redshift lineage by default
> fix(ingestion): Disable query parser failure reporting to Datahub in redshift lineage by default

- datahub-web-react/src/app/entity/shared/utils.ts
We didn't encode square brackets in our encode method. this created problems because square brackets are used in spark streaming entity urns.
> fix(url encoding): also encode square brackets

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/UpgradeCli.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/UpgradeCliApplication.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/common/steps/GMSDisableWriteModeStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/common/steps/GMSEnableWriteModeStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/common/steps/GMSQualificationStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/NoCodeUpgradeConfig.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/RestoreBackupConfig.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocode/NoCodeUpgrade.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restorebackup/RestoreBackup.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/RestoreIndices.java
Addition of auth caused an injection failure in datahub-upgrade. This PR aims to fix this while also making sure all entity clients refer to the RestliEntityClient and not the JavaEntityClient
> fix(datahub-upgrade): Fix Spring injection issue with datahub-upgrade

- metadata-dao-impl/kafka-producer/build.gradle
- metadata-events/mxe-registration/build.gradle
- metadata-events/mxe-utils-avro-1.7/build.gradle
- metadata-ingestion-examples/common/build.gradle
- metadata-ingestion-examples/kafka-etl/build.gradle
- metadata-ingestion-examples/mce-cli/build.gradle
- metadata-io/build.gradle
- metadata-service/restli-servlet-impl/build.gradle
- metadata-testing/metadata-models-test-utils/build.gradle
- metadata-testing/metadata-test-utils/build.gradle
- metadata-utils/build.gradle
A [vulnerability ](https://www.lunasec.io/docs/blog/log4j-zero-day/)has been identified in `log4j`. The latest version `2.15.0` fixes the vulnerability.
> Fix CVE-2021-44228

- datahub-web-react/src/app/search/SearchResultsRecommendations.tsx
`0` is not truthy in javascript but it is considered valid html content. in this case, it will exit the `&&` chain but return `0`, which renders. Transforming it into a boolean with `!!`, we will no longer render an artifact because `false` is rendered the same as `null`-- with nothing.
> fix(recommendations): don't show a `0` character when there are no suggestions

- metadata-ingestion/src/datahub_provider/hooks/datahub.py
> fix(ingestion): adds missing port to the connection bootstrap 

- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/elasticsearch-setup/Dockerfile
Got reports that base64 version may be different in different platforms. Adding coreutils which downloads the gnu base64 making it consistent across platforms.
> fix(docker): Fix issues with base64 not working on some platforms

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
Prior to this change, profiled tables were counted as normal scanned tables (since `report_entity_scanned` defaults to `ent_type="table"`), and hence the count of scanned tables was incorrectly reported.
> fix(ingest): count profiled tables separately in report

- docker/elasticsearch/env/docker.env
> (fix) Elastic search container log4j CVE-2021-44228 vulnerability

- metadata-ingestion/source_docs/snowflake.md
- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
`direct_objects_accessed` will display the view in the case a view is used. `base_objects_accessed` will display the underlying table the view was built off of. For usage, it makes more sense to default to `direct_objects_accessed`. This also includes a knob to use `base_objects_accessed` in the case a user would prefer that.
> feat(snowflake-usage): add knob for direct objects accesssed vs base objects accessed

- metadata-ingestion/source_docs/snowflake.md
- metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
> fix(snowflake): support snowflake allow/deny pattern for lineage and usage

- metadata-service/auth-impl/build.gradle
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/TokenService.java
**Summary** 
The Token Service requires a 256-bit signing key. We had previously assumed this key would be a Base64'd string, but are changing that to relax the requirements for this signing key as UTF-8 string. After this change, anyone who has enabled Metadata Service Authentication which was released last week will need to regenerate their Personal Access Tokens. 
Why do this? We want to be more flexible in the signing keys we accept to improve usability. We will handle the base64 encode and decode as required within the Token Service.
> refactor(gms auth): Remove base64 decoding of token service signing key 

- metadata-ingestion/tests/unit/test_usage_common.py
Pytest tries to treat classes of the form `Test*` as classes with tests, which is incorrect here. Adding the underscore prefix resolves the issue.
> test(ingest): fix pytest warning for class starting with `Test`

- metadata-dao-impl/kafka-producer/build.gradle
- metadata-events/mxe-registration/build.gradle
- metadata-events/mxe-utils-avro-1.7/build.gradle
- metadata-ingestion-examples/common/build.gradle
- metadata-ingestion-examples/kafka-etl/build.gradle
- metadata-ingestion-examples/mce-cli/build.gradle
- metadata-io/build.gradle
- metadata-service/restli-servlet-impl/build.gradle
- metadata-testing/metadata-models-test-utils/build.gradle
- metadata-testing/metadata-test-utils/build.gradle
- metadata-utils/build.gradle
> Fix CVE-2021-44228 continued:  log4j constraints to version 2.16.0

- metadata-ingestion/examples/recipes/mode_to_datahub.yml
- metadata-ingestion/source_docs/mode.md
- metadata-ingestion/src/datahub/ingestion/source/mode.py
Implement exponential backoff retry logic when accessing Mode API to avoid HTTP error 429: "Too many API request".
See Datahub Mode connector [Config Details](https://github.com/jawadqu/datahub/blob/62a0f5e9740fb7cc1cc157ae7fdcb06dbb479156/metadata-ingestion/source_docs/mode.md#config-details) on how to customize these settings.
> feat(ingestion): Mode retry wait logic to avoid hitting Mode API rate limit

- metadata-ingestion/setup.py
- metadata-ingestion/source_docs/mysql.md
- metadata-ingestion/source_docs/redshift.md
- metadata-ingestion/source_docs/snowflake.md
- metadata-ingestion/source_docs/stateful_ingestion.md
- metadata-ingestion/src/datahub/ingestion/api/common.py
- metadata-ingestion/src/datahub/ingestion/api/ingestion_state_provider.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
- metadata-ingestion/src/datahub/ingestion/source/state/sql_common_state.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
- metadata-ingestion/src/datahub/ingestion/source/state/usage_common_state.py
- metadata-ingestion/src/datahub/ingestion/source/state_provider/datahub_ingestion_state_provider.py
- metadata-ingestion/src/datahub/ingestion/source/state_provider/state_provider_registry.py
- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
- metadata-ingestion/tests/integration/hive/hive_mces_golden.json
- metadata-ingestion/tests/integration/mysql/mysql_mces_golden.json
- metadata-ingestion/tests/integration/sql_server/mssql_mces_golden.json
- metadata-ingestion/tests/integration/trino/trino_hive_mces_golden.json
- metadata-ingestion/tests/integration/trino/trino_mces_golden.json
- metadata-models/src/main/pegasus/com/linkedin/datajob/datahub/DatahubIngestionCheckpoint.pdl
- smoke-test/requirements.txt
- smoke-test/test_e2e.py
- smoke-test/tests/utils.py
1. Adds the datahub ingestion state provider for committing and retrieving checkpoint states.
2. Support for stale table/view removal for SQL based sources with stateful ingestion.
3. Skipping reruns for snowflake_usage connector with stateful ingestion.
4. Feature [documentation](https://github.com/linkedin/datahub/blob/5796935cf0526fc8d98a6e7d0c8e9fe020ef0a14/metadata-ingestion/source_docs/stateful_ingestion.md).
5. Integration tests.
> feat(Stateful Ingestion-2/3): Client side changes for checkpointing a source job state.

- metadata-ingestion/tests/integration/hive/test_hive.py
- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
- metadata-ingestion/tests/integration/kafka/test_kafka.py
- metadata-ingestion/tests/integration/mysql/test_mysql.py
- metadata-ingestion/tests/integration/openapi/test_openapi.py
- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/integration/trino/test_trino.py
- metadata-ingestion/tests/test_helpers/click_helpers.py
- metadata-ingestion/tests/test_helpers/fs_helpers.py
- metadata-ingestion/tests/unit/serde/test_serde.py
- metadata-ingestion/tests/unit/test_check.py
- metadata-ingestion/tests/unit/test_plugin_system.py
This should streamline our integration tests a bit.
It will also prevent us from forgetting to call `assert_result_ok`.
> refactor(test): replace `CliRunner` with `run_datahub_cmd` method

- build.gradle
As per http://slf4j.org/log4shell.html, there is a lesser vulnerability in logback, which DataHub libraries directly consume in favor of log4j. This PR addresses that by bumping to 1.2.9 as recommended.
> Upgrade to logback 1.2.9 to address CVE-2021-42550

- metadata-ingestion/source_docs/sql_profiles.md
- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/tests/integration/mysql/mysql_to_file.yml
- metadata-ingestion/tests/integration/trino/trino_to_file.yml
Disabling expensive profilers by default to have a better first-time experience.
> fix(profiling): Disabling expensive profilers by default

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/tests/unit/test_sql_common.py
Fix for showing None schema if foreign key pointed to a table in the same schema
> fix(ingestion): Fix for same schema foreign key reference

- metadata-ingestion/setup.py
> fix(ingest): fix compatibility with google composer

- datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
The header's height was capped at 137px. However, it may expand beyond that in the case of a very long title. This removes that limit.
> fix(react-ui): fix header min height

- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_properties.py
- metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
There is already a transform to add custom properties to a dataset by using a callback function.
This PR is adding a simple one on top of the existing one. The new one allows for adding custom properties from the configuration. The same pattern (callback + simple version) has been followed in other transforms too.
> feat(transform): adds simple add dataset properties transform

- metadata-ingestion/transformers.md
This is just adding the missing doc for the transform added here https://github.com/linkedin/datahub/pull/3778
> doc(transforms): adds doc for simple_add_dataset_properties transformer

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java
Previously, reindexing tasks would timeout after the ES rest client's 30 second limit. This PR ups the wait time to an hour.
Other attempted solutions:
- increase the timeout of the sync reindex call (this did not seem possible)
- use waitForComplete = true in the ListTaskRequest. This did not appear to abide by the timeout i set despite my efforts. It also threw exceptions after 30s, even when the timeout was set to be larger.
> fix(elastic): allow more time for re-indexing tasks

- metadata-ingestion/examples/recipes/snowflake_usage_to_datahub.yml
- metadata-ingestion/source_docs/snowflake.md
- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
This will introduce a breaking change as users will have to specify the `email_domain` config parameter.
> feat(snowflake-usage): Generate email address if not exists 

- docker/docker-compose.dev.yml
Per the [Dockerfile for elasticsearch-setup](https://github.com/linkedin/datahub/blob/master/docker/elasticsearch-setup/Dockerfile#L15) the files to use when creating indicies are now inside `restli-servlet-impl` [here](https://github.com/linkedin/datahub/tree/master/metadata-service/restli-servlet-impl/src/main/resources/index/usage-event). 
This took me way too long to figure out what was happening when I upgraded but hopefully this helps someone else! 
The error I was getting was due to the the setup job failing, and when using the analytics tab got 500s due to the following error in GMS.
Elastic Setup Container:
```
creating datahub_usage_event_policy
sed: /index/usage-event/policy.json: No such file or directory
% Total    % Received % Xferd  Average Speed   Time    Time     Time …
```
> fix(docker): Fix path to elastic definition in dev docker compose

- docs-website/sidebars.js
- docs/modeling/metadata-model.md
A link to the MXE page has been added to the navigation bar and in a suitable place within the Metadata Modeling page.
Earlier discussion on Slack: https://datahubspace.slack.com/archives/C02FWNS2F08/p1637219334130500
/cc @jjoyce0510
> docs(modeling): Add a link to MXE page inside the Metadata Modeling page

- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
Makes the url field of the DefaultConfig of business glossary optional to keep it consistent with the [documentation](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/source_docs/business_glossary.md#business-glossary-file-format) as well as the definition of [GlossaryTermInfo  aspect](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/glossary/GlossaryTermInfo.pdl#L44).
> fix(ingestion): Make url an optional field of the DefaultConfig for business glossary 

- metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
When a table is backed with Glue metastore, it can happen a column has string type and sqlalchemy does not know about it.
> fix(ingest): Handle string redshift type

- docs/how/kafka-config.md
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/schemaregistry/KafkaSchemaRegistryFactory.java
This PR adds support TLS support for Schema Registry in GMS by adding the appropriate values to `KafkaSchemaRegistryFactory`. I have tested this both with and without SSL. It also replaces the deprecated `AbstractKafkaAvroSerDeConfig` with `AbstractKafkaSchemaSerDeConfig`.
One consideration is the naming of the environment variables. For example,
`kafka.schemaRegistry.url` versus `kafka.schema.registry.ssl.truststore.location`. This means the URL environment variable is missing a space between `schema` and `registry`. I added the space to the others to match the [Kafka values](https://github.com/a0x8o/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/config/SslConfigs.java) but was hesitant to update the URL as it will likely break for many. Happy to reevaluate this either …
> feat(gms): add schema registry support for tls in gms

- docs/how/kafka-config.md
Added SASL/GSSAPI configuration for other components datahub-frontend, kafka-setup and schema-registry
> docs: improve docs for kafka configuration

- metadata-ingestion/source_docs/glue.md
- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> fix(ingest): ignore custom connectors for Glue ingestion

- metadata-integration/java/datahub-client/src/main/java/datahub/client/rest/RestEmitter.java
Null callbacks were not being checked before invocation.
> fix(java-emitter): check for null callback

- .github/workflows/build-and-test.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/test-results.yml
> feat(ci): split metadata-ingestion ci to streamline build

- metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
- metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py
Hello ! 
Today I tried using the bigquery-usage source with the following configuration : 
```yaml
source:
type: bigquery-usage
config:
projects:
- dailymotion-rawlogs
top_n_queries: 10
query_log_delay: 30
table_pattern:
deny:
- (tmp.+|temp.+)
sink:
type: "datahub-kafka"
config:
connection:
bootstrap: "localhost:9092"
schema_registry_url: "http://localhost:8081"
```
Unfortunately I had this error : 
```
File "/Users/p.genissel/venv/datahub/lib/python3.8/site-packages/datahub/ingestion/source/usage/bigquery_usage.py", line 605, in _aggregate_enriched_read_events
resource = event.resource.remove_extras()
File "/Users/p.genissel/venv/datahub/lib/python3.8/site-packages/datahub/ingestion/source/usage/bigquery_usage.py", line 136, in remove_extras
raise …
```
> fix(ingest): bigquery-usage - fix remove_extras to remove all partitions

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
When using the dbt-spark adapter, 'database' is not set, resulting in a fqn containing "None".
Apart from the cosmetic issue, this also creates a mismatch between the fqn of dbt models and the underlying glue tables (which are just schema.table).
> fix(ingestion): handle database=None for dbt ingestion

- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- datahub-web-react/src/app/lineage/LineageTree.tsx
- datahub-web-react/src/app/lineage/LineageVizInsideZoom.tsx
- datahub-web-react/src/app/lineage/constants.ts
- datahub-web-react/src/app/lineage/utils/LineageExplorerContext.tsx
- datahub-web-react/src/app/lineage/utils/layoutTree.ts
- datahub-web-react/src/app/lineage/utils/nodeHeightFromTitleLength.ts
Adds a toggle in the bottom right corner to expand/contract entity titles. Also adds a fix for the lineage sidepanel to have long titles break onto the next line
> feat(lineage): allow for expanding of lineage node titles in the lineage explorer

- .dockerignore
- .github/workflows/docker-datahub-upgrade.yml
- .github/workflows/docker-elasticsearch-setup.yml
- .github/workflows/docker-feast-source.yml
- .github/workflows/docker-frontend-react.yml
- .github/workflows/docker-gms.yml
- .github/workflows/docker-ingestion.yml
- .github/workflows/docker-kafka-setup.yml
- .github/workflows/docker-mae-consumer.yml
- .github/workflows/docker-mce-consumer.yml
- .github/workflows/docker-mysql-setup.yml
- .github/workflows/docker-postgres-setup.yml
- build.gradle
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
- datahub-graphql-core/src/main/resources/app.graphql
- datahub-web-react/src/app/shared/ManageAccount.tsx
- datahub-web-react/src/graphql/app.graphql
- docker/datahub-gms/Dockerfile
- metadata-io/src/main/java/com/linkedin/metadata/version/GitVersion.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MclConsumerConfig.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MceConsumerConfig.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/McpConsumerConfig.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/GitVersionFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
- metadata-service/servlet/build.gradle
- metadata-service/servlet/src/main/java/com/datahub/gms/servlet/Config.java
Add version to the UI and config endpoint by
1: Add git properties plugin to all java based gradle tasks that generates a git.properties file with the commit hash and other necessary information (latest tag for the given commit)
2: Add GitVersionFactory that fetches the commit hash and version from the git.properties
3: Add the version info to the config endpoint
Also modified all github actions that checkout code to build image to fetch all history (otherwise git describe does not work)
```
curl http://localhost:8080/config
{
"models" : { },
"versions" : {
"linkedin/datahub" : {
"version" : "v0.8.22",
"commit" : "22acafafa4b86c1ee9623bc6023851a50829949d"
}
},
"statefulIngestionCapable" : true,
"retention" : "true",
"noCode" : "true"
}
```
4: Add the version info in the UI
> feat(git-version): Add version to the UI and config endpoint

- metadata-ingestion/sink_docs/datahub.md
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/tests/unit/test_rest_emitter.py
> feat(metadata-ingestion): Make datahub-rest client more robust by configurable retries.  (#3826)

- metadata-ingestion/source_docs/metabase.md
- metadata-ingestion/src/datahub/ingestion/source/metabase.py
I'm trying to ingest data from a metabase setup which uses AWS Athena to read data registered in the AWS Glue metadata catalog. Currently the ingestion will create a new version of the dataset as an Athena table, instead of referring to the underlying glue dataset.
Allowing the user to configure the db engine -> platform mapping allows easily resolving issues like these, as well as supporting platforms not currently listed in the hardcoded mapping.
> feat(metabase): allow configuring how database engines get mapped to platforms

- build.gradle
- docs/how/kafka-config.md
- metadata-jobs/mae-consumer/build.gradle
- metadata-jobs/mce-consumer/build.gradle
- metadata-service/war/build.gradle
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
In order to use the MSK with IAM and with SASL Mechanism as `AWS_MSK_IAM` and security protocol as `SASL_SSL` AWS MSK IAM Jar should be added to the Project Dependencies.
Here are the env variables that's used in the GMS Project
```
SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/tmp/kafka.client.truststore.jks
SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true; …
```
> Add AWS MSK Iam Auth Jar to GMS 

- metadata-ingestion/source_docs/azure-ad.md
In retrospect it's obvious that these should be application-type permissions, but it's easily glossed over when not too familiar with the Azure AD API permissions system.
slack thread: https://datahubspace.slack.com/archives/C029A3M079U/p1636471101266200
> docs(ingestion) azure: specify required permission type

- metadata-ingestion/src/datahub/ingestion/source/dbt.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
Add spark sql types to the dbt type mappings, for use with the dbt-spark adapter.
> feat(ingestion) dbt: support spark sql types

- li-utils/src/main/java/com/datahub/util/RecordUtils.java
Issue with extracting unions once we moved to MCLs for all changes. This let's us extract fields from unions to unblock the chart issue.
> fix(field-extraction): Fix extraction for unions

- metadata-ingestion/examples/recipes/elasticsearch_to_datahub.yml
- metadata-ingestion/setup.py
- metadata-ingestion/source_docs/elastic_search.md
- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
- metadata-ingestion/tests/unit/test_elasticsearch_source.py
- metadata-models/src/main/resources/entity-registry.yml
Adds
1. Elasticsearch source and extracts the SchemaMetadata along with interesting properties such as the number of partitions for a data stream, aliases of an index etc. Supports nested schemas(mappings) and uses the v2 fieldPath encoding for the schema fields.
2. Unit tests and relevant user-facing documentation.
Addresses github issue [3517](https://github.com/linkedin/datahub/issues/3517).
> feat(Ingestion): Add Elasticsearch Source

- perf-test/locustfiles/get_entities.py
- perf-test/locustfiles/ingest_small.py
- perf-test/scripts/ingest_sample.py
- perf-test/scripts/ingest_test.sh
> perf: add/change scripts for tests

- docs-website/docusaurus.config.js
Pointing roadmap links back to HelloNext.
> docs: change roadmap link

- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/tests/unit/test_kafka_source.py
> feat(kafka): support confluent references

- metadata-service/auth-api/src/main/java/com/datahub/authentication/AuthenticationExpiredException.java
- metadata-service/auth-filter/src/main/java/com/datahub/authentication/filter/AuthenticationFilter.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/authenticator/AuthenticatorChain.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/authenticator/DataHubTokenAuthenticator.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/TokenExpiredException.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/TokenService.java
- metadata-service/auth-impl/src/test/java/com/datahub/authentication/authenticator/AuthenticatorChainTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authentication/token/TokenServiceTest.java
Previously, the error message for an expired token would be the same as an invalid token. This can cause confusion for an end user when a token that previously worked suddenly does not authenticate due to expiration. This pr propagates the expiration-specific warning back.
> feat(authentication): propagate expired token exceptions to end user

- smoke-test/tests/tags-and-terms/tags_and_terms_test.py
These dependencies were not brought over, leaving open the opportunity for the test to run before ingestion completed.
> ci(smoke-test): make tags&terms smoke test wait for ingestion to complete

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/OperationMapper.java
fix(ingest): operational stats - check if optional fields are present
> fix(ingest): operational stats - check if optional fields are present

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/browse/BrowsePathsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/DescriptionUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/MutationUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/LabelUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/LinkUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/util/OwnerUtils.java
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchHeader.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/navigateToEntitySearchUrl.ts
- datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
- datahub-web-react/src/app/entity/shared/types.ts
- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
- datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx
- datahub-web-react/src/app/search/SearchBar.tsx
- Ensure browsePaths resolver returns empty list when an Entity has no browse path (threw before). 
- Migrate persistAspect in mutationUtils to use ingestProposal instead of ingestEntity. 
- Adding common EmbeddedListSearch components to bundle entity search into a set of reusable, common components. 
- remove minHeight CSS in EntityHeader to avoid ui bug where tabs were floating above cutline. 
- Only show EntityProfile browse / lineage bar when lineage or browse is enabled for the entity
- make updateEntity an optional parameter to EntityProfile (in some cases not necessary) 
- Only show divider when there is a platform on entity profile 
- [Finally] Adding "Copy Urn" button to all entity profiles 
- Support "inputStyle" on search bar component
- Add Glossary Terms & Tags to the …
> refactor(gql/ui): Misc refactorings

- metadata-ingestion/developing.md
> docs(metadata-ingestion): fix command for running fast unit tests

- datahub-web-react/src/app/auth/login.module.css
fix(ui): update login title css to fit on one line
-
> fix(ui): update login title css to fit on one line

- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
`Issue 1`: 
Running GMS on Kubernetes cluster causes MCL Consumer thread to stop because of Snappy lib loading issue.
Here is the Error Stack:
```
[generic-mae-consumer-job-client-0-C-1] ERROR o.s.k.l.KafkaMessageListenerContainer$ListenerConsumer - Stopping container due to an Error
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-ab3ffedb-1d79-4f1f-8fe3-aa9f8c65c08f-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by …
```
> Adding Snappy Lib and JKS File

- datahub-web-react/src/app/entity/shared/EntityContext.tsx
- datahub-web-react/src/app/entity/shared/tabs/Documentation/components/DescriptionEditor.tsx
> refactor(ui): Allow DocumentationTab to optionally use updateDescription mutation

- docs/modeling/metadata-model.md
The query was not properly escaping `:` and did not wrap entity type in `List(...)`
> docs(metadata): update relationship query in docs

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/usage/snowflake_usage.py
Fix the snowflake_usage source regression introduced in acryl-datahub 0.8.23.1. Currently, if include_operational_stats is enabled, all of the SnowflakeJoinedAccessEvents get consumed by operational stats emission alone, resulting in no usage events getting aggregated. This fix reorders the computation to produced both the usage aggregation and operational status workunits together during a single pass over the original SnowflakeJoinedAccessEvents.
> fix(ingestion): Snowflake Usage should continue to emit usage workunits with include_operational_stats enabled.

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/ChartType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/DashboardType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataflow/DataFlowType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datajob/DataJobType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/DatasetType.java
- metadata-ingestion/examples/recipes/file_to_datahub_rest.yml
- smoke-test/sample_bq_data.json
- smoke-test/test_e2e.py
In a recent change, we migrated from using the legacy snapshot-based batchGet method to a new batchGetV2. In the process, we introduced a bug that causes the ordering of results from batchGet to be non-deterministically changed. 
These changes have not yet been released. This PR fixes the issue.
> fix(graphQL): Fixing set ordering in batchGet of entities

- metadata-service/factories/src/main/resources/application.yml
Changing default bulk index request size to speed up indexing catch-up scenarios.
> feat(elastic-search): changing default bulk index request batch to 1000

- metadata-ingestion/source_docs/azure-ad.md
- metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
- metadata-ingestion/tests/integration/azure_ad/azure_ad_mces_golden_default_config.json
Currently, when using Azure OIDC authentication together with the Azure AD ingestion source, the generated usernames won't match between logins and ingested users since both use a different attribute and regex to extract usernames (slack thread: https://datahubspace.slack.com/archives/CV2UVAPPG/p1642591442014900). I feel this is unexpected behavior.
I changed the ingestion source instead of the OIDC plugin because it seems more natural to me to use the azure principal name as the username in datahub, since it is guaranteed to uniquely identify a user. A change in the opposite direction would be fine as well, I think the important part is that they are consistent with each other.
> fix(ingestion): match default username for Azure OIDC and Azure ingestion source

- metadata-ingestion/src/datahub/ingestion/graph/client.py
The `Aspect` typevar was copied, so this replaces it with an import.
> refactor(ingestion): remove duplicate aspect type

- .github/workflows/metadata-ingestion-slow.yml
- .github/workflows/metadata-ingestion.yml
- metadata-ingestion/setup.py
Restrict python to <=3.9.9 due to https://github.com/looker-open-source/sdk-codegen/issues/944 causes build failure
> fix(ingestion): Restrict python to <=3.9.9

- metadata-ingestion/src/datahub/emitter/serialization_helper.py
Uses `startswith` instead of `find` and limits the replace to one modification.
> fix(ingestion): tighten conditions for restli json transformation

- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/configuration/__init__.py
- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/entrypoints.py
> fix(ingestion): don't dump variables for config errors

- datahub-web-react/src/graphql/fragments.graphql
> fix(graphql): support group display name in ownership

- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/types.ts
- datahub-web-react/src/app/entity/shared/utils.ts
- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
- datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx
Embedded search result was hardcoded to support only one search endpoint. This adds a parameter where a custom search hook can be passed in.
Also updates list rendering to be able to render paths.
> feat(embedded search results): support custom endpoints in embedded search result

- .github/workflows/docker-gms.yml
- docker/datahub-gms/Dockerfile
> fix(docker): datahub-gms - build in native, copy to target

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeaturePropertiesMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLFeatureSnapshotMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLPrimaryKeyPropertiesMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/mlmodel/mappers/MLPrimaryKeySnapshotMapper.java
Closes https://github.com/linkedin/datahub/issues/3925
> fix(ingest): check if feature data type is present

- metadata-ingestion/scripts/datahub_preflight.sh
> fix(setup): fix setup for M1

- docs/modeling/metadata-model.md
- metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
- smoke-test/tests/domains/domains_test.py
> Refining Metadata Model docs further

- docker/kafka-setup/Dockerfile
- docker/kafka-setup/kafka-setup.sh
> fix(docker): Alpine based multiplatform docker build for kafka-setup

- metadata-ingestion/src/datahub/ingestion/source/state/checkpoint.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
> fix(ingest): lint fix a few files

- metadata-integration/java/spark-lineage/src/test/java/datahub/spark/TestSparkJobsLineage.java
> fix(spark-lineage): select mock server port dynamically for unit test

- metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
- metadata-ingestion/tests/unit/test_snowflake_source.py
> fix(ingest): snowflake - Run authentication validation if default value used

- docker/docker-compose.yml
- docker/quickstart/docker-compose.quickstart.yml
> fix: docker-compose now persists kafka broker data

- metadata-ingestion/src/datahub/ingestion/source/kafka.py
- metadata-ingestion/tests/unit/test_kafka_source.py
Adds support for Kafka confluent external schema resolution by name or subject.
> feat(ingestion): Support Kafka confluent external schema resolution by name or subject

- metadata-ingestion/src/datahub/telemetry/telemetry.py
> feat(ingest): log CLI invocations and completions

- metadata-ingestion/src/datahub/cli/ingest_cli.py
This pull request adds the `--force` option to `ingest rollback` subcommand allowing users to run it in environments like JupyterLab cell.
> feat(cli): add --force option to ingest rollback subcommand

- metadata-ingestion/source_docs/glue.md
- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
Adds a level for glue source to disable ownership ingestion, similar to Looker.
> feat(glue): make ownership configurable in glue source

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
Python HTTP adapter by default does not retry on POST. Change this behavior since we know all ingest and ingestProposal requests are idempotent. 
Also change default number of retries to 3.
> fix(retry): Retry on POST for rest emitter

- datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
Schema tab is not always present. Having it be the default tab creates a strange scenario where landing on a glossary term page does not provide a consistent experience. Updating that. cc @saxo-lalrishav
> fix(glossary): make schema tab no longer default for glossary term

- metadata-ingestion/src/datahub/emitter/serialization_helper.py
In this PR: https://github.com/linkedin/datahub/pull/3973, we changed how Rest.li records are serialized. The new conditional is not returning true as expected, causing server-side validation to fail. This PR addresses.
We will be releasing a new version of DataHub Cli to address this problem.
> hot fix: Fix serialization helper conditional (0.8.25 ingestion) 

- datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
- metadata-ingestion/examples/recipes/file_to_datahub_rest.yml
Domains icon appears twice in the top-left of the Domain profile. Addressing!
> fix(ui): Fixing domains double icon on profile

- metadata-ingestion/src/datahub/ingestion/api/committable.py
- metadata-ingestion/tests/unit/test_pipeline.py
fixes a bug in the CommitPolicy enum that was causing an incorrect behaviour during the pipeline `process_commits` stage.
```
class CommitPolicy(Enum):
ALWAYS = auto
ON_NO_ERRORS = auto
ON_NO_ERRORS_AND_NO_WARNINGS = auto
```
meant that ```ALWAYS == ON_NO_ERRORS == ON_NO_ERRORS_AND_NO_WARNINGS``` that would cause an incorrect
behaviour when calling the `process_commits()` method in the pipeline
> fix(ingestion): enforce correct behaviour for commit policy

- metadata-ingestion/setup.py
Adds psutil dependency required for stateful ingestion reporting.
> fix(ingestion): Add psutil dependency required for stateful ingestion reporting.

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpuser/CorpUserType.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpuser/mappers/CorpUserEditableInfoMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpuser/mappers/CorpUserPropertiesMapper.java
- datahub-graphql-core/src/main/resources/entity.graphql
- metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserEditableInfo.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
...For display name and title authored natively on datahub.
> feat(ui): Add display name & title to editable corp user properties.

- datahub-web-react/src/app/shared/tags/AddTagTermModal.tsx
- datahub-web-react/src/graphql/search.graphql
- smoke-test/tests/cypress/cypress/integration/mutations/mutations.js
Introduced in: https://github.com/linkedin/datahub/pull/4072
Fortunately, this was caught by our newly introduced smoke test for terms.
Also adds some waiting to add tag smoke test to prevent flaking
> fix(glossary terms): fix add glossary term flow

- metadata-ingestion/setup.py
> fix(ingestion): Add sql lineage to redshift-usage plugin

- datahub-web-react/src/images/datahub-logo-color-loading_pendulum.svg
- datahub-web-react/src/images/datahub-logo-color-loading_satellite.svg
I created new loading logo that moves like satellites.
> feat(ui): Add svg datahub satellite loading logo

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> fix(ingest) Athena: db filter was not applied

- docs/modeling/metadata-model.md
Update the doc to use the same environment variable as the script
to configure which Datahub server to upload the model doc to.
> fix(docs) Fix doc on modelDocUpload

- datahub-web-react/craco.config.js
- datahub-web-react/package.json
- datahub-web-react/yarn.lock
- metadata-ingestion/examples/mce_files/data_platforms.json
- metadata-service/war/src/main/resources/boot/data_platforms.json
Adds capability for users to host their platform images (from `src/images`) on their react app instead.
Context: https://datahubspace.slack.com/archives/CV2UXSE9L/p1644477881072309
- Installs [CopyWebpackPlugin](https://webpack.js.org/plugins/copy-webpack-plugin/) to copy `src/images` to `platforms`
- [Updated] `data_platforms.json` files are updated to use the new relative url
```jsonc
// data_platforms.json
{
"urn": "urn:li:dataPlatform:hive",
"aspect": {
"datasetNameDelimiter": ".",
"name": "hive",
"displayName": "Hive",
"type": "FILE_SYSTEM",
- "logoUrl": "https://raw.githubusercontent.com/linkedin/datahub/master/datahub-web-react/src/images/hivelogo.png"
+ "logoUrl": "/assets/platforms/hivelogo.png"
}
},
```
> feat(ui): Host platform images on datahub-web-react

- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestRootUserStep.java
> bug(seedData): adds a key to the root user seed data and fixes corner case check for missing key aspects

- datahub-web-react/package.json
- datahub-web-react/src/app/domain/CreateDomainModal.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/AddOwnerModal.tsx
- datahub-web-react/src/app/identity/group/CreateGroupModal.tsx
- datahub-web-react/src/app/ingest/secret/SecretBuilderModal.tsx
- datahub-web-react/src/app/policy/PolicyBuilderModal.tsx
- datahub-web-react/src/app/shared/tags/AddTagTermModal.tsx
- datahub-web-react/src/app/shared/tags/CreateTagModal.tsx
- datahub-web-react/src/app/shared/useEnterKeyListener.tsx
- datahub-web-react/yarn.lock
- smoke-test/tests/cypress/cypress/integration/mutations/mutations.js
Completed: UI Fix and New Project
- Fixed alignment  previous and next button on policy builder modal
- Completed new project: Expand and collapse right section (tags, terms, domain)
- Close Modals (Add owner, tag, glossary term, domain) when user press Enter
- Auto Focus: When you click 'Add Owner' and 'Set Domain', the text box should be focused
https://user-images.githubusercontent.com/86347578/154199529-f2b98352-4e27-483e-a42b-a7ab24fe63ee.mp4
> UI Fix: Modal close on Enter press, autofocus on modal, added split panel, alignment of button

- docs/api/graphql/querying-entities.md
There is a small error in the GraphQL code block. There are additional double quotes ("") in the type field in the "Searching for a Metadata Entitiy" section. This is wrong.
> Update querying-entities.md -> Documentation Error

- metadata-io/src/test/java/com/linkedin/metadata/ElasticTestUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/ElasticSearchGraphServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/SearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataServiceTest.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectServiceTest.java
refactor(metadata-io/test): create common ElasticsearchContainer helper and ability to override from environment.
Add ElasticTestUtils to provide a common place to construct ElasticsearchContainer and create REST clients. This is to remove code duplication in tests, to ensure tests are against a consistent image of Elasticsearch. Also included is the ability to use an environment variable to override the container full name, this is to allow builds behind a firewall to specify internal source for the image.
> refactor(metadata-io/test): common ElasticsearchContainer and ability to override from environment.

- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> fix(ingest) Glue: Removing sqlalchemy dependency from glue

- metadata-service/auth-impl/src/main/java/com/datahub/authentication/authenticator/AuthenticatorChain.java
> bugfix(logging): reduce log noise from authentication chain

- metadata-ingestion/setup.py
Markupsafe update caused jinja and some other lib to faile:
https://github.com/aws/aws-sam-cli/issues/3661
> fix(python build): Pinning markupsafe

- datahub-web-react/src/app/home/HomePageHeader.tsx
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
When we use reserved characters to query elastic, the DataHub API will throw 500s. We want to catch and suppress such exceptions, abstracting them away from our callers.
Screenshot below showing exception has been handled on server:
> fix(ui): Return empty search response on invalid characters in search

- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
- metadata-ingestion/tests/unit/test_elasticsearch_source.py
allow users to specify url scheme. enable ingestion from both TLS enabled clusters.
currently specifying the url scheme resulted in assertion error.
> fix(Ingestion): Elastic http/https host support

- metadata-ingestion/setup.py
The Elasticsearch client library is not pinned to a particular version of the client. It downloads the latest version of Elasticsearch which is > 8.0.0. In version 8.0.0 Elasticsearch python client introduced a check that checks if the response from Elasticsearch server has a header `'X-Elastic-Product: Elasticsearch'` If not it throws 
```UnsupportedProductError(
message=(
"The client noticed that the server is not Elasticsearch "
"and we do not support this unknown product"
)   
```
This breaks ingestion from OpenSearch as well as for those cases where we forked from open source Elasticsearch some time back.
> Pinning down elasticsearch to less than 8.0.0

- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java
deleteAspect can return a null value, but the caller was not handling is appropriately. In addition a brittle legacy check is being removed that checks that the key aspect was written prior to the value aspect. Finally, an unnecessary call to deleteAspect was removed.
> fix(delete): Fixing NPE on delete urns path

- metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> feat(ingest) Bigquery: Ignore temporary tables from lineage and connect edges directly

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
> feat(ingest): Not failing on table/view ingestion error

- metadata-events/mxe-schemas/rename-namespace.sh
ci: update rename-namespace.sh to specify /bin/bash 
On some variants of linux /bin/sh isn't necessarily bash, this is to allow builds to succeed on these platforms.
> ci: update rename-namespace.sh to specify /bin/bash 

- metadata-ingestion/source_docs/stateful_ingestion.md
Also removed some trailing whitespaces 😅
> fix(docs): fix config typo for stateful ingestion

- datahub-web-react/src/app/entity/group/GroupOwnerships.tsx
- datahub-web-react/src/app/entity/group/GroupProfile.tsx
- datahub-web-react/src/app/shared/entitySearch/RelatedEntityResults.tsx
There was no pagination support on the ownerships of the groups. For each type of entity, if the group owns more than 10 entities, the rest of these become unreachable through UI. 
In this pr, I have tried to implement pagination per entity type to allow discovering all of the entities owned by the group.
_(I have changed the page size for ownership to 10, while it's 20 in the recording)_
> Add pagination to group ownerships

- metadata-ingestion/src/datahub/utilities/urns/data_platform_urn.py
- metadata-ingestion/src/datahub/utilities/urns/dataset_urn.py
- metadata-ingestion/src/datahub/utilities/urns/error.py
- metadata-ingestion/src/datahub/utilities/urns/urn.py
- metadata-ingestion/tests/unit/test_dataset_urn.py
- metadata-ingestion/tests/unit/test_urn.py
In the data model we define Urn as String which make it hard to manipulate. This PR creates python lib for Urn, DatasetUrn, DataPlatformUrn classes which is meant to help interact with Urn easier.
> feat(ingest): add Python libs for Urns

- datahub-web-react/src/app/shared/LogoCountCard.tsx
Platform or Domain names with long names will cause the text to appear unreadable on the homepage. This PR aims to address that! See screenshots below.
> fix(ui): Wrap homepage cards on long text

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/serde/test_serde.py
Follows https://github.com/acryldata/avro_gen/pull/5.
> fix(ingestion): enable compat with avro 1.11
