datahub-project/datahub

- metadata-ingestion/setup.cfg
- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
> feat(ingest): enable joins across FileBackedDicts + add FileBackedList

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py
> fix(ingest): delta-lake - support assume aws role

- metadata-ingestion/developing.md
> docs(ingest): add guidelines around proactive version pinning

- docs/api/restli/restore-indices.md
> Add documentation example for using restoreIndices with an urnLike argument

- metadata-ingestion/setup.py
This version has improvements in logging and exception handling during classification.
> fix(ingest/snowflake): bump up classification library version to 0.0.6

- docs/api/restli/restore-indices.md
> Update restore indices docs to include batch information

- docker/quickstart/quickstart_version_mapping.yaml
- metadata-ingestion/src/datahub/cli/docker_cli.py
- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
> feat(cli): switch default quickstart to v0.10.0

- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
- metadata-io/src/test/java/com/linkedin/metadata/search/LineageSearchServiceTest.java
> fix(lineage): nullpointer exceptions

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_3.md
> docs(managed ingestion): add release notes for v0.2.3

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_usage_v2.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_utils.py
> feat(ingest/snowflake): use auto_workunit_reporter helper

- metadata-ingestion/build.gradle
- metadata-service/servlet/src/main/java/com/datahub/gms/servlet/Config.java
> fix(gms): convert obj to string, fix wrong setup

- datahub-web-react/src/app/domain/CreateDomainModal.tsx
> Extend character limit for Create Domain Modal

- smoke-test/run-quickstart.sh
> fix(smoke-test): always use built images in smoke tests

- metadata-ingestion/setup.py
> fix(ingest): pin `typeguard` version for feast

- docker/docker-compose.yml
> fix(docker): fix elasticsearch image tag

- docs-website/sidebars.js
- docs/cli.md
- docs/debugging.md
- docs/faq-using-datahub.md
> docs: misc fixes

- docs/tools/tutorials/creating-tags.md
- docs/tools/tutorials/creating-terms.md
- metadata-ingestion/examples/library/create_tag.py
- metadata-ingestion/examples/library/create_term.py
> docs: add new code examples on creating entities & fix minor typos

- docs/quickstart.md
> docs: add CLI installiation guide via poetry

- docs/api/datahub-apis.md
- docs/api/tutorials/creating-terms.md
> docs: fix typo and image

- .github/workflows/docker-ingestion.yml
> fix(docker): fix image name for datahub-ingestion-slim

- metadata-ingestion/src/datahub/cli/delete_cli.py
> fix(cli/delete): include aspect name in dry-run message

- datahub-web-react/src/app/entity/shared/tabs/Lineage/ImpactAnalysis.tsx
- datahub-web-react/src/app/entity/shared/tabs/Lineage/LineageTabTimeSelector.tsx
- datahub-web-react/src/app/lineage/LineageTimeSelector.tsx
- datahub-web-react/src/app/lineage/controls/LineageVizTimeSelector.tsx
- datahub-web-react/src/app/lineage/utils/lineageUtils.ts
- datahub-web-react/src/app/lineage/utils/navigateToLineageUrl.ts
- datahub-web-react/src/app/lineage/utils/useGetLineageTimeParams.ts
> fix(lineage): change default lineage time window to All Time

- metadata-ingestion/src/datahub/api/entities/corpgroup/corpgroup.py
- metadata-ingestion/src/datahub/api/entities/corpuser/corpuser.py
> fix(cli): allow usage without kafka

- .github/workflows/metadata-ingestion.yml
- .gitignore
- metadata-ingestion/build.gradle
> chore(ci): add coverage code for python

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_4.md
> doc(release): managed datahub v0.2.4 release notes

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> fix(ingest/looker): skip empty user ids for usage

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/tests/integration/looker/test_looker.py
Also updating the capability report here https://github.com/datahub-project/datahub/pull/7683.
> feat(ingest/looker): enable looker usage ingestion by default

- docs/faq-using-datahub.md
> doc(freshness): add faq for dataset freshness

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
> chore(lint): fix lint in looker

- docker/quickstart/quickstart_version_mapping.yaml
Basically reverts the relevant changes from https://github.com/datahub-project/datahub/pull/7567
> feat(quickstart): move quickstart back to master

- metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
> docs(okta): add how to use email in urns

- metadata-ingestion/src/datahub/configuration/pydantic_field_deprecation.py
- metadata-ingestion/src/datahub/configuration/source_common.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
- metadata-ingestion/tests/unit/test_pydantic_validators.py
- metadata-ingestion/tests/unit/test_snowflake_source.py
> feat(ingest/snowflake): hide `host_port` from snowflake docs

- docs/lineage/airflow.md
> docs(airflow): update with information for new plugin

- metadata-ingestion/src/datahub/ingestion/source/demo_data.py
Fixes a regression from https://github.com/datahub-project/datahub/pull/7718.
> fix(ingest/demo-data): fix bug in path type

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
> fix(ingest/dbt-cloud): use correct dbt cloud IDE urls

- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
> docs(ingest/lookml): update error message for Looker connection fetch

- docker/README.md
> docs(docker): fix typo in README.md

- docs/cli.md
> doc(cli): fix get cli example

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
> fix(ingest/snowflake): fix tags without lineage query, remove comma

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_5.md
> docs(managed datahub): release notes for v0.2.5

- datahub-frontend/play.gradle
> build: Use external dependency to set jsonSmart version in frontend build file

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
> config(ingest/bigquery): Default lineage_use_sql_parser to true; update description

- entity-registry/src/main/java/com/linkedin/metadata/models/extractor/FieldExtractor.java
- metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java
- metadata-io/src/test/java/com/linkedin/metadata/TestEntityUtil.java
- metadata-io/src/test/java/com/linkedin/metadata/extractor/FieldExtractorTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformerTest.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/SearchDocumentTransformerFactory.java
- metadata-service/factories/src/main/resources/application.yml
> feat(search): allow longer customProperties

- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/unity/test_unity_catalog_ingest.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
For the reviewer - the first commit is just canonicalizing the golden file with no changes, so review the commit(s) after that one.
> feat(ingest/unity): support extracting ownership

- .github/workflows/spark-smoke-test.yml
- build.gradle
- datahub-upgrade/build.gradle
- metadata-integration/java/datahub-client/build.gradle
- metadata-integration/java/datahub-protobuf/build.gradle
- metadata-integration/java/spark-lineage/build.gradle
- metadata-jobs/mae-consumer-job/build.gradle
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/ingestion/IngestionSchedulerHookTest.java
- metadata-jobs/mce-consumer-job/build.gradle
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/IngestDataPlatformInstancesStepTest.java
- metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/IngestDefaultGlobalSettingsStepTest.java
Requires updates to Spring boot 2.7.10, Jackson 2.15 (unreleased, currently an RC to be updated to final release at later date), Spring Kafka 2.8
> chore(snakeyaml): upgrade to snakeyaml 2

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
Should add a connector test to this... eventually
> fix(ingest/bigquery): Add to lineage, not overwrite, when using sql parser

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
> fix(ingest/bigquery): Enable lineage and usage ingestion without tables

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
> fix(ingest/bigquery): Do not query columns when not ingesting tables or views

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
> fix(ingest/bigquery): update usage query, remove erroneous init

- metadata-ingestion/scripts/datahub_docker.sh
> fix(cli): use correct ingestion image in script

- .github/workflows/build-and-test.yml
- .github/workflows/check-datahub-jars.yml
- .github/workflows/docker-ingestion-base.yml
- .github/workflows/docker-ingestion-smoke.yml
- .github/workflows/docker-ingestion.yml
- .github/workflows/docker-postgres-setup.yml
- .github/workflows/docker-unified.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-model.yml
- .github/workflows/spark-smoke-test.yml
> fix(release): prevent republish of images on release edits

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/tests/unit/test_codegen.py
- metadata-models/src/main/resources/entity-registry.yml
Also adds a test that makes sure we remain at parity with snapshots.
> feat(): finish populating the entity registry

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/constants.ts
- datahub-web-react/src/app/ingest/source/builder/RecipeForm/powerbi.ts
- datahub-web-react/src/app/ingest/source/builder/sources.json
In this PR, we introduce a UI form for configuring PowerBI ingestion recipe. 
> feat(ui): Support PowerBI Ingestion via UI form

- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
> feat(ingest/unity): capture create/lastModified timestamps

- metadata-models/src/main/pegasus/com/linkedin/datajob/DataJobInputOutput.pdl
> Update DataJobInputOutput.pdl to express that CLL fields are not shown in the UI right now

- metadata-ingestion/setup.py
> fix(ingest): pin sqlparse version

- metadata-ingestion/developing.md
- metadata-ingestion/examples/library/dataset_add_column_documentation.py
> chore(ci): fix CI failing due to lint

- metadata-ingestion/src/datahub/cli/cli_utils.py
- metadata-ingestion/src/datahub/cli/state_cli.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
Adds:
- get_urns_by_platform, using scroll by entities
- get_latest_pipeline_checkpoint
- soft_delete_urn
> refactor(ingest): Add helper DataHubGraph methods

- metadata-ingestion/examples/library/upsert_group.py
> docs(ingest): fix CorpGroup example

- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/unity/test_unity_catalog_ingest.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
> feat(ingest/unity): Ingest ownership for containers; lookup service principal display names

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Fixes https://github.com/datahub-project/datahub/issues/7868.
> fix(ingest/dbt): ensure dbt shows view properties

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/src/datahub/ingestion/graph/client.py
> feat(sdk): add `DataHubGraph.get_entity_semityped` method

- metadata-ingestion/tests/integration/business-glossary/glossary_events_auto_id_golden.json
- metadata-ingestion/tests/integration/business-glossary/test_business_glossary.py
> test(ingest/biz-glossary): add test for enable_auto_id

- metadata-ingestion/src/datahub/configuration/config_loader.py
- metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
- metadata-ingestion/src/datahub/ingestion/source/file.py
referencing issue https://github.com/datahub-project/datahub/issues/7865   
This bug affects people ingesting sample data on Windows environment. (Sorry, I contributed to the bug previously)
> [bugfix] Fix remote file ingestion for Windows

- metadata-service/war/src/main/resources/boot/data_platforms.json
> fix(platforms): fix json parse exception for data platforms

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_6.md
> docs(release): managed DataHub 0.2.6

- docs-website/sidebars.js
- docs/deploy/environment-vars.md
> docs(deploy): document some of the environment variables

- metadata-service/auth-filter/src/main/java/com/datahub/auth/authentication/filter/AuthenticationFilter.java
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/authenticator/AuthenticatorChain.java
- metadata-service/auth-impl/src/test/java/com/datahub/authentication/authenticator/AuthenticatorChainTest.java
- metadata-service/factories/src/main/resources/application.yml
> logging(auth): adding optional logging to authentication exceptions

- metadata-ingestion/setup.py
Hopefully the last one... Is there a good way to check dependencies are complete?
> fix(ingest/unity): Add sqllineage dependency

- metadata-ingestion/src/datahub/ingestion/api/common.py
> fix(ingest): improve error message when graph connection fails

- metadata-ingestion/docs/sources/mariadb/mariadb_recipe.yml
- metadata-ingestion/docs/sources/postgres/postgres_recipe.yml
> docs(ingest/postgres): add example with ssl configuration

- docs/quick-ingestion-guides/powerbi/setup.md
The endpoints should’ve referenced here:  https://github.com/datahub-project/static-assets/tree/main/imgs/guides/powerbi but seems like some of the endpoints didn't specify the username in the right way 
Demo : https://docs-website-7pzlug1ti-acryldata.vercel.app/docs/quick-ingestion-guides/powerbi/setup
> fix: Fix broken links on PowerBI

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> fix(ingest/bigquery): Filter projects for lineage and usage

- docs-website/vercel-setup.sh
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion/scripts/install_deps.sh
- vercel.json
> fix: build vercel python from source

- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
Another issue caused by automerge, follow up on
https://github.com/datahub-project/datahub/pull/7963.
> fix(ingest/salesforce): fix lint

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
Fixes https://github.com/datahub-project/datahub/issues/7923
> fix(ingest): use certs correctly in rest emitter

- docs/developers.md
> docs(development): update per feedback from community

- metadata-io/src/main/java/com/linkedin/metadata/search/cache/CacheableSearcher.java
- metadata-io/src/test/java/com/linkedin/metadata/search/cache/CacheableSearcherTest.java
> fix(cache): update search cache when skipped, but enabled

- metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/DailyReport.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/telemetry/ScheduledAnalyticsFactory.java
> feat(telemetry): add server version

- metadata-service/auth-impl/src/main/java/com/datahub/authentication/user/NativeUserService.java
> fix(auth): guards against creating a user for the system actor

- build.gradle
> chore(security): update org json json dependency - cve-2022-45688

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_7.md
> docs(managed datahub): release notes for v0.2.7

- datahub-web-react/src/app/entity/shared/components/styled/search/DownloadAsCsvModal.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchHeader.tsx
- datahub-web-react/src/app/entity/shared/components/styled/search/SearchExtendedMenu.tsx
- datahub-web-react/src/app/search/SearchResults.tsx
https://github.com/datahub-project/datahub/assets/19418814/bd694848-2919-4f9f-a6b8-55c03ea791c1
> fix(ui): add loading indicator for download as CSV action

- docs/how/search.md
> feat(docs): Add example documentation for scrollAcrossEntities

- metadata-ingestion/setup.py
See https://github.com/databricks/databricks-cli/issues/639
> fix(ingest/unity): Update databricks-cli pin

- metadata-ingestion/setup.py
> fix(ingest/s3) Adding missing more-itertools dependency

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub_provider/hooks/datahub.py
Also makes Airflow config issues more clear.
> fix(sdk): throw errors on empty gms server urls

- .gitignore
- docker/datahub-frontend/Dockerfile
- docker/datahub-gms/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
https://security.snyk.io/vuln/SNYK-ALPINE39-SQLITE-449762
> fix(PFP-260): Upgrading sqlite to fix SQLITE-449762

- metadata-ingestion/src/datahub/ingestion/api/registry.py
> feat(ingest): support importing local modules

- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
fix NPE in the event generator
set fulltext for searchAcrossLineage in java client by explicit default (if not specified)
> fix(timeline-events): fix NPE in timeline events

- datahub-web-react/src/app/home/HomePagePosts.tsx
- datahub-web-react/src/app/search/PostTextCard.tsx
> fix(posts): fix formatting for posts where the title can get cut off

- datahub-web-react/src/app/search/SearchBar.tsx
> fix(search): only show explore all btn on search and home

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/siblings/SiblingAssociationHook.java
This ensures that siblings works properly.
> fix(ingest/dbt): fix dbt subtypes for sources

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/api/workunit.py
- metadata-ingestion/src/datahub/ingestion/extractor/mce_extractor.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_lite.py
- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
- metadata-ingestion/src/datahub/ingestion/sink/file.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
- metadata-ingestion/src/datahub/ingestion/source/demo_data.py
- metadata-ingestion/src/datahub/ingestion/source/file.py
- metadata-ingestion/src/datahub/ingestion/source/gcs/gcs_source.py
- metadata-ingestion/src/datahub/ingestion/source/metadata/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
- metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py
- metadata-ingestion/tests/test_helpers/mce_helpers.py
- metadata-ingestion/tests/unit/serde/test_serde_usage.json
- metadata-ingestion/tests/unit/test_pipeline.py
- metadata-ingestion/tests/unit/test_source.py
- metadata-ingestion/tests/unit/test_usage_common.py
- metadata-models/src/main/pegasus/com/linkedin/usage/UsageAggregation.pdl
- metadata-service/restli-api/src/main/idl/com.linkedin.usage.usageStats.restspec.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.usage.usageStats.snapshot.json
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/usage/UsageStats.java
To do this, file source attempts to create DatasetUsageStatistics from UsageAggregationClass
> refactor(ingest): Make get_workunits() return MetadataWorkUnits

- metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py
- metadata-ingestion/src/datahub/ingestion/glossary/datahub_classifier.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
> refractor(classification): simplify classification handler

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
Hi! I've created an issue related to this PR: #7768
> fix(ingest/snowflake): lowercase user urn when using email

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
> fix(ingest/looker): don't prematurely show connectivity success

- metadata-ingestion/tests/unit/test_codegen.py
> test(sdk): better error messages in registry codegen test

- metadata-io/build.gradle
- metadata-service/factories/build.gradle
> chore(vulnerability): add exclusions for json to prevent leaking dependency

- metadata-utils/src/main/java/com/linkedin/metadata/utils/elasticsearch/IndexConvention.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/elasticsearch/IndexConventionImpl.java
- metadata-utils/src/test/java/com/linkedin/metadata/utils/elasticsearch/IndexConventionImplTest.java
> fix(checkstyle): Fix checkstyle violations to turn master green

- metadata-service/restli-api/src/main/idl/com.linkedin.usage.usageStats.restspec.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
- metadata-service/restli-api/src/main/snapshot/com.linkedin.usage.usageStats.snapshot.json
> fix(ci): add missing updates to restli-spec

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift_schema.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/report.py
> fix(ingest/redshift): Making Redshift source more verbose

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAOTest.java
> fix(search): Update _entityType transform logic to work for entities containing _

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
> fix(search): Transform _entityType/index output for scroll across entities as well

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
> fix(ingest/redshift): Fixing Redshift subtypes

- smoke-test/tests/test_stateful_ingestion.py
> fix(ingest): Fix breaking smoke test on stateful ingestion

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/usage.py
> fix(ingest/bigquery): Deduplicate LogEntries based on insertId, timestamp, logName

- metadata-ingestion/docs/sources/glue/glue.md
- metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> feat(ingest/glue): report glue job lineage failures, update doc

- metadata-ingestion/docs/sources/glue/glue.md
> docs(glue): fix broken link

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/ScrollAcrossEntitiesResolver.java
- metadata-io/src/main/java/com/linkedin/metadata/search/client/CachingEntitySearchService.java
- metadata-service/factories/src/test/java/com/linkedin/gms/factory/search/CacheTest.java
> fix(scroll): fix scroll cache key for hazelcast

- docs/ownership/ownership-types.md
> fix(docs): Fix ownership type typos

- docs/townhall-history.md
> docs(townhall) feb and march town hall agenda and recording

- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
> feat(ingest/unity): Add qualified name to dataset properties

- metadata-ingestion/src/datahub/ingestion/source/kafka.py
> fix(ingest/kafka): Fixing error printing in Kafka properties get call

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
> fix(ingest/snowflake): set use_quoted_name to profile lowercase tables

- metadata-service/restli-client/build.gradle
- metadata-service/restli-client/src/main/java/com/linkedin/common/client/BaseClient.java
- metadata-service/restli-client/src/test/java/com/linkedin/common/client/BaseClientTest.java
> fix(restli): update base client retry logic

- metadata-ingestion/setup.py
> build(ingest/feast): Pin feast to minor version

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_8.md
> docs(managed datahub): release notes for v0.2.8

- docs/modeling/metadata-model.md
The code doesn't run as is, need this import as well. Also, change the initialized emitter to the rest emitter to localhost, for continuity with the above curl command, and an example that can run out of the box.
> docs(ingest) Add MetadataChangeProposalWrapper import to example code

- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
> fix(ingest/redshift): Adding env parameter where it was missing for urn generation

- docs/managed-datahub/release-notes/v_0_2_8.md
> docs(managed datahub): add docs link to v0.2.8

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.tools.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- metadata-integration/java/datahub-client/src/test/java/datahub/client/kafka/containers/Utils.java
> chore(cp-schema-registry): bump minor version

- metadata-ingestion/src/datahub/ingestion/glossary/datahub_classifier.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake_legacy_lineage.py
Follow up on [this](https://github.com/datahub-project/datahub/pull/8186#discussion_r1222437244).
> refractor(classification): datahub classifier init

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
> fix(ingest/delta-lake): fix CI issues due to delta lake version bump

- datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
- gradle/versioning/versioning.gradle
> chore(release): update default cli for managed ingestion

- metadata-ingestion/src/datahub/cli/docker_check.py
- metadata-ingestion/src/datahub/telemetry/telemetry.py
Also capture command durations as part of telemetry.
> fix(cli): make quickstart robust to docker race conditions

- metadata-ingestion/src/datahub/emitter/mcp.py
- metadata-ingestion/tests/unit/patch/complex_dataset_patch.json
- metadata-ingestion/tests/unit/patch/test_patch_builder.py
- metadata-ingestion/tests/unit/serde/test_serde.py
- metadata-ingestion/tests/unit/serde/test_serde_patch.json
> feat(sdk): support patches as MCPs in file source

- docs/authorization/access-policies-guide.md
- docs/authorization/policies.md
- metadata-auth/auth-api/src/main/java/com/datahub/authorization/ResolvedResourceSpec.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/PolicyEngine.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/AspectResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/entity/EntityResource.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/usage/UsageStats.java
Added docs on which policies apply for non-API only policies and port over fix for specifying resources where able.
> fix(apiAuth): add resources where applicable and update docs

- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/sql/presto_on_hive.py
- metadata-ingestion/src/datahub/ingestion/source/unity/config.py
- metadata-ingestion/src/datahub/ingestion/source/unity/connection_test.py
- metadata-ingestion/src/datahub/ingestion/source/unity/profiler.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/proxy_types.py
- metadata-ingestion/src/datahub/ingestion/source/unity/report.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/src/datahub/ingestion/source/unity/usage.py
- metadata-ingestion/tests/integration/unity/test_unity_catalog_ingest.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
- metadata-ingestion/tests/unit/test_unity_catalog_config.py
Review https://github.com/datahub-project/datahub/pull/8237 first. Have to rebase once the other one is merged. Just review the last commit.
> feat(ingest/unity): Set external url for containers and datasets

- docker/kafka-setup/Dockerfile
> fix(kafka-setup): bump kafka version

- metadata-service/factories/src/main/resources/search_config.yml
> fix(custom-search): revert underscore as quoted

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/FormField.tsx
- datahub-web-react/src/conf/theme/global-overrides.less
> chore(checkbox): darken all checkboxes

- metadata-ingestion/src/datahub/cli/delete_cli.py
> feat(ingest/delete-cli): Add configurable batch size; update docs

- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
> fix(metadata-io): retry transactions on serialization errors when using a PostgreSQL database

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
> tests(urn): Add tests for more cases of invalid urns

- metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProfile.pdl
Can use
```
/q hasRowCount:true
```
```
/q NOT (hasRowCount:true)
```
> feat(search): add search annotations for profile aspect

- metadata-ingestion/docs/sources/business-glossary/datahub-business-glossary.md
- metadata-ingestion/examples/bootstrap_data/business_glossary.yml
This PR updates the business glossary docs to make them more readable. It provides examples of a Glossary, GlossaryNode, and GlossaryTerm with inline comments explaining what each does, and the examples use all available fields. It also attempts to place the example yaml link in an easier-to-find location.
> docs(business glossary) Update business glossary docs

- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/EntityRegistryTestUtil.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/GraphIndexUtilsTest.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
- metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/ingestion/IngestionSchedulerHookTest.java
> fix(test): consolidate mae-consumer test entity registry

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/tests/integration/tableau/tableau_extract_all_project_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_nested_project_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_signout_timeout_mces_golden.json
- metadata-ingestion/tests/integration/tableau/tableau_with_platform_instance_mces_golden.json
In https://github.com/datahub-project/datahub/pull/8307 I hide the embed previews for Tableau in the UI. For those who won't update their UI, lets not continue creating bad embed tabs.
> fix(embed): set embed url to false for tableau config

- metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
- metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py
- metadata-ingestion/tests/integration/postgres/postgres_all_db_mces_with_db_golden.json
- metadata-ingestion/tests/integration/postgres/postgres_all_db_to_file_with_db_estimate_row_count.yml
- metadata-ingestion/tests/integration/postgres/postgres_mces_with_db_golden.json
- metadata-ingestion/tests/integration/postgres/postgres_to_file_with_db_estimate_row_count.yml
- metadata-ingestion/tests/integration/postgres/setup/setup.sql
> fix(ingest/postgres): fix profiling errors, skip json type column

- metadata-io/src/test/java/com/linkedin/metadata/ESTestUtils.java
- metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/fixtures/SampleDataFixtureTests.java
> tests(elasticsearch): Add fixture test for basic scroll functionality

- datahub-web-react/src/app/search/sidebar/BrowseNode.tsx
- datahub-web-react/src/app/search/sidebar/PlatformNode.tsx
- datahub-web-react/src/app/search/sidebar/useBrowsePagination.tsx
> fix(browsev2): improved error handling

- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/utilities/yaml_sync_utils.py
- metadata-ingestion/tests/unit/utilities/test_yaml_sync_utils.py
> feat(ingest): add YamlFileUpdater utility

- docs-website/sidebars.js
- docs/api/restli/get-elastic-task-status.md
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/operations/OperationsResource.java
- metadata-service/restli-servlet-impl/src/test/java/com/linkedin/metadata/resources/operations/OperationsResourceTest.java
> fix(restli): Add docs for get task status, and fix hostname regex

- datahub-web-react/src/app/home/AcrylDemoBanner.tsx
Updates the copy for our demo site acryl banner based on feedback we've received.
> fix(ui) Update copy of the demo site acryl banner

- metadata-ingestion/src/datahub/cli/migrate.py
> fix(cli): local variable reference before assignment

- metadata-ingestion/src/datahub/cli/check_cli.py
> build(ingest): Inline import testing utils for check cli

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
> fix(ingest/bigquery): skip self-references when generating lineage

- metadata-ingestion/src/datahub/__init__.py
Open to improvements on the actual message
> docs(ingest): Add warning for Python 3.7 deprecation

- datahub-web-react/src/app/entity/dataset/profile/stats/historical/HistoricalStatsView.tsx
> chore(stats): change default stats lookback

- perf-test/README.md
> docs(perf-test) Update README

- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_file_without_extension.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_exclude.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_filename.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_no_partition_glob.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_basic.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_keyval.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_folder_partition_update_schema.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_files.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_spec_for_files.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_multiple_specs_of_different_buckets.json
- metadata-ingestion/tests/integration/s3/golden-files/s3/golden_mces_single_file.json
- metadata-ingestion/tests/integration/s3/test_s3.py
Set s3 test file modification date explicitly for s3 files
> fix(ingest/s3): fix test flakiness

- metadata-ingestion/setup.py
> fix(ingest/snowflake): Add sqlglot as snowflake dependency

- metadata-integration/java/spark-lineage/README.md
> docs(databricks/spark-lineage): Fix incorrect statement

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/feature_groups.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/models.py
This reverts commit f41f642eaf4ff602c8299426912a63d26dc91e35.
And requires one additional type change. If this happens again I'll look for a more permanent solution, but this was pretty easy for now
> build(ingest/boto3): Update boto3-stubs to fix CI

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_report.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/utilities/stats_collections.py
- Handle table name formatting issues
- Include some failed view names in the report
- Fixes the stage duration sorting in the report
> fix(ingest/bigquery): make sql parsing more robust

- docs/deploy/environment-vars.md
> docs(env): add env vars authentication

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
- metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_tags.py
- metadata-ingestion/src/datahub/ingestion/transformer/dataset_transformer.py
- metadata-ingestion/src/datahub/ingestion/transformer/extract_dataset_tags.py
- metadata-ingestion/tests/unit/test_elasticsearch_source.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> ingest(elasticsearch): add basic profiling

- docs/how/updating-datahub.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/source_registry.py
- Both have been in there for ~8 months.
> chore(ingest): drop bigquery-beta and snowflake-beta aliases

- metadata-ingestion/src/datahub/ingestion/source/elastic_search.py
> feat(ingest/elastic): reduce number of calls made

- metadata-ingestion/examples/library/create_mlmodel.py
> chore(ingest): add example of training metric/hyper parameters

- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
> docs: add docs on sqlglot lineage

- metadata-ingestion/src/datahub/testing/compare_metadata_json.py
> fix(ingest): hint at --update-golden-files option when tests fail

- metadata-ingestion/docs/sources/looker/lookml_pre.md
- Also updates the sample lookml recipe.
> docs(ingest/lookml): clarify connection map config

- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraAspectDao.java
> feat(metrics): add metrics for aspect write and bytes

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/feature_groups.py
- metadata-ingestion/src/datahub/utilities/mapping.py
- metadata-ingestion/src/datahub_provider/_plugin.py
- metadata-ingestion/src/datahub_provider/operators/datahub_assertion_operator.py
- metadata-ingestion/src/datahub_provider/operators/datahub_assertion_sensor.py
- metadata-ingestion/src/datahub_provider/operators/datahub_operation_operator.py
- metadata-ingestion/src/datahub_provider/operators/datahub_operation_sensor.py
- metadata-ingestion/tests/unit/test_glue_source.py
- metadata-ingestion/tests/unit/test_kafka_source.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
Fixing Sagemaker mypy issue
Using instanceof vs type to fix flak8 errors
> fix(ingest/build): Fix sagemaker mypy and flake8 issues

- datahub-web-react/src/app/lineage/LineageEntityNode.tsx
- smoke-test/tests/cypress/cypress/e2e/siblings/siblings.js
> fix(test): increase siblings.js test stability

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/unit/s3/test_s3_source.py
> fix(ingest/s3): wrong sorting in case of multi-partition key

- metadata-ingestion/tests/integration/presto-on-hive/presto_on_hive_mces_golden_5.json
Caused by two PRs getting merged simultaneously.
> fix(ingest/presto): fix presto on hive test failures

- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
> fix(ingest/s3): catch no such bucket exception instead of failing

- metadata-ingestion/setup.py
> fix(ingest): add tableau sqlglot dep

- metadata-service/configuration/src/main/resources/application.yml
> fix(glue): restore glue configurations

- datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
- gradle/versioning/versioning.gradle
- smoke-test/tests/cypress/cypress/e2e/mutations/managed_ingestion.js
> build(release): Update files for 0.10.5 release

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Stats/StatsTab.tsx
Follow up of https://github.com/datahub-project/datahub/pull/8408. Seems like we needed to change 2 places
> fix(stats): default to 3 months

- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
> fix(aspect): count query only for relevant aspect index

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
In response to continued issues e.g. https://github.com/datahub-project/datahub/issues/8133
Closes https://github.com/datahub-project/datahub/pull/8573. Should also fix https://github.com/datahub-project/datahub/issues/8044.
> feat(quickstart): bump quickstart start periods more

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
> fix(ingest/snowflake): maintain qualified name casing, do not lowercase

- metadata-ingestion/src/datahub/emitter/mce_builder.py
> docs(lineage): Add description to make_lineage_mce

- metadata-ingestion/README.md
Document the option added in this PR https://github.com/datahub-project/datahub/pull/5694
> doc(ingest/log): failure log at pipeline level document

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_10.md
> doc(release): release notes for 0.2.10

- docs/managed-datahub/release-notes/v_0_2_10.md
> docs(release): fix typo

- datahub-web-react/src/app/search/autoComplete/AutoCompleteEntity.tsx
- datahub-web-react/src/app/search/autoComplete/AutoCompleteItem.tsx
- smoke-test/tests/cypress/cypress/e2e/auto_complete/auto_complete.js
All autocomplete tests pass for me locally before and after this PR, so I'm not sure yet what situation is causing this in CI.
Theory being that the urn doesn't match the one I hardcoded, so hopefully this fixes that by making it more flexible.
> fix(cypress): attempt to fix autocomplete test

- docs/quickstart.md
> docs(quickstart): quickstart documentation, clarification on production

- datahub-web-react/src/app/search/AdvancedFilterSelectValueModal.tsx
- datahub-web-react/src/app/search/utils/constants.ts
> fix(data products): removing data products filter in search as its not indexed on entity documents

- smoke-test/tests/cypress/cypress/e2e/lineage/lineage_column_level.js
Test steps:
1. Navigate to Lineage Graph View
2. Click “show columns”
3. Verify that Column-Level Lineage is showing correctly
> Lineage column level test

- docs/lineage/airflow.md
> docs(ingest/airflow): add `capture_executions` to docs

- metadata-ingestion/tests/integration/vertica/docker-compose.yml
- metadata-ingestion/tests/integration/vertica/test_vertica.py
> test(ingest/vertica): Skip integration test failing CI; support arm Macs

- smoke-test/tests/cypress/cypress/e2e/login/login.js
This test was recently incorrectly edited so that it always fails. This fixes the copy we're looking for.
> fix(cypress) Fix login.js cypress test

- metadata-ingestion/src/datahub/ingestion/source/openapi.py
cc @shirshanka as you marked this certified in the past
> docs(ingest/openapi): Downgrade status from CERTIFIED to INCUBATING

- metadata-ingestion/setup.py
> build(ingest): Pin mypy-boto3-sagemaker directly

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> fix(ingest/athena): Fixing db container id

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_utils.py
Follow up on https://github.com/datahub-project/datahub/pull/8689.
> fix(ingest/athena): fix container linting

- docker/datahub-frontend/Dockerfile
> fix(datahub-frontend) Give permission for start.sh so it can run

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/tests/unit/test_bigquery_lineage.py
Test confirmed to fail before the 1 line change
> fix(ingest/bigquery): Filter out fine grained lineage with no upstreams

- docs/managed-datahub/observe/volume-assertions.md
> docs(observe): Dataset Profile volume assertion guide

- docs/api/restli/evaluate-tests.md
> doc(tests): fix endpoint param to push results

- datahub-web-react/package.json
- datahub-web-react/yarn.lock
Confirmed track calls still happened in the network tab ✅
> chore(analytics): bump version

- metadata-ingestion-modules/airflow-plugin/setup.py
> feat(airflow-plugin): add package type information

- docs-website/filterTagIndexes.json
> docs: add datahub source to integrations page

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/utilities/sql_parser.py
- metadata-ingestion/tests/unit/test_utilities.py
> feat(ingest): drop sql_metadata parser

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
> fix(custom-search): fix custom search to be able to use unquoted query

- docs/how/updating-datahub.md
> docs(release): Update updating-datahub.md for 0.11.0 release

- docker/datahub-ingestion-base/smoke.Dockerfile
- docker/datahub-ingestion/Dockerfile
- docker/datahub-ingestion/Dockerfile-slim-only
- metadata-ingestion-modules/airflow-plugin/scripts/release.sh
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/__init__.py
- metadata-ingestion/scripts/release.sh
- metadata-ingestion/src/datahub/__init__.py
Inspired by Dagster's approach to this problem, which is the exact same problem we're running into right now: https://github.com/dagster-io/dagster/pull/11334
Superseeds https://github.com/datahub-project/datahub/pull/8816.
> fix(ingest): use epoch 1 for dev build versions

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
See stack overflow link in the comments
> feat(ingest/rest-emitter): Do not raise error on retry failure to get better error messages

- metadata-events/mxe-avro-1.7/build.gradle
> fix(build): clean task cleanup generated src

- .github/workflows/docker-ingestion-smoke.yml
> feat(ci): disable ingestion smoke build

- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
- datahub-web-react/src/app/lineage/LineageExplorer.tsx
- metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
Adding logging for impact analysis, lineage viz and expanding the lineage viz.
> logging(lineage): adding some lineage explorer and impact analysis logging

- docs-website/sidebars.js
- docs/managed-datahub/observe/custom-assertions.md
Add docs for Custom Assertions (Acryl only)
> docs(observability): Add Custom Assertion user guide

- metadata-ingestion/src/datahub/ingestion/source/mode.py
> fix(ingest): fix mode lint error

- docs/managed-datahub/observe/custom-assertions.md
Custom Assertion updates to reflect current UI:
- Renamed "Differential" to "Value"
- Removed "Is False" option from evaluation criteria
> docs(observability): Custom Assertion user guide updates

- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- allow CLL in BigQuery without enabling `include_tables` and `include_views`
- improved performance of sql-queries source due to bulk fetching of schema
> feat(ingest): bulk fetch schema info for schema resolver

- metadata-ingestion/docs/sources/looker/lookml_post.md
> docs(ingest/lookml): add guide on debugging lkml parse errors

- build.gradle
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/auth/ListAccessTokensResolverTest.java
Fix regression in test execution
> fix(test): fix test execution

- docs-website/sidebars.js
- docs/managed-datahub/observe/custom-sql-assertions.md
> fix(docs): Rebranding custom to custom SQL

- metadata-ingestion/setup.py
> fix(ingest): bump typing-extensions

- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
> test(ingest/delta-lake): Fix minio test for new version of delta-lake

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/queries.py
> refactor(ingest/bigquery): Clarify table / view queries

- datahub-web-react/src/app/entity/shared/components/styled/DemoButton.tsx
- datahub-web-react/src/app/home/AcrylDemoBanner.tsx
- docs-website/docusaurus.config.js
- docs-website/src/pages/_components/CardCTAs/index.js
- docs-website/src/pages/_components/Section/index.js
- docs/saas.md
> docs: update cta links for acryl

- docs/act-on-metadata/impact-analysis.md
Changed `Platfrom` to `Platform`
- [yes] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [n/a] Links to related issues (if applicable)
- [n/a] Tests for the changes have been added/updated (if applicable)
- [n/a] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [n/a] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)
> docs: fix typo in impact-analysis.md

- metadata-ingestion/src/datahub/ingestion/graph/client.py
> fix(client): use value for RelationshipDirection

- datahub-web-react/src/app/lineage/utils/__tests__/columnLineageUtils.test.tsx
- datahub-web-react/src/app/lineage/utils/columnLineageUtils.ts
- datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts
> fix(fine-grained lineage) CLL for datajob downstreams

- docs/how/add-custom-data-platform.md
- docs/how/add-user-data.md
- docs/ownership/ownership-types.md
- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/transformer/extract_ownership_from_tags.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> feat(transfomer): add transformer to get ownership from tags

- docs/deploy/aws.md
Reports from https://datahubspace.slack.com/archives/C029A3M079U/p1695847882924719
> fix: fix typo on aws guide

- .github/workflows/build-and-test.yml
- .github/workflows/metadata-ingestion.yml
- metadata-ingestion/tests/integration/powerbi/test_admin_only_api.py
- metadata-ingestion/tests/integration/powerbi/test_m_parser.py
- metadata-ingestion/tests/integration/powerbi/test_powerbi.py
- metadata-ingestion/tests/integration/snowflake/test_snowflake.py
- metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
- metadata-ingestion/tests/integration/trino/test_trino.py
> ci: tweak ci runs to decrease wait time of devs

- datahub-web-react/src/app/settings/AccessTokenModal.tsx
- datahub-web-react/src/app/settings/AccessTokens.tsx
- datahub-web-react/src/app/settings/CreateTokenModal.tsx
- smoke-test/tests/cypress/cypress/e2e/settings/manage_access_tokens.js
- smoke-test/tests/cypress/cypress/support/commands.js
Test steps:
1. Create access token
2. Verify token created successfully
3. Revoke access token
4. Verify token removed successfully
> Manage Access Tokens Cypress test

- metadata-models/src/main/pegasus/com/linkedin/assertion/AssertionInfo.pdl
- metadata-models/src/main/pegasus/com/linkedin/assertion/SqlAssertionInfo.pdl
> feat(models/assertion): Add SQL Assertions

- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
- metadata-ingestion/tests/unit/api/source_helpers/test_incremental_lineage_helper.py
> feat(ingest): refactor + simplify incremental lineage helper

- metadata-ingestion/src/datahub/ingestion/api/common.py
- metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_tests.py
> refactor(ingest/dbt): move dbt tests logic to dedicated file

- metadata-ingestion/src/datahub/ingestion/source/data_lake_common/path_spec.py
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
Fixes https://github.com/datahub-project/datahub/issues/8734.
> feat(ingest/s3): support .gzip and fix decompression bug

- smoke-test/tests/cypress/cypress/e2e/search/query_and_filter_search.js
Test steps:
1. Verify search results for test query and Airflow platform
2. Verify search results for test query and BigQuery platform
3. Verify search results for test query and dbt platform
4. Verify search results for test query and Hive platform
5. Verify search results for test query and Datasets entity type
6. Verify search results for test query and Dashboards entity type
7. Verify search results for test query and Pipelines entity type
8. Verify search results for test query and Domains entity type
9. Verify search results for test query and Glossary Terms entity type
> Query plus filter search test

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_11.md
- docs/managed-datahub/release-notes/v_0_2_12.md
> docs(Acryl DataHub): release notes for 0.2.12

- metadata-ingestion/setup.py
> Adding missing sqlparser libs to setup.py

- metadata-ingestion/setup.py
> build(ingest/redshift): Add sqlglot dependency

- metadata-ingestion/examples/library/create_dataproduct.py
> add create dataproduct example

- docker/build.gradle
- docker/datahub-gms/Dockerfile
- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
> chore(docker): update base images to alpine 3.18

- docs/datahub_lite.md
> docs(datahub-lite): Fix recipe

- metadata-ingestion/src/datahub/cli/specific/group_cli.py
> fix(ingest): fix typo in parsing list of groups

- metadata-integration/java/datahub-protobuf/README.md
> docs(protobuf) Update messaging around nesting messages

- metadata-ingestion/tests/integration/delta_lake/delta_lake_minio_mces_golden.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_allow_table.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_inner_table.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_relative_path.json
- metadata-ingestion/tests/integration/delta_lake/golden_files/local/golden_mces_single_table.json
> test(ingest/delta-lake): Fix integration tests

- docs-website/docusaurus.config.js
- docs-website/src/styles/global.scss
- docs-website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
- docs-website/src/theme/NavbarItem/styles.module.scss
Minor tweaks to navbar refactor
> docs(website): styling and other tweaks to main navbar

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/MappingsBuilder.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/search/TimeseriesAspectServiceTestBase.java
- metadata-io/src/test/java/io/datahubproject/test/search/SearchTestContainer.java
- smoke-test/tests/containers/containers_test.py
> fix(search): fix mapping builder bug

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
- metadata-ingestion/src/datahub/utilities/sqlalchemy_type_converter.py
- metadata-ingestion/tests/unit/test_athena_source.py
- metadata-ingestion/tests/unit/utilities/test_sqlalchemy_type_converter.py
> refactor(ingest): Move sqlalchemy import out of sql_types.py

- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_update_from_table.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_snowflake_update_hardcoded.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(sqlparser): extract CLL from `update`s

- docs/how/updating-datahub.md
> docs(ingest/bigquery): Add docs for breaking change: match_fully_qualified_names

- docs/how/updating-datahub.md
As per discussion in https://github.com/datahub-project/datahub/pull/9087 and https://github.com/datahub-project/datahub/issues/9085
> docs(update): Added info on breaking change for policies

- docs-website/docusaurus.config.js
> docs: add luckyorange script to head

- metadata-auth/auth-api/src/main/java/com/datahub/authorization/EntityFieldType.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DefaultEntitySpecResolver.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/DataPlatformInstanceFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/DomainFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/EntityFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/EntityTypeFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/EntityUrnFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/GroupMembershipFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/OwnerFieldResolverProvider.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/DataPlatformInstanceFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/GroupMembershipFieldResolverProviderTest.java
> feat(auth): Add backwards compatible field resolver

- metadata-models/build.gradle
- metadata-service/restli-servlet-impl/build.gradle
Minor build changes to support IntelliJ 2023.2.3, thanks @david-leifker
> build(gradle): Support IntelliJ 2023.2.3

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
- metadata-ingestion/tests/unit/test_bigquery_source.py
> feat(ingest/bigquery): Attempt to support raw dataset pattern

- docs/dev-guides/timeline.md
As a result "Explore the API" and "Future Work" links show up and can be shared as a link.
> docs(timeline): correct markdown heading level

- .github/workflows/airflow-plugin.yml
- .github/workflows/check-datahub-jars.yml
- .github/workflows/documentation.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/metadata-model.yml
> ci: tweak to only run relevant workflows

- metadata-ingestion/setup.py
See https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/272
Example failure: https://github.com/datahub-project/datahub/actions/runs/6688931190/job/18171700309?pr=9123
> fix(ingest/clickhouse): pin version to solve column reflection regression

- metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- metadata-ingestion/tests/integration/vertica/test_vertica.py
- metadata-ingestion/tests/test_helpers/docker_helpers.py
This will mitigate failures like this one: https://github.com/datahub-project/datahub/actions/runs/6701852267/job/18209927919
> fix(ingest): cleanup large images in CI

- datahub-web-react/src/app/entity/group/GroupProfile.tsx
- datahub-web-react/src/app/entity/user/UserProfile.tsx
- datahub-web-react/src/conf/Global.ts
> feat: rename Assets tab to Owner Of

- metadata-ingestion/adding-source.md
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1698741579390259?thread_ts=1698398043.109239&cid=CUMUWQU66
> docs(ingest): clarify adding source guide

- datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
> lint(frontend): fix HeaderLinks lint error

- build.gradle
- datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
- metadata-service/restli-api/build.gradle
> fix(security): fix for zookeeper CVE-2023-44981

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
Got tired of reading `tableau_constant` all the time
> style(ingest/tableau): Rename tableau_constant to c

- smoke-test/tests/privileges/test_privileges.py
> Test policy to create and manage privileges

- docs-website/generateDocsDir.ts
- docs-website/sidebars.js
> docs(security): add security doc to website

- datahub-web-react/src/app/ingest/source/IngestionSourceTableColumns.tsx
- datahub-web-react/src/app/ingest/source/executions/ExecutionRequestDetailsModal.tsx
- datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
> Managed Ingestion UX Improvements

- SECURITY.md
- docs-website/sidebars.js
> fix: add security.md to sidebar

- README.md
Added new company that try to officially adopte DataHub
> Update add new company s7 airlines

- docs/actions/README.md
- docs/cli.md
> docs(debug): add debug information for cli

- docs/deploy/telemetry.md
Closes https://github.com/datahub-project/datahub/issues/8893.
> docs: clarify how to disable telemetry

- datahub-frontend/app/auth/NativeAuthenticationConfigs.java
- datahub-frontend/app/controllers/AuthenticationController.java
- datahub-frontend/conf/application.conf
- metadata-service/auth-impl/src/main/java/com/datahub/authentication/user/NativeUserService.java
- metadata-service/auth-impl/src/test/java/com/datahub/authentication/user/NativeUserServiceTest.java
- metadata-service/auth-servlet-impl/src/main/java/com/datahub/auth/authentication/AuthServiceController.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/auth/NativeUserServiceFactory.java
> fix(signup): prevent invalid email signup

- datahub-web-react/build.gradle
- datahub-web-react/package.json
> chore(node): update node to non-EOL version

- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
> test(ingest/unity): Update goldens

- docs/lineage/airflow.md
> docs(airflow): update plugin setup docs to include UI setup approach

- .github/actions/docker-custom-build-and-push/action.yml
- .github/workflows/docker-unified.yml
> fix(gha): fix gha for single tag

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_13.md
> docs(acryl cloud): release notes 0.2.13

- datahub-web-react/src/app/entity/dashboard/shared/DashboardStatsSummary.tsx
- datahub-web-react/src/app/entity/dataset/shared/DatasetStatsSummary.tsx
> fix: stats are spaced out too far

- metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/SimpleKafkaConsumerFactory.java
- metadata-service/factories/src/test/java/com/linkedin/gms/factory/kafka/SimpleKafkaConsumerFactoryTest.java
> fix(kafka): fix consumer properties on due consumer

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
> fix(dbt-cloud): do not pass macros to sorting nodes

- docs/managed-datahub/release-notes/v_0_2_13.md
> docs: update recommended CLI

- build.gradle
- entity-registry/build.gradle
- entity-registry/src/test/java/com/linkedin/metadata/models/OpenApiSpecBuilderTest.java
> Add test to generate Open API spec from EntityRegistry.

- docker/docker-compose-with-cassandra.yml
- docker/docker-compose-without-neo4j.yml
- docker/docker-compose.yml
- docker/quickstart/docker-compose-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
Healthchecks execute within the container and should not refer to mapped ports.
> fix(docker): docker compose health checks port fix

- metadata-ingestion/setup.py
Based on https://github.com/acryldata/PyHive/pull/9.
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1701213692269599?thread_ts=1701204073.215289&cid=CUMUWQU66
> fix(ingest): bump pyhive to fix headers issue

- .github/workflows/metadata-model.yml
> Upload metadata model to s3

- metadata-ingestion/src/datahub/ingestion/source/ldap.py
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1699968251193749?thread_ts=1698318180.127719&cid=CUMUWQU66
> feat(ingest/ldap): make ingestion robust to string departmentId

- datahub-web-react/package.json
- datahub-web-react/yarn.lock
> fix:Address HIGH vulnerability with Axios

- docs/quick-ingestion-guides/looker/setup.md
- metadata-ingestion/docs/sources/looker/lookml_pre.md
- metadata-ingestion/src/datahub/configuration/git.py
> docs(ingest/lookml): clarify that ssh key has no passphrase

- docs/developers.md
Follow up on https://github.com/datahub-project/datahub/pull/9339.
> docs: add setup instructions for mac dependencies

- docker/elasticsearch-setup/create-indices.sh
- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/aws_es_index_template.json
- metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/index_template.json
> fix(elasticsearch): set datahub usage events shard & replica count

- datahub-web-react/src/App.less
- [- ] Links to related issues (if applicable)
- [- ] Tests for the changes have been added/updated (if applicable)
- [- ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [- ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)
> fix(ui): fixed font src spelling mistake

- docs-website/sidebars.js
> docs: fix duplicated overview link for api section

- metadata-ingestion/src/datahub/configuration/git.py
- metadata-ingestion/src/datahub/ingestion/source/git/git_import.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/tests/integration/git/test_git_clone.py
- metadata-ingestion/tests/integration/lookml/test_lookml.py
Also refactors some of the clone logic into the config object.
This also uses doctest within pytest for testing, which I think we should do more of in the future.
> fix(ingest/lookml): make deploy key optional

- metadata-ingestion/setup.py
> fix(ingest/transformer): correct registration

- build.gradle
> fix(CVE-2023-6378): update logback classic

- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic_profiler.py
> fix(ingest/profiling) Fixing profile eligibility check

- metadata-ingestion/src/datahub/configuration/git.py
> fix(ingest): avoid git dependency in dbt

- docs-website/genJsonSchema/gen_json_schema.py
> fix(ingest): bump source configs json schema version

- metadata-io/src/main/java/com/linkedin/metadata/timeseries/elastic/ElasticSearchTimeseriesAspectService.java
- metadata-io/src/test/java/com/linkedin/metadata/timeseries/search/TimeseriesAspectServiceUnitTest.java
- metadata-models/src/main/pegasus/com/linkedin/timeseries/TimeseriesIndexSizeResult.pdl
- metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json
> fix(operations): fix get index sizes integer wrap

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/report.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/usage.py
- metadata-ingestion/tests/integration/redshift-usage/test_redshift_usage.py
> feat(ingest/redshift): drop repeated operations

- datahub-web-react/src/app/entity/group/EditGroupDescriptionModal.tsx
- datahub-web-react/src/app/entity/group/GroupInfoSideBar.tsx
- datahub-web-react/src/app/identity/group/CreateGroupModal.tsx
- smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js
Here is the screencast [Screencast from 13-12-23 06:13:00 PM IST.webm](https://github.com/datahub-project/datahub/assets/77378510/cbe2b9fd-4bfc-463f-942a-104699fd03cc)
> feat : markdown support for group description

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_lib_wrapper.py
- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
> feat(ingest): enable CLL for dbt by default

- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-ingestion/Dockerfile
- docker/datahub-ingestion/build.gradle
> Fix downstream CI issue

- metadata-ingestion/src/datahub/ingestion/source/redshift/usage.py
> fix(ingest/redshift: Fixing operation query to not return duplicate operations

- docker/docker-compose.dev.yml
- docker/profiles/docker-compose.frontend.yml
> fix(docker): fix frontend dev docker path

- .github/workflows/docker-unified.yml
> Do not sync demo in downstream repos

- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
> fix(ingest): update ingest_stats event with transformer types

- datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
> style | PRD-893 | Tag overflow is missing padding

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/analytics/resolver/GetChartsResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/util/DateUtil.java
> feat(analytics): change MAU chart to be until last month

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
- metadata-ingestion/tests/integration/fivetran/fivetran_golden.json
> fix(ingest/fivetran): only materialize upstream lineage

- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-ingestion-base/base-requirements.txt
- metadata-ingestion/developing.md
- metadata-ingestion/scripts/datahub_preflight.sh
- metadata-ingestion/scripts/install_deps.sh
- metadata-ingestion/setup.py
Possible now that https://github.com/confluentinc/confluent-kafka-python/issues/1182 is unblocked.
> feat(ingest): remove librdkafka hacks

- metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_non_incremental_lineage_mces_golden.json
- metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Follow up on https://github.com/datahub-project/datahub/pull/9508 to fix tests.
> fix(ingest): update dbt type inference

- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
We really should migrate to using the `SqlParsingBuilder` instead of rebuilding this merge logic everywhere.
> feat(ingest/redshift): merge CLL instead of overwriting

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/AssertionMenu.tsx
- datahub-web-react/src/app/entity/shared/tabs/Dataset/Validations/DatasetAssertionsList.tsx
> feat(ui): Allow copying assertion urn from the UI

- metadata-ingestion/src/datahub/ingestion/source/openapi.py
- metadata-ingestion/src/datahub/ingestion/source/openapi_parser.py
fixes https://github.com/datahub-project/datahub/issues/7914
adding http proxies
support for authentication scheme other than bearer
> feat(ingest/openapi): support proxies and alternate auth schemes

- metadata-ingestion/setup.py
Changelogs:
* https://github.com/feast-dev/feast/releases/tag/v0.32.0
* https://github.com/feast-dev/feast/releases/tag/v0.33.0
* https://github.com/feast-dev/feast/releases/tag/v0.34.0
> build(ingest/feast): upgrade to latest feast version

- datahub-web-react/src/app/identity/user/UserListItem.tsx
- datahub-web-react/src/app/identity/user/ViewResetTokenModal.tsx
- smoke-test/tests/cypress/cypress/e2e/mutations/add_users.js
> add automatic reset password test

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
Closes https://github.com/datahub-project/datahub/issues/9461
> fix(ingest/snowflake): explicit set schema if public schema is absent

- datahub-web-react/src/app/ingest/source/executions/IngestionExecutionTable.tsx
- datahub-web-react/src/app/shared/formatDuration.ts
> Humanise duration shown on ingestion page

- datahub-web-react/src/app/ingest/secret/SecretBuilderModal.tsx
> while creating secrets via UI validate validate character~

- datahub-web-react/src/app/ingest/source/builder/constants.ts
> feat(ui): add databricks logo

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_14.md
> docs(acryl cloud): release notes for 0.2.14.1

- .github/workflows/docker-unified.yml
> ci(doc): tweak build rule to avoid docker build for docs

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_config.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
> fix(ingest/looker): add user stats to report

- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-io/src/test/java/com/linkedin/metadata/graph/search/ESGraphQueryDAOTest.java
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_query_filters_full.json
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_query_filters_full_empty_filters.json
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_query_filters_full_multiple_filters.json
- metadata-io/src/test/resources/elasticsearch/sample_filters/lineage_query_filters_limited.json
Improves lineage performance for the Elastic-backed graph store by generating a more efficient query.
> perf(lineage): Rewrite lineage query for Elastic graph store

- docker/build.gradle
- docker/profiles/README.md
- docker/profiles/docker-compose.actions.yml
- docker/profiles/docker-compose.frontend.yml
- docker/profiles/docker-compose.gms.yml
- docker/profiles/docker-compose.prerequisites.yml
- docs/developers.md
- docs/how/updating-datahub.md
* Add minimum version check for docker compose
* Add documentation for minimum version
* Add docker repo overrides for docker compose profiles
> feat(docker): docker compose profiles updates

- .github/workflows/spark-smoke-test.yml
- docker/build.gradle
Dump quickstart container logs for spark smoke test
> build(spark-smoke): dump container logs for spark smoke test

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
> fix(ingest/looker): limit dashboard object lifetime to thread

- datahub-web-react/src/app/entity/shared/components/styled/search/DownloadAsCsvModal.tsx
> Lower count for CSV download query from 500 to 200 to alleviate timeouts

- smoke-test/tests/cypress/cypress/e2e/search/query_and_filter_search.js
> Fix - Removed AWS S3 Platform

- datahub-frontend/app/controllers/AuthenticationController.java
- datahub-frontend/test/app/ApplicationTest.java
> fix(frontend): restrict redirect uri domain

- docs/managed-datahub/saas-slack-setup.md
- metadata-ingestion/docs/sources/postgres/postgres_recipe.yml
> docs(slack): add note about private Slack channels

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
Slack ref: https://datahubspace.slack.com/archives/CUMUWQU66/p1704469819808509
> fix(ingest/snowflake): set platform instance for foreign keys

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/rolemetadata/mappers/AccessMapper.java
> fix(graphql): fix npe in access mapper

- smoke-test/tests/cypress/cypress/e2e/query/query_tab.js
> Fix - updated verification steps

- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/transformer/extract_ownership_from_tags.py
- metadata-ingestion/tests/integration/tableau/tableau_with_platform_instance_mces_golden.json
> feat(ingest/tableau): include platform_instance in browse v1 path

- metadata-ingestion/src/datahub/ingestion/source/nifi.py
- metadata-ingestion/tests/unit/test_nifi_source.py
> fix(ingest/nifi): make s3 dataset urn consistent with s3 source

- smoke-test/tests/cypress/cypress/e2e/search/query_and_filter_search.js
> Unskip "type" filter tests

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
> feat(ingest/dbt): speed up dbt CLL

- entity-registry/src/main/java/com/linkedin/metadata/models/SearchableFieldSpecExtractor.java
- entity-registry/src/main/java/com/linkedin/metadata/models/annotation/SearchableAnnotation.java
- entity-registry/src/test/java/com/linkedin/metadata/models/EntitySpecBuilderTest.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AggregationQueryBuilder.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/AggregationQueryBuilderTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchQueryBuilderTest.java
- metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchRequestHandlerTest.java
- metadata-utils/src/main/java/com/linkedin/metadata/utils/SearchUtil.java
- test-models/src/main/pegasus/com/datahub/test/TestEntityInfo.pdl
> feat(search): add support for empty aggregations through searchable annotation

- docs-website/docusaurus.config.js
> docs: add events link

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> feat(ingest/dbt-cloud): Add way to customize dbt cloud access endpoint

- metadata-ingestion/setup.py
NOTE: This updates the pyarrow dependencies to resolve https://nvd.nist.gov/vuln/detail/CVE-2023-47248
Changelog: https://github.com/feast-dev/feast/releases/tag/v0.35.0
- [ n/a] Links to related issues (if applicable)
- [n/a ] Tests for the changes have been added/updated (if applicable)
- [ n/a] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ n/a] For any breaking change/potential downtime/deprecation/big changes an …
> build(ingest/feast): upgrade to latest feast version (0.35.x)

- metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
> feat(cli): add threads to sink report

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessor.java
- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeLogProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
- metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
- metadata-jobs/pe-consumer/src/main/java/com/datahub/event/PlatformEventProcessor.java
- metadata-service/factories/src/main/java/com/linkedin/metadata/boot/kafka/DataHubUpgradeKafkaListener.java
> feat(monitoring): add metrics for kafka consumers

- metadata-ingestion/src/datahub/emitter/sql_parsing_builder.py
> feat(ingest/sql-parsing): Support file backed dict in SqlParsingBuilder for lineage

- datahub-web-react/src/app/identity/user/UserList.tsx
> fix(user-removal):  resolve user removal list update issue

- metadata-ingestion/docs/sources/kafka-connect/README.md
> fix(docs): Correct Kafka Connect sink documentation

- .github/actions/ci-optimization/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/metadata-io.yml
Don't install python if its not needed.
> fix(workflow): workflow tweaks

- metadata-ingestion/src/datahub/ingestion/source/unity/hive_metastore_proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
- metadata-ingestion/tests/integration/unity/unity_catalog_mces_golden.json
Ideally Stacked on top of https://github.com/datahub-project/datahub/pull/9601
> feat(ingest/databricks): view upstream lineage for hive metastore

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lkml_patched.py
- metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
- metadata-ingestion/tests/integration/lookml/lkml_manifest_samples/complex-manifest.lkml
- metadata-ingestion/tests/integration/lookml/test_lookml.py
Related to https://github.com/joshtemple/lkml/issues/77
> feat(ingest/lookml): support complex lookml manifests

- metadata-ingestion/docs/sources/datahub/datahub_recipe.yml
- metadata-ingestion/src/datahub/cli/ingest_cli.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_utils.py
> feat(ingest): improve sql tests + dbt reporting

- datahub-web-react/src/app/analytics/event.ts
- datahub-web-react/src/app/identity/group/AssignRoletoGroupConfirmation.tsx
- datahub-web-react/src/app/identity/group/GroupList.tsx
- datahub-web-react/src/app/identity/group/GroupListItem.tsx
- datahub-web-react/src/app/identity/group/SelectRoleGroup.tsx
- datahub-web-react/src/app/identity/group/cacheUtils.ts
- datahub-web-react/src/graphql/group.graphql
- metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
- smoke-test/tests/cypress/cypress/e2e/settings/managing_groups.js
> feat(role-assignment): add role assignment dropdown in the UI for groups

- metadata-ingestion/src/datahub/ingestion/extractor/json_schema_util.py
- metadata-ingestion/tests/unit/schema/test_json_schema_util.py
> feat(ingest): handling for const in json schema

- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
- metadata-ingestion/src/datahub/entrypoints.py
- metadata-ingestion/src/datahub/ingestion/transformer/base_transformer.py
- metadata-ingestion/src/datahub/ingestion/transformer/extract_dataset_tags.py
Thanks to @rinzool for finding this bug + suggesting the fix
EDIT: This was tweaked to be a refactoring PR only.
> refactor(ingest): simplify adding aspects to MCEs in transformers

- metadata-ingestion/src/datahub/ingestion/source/openapi.py
Add description to each args for openapi
> docs(openapi): improve description fields

- docs/managed-datahub/datahub-api/entity-events-api.md
> feat(docs): Add documentation on Incident Change Event

- smoke-test/tests/cypress/cypress/e2e/glossary/glossary.js
- smoke-test/tests/cypress/cypress/e2e/mutations/managed_ingestion.js
- smoke-test/tests/cypress/cypress/support/commands.js
> fix(test): improve cypress tests

- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
> feat(ingest/tableau): map trino_jdbc platform type

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_extractors.py
- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/m_query/native_sql_parser.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
- metadata-ingestion/tests/integration/metabase/metabase_mces_golden.json
- metadata-ingestion/tests/integration/metabase/setup/card.json
- metadata-ingestion/tests/integration/metabase/setup/card_1.json
- metadata-ingestion/tests/integration/metabase/setup/dashboard_1.json
- metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
Got reports in OSS that ingestion failed too easily. While I was at it, tried to put in the new sql parser
> feat(ingest/metabase): Use new sql parser; reduce error reporting levels

- docs/managed-datahub/observe/custom-sql-assertions.md
- docs/managed-datahub/observe/freshness-assertions.md
Adding docs around our databricks assertions support.
> docs(): Updating docs for assertions to correct databricks assertions support

- .github/workflows/spark-smoke-test.yml
- docker/build.gradle
- metadata-integration/java/spark-lineage/src/test/java/datahub/spark/TestSparkJobsLineage.java
> test(spark-lineage): minor tweaks

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_datahub_listener_module.py
Closes https://github.com/datahub-project/datahub/issues/9702.
> fix(ingest/airflow): fix plugin support for airflow 2.5.0

- .github/workflows/airflow-plugin.yml
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/airflow-plugin/tests/conftest.py
- metadata-ingestion/examples/data_contract/pet_of_the_week.dhub.dc.yaml
> fix(cli): fix example data contract yaml + update airflow codecov

- metadata-ingestion/setup.py
> fix(ingest/metabase): add missing sql parser dep

- datahub-web-react/src/app/entity/glossaryTerm/profile/AddRelatedTermsModal.tsx
- datahub-web-react/src/app/entity/shared/EntityDropdown/NodeParentSelect.tsx
- datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Domain/SetDomainModal.tsx
- datahub-web-react/src/app/glossary/GloassarySearchResultItem.tsx
- datahub-web-react/src/app/glossary/GlossarySearch.tsx
- datahub-web-react/src/app/glossary/utils.ts
- datahub-web-react/src/app/shared/DomainLabel.tsx
- datahub-web-react/src/app/shared/tags/AddTagsTermsModal.tsx
> feat(glossary-term-dropdown): include parent term groups  in dropdown

- datahub-web-react/src/app/ingest/secret/SecretBuilderModal.tsx
- datahub-web-react/src/app/ingest/secret/SecretsList.tsx
- datahub-web-react/src/app/ingest/secret/cacheUtils.ts
- datahub-web-react/src/app/ingest/secret/types.ts
> feat(edit-secret): frontend support to edit secrets

- metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
> feat(ingest/okta): option to only ingest users from filtered groups

- metadata-ingestion/src/datahub/cli/specific/dataset_cli.py
https://www.loom.com/share/15e22f3750a74024bdbdbbc757d7dfae
> feat(cli): add sibling helper CLI command

- metadata-service/war/src/main/resources/logback.xml
> chore(gms): allow adjusting the log level for gms debug log file

- docker/datahub-ingestion-base/smoke.Dockerfile
> build(ingestion-smoke): fix smoke dockerfile

- metadata-ingestion/setup.py
- metadata-ingestion/tests/test_helpers/docker_helpers.py
Related to https://github.com/avast/pytest-docker/pull/108
> fix(ingest): upgrade pytest-docker

- entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/builder/GlobalTagsPatchBuilder.java
> fix(patch): patch builder import TagUrn

- metadata-ingestion/src/datahub/ingestion/source/metabase.py
- metadata-ingestion/tests/unit/test_metabase_source.py
> feat(ingest/metabase): Allow to configure a different url for links

- docs-website/src/pages/champions/index.js
> docs: update champion bio

- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
> feat(ingest/glossary): support pydantic v2 in business-glossary source

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
> chore(lint): apply spotless

- docs-website/src/pages/slack/index.js
> fix(docs): fix the subtitle on the slack page

- datahub-web-react/src/app/settings/AccessTokens.tsx
- datahub-web-react/src/graphql/me.graphql
> feat(access-token-list): admin being able to view all org access tokens

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngineArgs.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GraphQLEngine.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/GraphQLConfiguration.java
- metadata-service/configuration/src/main/java/com/linkedin/metadata/config/GraphQLQueryConfiguration.java
- metadata-service/configuration/src/main/resources/application.yml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/config/ConfigurationProvider.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
> feat(graphql): add configuration for limiting graphql query complexity

- metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
- metadata-ingestion/tests/integration/business-glossary/business_glossary.yml
- metadata-ingestion/tests/integration/business-glossary/glossary_events_auto_id_golden.json
- metadata-ingestion/tests/integration/business-glossary/glossary_events_golden.json
this handles both custom ownership types and values from enum
> feat(ingest/glossary): handle ownership type in business glossary connector

- metadata-ingestion/src/datahub/cli/docker_check.py
- metadata-ingestion/src/datahub/cli/docker_cli.py
- smoke-test/tests/consistency_utils.py
> feat(cli): make docker compose project name configurable

- metadata-ingestion/src/datahub/cli/docker_cli.py
Closes https://github.com/datahub-project/datahub/issues/9760
> fix(cli): fix quickstart command with pydantic v2

- docs/developers.md
- metadata-jobs/mae-consumer-job/README.md
- metadata-service/README.md
Closes https://github.com/datahub-project/datahub/issues/9586
Closes https://github.com/datahub-project/datahub/issues/9795
> docs: update docs referencing jdk8

- build.gradle
Upgrade shiro-core to 1.13 due to the vulnerability.
> Upgrade shiro-core to 1.13

- docker/datahub-ingestion-base/base-requirements.txt
> feat(build): upgrade fastapi and gitdb due to vulnerablities

- metadata-service/war/src/main/resources/boot/policies.json
> doc(policies): consistent descriptions for root user policies

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_15.md
> doc(acryl cloud): release notes for 0.2.15.1

- datahub-web-react/src/app/lineage/LineageExplorer.tsx
> fix(ui/lineage): Do not crash on query entity

- datahub-web-react/src/graphql/dataPlatform.graphql
- datahub-web-react/src/graphql/post.graphql
- datahub-web-react/src/graphql/preview.graphql
> feat(graphql): Miscellaneous query additions

- datahub-web-react/.eslintrc.js
- datahub-web-react/src/app/lineage/types.ts
> refactor(ui): Update eslint and rearrange imports

- build.gradle
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandler.java
> chore(graphql): bump graphql engine version

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/utilities/logging_manager.py
- metadata-ingestion/tests/unit/test_utilities.py
> fix(ingest): better logging line attribution

- .github/workflows/docker-unified.yml
- docs/README.md
> build(workflow): test enable workflow for docs change

- metadata-models/src/main/resources/entity-registry.yml
> feat(models): Add subtypes aspect to dataFlow

- metadata-ingestion/src/datahub/cli/specific/dataset_cli.py
Original command will overwrite existing siblings: https://github.com/datahub-project/datahub/pull/9744#discussion_r1471083321
Siblings does not support PATCH operations yet https://github.com/datahub-project/datahub/blob/62f27897241516ec7aac4a809ef340fc343aa8b1/entity-registry/src/main/java/com/linkedin/metadata/aspect/patch/template/AspectTemplateEngine.java#L36-L51
> fix(cli): add-sibling preserve existing siblings

- datahub-web-react/src/app/search/PostLinkCard.tsx
> fix(posts): add padding to post link card

- smoke-test/tests/privileges/test_privileges.py
> PRD-1069 | Changed secret name

- .github/workflows/pr-labeler.yml
> feat(ci): exempt more names from being marked as community

- datahub-web-react/src/app/settings/AccessTokens.tsx
> feat(token-status-filter): add filter for expired and all tokens

- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> feat(ingest/slack): add option to ingest slack channels

- metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
- metadata-ingestion/tests/unit/test_csv_enricher_source.py
> feat(ingest/csv-enricher): add support for ownership type urn

- metadata-ingestion/setup.py
> feat(ingest): loosen sentry requirements

- datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx
> fix(ui/schema): error handling add

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
> feat(ingest/sql-parser): add alias for mariadb

- metadata-ingestion/src/datahub/ingestion/extractor/json_schema_util.py
- metadata-ingestion/tests/unit/schema/test_json_schema_util.py
> fix(ingest/json-schema): adding support descriptions for array

- metadata-ingestion/src/datahub/ingestion/source/redshift/lineage_v2.py
> fix(ingest/redshift): fix bug in lineage v2 table renames

- metadata-ingestion/setup.py
See https://github.com/acryldata/avro_gen/pull/20. See ~3x speedups for certain serialization-heavy workloads.
> feat(ingest): speed up to_obj() and validate()

- metadata-ingestion/tests/conftest.py
> feat(ingest): fix fspath lint error

- metadata-ingestion/src/datahub/cli/check_cli.py
> feat(ingestion/cli): Adding check option to validate allow/deny and path_specs

- metadata-ingestion/src/datahub/cli/check_cli.py
Fix regression from https://github.com/datahub-project/datahub/pull/9983
> fix(ingest): only import PathSpec when necessary

- metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
> fix(ingest/unity): creating group urn in case of group

- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
> fix(ui/left-side-bar): hide data products option in left side bar

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/policyfields/BackfillPolicyFieldsStep.java
> fix(policy-backfull): fix policy backfill job

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/config/SpringWebConfig.java
> fix(openapi): fix openapi openlineage endpoint

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_from_sharded_table_wildcard.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_sharded_table_normalization.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_bigquery_star_with_replace.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_create_view_as_select.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_redshift_temp_table_shortcut.json
> feat(ingest): update sqlglot fork

- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> fix(ingest/slack): tweak docs for slack source

- metadata-ingestion/src/datahub/utilities/cooperative_timeout.py
- metadata-ingestion/src/datahub/utilities/lossy_collections.py
- metadata-ingestion/tests/unit/utilities/test_cooperative_timeout.py
- metadata-ingestion/tests/unit/utilities/test_lossy_collections.py
Also adds tests for that class.
> fix(ingest): use contextvar for cooperative timeout

- metadata-ingestion/scripts/avro_codegen.py
- metadata-ingestion/scripts/custom_package_codegen.py
> feat(ingest): improve custom package metadata

- docs-website/build.gradle
- docs-website/docusaurus.config.js
- docs-website/package.json
- docs-website/yarn.lock
See https://github.com/facebook/docusaurus/issues/4765
> feat(docs): build website using swc-loader instead of babel

- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/src/datahub/utilities/sql_formatter.py
- metadata-ingestion/tests/integration/snowflake/snowflake_golden.json
- metadata-ingestion/tests/integration/snowflake/snowflake_privatelink_golden.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_add_known_query_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_basic_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_column_lineage_deduplication.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_overlapping_inserts.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_table_rename.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_temp_table.json
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_view_lineage.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_utils.py
> feat(ingest): add query formatting to sql aggregator

- docs/advanced/monitoring.md
> docs(monitoring): add health check endpoint

- metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/siblings/SiblingAssociationHook.java
> feat(gms): add aspect name to siblings hook log

- .github/workflows/pr-labeler.yml
> feat(ci): exempt more names from community

- metadata-ingestion/src/datahub/cli/check_cli.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic.py
- metadata-ingestion/src/datahub/sql_parsing/schema_resolver.py
- metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
- metadata-ingestion/tests/unit/redshift_query_mocker.py
- metadata-ingestion/tests/unit/sql_parsing/aggregator_goldens/test_overlapping_inserts_from_temp_tables.json
- metadata-ingestion/tests/unit/sql_parsing/test_sql_aggregator.py
> fix(ingest/redshift): tweak lineage v2 queries

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_2_16.md
> docs(acryl-cloud): notes for 0.2.16

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/ingestion/source/state/stateful_ingestion_base.py
> fix(ingest): only auto-enable stateful ingestion if pipeline name is set

- metadata-ingestion/scripts/docgen.sh
- metadata-ingestion/src/datahub/ingestion/source/s3/source.py
- metadata-ingestion/tests/integration/s3/test_s3.py
> feat(ingest/s3): set default spark version

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
> feat(ingest): better rest emitter error message

- metadata-ingestion/as-a-library.md
This guide is confusing for hosted customers and a common source of pain. Adding context.
> docs(sdk): Update API guide with example for Acryl

- metadata-ingestion-modules/airflow-plugin/tests/unit/test_packaging.py
- metadata-ingestion/src/datahub/ingestion/source/delta_lake/source.py
- metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
- metadata-ingestion/src/datahub/testing/check_imports.py
- metadata-ingestion/tests/unit/test_packages.py
> feat(ingest): check for private import path usages

- metadata-ingestion/src/datahub/cli/check_cli.py
- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_lineage_v2.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
> feat(ingest): add sql formatter utility

- metadata-ingestion/src/datahub/configuration/common.py
- metadata-ingestion/src/datahub/configuration/source_common.py
- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/config.py
- metadata-ingestion/src/datahub/ingestion/source/redshift/redshift.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_config.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_utils.py
> feat(ingest): refactor LineageConfig class

- docs/api/tutorials/domains.md
- docs/domains.md
- metadata-ingestion/examples/library/create_nested_domain.py
> Update domains docs to include nested domains

- metadata-io/src/main/java/com/linkedin/metadata/search/LineageSearchService.java
> fix(lineage): fix array out of bounds error

- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> Add rate limiting to slack source

- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/config.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/testing/check_imports.py
- metadata-ingestion/tests/integration/powerbi/golden_test_admin_access_not_allowed.json
- metadata-ingestion/tests/integration/powerbi/golden_test_admin_only.json
- metadata-ingestion/tests/integration/powerbi/golden_test_cll.json
- metadata-ingestion/tests/integration/powerbi/golden_test_container.json
- metadata-ingestion/tests/integration/powerbi/golden_test_disabled_ownership.json
- metadata-ingestion/tests/integration/powerbi/golden_test_endorsement.json
- metadata-ingestion/tests/integration/powerbi/golden_test_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_lineage.json
- metadata-ingestion/tests/integration/powerbi/golden_test_lower_case_urn_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_most_config_and_modified_since_admin_only.json
- metadata-ingestion/tests/integration/powerbi/golden_test_platform_instance_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_report.json
- metadata-ingestion/tests/integration/powerbi/golden_test_scan_all_workspaces.json
- metadata-ingestion/tests/integration/powerbi/golden_test_server_to_platform_instance.json
- metadata-ingestion/tests/integration/powerbi/test_powerbi.py
> feat(ingest/powerbi): add chart subtypes

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/source/gc/datahub_gc.py
Currently only for cleaning up expired tokens but can be used for more later.
> feat(ingest/datahub-gc): gc source to cleanup things

- docs/managed-datahub/release-notes/v_0_2_14.md
- docs/managed-datahub/release-notes/v_0_2_15.md
- docs/managed-datahub/release-notes/v_0_2_16.md
> docs(acryl-cloud): fix year in notes from 2023 to 2024

- docs-website/docusaurus.config.js
> docs: add gtm tag 

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/transformer/pattern_cleanup_ownership.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> fix(ingestion/transformer): added new transformer to cleanup suffix/prefix in owner URN

- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
> fix(metrics): get fieldName for GraphQL Mutation queries

- .github/actions/ci-optimization/action.yml
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/glossary/AddRelatedTermsResolver.java
> ci(filters): add graphql code to backend trigger

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/elasticsearch/steps/DataHubStartupStep.java
> log(system-update): Update DataHubStartupStep.java

- .github/actions/ci-optimization/action.yml
- metadata-operation-context/src/main/java/io/datahubproject/metadata/context/SearchContext.java
- metadata-operation-context/src/test/java/io/datahubproject/metadata/context/SearchContextTest.java
> fix(searchContext): fix search flag immutability

- .github/workflows/documentation.yml
- vercel.json
> fix(docs): fix docs build

- metadata-ingestion/setup.py
> feat(ingest): loosen pyarrow dep

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
> fix(ingest/dbt): respect `convert_column_urns_to_lowercase` in mapping CLL

- datahub-web-react/src/app/entity/shared/tabs/Incident/components/IncidentListItem.tsx
> feat(incidents) incident resolution note more clearly displayed

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_usage.py
Also changes lastModified to not fall back to created at.
> feat(ingest/bigquery): improve debug logs

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/util/MappingUtil.java
> fix(openapi): fix system-metadata response

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
> add row type for athena types

- .github/workflows/airflow-plugin.yml
- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_plugin.py
> feat(ingest/airflow): allow plugin to load on listener exception

- docs-website/src/pages/_components/Section/index.js
> docs(website): tweak eyebrow copy

- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ElasticSearchGraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/GraphRelationshipMappingsBuilder.java
- metadata-service/services/src/main/java/com/linkedin/metadata/graph/Edge.java
> fix(search): fix field name in api

- .github/actions/ci-optimization/action.yml
- .github/scripts/docker_helpers.sh
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/build.gradle
> build(docker): prefix pr on pr sha tags

- docker/docker-compose-without-neo4j.override.yml
- docker/docker-compose.override.yml
- docker/mysql/docker-compose.mysql.yml
- docker/quickstart/docker-compose-without-neo4j.quickstart.yml
- docker/quickstart/docker-compose.quickstart.yml
- docker/quickstart/quickstart_version_mapping.yaml
- metadata-ingestion/src/datahub/cli/quickstart_versioning.py
- metadata-ingestion/tests/unit/cli/test_quickstart_version_mapping.py
> fix(docker): fix versioning for compose file post release

- datahub-web-react/src/app/ingest/source/builder/RecipeForm/TestConnection/types.ts
> feat(ui): show classification in test connection

- metadata-ingestion/setup.py
> fix(ingest): add classification dep for dynamodb

- .github/workflows/docker-unified.yml
> fix(github): fix docker publish

- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
- metadata-ingestion/tests/integration/salesforce/mock_files/account_fields_soql_response.json
- metadata-ingestion/tests/integration/salesforce/salesforce_mces_golden.json
> fix(ingestion/salesforce): fixed the issue by escaping the markdown string

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_3_1.md
> saas release v0.3.1 release notes

- metadata-ingestion/setup.py
> fix(ingest/databricks): pin pandas for databricks ingestion

- build.gradle
- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/PluginFactory.java
> bump(version): bump classgraph version, add early package filter

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/lineage.py
> feat(ingest/bigquery): fix support for incremental column lineage

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
- metadata-ingestion/tests/unit/test_dbt_source.py
> fix(ingest/dbt): better dbt timestamp parsing

- docs-website/src/components/Feedback/styles.module.scss
> docs: fix feedback button design

- docs-website/docusaurus.config.js
> docs: edit the text and destination for sign up link

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> fix(ingestion/airflow-plugin): ingesting the tags along with the data

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_lineage.py
> fix(ingest): suppress all column-level parsing errors

- .github/actions/docker-custom-build-and-push/action.yml
- .github/workflows/docker-unified.yml
> chore(build): bump actions versions

- metadata-ingestion/src/datahub/ingestion/glossary/classification_mixin.py
- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
- metadata-ingestion/src/datahub/ingestion/source/sql/sqlalchemy_data_reader.py
> fix(ingest): avoid requiring sqlalchemy for dynamodb classification

- docs/cli.md
> docs(cli/init): make datahub init docs more clear

- metadata-ingestion/src/datahub/ingestion/source/redshift/query.py
> feat(ingest/redshift): filter out system queries from usage

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GraphQLEngine.java
- metadata-ingestion/src/datahub/ingestion/graph/client.py
- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
> feat(gql): support operationName

- datahub-frontend/run/run-local-frontend
- datahub-frontend/run/run-local-frontend-debug
> fix(frontend): fix frontend script used in release checklist

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> fix(airflow): disable OL regardless of plugin status

- metadata-ingestion/src/datahub/ingestion/source/salesforce.py
> fix(ingestion/salesforce): added additional check for description

- docs/managed-datahub/datahub-api/entity-events-api.md
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/DatasetPropertiesChangeEventGenerator.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/EditableDatasetPropertiesChangeEventGenerator.java
> feat(api): Add description parameter to editable dataset change entity event

- .github/workflows/publish-datahub-jars.yml
> fix publish-datahub-jars workflow

- metadata-ingestion/src/datahub/ingestion/source/unity/source.py
> fix(ingest/unity): Fix bug around unity notebook ingestion

- metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py
- metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
- metadata-ingestion/src/datahub/api/entities/forms/forms.py
- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
Follow up on https://github.com/datahub-project/datahub/pull/10256
> feat(cli): Make yaml loaders compatible with pydantic v2

- metadata-ingestion/src/datahub/api/entities/structuredproperties/structuredproperties.py
> fix(ingest): support pydantic v2 with properties subcommand

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
- metadata-ingestion/src/datahub/api/entities/datajob/datajob.py
- metadata-ingestion/src/datahub/api/entities/dataprocess/dataprocess_instance.py
> fix(ingestion/airflow-plugin): replace deprecated calls

- docs/managed-datahub/operator-guide/setting-up-remote-ingestion-executor-on-aws.md
> Update datahub-executor docs

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/util/MappingUtil.java
> fix(openapi): fix structured properties mapping

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtilsTest.java
> fix(authorization): fix restricted entity privmitives

- datahub-web-react/src/app/search/sidebar/BrowseNode.tsx
- datahub-web-react/src/app/search/sidebar/BrowseSidebar.tsx
- datahub-web-react/src/app/search/sidebar/EntityNode.tsx
- datahub-web-react/src/app/search/sidebar/EnvironmentNode.tsx
- datahub-web-react/src/app/search/sidebar/PlatformNode.tsx
- datahub-web-react/src/app/search/sidebar/useSort.ts
> feat(ui/folder-structure-sort): sort folder structure alphabetically

- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/tests/integration/powerbi/golden_test_admin_access_not_allowed.json
- metadata-ingestion/tests/integration/powerbi/golden_test_admin_only.json
- metadata-ingestion/tests/integration/powerbi/golden_test_cll.json
- metadata-ingestion/tests/integration/powerbi/golden_test_container.json
- metadata-ingestion/tests/integration/powerbi/golden_test_disabled_ownership.json
- metadata-ingestion/tests/integration/powerbi/golden_test_endorsement.json
- metadata-ingestion/tests/integration/powerbi/golden_test_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_lineage.json
- metadata-ingestion/tests/integration/powerbi/golden_test_lower_case_urn_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_most_config_and_modified_since_admin_only.json
- metadata-ingestion/tests/integration/powerbi/golden_test_platform_instance_ingest.json
- metadata-ingestion/tests/integration/powerbi/golden_test_report.json
- metadata-ingestion/tests/integration/powerbi/golden_test_scan_all_workspaces.json
- metadata-ingestion/tests/integration/powerbi/golden_test_server_to_platform_instance.json
> fix(ingestion/powerbi): patch column lineage for powerbi report

- docs-website/docusaurus.config.js
> fix: revert signup page

- metadata-ingestion/examples/mce_files/bootstrap_mce.json
> feat: add posts to quickstart sample data

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/transformer/replace_external_url.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> fix(ingestion/transformer): tranformer to replace the externalUrl in dataset properties

- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/api/incremental_lineage_helper.py
- metadata-ingestion/src/datahub/ingestion/source/powerbi/powerbi.py
- metadata-ingestion/src/datahub/testing/check_imports.py
> fix(ingest): disallow src.* imports, fix powerbi/sigma

- docker/kafka-setup/Dockerfile
> chore(docker): bump kafka docker base image

- metadata-ingestion/setup.py
> chore(pyiceburg): set minimum version

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
- metadata-ingestion/tests/unit/test_tableau_source.py
> fix(ingest/tableau): handle very large filter queries

- metadata-ingestion/src/datahub/utilities/logging_manager.py
> feat(ingest): mark acryl cloud package first-party for logging

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
> fix(ingest/bigquery): set default `max_overflow` to -1

- metadata-service/auth-impl/src/main/java/com/datahub/authorization/DataHubAuthorizer.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/DataPlatformInstanceFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/DomainFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/EntityUrnFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/GroupMembershipFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/OwnerFieldResolverProvider.java
- metadata-service/auth-impl/src/main/java/com/datahub/authorization/fieldresolverprovider/TagFieldResolverProvider.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/DataPlatformInstanceFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/DomainFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/EntityFieldResolverProviderBaseTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/EntityUrnFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/GroupMembershipFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/OwnerFieldResolverProviderTest.java
- metadata-service/auth-impl/src/test/java/com/datahub/authorization/fieldresolverprovider/TagFieldResolverProviderTest.java
> fix(auth-impl): handle empty entities in field resolver providers

- metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
@hsheth2 Related to datahub-project/datahub#10326
> fix(ingest/starburst): parse create_time datetime format

- metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
- metadata-ingestion/tests/integration/sigma/golden_test_platform_instance_ingest.json
- metadata-ingestion/tests/integration/sigma/golden_test_sigma_ingest.json
- metadata-ingestion/tests/integration/sigma/test_sigma.py
> test(ingestion/sigma): Add integration test cases

- metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/CacheConfig.java
> fix(hazelcast): fix cache value classloading

- docs/businessattributes.md
> docs(business-attribute):add info businessAttributeEntityEnable flag

- metadata-ingestion/src/datahub/emitter/mce_builder.py
- metadata-ingestion/src/datahub/utilities/mapping.py
- metadata-ingestion/tests/unit/test_mapping.py
> feat(ingest/dbt): support a `datahub` section in meta mappings

- docs/managed-datahub/observe/assertions.md
- docs/managed-datahub/observe/column-assertions.md
- docs/managed-datahub/observe/custom-sql-assertions.md
- docs/managed-datahub/observe/freshness-assertions.md
- docs/managed-datahub/observe/volume-assertions.md
> docs(observe): update docs for remote executor, databricks

- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_log_api.py
- metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran_query.py
- metadata-ingestion/tests/integration/fivetran/test_fivetran.py
> perf(ingestion/fivetran): Connector performance optimization

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
- metadata-ingestion/src/datahub/utilities/hive_schema_to_avro.py
> fix(ingest): map bigquery nested types properly

- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
> feat(search): allow overriding case-sensitivity to zero

- .github/workflows/docker-unified.yml
> fix(ci): add labeled to list of pr types for ci

- datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java
- datahub-frontend/app/client/AuthServiceClient.java
- datahub-frontend/app/controllers/AuthenticationController.java
- metadata-service/auth-servlet-impl/src/main/java/com/datahub/auth/authentication/AuthServiceController.java
- Log messages for successful and failed login attempts
- Log messages whenever a new session token is generated
> feat(auth): improve authentication flow logging

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/AbstractMCLStep.java
> fix(upgrade): fix upgrade npe

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py
- metadata-ingestion/tests/integration/mysql/docker-compose.yml
- metadata-ingestion/tests/unit/test_bigquery_source.py
> fix(ingest/bigquery): remove last modified timestamp fallback

- docs-website/docusaurus.config.js
> docs: fix blog link

- metadata-ingestion/src/datahub/ingestion/api/ingestion_job_checkpointing_provider_base.py
- metadata-ingestion/src/datahub/ingestion/run/pipeline.py
- metadata-ingestion/src/datahub/ingestion/source/state/stale_entity_removal_handler.py
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state_after_deleted.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state_after_deleted_failure.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_checkpoint_state_failure.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion_after_deleted_failure.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/golden_test_stateful_ingestion_failure.json
- metadata-ingestion/tests/unit/stateful_ingestion/state/test_stateful_ingestion.py
> feat(ingestion): Copy urns from previous checkpoint state on ingestion failure

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
> remove value from aspect request schemas

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/IngestionResolverUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateIngestionExecutionRequestResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
- datahub-graphql-core/src/main/resources/ingestion.graphql
- datahub-web-react/src/graphql/ingestion.graphql
- metadata-models/src/main/pegasus/com/linkedin/execution/ExecutionRequestInput.pdl
actor urn not present initially 
actor Urn after the change is done and manual execution is done
after change manual run
after change scheduled run
> feat(ingest): add actorUrn for ingestion through UI

- metadata-ingestion/src/datahub/utilities/urn_encoder.py
> perf(ingest): speed up urn encode happy path

- metadata-ingestion/cli-ingestion.md
Fixed typo + made things clearer (imho)
> docs(ingest): fix typos and clarify ingestion recipe docs

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
> Adding nullable to open api models

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
> fix(ingest/dbt): failures due to API change

- metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_mces_golden.json
- metadata-ingestion/tests/integration/kafka-connect/kafka_connect_to_file.yml
- metadata-ingestion/tests/integration/kafka-connect/setup/connect.env
- metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
> fix(ingestion/kafka-connect): fixed the issue with ingestion requiring multiple substitutes

- metadata-ingestion/src/datahub/ingestion/api/source.py
This makes debugging some aspect generation easier to do.
> feat(ingest/cli): add some URNs per aspect for easier debugging

- entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/PluginFactory.java
> fix(entity-registry): fix plugin load error

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v2/controller/EntityController.java
> fix(openapi): fix lookupAspectSpec

- README.md
- docs/slack.md
- metadata-ingestion/docs/dev_guides/profiling_ingestions.md
- metadata-ingestion/docs/dev_guides/sql_profiles.md
- metadata-ingestion/docs/sources/hana/hana.md
- metadata-ingestion/sink_docs/console.md
- metadata-ingestion/sink_docs/file.md
> docs: fix docs utms & slack footer

- datahub-frontend/app/auth/AuthModule.java
- datahub-frontend/conf/application.conf
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/AbstractMCLStep.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/AspectsBatch.java
- entity-registry/src/main/java/com/linkedin/metadata/aspect/batch/ChangeMCP.java
- li-utils/src/main/java/com/datahub/util/RecordUtils.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/AspectsBatchImpl.java
- metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ChangeItemImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/client/JavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/client/SystemJavaEntityClient.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/test/java/com/linkedin/metadata/client/JavaEntityClientTest.java
- metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SampleDataFixtureConfiguration.java
- metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SearchLineageFixtureConfiguration.java
- metadata-jobs/mce-consumer-job/src/test/java/com/linkedin/metadata/kafka/MceConsumerApplicationTestConfiguration.java
- metadata-service/configuration/src/main/resources/application.yaml
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityclient/JavaEntityClientFactory.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityclient/RestliEntityClientFactory.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/RestliEntityClient.java
- metadata-service/restli-client/src/main/java/com/linkedin/entity/client/SystemRestliEntityClient.java
- metadata-service/restli-client/src/test/java/com/linkedin/common/client/BaseClientTest.java
- metadata-service/restli-client/src/test/java/com/linkedin/entity/client/SystemRestliEntityClientTest.java
- metadata-service/services/src/main/java/com/linkedin/metadata/service/BaseService.java
* logging updates
* entity client batching
* remove restore indices from mcp update
> fix(misc): misc fixes for OSS release

- metadata-ingestion/docs/transformer/dataset_transformer.md
- metadata-ingestion/setup.py
- metadata-ingestion/src/datahub/ingestion/transformer/dataset_domain_based_on_tags.py
- metadata-ingestion/tests/unit/test_transform_dataset.py
> fix(ingestion/transformer): Add dataset domains based on tags using transformer

- docs-website/sidebars.js
> fix(ci): documentation build fix

- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/restoreindices/SendMAEStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/AbstractMCLStep.java
- datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/elasticsearch/steps/BuildIndicesPreStep.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/PartitionedStream.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanAspectMigrationsDaoTest.java
- metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
- metadata-jobs/mce-consumer-job/src/test/java/com/linkedin/metadata/kafka/MceConsumerApplicationTest.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/OperationsController.java
- metadata-service/restli-servlet-impl/src/main/java/com/linkedin/metadata/resources/operations/Utils.java
- metadata-service/services/src/main/java/com/linkedin/metadata/entity/EntityService.java
> fix(ebean): fix auto-closeable ebean dao streams

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_profiler.py
> fix(ingest/snowflake): use block sampling more conservatively

- docs-website/sidebars.js
- metadata-ingestion/src/datahub/ingestion/graph/client.py
> feat(sdk): add DataHubGraph.get_timeseries_values() method

- docs/managed-datahub/release-notes/v_0_3_2.md
> docs: update cli recommendation

- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
- metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
Ran `./gradlew :metadata-service:openapi-servlet:spotlessApply` to address formatting issues.
> Fix formatting for #10514

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_report.py
> fix(ingestion/snowflake): fix dataclass defaults for SnowflakeReport

- metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
- metadata-io/src/main/java/com/linkedin/metadata/service/BusinessAttributeUpdateHookService.java
> feat(neo4j): neo4j pagination as per v2 scrollApi for related entities

- docs-website/sidebars.js
- docs/_api-guide-template.md
> docs: add api templates

- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
- metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py
- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
- metadata-ingestion/tests/unit/sql_parsing/test_sql_detach.py
> fix(ingest/dbt): improve handling for CLL via ephemeral nodes

- metadata-ingestion/setup.py
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_expand_select_star_basic.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_postgres_select_subquery.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_postgres_update_subselect.json
- metadata-ingestion/tests/unit/sql_parsing/goldens/test_redshift_system_automove.json
- metadata-ingestion/tests/unit/sql_parsing/test_sqlglot_lineage.py
> feat(ingest): bump acryl-sqlglot dep

- metadata-ingestion/src/datahub/ingestion/api/source.py
- metadata-ingestion/src/datahub/ingestion/api/source_helpers.py
> feat(ingest): auto-fix duplicate schema fieldPaths

- metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_extractors.py
Fixes https://datahubspace.slack.com/archives/CUMUWQU66/p1715954177158679?thread_ts=1712847298.005519&cid=CUMUWQU66
> fix(ingest/airflow): fix support for bigquery insert job operator

- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/integration/mode/mode_mces_golden.json
> fix(ingest/mode): Adding Dashboards into containers

- li-utils/src/main/javaPegasus/com/linkedin/common/urn/UrnUtils.java
> fix(lint): fix linting

- metadata-integration/java/custom-plugin-lib/build.gradle
Enable publishing a jar which contains dependencies for developing custom plugins for validators, mutators, side-effects.
> build(jar): enable custom plugin lib

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
> fix(instropection): fix configuration application order

- metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
> fix(ingest/slack): pull real names

- docs/how/updating-datahub.md
> docs(update): updating-datahub

- metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/common.py
Follow up on https://github.com/datahub-project/datahub/pull/10573
> fix(ingest/sagemaker): remove unsupported config

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
> fix(ingest/snowflake): make test connection logs less noisy

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/datacontract/DataContractUtils.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/datacontract/EntityDataContractResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/datacontract/UpsertDataContractResolver.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datacontract/DataContractMapper.java
- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datacontract/DataContractType.java
- datahub-graphql-core/src/main/resources/contract.graphql
- datahub-graphql-core/src/main/resources/entity.graphql
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/datacontract/DataContractUtilsTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/datacontract/EntityDataContractResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/datacontract/UpsertDataContractResolverTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/datacontract/DataContractMapperTest.java
- datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/datacontract/DataContractTypeTest.java
- li-utils/src/main/java/com/linkedin/metadata/Constants.java
- metadata-models/src/main/pegasus/com/linkedin/assertion/FreshnessAssertionSchedule.pdl
- metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
> feat(graphql) data contract resolvers for graphql

- metadata-ingestion/src/datahub/cli/delete_cli.py
When deleting a form through the CLI, auto delete all references as well.
> feat(cli) Delete form references when using delete CLI

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
Fixes https://github.com/datahub-project/datahub/issues/10623
> feat(ingest/looker): add ownership info to independent looks

- metadata-service/plugin/src/main/java/com/datahub/plugins/metadata/aspect/SpringPluginFactory.java
> log(custom-plugins): add additional logging for spring plugins

- datahub-web-react/src/app/entity/shared/EntityDropdown/useDeleteEntity.tsx
> refactor(ui/glossary): Clean up term deletion

- datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ResolverUtils.java
> fix(views): handle unknown view when resolving a view to a filter

- docs/lineage/airflow.md
- metadata-ingestion/developing.md
> fix(ingestion/airflow-plugin): updated the document for developers

- .github/actions/ci-optimization/action.yml
- .github/workflows/docker-unified.yml
> feat(ci): fix conditionals and consolidate change detection

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
> fix(ingest/snowflake): avoid overfetching schemas from datahub

- docs/api/tutorials/tags.md
> docs: add note for subResourceType being a fieldPath

- metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
Useful for debugging authorization errors.
> fix(azure_ad): print request URL on error

- docs/cli.md
- metadata-ingestion/examples/cli_usage/dataset/dataset.yaml
> docs(cli/dataset): add dataset CLI get and upsert examples

- metadata-ingestion/src/datahub/emitter/rest_emitter.py
- metadata-ingestion/src/datahub/entrypoints.py
> feat(ingest/cli): optionally show server config

- datahub-web-react/src/app/lineage/__tests__/manageLineage.test.tsx
- datahub-web-react/src/app/lineage/manage/AddEntityEdge.tsx
> fix: APPT-43 | Lineage Edit: Modal Autocomplete

- datahub-web-react/src/app/ingest/source/builder/NameSourceStep.tsx
> chore(ui/ingest): improve description of executor ID

- metadata-ingestion/docs/sources/oracle/oracle_pre.md
> docs(ingest): Add Oracle prerequisites

- metadata-ingestion-modules/dagster-plugin/src/datahub_dagster_plugin/__init__.py
> fix(ingest): fix dagster plugin release process

- metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator_no_dag_listener.json
> fix(ingestion/airflow-plugin): fixed the failing pipeline

- build.gradle
- datahub-upgrade/build.gradle
- docker/datahub-gms/Dockerfile
- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-mae-consumer/Dockerfile
- docker/datahub-mce-consumer/Dockerfile
- docker/datahub-upgrade/Dockerfile
- docker/elasticsearch-setup/Dockerfile
- docker/mysql-setup/Dockerfile
- docker/postgres-setup/Dockerfile
- metadata-integration/java/datahub-client/build.gradle
> chore(security): updates for security vulnerabilities

- docker/datahub-gms/Dockerfile
- docker/datahub-upgrade/Dockerfile
> chore(security): bump jetty version

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py
> feat(ingest/snowflake): log queries at info level

- docs/managed-datahub/subscription-and-notification.md
> docs(notifications): add personal notifications docs

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
> fix(ingest/tableau): warn with better error message

- datahub-frontend/app/controllers/Application.java
- metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/controller/GenericEntitiesController.java
> fix(media-type): fix proxy media-type and openapi patch endpoint

- metadata-jobs/mae-consumer-job/build.gradle
- metadata-jobs/mae-consumer-job/src/test/java/com/linkedin/metadata/kafka/MaeConsumerApplicationTest.java
> test(mae-consumer): test for injection of pe-consumer

- metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/config/DatahubOpenlineageConfig.java
- metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/converter/OpenLineageToDataHub.java
- metadata-integration/java/spark-lineage-beta/README.md
- metadata-integration/java/spark-lineage-beta/src/main/java/datahub/spark/conf/SparkConfigParser.java
- metadata-integration/java/spark-lineage-beta/src/test/java/datahub/spark/OpenLineageEventToDatahubTest.java
> fix(spark):Add option to disable symlink resolution

- metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/config/DatahubOpenlineageConfig.java
- metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/converter/OpenLineageToDataHub.java
- metadata-integration/java/spark-lineage-beta/src/main/java/datahub/spark/conf/SparkConfigParser.java
- metadata-integration/java/spark-lineage-beta/src/test/java/datahub/spark/OpenLineageEventToDatahubTest.java
> chore(lint): spotless apply

- metadata-ingestion/src/datahub/sql_parsing/sqlglot_utils.py
> fix(ingest): use more aggressive errors with sqlglot

- datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
Closes https://github.com/datahub-project/datahub/issues/10720
> fix(ui/entityProfile/dataset): Show view definition tab if viewProperties.logic defined

- metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_query.py
- metadata-ingestion/src/datahub/utilities/prefix_batch_builder.py
- metadata-ingestion/tests/integration/snowflake/common.py
- metadata-ingestion/tests/unit/utilities/test_prefix_patch_builder.py
Follow up on https://github.com/datahub-project/datahub/pull/10746.
Also removes some dead code - queries that are no longer used.
> fix(ingest/snowflake): fix column batcher

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_3_3.md
> docs(acryl cloud): release 0.3.3

- docs-website/src/pages/champions/index.js
> docs(champions): update champions entry

- metadata-ingestion/src/datahub/ingestion/source/looker/looker_source.py
> fix(ingest/looker): prevent bad input fields

- datahub-web-react/src/app/entity/chart/ChartEntity.tsx
- datahub-web-react/src/app/entity/chart/ChartQueryTab.tsx
> feat(ui): display chart query if it exists

- metadata-models/docs/entities/dataset.md
> fix(docs) adding dataset column tags docs

- docs-website/src/pages/_components/Logos/index.js
- docs-website/src/pages/_components/Logos/logos.module.scss
> fix: fix customer logo alignment and make responsive

- datahub-frontend/app/controllers/SsoCallbackController.java
- metadata-service/graphql-servlet-impl/src/main/java/com/datahub/graphql/GraphQLController.java
---
CodeQL scans detect high vulnerability in the code base. Its due to logging user inputs. We are logging the error instead of the json. CodeQL detects it as vulnerability and by resolving this, the overall vulnerabilty score improves. And it had no impacts.
> chore(vulnerability): Log Injection

- metadata-service/auth-filter/src/main/java/com/datahub/auth/authentication/filter/AuthenticationFilter.java
CodeQL scans detect high vulnerability in the code base. Its due to Information exposure through a stack trace. We are sending a clean message to the end-user. CodeQL detects it as vulnerability and by resolving this, the overall vulnerabilty score improves. And it had no impacts.
> chore(vulnerability): Information exposure through a stack trace

- metadata-models/src/main/pegasus/com/linkedin/dataset/PartitionSummary.pdl
> fix(models): fixing the datasetPartition models

- docs-website/src/pages/cloud/CompanyLogos/logos.module.scss
- docs-website/src/pages/cloud/index.js
- docs-website/src/pages/cloud/styles.module.scss
> feat(docs-site) cloud page spacing and content polishes

- smoke-test/requirements.txt
- smoke-test/tests/openapi/README.md
- smoke-test/tests/openapi/test_openapi.py
- smoke-test/tests/openapi/v1/timeline.json
- smoke-test/tests/openapi/v2/structured_properties.json
- smoke-test/tests/openapi/v2/timeline.json
- smoke-test/tests/openapi/v3/structured_properties.json
This test is configuration driven by json files which contain request/response sequences intended to
detect unexpected regressions between releases.
Files can be executed in parallel but each request within the file is sequential.
Create a file for a given OpenAPI version which contains a list of request/response pairs in the following
format.
The request json object is translated into the python request arguments and the response object is the
expected status code and optional body.
```json
[
{
"request": {
"urn": "",
"description": "",
"method": "",
"json": {}
},
"response": {
"status_codes": [200],
"exclude_regex_paths": [],
"json": {}
}
}
]
```
> test(openapi): openapi regression smoke tests

- .github/actions/ci-optimization/action.yml
- .github/actions/docker-custom-build-and-push/action.yml
> fix(ci): smoke-test changes do not need to build images

- .github/actions/docker-custom-build-and-push/action.yml
> fix(ci): fix single tag comma split

- .github/actions/docker-custom-build-and-push/action.yml
> fix(ci): typo

- docker/kafka-setup/Dockerfile
> fix(kafka-setup): add missing script to image

- metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataService.java
- metadata-io/src/test/java/com/linkedin/metadata/systemmetadata/SystemMetadataServiceTestBase.java
- metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/ElasticSearchSystemMetadataServiceFactory.java
> fix(config): fix hash algo config

- .github/workflows/docker-unified.yml
> ci(smoke-test): allow smoke-test only PRs

- README.md
> docs(readme): add security notes

- metadata-ingestion/src/datahub/ingestion/source/tableau.py
- metadata-ingestion/src/datahub/ingestion/source/tableau_common.py
- metadata-ingestion/tests/unit/test_tableau_source.py
> fix(ingestion/tableau): Tableau field type parsing

- build.gradle
- datahub-upgrade/build.gradle
> chore(bump): bump hadoop and dnsjava versions

- build.gradle
> chore(bump): update graphql & spring version

- metadata-ingestion/src/datahub/configuration/source_common.py
> docs(ingest): update config docs on platform instances

- docker/kafka-setup/Dockerfile
> chore(bump): bump kafka base image

- docker/datahub-frontend/env/docker.env
> fix(datahub-frontend): remove old test creds

- docs/deploy/confluent-cloud.md
Removed duplicated kafka topic reference (MetadataGraphEvent_v4)
> docs: Update confluent-cloud.md

- README.md
- docs-website/sidebars.js
- docs/SECURITY_STANCE.md
> docs(update): Security stance docs.md

- metadata-ingestion/setup.py
> chore(bump): bump azure-identity

- docs/authorization/roles.md
- docs/managed-datahub/subscription-and-notification.md
> feat(docs): Update docs on managing user subscriptions

- docs/SECURITY_STANCE.md
> Rephrase scope of automated scanning

- metadata-ingestion/integration_docs/great-expectations.md
> docs: fix great-expectations doc module_name

- .github/workflows/pr-labeler.yml
> chore: update contributor list

- .github/workflows/docker-unified.yml
- docker/datahub-ingestion-base/Dockerfile
- docker/datahub-ingestion-base/build.gradle
- docker/datahub-ingestion/Dockerfile
- docker/datahub-ingestion/build.gradle
* upstream image is better maintained
* image size reduced 500MB
> feat(ingestion-base): convert to ubuntu image

- metadata-integration/java/acryl-spark-lineage/build.gradle
> fix(build/spark): Add explicit dependency to openlineage-converter

- docker/datahub-ingestion-base/Dockerfile
> fix(ingestion-base): add missing util

- docs-website/sidebars.js
- docs/managed-datahub/release-notes/v_0_3_5.md
> doc(acryl cloud): release notes for 0.3.5.x

- docs/authentication/guides/sso/configure-oidc-react.md
> fix(docs): fix logout url

- metadata-ingestion-modules/prefect-plugin/README.md
- metadata-ingestion-modules/prefect-plugin/setup.py
> fix(ingest/prefect): Temporary pinning Prefect 2.x until we can upgrade to 3.x

- metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> feat(ingest/athena): Add option to disable partition extraction

- README.md
Just add Adoption in `Readme.md`
> docs(adoption): Add Inter&Co

- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/ProtobufUtils.java
- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/model/ProtobufField.java
- metadata-integration/java/datahub-protobuf/src/main/java/datahub/protobuf/visitors/field/ProtobufExtensionFieldVisitor.java
- metadata-integration/java/datahub-protobuf/src/test/java/datahub/protobuf/ProtobufUtilsTest.java
- metadata-integration/java/datahub-protobuf/src/test/java/datahub/protobuf/model/ProtobufFieldTest.java
- metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
> fix(search): fix regression from #10932

- docs/how/updating-datahub.md
- metadata-ingestion/src/datahub/cli/get_cli.py
> feat(cli): reject missing urns in `datahub get`

- metadata-ingestion/docs/sources/dbt/README.md
- metadata-ingestion/src/datahub/ingestion/source/aws/aws_common.py
> docs(ingest/dbt): clarify dbt ingestion docs

- metadata-io/src/main/java/com/linkedin/metadata/entity/AspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/cassandra/CassandraAspectDao.java
- metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
* forUpdate is required for a read lock whenever calculating a version
> fix(version): forUpdate needed for versioning

- docs/authentication/guides/sso/configure-oidc-react.md
> docs(oidc): document azure logout uri

- metadata-ingestion/docs/sources/dbt/dbt.md
> docs(ingest/dbt): add docs on hiding sources

- metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
- metadata-ingestion/src/datahub/ingestion/source/mode.py
- metadata-ingestion/tests/integration/mode/mode_mces_golden.json
- metadata-ingestion/tests/integration/mode/setup/dataset_24f66e1701b6.json
- metadata-ingestion/tests/integration/mode/setup/dataset_queries_24f66e1701b6.json
- metadata-ingestion/tests/integration/mode/setup/datasets_157933cc1168.json
- metadata-ingestion/tests/integration/mode/setup/datasets_75737b70402e.json
- metadata-ingestion/tests/integration/mode/setup/reports_75737b70402e.json
- metadata-ingestion/tests/integration/mode/test_mode.py
> feat(mode/ingest): Add support for missing Mode datasets in lineage

- docs/how/updating-datahub.md
> docs(updating-datahub) Bump minor version on v0.14.0 notes

- metadata-ingestion/src/datahub/utilities/file_backed_collections.py
- metadata-ingestion/tests/unit/utilities/test_file_backed_collections.py
> feat(ingest): maintain ordering in file-backed dict

- metadata-service/war/src/main/resources/boot/retention.yaml
> config(retention): update dataHubExecutionRequestResult

- datahub-web-react/src/app/entity/shared/propagation/PropagationDetails.tsx
- datahub-web-react/src/app/settings/features/Features.tsx
> chore(links): add attribution

- metadata-io/src/main/java/com/linkedin/metadata/timeline/data/dataset/DatasetSchemaFieldChangeEvent.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/data/dataset/SchemaFieldModificationCategory.java
- metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGenerator.java
- metadata-io/src/test/java/com/linkedin/metadata/timeline/eventgenerator/SchemaMetadataChangeEventGeneratorTest.java
- smoke-test/tests/openapi/v1/timeline.json
- smoke-test/tests/openapi/v2/timeline.json
> fix(timeline api): adding modification category

- .github/workflows/airflow-plugin.yml
- .github/workflows/dagster-plugin.yml
- .github/workflows/gx-plugin.yml
- .github/workflows/metadata-ingestion.yml
- .github/workflows/prefect-plugin.yml
- metadata-ingestion-modules/airflow-plugin/build.gradle
- metadata-ingestion-modules/dagster-plugin/build.gradle
- metadata-ingestion-modules/gx-plugin/build.gradle
- metadata-ingestion-modules/prefect-plugin/build.gradle
> chore(py): cleanup python CI

- metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
* On some database failures null is found in the stream, filter it to avoid red herring stacktrace
> fix(NPE): fix NPE in EntityService

- docker/profiles/docker-compose.actions.yml
> chore(actions): bump actions version in docker profiles

- docs-website/src/pages/_components/Hero/index.js
> text animation update for the header component.

- metadata-ingestion/src/datahub/ingestion/source/nifi.py
> fix(ingest/nifi): add error handling for version

- docs-website/src/pages/_components/CaseStudy/case-study.module.scss
- docs-website/src/pages/_components/CaseStudy/caseStudyContent.js
- docs-website/src/pages/_components/CaseStudy/index.js
> Add Carousel for Case Study Section

- smoke-test/tests/tokens/revokable_access_token_test.py
> fix(smoke-test): add wait for sync to smoke-test

- metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema_gen.py
> fix(docs): Fix typo in bigquery permissions error

- docker/kafka-setup/kafka-config.sh
> feat(kafka-setup): allow override KAFKA_HEAP_OPTS
