web/app/controllers/api/v1/Lineage.java, web/app/dao/LineageDAO.java, web/conf/application.conf
Either configure in the application.conf.
Or pass through 'period' parameter in the API call.
=> Configurize lineage look back time

web/app/utils/Lineage.java
To enable hive lineage show up.
=> Add process for hive url in front end

web/app/dao/AdvSearchDAO.java, web/public/javascripts/routers/advancedSearch.js, web/public/javascripts/routers/search.js, web/public/javascripts/search.js
1. fix the advanced search schema invalid json issue
2. fix the field contains all no result cause exception issue
3. fix the advanced search can't launch from lineage page issue
=> fix advanced search issues

.travis.yml, backend-service/build.gradle, build.gradle, metadata-etl/build.gradle, metadata-etl/extralibs/readme.md, metadata-etl/src/main/resources/jython/TeradataExtract.py, web/build.gradle
Mysql and Jython lib can get from maven repository.
Teradata jar is reference through reflection, as long as don't run test on Teradata ETL module, it won't failed.
=> enable travis CI

hadoop-dataset-extractor-standalone/src/main/java/wherehows/SchemaFetch.java, metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java, wherehows-common/src/main/java/wherehows/common/Constant.java
For HDFS dataset metadata ETL, if it have a kerberos keytab location parameter, will try to login from Kerberos. Otherwise assume there is no security mechanisms.
=> Use Kerberos login

backend-service/app/actors/TreeBuilderActor.java, backend-service/app/models/daos/DatasetDao.java, metadata-etl/src/main/resources/jython/HdfsLoad.py, metadata-etl/src/main/resources/jython/HiveLoad.py
=> Fix dataset insert API bug. Fix load sql bug.

data-model/ELASTICSEARCH/index_mappings.md, data-model/build.gradle, metadata-etl/src/main/java/metadata/etl/elasticsearch/ElasticSearchBuildIndexETL.java, metadata-etl/src/main/java/metadata/etl/models/EtlJobFactory.java, metadata-etl/src/main/java/metadata/etl/models/EtlJobName.java, metadata-etl/src/main/resources/jython/DatasetTreeBuilder.py, metadata-etl/src/main/resources/jython/ElasticSearchIndex.py, metadata-etl/src/main/resources/jython/FlowTreeBuilder.py, metadata-etl/src/test/java/metadata/etl/elasticsearch/ElasticSearchBuildIndexEtlTest.java, web/app/controllers/api/v1/AdvSearch.java, web/app/controllers/api/v1/Dataset.java, web/app/controllers/api/v1/Search.java, web/app/dao/AdvSearchDAO.java, web/app/dao/DatasetsDAO.java, web/app/dao/SearchDAO.java, web/app/models/FlowJob.java, web/app/utils/Search.java, web/app/views/index.scala.html, web/app/views/main.scala.html, web/conf/application.conf, web/conf/routes, web/public/javascripts/controllers/datasets.js, web/public/javascripts/main.js, web/public/javascripts/routers/datasets.js, web/public/javascripts/routers/search.js, web/public/javascripts/search.js, web/public/stylesheets/main.css, wherehows-common/src/main/java/wherehows/common/Constant.java
If user want to use elasticsearch as search engine, please specify the search engine in application configuration file and add the elasticsearch index url
search.engine = "elasticsearch"
elasticsearch.dataset.url = $YOUR_DATASET_INDEX_URL
elasticsearch.flow.url = $YOUR_FLOW_INDEX_URL
=> support the elasticsearch as search engine

metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java, wherehows-common/src/main/java/wherehows/common/Constant.java
Set 'hdfs.remote' to true is remote mode.
Default false.
=> Add local mode for hdfs extract

.travis.yml, build.gradle, metadata-etl/src/main/resources/jython/AppworxExtract.py, web/app/controllers/api/v1/ScriptFinder.java, web/app/dao/ScriptFinderDAO.java, web/app/dao/ScriptInfoRowMapper.java, web/app/dao/ScriptLineageRowMapper.java, web/app/dao/ScriptRuntimeRowMapper.java, web/app/models/ScriptInfo.java, web/app/models/ScriptLineage.java, web/app/models/ScriptRuntime.java
- trigger travis-ci build with extralibs
- add license header to a few files
- include running chains from SO_JOB_QUEUE for Appworx
=> travis ci test + license header + SO_JOB_QUEUE for Appworx

backend-service/app/controllers/DatasetController.java, backend-service/app/models/daos/UserDao.java, backend-service/conf/routes
These changes brings in support to retrieve userName of the users who are watching the given dataset.
=> Fetching dataset watchers userName via get /dataset/watchers

web/public/javascripts/main.js, web/public/javascripts/routers/datasets.js, web/public/javascripts/routers/flows.js
List view need the dataset and flow root to go back to top level
=> add the dataset and flow root in the breadcrumb since list view need them

backend-service/app/controllers/DatasetController.java, backend-service/app/models/daos/UserDao.java, backend-service/conf/routes, data-model/DDL/ETL_DDL/dataset_metadata.sql, metadata-etl/src/main/resources/jython/HiveLoad.py
The table key changed for hold the different version info for datasets
=> update the dict_dataset_instance data loading sql

web/app/views/index.scala.html, web/public/javascripts/main.js, web/public/stylesheets/wherehows.css, web/public/vendors/fancytree/src/skin-wherehows/ui.wherehows.css
Steve updated the css to make list view and tree view have same look & feel
=> merge css change from Steve for navtree and listview

build.gradle
We met the no such method issue on akka-actor version 2.3.15, change the version to 2.3.5 to fix it
=> change the akka version to 2.3.5 to fix the no such method issue

web/app/controllers/api/v1/Metric.java, web/app/dao/MetricsDAO.java, web/app/models/MetricListViewNode.java, web/app/views/index.scala.html, web/conf/routes, web/public/javascripts/main.js, web/public/javascripts/routers/metrics.js
As same as datasets and flows in main branch
=> implement the list view for metrics

backend-service/app/controllers/DatasetController.java, backend-service/app/models/daos/DatasetDao.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetRecord.java, wherehows-common/src/main/java/wherehows/common/writers/DatabaseWriter.java
=> Modify /dataset POST method to perform INSERT or UPDATE of the DatasetRecord

web/app/controllers/api/v1/Dataset.java, web/app/dao/DatasetsDAO.java, web/app/views/index.scala.html, web/conf/routes, web/public/javascripts/routers/datasets.js, web/test/ControllersTest.java
Changed the "Depend On" section to "Relations" which includes depend on and referred by two sections.
=> implemented the referred by feature for dataset detail

web/app/dao/DatasetRowMapper.java
We should return the schema back to user for dataset api 
api/v1/datasets/88982 when there is no logged in user
=> fix the issue which dataset api returns empty schema when user is not logged in

web/app/dao/DatasetsDAO.java, web/app/views/index.scala.html, web/public/javascripts/routers/datasets.js, web/public/stylesheets/wherehows.css
=> merge the commit of wherehows datasets properties styling

backend-service/app/models/daos/CfgDao.java, build.gradle, data-model/DDL/ETL_DDL/etl_configure_tables.sql, data-model/DDL/ETL_DDL/kafka_tracking.sql
log_dataset_instance_load_status will track the dataset instance load/publish events (mainly gathered from Kafka events or other audit logs)
replace db_type_id with primary_dataset_type to map dataset URN to db_id in cfg_database in an easier way
=> add log_dataset_instance_load_status

backend-service/app/actors/KafkaConsumerMaster.java, backend-service/app/utils/KafkaConfig.java
Kafka Consumer Master first fetches the kafka job list from application.conf, then for each job in the list, it creates a consumer connection. When no such list or list is empty, the Master will stop. Error handling has been added to take exceptions.
=> Modify Kafka Master to handle more than one kafka config, add error handling

web/public/javascripts/test/datasets.js, web/public/javascripts/test/flows.js, web/public/javascripts/test/index.html, web/public/javascripts/test/qunit-2.0.1.css, web/public/javascripts/test/qunit-2.0.1.js, web/public/javascripts/test/schemaHistory.js
Using the Qunit as Ember 2.0 does to test the ui javascript code
=> add the ui test for javascript code

data-model/DDL/ETL_DDL/git_metadata.sql, data-model/DDL/ETL_DDL/kafka_tracking.sql, metadata-etl/src/main/resources/jython/MultiproductExtract.py, metadata-etl/src/main/resources/jython/MultiproductLoad.py, metadata-etl/src/main/resources/jython/OwnerLoad.py, metadata-etl/src/test/java/metadata/etl/git/MultiproductMetadataEtlTest.java, wherehows-common/src/main/java/wherehows/common/schemas/MultiproductRepoOwnerRecord.java
Use cfg_object_name_map table to find the mapping between repo and dataset for dalids. Then merge the repo owner info from ACL files into the dataset_owner table.
=> Map scm repo owner to dataset owner table

metadata-etl/src/main/java/metadata/etl/metadata/DatasetDescriptionEtl.java, metadata-etl/src/main/java/metadata/etl/models/EtlJobFactory.java, metadata-etl/src/main/java/metadata/etl/models/EtlJobName.java, metadata-etl/src/main/java/metadata/etl/security/DatasetConfidentialFieldEtl.java, metadata-etl/src/main/resources/jython/ConfidentialFieldLoad.py, metadata-etl/src/main/resources/jython/DatasetDescriptionLoad.py, metadata-etl/src/test/java/metadata/etl/metadata/DatasetDescriptionEtlTest.java, metadata-etl/src/test/java/metadata/etl/security/DatasetConfidentialFieldEtlTest.java, web/app/controllers/Application.java, web/app/controllers/api/v1/Dashboard.java, web/app/dao/DashboardDAO.java, web/app/models/ConfidentialFieldsOwner.java, web/app/models/DatasetConfidential.java, web/app/models/MetadataBarData.java, web/app/views/dashboard.scala.html, web/app/views/main.scala.html, web/conf/routes, web/public/javascripts/dashboard.js, web/public/stylesheets/main.css, web/public/vendors/d3pie-0.18/d3pie-customized.js, web/public/vendors/d3pie-0.18/d3pie.js
default the fields considered as confidential:  ["member_id", "memberid", "firstname", "first_name", "lastname", "last_name",  "email", "email_address", "emailaddress", "address", "birthday", "birth_day",                              "birthdate", "birth_date", "birth_month", "birthmonth", "birthyear", "birth_year", "ssn"]
=> metadata dashboard confidential field data collecting

backend-service/app/controllers/DatasetInfoController.java, backend-service/app/models/daos/DatasetInfoDao.java, backend-service/app/utils/MetadataInventoryProcessor.java, backend-service/conf/routes, data-model/DDL/ETL_DDL/dataset_info_metadata.sql, wherehows-common/src/main/java/wherehows/common/schemas/DatasetCaseSensitiveRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetChangeAuditStamp.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetInventoryItemRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetInventoryPropertiesRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetPropertiesRecord.java, wherehows-common/src/main/java/wherehows/common/utils/PreparedStatementUtil.java
1. Create Kafka processor for MetadataInventoryEvent, call the API with json.
2. API to handle MetadataInventoryEvent json and store info into dataset_inventory table.
=> Add MetadataInventoryEvent processor and API

backend-service/app/controllers/DatasetInfoController.java, backend-service/app/models/daos/DatasetInfoDao.java, web/app/controllers/api/v1/Dataset.java, web/conf/application.conf, web/conf/routes, wherehows-common/src/main/java/wherehows/common/schemas/AbstractRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetGeographicAffinityRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetLocaleRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetRetentionRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetSecurityRecord.java, wherehows-common/src/main/java/wherehows/common/utils/StringUtil.java
Support get and post
GET     /api/v1/datasets/:id/security
POST    /api/v1/datasets/:id/security
Will call the corresponding Backend-service API to process request.
=> Add REST proxy for Security API from backend to web

data-model/DDL/ETL_DDL/owner_metadata.sql, web/app/dao/DatasetOwnerRowMapper.java, web/app/dao/DatasetsDAO.java, web/app/models/DatasetOwner.java, web/app/views/index.scala.html, web/app/views/main.scala.html, web/public/javascripts/components/components.js
replace the isGroup column with Owner ID type and Owner source, and add the confirmed_by and confirmed_on two columns.
=> update the dataset ownership information

backend-service/app/actors/ConfigUtil.java, backend-service/app/actors/EtlJobActor.java, metadata-etl/src/main/resources/logback.xml
each ETL job will has its own log file, e.g. ORACLE_DATASET_METADATA_ETL.log
=> logback redirect ETL job logs into corresponding files

metadata-etl/src/main/resources/jython/LdapTransform.py
Sometimes there may be errors in LDAP, in case a user's manager is his/herself, the code to figure out the org hierarchy will go into infinite loop.
This patch will address such issue.
=> avoid loop in LDAP org hierarchy

backend-service/app/models/daos/DatasetInfoDao.java, backend-service/app/utils/MetadataChangeProcessor.java, data-model/DDL/ETL_DDL/dataset_info_metadata.sql, data-model/DDL/create_all_tables_wrapper.sql, data-model/avro/MetadataChangeEvent.avsc, data-model/avro/MetadataInventoryEvent.avsc, metadata-etl/src/main/resources/jython/MultiproductLoad.py, wherehows-common/src/main/java/wherehows/common/enums/OwnerType.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetDeploymentRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetEntityRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetFieldSchemaRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetKeySchemaRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetOriginalSchemaRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetOwnerRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionKeyRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetSchemaInfoRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetSecurityRecord.java
New MetadataChangeEvent.avsc is updated with this commit.
1. Modify dataset identify process, try datasetId first, then URI in datasetProperties, then URN.
2. Update dataset owner merge process, new Owner Type (Category), also fix merge bugs
3. Modify dataset security info section according to schema change
4. Other small updates.
=> Update MetadataChangeEvent APIs according to schema change

data-model/DDL/ETL_DDL/etl_configure_tables.sql, metadata-etl/src/main/resources/jython/ElasticSearchIndex.py, web/app/dao/SearchDAO.java
This check in is for using function_score from elastic search to improve the search ranking. I scheduled the table boost value update together with elastic search data set update for now. In the future, we may need to have a configuration table.
=> search ranking improvement with static boosting

data-model/DDL/ETL_DDL/etl_configure_tables.sql
=> last_modified column has a default for the table cfg_database

README.md, backend-service/app/actors/KafkaConsumerMaster.java, backend-service/app/controllers/DatasetInfoController.java, backend-service/app/controllers/LineageController.java, backend-service/app/models/daos/CfgDao.java, backend-service/app/models/daos/DatasetInfoDao.java, backend-service/app/models/daos/LineageDao.java, backend-service/app/models/kafka/JobExecutionLineageProcessor.java, backend-service/conf/routes, data-model/avro/JobExecutionLineageEvent.avsc, metadata-etl/src/main/java/metadata/etl/lineage/AzLineageExtractor.java, metadata-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java, wherehows-common/src/main/java/wherehows/common/LineageCombiner.java, wherehows-common/src/main/java/wherehows/common/schemas/AbstractRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/ApplicationRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/ChangeAuditStamp.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetIdentifier.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetPartitionRangeRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetPropertyRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DeploymentRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/JobExecutionRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/LineageDatasetMapRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/LineageDatasetRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/LineageFieldMapRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/LineageFieldRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/LineageRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/Record.java
- Add JobExecutionLineageEvent kafka event for job execution and data lineage information. 
- Create JobExecutionLineageProcessor
- Write into job_execution and job_execution_data_lineage table
=> Add JobExecutionLineageEvent and kafka processor

metadata-etl/src/main/resources/jython/CodeSearchLoad.py
During loading stage, we automatically set the "confirmed by" column of data set owners. They are marked by system. The web will show them as "confirmed" if it detects this column non empty. We may want to add this information on web to indicate these are confirmed by system not individual.
=> mark SCM users confirmed by system automatically

backend-service/app/controllers/DatasetInfoController.java, backend-service/app/models/daos/DatasetInfoDao.java, backend-service/app/models/kafka/MetadataChangeProcessor.java, backend-service/conf/routes, data-model/DDL/ETL_DDL/dataset_info_metadata.sql, data-model/avro/MetadataChangeEvent.avsc, web/app/controllers/api/v1/Dataset.java, web/conf/routes, wherehows-common/src/main/java/wherehows/common/schemas/DatasetComplianceRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetOriginalSchemaRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetOwnerRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetSchemaInfoRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetSecurityRecord.java
Now dataset compliance and security are two APIs, writing to two separate tables.
Other small changes according to avsc schema
=> Update MetadataChangeEvent, separate privacy compliance from security

web/app/views/index.scala.html, web/public/javascripts/components/components.js, web/public/javascripts/routers/datasets.js
- Removes arbitrary `setTimeout`'s set for updating DOM elements when ready and uses Ember component lifecycle, converts component usage to inline, uses data-\* attribute in place of id reference to component element from JS
- Imports refactoring changes from linkedin branch into master
=> DSS-5477: DatasetAuthorComponent

metadata-etl/src/main/resources/jython/ElasticSearchIndex.py
This check in is for further refine the elastic search boosting rule. and also add some into blacklist. 
Need to check with Eric about cleaning the old boosting score stored in elastic search engine
=> refine elastic search boosting rule

web/app/views/index.scala.html, web/public/javascripts/components/components.js, web/public/javascripts/routers/datasets.js, web/public/stylesheets/wherehows.css
…ners for a specific dataset and providing 'mailto:' functionality
=> DSS-5477: Implements DatasetOwnerList component displaying list of owners for a specific dataset and providing 'mailto:' functionality

web/app/views/main.scala.html, web/public/javascripts/search.js
Add initial piwik tracking for wherehows including the basic page view, visitors and site search keywords tracking. More custom events/variables are coming along the way
=> add piwik tracking for wherehows

web/app/views/main.scala.html
piwik tracking for wherehows prod site, Change from STG site ID to PROD site ID for now. Will try to do dynamic attaching ID later.
=> piwik tracking for wherehows prod site

data-model/ELASTICSEARCH/index_mapping.json, data-model/ELASTICSEARCH/index_mappings.md, metadata-etl/src/main/resources/jython/ElasticSearchIndex.py, wherehows-common/src/main/java/wherehows/common/Constant.java
In this commit, I have 
1, Add index_mapping json file
2, Modify index_mappings.md file to include the instructions such as building index, create index alias, etc
3, Modify the data set update SQL using left Join
4, Make default value for static boosting score as 0, to avoid null data populating issues
5, Rewrite code for flow_jobs, metric, etc, to make it more readable. 
6, Add a parameter for elastic index version, to make it configurable through wh_propery
=> clean and refactor elastic serach ETL job

web/app/views/index.scala.html, web/app/views/main.scala.html, web/public/javascripts/components/components.js, web/public/javascripts/search.js, web/public/stylesheets/wherehows.css
- Updates UI with CR from @sdas-> Adds 'Ask a question?' email link to email all owners
- Fixes enter key in Search bar input
=> Feature/dss 5477 + Typeahead fixes

metadata-etl/src/main/resources/jython/AppworxExtract.py, metadata-etl/src/main/resources/jython/AppworxLineageExtract.py, metadata-etl/src/main/resources/jython/AppworxLogParser.py, metadata-etl/src/main/resources/jython/BteqLogParser.py, metadata-etl/src/main/resources/jython/ParseUtil.py, metadata-etl/src/main/resources/jython/PigLogParser.py, metadata-etl/src/main/resources/jython/ScriptCollect.py
Eric's changes on Appworx Extract and Appworx Lineage Extract. 
Also removed some unnecessary python import.
=> Update Appworx Execution and Lineage jobs

web/app/dao/AdvSearchDAO.java, web/app/dao/SearchDAO.java
Added/Delete some logs related with elastic search. For better analysis in the future.
=> elastic search logs for further analysis

web/app/views/index.scala.html
Fixes issue with compliance and confidential tabs in dataset detail view
=> DSS-6385 Fixes issue with compliance and confidential tabs in dataset detail view

backend-service/app/controllers/DatasetController.java, backend-service/app/models/daos/DatasetInfoDao.java, backend-service/app/models/kafka/MetadataChangeProcessor.java, data-model/DDL/ETL_DDL/dataset_info_metadata.sql, web/app/dao/DatasetColumnCommentRowMapper.java, web/app/dao/LineageDAO.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetConstraintRecord.java
Some existing Group_by and Order_by SQL clause needs to be revised to work on MySQL 5.7 which enforces "ONLY_FULL_GROUP_BY". 
Should solve #333
=> Fix SQL query issues when upgrading to MySQL 5.7

web/app/controllers/api/v1/Dataset.java, web/app/dao/DashboardDAO.java, web/app/dao/DatasetsDAO.java, web/app/dao/ReturnCode.java, web/conf/routes
- Add frontend API for datasetOwnedBy, GET paged datasets owned by a user. 
- Enforce a minimum of 2 confirmed users before making changes on dataset owners page.
- Fix minor issues on frontend Dashboard APIs.
=> Add frontend API for datasetOwnedBy

.travis.yml, gradle/scripts/coverage.gradle
Play gradle plugin puts files in non-standard locations
=> Fix coverall reporting.

metadata-etl/src/main/resources/jython/EspressoTransform.py
- add "key:" prefix to Espresso keySchema (e.g. "key:fieldName01")
- support input json with empty "documentSchema"
=> add "key:" prefix to Espresso keySchema

web/app/controllers/api/v1/Search.java, web/app/dao/AdvSearchDAO.java, web/app/dao/SearchDAO.java, web/app/utils/Search.java, web/conf/routes
Search improvement. New type ahead api & phrase suggester support. Ready to be integrated with frontend.
=> Search improvement. New type ahead api & phrase suggester support. Ready to be integrated with frontend. 

metadata-etl/src/main/java/datamigration/EspressoPopulateSchemaMetadataEtl.java, metadata-etl/src/main/java/datamigration/OraclePopulateSchemaMetadataEtl.java, metadata-etl/src/main/resources/local_test.properties.template, restli-client/extralibs/readme.md, restli-client/src/main/java/wherehows/restli/dataset/client/EspressoCreateSchemaMetadata.java
1, adopting server changes. switch from avro schema to espresso schema format
2, Reverse readme file for restli client jar file list
3, modify metadata-etl/src/main/resources/local_test.properties.template, this is for configuration of restli server
=> switch from avro schema to espresso schema format

backend-service/app/actors/ConfigUtil.java
Remove the single quote around classpath.
=> Modify genearate java command to solve classpath issue

data-model/DDL/ETL_DDL/git_metadata.sql
Primary key fields needs to be "NOT NULL".
=> Fix table creation DDL bug for MySQL 5.7

web/app/dao/DatasetsDAO.java
Requirements: 2 owners, idType = USER, ownerType = Owner
before any updating action is allowed for ownership.
=> Modify ownership requirement of 2 confirmed Owner USER

web/app/dao/UserDAO.java
Only return active users instead of all users. Reduce returned number of entires.
=> Modify frontend API /party/entities to retrieve 'active' users

wherehows-web/app/components/dataset-author.js, wherehows-web/app/components/dataset-compliance.js, wherehows-web/app/styles/components/dataset-compliance/_compliance-prompts.scss, wherehows-web/app/templates/components/dataset-author.hbs, wherehows-web/app/templates/components/dataset-compliance.hbs, wherehows-web/app/templates/components/dataset-schema-table.hbs, wherehows-web/app/templates/components/dataset-table-group-compliance.hbs, wherehows-web/app/templates/components/dataset-table-org-compliance.hbs
removes the ability for the ui to edit usernames for owners that have been sourced from SCM 🔒
=> scm sourced owners not editable

web/app/controllers/Application.java, web/app/security/AuthenticationManager.java
Trying to debug and resolve the China Ldap login issue.
=> Add more logging for ldap login, refactor some authentication code

web/app/dao/DatasetColumnRowMapper.java, web/app/dao/MetadataStoreDao.java, web/app/models/DatasetColumn.java
From WhereHows DB, full path = parentPath.fieldName
=> Add fullFieldPath in frontend getColumn API return

backend-service/app/actors/KafkaConsumerMaster.java, backend-service/app/shared/Global.java, backend-service/app/utils/SchedulerUtil.java, backend-service/application.env.template, backend-service/conf/application.conf
This will allow us to set different job IDs in staging & production via cfg2.
=> Use environmental variables to set ETL & Kafka job IDs.

backend-service/application.env.template, metadata-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java
Also remove the unset WH_HOME directory from the search path.
=> Add WHZ_KRB5_DIR environmental variable to the search path for gss-jass.conf & krb5.conf files.

web/app/controllers/Application.java
This allows it to be set via env var (hence cfg2).
=> Change config tracking.piwik.siteid from type int to string.

data-model/DDL/ETL_DDL/dataset_info_metadata.sql, web/app/dao/DatasetsDAO.java, web/app/models/DatasetSecurity.java
Tested by API and UI. 
Added field will not impact current UI query.
=> Add dataset level confidentiality field in security API and DB

gradle/scripts/ember.gradle, metadata-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java
=> Set the correct system property for krb5 config flie.

metadata-etl/src/main/resources/jython/NuageLoad.py
Tested with Voldermort, Espresso, Kafka ETL jobs on local DB.
=> Update Nuage Load to purge non-exist dataset owners

metadata-etl/src/main/resources/jython/CodeSearchExtract.py, metadata-etl/src/main/resources/jython/CodeSearchLoad.py, metadata-etl/src/main/resources/jython/EspressoExtract.py, metadata-etl/src/main/resources/jython/EspressoTransform.py, metadata-etl/src/main/resources/jython/FileUtil.py, metadata-etl/src/main/resources/jython/KafkaExtract.py, metadata-etl/src/main/resources/jython/KafkaTransform.py, metadata-etl/src/main/resources/jython/MultiproductExtract.py, metadata-etl/src/main/resources/jython/MultiproductLoad.py, metadata-etl/src/main/resources/jython/OracleExtract.py, metadata-etl/src/main/resources/jython/OracleLoad.py, metadata-etl/src/main/resources/jython/TeradataExtract.py, metadata-etl/src/main/resources/jython/TeradataLoad.py, metadata-etl/src/main/resources/jython/TeradataTransform.py, metadata-etl/src/main/resources/jython/VoldemortExtract.py, metadata-etl/src/main/resources/jython/VoldemortTransform.py, metadata-etl/src/test/java/metadata/etl/dataset/espresso/EspressoMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/dataset/kafka/KafkaMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/dataset/oracle/OracleMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/dataset/teradata/TeradataMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/dataset/voldemort/VoldemortMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/git/CodeSearchMetadataEtlTest.java, metadata-etl/src/test/java/metadata/etl/git/MultiproductMetadataEtlTest.java
Instead of the full path defined in wh_etl_job_property, which is often /var/tmp/{something}.
=> Use WH_APP_FOLDER property as the base directory for temp files for various ETL jobs

metadata-etl/src/main/resources/jython/CodeSearchLoad.py, metadata-etl/src/main/resources/jython/MultiproductLoad.py, metadata-etl/src/main/resources/jython/NuageLoad.py
Tested loading process on local DB.
=> Update Multiproduct and CodeSearch ETL job to purge non-exist dataset owner

web/app/dao/DatasetOwnerRowMapper.java, web/app/dao/DatasetRowMapper.java, web/app/dao/DatasetWithUserRowMapper.java, web/app/dao/DatasetsDAO.java, web/app/models/User.java
refactor some code along the way.
Tested locally with UI
=> Frontend dataset and owner API to return user email

metadata-etl/src/main/resources/jython/HiveExtract.py
Should be chmod 666, previous change used python stat enums but did it wrong.
=> Fix output file chmod mistake

data-model/DDL/ETL_DDL/dataset_info_metadata.sql, web/app/dao/DatasetsDAO.java, web/app/models/DatasetSecurity.java
Test with API get and post. 
Now can handle null value for dataset_classification, confidentiality, classification, retention_policy and geographic_affinity.
=> Add dataset_classification to frontend security API

wherehows-api/app/dao/SearchDAO.java, wherehows-api/app/utils/Search.java
1, Support refine by multiple sources using ES filter feature
2, Keeps backward compatible when only one source is selected
3, Keeps backward compatible when "All" is selected
4, Remove the old mustunittemplate
5, For multiple sources, need integration testing with frontend; expected sources are a list of strings separated by comma.Locally tested by hardcode
=> support refine by multiple sources using ES filter

wherehows-etl/src/main/resources/jython/HiveTransform.py
DBA's suggestion to reduce undo log
=> Modify HIVE ETL to commit often

web/public/vendors/fancytree/src/skin-wherehows/ui.wherehows.css
I have many nested directories.
Currently, fancytree support until level5.
May I add new levels?
Thank you!
=> Add new levels for fancytree

wherehows-api/app/dao/DatasetsDAO.java, wherehows-api/app/models/DatasetSecurity.java
Previous format: map<classificationCategory, List<FieldEntity>>
Change to: map<FieldName, classificationCategory>
Easier for UI to manipulate and for backend to digest.
=> Security API classification field format change

docker/.gitignore, docker/README.md, docker/docker-compose.yml, docker/mysql/copy-ddl.sh
I tried "prepare-docker-archives.sh", but I did not go well.
May I change files?
- An error occurs because the archive directory does not exist
- Add a step for JDK Download
- The default tag of docker build is latest
Thank you!
Related PR: #478
=> Change build process for docker-compose.

backend-service/README.md
I am using the TreeBuilderActor. But it did not output dataset.json.
The reason is that the resource directory does not exist. Therefore, add the setup procedure.
Could you change wiki pages?
Thank you!
=> Add a mkdir comamnd for the TreeBuilder output.

wherehows-web/app/components/dataset-compliance.js, wherehows-web/app/components/search-bar-form.js, wherehows-web/app/constants/metadata-acquisition.js, wherehows-web/app/templates/components/dataset-compliance.hbs, wherehows-web/package.json, wherehows-web/yarn.lock
- fixes debouncing issue: invalid function referencing
- 	adds prettier precommit hook for app js files
- 	adds default value for mixed identifier types. disabled field format select for mixed identifier types. removes geolocation from field format options. updates defaulting logic for mixed types
=> fixes search debouncing issue. adds precommit for prettier. updates compliance feature for mixed types.

backend-service/conf/application.conf, docker/archive-factory/build-backend.sh, docker/archive-factory/build-web.sh, docker/docker-compose.yml, web/conf/application.conf
Make the setting changeable with docker option `-e`
=> Make possible to change settings via environment variables

web/public/javascripts/routers/advancedSearch.js, web/public/javascripts/routers/search.js, web/public/javascripts/search.js
I got a following exception when use Japanease(multi byte) in search.
```
search.js:17 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
at handleSearchInput (http://cdh:9000/assets/javascripts/search.js:17:52)
at HTMLInputElement.document.querySelector.addEventListener.e (http://cdh:9000/assets/javascripts/search.js:348:96)
```
Thank you!
=> Make possible to search by multi byte string.

restli-client/src/main/java/metastore/util/UrnUtil.java
=> Add dataset name convert for dalids and hive

wherehows-api/app/controllers/api/v1/Dataset.java, wherehows-api/app/dao/DatasetsDAO.java, wherehows-api/app/models/DatasetCompliance.java, wherehows-data-model/DDL/ETL_DDL/dataset_info_metadata.sql
Use username from session as the modified person.
=> track last modified person of compliance info

wherehows-web/app/routes/application.js, wherehows-web/app/routes/datasets/dataset.js, wherehows-web/app/routes/index.js, wherehows-web/app/services/configurator.js, wherehows-web/app/services/current-user.js, wherehows-web/app/templates/datasets/dataset.hbs, wherehows-web/app/templates/navbar.hbs, wherehows-web/tests/unit/services/configurator-test.js
-	adds internal flag check for branding
- 	adds support for constraining ui feature behind config flag - isInternal
-	adds application configuration to application start sequence. create configurator service for application.
=> adds support for constraining ui feature behind config flag - isInternal

wherehows-common/src/main/java/wherehows/common/Constant.java, wherehows-etl/src/main/resources/jython/DatasetTreeBuilder.py, wherehows-etl/src/main/resources/jython/ElasticSearchIndex.py, wherehows-etl/src/main/resources/jython/FlowTreeBuilder.py
This will break FlowTreeBuilder & DatasetTreeBuilder, both are not being used anyway.
=> Move elastic-serach related props from wh_property table to job files.

.travis.yml, wherehows-docker/.env, wherehows-docker/docker-compose.yml, wherehows-frontend/conf/application.conf
Expose various application.conf as env vars for wherehows-frontend.
=> Add Travis check for docker build & compose.

wherehows-backend/app/models/daos/DatasetInfoDao.java, wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetInstanceRecord.java, wherehows-common/src/main/java/wherehows/common/schemas/DatasetRecord.java, wherehows-data-model/DDL/ETL_DDL/dataset_metadata.sql, wherehows-etl/src/main/resources/jython/HdfsLoad.py, wherehows-etl/src/main/resources/jython/HiveLoad.py, wherehows-etl/src/main/resources/jython/HiveTransform.py, wherehows-etl/src/main/resources/jython/OracleLoad.py, wherehows-etl/src/main/resources/jython/TeradataLoad.py
=> Add active, deprecated flag to dataset, modify ETL to update is_active

wherehows-etl/src/main/resources/jython/OracleExtract.py, wherehows-etl/src/main/resources/jython/OracleLoad.py
tested on local desktop and DB.
=> Fix Oracle ETL job, rewrite data sampling

wherehows-data-model/avro/MetadataChangeEvent.avsc, wherehows-data-model/avro/MetadataInventoryEvent.avsc
Check in the new schema for reference.
=> Updated Metadata Catalog kafka event schema

gradle/scripts/dependency.gradle, wherehows-backend/app/controllers/Application.java, wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java, wherehows-backend/build.gradle, wherehows-dao/build.gradle, wherehows-dao/src/main/java/wherehows/dao/DatasetClassificationDao.java, wherehows-dao/src/main/java/wherehows/models/DatasetClassification.java, wherehows-dao/src/main/java/wherehows/models/DatasetColumn.java, wherehows-dao/src/main/resources/META-INF/persistence.xml
re-submite hibernate cfg and examples.
Have fixed all issues from comments.
=> submit hibernate cfg

wherehows-backend/app/controllers/Application.java, wherehows-backend/conf/routes, wherehows-dao/build.gradle, wherehows-frontend/app/controllers/Application.java, wherehows-frontend/conf/routes
It displays all the libraries from container
=> Added an end point in wherehows-frontend and wherehows-backend to display all the libraries

wherehows-backend/app/controllers/Application.java, wherehows-backend/application.env, wherehows-backend/conf/application.conf, wherehows-dao/src/main/java/wherehows/dao/ConnectionPoolProperties.java
Add 2 cfg properties for hikariCP:  datasource class name and database.diacle
Refactor CP properties to use builder pattern.
testing done:
local test/build passed.
Able to connection MYSQL and H2 DB.
=> fix hibernate connection pool only support mysql issue

wherehows-backend/conf/application.conf
Add a "?" to config default value, also update mysqldialect to mysql5dialect.
Verified the change works fine in stg server
=> correct syntax in application.conf

wherehows-frontend/app/controllers/Application.java, wherehows-frontend/conf/application.conf
Verified build works fine, can start frontend service locally
=> apply hibernate related change to frontend

wherehows-frontend/app/controllers/Application.java
fix a config variable in wherehows-frontend.
Also add the hibernate related config to FE application.env.
verified connection works in local/stg.
=> fix a config variable name

wherehows-dao/src/main/java/wherehows/dao/DatasetsDao.java, wherehows-dao/src/main/java/wherehows/util/JsonUtil.java, wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/app/dao/AbstractMySQLOpenSourceDAO.java, wherehows-frontend/app/dao/DatasetsDAO.java
Prepare to be extended internally for dual write.
=> Move dataset compliance DAO to dao module

wherehows-common/src/main/java/wherehows/common/schemas/DatasetRecord.java
DB insertion failed because of missing a new field. Given default null value.
Verified i can insert/update the to DB.
=> fix a DB insert issue, reporting missing a column

wherehows-backend/app/controllers/Application.java, wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java, wherehows-frontend/app/controllers/Application.java, wherehows-frontend/app/controllers/api/v1/Dataset.java
Config name mistakenly changed to dao.entityManagerFactory.class  by a previous commit. Change it back to dao.factory.class
=> Fix DAO Factory config name error, refactor some code

wherehows-backend/app/models/kafka/GobblinTrackingAuditProcessor.java
if classification result is empty or null, skip DB insertion.
=> skip empty classify result DB insertion

wherehows-dao/src/main/java/wherehows/dao/DatasetClassificationDao.java, wherehows-dao/src/main/java/wherehows/models/DatasetClassification.java, wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/conf/routes
=> Add compliance/suggestions API to get auto-classification data

wherehows-dao/src/main/java/wherehows/dao/DatasetsDao.java, wherehows-dao/src/main/java/wherehows/models/DatasetCompliance.java
Prepare to be overwrite internally
=> Update Dataset compliance DAO

wherehows-backend/jobs/templates/UMP_METRIC_ETL.job, wherehows-common/src/main/java/wherehows/common/Constant.java, wherehows-data-model/DDL/ETL_DDL/metric_metadata.sql
* add metric ETL job template
* Add constant for csv file config
* metric table ddl changes added
=> ump metric ETL

wherehows-backend/app/actors/ConfigUtil.java, wherehows-backend/app/actors/EtlJobActor.java, wherehows-backend/app/actors/SchedulerActor.java, wherehows-backend/app/models/daos/EtlJobDao.java, wherehows-backend/test/actors/ConfigUtilTest.java, wherehows-common/src/main/java/wherehows/common/jobs/BaseJob.java, wherehows-common/src/main/java/wherehows/common/jobs/JobFactory.java, wherehows-common/src/main/java/wherehows/common/jobs/JobStatus.java, wherehows-common/src/main/java/wherehows/common/jobs/Launcher.java, wherehows-etl/build.gradle, wherehows-etl/src/main/java/metadata/etl/EtlJob.java, wherehows-etl/src/main/java/metadata/etl/JythonEtlJob.java, wherehows-etl/src/test/java/metadata/etl/models/EtlJobFactoryTest.java
Tested on local by running a backend job.
=> Add BaseJob in wherehows-common, make ETLjob extends from it

wherehows-dao/src/main/java/wherehows/dao/DatasetsDao.java, wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/app/dao/DatasetsDAO.java
=> Modify frontend owners DAO functions

wherehows-frontend/app/utils/Search.java
* This is to support dataset urn search. Now if user searches for something like "/data/tracking/AdAnomalyDetectionStatsEvent" , it will be on the 1st in the search result
=> support dataset urn search

wherehows-dao/src/main/java/wherehows/models/DatasetCompliance.java, wherehows-dao/src/main/java/wherehows/models/Flow.java, wherehows-frontend/app/dao/FlowRowMapper.java, wherehows-frontend/app/dao/FlowsDAO.java
Converting Flow model to hibernate
=> Converting Flow model to hibernate

wherehows-dao/src/main/java/wherehows/dao/DatasetsDao.java, wherehows-dao/src/main/java/wherehows/mapper/DatasetOwnerRowMapper.java, wherehows-dao/src/main/java/wherehows/models/DatasetCompliance.java, wherehows-dao/src/main/java/wherehows/models/DatasetOwner.java, wherehows-dao/src/main/java/wherehows/models/Flow.java, wherehows-frontend/app/controllers/api/v1/Dataset.java
Making FlowKeys Implementing serializable and also converting dataset owner to hibernate entity
=> Converting DatasetOwner to hibernate entity

wherehows-dao/src/main/java/wherehows/dao/DatasetsDao.java, wherehows-dao/src/main/java/wherehows/models/DatasetOwner.java, wherehows-dao/src/main/java/wherehows/models/Flow.java, wherehows-frontend/app/controllers/api/v1/Dataset.java
Also fix a bug of Flow entity by not implementing Serializable
=> Convert DatasetOwner to entity and add copy constructor

wherehows-dao/src/main/java/wherehows/models/DatasetCompliance.java, wherehows-dao/src/main/java/wherehows/models/JiraTicket.java, wherehows-frontend/app/controllers/api/v1/Jira.java, wherehows-frontend/app/dao/JiraTicketRowMapper.java
Converting JiraTicket to hibernate entity
=> Converting JiraTicket to hibernate entity

wherehows-etl/src/main/resources/jython/HiveExtract.py, wherehows-etl/src/main/resources/jython/HiveLoad.py, wherehows-etl/src/main/resources/jython/HiveTransform.py
Instead of writing to fixed location (/var/tmp), write to job temp dir
=> Modify HIVE ETL output file dir

gradle/scripts/dependency.gradle, wherehows-common/build.gradle, wherehows-common/src/main/java/wherehows/common/Constant.java, wherehows-common/src/main/java/wherehows/common/utils/JobsUtil.java, wherehows-common/src/test/java/wherehows/common/utils/JobsUtilTest.java, wherehows-kafka/build.gradle, wherehows-kafka/src/main/java/wherehows/actors/KafkaClientMaster.java, wherehows-kafka/src/main/java/wherehows/actors/KafkaWorker.java, wherehows-kafka/src/main/java/wherehows/main/ApplicationStart.java, wherehows-kafka/src/main/java/wherehows/processors/DummyProcessor.java, wherehows-kafka/src/main/java/wherehows/processors/KafkaMessageProcessor.java, wherehows-kafka/src/main/java/wherehows/utils/KafkaClientUtil.java, wherehows-kafka/src/main/resources/application.conf, wherehows-kafka/src/main/resources/jobs/KAFKA_JOB_TEMPLATE.job, wherehows-kafka/src/test/java/wherehows/util/KafkaClientUtilTest.java
Dependency on wherehows-commons/kafka will be removed later on. Old consumerMaster and worker will also be remove after the processors have been refactored.
Tested consumer in local
=> Rewrite Kafka client master and worker

wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/app/dao/DatasetsDAO.java
=> Fix Dataset comment PUT API

wherehows-dao/src/main/java/wherehows/dao/table/DatasetsDao.java, wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/conf/routes
=> Add Frontend find ID by URN api

wherehows-dao/src/main/java/wherehows/dao/table/DatasetOwnerDao.java, wherehows-dao/src/main/java/wherehows/dao/table/FieldDetailDao.java, wherehows-kafka/src/main/java/wherehows/processors/MetadataChangeProcessor.java
Minor update on function definition for override.
=> Update Field detail and Owner Dao

gradle/scripts/dependency.gradle, wherehows-backend/app/actors/EtlJobActor.java, wherehows-backend/app/actors/SchedulerActor.java, wherehows-backend/app/actors/TreeBuilderActor.java, wherehows-common/src/main/java/wherehows/common/Constant.java
=> Move various constants into Constant class

wherehows-common/build.gradle, wherehows-common/src/main/java/wherehows/common/jobs/BaseJob.java, wherehows-common/src/main/java/wherehows/common/jobs/Launcher.java, wherehows-common/src/main/java/wherehows/common/utils/GitUtil.java, wherehows-common/src/main/java/wherehows/common/writers/DatabaseWriter.java, wherehows-dao/src/main/java/wherehows/dao/table/DatasetsDao.java, wherehows-etl/build.gradle, wherehows-etl/src/main/java/metadata/etl/EtlJob.java, wherehows-etl/src/main/java/metadata/etl/JythonEtlJob.java, wherehows-etl/src/main/java/metadata/etl/dataset/druid/DruidMetadataEtl.java, wherehows-etl/src/main/java/metadata/etl/dataset/druid/DruidMetadataExtractor.java, wherehows-etl/src/main/java/metadata/etl/dataset/druid/DruidMetadataLoader.java, wherehows-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java, wherehows-etl/src/main/java/metadata/etl/dataset/hive/HiveMetadataEtl.java, wherehows-etl/src/main/java/metadata/etl/dataset/hive/HiveViewDependency.java, wherehows-etl/src/main/java/metadata/etl/git/GitMetadataEtl.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzJobChecker.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzJsonAnalyzer.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzLineageExtractor.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzLineageExtractorActor.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzLineageExtractorMaster.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzLineageMetadataEtl.java, wherehows-etl/src/main/java/metadata/etl/lineage/AzServiceCommunicator.java, wherehows-etl/src/main/java/metadata/etl/lineage/HadoopJobHistoryNodeExtractor.java, wherehows-etl/src/main/java/metadata/etl/lineage/appworx/AppworxLineageEtl.java, wherehows-etl/src/main/java/metadata/etl/sqlParser/SelectStmt.java, wherehows-etl/src/main/java/metadata/etl/sqlParser/SqlParser.java, wherehows-etl/src/main/java/metadata/etl/treebuilder/DatasetTreeBuildETL.java, wherehows-etl/src/test/java/metadata/etl/lineage/LineageTest.java, wherehows-hadoop/src/main/java/wherehows/SchemaFetch.java
Removed all manual logger instantiations with lombok's @Slf4j.
=> Removed all manual logger instantiations with lombok's @Slf4j.

wherehows-dao/src/main/java/wherehows/dao/table/BaseDao.java, wherehows-dao/src/main/java/wherehows/dao/view/BaseViewDao.java, wherehows-kafka/src/main/java/wherehows/processors/MetadataChangeProcessor.java
Put all statements inside try{} block.
=> Modify BaseDao, add dataset name length check

wherehows-backend/app/actors/ConfigUtil.java, wherehows-backend/app/actors/EtlJobActor.java, wherehows-backend/conf/etl_logback.xml, wherehows-backend/test/actors/ConfigUtilTest.java
Updating ETL util to incorporate unify logging.
=> Updating ETL config to incorporate unify logging.

wherehows-dao/src/main/java/wherehows/dao/table/BaseDao.java, wherehows-dao/src/main/java/wherehows/dao/table/DatasetsDao.java, wherehows-dao/src/main/java/wherehows/dao/table/DictDatasetDao.java, wherehows-dao/src/main/java/wherehows/dao/table/FieldDetailDao.java, wherehows-dao/src/main/java/wherehows/dao/view/BaseViewDao.java, wherehows-dao/src/main/java/wherehows/dao/view/DatasetViewDao.java, wherehows-dao/src/main/java/wherehows/models/table/Dataset.java, wherehows-dao/src/main/java/wherehows/models/view/DatasetView.java, wherehows-dao/src/test/java/wherehows/dao/DatasetViewDaoTest.java, wherehows-frontend/app/controllers/api/v1/Dataset.java, wherehows-frontend/app/dao/DatasetRowMapper.java, wherehows-frontend/app/dao/DatasetWithUserRowMapper.java, wherehows-frontend/app/dao/DatasetsDAO.java, wherehows-frontend/app/utils/Dataset.java, wherehows-frontend/conf/routes
Introduce two new frontend APIs
1. GET dataset view , from dict_dataset
2. PUT dataset deprecation, write to dict_dataset column is_deprecated
Plus reformat/refactor some JDBC DAO code, no functional change here.
=> Add dataset deprecation frontend API

wherehows-dao/src/main/java/wherehows/dao/table/DictDatasetDao.java, wherehows-dao/src/test/java/wherehows/dao/DictDatasetDaoTest.java
Previously put the wrong value into source.
=> Fix bug in Dict dataset source

wherehows-web/app/components/dataset-deprecation.ts, wherehows-web/app/components/purge-policy.ts, wherehows-web/app/controllers/datasets/dataset.js, wherehows-web/app/styles/components/comments/_comment-new.scss, wherehows-web/app/templates/components/comment/comment-new.hbs, wherehows-web/app/templates/datasets/dataset.hbs, wherehows-web/ember-cli-build.js, wherehows-web/tests/integration/components/dataset-deprecation-test.js
@camelliazhang let me know if this drops latency
=> updates build options to support uglify2 compression options to improve build time

wherehows-data-model/DDL/create_all_tables_wrapper.sql
ERROR at line 26: Failed to open file 'ETL_DDL/kafka_tracking.sql', error: 2
=> Fix issue :Failed to open file 'ETL_DDL/kafka_tracking.sql

wherehows-web/app/components/dataset-authors.ts, wherehows-web/app/components/pendulum-ellipsis-animation.ts, wherehows-web/app/styles/components/_all.scss, wherehows-web/app/styles/components/pendulum-ellipsis-animation/_all.scss, wherehows-web/app/styles/components/pendulum-ellipsis-animation/_ellipsis-loader.scss, wherehows-web/app/templates/components/dataset-author.hbs, wherehows-web/app/templates/components/dataset-authors.hbs, wherehows-web/app/templates/components/pendulum-ellipsis-animation.hbs, wherehows-web/app/typings/api/datasets/properties.d.ts, wherehows-web/app/utils/api/datasets/properties.ts, wherehows-web/app/utils/api/shared.ts, wherehows-web/tests/integration/components/pendulum-ellipsis-animation-test.js
- removes source column for confirmed owners and removes non user id types from suggested list. changes column header to data owner
- updates ownership type wording
=> updates propeties api getter to treat error as empty result. updates loading animation on save

wherehows-web/app/constants/datasets/shared.ts, wherehows-web/app/controllers/datasets/dataset.js, wherehows-web/app/router.js, wherehows-web/app/routes/datasets/dataset/comments.ts, wherehows-web/app/routes/datasets/dataset/compliance.ts, wherehows-web/app/routes/datasets/dataset/ownership.ts, wherehows-web/app/routes/datasets/dataset/properties.ts, wherehows-web/app/routes/datasets/dataset/relations.ts, wherehows-web/app/routes/datasets/dataset/sample.ts, wherehows-web/app/routes/datasets/dataset/schema.ts, wherehows-web/app/templates/datasets/dataset.hbs, wherehows-web/app/typings/untyped-js-module.d.ts, wherehows-web/tests/acceptance/browse-test.js, wherehows-web/tests/unit/routes/datasets/dataset/comments-test.js, wherehows-web/tests/unit/routes/datasets/dataset/compliance-test.js, wherehows-web/tests/unit/routes/datasets/dataset/ownership-test.js, wherehows-web/tests/unit/routes/datasets/dataset/properties-test.js, wherehows-web/tests/unit/routes/datasets/dataset/relations-test.js, wherehows-web/tests/unit/routes/datasets/dataset/sample-test.js, wherehows-web/tests/unit/routes/datasets/dataset/schema-test.js
=> implements tabbed routes for datasets

wherehows-kafka/build.gradle, wherehows-kafka/src/main/java/wherehows/actors/KafkaClientMaster.java, wherehows-kafka/src/main/java/wherehows/exceptions/SelfLineageException.java, wherehows-kafka/src/main/java/wherehows/processors/DummyProcessor.java, wherehows-kafka/src/main/java/wherehows/processors/KafkaMessageProcessor.java, wherehows-kafka/src/main/java/wherehows/processors/MetadataChangeProcessor.java, wherehows-kafka/src/main/java/wherehows/processors/MetadataInventoryProcessor.java, wherehows-kafka/src/main/java/wherehows/processors/MetadataLineageProcessor.java, wherehows-kafka/src/test/java/wherehows/processors/MetadataLineageProcessorTest.java
Also make Kafka processors testable
=> Validate linage and throws exception on self lineage

wherehows-frontend/app/controllers/Application.java, wherehows-frontend/conf/application.conf
Purpose is to show revamped features only in staging environment while overall feature is still in development.
=> add a config for showing the ownership tab revamp feature only on stg

wherehows-web/app/components/dataset-compliance.ts, wherehows-web/app/components/datasets/schemaless-tagging.ts, wherehows-web/app/templates/components/dataset-compliance.hbs, wherehows-web/app/templates/components/datasets/schemaless-tagging.hbs, wherehows-web/app/templates/components/purge-policy.hbs, wherehows-web/app/templates/datasets/dataset-compliance/-dataset-classification.hbs, wherehows-web/app/templates/datasets/dataset-compliance/-dataset-compliance-entities.hbs, wherehows-web/tests/integration/components/datasets/schemaless-tagging-test.js
=> removes ability to specify schema-less security classification in ui

wherehows-web/app/routes/datasets/dataset.ts, wherehows-web/app/utils/validators/urn.ts
Not having this will create an apiError
=> Encode wildcard symbol before sending api call for readdataset

wherehows-backend/application.env
Cleaning up wherehows-backend/application.env config file to fix error message
=> Cleaning up wherehows-backend/application.env

wherehows-web/app/components/dataset-authors.ts
=> Remove stray debugger statement

wherehows-web/app/constants/notifications.ts, wherehows-web/app/controllers/login.ts, wherehows-web/app/routes/login.js, wherehows-web/app/services/banners.ts
Only minor changes with some constants added
```
1..458
```
=> change severity of login and stale search banner to draw more attention

wherehows-web/app/components/datasets/containers/dataset-compliance.ts, wherehows-web/app/utils/datasets/compliance/metadata-schema.ts
slightly modifies variable names and removes unnecessary array type check
fixes cases where the type is a list that may include array or object
=> refactors IDL for metadata json schema and implementation of validator

wherehows-frontend/app/controllers/Application.java, wherehows-web/app/components/dataset-authors.ts, wherehows-web/app/constants/datasets/owner.ts, wherehows-web/app/controllers/datasets/dataset.ts, wherehows-web/app/routes/datasets/dataset.ts, wherehows-web/app/templates/components/dataset-author.hbs, wherehows-web/app/templates/components/dataset-authors.hbs, wherehows-web/app/templates/components/datasets/containers/dataset-ownership.hbs, wherehows-web/app/templates/datasets/dataset.hbs, wherehows-web/tests/helpers/datasets/compliance-policy/field-changeset-constants.ts, wherehows-web/tests/integration/components/dataset-authors-test.js, wherehows-web/tests/integration/components/datasets/containers/dataset-ownership-test.js
Reverts linkedin/WhereHows#1223
=> Revert "removes obsolete flags for ownership feature gate"

wherehows-frontend/app/controllers/Application.java, wherehows-web/app/components/dataset-authors.ts, wherehows-web/app/constants/datasets/owner.ts, wherehows-web/app/controllers/datasets/dataset.ts, wherehows-web/app/routes/datasets/dataset.ts, wherehows-web/app/templates/components/dataset-author.hbs, wherehows-web/app/templates/components/dataset-authors.hbs, wherehows-web/app/templates/components/datasets/containers/dataset-ownership.hbs, wherehows-web/app/templates/datasets/dataset.hbs, wherehows-web/tests/helpers/datasets/compliance-policy/field-changeset-constants.ts, wherehows-web/tests/integration/components/dataset-authors-test.js, wherehows-web/tests/integration/components/datasets/containers/dataset-ownership-test.js
removes mid-tier config property for showOwnership feature flag
fix failing tests
=> removes obsolete flags for ownership feature gate

wherehows-web/app/components/visualization/charts/score-gauge.ts, wherehows-web/app/constants/visualization/charts/chart-configs.ts, wherehows-web/app/styles/base/_visualization.scss, wherehows-web/app/styles/components/visualization/charts/_all.scss, wherehows-web/app/styles/components/visualization/charts/_score-gauge.scss, wherehows-web/app/templates/components/visualization/charts/score-gauge.hbs, wherehows-web/app/typings/app/visualization/charts.d.ts, wherehows-web/ember-cli-build.js, wherehows-web/tests/integration/components/datasets/containers/dataset-acl-access-test.js, wherehows-web/tests/integration/components/visualization/charts/score-gauge-test.js
- Correctly import highcharts to handle solid gauges
- Create component with correct configuration for solid gauge chart to match our intended designs for a health score
- Add optional, light customizations to the gauge chart
- Skip a currently failing test to be investigated
```
skip 1 Chrome 68.0 - [0 ms] - Acceptance | datasets/dataset/comments: visiting /datasets/dataset/comments
skip 2 Chrome 68.0 - [0 ms] - Acceptance | datasets/dataset/ownership: visiting /datasets/dataset/ownership
...
ok 378 Chrome 68.0 - [2 ms] - Unit | Utility | validators/urn: buildLiUrn
ok 379 Chrome 68.0 - [1 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
1..379
```
Reference for appearance with various states:
=> Score gauge component

wherehows-data-model/src/main/avro/SuggestedCompliancePolicy.avsc, wherehows-frontend/app/dao/UserDAO.java
=> Drop org_hierarchy_depth in user queries

wherehows-dao/src/main/java/wherehows/models/view/DatasetValidation.java
to fix error java.lang.IllegalArgumentException: No serializer found for class
=> Add getter to DatasetValidation class

wherehows-dao/src/main/java/wherehows/dao/DaoFactory.java, wherehows-dao/src/main/java/wherehows/dao/table/SearchDao.java, wherehows-frontend/app/controllers/api/v1/Search.java
* Remove static so that internal searchdao can override
* Rename to be consistent with other dao models 
* Add search dao into dao factory
=> more refactoring so that the methods can be override internally

wherehows-dao/src/main/java/wherehows/models/view/DatasetExportPolicy.java
```
BUILD SUCCESSFUL in 2m 58s
26 actionable tasks: 16 executed, 10 up-to-date
```
=> Add allargsconstructor to exportpolicy

wherehows-dao/src/main/java/wherehows/dao/DaoFactory.java, wherehows-dao/src/main/java/wherehows/dao/table/ExportPolicyDao.java
```
BUILD SUCCESSFUL in 1m 16s
26 actionable tasks: 10 executed, 16 up-to-date
```
=> Edit dao factory for export policy

wherehows-data-model/ELASTICSEARCH/dataset_query_template.json
remove the urn and schema field search to reduce the noise in the result
=> remove unrelated results

wherehows-dao/src/main/java/wherehows/dao/table/SearchDao.java, wherehows-dao/src/main/java/wherehows/util/Search.java, wherehows-data-model/ELASTICSEARCH/filter_unit_fabric.json, wherehows-frontend/app/controllers/api/v1/Search.java
* Allow filtering on fabrics for search results
* Tested on dev
=> add fabric facet for search

settings.gradle, wherehows-ingestion/build.gradle, wherehows-ingestion/src/main/java/wherehows/ingestion/converters/KafkaLogCompactionConverter.java, wherehows-ingestion/src/main/java/wherehows/ingestion/converters/KafkaMessageConverter.java, wherehows-ingestion/src/main/java/wherehows/ingestion/processors/DummyProcessor.java, wherehows-ingestion/src/main/java/wherehows/ingestion/processors/KafkaMessageProcessor.java, wherehows-ingestion/src/main/java/wherehows/ingestion/processors/MetadataChangeProcessor.java, wherehows-ingestion/src/main/java/wherehows/ingestion/processors/MetadataInventoryProcessor.java, wherehows-ingestion/src/main/java/wherehows/ingestion/processors/MetadataLineageProcessor.java, wherehows-ingestion/src/main/java/wherehows/ingestion/utils/ProcessorUtil.java, wherehows-ingestion/src/test/java/wherehows/ingestion/converters/KafkaLogCompactionConverterTest.java, wherehows-ingestion/src/test/java/wherehows/ingestion/processors/MetadataLineageProcessorTest.java, wherehows-ingestion/src/test/java/wherehows/ingestion/util/ProcessorUtilTest.java, wherehows-kafka/build.gradle, wherehows-kafka/src/main/java/wherehows/actors/KafkaClientMaster.java, wherehows-kafka/src/main/java/wherehows/actors/KafkaWorker.java, wherehows-kafka/src/main/java/wherehows/utils/ConfigUtil.java, wherehows-kafka/src/test/java/wherehows/util/ConfigUtilTest.java
wherehows-kafka module will depend on this wherehows-ingestion module
=> Move kafka processors to module wherehows-ingestion

wherehows-web/app/components/avatars/stacked-avatars-list.ts, wherehows-web/app/components/dataset-aclaccess.ts, wherehows-web/app/components/dataset-authors.ts, wherehows-web/app/components/dataset-compliance-rollup-row.ts, wherehows-web/app/components/datasets/containers/dataset-owner-list.ts, wherehows-web/app/constants/avatars/avatars.ts, wherehows-web/app/constants/datasets/owner.ts, wherehows-web/app/routes/application.js, wherehows-web/app/templates/components/datasets/containers/dataset-owner-list.hbs, wherehows-web/app/typings/app/avatars.d.ts
- adds ability to replace all annotations for a compliance field with identifierType none when the suggestion is accepted
- refactors StackedAvatarList component api with action to handle any menu option selection
=> obfuscation feedback ui: accepting none should replace multi tagged field with single none tag

wherehows-web/app/components/datasets/compliance/export-policy.ts
=> Adds missing documentation for computed property in export policy component

wherehows-dao/src/main/java/wherehows/dao/table/SearchDao.java, wherehows-frontend/app/controllers/api/v1/Search.java
allow read facet name in autocomplete/datasets api
=> support auto complete with facets

wherehows-web/build.gradle, wherehows-web/ember.gradle
=> Move ember.gradle from gradle/scripts to wherehows-web

wherehows-dao/src/main/java/wherehows/models/view/DatasetExportPolicy.java
Preparing to add last modified when by whom to all compliance sections.
`gradle build`:
```
BUILD SUCCESSFUL in 2m 13s
21 actionable tasks: 12 executed, 9 up-to-date
```
=> Add actor and modified time to export policy class

wherehows-frontend/app/Filters.java, wherehows-frontend/app/security/DummyLoginModule.java, wherehows-frontend/test/ControllersTest.java
MP: wherehows-frontend
TO_COMMIT: 91bd2f50851c612d667c8265c1e788dc0edf8de4
FROM_COMMIT: 23999624d62fbeeff0fde1b66b92dceb52f1611c
=> Drop extra spaces

wherehows-common/src/test/java/DatasetPathTest.java, wherehows-common/src/test/java/FileWriterTest.java, wherehows-common/src/test/java/LineageCombinerTest.java
MP: wherehows-proxy
TO_COMMIT: c89c82cd9808446fb096ffa7b2db74df06864457
FROM_COMMIT: 3e99ed082c2b3cca48425753a62af0e55833d015
=> Drop extra white lines

wherehows-web/app/parsers/autocomplete.ne, wherehows-web/app/styles/components/user-lookup/_pwr-user-lookup.scss, wherehows-web/app/styles/components/user-lookup/_user-lookup.scss, wherehows-web/app/typings/app/parsers.d.ts, wherehows-web/app/typings/modules/nearley.d.ts, wherehows-web/app/utils/parsers/parser.ts, wherehows-web/ember-cli-build.js, wherehows-web/lib/.eslintrc.js, wherehows-web/lib/ember-nearley/broccoli-nearley.js, wherehows-web/lib/ember-nearley/index.js, wherehows-web/lib/ember-nearley/package.json, wherehows-web/package.json, wherehows-web/scripts/ember.sh, wherehows-web/scripts/yarn.sh, wherehows-web/tests/unit/parsers/autocomplete-test.ts, wherehows-web/tsconfig.json, wherehows-web/yarn.lock
MP=wherehows-frontend
TO_COMMIT=067b514ddae957b14c007c62cba7124e5ee8af01
FROM_COMMIT=a7a6163cf41ee86be2dd903bfc618c71f1b92cfc
=> Advanced search autocomplete

wherehows-web/package.json, wherehows-web/yarn.lock
MP=wherehows-frontend
TO_COMMIT=9eae6d8bced135f4ffd59e950ecfb412aaf67030
FROM_COMMIT=9eae6d8bced135f4ffd59e950ecfb412aaf67030
=> Upgrade husky

metadata-ingestion/README.md, metadata-ingestion/ldap_etl.py
Ingested metadata from LDAP server to Data Hub.
=> Ingested metadata from LDAP server to Data Hub.

docker/frontend/README.md
Fixed a minor documentation issue regarding logging in to datahub frontend
=> Minor Documentation Fixes

datahub-web/packages/data-portal/app/styles/layout/_dataset.scss, datahub-web/packages/data-portal/app/templates/components/datasets/dataset-header.hbs, docker/quickstart/docker-compose.yml
This PR aims to show the dataset description in the Dataset view. 
_Related with https://github.com/linkedin/datahub/issues/1561_
=> feature: 📝 - Show Dataset description

contrib/nix/README.md, contrib/nix/sandbox.nix
switch from master to tag version.
test on mac and redhat 7.
welcome to use.
=> switch home-manager from master to stable version

contrib/nix/README.md, contrib/nix/datahub-check.nix, contrib/nix/datahub-config.nix
add port check: 
simple run ```nix-shell datahub-check.nix -A gms```
=> add datahub-check for port check

metadata-ingestion/mce-cli/requirements.txt
=> fix: specify explicit avro lib for compatibility issue

contrib/metadata-ingestion/README.md, contrib/metadata-ingestion/bin/lineage_hive_generator.hs, contrib/metadata-ingestion/bin/lineage_hive_generator.hs.nix, contrib/metadata-ingestion/sample/hive_1.sql
wait for more test.
parse hive sql to upstreams aspect format, and can send to gms by datahub-producer
#1519
=> init lineage hive

contrib/metadata-ingestion/README.md, contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs, contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs.nix
use jdbc to fetch database schema in one query (include mysql, mssql, postgresql driver)
#1520
=> init jdbc generator

li-utils/src/main/java/com/linkedin/common/urn/Urn.java, metadata-dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, metadata-dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jQueryDAOTest.java, metadata-dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAOTest.java, metadata-restli-resource/src/main/java/com/linkedin/metadata/restli/BrowsableClient.java, metadata-restli-resource/src/test/java/com/linkedin/metadata/restli/BrowsableClientTest.java, metadata-testing/metadata-test-models/build.gradle, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/TestUtils.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/BarUrn.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/BarUrnCoercer.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/BaseUrnCoercer.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/BazUrn.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/BazUrnCoercer.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/FooUrn.java, metadata-testing/metadata-test-models/src/main/java/com/linkedin/testing/urn/FooUrnCoercer.java, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/BarUrn.pdsc, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/BazUrn.pdsc, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/EntityBar.pdsc, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/EntityBaz.pdsc, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/EntityFoo.pdsc, metadata-testing/metadata-test-models/src/main/pegasus/com/linkedin/testing/FooUrn.pdsc
Expose EbeanServer from EbeanLocalDAO
Create test URNs and use those from entity models
Implement interface for browse
MP_VERSION=metadata-models:62.0.3
MP_VERSION=wherehows-samza:1.0.56
=> metadata-models 58.0.1 -> 62.0.3

gms/impl/build.gradle, gms/war/src/main/webapp/WEB-INF/beans.xml
Fix the unable to find registered resource error introduced by 6a309332f321fc6847a721629c276e62867bf52c
Also simplify the build script
=> fix(gms): unable to find registered resources

contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml, contrib/kubernetes/yaml/datahub-gms-deployment.yaml, docker/frontend/Dockerfile, docker/gms/Dockerfile, docker/gms/docker-compose.yml, docker/quickstart/docker-compose.yml
=> fix: Reduce gms & frontend docker image sizes

contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml, contrib/kubernetes/yaml/datahub-mae-consumer-deployment.yaml, contrib/kubernetes/yaml/datahub-mce-consumer-deployment.yaml, docker/mae-consumer/Dockerfile, docker/mae-consumer/docker-compose.yml, docker/mce-consumer/Dockerfile, docker/mce-consumer/docker-compose.yml, docker/quickstart/docker-compose.yml
=> fix: Reduce mae-consumer & mce-consumer docker image sizes

contrib/metadata-ingestion/README.md, contrib/metadata-ingestion/bin/dataset-jdbc-generator.hs
add field for ui and lineage parser reference.
=> add field for ui and parser reference

docs/how/metadata-modelling.md
Pegasus schema blog url is not working ,so use rest.li wiki instead
=> docs: update metadata-modelling.md

contrib/metadata-ingestion/README.md, contrib/metadata-ingestion/bin/dataset-hive-generator.py, contrib/metadata-ingestion/bin/dataset-hive-generator.py.nix
migrate hive python generator to json format load.
=> migrate hive generator

build.gradle, docs/developers.md, gradle/checkstyle/checkstyle.xml, gradle/checkstyle/suppressions.xml, gradle/idea/LinkedIn Style.xml
Currently allow checkstyle warnings until all violations have been fixed
=> style: add checkstyle and IDEA code style config

build.gradle, repositories.gradle
See https://github.com/linkedin/rest.li/issues/283 for new repo location
=> build: update pegasus to v28 to add PDL support

build.gradle, datahub-dao/src/main/java/com/linkedin/datahub/dao/DaoFactory.java, gms/client/src/main/java/com/linkedin/dataset/client/Datasets.java, gms/client/src/main/java/com/linkedin/dataset/client/Lineages.java, gms/client/src/main/java/com/linkedin/dataset/client/Ownerships.java, gms/factories/src/main/java/com/linkedin/restli/server/spring/ParallelRestliHttpRequestHandler.java, gms/impl/src/main/java/com/linkedin/metadata/configs/DatasetSearchConfig.java, gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/Datasets.java, gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/DownstreamLineageResource.java, gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/UpstreamLineageResource.java, gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpGroups.java, gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpUsers.java, gms/impl/src/test/java/com/linkedin/metadata/configs/CorpUserSearchConfigTest.java, li-utils/src/main/java/com/linkedin/common/urn/DatasetUrn.java, li-utils/src/main/java/com/linkedin/common/urn/Urn.java, li-utils/src/main/java/com/linkedin/common/urn/UrnUtils.java, li-utils/src/main/java/com/linkedin/util/Configuration.java, metadata-dao-impl/kafka-producer/src/main/java/com/linkedin/metadata/dao/producer/KafkaProducerCallback.java, metadata-dao/src/test/java/com/linkedin/metadata/dao/utils/QueryUtilTest.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MaeConsumerApplication.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/Neo4jConfig.java, metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MceConsumerApplication.java, metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java, metadata-testing/metadata-test-utils/src/main/java/com/linkedin/metadata/utils/ESTestUtils.java, metadata-utils/src/main/java/com/linkedin/metadata/neo4j/Neo4jDriverFactory.java, metadata-utils/src/main/java/com/linkedin/metadata/restli/DefaultRestliClientFactory.java, metadata-utils/src/main/java/com/linkedin/metadata/utils/elasticsearch/ElasticsearchConnectorFactory.java
=> build: start enforcing checkstyle and fix all violations

datahub-dao/src/main/java/com/linkedin/datahub/dao/table/LineageDao.java, datahub-dao/src/main/java/com/linkedin/datahub/util/DatasetUtil.java
=> fix(frontend): Extract lastModified field from downstream/upstream aspect

build.gradle, metadata-jobs/mae-consumer-job/build.gradle, metadata-jobs/mce-consumer-job/build.gradle
=> build: upgrade version of certain dependencies

build.gradle, metadata-jobs/mae-consumer-job/build.gradle, metadata-jobs/mce-consumer-job/build.gradle
Reverts linkedin/datahub#1675
Plan on testing this end-to-end before rolling it out.
=> Revert "build: upgrade version of certain dependencies"

contrib/kubernetes/README.md, contrib/kubernetes/datahub/README.md, contrib/kubernetes/datahub/charts/datahub-frontend/README.md, contrib/kubernetes/datahub/charts/datahub-frontend/values.yaml, contrib/kubernetes/datahub/charts/datahub-gms/README.md, contrib/kubernetes/datahub/charts/datahub-gms/values.yaml, contrib/kubernetes/datahub/charts/datahub-mae-consumer/README.md, contrib/kubernetes/datahub/charts/datahub-mae-consumer/values.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/README.md, contrib/kubernetes/datahub/charts/datahub-mce-consumer/values.yaml, contrib/kubernetes/datahub/values.yaml, contrib/kubernetes/yaml/datahub-frontend-deployment.yaml, contrib/kubernetes/yaml/datahub-gms-deployment.yaml, contrib/kubernetes/yaml/datahub-mae-consumer-deployment.yaml, contrib/kubernetes/yaml/datahub-mce-consumer-deployment.yaml, docker/README.md, docker/frontend/README.md, docker/frontend/docker-compose.yml, docker/gms/README.md, docker/gms/docker-compose.yml, docker/mae-consumer/README.md, docker/mae-consumer/docker-compose.yml, docker/mce-consumer/README.md, docker/mce-consumer/docker-compose.yml, docker/quickstart/docker-compose.yml, docs/debugging.md
As we're now utilize GitHub Actions to build & publish docker images to docker hub under linkedin org
Closes https://github.com/linkedin/datahub/issues/1548
=> docs: points to docker images hosted by linkedin org

gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/DownstreamLineageResource.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/search/BuilderUtilsTest.java, metadata-dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java, metadata-dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jUtil.java, metadata-dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jUtilTest.java
=> Add missing updates from recent internal push

docs/how/search-onboarding.md
=> fix-DatasetSearchConfig class ref

metadata-ingestion/sql-etl/bigquery_etl.py, metadata-ingestion/sql-etl/bigquery_etl.txt, metadata-ingestion/sql-etl/common.py, metadata-ingestion/sql-etl/mysql_etl.py
Also fix minor issues in the common script
=> feature(ingest): add bigquery ETL script

metadata-ingestion/sql-etl/postgres.yml, metadata-ingestion/sql-etl/postgres_etl.py, metadata-ingestion/sql-etl/postgres_etl.txt
Also add a simple docker file for testing
=> feat(ingest): add PostgreSQL ETL script

metadata-ingestion/sql-etl/snowflake.txt, metadata-ingestion/sql-etl/snowflake_etl.py
=> feat(ingest): add snowflake ETL script

docker/ingestion/Dockerfile, metadata-ingestion/mce-cli/requirements.txt
Fixes #1612 
Tested both on Linux (Python 3.6.8) & Mac (Python 3.7.3)
=> fix(py3): Bump ingestion Docker py dependency to 3.6

metadata-ingestion/ldap-etl/requirements.txt, metadata-ingestion/mysql-etl/requirements.txt, metadata-ingestion/sql-etl/common.txt
Issue:  https://github.com/linkedin/datahub/issues/1724
=> fix: modify the etl script dependency

docs/roadmap.md
- Make short term more like what we're doing this quarter
- Medium term is next quarter
- Long term is 2 or 3 quarters from now
- Visionary is even beyond that
Making this PR mostly to discuss the roadmap. I've moved a few items down to "unprioritized"; before merging this we should put these in a category. Mostly saving the state of what I've done so far.
=> Update the roadmap

README.md, docs/links.md
=> doc: add a separate doc to keep track of the full list or links

contrib/metadata-ingestion/bin/dataset-hive-generator.py, contrib/metadata-ingestion/openldap-etl/openldap-etl.py, docker/kafka/Dockerfile, metadata-ingestion/kafka-etl/kafka_etl.py, metadata-ingestion/ldap-etl/ldap_etl.py, metadata-ingestion/mce-cli/mce_cli.py, metadata-ingestion/mysql-etl/mysql_etl.py, metadata-ingestion/sql-etl/common.py
=> fix(ingestions): align the default kafka topics with PR #1756

.github/pull_request_template.md
=> docs(PR template): Fix reflinks in PR template

README.md, docs/quickstart.md
=> docs: move quickstart guide to a separate file under docs

.github/workflows/docker-frontend.yml, .github/workflows/docker-gms.yml, .github/workflows/docker-mae-consumer.yml, .github/workflows/docker-mce-consumer.yml
Will keep publishing to Docker Hub meanwhile until all Dockerfiles have been updated to point to GitHub.
Fixes #1548
Check out both the sample output: https://github.com/mars-lan/datahub/packages
=> build(docker): build & publish GitHub Package

docs/advanced/aspect-versioning.md, docs/advanced/backfilling.md, docs/advanced/derived-aspects.md
=> docs: more placeholders for advance topics

docs/how/search-over-new-field.md
Add a doc on searching over a new field
=> docs: create search-over-new-field.md

docker/elasticsearch-setup/dataset-index-config.json
=> feat: add description field to dataset index mapping

docs/features.md, metadata-ingestion/sql-etl/common.py, metadata-ingestion/sql-etl/mssql.yml, metadata-ingestion/sql-etl/mssql_etl.py, metadata-ingestion/sql-etl/mssql_etl.txt
Also fix the incorrect assumption on column comments & add sample docker-compose file
Fixes https://github.com/linkedin/datahub/issues/1797
=> feat(ingest): add example crawler for MS SQL

datahub-dao/src/main/java/com/linkedin/datahub/dao/DaoFactory.java, datahub-dao/src/main/java/com/linkedin/datahub/dao/table/DataPlatformsDao.java, datahub-dao/src/main/java/com/linkedin/datahub/dao/table/GmsDao.java, datahub-frontend/app/controllers/api/v2/Dataset.java, datahub-frontend/app/utils/ControllerUtil.java, datahub-frontend/conf/routes, gms/api/src/main/idl/com.linkedin.dataplatform.dataPlatforms.restspec.json, gms/api/src/main/snapshot/com.linkedin.dataplatform.dataPlatforms.snapshot.json, gms/client/src/main/java/com/linkedin/dataplatform/client/DataPlatforms.java, gms/factories/src/main/java/com/linkedin/dataplatform/factory/DataPlatformLocalDaoFactory.java, gms/impl/src/main/java/com/linkedin/metadata/resources/dataplatform/DataPlatforms.java, gms/impl/src/main/java/com/linkedin/metadata/resources/dataplatform/utils/DataPlatformsUtil.java, gms/impl/src/main/resources/DataPlatformInfo.json, gms/impl/src/test/java/com/linkedin/metadata/resources/dataplatform/utils/DataPlatformsUtilTest.java
Tested the change E2E using `docker/dev.sh`.
Fixes https://github.com/linkedin/datahub/issues/1725
=> feat(data-platforms): adding rest resource for /dataPlatforms and mid-tier support

NOTICE
Copies the file from the wherehows branch.
=> docs: add NOTICE

metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/KafkaConfig.java
Fixes https://github.com/linkedin/datahub/issues/1829
=> fix(ingestion): set schema registry URL correctly for FMCE producer

gms/impl/src/main/resources/DataPlatformInfo.json, gms/impl/src/test/java/com/linkedin/metadata/resources/dataplatform/utils/DataPlatformsUtilTest.java
=> feat(platform): add "postgres" as a supported data platform

li-utils/src/main/java/com/linkedin/common/urn/ChartUrn.java, li-utils/src/main/java/com/linkedin/common/urn/DashboardUrn.java, li-utils/src/main/java/com/linkedin/common/urn/Urn.java, li-utils/src/main/pegasus/com/linkedin/common/ChartUrn.pdl, li-utils/src/main/pegasus/com/linkedin/common/DashboardUrn.pdl, metadata-models/src/main/pegasus/com/linkedin/chart/ChartDataSourceType.pdl, metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl, metadata-models/src/main/pegasus/com/linkedin/chart/ChartQuery.pdl, metadata-models/src/main/pegasus/com/linkedin/chart/ChartType.pdl, metadata-models/src/main/pegasus/com/linkedin/common/AccessLevel.pdl, metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardInfo.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/ChartAspect.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/DashboardAspect.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/entity/ChartEntity.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/entity/DashboardEntity.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/relationship/Contains.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/relationship/DownstreamOf.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/search/ChartDocument.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/search/DashboardDocument.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/ChartSnapshot.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/DashboardSnapshot.pdl
RFC for this change: https://github.com/linkedin/datahub/pull/1778
=> feat(dashboard): Dashboard metadata models

gms/factories/src/main/java/com/linkedin/common/factory/KafkaEventProducerFactory.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/KafkaConfig.java, metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/KafkaConfig.java
link to the related issue: https://github.com/linkedin/datahub/issues/1892
=> add default KAFKA_BOOTSTRAP_SERVER

build.gradle, metadata-ingestion-examples/common/build.gradle
=> build: fix build by adding zookeeper dependency explicitly

README.md, docs/links.md
=> docs: add Budapest talk

README.md, docs/townhalls.md
=> Update of townhall schedule for the next quarter

docs/how/entity-onboarding.md, gms/factories/src/main/java/com/linkedin/gms/factory/common/KafkaEventProducerFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/common/LocalEbeanServerConfigFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/common/Neo4jDriverFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/common/TopicConventionFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataplatform/DataPlatformLocalDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataprocess/DataProcessDAOFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataprocess/DataProcessSearchDAOFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataset/DatasetBrowseDAOFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataset/DatasetDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataset/DatasetQueryDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/dataset/DatasetSearchDAOFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpGroupDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpGroupSearchDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpUserDaoFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/identity/CorpUserSearchDaoFactory.java, gms/war/src/main/webapp/WEB-INF/beans.xml, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/ElasticSearchConfig.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/Neo4jConfig.java
Fixes https://github.com/linkedin/datahub/issues/1658
=> refactor(gms): reorganize GMS factory namespace

README.md
=> Update next townhall meeting id

README.md
=> Announce DataHub's participation in Hacktoberfest

README.md
=> Announcement on v0.5.0 of DataHub

docker/docker-compose.yml
Fixes #1928
Did a quick end-to-end test to verify that search is working as expected.
=> build(docker): use community version of ES & Kibana in quickstart

README.md, docs/links.md
=> docs: update links

datahub-web/@datahub/shared/types/configurator/configurator.d.ts, datahub-web/yarn.lock
- Fixes #1875 Removes non-inclusive language from our open source
- Will rely on build tests as the code change does not affect anything currently in OS production
=> Moves remaining references to non-inclusive language

metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java
=> refactor: use better assertj assertions.

README.md
=> announce release of v0.6.0

gms/database/scripts/index/dataset-bootstrap.sql
=> feat: add SCSI bootstrap script for datasets

docs/townhalls.md
=> docs: update agenda of town hall

build.gradle, gms/factories/build.gradle, gms/factories/src/main/java/com/linkedin/gms/factory/common/LocalDAOStorageConfigFactory.java, gms/factories/src/test/java/com/linkedin/gms/factory/common/LocalDAOStorageConfigFactoryTest.java, gms/factories/src/test/resources/localDAOBadConfig.json, gms/factories/src/test/resources/localDAOStorageCompleteConfig.json, gms/factories/src/test/resources/localDAOStorageEmptyConfig.json, gms/factories/src/test/resources/localDAOStorageMergedAspectsConfig.json, gms/factories/src/test/resources/localDAOStorageSomeAspectsConfig.json
=> feat: add LocalDAOStorageConfigFactory for SCSI

docs/quickstart.md
=> docs: update UI credential requirement for Quickstart

README.md, docs/townhall-history.md, docs/townhalls.md
Updates to town hall history and next town hall
=> Updates to town hall history and next town hall

li-utils/src/main/javaPegasus/com/linkedin/common/urn/DatasetFieldUrn.java
=> fix: fix build definition of DatasetFieldUrn

contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml
=> fix: indentation value in helm deployment templates

contrib/kubernetes/datahub/Chart.yaml, contrib/kubernetes/datahub/README.md, contrib/kubernetes/datahub/charts/datahub-frontend/Chart.yaml, contrib/kubernetes/datahub/charts/datahub-frontend/README.md, contrib/kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-frontend/values.yaml, contrib/kubernetes/datahub/charts/datahub-gms/Chart.yaml, contrib/kubernetes/datahub/charts/datahub-gms/README.md, contrib/kubernetes/datahub/charts/datahub-gms/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-gms/values.yaml, contrib/kubernetes/datahub/charts/datahub-mae-consumer/Chart.yaml, contrib/kubernetes/datahub/charts/datahub-mae-consumer/README.md, contrib/kubernetes/datahub/charts/datahub-mae-consumer/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-mae-consumer/values.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/Chart.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/README.md, contrib/kubernetes/datahub/charts/datahub-mce-consumer/templates/deployment.yaml, contrib/kubernetes/datahub/charts/datahub-mce-consumer/values.yaml
=> feat(kubernetes): Add pod-level annotations to the datahub helm charts

datahub-web/@datahub/data-models/addon/entity/dataset/fields.ts, docker/elasticsearch-setup/dataset-index-config.json, metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DatasetIndexBuilderTest.java, metadata-models/src/main/pegasus/com/linkedin/metadata/search/DatasetDocument.pdl
Enable search of datasets by field names. Fixes #1993 
Already existing users needs to rebuild dataset index to take advantage of search by field names of dataset
=> feat(dataset): Enable search of datasets by field names

docs/townhalls.md
Townhall agenda for December 4
=> Townhall agenda for December 4

docker/elasticsearch-setup/dataset-index-config.json
Fix dataset index creation issue. Fixes #2014
=> Fix dataset index creation issue

README.md
Adding links to latest DataHub blog post.
=> Update README.md with latest blog post

docs/townhalls.md
=> Townhall Agenda for Jan 15

docs/what/gms.md
Fix broken link to the Restli resource base classes.
=> Fix broken link to the Restli resource

docs/townhalls.md
Update townhall schedule docs to third friday of every month
=> Update townhall schedule docs to third friday of every month

build.gradle, gms/impl/src/integTest/java/com/linkedin/metadata/ChartSearchSanityTest.java, gms/impl/src/integTest/java/com/linkedin/metadata/CorpUserSearchSanityTest.java, gms/impl/src/integTest/java/com/linkedin/metadata/DashboardSearchSanityTest.java, gms/impl/src/integTest/java/com/linkedin/metadata/DataProcessSearchSanityTest.java, gms/impl/src/integTest/java/com/linkedin/metadata/DatsetsSearchSanityTest.java, gms/impl/src/main/resources/index/data-process/settings.json
Required editing the search tests for the new search config tests.
=> feat: update GMA to 0.2.35

metadata-ingestion/README.md
=> docs: drop obsolete info on mysql-etl

README.md
=> docs: Updating README with upcoming TownHall info

metadata-ingestion/sql-etl/common.txt
=> fix(SQL ingest): Bump confluent-kafka version

datahub-web-react/build.gradle, datahub-web-react/package.json, datahub-web-react/src/App.test.tsx, datahub-web-react/src/App.tsx, datahub-web-react/src/components/browse/BrowseList.tsx
Also fixes the existing lint errors
=> fix(react): including eslint in CI

docs/what/urn.md
Signed-off-by: mahao <allenhaozi@gmail.com>
=> docs: fix URN and DatasetUrn links 

datahub-web/packages/data-portal/app/templates/components/datasets/containers/dataset-lineage-downstreams.hbs, datahub-web/packages/data-portal/app/templates/components/datasets/containers/dataset-lineage-upstreams.hbs
=> fix: Update pendulum animation component for dataset lineage

build.gradle
Resolves https://github.com/linkedin/datahub/issues/2088. See https://github.com/linkedin/datahub-gma/pull/76 for discussion. Tested and works on my Linux-based machine.
=> fix: Bump GMA version

datahub-web-react/src/components/entity/user/UserHeader.tsx, datahub-web-react/src/components/entity/user/UserProfile.tsx, datahub-web-react/src/graphql/user.graphql
=> feat(React): Powering user page through graphql endpoint

docs/townhalls.md
=> docs: Update with Feb 19 Agenda

docs/how/entity-onboarding.md, metadata-ingestion/README.md, metadata-ingestion/examples/recipes/secured_kafka_to_console.yml
Also fixes a couple minor typos.
=> docs(ingest): clarify docs for new ingestion framework

metadata-ingestion/examples/airflow/generic_recipe_sample_dag.py, metadata-ingestion/examples/airflow/mysql_sample_dag.py, metadata-ingestion/src/datahub/configuration/common.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/api/sink.py, metadata-ingestion/src/datahub/ingestion/api/source.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/src/datahub/ingestion/source/kafka.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py, metadata-ingestion/tests/unit/serde/test_serde.py, metadata-ingestion/tests/unit/test_pipeline.py
- Adds a nice bolded status message the the end of a pipeline run.
- Enables pipeline runners to raise an exception when an failure occurs.
=> feat(ingest): improve error reporting for pipelines

metadata-ingestion/tests/integration/fixtures/sql_fixtures.py, metadata-ingestion/tests/integration/mysql/test_mysql.py, metadata-ingestion/tests/integration/sql_server/mssql_mces_golden.json, metadata-ingestion/tests/integration/sql_server/test_sql_server.py
- Now it tests for correctness, not just that it doesn't crash
- Also avoids spawning a child process in the integration test
=> test(ingest): verify the output of mssql

metadata-ingestion/README.md
=> docs(ingest): add solutions for common install issues

metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> fix(ingest): update sample MCEs based on MLModel changes

metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> fix(ingest): gracefully handle unknown types

metadata-ingestion/scripts/ci.sh
=> ci(ingest): run apt update

metadata-models/src/main/pegasus/com/linkedin/common/Owner.pdl
More details on the issue here: https://github.com/linkedin/datahub/issues/2138
@frsann @shirshanka
=> docs(Ownership): making lack of support for ownergroups in frontend explicit in pdl

metadata-ingestion/README.md, metadata-ingestion/setup.cfg, metadata-ingestion/src/datahub/ingestion/source/postgres.py
=> feat(ingest): support Postgres PostGIS extensions

datahub-dao/src/main/java/com/linkedin/datahub/dao/DaoFactory.java, datahub-dao/src/main/java/com/linkedin/datahub/dao/table/GmsDao.java, docker/datahub-frontend/env/docker.env, docker/datahub-mce-consumer/env/docker.env, metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/RemoteWriterConfig.java, metadata-utils/src/main/java/com/linkedin/metadata/restli/DefaultRestliClientFactory.java
Fixes https://github.com/linkedin/datahub/issues/2113
=> feat(datahub-dao): enable services to access gms over https

datahub-frontend/README.md
=> docs(Frontend): Update docs to clarify running local frontend w/ local react app

.github/workflows/docker-ingestion.yml, docker/datahub-ingestion/Dockerfile, docker/datahub-ingestion/README.md, metadata-ingestion/plugin_requirements.txt
=> ci(ingest): setup docker container for metadata ingestion

gms/impl/src/main/resources/DataPlatformInfo.json, metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/api/report.py, metadata-ingestion/src/datahub/ingestion/source/bigquery.py, metadata-ingestion/src/datahub/ingestion/source/mssql.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py, metadata-ingestion/tests/integration/mysql/mysql_mce_golden.json
- Only add database name where appropriate
- Minor bug fixes in the bigquery source (closes #2153)
=> fix(ingest): bigquery source and dataset naming fixes

datahub-web/@datahub/entities/addon/components/datasets/dataset-schema.hbs, datahub-web/@datahub/entities/tests/integration/components/datasets/dataset-schema-test.ts
=> fix: Rename 'JSON' sub-tab under schema tab to 'Raw'

README.md, docs/townhall-history.md, docs/townhalls.md
=> doc(townhall): Add links for Feb 19, upcoming townhall on Mar 19

metadata-ingestion/src/datahub/configuration/kafka.py
=> fix(ingest): loosen Kafka broker validation

.github/workflows/documentation.yml
=> ci(docs): only deploy docs on main repo

README.md, datahub-frontend/README.md, docs-website/docusaurus.config.js, docs-website/generateDocsDir.ts, docs-website/src/pages/index.js, metadata-jobs/mae-consumer-job/README.md, metadata-jobs/mce-consumer-job/README.md
=> fix(docs): fix broken links

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
**Scope**
This PR only affects the GQL api. 
**Changes**
Previously, DataPlatforms had to exist in GMS at read time, else an exception would be thrown. This change loosens read time restrictions, simply falling back to creating an "unknown" data platform if one cannot be found in GMS.
=> fix(GraphQL): Loosen read time validations on DataPlatforms

docs-website/sidebars.js, docs/rfc/active/tags/README.md
=> feat(tags): RFC for tags

docs-website/generateDocsDir.ts, docs-website/sidebars.js, docs/how/search-over-new-field.md, gms/README.md
Also improves the error message, fixes a few more links throughout, and makes the link validation stricter.
=> feat(docs): automatically populate sidebar with RFCs

metadata-ingestion/examples/mce_files/bootstrap_mce.json
Creating a sample tag that demonstrates a practical use case of tags
=> feat(tags): Enriching sample data for tags

docs/roadmap.md
Project roadmap update based on discussions with LinkedIn team.
=> docs(roadmap): update project roadmap

docs/how/entity-onboarding.md, metadata-ingestion/README.md, metadata-ingestion/examples/recipes/file_to_datahub.yml, metadata-ingestion/examples/recipes/kafka_to_console.yml, metadata-ingestion/examples/recipes/kafka_to_datahub.yml, metadata-ingestion/examples/recipes/kafka_to_datahub_rest.yml, metadata-ingestion/examples/recipes/secured_kafka_to_console.yml, metadata-ingestion/src/datahub/configuration/common.py, metadata-ingestion/src/datahub/configuration/kafka.py, metadata-ingestion/src/datahub/emitter/kafka_emitter.py, metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_kafka.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/tests/unit/test_kafka_sink.py
- create metadata emitter interfaces for REST and Kafka
- fix a minor Kafka config parsing issue
- update ingestion readme
=> feat(ingest): standalone metadata emitters

metadata-ingestion/README.md, metadata-ingestion/plugin_requirements.txt, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/source/athena.py, metadata-ingestion/src/datahub/ingestion/source/source_registry.py
=> feat(ingestion): add aws athena ingestion source

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/athena.py
=> refactor(ingestion): improve athena source api and documentation

docker/datahub-ingestion/Dockerfile
=> fix(ingest): use python extras in docker image

metadata-ingestion/setup.py
=> fix(ingest): pin version of avro-gen3

datahub-web-react/src/app/browse/BrowseResultCard.tsx, datahub-web-react/src/app/browse/BrowseResults.tsx, datahub-web-react/src/app/entity/user/UserOwnership.tsx, datahub-web-react/src/app/entity/user/UserProfile.tsx, datahub-web-react/src/app/entity/user/__tests__/UserDetails.test.tsx, datahub-web-react/src/app/entity/user/__tests__/UserOwnership.test.tsx, datahub-web-react/src/app/search/SearchPage.tsx, datahub-web-react/src/conf/theme/theme_light.config.json
**Scope**
React app
**Changes**
1. Small enhancements in User profile page
2. Small enhancements in browse results
3. Change the theme border color to light gray.
=> refactor(React): Misc UI improvements

docs/how/configure-oidc-react.md, docs/how/sso/configure-oidc-react-google.md, docs/how/sso/configure-oidc-react-okta.md
**Scope**
OIDC Docs
**Changes**
Fixing some minor inaccuracies in the main OIDC guide.
=> docs(React): Oidc React Doc Updates 

datahub-web-react/src/app/entity/EntityPage.tsx, datahub-web-react/src/app/entity/EntityRegistry.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/app/search/AllEntitiesSearchResults.tsx, datahub-web-react/src/app/search/EntityGroupSearchResults.tsx, datahub-web-react/src/app/search/SearchPage.tsx, datahub-web-react/src/utils/customGraphQL/useGetAllEntitySearchResults.ts
**Scope**
React App
**Changes**
1. Add loading indicator to "all" entity search tab
2. Add "no data" feedback if no results are found across all entities
3. Replace hardcoded entity search in UserDetails with only entities enabled for search
4. Add light gray "no description" to search result w empty descripton
5. Fix "user is not a browsable entity" error from BrowsableEntityPage
=> refactor(React): All entity search UI + misc improvements

gms/factories/src/main/java/com/linkedin/gms/factory/datajob/DataFlowBrowseDAOFactory.java, gms/factories/src/main/java/com/linkedin/gms/factory/datajob/DataJobBrowseDAOFactory.java
=> fix(dataflow): fixing browse dao access for flows and jobs

docs/townhalls.md
=> docs: adding mar-19 townhall agenda

metadata-ingestion/README.md, metadata-ingestion/scripts/avro_codegen.py, metadata-ingestion/scripts/ci.sh, metadata-ingestion/scripts/datahub_docker.sh, metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/api/common.py, metadata-ingestion/src/datahub/ingestion/api/registry.py, metadata-ingestion/src/datahub/ingestion/api/sink.py, metadata-ingestion/src/datahub/ingestion/api/source.py, metadata-ingestion/src/datahub/ingestion/extractor/mce_extractor.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/src/datahub/ingestion/sink/console.py, metadata-ingestion/src/datahub/ingestion/sink/file.py, metadata-ingestion/src/datahub/ingestion/source/metadata_common.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py, metadata-ingestion/tests/conftest.py, metadata-ingestion/tests/unit/serde/test_serde.py, metadata-ingestion/tests/unit/serde/test_serde_chart_snapshot.json, metadata-models/src/main/pegasus/com/linkedin/schema/UrnForeignKey.pdl
- Add an option to set the logging level to debug from the command line
- Add more comprehensive testing for SerDe and fix a bug in chart info serialization
- Add docs about the ingestion Docker image
Fixes
- Autogenerate run_id using uuid
- Improve error handling and correctly use info, debug, and error log levels
- CI improvements for black, flake8, and mypy
=> feat(ingest): various minor fixes

README.md, docs-website/docusaurus.config.js, docs-website/src/pages/index.js, docs/roadmap.md, docs/slack.md
=> fix: update slack links

metadata-ingestion/examples/demo_data/demo_data.json, metadata-ingestion/examples/demo_data/enrich.py, metadata-ingestion/examples/demo_data/generate_demo_data.sh
Add empty global tags and editable schema metadata, so we start fresh each time we ingest the demo data.
=> refactor(demo-data): Add empty global tags to BQ demo data

docs/roadmap.md
=> docs: update roadmap progress

docker/docker-compose.yml, docker/elasticsearch-setup/create-indices.sh, gms/impl/src/main/resources/index/chart/settings.json, gms/impl/src/main/resources/index/corp-user/settings.json, gms/impl/src/main/resources/index/dashboard/settings.json, gms/impl/src/main/resources/index/dataflow/settings.json, gms/impl/src/main/resources/index/datajob/settings.json, gms/impl/src/main/resources/index/ml-model/settings.json, gms/impl/src/main/resources/index/tags/settings.json
Add to docker compose and update create_indices script
=> feat(es-7-migration): Add to docker compose and update create_indices script

README.md
=> docs: update readme for v0.7.0 release

docker/datahub-frontend/Dockerfile, docker/dev.sh, docker/docker-compose.dev.yml
- Makes dev.sh use only local artifacts
- Tested manually on my local machine
=> fix: use local datahub-frontend in dev.sh

datahub-web-react/src/app/home/HomePageHeader.tsx
this makes the transitions between suggestions a bit less distracting
=> feat(react): update search suggestion styling

metadata-ingestion/README.md, metadata-ingestion/examples/recipes/dbt_to_datahub.yml, metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/src/datahub/ingestion/source/source_registry.py, metadata-ingestion/tests/integration/dbt/dbt_catalog.json, metadata-ingestion/tests/integration/dbt/dbt_manifest.json, metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json, metadata-ingestion/tests/integration/dbt/test_dbt.py
Original PR opened in [luck02:datahub](https://github.com/luck02/datahub/pull/1)
@hsheth2 That PR has moved here now, thanks for helping!
=> feat(ingest Dbt metadata)

metadata-ingestion/README.md
=> docs(ingest): add python versions badge

metadata-ingestion/setup.py
See https://github.com/tswast/pybigquery/pull/82.
=> fix(ingest): use custom pybigquery version

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsClientFactory.java
=> feat(react): enable the react frontend to use SSL when talking with GMS

metadata-ingestion/README.md, metadata-ingestion/scripts/update_golden_files.sh, metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/mongodb.py, metadata-ingestion/src/datahub/ingestion/source/source_registry.py, metadata-ingestion/tests/integration/dbt/test_dbt.py, metadata-ingestion/tests/integration/docker-compose.yml, metadata-ingestion/tests/integration/fixtures/sql_fixtures.py, metadata-ingestion/tests/integration/mongodb/mongodb_mce_golden.json, metadata-ingestion/tests/integration/mongodb/setup/mongo_init.js, metadata-ingestion/tests/integration/mongodb/setup/wait-for-it.sh, metadata-ingestion/tests/integration/mongodb/test_mongodb.py
Adds a MongoDB connector (basic list of databases and collections only) and associated integration test. Closes #2280.
=> feat(ingest): MongoDB ingestion source

gms/factories/src/main/java/com/linkedin/gms/servlet/HealthCheck.java
Add Healthcheck servlet for GMS to enable healthcheck. The file wasn't added into the previous PR https://github.com/linkedin/datahub/pull/2288
=> feat(healthcheck): Add Healthcheck servlet for GMS

docs/how/search-onboarding.md
=> docs(search-onboarding): fix index builder link

docker/docker-compose.yml, docs/debugging.md, metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/check/check_cli.py, metadata-ingestion/src/datahub/check/docker.py, metadata-ingestion/src/datahub/check/json_file.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/source/mce_file.py
- Add a `datahub check local-docker` command
- Refactor check commands into a group
- Add an elasticsearch healthcheck
=> feat: datahub check local-docker

metadata-ingestion/src/datahub/check/docker.py
=> fix(cli): validate only required containers

metadata-ingestion/README.md, metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/configuration/config_loader.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/tests/unit/config/bad_variable_expansion.yml, metadata-ingestion/tests/unit/config/basic.toml, metadata-ingestion/tests/unit/config/basic.yml, metadata-ingestion/tests/unit/config/simple_variable_expansion.yml, metadata-ingestion/tests/unit/config/test_config_loader.py
- Support environment variable expansion in recipe files
- Refactor config loading mechanism
=> feat(ingest): environment variables in recipes

docs/how/kafka-config.md, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java, metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
=> feat(kafka-config): add variable KAFKA_CONSUMER_GROUP_ID to override group id value for kafka consumer

contrib/kubernetes/datahub/README.md, contrib/kubernetes/datahub/templates/elasticsearch-setup-job.yml, contrib/kubernetes/datahub/values.yaml
=> feat(k8s): Add k8s hook in helm chart for setting up elasticsearch

README.md, docs/faq.md, docs/townhall-history.md, docs/townhalls.md
=> docs: Update next townhall details, fixup links and misc docs

docker/datahub-gms/start.sh
Fix issue introduced https://github.com/linkedin/datahub/pull/2251 where gms fails to start
=> fix(docker): Fix issue in gms start.sh

datahub-web-react/README.md
=> docs(theme): making `yarn start` instructions more explicit

contrib/kubernetes/datahub/README.md, contrib/kubernetes/datahub/templates/elasticsearch-setup-job.yml, contrib/kubernetes/datahub/values.yaml
=> fix(k8s): make es-setup job parameters more contextual

metadata-ingestion/tests/integration/dbt/dbt_manifest.json, metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json
=> (test) dbt copypasta

datahub-web-react/.eslintrc.js, datahub-web-react/src/app/entity/dataset/profile/__tests__/Schema.test.tsx, datahub-web-react/src/app/entity/dataset/profile/__tests__/SchemaDescriptionField.test.tsx, datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx, datahub-web-react/src/app/entity/dataset/profile/schema/SchemaDescriptionField.tsx
=> feat(react): add description edit behavior along with modal, update UX

metadata-ingestion/README.md, metadata-ingestion/src/datahub/check/check_cli.py, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/api/registry.py, metadata-ingestion/tests/unit/test_plugin_system.py
=> fix(cli): add --verbose flag for `datahub check plugins`

metadata-ingestion/README.md, metadata-ingestion/developing.md, metadata-ingestion/src/datahub/__main__.py
=> fix(ingest): support `python3 -m datahub`

datahub-web-react/src/app/entity/dataset/profile/DatasetProfile.tsx
=> feat(react): improving error logging on dataset entity

datahub-web-react/src/app/entity/dataset/profile/schema/SchemaDescriptionField.tsx
=> feat(react): keep original description shows in edit modal

metadata-ingestion/src/datahub/check/docker.py
=> feat(cli): add support for checking docker memory usage

datahub-web-react/src/app/browse/BrowsePath.tsx, datahub-web-react/src/app/lineage/LineageEntityNode.tsx, datahub-web-react/src/app/lineage/types.ts, datahub-web-react/src/app/lineage/utils/constructFetchedNode.ts, datahub-web-react/src/app/lineage/utils/constructTree.ts, datahub-web-react/src/app/lineage/utils/extendAsyncEntities.ts, datahub-web-react/src/graphql/dataset.graphql
=>  feat(react): add icons on entities, updated styling in LineageViz

datahub-web-react/src/app/home/HomePageBody.tsx, datahub-web-react/src/app/home/HomePageHeader.tsx, datahub-web-react/src/app/shared/ManageAccount.tsx, datahub-web-react/src/conf/theme/theme_dark.config.json, datahub-web-react/src/conf/theme/theme_light.config.json
=> feat(react): add dropdown menu links, menu styling, removed warnings

datahub-web-react/src/app/browse/BrowseResults.tsx
=> feat(react): add empty state UI for browse when no entities

datahub-web-react/src/app/browse/BrowseResults.tsx, datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx, datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx, datahub-web-react/src/app/entity/dataset/profile/DatasetHeader.tsx, datahub-web-react/src/app/entity/shared/Ownership.tsx, datahub-web-react/src/app/entity/tag/TagProfile.tsx, datahub-web-react/src/app/entity/tag/__tests__/TagProfile.test.tsx, datahub-web-react/src/app/entity/user/UserHeader.tsx, datahub-web-react/src/app/entity/user/preview/Preview.tsx, datahub-web-react/src/app/home/HomePageHeader.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/app/shared/ManageAccount.tsx, datahub-web-react/src/app/shared/avatar/CustomAvatar.tsx
=> feat(react): update avatar to use initial if no image, refactor all avatars with custom one

datahub-web-react/src/app/entity/user/UserOwnership.tsx, datahub-web-react/src/app/entity/user/UserProfile.tsx, datahub-web-react/src/app/entity/user/__tests__/UserDetails.test.tsx, datahub-web-react/src/app/entity/user/__tests__/UserOwnership.test.tsx
=> Fix ownership rendering

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
=> feat(react): hide Owned By label in card if no owners

metadata-ingestion/src/datahub/__init__.py, metadata-ingestion/src/datahub/entrypoints.py
=> fix(ingest): report correct version status in dev

metadata-ingestion/README.md, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/sql_generic.py
=> feat(ingest): add generic sqlalchemy source

datahub-web-react/src/app/browse/BrowsableEntityPage.tsx, datahub-web-react/src/app/browse/BrowsePath.tsx
=> feat(react): fix browse link of last breadcrumb linked to unknown page

datahub-web-react/src/app/entity/dataset/profile/DatasetHeader.tsx
=> feat(react): fix long descriptions overflow issue in lineage side panel

metadata-ingestion/src/datahub/ingestion/source/postgres.py
Postgres has a three level hierarchy (database, schema, table), which we want to model correctly during ingestion.
=> fix(ingest): add db name to postgres URNs

metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/src/datahub/ingestion/source/kafka.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> feature(ingestion): Make origin/fabric_type configurable

contrib/kubernetes/datahub/templates/elasticsearch-setup-job.yml, contrib/kubernetes/datahub/templates/kafka-setup-job.yml, contrib/kubernetes/datahub/templates/mysql-setup-job.yml
Add extraEnvs to setup jobs for flexibility
=> feat(k8s): Add extraEnvs to setup jobs

metadata-ingestion/setup.py
=> fix(ingest): add sqlalchemy extra

metadata-ingestion/examples/mce_files/bootstrap_mce.json, metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/tests/unit/serde/test_serde.py
=> fix(ingest): properly handle fieldDiscriminator with restli

metadata-ingestion/setup.py
Closes #2375. See also - https://github.com/hsheth2/avro_gen/commit/17ed0e177958c7bd90cc442c09b055449a670ffe.
=> fix(ingest): bump avro-gen3

datahub-web-react/src/app/lineage/LineageExplorer.tsx
=> fix(react): fix button link in lineage sidebar

datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx, datahub-web-react/src/app/entity/dataset/profile/schema/TypeIcon.tsx, metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> feat(react): add schema table visual hierarchy, ellipsis when over max length limit

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/snowflake.py
=> fix(ingest): include database info for snowflake

metadata-ingestion/README.md, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/integrations/airflow/lineage_backend.py, metadata-ingestion/tests/unit/test_airflow.py
Unit tests passing locally with both Airflow 1.10.15 and 2.0.2
=> fix(ingest): ensure lineage backend upstreams are entities

docs/townhalls.md
=> docs: Update agenda for Apr 23 townhall

metadata-ingestion/setup.py, metadata-ingestion/tests/unit/test_rest_sink.py
=> fix(ingest): fix chart type enum serialization and add tests for rest emitter

gms/impl/src/main/resources/index/dataflow/mappings.json, gms/impl/src/main/resources/index/dataflow/settings.json, gms/impl/src/main/resources/index/datajob/mappings.json, metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DataFlowIndexBuilder.java, metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DataJobIndexBuilder.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/common/DataFlowTestUtils.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/common/DataJobTestUtils.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DataFlowIndexBuilderTest.java, metadata-builders/src/test/java/com/linkedin/metadata/builders/search/DataJobIndexBuilderTest.java, metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/IndexBuildersConfig.java, metadata-models/src/main/pegasus/com/linkedin/metadata/search/DataFlowDocument.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/search/DataJobDocument.pdl
Searching for datajobs and dataflows was not implemented correctly, so this PR should fix it. The `mappings.json` might be suboptimal, so please take a close look at them.
=> Fix datajob and dataflow search

metadata-ingestion/src/datahub/ingestion/source/snowflake.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> fix(ingest): map some custom snowflake types

datahub-web-react/src/app/lineage/LineageExplorer.tsx
=> fix(react): update lineage sidebar buttons

metadata-ingestion/src/datahub/ingestion/source/ldap.py, metadata-ingestion/tests/integration/ldap/ldap_mce_golden.json, metadata-ingestion/tests/unit/test_ldap_source.py
The main change is the addition of a "handle_group" function. The rest is just done to follow general linting rules. Can remove this or split the commits if not needed. (Was not sure if we were going to commit it.)
I am unsure about two things though, will address them in the comments.
Closes #2434
=> feat(ingestion) LDAP groups ingestion

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/ChartType.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/mappers/ChartUpdateInputMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/DashboardType.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/mappers/DashboardUpdateInputMapper.java, datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx, datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx, datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx, datahub-web-react/src/graphql/browse.graphql, datahub-web-react/src/graphql/search.graphql
**Scope**
These changes impact the React app.
**Changes**
1. Fetch GlobalTags in GraphQL for Entity Search + Browse 
2.  Completes implementation of Ownership updates for Dashboards + Charts.
**Status**
=> feat(React): Adding Tags to Previews & Fixing Dashboard / Charts Ownership Updates

datahub-web-react/package.json, datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx, datahub-web-react/src/app/entity/dataset/profile/schema/TypeIcon.tsx, datahub-web-react/yarn.lock
=> feat(react): update schema table hierarchy

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/snowflake.py, metadata-ingestion/tests/unit/test_snowflake_source.py
=> fix(ingest): add snowflake warehouse and role to config

metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py, metadata-ingestion/src/datahub/integrations/airflow/hooks.py, metadata-ingestion/tests/unit/test_airflow.py
- use a session to keep the connect alive
- add option to include a bearer token for auth
- print curl commands in debug mode
=> fix(ingest): various updates to datahub rest sink

metadata-ingestion/pyproject.toml, metadata-ingestion/setup.cfg, metadata-ingestion/tests/unit/test_rest_sink.py
- Create pyproject.toml config
- Create a config for black excludes
- Move isort config to pyproject file
=> fix(ingest): setup pyproject.toml

repositories.gradle
=> fix(build): remove bintray deps

metadata-ingestion/src/datahub/check/docker.py
=> fix(cli): check docker setup containers

metadata-ingestion/README.md
=> docs(ingest): clarify options field and fix bigquery sample config

datahub-web-react/src/app/entity/chart/profile/ChartDashboards.tsx, datahub-web-react/src/app/entity/chart/profile/ChartProfile.tsx
=> feat(react): add dashboards tab in charts entity

metadata-ingestion/tests/unit/test_schema_util.py
=> test(ingest): fix mypy issue in schema util test

metadata-ingestion/src/datahub/integrations/airflow/lineage_backend.py, metadata-ingestion/tests/unit/test_airflow.py
Should merge #2451 first, and then I'll rebase.
=> fix(ingest): support Airflow 1.10.x style lineage in Airflow 2

metadata-ingestion/README.md
Updating metadata ingestion readme to include docs on superset source
@hsheth2
=> docs(metadata-ingestion): Update README.md

metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> fix(ingest): update schema structure with more real like data

datahub-web-react/src/app/entity/dashboard/profile/DashboardProfile.tsx, datahub-web-react/src/graphql/fragments.graphql, metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> feat(react): add custom properties tab on dashboard profile page (#2439)

metadata-ingestion/src/datahub/integrations/airflow/hooks.py
=> fix(ingest): determine airflow hook type from name

.github/workflows/build-and-test.yml
This is the first step before we can check in a couple of the codegen files.
=> build: ensure files are not changed in CI

metadata-ingestion/developing.md
=> docs(ingest): add gradle build step to setup as well

datahub-web-react/.eslintrc.js, datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/entity/dataset/profile/DatasetProfile.tsx, datahub-web-react/src/app/entity/dataset/profile/Documentation.tsx, datahub-web-react/src/app/entity/dataset/profile/__tests__/Documentation.test.tsx, datahub-web-react/src/app/home/HomePageHeader.tsx, datahub-web-react/src/app/search/SearchablePage.tsx, datahub-web-react/src/app/useGetAuthenticatedUser.tsx, datahub-web-react/src/utils/test-utils/TestPageContainer.tsx
**Scope**
React app
**Changes**
1. Throw errors when on unexpected results within "useGetAuthenticatedUser" hook
2. Refactor `Documentation.tsx` to use "useGetAuthenticatedUser" hook
=> refactor(react): Use useGetAuthenticatedUser hook to get the logged in user.

metadata-ingestion/README.md, metadata-ingestion/scripts/install_editable_versions.sh, metadata-ingestion/setup.py
=> feat(ingest): support hive over http

metadata-ingestion/README.md, metadata-ingestion/setup.py
Tested against an Azure HDInsight instance. See also: https://github.com/hsheth2/PyHive/commit/937369978d1b599e3e38d5e3bac94fb43f37d997.
=> fix(ingest): support https connections with cookies in Hive ingestion

docs/roadmap.md
=> docs: Update roadmap with accomplished items

metadata-ingestion/README.md, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> feat(ingest): capture table properties if available

metadata-ingestion/setup.cfg
=> ci(ingest): ensure datahub imports work

metadata-ingestion/README.md
=> docs: fixed MCE file recipe example

metadata-ingestion/src/datahub/integrations/airflow/lineage_backend.py
Follow up on #2501 cc @gabe-lyons
=> fix(ingest): remove double edges from Airflow lineage backend

metadata-ingestion/README.md, metadata-ingestion/examples/airflow/generic_recipe_sample_dag.py, metadata-ingestion/examples/airflow/mysql_sample_dag.py, metadata-ingestion/src/datahub/configuration/config_loader.py
=> docs(ingest): improve airflow explanations and examples

metadata-ingestion/build.gradle
=> fix(build): only check for src/ and tests/ directories for lint checks

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
=> feat(react): set fixed height for dataset preview

datahub-web-react/src/app/entity/chart/profile/ChartHeader.tsx, datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx, datahub-web-react/src/app/entity/dataFlow/profile/DataFlowHeader.tsx, datahub-web-react/src/app/entity/dataJob/profile/DataJobHeader.tsx
=> fix(react): fixing import issue from usergroups and analytics conflict

datahub-web-react/src/app/entity/shared/Ownership.tsx
=> fix(react): fix type issue with adding new in ownership

metadata-ingestion/README.md, metadata-ingestion/examples/recipes/secured_kafka_to_console.yml
=> docs(ingest): improve kafka schema registry config docs

metadata-ingestion/src/datahub/ingestion/source/hive.py
=> fix(ingest): register custom Hive types

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/GlossaryTermUtils.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryTermMapper.java, datahub-graphql-core/src/main/resources/gms.graphql, datahub-web-react/.eslintrc.js, datahub-web-react/src/App.tsx, datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx, datahub-web-react/src/app/entity/glossaryTerm/preview/Preview.tsx, datahub-web-react/src/app/entity/glossaryTerm/preview/__tests__/Preview.test.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/graphql/browse.graphql, datahub-web-react/src/utils/test-utils/TestPageContainer.tsx
=> feat(Business Glossary) Listing, drilling and homepage for business glossary

datahub-web-react/src/app/home/HomePageHeader.tsx, datahub-web-react/src/app/search/SearchPage.tsx, datahub-web-react/src/app/search/SearchablePage.tsx
Followups:
1) we should provide some guidance to users who attempt to do blank searches
2) we should refactor search code so that we don't have search logic in 3 places.
=> fix(search): have search bar ignore blank searches

docs/demo.md, metadata-ingestion/README.md, metadata-ingestion/pyproject.toml, metadata-ingestion/setup.py, metadata-ingestion/src/datahub_provider/_lineage_core.py, metadata-ingestion/src/datahub_provider/entities.py, metadata-ingestion/src/datahub_provider/lineage/datahub.py, metadata-ingestion/tests/unit/test_airflow.py
=> feat(ingest): add options for Airflow lineage backend

README.md, docs/townhall-history.md, docs/townhalls.md
=> docs: town-hall updates and some badges

metadata-ingestion/setup.cfg, metadata-ingestion/tests/test_helpers/mce_helpers.py
=> fix(ingest): check mypy types for test helpers

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/ldap.py
=> fix(ingest): better active directory LDAP support

metadata-ingestion/setup.cfg, metadata-ingestion/tests/unit/test_pipeline.py
=> test(ingest): ensure transformer registry works for aliases

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_tags.py, metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py, metadata-ingestion/tests/unit/test_transform_dataset.py
=> feat(ingest): add dataset tag transformer

metadata-ingestion/build.gradle
=> build(ingest): show diff upon lint failures

metadata-ingestion/README.md
Fixing a typo with the Apache Superset plugin.
=> [README] Fix Superset typo

README.md
=> docs: Add Plum Research to POC adoption section in README.md

datahub-web-react/src/app/entity/dataset/profile/schema/Schema.tsx, datahub-web-react/src/app/entity/dataset/profile/schema/TypeIcon.tsx, datahub-web-react/src/app/shared/avatar/CustomAvatar.tsx, metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> feat(react): add nativeDataType with tooltip over icon in schema, update ingestion

README.md, docs-website/docusaurus.config.js, docs-website/generateDocsDir.ts, docs-website/sidebars.js, docs/demo.md, docs/saas.md
=> fix(docs): various fixes and additions

metadata-ingestion/examples/demo_data/bigquery_covid19_to_file.yml, metadata-ingestion/examples/demo_data/directives.csv, metadata-ingestion/examples/demo_data/enrich.py, metadata-ingestion/examples/demo_data/generate_demo_data.sh
=> feat(ingest): update bigquery demo data

datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/entity/dataFlow/profile/DataFlowDataJobs.tsx, datahub-web-react/src/app/entity/dataFlow/profile/DataFlowProfile.tsx, datahub-web-react/src/app/entity/dataFlow/profile/__tests__/DataFlowProfile.test.tsx, datahub-web-react/src/app/entity/dataJob/preview/Preview.tsx, datahub-web-react/src/app/entity/dataJob/profile/__tests__/DataJobProfile.test.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/graphql/fragments.graphql, datahub-web-react/src/utils/sort/topologicalSort.ts
=>  feat(react): add topological sort feature, update graphql, add tests

datahub-web-react/src/app/entity/dataJob/profile/DataJobHeader.tsx
=> feat(react): add parent flow link on datajob page

metadata-ingestion/src/datahub_provider/_lineage_core.py, metadata-ingestion/tests/unit/test_airflow.py
=> feat(ingest): populate inputDatajobs field in airflow integration

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteForAllResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/AutoCompleteResolver.java, datahub-graphql-core/src/main/resources/gms.graphql, datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/home/HomePageBody.tsx, datahub-web-react/src/app/home/HomePageHeader.tsx, datahub-web-react/src/app/home/__tests__/HomePage.test.tsx, datahub-web-react/src/app/search/SearchBar.tsx, datahub-web-react/src/app/search/SearchHeader.tsx, datahub-web-react/src/app/search/SearchPage.tsx, datahub-web-react/src/app/search/SearchablePage.tsx, datahub-web-react/src/app/search/utils/constants.ts, datahub-web-react/src/app/search/utils/filterSearchQuery.ts, datahub-web-react/src/app/search/utils/navigateToSearchUrl.ts, datahub-web-react/src/app/shared/tags/AddTagModal.tsx, datahub-web-react/src/graphql/search.graphql
=> feat(graphql): redesign autocomplete to search for all entity types, show suggestions grouped by entities

datahub-web-react/src/app/entity/dataFlow/profile/DataFlowDataJobs.tsx, datahub-web-react/src/app/entity/dataFlow/profile/DataFlowProfile.tsx, datahub-web-react/src/app/entity/dataFlow/profile/__tests__/DataFlowProfile.test.tsx, datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx, datahub-web-react/src/app/entity/dataJob/profile/DataJobProfile.tsx, datahub-web-react/src/app/entity/shared/Ownership.tsx
=> feat(react): update collectionname in datajob, update tabs ui/ux

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/check/check_cli.py, metadata-ingestion/src/datahub/ingestion/source/lookml.py
=> fix(ingest): fail gracefully when lookml used on old python versions

docs-website/generateDocsDir.ts, docs-website/src/pages/index.js
=> docs: update homepage text

metadata-ingestion/src/datahub/ingestion/source/glue.py, metadata-ingestion/tests/unit/test_glue_source.py
=> fix(ingestion): improve robustness of glue ingestion source

.github/workflows/docker-elasticsearch-setup.yml, .github/workflows/docker-kafka-setup.yml
Trigger setup job docker action on every push
=> fix(workflow): Trigger setup job docker action on every push

metadata-ingestion/src/datahub/emitter/kafka_emitter.py, metadata-ingestion/tests/unit/test_kafka_sink.py
=> fix(ingest): include urn as key for kafka emitter

docs/modeling/extending-the-metadata-model.md
=> docs(no-code): removing unused snapshot annotations

docker/datahub-upgrade/Dockerfile
=> fix(datahub-upgrade): Removing JVM debug flag for datahub-upgrade container

datahub-frontend/app/react/analytics/AnalyticsService.java
Fix index names in analytics service
=> fix(NoCode): Fix index names in analytics service

docs/advanced/no-code-upgrade.md
Update migration docs with debug port solution and also link to the #release-0_8_0 slack channel.
=> fix(NoCode): Update migration docs with debug port solution

docker/datahub-upgrade/env/docker.env
=> fix(datahub-upgrade): Fixing misspelled schema registry title

docker/docker-compose.dev.yml
=> fix(docker): use debug tag in local dev images

docker/datahub-ingestion/Dockerfile, metadata-ingestion/setup.py
=> fix(ingest): exclude mssql-odbc from "all" extra

.github/workflows/docker-datahub-upgrade.yml, .github/workflows/docker-elasticsearch-setup.yml, .github/workflows/docker-frontend-react.yml, .github/workflows/docker-gms.yml, .github/workflows/docker-ingestion.yml, .github/workflows/docker-kafka-setup.yml, .github/workflows/docker-mae-consumer.yml, .github/workflows/docker-mce-consumer.yml
=> build(docker): test docker builds in pull request CI

datahub-frontend/app/react/controllers/TrackingController.java, datahub-frontend/conf/application.conf
=> fix(analytics): Support sasl authentication to kafka

datahub-kubernetes/datahub/Chart.yaml, datahub-kubernetes/datahub/README.md, datahub-kubernetes/datahub/charts/datahub-frontend/README.md, datahub-kubernetes/datahub/charts/datahub-frontend/values.yaml, datahub-kubernetes/datahub/charts/datahub-gms/README.md, datahub-kubernetes/datahub/charts/datahub-gms/values.yaml, datahub-kubernetes/datahub/charts/datahub-ingestion-cron/README.md, datahub-kubernetes/datahub/charts/datahub-ingestion-cron/values.yaml, datahub-kubernetes/datahub/charts/datahub-mae-consumer/README.md, datahub-kubernetes/datahub/charts/datahub-mae-consumer/values.yaml, datahub-kubernetes/datahub/charts/datahub-mce-consumer/README.md, datahub-kubernetes/datahub/charts/datahub-mce-consumer/values.yaml, datahub-kubernetes/datahub/quickstart-values.yaml, datahub-kubernetes/datahub/values.yaml
=> feat(k8s): Update version for helm chart

docs/modeling/extending-the-metadata-model.md
=> fix(docs): fixing type in no code documentation

docker/docker-compose.consumers.yml, docker/docker-compose.ember.yml, docker/docker-compose.graphql-service.yml, docker/docker-compose.yml, docker/ingestion/docker-compose.yml, docker/quickstart/docker-compose.quickstart.yml
Update docker-compose tags to head which point to the latest images after the NoCode change.
=> fix(docker): Update tags to head

metadata-ingestion/src/datahub/ingestion/source/lookml.py, metadata-ingestion/tests/integration/lookml/expected_output.json
=> fix(ingest): Patch lookml platform URN

metadata-ingestion/tests/test_helpers/docker_helpers.py
=> feat(ingest): print Docker logs on timeout

metadata-ingestion/tests/integration/feast/docker-compose.yml
=> Increase wait-for-it timeout

metadata-ingestion/src/datahub/cli/docker.py
=> Remove Orphans CLI Quickstart

metadata-ingestion/scripts/datahub_docker.sh
=> fix(docker): use head tag for datahub-ingestion image

datahub-web-react/src/app/entity/dataFlow/profile/__tests__/DataFlowProfile.test.tsx, datahub-web-react/src/app/shared/tags/AddTagModal.tsx, datahub-web-react/src/utils/sort/topologicalSort.ts
=> fix(react): reverse result of topological sort, autofocus in add tag modal

build.gradle, datahub-frontend/play.gradle, docker/quickstart/docker-compose.quickstart.yml, gms/impl/build.gradle, metadata-events/mxe-avro-1.7/build.gradle
Fix critical dependency vulnerabilities found by using https://github.com/aquasecurity/trivy
=> fix(docker): Fix dependency vulnerability

metadata-ingestion/README.md
=> docs(ingest): move usage stats docs into the "sources" section

datahub-web-react/src/app/entity/dataset/profile/DatasetHeader.tsx
=> fix(react): update the query frequency text label

datahub-frontend/app/react/controllers/GraphQLController.java, datahub-frontend/conf/logback.xml, datahub-frontend/run/logback.xml, gms/impl/src/main/java/com/linkedin/metadata/filter/LoggingFilter.java, gms/impl/src/main/java/com/linkedin/metadata/resources/lineage/Relationships.java, gms/war/src/main/resources/logback.xml
1 commit missed in previous logging PR.
=> feat(logs): add thresholding, misc cleanup

docs-website/package.json, docs-website/yarn.lock, metadata-ingestion/README.md, metadata-ingestion/developing.md
Also will include the fix for https://github.com/facebook/docusaurus/issues/4781.
=> docs: upgrade docusaurus + minor ingestion updates

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/mongodb.py
=> feat(ingest) add non-random sampling for mongo

build.gradle, datahub-frontend/play.gradle
Vulnerability issue was reported on 4.1.41 version.
=> fix(docker): Upgrade to 4.1.44 netty-all library

metadata-ingestion/README.md
=> fix(docs): links to Feast entities

datahub-kubernetes/datahub/README.md, datahub-kubernetes/datahub/charts/datahub-frontend/README.md, datahub-kubernetes/datahub/charts/datahub-frontend/values.yaml, datahub-kubernetes/datahub/charts/datahub-gms/README.md, datahub-kubernetes/datahub/charts/datahub-gms/values.yaml, datahub-kubernetes/datahub/charts/datahub-ingestion-cron/README.md, datahub-kubernetes/datahub/charts/datahub-ingestion-cron/values.yaml, datahub-kubernetes/datahub/charts/datahub-mae-consumer/README.md, datahub-kubernetes/datahub/charts/datahub-mae-consumer/values.yaml, datahub-kubernetes/datahub/charts/datahub-mce-consumer/README.md, datahub-kubernetes/datahub/charts/datahub-mce-consumer/values.yaml, datahub-kubernetes/datahub/quickstart-values-without-neo4j.yaml, datahub-kubernetes/datahub/quickstart-values.yaml, datahub-kubernetes/datahub/values.yaml
=> feat(k8s): Upgrade to v0.8.4

metadata-ingestion/src/datahub/cli/check_cli.py, metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/src/datahub/ingestion/source/feast.py, metadata-ingestion/src/datahub/ingestion/source/file.py, metadata-ingestion/src/datahub/ingestion/source/glue.py, metadata-ingestion/src/datahub/ingestion/source/kafka.py, metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py, metadata-ingestion/src/datahub/ingestion/source/ldap.py, metadata-ingestion/src/datahub/ingestion/source/looker.py, metadata-ingestion/src/datahub/ingestion/source/lookml.py, metadata-ingestion/src/datahub/ingestion/source/metadata_common.py, metadata-ingestion/src/datahub/ingestion/source/mongodb.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py, metadata-ingestion/src/datahub/ingestion/source/superset.py, metadata-ingestion/src/datahub/integrations/airflow/__init__.py, metadata-ingestion/src/datahub/integrations/airflow/entities.py, metadata-ingestion/src/datahub/integrations/airflow/hooks.py, metadata-ingestion/src/datahub/integrations/airflow/operators.py, metadata-ingestion/tests/unit/test_pipeline.py
=> refactor(ingest): remove deprecated methods and warn on deprecated import

metadata-io/src/main/java/com/linkedin/metadata/usage/elasticsearch/ElasticUsageService.java
=> fix(usage-stats): Add indices target for usage stats query

metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> fix(ingest): handle case when view definition handler is not implemented

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/hive.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py
Stacked on top of #2796, so merge that first.
=> fix(ingest): quote table names in hive

metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java
=> fix(usage-stats): Add usage stats factory to mae processor config

README.md, docs-website/sidebars.js
=> docs(website): hide outdated FAQs page

metadata-ingestion/scripts/update_golden_files.sh, metadata-ingestion/src/datahub/ingestion/source/sagemaker.py, metadata-ingestion/tests/conftest.py, metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py, metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json, metadata-ingestion/tests/integration/dbt/test_dbt.py, metadata-ingestion/tests/integration/feast/test_feast.py, metadata-ingestion/tests/integration/ldap/test_ldap.py, metadata-ingestion/tests/integration/looker/expected_output.json, metadata-ingestion/tests/integration/looker/test_looker.py, metadata-ingestion/tests/integration/lookml/expected_output.json, metadata-ingestion/tests/integration/lookml/test_lookml.py, metadata-ingestion/tests/integration/mongodb/test_mongodb.py, metadata-ingestion/tests/integration/mysql/test_mysql.py, metadata-ingestion/tests/integration/sql_server/test_sql_server.py, metadata-ingestion/tests/test_helpers/mce_helpers.py, metadata-ingestion/tests/test_helpers/type_helpers.py, metadata-ingestion/tests/unit/sagemaker/test_sagemaker_source.py, metadata-ingestion/tests/unit/serde/test_serde.py, metadata-ingestion/tests/unit/test_glue_source.py, metadata-ingestion/tests/unit/test_mce_helpers.py
Also improves the precision of the timestamps for a couple of the tests, and refactors the ignore paths setup.
=> feat(ingest): refactor mce comparison and add pytest update golden files option

datahub-kubernetes/datahub/Chart.yaml
Upgrade helm chart version to match release
=> fix(k8s): Upgrade helm version

metadata-ingestion/README.md
=> docs(ingest): add extra info for Redshift behind a proxy

docs/debugging.md
=> docs(docker): fix debugging check command reference

metadata-ingestion/README.md, metadata-ingestion/src/datahub/entrypoints.py, metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> fix(ingest): mask password in info-level logs

metadata-ingestion/README.md
=> docs(ingest): clarify that the Kafka options are pass-through

metadata-ingestion/src/datahub/ingestion/source/dbt.py
=> fix(ingest): do not fail when encountering missing nodes

datahub-frontend/app/react/analytics/AnalyticsService.java, datahub-frontend/app/react/analytics/AnalyticsServiceModule.java, datahub-frontend/app/react/controllers/TrackingController.java, datahub-frontend/app/utils/ConfigUtil.java, datahub-frontend/conf/application.conf, datahub-kubernetes/datahub/charts/datahub-frontend/templates/deployment.yaml, docker/elasticsearch-setup/create-indices.sh, gms/impl/src/main/resources/index/usage-event/aws_es_index_template.json, gms/impl/src/main/resources/index/usage-event/aws_es_ism_policy.json, gms/impl/src/main/resources/index/usage-event/index_template.json
Fix SSL issue with analytics on frontend and allow adding index prefix to the analytics index. 
- Cleaned up old elasticsearch setup in the meantime
=> fix(analytics): Fix SSL issue with analytics on frontend

docs-website/generateDocsDir.ts, docs-website/package.json, docs-website/yarn.lock
=> feat(docs): throttle and retry requests in doc generation

metadata-ingestion/build.gradle
=> fix(ingest): delete pycache files when running clean

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/aspect/AspectType.java
=> fix(lint): fixing lint issue in AspectType

gradle.properties
We've had some build flakes because of this issue (e.g. https://github.com/linkedin/datahub/runs/3024420085 and https://github.com/linkedin/datahub/runs/3049435956) - hoping this will resolve some of those issues.
=> build: increase retries for dependency fetches

docker/docker-compose-without-neo4j.yml, docker/quickstart/docker-compose-without-neo4j.quickstart.yml, docker/quickstart/docker-compose.quickstart.yml, docker/quickstart/generate_docker_quickstart.py
Also update the defaults to point at the head tag instead of latest.
=> fix(quickstart): update compose spec version

metadata-ingestion/scripts/release.sh
=> build(ingestion): add version prompt to release script

datahub-web-react/src/app/entity/shared/DescriptionModal.tsx
=> fix(react): fix bug in description update modal

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UrnToEntityMapper.java, datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
=> (fix) enable searching of business glossary 

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/druid.py, metadata-ingestion/tests/unit/test_druid_source.py
=> fix(ingest): fix druid misconfiguration bug

README.md
Removing eval - POC section of adoption as it is hard to keep accurate, adding DefinedCrowd
=> docs: revamp adoption section

docs/how/auth/sso/configure-oidc-react-google.md, docs/modeling/metadata-model.md
As reported by some folks from the community.
=> fix(docs): Misc doc fixes

metadata-ingestion/src/datahub/ingestion/source/dbt.py
=> fix(ingest): stringify dbt custom props

README.md, docs/townhall-history.md, docs/townhalls.md
=> docs: update docs for July townhall

metadata-ingestion/src/datahub/ingestion/source/looker.py
=> feat(ingest): add connectivity check for Looker

metadata-ingestion/setup.cfg, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/tests/unit/test_mce_builder.py
Also tightens the mypy ignore regex.
=> feat(ingest): add `can_add_aspect` method for MCEs

metadata-ingestion/src/datahub/ingestion/source/sql_common.py
=> fix(ingestion): issue a warning if the column list is empty

metadata-ingestion/src/datahub/ingestion/source/dbt.py
=> fix(ingest): stringify all dbt custom props

metadata-ingestion/examples/recipes/dbt_to_datahub.yml, metadata-ingestion/tests/integration/dbt/dbt_catalog.json, metadata-ingestion/tests/integration/dbt/dbt_manifest.json, metadata-ingestion/tests/integration/dbt/dbt_mces_golden.json
=> fix(ingest): update dbt test input and example recipe

metadata-ingestion/setup.cfg, metadata-ingestion/src/datahub/ingestion/api/registry.py, metadata-ingestion/src/datahub/ingestion/source/oracle.py, metadata-ingestion/tests/unit/test_oracle_source.py
=> feat(ingest): add support for Oracle spatial types

metadata-ingestion/README.md, metadata-ingestion/setup.cfg, metadata-ingestion/src/datahub/ingestion/source/bigquery_usage.py, metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py
=> feat(ingestion): support multiple project IDs in bigquery usage stats

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/athena.py
=> fix(ingest): note that views are not supported for Athena

docs/how/restore-indices.md
=> docs: update docs for consistency in naming

metadata-ingestion/examples/recipes/secured_kafka.yml
=> fix(ingestion): add quotes to secured kafka yaml config example

datahub-web-react/src/app/entity/chart/ChartEntity.tsx, datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx, datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx, datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx, datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/graphql/search.graphql
=> feat(react): show up edited descriptions on preview for entities

metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/tests/unit/sagemaker/sagemaker_mces_golden.json
Also fixes the sagemaker test that was previously using this incorrectly.
=> feat(ingestion): add `make_data_platform_urn` method to builder

metadata-ingestion/README.md
=> docs(ingestion): update looker + docker script docs

metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/feature_groups.py, metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/jobs.py, metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/models.py, metadata-ingestion/tests/unit/sagemaker/sagemaker_mces_golden.json
=> fix(ingest): fix SageMaker ownership URNs and browsepaths

metadata-ingestion/src/datahub/ingestion/source/glue.py
For the suggestion in https://github.com/linkedin/datahub/pull/2930
=> refactor(ingest): make code pythonic

metadata-ingestion/README.md, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/ingestion/source/looker.py, metadata-ingestion/src/datahub/ingestion/source/snowflake.py
This should have no behavioral changes other than the new log line. Hopefully this will help #2936.
=> feat(ingest): use urn builders in looker and validate data platforms

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/snowflake.py
=> fix(ingestion): make snowflake database names lowercase

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/lookml.py
=> fix(ingestion): handle backticks in lookml properly

metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/tests/unit/test_airflow.py
=> fix(ingestion): resolve test bugs for Python 3.6

metadata-ingestion/scripts/release.sh, metadata-ingestion/tests/unit/test_packaging.py
Moving into the release process rather than the build/test system.
=> test(ingestion): fix flaky package discovery test

metadata-ingestion/src/datahub/emitter/rest_emitter.py, metadata-ingestion/src/datahub/ingestion/sink/datahub_rest.py
=> feat(ingestion): test GMS connections before ingestion

metadata-ingestion/setup.cfg, metadata-ingestion/src/datahub/cli/docker.py, metadata-ingestion/src/datahub/cli/docker_check.py, metadata-ingestion/src/datahub/configuration/common.py, metadata-ingestion/src/datahub/configuration/import_resolver.py, metadata-ingestion/src/datahub/ingestion/api/closeable.py, metadata-ingestion/src/datahub/ingestion/api/registry.py, metadata-ingestion/src/datahub/ingestion/api/sink.py, metadata-ingestion/src/datahub/ingestion/api/workunit.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Ratcheting the strictness of mypy just a bit tighter.
=> fix(ingestion): add more mypy annotations

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
Reverts linkedin/datahub#2947
This is causing performance issues- reverting while improving perf
=> Revert "fix(gql): removing data platform caching in gql"

metadata-ingestion/README.md, metadata-ingestion/src/datahub_provider/example_dags/lineage_backend_taskflow_demo.py, metadata-ingestion/tests/unit/test_airflow.py
=> feat(ingest): add Airflow TaskFlow example

.github/workflows/build-and-test.yml, metadata-ingestion/build.gradle, metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/tests/unit/test_airflow.py, metadata-ingestion/tox.ini
=> text(ingestion): test multiple python versions in CI

docs/deploy/aws.md, gms/impl/src/main/resources/index/usage-event/aws_es_ism_policy.json
Description is required in index state management policy. 
Also updated docs for using AWS ES.
=> fix(elasticsearch-setup) Fix elasticsearch setup for AWS ES

metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py, metadata-ingestion/tests/integration/bigquery-usage/test_bigquery_usage.py
=> fix(ingestion): add timezone validation to usage collectors

metadata-ingestion/README.md, metadata-ingestion/src/datahub/ingestion/source/sql/hive.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py, metadata-ingestion/tests/integration/hive/hive_mces_golden.json, metadata-ingestion/tests/integration/hive/hive_setup.sql, metadata-ingestion/tests/integration/hive/hive_to_file.yml, metadata-ingestion/tests/unit/test_hive_source.py
=> fix(ingestion): fix hive database ingestion recipe

metadata-ingestion/tox.ini
=> test(ingestion): run full tests on both python versions

docs-website/sidebars.js, docs/how/extract-container-logs.md
Title says it! Adding a doc on how to extract the container logs written by datahub backend and frontend servers
=> docs(logs): How to Extract Logs from DataHub Containers doc 

metadata-ingestion/README.md
added escape character to snowflake recipe
=> updated README.md

docker/datahub-upgrade/Dockerfile, docker/datahub-upgrade/env/docker-without-neo4j.env, docker/datahub-upgrade/env/docker.env
Added config path in the Timeseries PR. Adding it to upgrade image as well.
=> fix(upgrade): Add config path to upgrade

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataplatform/DataPlatformType.java
=> fix(CI): Using AspectExtractor instead of removed SnapshotToAspectMap

metadata-dao-impl/kafka-producer/src/main/java/com/linkedin/metadata/dao/producer/EntityKafkaMetadataEventProducer.java
We've seen issues with silent failures producing to Kafka. This PR should fix these issues by logging results of kafka emission.
=> fix(logs): Fix silent kafka producer with logs. 

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
=> fix(ingest): don't assume Glue job description always exists

datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx, gms/impl/src/main/java/com/linkedin/metadata/resources/ResourceUtils.java, gms/impl/src/test/java/com/linkedin/metadata/resources/ResourceUtilsTest.java, metadata-io/src/main/java/com/linkedin/metadata/extractor/AspectExtractor.java
Title says it. Thanks to Shirshanka for pointing this out! Also adding some unis for good measure.
=> fix(gms): Validate unrecognized model fields.

metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
=> fix(ingest): type mappings for dbt BigQuery

metadata-ingestion/src/datahub/ingestion/source/lookml.py
=> fix(ingest): remove backticks from LookML tables and views

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
=> fix(ingest): detect malformed Glue S3 script paths

gms/client/src/main/java/com/linkedin/entity/client/EntityClient.java
Remove the potential for ClassCastException when calling GMS.
=> fix(frontend): Fix exception casting in EntityClient

datahub-frontend/app/react/controllers/TrackingController.java, datahub-frontend/conf/application.conf
=> feat: Add SASL_KERBEROS_SERVICE_NAME & SASL_PLAINTEXT support

datahub-web-react/src/app/entity/dashboard/profile/DashboardHeader.tsx
=> fix(dashboards): hide dashboard date when null

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/chart/mappers/ChartSnapshotMapper.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dashboard/mappers/DashboardSnapshotMapper.java
- fixes logical bug in dashboard mapper
- also support fallback logic so externalUrl is prioritized by chartUrl and dashboardUrl can provide backup.
=> fix(external url): fixing external url logic in charts and dashboard mapper

gms/README.md
Add example CURLs for adding a new tag and adding a tag to existing entity.
=> docs: Add tags GMS API documentation

metadata-ingestion/setup.cfg, metadata-ingestion/setup.py, metadata-ingestion/src/datahub/configuration/__init__.py, metadata-ingestion/src/datahub/configuration/toml.py, metadata-ingestion/src/datahub/ingestion/api/__init__.py, metadata-ingestion/src/datahub/ingestion/api/source.py, metadata-ingestion/src/datahub/ingestion/api/transform.py, metadata-ingestion/src/datahub/ingestion/extractor/extractor_registry.py, metadata-ingestion/src/datahub/ingestion/source/kafka.py, metadata-ingestion/src/datahub/ingestion/source/sql/athena.py, metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py, metadata-ingestion/src/datahub/ingestion/source/sql/druid.py, metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py, metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py, metadata-ingestion/src/datahub/ingestion/source/sql/oracle.py, metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py, metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_generic.py
=> feat(ingest): replace and warn against relative imports

datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx, gms/README.md
Title says it. Just adding some more CURL examples.
=> docs: Add Exact match search CURL example. 

metadata-ingestion/developing.md
=> fix(docs): update meta ingestion dev guide

metadata-ingestion/src/datahub/ingestion/source/looker.py, metadata-ingestion/src/datahub/metadata/schema.avsc, metadata-ingestion/src/datahub/metadata/schemas/MetadataChangeEvent.avsc, metadata-ingestion/tests/integration/looker/expected_output.json
=> fix(looker-ingestion): stop looker source from unnecessarily filling out owners

metadata-ingestion/README.md, metadata-ingestion/examples/recipes/dbt_to_datahub.yml, metadata-ingestion/examples/recipes/example_to_datahub_kafka.yml, metadata-ingestion/examples/recipes/example_to_datahub_rest.yml, metadata-ingestion/examples/recipes/example_to_datahub_rest2.yml, metadata-ingestion/examples/recipes/feast_to_datahub.yml, metadata-ingestion/examples/recipes/file_to_console.yml, metadata-ingestion/examples/recipes/file_to_datahub.yml, metadata-ingestion/examples/recipes/file_to_datahub_rest.yml, metadata-ingestion/examples/recipes/file_to_file.yml, metadata-ingestion/examples/recipes/glue_to_datahub.yml, metadata-ingestion/examples/recipes/ingest.yaml, metadata-ingestion/examples/recipes/kafka_connect_to_datahub_rest.yml, metadata-ingestion/examples/recipes/kafka_to_console.toml, metadata-ingestion/examples/recipes/kafka_to_console.yml, metadata-ingestion/examples/recipes/kafka_to_datahub.yml, metadata-ingestion/examples/recipes/kafka_to_datahub_rest.yml, metadata-ingestion/examples/recipes/ldap_to_console.yml, metadata-ingestion/examples/recipes/mongodb_to_datahub.yml, metadata-ingestion/examples/recipes/mssql_to_console.yml, metadata-ingestion/examples/recipes/mssql_to_datahub.yml, metadata-ingestion/examples/recipes/mysql_to_datahub.yml, metadata-ingestion/examples/recipes/sagemaker_to_datahub.yml, metadata-ingestion/examples/recipes/secured_kafka.yml, metadata-ingestion/examples/recipes/superset_to_rest.yml, metadata-ingestion/source_docs/sagemaker.md
=> feat(docs): link to docs from recipes

docs-website/sidebars.js
=> feat(docs): link to ingestion quickstart under ingestion section

docs-website/docusaurus.config.js, docs-website/src/css/custom.css, docs-website/src/pages/index.js, docs-website/src/pages/styles.module.css
=> feat(docs): reorder and restyle navbar

metadata-ingestion/examples/mce_files/bootstrap_mce.json
=> fix(ingest): clear tags in bootstrap_mce.json

docker/elasticsearch-setup/Dockerfile, docker/kafka-setup/Dockerfile, docker/mysql-setup/Dockerfile
=> fix(vulnerability): Upgrade base image version for setup jobs

metadata-ingestion/setup.py
=> fix(ingest): sqlalchemy-snowflake dependency constraint

README.md, docs/townhall-history.md, docs/townhalls.md
=> docs: Update Aug town-hall dates and previous town-hall details

datahub-web-react/src/app/entity/dataset/profile/schema/utils/schemaTitleRenderer.tsx
=> fix(schema): bolding field name if single token

.github/workflows/docker-mysql-setup.yml, .github/workflows/docker-postgres-setup.yml, docker/postgres-setup/Dockerfile
=> feat(workflow): Add mysql/postgres setup workflow

docker/mysql-setup/init.sql, docker/mysql/init.sql, smoke-test/sample_bq_data.json
=> fix(mysql-setup): Change default charset to utf8mb4

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/UpgradeCliApplication.java, metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java
=> fix(upgrade): Fix MAE consumer and upgrade's dependency issue

gms/api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json, gms/api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json, gms/api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json, gms/api/src/main/snapshot/com.linkedin.glossary.glossaryTerms.snapshot.json, metadata-ingestion/src/datahub/metadata/com/linkedin/pegasus2avro/glossary/__init__.py, metadata-ingestion/src/datahub/metadata/schema_classes.py, metadata-models/src/main/pegasus/com/linkedin/glossary/GlossaryRelatedTerms.pdl, metadata-models/src/main/pegasus/com/linkedin/glossary/GlossaryTermInfo.pdl, metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/GlossaryTermAspect.pdl
=> (feat)(Business Glossary) Glossary term relationship backend

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/glossary/mappers/GlossaryTermInfoMapper.java, datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTerms.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTermsResult.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryTermHeader.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryTermProfile.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/SchemaView.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/__tests__/GlossaryRelatedTerms.test.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx, datahub-web-react/src/app/shared/RoutedTabs.tsx, datahub-web-react/src/graphql/glossaryTerm.graphql
=> (feat)(Business Glossary) Business glossary relationship UI

metadata-ingestion/src/datahub_provider/_lineage_core.py
=> fix(airflow): only emit specific keys for airflow lineage properties

datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
=> fix(glossary): Make terms searchable and browseable

metadata-ingestion/setup.py
=> deps(pyhive): upgrade to pick up pyhive changes

datahub-web-react/src/app/entity/glossaryTerm/preview/Preview.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/GlossaryRelatedTerms.tsx, datahub-web-react/src/app/entity/glossaryTerm/profile/__tests__/GlossaryRelatedTerms.test.tsx
=> (fix)(Business Glossary) Business glossary visual changes

metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserEditableInfo.pdl
=> fix(frontend):Fixing broken link to default avatar

datahub-gms-graphql-service/README.md, docker/mariadb/init.sql, docker/mysql-setup/init.sql, docker/mysql/init.sql, docker/postgres-setup/init.sql, docker/postgres/init.sql, docker/quickstart/mysql/init.sql, metadata-ingestion/tests/integration/mysql/setup/setup.sql, metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserEditableInfo.pdl
=> fix(frontend): Replacing broken link for default avatar

README.md, docs/townhall-history.md, docs/townhalls.md
=> docs: update Aug townhall details and announce Sep townhall

metadata-ingestion/source_docs/mssql.md
=> fix(doc): add use_odbc to mssql doc example

metadata-ingestion/source_docs/hive.md
=> docs(ingestion): updated hive ingestion docs with Databricks recipe

datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx, datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
removes placeholder background image from platform logo
=> fix(react): removing preview artifact from platform logo

metadata-ingestion-examples/common/src/main/java/com/linkedin/metadata/examples/configs/TopicConventionFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/TopicConventionFactory.java
Match all other cases of this env variable.
=> fix(kafka): Change env variable name for MCL_versioned to be consistent

metadata-ingestion/source_docs/dbt.md
- ~~Links to related issues (if applicable)~~
- ~~Tests for the changes have been added/updated (if applicable)~~
- ~~Docs related to the changes have been added/updated (if applicable)~~
=> docs: fix "data platforms" link in dbt.md

datahub-web-react/src/app/entity/dataset/profile/schema/utils/utils.ts
Fixes issue where some fields where spuriously grouped together.
=> fix(react): Fix the fieldPath grouping logic in the front-end

datahub-web-react/src/app/AdminConsole.tsx
=> style(): Pin the Control Center Menu Icon

datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
=> fix(react): fixing format of search snippets

metadata-ingestion-examples/common/src/main/java/com/linkedin/metadata/examples/configs/TopicConventionFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/TopicConventionFactory.java
=> fix(platform): fix kafka env name for MCL_timeseries

datahub-web-react/src/Mocks.tsx, datahub-web-react/src/app/entity/tag/TagProfile.tsx
It now includes tags applied to schema fields
=> fix(UI): Fix tag profile search module

metadata-ingestion/src/datahub/ingestion/source/looker.py, metadata-ingestion/src/datahub/metadata/schema.avsc, metadata-ingestion/src/datahub/metadata/schemas/MetadataChangeEvent.avsc
Some lint issues snuck into metadata-ingestion, not exactly sure how but possibly due to https://github.com/linkedin/datahub/pull/3211?
=> fix(metadata-ingestion): fixing lint issues

docker/datahub-ingestion/Dockerfile
=> fix(ingestion-docker) Specify setuptools version

datahub-web-react/src/app/entity/shared/containers/profile/sidebar/Ownership/AddOwnerModal.tsx
=> fix(ui): fix owner modal title

datahub-frontend/app/auth/ConfigUtil.java, datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java, datahub-frontend/app/auth/sso/oidc/OidcConfigs.java, datahub-frontend/app/auth/sso/oidc/OidcProvider.java, datahub-frontend/conf/application.conf
Add more oidc configs. Refactor some code to minimize number of code changes.
=> fix(oidc): Add more oidc config

metadata-io/src/main/java/com/linkedin/metadata/entity/AspectStorageValidationUtil.java
=> fix(upgrades): Check whether tables exist using findList

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py, metadata-ingestion/tests/unit/glue/glue_mces_golden.json
=> fix(ingest): add missing partition keys in schema for glue sources

docs/how/auth/sso/configure-oidc-react.md
Need to put quotes around true.
=> fix(oidc-docs): Fix OIDC doc

datahub-frontend/app/auth/sso/oidc/OidcProvider.java
This fixes a configuration bug for OIDC. 
Shoutout to Wan Chun Chen for catching this!!
=> fix(oidc): Fixing OIDC response type bug

README.md
=> chore(README): add banksalad to datahub adoption README.md

metadata-ingestion/src/datahub/ingestion/source/lookml.py, metadata-ingestion/tests/integration/lookml/expected_output.json, metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json, metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json, metadata-ingestion/tests/integration/lookml/lookml_mces_offline.json, metadata-ingestion/tests/integration/lookml/test_lookml.py
Fixes #3239 
Also adds checks for recursive includes
=> fix(ingest): making lookml recursive and nested includes work

datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/exception/DataHubDataFetcherExceptionHandler.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/exception/DataHubGraphQLErrorCode.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddTagResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/AddTermResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/LabelUtils.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/RemoveTagResolver.java, datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/mutate/RemoveTermResolver.java, datahub-graphql-core/src/main/resources/gms.graphql, datahub-web-react/src/app/shared/tags/AddTagTermModal.tsx, datahub-web-react/src/app/shared/tags/CreateTagModal.tsx, datahub-web-react/src/app/shared/tags/TagTermGroup.tsx, metadata-ingestion/examples/mce_files/bootstrap_mce.json, metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java, metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java, smoke-test/test_e2e.py
Adding validation that the term/tag exists, the resource exists and the subResource exists. Also the validates the tag/term, resource and subresource type are valid.
Tests add & remove tags+terms to entities and schema fields
=> feat(tags+terms): Adding write side validation and tests for add+remove API

metadata-ingestion/src/datahub/metadata/schema.avsc, metadata-ingestion/src/datahub/metadata/schema_classes.py, metadata-ingestion/src/datahub/metadata/schemas/MetadataChangeEvent.avsc
=> fix(ingestion): update gen files

metadata-ingestion/setup.py, metadata-ingestion/src/datahub/ingestion/source/usage/redshift_usage.py, metadata-ingestion/tests/integration/redshift-usage/redshift_usages_golden.json, metadata-ingestion/tests/integration/redshift-usage/test_redshift_usage.py, metadata-ingestion/tests/integration/redshift-usage/usage_events_history.json
- [] Docs related to the changes have been added/updated (if applicable)
=> feat(ingest): add usage stats for Redshift source

docker/airflow/local_airflow.md
=> fix(docs): patch link to Airflow Docker compose file

metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
=> fix(graphql): add ElasticSearch path prefix configuration

metadata-ingestion/src/datahub/ingestion/source/looker_common.py, metadata-ingestion/src/datahub/ingestion/source/lookml.py, metadata-ingestion/src/datahub/utilities/sql_parser.py, metadata-ingestion/tests/integration/lookml/expected_output.json, metadata-ingestion/tests/integration/lookml/lkml_samples/data.model.lkml, metadata-ingestion/tests/integration/lookml/lkml_samples/fragment_derived.view.lkml, metadata-ingestion/tests/integration/lookml/lkml_samples/liquid.view.lkml, metadata-ingestion/tests/integration/lookml/lookml_mces_api_bigquery.json, metadata-ingestion/tests/integration/lookml/lookml_mces_api_hive2.json, metadata-ingestion/tests/integration/lookml/lookml_mces_badsql_parser.json, metadata-ingestion/tests/integration/lookml/test_lookml.py
Mostly resilience to breakages in the current best-effort sql parsing.
=> fix(ingest): more robust error handling in lookml sql parsing

metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/tests/integration/dbt/dbt_manifest.json, metadata-ingestion/tests/integration/dbt/dbt_with_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_without_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/test_dbt.py
The ingestion for DBT didn't actually move the tags and neither the owner. The owner is set in DBT by setting the 
```
meta:
owner: some@owner.com
```
I haven't created an issue, hopefully this is something you think could be merged.
=> feat(dbt-ingestion): added tags and owner from dbt

README.md, docs/slack.md, docs/townhall-history.md, docs/townhalls.md
=> Docs: Update to Slack & Townhall details

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py, metadata-ingestion/src/datahub/utilities/perf_timer.py
=> refactor(profiler): add PerfTimer class and fix typos

docs/quickstart.md
- [x ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> docs: add path fix for 'command not found'

metadata-ingestion/transformers.md
- [ x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> Docs: nits

metadata-ingestion/source_docs/dbt.md, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json, metadata-ingestion/tests/integration/dbt/test_dbt.py
=> feat(dbt): Dbt enhancements - dbt nodes, lineage, subtype, etc.

docs/modeling/metadata-model.md
=> docs (Metadata Model): nits

docs/modeling/extending-the-metadata-model.md
- [x ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> docs: nits and added hyperlinks

docs/docker/development.md
=> (Docs) Updated troubleshooting tip

datahub-web-react/README.md
=> doc (React) Node 17 openssl change causes error

datahub-frontend/app/controllers/Application.java
Recently, [we've heard requests](https://datahubspace.slack.com/archives/CV2UVAPPG/p1635836607055200) to allow proxying to DataHub GMS via datahub-frontend proxy layer to reduce the surface area / endpoints that need to be exposed. 
The hope is that in the long term, this change can help reduce the surface area of DataHub. For now, users who want to hit GMS through frontend will need to provide the PLAY_SESSION session Cookie issued by datahub-frontend on UI login when issuing a query. In the near future we plan to revisit authentication to support header-based tokens (ie for service principal use cases) that will make the experience of querying GMS as well as the GraphQL API via the frontend server more usable. 
The specific logic mapping logic introduced is:
- …
=> feat(frontend): Proxy GMS API requests

metadata-ingestion/src/datahub/cli/delete_cli.py
=> fix(cli): fix name of cli arg

docker/datahub-frontend/Dockerfile, docker/datahub-gms/Dockerfile
=> fix(docker): fix multi-platform build for arm

metadata-ingestion/src/datahub/ingestion/extractor/schema_util.py, metadata-ingestion/tests/unit/test_schema_util.py
Allow graceful progression of ingestion in the event of an exception in AVRO schema conversion to mce fields.
=> fix(ingestion): Make AVRO schema parsing robust to exceptions.

metadata-ingestion/src/datahub/cli/docker.py
=> feat(cli): add support for m1 laptops during quickstart

metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_properties.py, metadata-ingestion/src/datahub/ingestion/transformer/transform_registry.py, metadata-ingestion/tests/unit/test_transform_dataset.py, metadata-ingestion/transformers.md
Propose to use a class instead of just a function to have a more explicit contract
=> feat(ingest): add transformer to add properties

.github/workflows/docker-frontend-react.yml
Disabling arm frontend build temporary
=> [fix] Disabling arm frontend build temporary

metadata-service/README.md
Small docs change for `com.linkedin.dashboard.TagProperties` to `com.linkedin.tag.TagProperties`
=> fix `com.linkedin.dashboard.TagProperties`

.github/workflows/docker-elasticsearch-setup.yml
=> fix(docker): create multiplatform docker build from elasticsearch-setup

metadata-ingestion/src/datahub/ingestion/source/usage/redshift_usage.py, metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py, metadata-ingestion/tests/integration/redshift-usage/redshift_usages_golden.json, metadata-ingestion/tests/integration/redshift-usage/usage_events_history.json
Do not append email_domain to redshift username if username is already an email address.
=> fix(ingestion, redshift-usage): Do not append email domain to the username if the username is already an email.

docs/modeling/metadata-model.md
=> docs: adding links to help with metadata model visualization and documentation

metadata-ingestion/src/datahub/cli/docker.py
Bug introduced in #3547 
Moving to more portable platform module.
=> fix(cli): m1 check breaks on windows

metadata-ingestion/scripts/release.sh
=> feat(ci): adding support for env variables in python release script

docs/deploy/aws.md
Add documentation on how to connect to custom ES instance when deploying from docker.
=> fix(docs): Add documentation on how to connect to custom ES instance.

docs-website/docusaurus.config.js, docs-website/src/pages/managed.js, docs-website/src/styles/global.scss
Adds new blog, feature request and roadmap links.
Bonus: fixes Hubspot form in dark mode.
=> Add docs nav links

metadata-ingestion/tests/test_helpers/mce_helpers.py, metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json, metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
=> feat(model): adding a field to capture unmodeled field level properties

docs-website/sidebars.js
=> fix(docs): Move transformers to be under metadata ingestion

docs-website/sidebars.js, docs/cli.md, docs/how/delete-metadata.md, metadata-ingestion/src/datahub/cli/cli_utils.py, metadata-ingestion/src/datahub/cli/delete_cli.py, metadata-ingestion/src/datahub/cli/get_cli.py, metadata-ingestion/src/datahub/cli/ingest_cli.py, metadata-ingestion/src/datahub/cli/put_cli.py, metadata-ingestion/src/datahub/entrypoints.py
=> feat(cli): adding a put command and docs

docs-website/docusaurus.config.js
=> fix(docs-website): fix incorrect managed url

metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py, metadata-ingestion/tests/integration/kafka-connect/kafka_connect_mces_golden.json, metadata-ingestion/tests/integration/kafka-connect/kafka_connect_to_file.yml, metadata-ingestion/tests/test_helpers/mce_helpers.py
=> fix(ingest): rectify platform urn in kafka connect source

docs/how/auth/sso/configure-oidc-react-okta.md
=> docs(okta): Added Okta Logout Settings

metadata-ingestion/source_docs/redshift.md
Doc for redshift usage ingestion
=> fix(redshift-usage): Add docs for redshift usage ingestion.

metadata-ingestion/tests/unit/test_schema_util.py
I'm only a casual convention commit message user, so please correct me if there's a better tag for something this trivial.
=> fix(tests): fix typo in test name

metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/MostPopularSource.java, metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/RecentlyViewedSource.java, metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java, metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
Fix issue with recently viewed and most popular recs not showing up when there are special characters in the user URN.
=> fix(recommendations): Fix issue with recently viewed and most popular recs not showing up

metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
Handling for special characters such as hyphen etc. in snowflake databases and schemas.
=> fix(ingestion): Handling for special characters in snowflake databases and schemas.

metadata-ingestion/source_docs/business_glossary.md
Adds documentation for the business glossary file format.
=> docs(business glossary): document the business glossary file format

metadata-ingestion/build.gradle, metadata-ingestion/developing.md
=> feat(build): adds support for incremental build in ingestion

metadata-ingestion/build.gradle, metadata-ingestion/scripts/datahub_preflight.sh
Preflight script for metadata ingestion setup on m1
=> feat(build): Preflight script for metadata ingestion setup on m1

docs-website/graphql/generateGraphQLSchema.sh
=> docs(graphql) Adding additional GraphQL docs

docker/postgres/README.md
=> docs: correct title of postgres gms

metadata-ingestion/src/datahub/cli/delete_cli.py
Fixes https://datahubspace.slack.com/archives/C029A3M079U/p1638355952078400
=> fix(cli): fix for deletion cli

docs-website/build.gradle, docs-website/sidebars.js
=> fix(docs): fix docs build on m1

metadata-ingestion/src/datahub/cli/ingest_cli.py, metadata-ingestion/src/datahub/ingestion/run/pipeline.py, metadata-ingestion/tests/integration/mysql/test_mysql.py
=> feat(ingest): add --strict-warnings option

metadata-ingestion/src/datahub/cli/cli_utils.py, metadata-ingestion/src/datahub/cli/delete_cli.py, metadata-ingestion/src/datahub/ingestion/source/sql/trino.py, metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
We used to drop the token when deleting by search. This should be propagated through when present.
=> feat(delete): support deleting by search w/ tokens

metadata-ingestion/source_docs/business_glossary.md
=> docs(business glossary): fix specification of the file

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py, metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py
=> refactor(profiling): clean up SQL query analysis

metadata-ingestion/src/datahub/ingestion/api/report.py, metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py, metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py, metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py
Changes are stacked on top of #3674, so merge that first.
=> feat(profiler): add query combiner report statistics

metadata-ingestion/src/datahub/cli/delete_cli.py
=> fix(ingest): refactor urn deletion

docker/dev-without-neo4j.sh, docker/docker-compose.m1.yml
=> fix(perf-test): fix for M1

metadata-ingestion/examples/recipes/file_to_datahub_rest.yml
Introduced in https://github.com/linkedin/datahub/commit/1d7ec8dba84ab7a62b96b894ef5847560bea8f70
=> fix(bootstrap): revert accidental change to file_to_datahub_rest.yml

metadata-ingestion/setup.py, metadata-ingestion/source_docs/redshift.md, metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py, metadata-ingestion/src/datahub/ingestion/source/sql/trino.py, metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py
Adds lineage integration to redshift source
=> feat(ingestion): Add lineage support for Redshift source

docker/airflow/local_airflow.md
=> docs(airflow): add some troubleshooting for error

metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationSource.java, metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopPlatformsSource.java, metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTagsSource.java, metadata-io/src/main/java/com/linkedin/metadata/recommendation/candidatesource/TopTermsSource.java, metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java, metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java, metadata-io/src/test/java/com/linkedin/metadata/recommendation/candidatesource/EntitySearchAggregationCandidateSourceTest.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopPlatformsCandidateSourceFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTagsCandidateSourceFactory.java, metadata-service/factories/src/main/java/com/linkedin/gms/factory/recommendation/candidatesource/TopTermsCandidateSourceFactory.java
Also remove unused member variables for recs
=> fix(home): Change docs count to not count removed datasets

docs/cli.md
=> fix(doc): fixing doc in datahub cli for corpuser urn.

metadata-ingestion/source_docs/redshift.md
=> docs(redshift): Adding svv_table privilege requirement to redshift source doc

metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
=> fix(profiler): Fixing division by zero in pct_unique calculation

metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py
=> fix(ingest): get mysql geotypes properly

metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
=> fix(ingest): update trino source error handling in get_table_comment

metadata-ingestion/src/datahub/ingestion/source/usage/usage_common.py, metadata-ingestion/tests/unit/test_usage_common.py
Trim long sql queries in usage
- [x ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> feat(ingest) Trim long sql queries in usage

metadata-ingestion/src/datahub/ingestion/source/kafka.py
=> fix(ingest): add source.config.connection.schema_registry_config to SchemaRegistryClient creation

metadata-ingestion/src/datahub/ingestion/graph/client.py
Add methods to - 
1. get urns of an aspect.
2. get usage aspects of an urn.
=> feat(DataHubGraph): Adding utilities methods to DataHubGraph class.

metadata-ingestion/src/datahub/ingestion/source/superset.py
=> fix(superset): handle dashboards without charts (#3713)

docker/monitoring/grafana/dashboards/datahub_dashboard.json, docker/monitoring/prometheus.yaml, metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataAuditEventsProcessor.java, perf-test/locustfiles/ingest.py
=> feat(perf-test): changes for perf testing

docker/quickstart/docker-compose-without-neo4j.quickstart.yml, docker/quickstart/docker-compose.quickstart.yml
Regenerate quickstart compose files to fix CI breakage
=> fix(CI): Regenerate Docker Quickstart

metadata-ingestion/src/datahub/ingestion/graph/client.py
=> fix(DataHubGraph): changing datahub-graph to use underlying session connection.

metadata-ingestion/src/datahub/emitter/mce_builder.py
=> fix(ingest): Remove unecessary isalpha check for data platforms + warnings

metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
=> fix(ingestion): Skipping duplicate tables from ingestion

metadata-ingestion/setup.py
Responding to latest mypy 0.920 release.
=> build(ingest): restrict latest mypy version

README.md
Add IOMED as a company that has officially adopted DataHub.
=> doc: Add IOMED as a DataHub adopter

metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py
=> feat(profiler): add upper bound on combined query size

metadata-ingestion/README.md
=> docs(ingestion): Add details of sensitive info handling

metadata-ingestion/source_docs/bigquery.md, metadata-ingestion/source_docs/redshift.md, metadata-ingestion/source_docs/snowflake.md
Adding docs & examples about gaining the required privileges to use the Snowflake Metadata Extractor.
=> docs(snowflake): Adding documentation about required Snowflake Privileges 

metadata-dao-impl/kafka-producer/build.gradle, metadata-events/mxe-registration/build.gradle, metadata-events/mxe-utils-avro-1.7/build.gradle, metadata-ingestion-examples/common/build.gradle, metadata-ingestion-examples/kafka-etl/build.gradle, metadata-ingestion-examples/mce-cli/build.gradle, metadata-io/build.gradle, metadata-service/restli-servlet-impl/build.gradle, metadata-testing/metadata-models-test-utils/build.gradle, metadata-testing/metadata-test-utils/build.gradle, metadata-utils/build.gradle
Follow on from #3716 and #3755
=> Upgrade to 3rd Apache patch for log4j

docs-website/sidebars.js
Adding oidc guide to sidebars.js file for CI.
=> Add azure OIDC doc to sidebar

metadata-ingestion/src/datahub/ingestion/source/superset.py
Related to issue #3792
I didn't find a test suite for Superset, so I did not create a test case for this.  Let me know if I missed it.
=> fix(superset): fix Superset chart ingestion with an empty metric label

metadata-ingestion/source_docs/kafka.md
=> docs(kafka): add example for ingestion from confluent cloud

docs/modeling/metadata-model.md
Fix broken reference, file extension is required.
=> docs(fix): fix broken reference

docs/advanced/db-retention.md
=> Add table, changed formatting and wording

docs/deploy/confluent-cloud.md
=> docs(confluent): Add new topic names

datahub-web-react/src/app/shared/tags/AddTagTermModal.tsx
=> (feat)(glossary): Increase number of autocomplete results shown to 25

metadata-ingestion/setup.py, metadata-ingestion/source_docs/lookml.md, metadata-ingestion/source_docs/redash.md, metadata-ingestion/src/datahub/utilities/sql_parser.py, metadata-ingestion/src/datahub/utilities/sqllineage_patch.py, metadata-ingestion/tests/unit/test_redash_source.py, metadata-ingestion/tests/unit/test_utilities.py
=> feat(sql-parser): Replacing sqlmetadata sql parser lib with sqlineage parser lib

metadata-ingestion/source_docs/dbt.md, metadata-ingestion/src/datahub/emitter/mce_builder.py, metadata-ingestion/src/datahub/ingestion/graph/client.py, metadata-ingestion/src/datahub/ingestion/source/dbt.py, metadata-ingestion/src/datahub/utilities/mapping.py, metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_manifest.json, metadata-ingestion/tests/integration/dbt/dbt_with_external_metadata_files_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_with_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_without_schemas_mces_golden.json, metadata-ingestion/tests/integration/dbt/dbt_without_schemas_with_filter_mces_golden.json, metadata-ingestion/tests/integration/dbt/test_dbt.py, metadata-ingestion/tests/unit/test_dbt_source.py, metadata-ingestion/tests/unit/test_mapping.py
As seen in town-hall, support for mapping `dbt meta` concepts to add tags, owners etc.
=> feat(dbt-meta): add support for dbt meta mapping

metadata-ingestion/src/datahub/ingestion/source/metabase.py, metadata-ingestion/tests/integration/metabase/setup/card_2.json
Fixes the github [issue 3803]( https://github.com/linkedin/datahub/issues/3803).
=> fix(ingestion): Fix the datetime parsing issue in the metabase source.

datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocode/DataMigrationStep.java, docs/advanced/monitoring.md, metadata-io/build.gradle, metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java, metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java, metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanEntityService.java, metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java, metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestDataPlatformInstancesStep.java, metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestDataPlatformsStep.java, metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/IngestRootUserStep.java
=>  perf(ingest): changes to improve ingest performance a bit

metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
Related issues
- https://github.com/linkedin/datahub/issues/3583
=> fix(azure AD): fix problem with missing key causing failures in ingestion

docs/how/add-user-data.md
=> docs: fix typo

docs/cli.md
=> docs(cli): fix wrong heading, add link to release notes

.github/workflows/docker-ingestion.yml, docker/datahub-ingestion/Dockerfile, metadata-ingestion/src/datahub/__init__.py
=> build: include correct version in metadata-ingestion docker image

metadata-ingestion/src/datahub/ingestion/source/metabase.py
Fixes some hard crashes encountered when ingesting data from metabase.
=> fix(metabase): fix crashes on missing values

metadata-integration/java/datahub-client/scripts/check_jar.sh
=> fix(build): fix shadow jar checker to allow new git.properties

.github/workflows/docker-kafka-setup.yml
=> fix(github-workflow): Remove duplicate context in kafka setup workflow

docs/api/graphql/getting-started.md
=> docs: fix endpoint URL

metadata-ingestion/tests/test_helpers/click_helpers.py
=> fix(cli): disable telemetry in CLI tests

docs/api/graphql/querying-entities.md
=> doc(graphql): add some examples

repositories.gradle
=> fix(build): remove jcenter from gradle build

metadata-ingestion/source_docs/kafka.md
=> doc(kafka): add permissions required for confluent cloud

metadata-ingestion/src/datahub/utilities/sql_parser.py, metadata-ingestion/tests/unit/test_utilities.py
=> fix(ingest): sqlparser - Not lowercasing looker source's special table name

metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
=> feat(ingest): Support for spectrum external array types

.github/workflows/docker-ingestion.yml
=> fix(workflow) docker-ingestion is failing bc of an invalid sed command

metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
=> fix(glossary): owner should be optional as per docs

metadata-ingestion/src/datahub/ingestion/source/aws/glue.py, metadata-ingestion/src/datahub/ingestion/source/sql/hive.py, metadata-ingestion/src/datahub/utilities/hive_schema_to_avro.py, metadata-ingestion/tests/unit/glue/glue_mces_golden.json, metadata-ingestion/tests/unit/test_glue_source.py, metadata-ingestion/tests/unit/test_hive_source.py
Adds support for nested glue schemas.
Refactors existing Hive column to avro converter.
=> feat(ingestion): Support for nested glue schemas

metadata-ingestion/source_docs/elastic_search.md
'env = "prod" ' --> 'env: "PROD" '.
=> docs (elasticsearch): config error

metadata-ingestion/src/datahub/ingestion/source/nifi.py
=> fix(ingest): nifi - replace hardcode password with config variable

metadata-ingestion/src/datahub/ingestion/source/metadata/business_glossary.py
=> Revert "fix(glossary): owner should be optional as per docs (#3858)"

docs/modeling/extending-the-metadata-model.md
=> fix(typo): fix typo in docs

datahub-frontend/app/controllers/Application.java, metadata-ingestion/src/datahub/emitter/rest_emitter.py
=> feat(config): make check for frontend instead of gms more robust

metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/BulkListener.java, metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/elasticsearch/ElasticsearchConnector.java, metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java
=> fix(log): fix log levels and formats
